### ISSUE TITLE
Handling space in directory name

### ISSUE THREAD

**Issue by cjunekim** [IntellectualSites/FastAsyncWorldEdit#1006]
### Server Implementation

Paper

### Server Version

1.15.2

### Describe the bug

If there is a space in the directory name, //schematic list <directoryname> fails.

### To Reproduce

1. Create a schematic folder under your plugins\FastAsyncWorldEdit\schematics.
2. Set the directory name as "foo bar"
3. Click foo bar in orange
4. See //schematic list ..\foo bar/ is copied to the input line and hit enter
5. Also try //schematic list "..\foo bar/" and see it results NO files found.

### Expected behaviour

It should show the contents of the directory.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c77d321a7a4f4ce099ccf49b3527bf89

### Fawe Version

FastAsyncWorldEdit version 1.16-639;e40d3e3

### Checklist

I have included a Fawe debugpaste.
I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Folder names should not have spaces in their name under any circumstances. Use a proper file separator.
