### ISSUE TITLE
Terraform generator

### ISSUE THREAD

**Issue by anton3312578859** [IntellectualSites/FastAsyncWorldEdit#1007]
### What feature do you want to see added?

Add a terraform generator support pls

### Are there any alternatives?

use another generator

Error: Unsupported generator type org.terraform.v1_16_R3.NMSChunkGenerator

**Comment by NotMyFault** [comment]
Can you elaborate that please?

**Comment by anton3312578859** [comment]
no
link to this plugin: https://www.spigotmc.org/resources/terraformgenerator-alpha.75132/

**Comment by NotMyFault** [comment]
If you put no effort to explain what you are actually looking for, I'll put not effort into trying to understand you.

**Comment by anton3312578859** [comment]
fastasyncworldedit dont support terraform generator https://www.spigotmc.org/resources/terraformgenerator-alpha.75132/
sorry i am not english

**Comment by NotMyFault** [comment]
> fastasyncworldedit dont support terraform generator https://www.spigotmc.org/resources/terraformgenerator-alpha.75132/
> sorry i am not english

FAWE cannot support all plenty of custom terrain generation plugins out there. Ideally those would make use of the WorldEdit API to regenerate chunks instructing it with their own data.

**Comment by anton3312578859** [comment]
ok thx
