### ISSUE TITLE
Java 16 Support

### ISSUE THREAD

**Issue by Thommii** [IntellectualSites/FastAsyncWorldEdit#1014]
### What feature do you want to see added?

Can Java version 16 support be added? So far everything works under version 16, but there are always warnings in the console. No problems in-game, but not everything tested.
pos, set, replace no errors.

### Are there any alternatives?

The functions I tested also work in the current version. However, only a few tests so far.

**Comment by NotMyFault** [comment]
Reflections will be addressed once someone has the time for that.

**Comment by SirYwell** [comment]
See #396. In fact, you can use `--illegal-access=permit` or  `--add-opens` with the proper arguments to avoid issues for now.
