### ISSUE TITLE
When //set rail on a specific angle, it pastes it wrong.

### ISSUE THREAD

**Issue by mistershkolnik** [IntellectualSites/FastAsyncWorldEdit#1019]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

when setting the rails on a specific angle, it pastes it incorrectly, and have to manually fix it which is pretty annoying

### To Reproduce

1. set 2 positions in a straight line
2. //set rail
3. if works normally, try another angle
4. repeat the steps

### Expected behaviour

The rails should've been setted to every angle you set

### Screenshots / Videos

https://imgur.com/a/HY4yNbX

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9d23c194d0e449e68937c0f5f868a28f

### Fawe Version

1.16-651:4d77771

### Checklist

I have included a Fawe debugpaste.
I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
That is the correct behavior. To change the orientation of rails, apply a cardinal direction like `//set rails[shape=east_west]`.
