### ISSUE TITLE
//gmask causing FAWE to deadlock when a user joins the server

### ISSUE THREAD

**Issue by ShayPunter** [IntellectualSites/FastAsyncWorldEdit#1024]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Whenever our builder types in a specific gmask command FAWE stalls with no errors outputted.

### To Reproduce

1. //gmask /[0d][50d]
2. //br sphere 252:8 5
3. //mask 1
4. Have a user join the server while the brush is in use

FAWE should stall.

### Expected behaviour

For FAWE to not stall while using the brush.

### Screenshots / Videos

https://youtu.be/IeM7Q5U4YiE

### Error log (if applicable)

N/A, however here is the server log: https://haste.athion.net/ruhuyafopo.md

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/71a5642571044a61ba96e950bd27d8dc

### Fawe Version

FastAsyncWorldEdit version 1.16-656;64a0a1d

### Checklist

I have included a Fawe debugpaste.
I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by ShayPunter** [comment]
For additional diagnosing/debugging. ZIP file contains 2 exported deadlocks from YourKit and a log file of the process.
[YourKit Exports & Logs.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6292505/YourKit.Exports.Logs.zip)

**Comment by jewome62** [comment]
I confirm i have similar issue with gmask.
FAWE is stopped when someone use some gmask. impossible to use wand or something else.
And if the player disconnect, FAWE still running the blocked task (try to applied this gmask to infinite ?) and crash because of #749

**Comment by dordsor21** [comment]
Should be fixed by https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/f6af9925e8366ee7055a7dd95515c09021a152b4
