### ISSUE TITLE
Deadlock in chunk holder

### ISSUE THREAD

**Issue by RainbowDashLabs** [IntellectualSites/FastAsyncWorldEdit#1025]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I experienced Deadlocks in fawe for some time now.
The thread dump shows three deadlocks inside the chunk holder:
https://haste.athion.net/adilifurel.bash

FAWE died at 12:50 in our latest log.
https://haste.athion.net/gicotadabu.md

At this point nothing fawe related works anymore. 
No FAWE command responds in any way. I am not able to create a debugpaste nor seeing the basic fawe information with the /fawe command.

However I added a debugpaste after a server restart to provide the required meta information.

inb4 Youre not using the latest fawe version:
I know. Its hard to wait for a bug occurring every 24 hours or so. I try to update every few days. However the bug is common on our server for month now so I dont think a miracle will happen and it magically disappears. So I guess it will happen with all future builds currently as well.

### To Reproduce

The bug is kinda weird.
It is not reproducible in any way I can grantee that it works.
When using fawe at some point a deadlock occurs.
Our observation was that it is kinda reproducible when using different stencil setups and undo a few time or so. However It doesnt work anytime. Sometime it takes hours to get stuck and sometime only a few minutes.

### Expected behaviour

Not running into a deadlock I guess ¯\\\_(ツ)_/¯

### Fawe Debugpaste

 https://athion.net/ISPaster/paste/view/c752108ed6a449efa7ccbfcbddd5bc57

### Fawe Version

1.16-655;88764d8

### Checklist

I have included a Fawe debugpaste.
I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by Aurelien30000** [comment]
Confirmed on my side, nothing coherent in this issue :/ I'll try to investigate.

**Comment by jewome62** [comment]
Duplicate with #749 
Yes, this is a major problem currently on my server

**Comment by RainbowDashLabs** [comment]
I have another thread dump of this behavior.
First time:
https://chojos.lewds.de/wsZcOWLTWc.txt
Second time:
https://chojos.lewds.de/s9aVesbdvM.txt

This time we managed to get 5 and 4 deadlocks.
We also managed to find a way to reproduce this behavior on the latest fawe build.

```
/br sphere grass_block 20
/mask /[0d][45d]<7
//1
Play around with the brush for a bit.
```

The debugpaste from above is still valid. Fawe is to stuck to create a debugpaste atm.

**Comment by libraryaddict** [comment]
This has been an issue for a while now on my server, but didn't file a report as I was using a backported version of FAWE previously.

I strongly believe /u, which is undo, to be the main culprit. It's generally the last command seen..

**Comment by wellnesscookie** [comment]
I think this problem is the one I am experiencing atm as well, using latest Paper for 1.16.5 and version of fawe:

```
[18:09:41 INFO]: FastAsyncWorldEdit-695 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[18:09:41 INFO]: FAWE version:
 - Date May 24, 2021, 12:00:00 AM
 - Commit ffb9ef7e
 - Build 695
 - Platform Bukkit
```
It just freezees the server after a while. Sometimes minutes, sometimes hours. The chat is the only active thing working correctly.
Log: https://pastebin.com/4Ah7LM0L

We were unable to determine the steps to reproduce it, it just doesn't makes sense.
