### ISSUE TITLE
Excessive log files / errors crash the server

### ISSUE THREAD

**Issue by KateHutch** [IntellectualSites/FastAsyncWorldEdit#1028]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Over the past couple of months, we have had an intermittent issue where an occasional error in FAWE causes the hard drive to fill up completely (in excess of 300GB). I'm not aware of what specifically triggers this issue.

This error has been happening on the following versions:

- FastAsyncWorldEdit-1.16-616.jar
- FastAsyncWorldEdit-1.16-626.jar
- FastAsyncWorldEdit-1.16-648.jar

Due to the size of the log file I have not been able to access it, however I here is a link to a snippet of the error log: https://haste.athion.net/uhamaxotod.sql

### To Reproduce

I'm not actually sure what triggers this issue, nor the steps to reproduce it but I believe it's something like this:

1. Install FAWE on your server
2. Give 30 players access to FAWE on PlotSquared plots
3. Walk away for 24 hours
4. Return to a crashed server, a full HD, and corrupt files

### Expected behaviour

If FAWE encounters a "fatal error" it would be great if it could either forcefully stop whatever task it's doing.

### Error log (if applicable)

https://haste.athion.net/uhamaxotod.sql

### Fawe Debugpaste

N/A

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.16-648.jar

### Checklist

I have included a Fawe debugpaste.
I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/57773765d779efba76764188ec65ef3f45ca1977
