### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by ForceUpdate1** [IntellectualSites/FastAsyncWorldEdit#1033]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

High memory usage

### To Reproduce

Many players join and leave again

### Expected behaviour

No high memory usage 

### Screenshots / Videos

![img](https://i.imgur.com/QCOaqyi.png)
![img](https://i.imgur.com/wqoso8T.png)
![img](https://i.imgur.com/8EaosCk.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6f5d79afd77846a698f56f0f18723fd5

### Fawe Version

FastAsyncWorldEdit version 1.16-13;4c333e6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by SirYwell** [comment]
1.) While you're writing you're using Tuinity, the Debugpaste indicates you're using Paper.
2.) On the first two screenshots, there's basically nothing useful to see. Yes, FAWE allocates objects.
3.) The third screenshot shows us a sum of 3,984 bytes - that's no high memory usage.

If you want us to look into your issue, you actually need to provide consistent information and heap dump files instead of screenshots.

**Comment by ForceUpdate1** [comment]
![img](https://i.imgur.com/GOa0VwD.png)

https://athion.net/ISPaster/paste/view/f441579270c34415993ae8129f8f1814

We have accidentally used the wrong version. I thought we had Tuinity on it. But of course the issue exists on Tuinity as well. And I have only a part to see on the screenshots, because I thought that you can see that there is an issue. Due to the memory leak, some CraftPlayer and WorldServer instances cannot be collected on GC.

**Comment by LaurenceBarnes** [comment]
what would help a lot probably is a spark heapsummary

**Comment by ForceUpdate1** [comment]
https://spark.lucko.me/Q862vKLD3C

![img](https://i.imgur.com/WdRu6zR.png)

**Comment by SirYwell** [comment]
I'd prefer a heap dump that can be analyzed properly (in best case, you can provide a heap dump when *not* using FAWE too for comparison).
