### ISSUE TITLE
client side block updates

### ISSUE THREAD

**Issue by rudde0** [IntellectualSites/FastAsyncWorldEdit#1034]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

Blocks by created schematic system aren't updating on my client side so I need to update it via teleport so far or relog to the server to see changes.

### To Reproduce

1. //perf on
2. //perf neighbors off
3. Paste a schematic which >80kb (I'm not sure exact size but there is no problem with my 27kb schematic)

### Expected behaviour

block updates should send to client side

### Screenshots / Videos

https://imgur.com/a/K3itOhp

### Error log (if applicable)

https://paste.gg/p/anonymous/f978cc80bfda46b697e68bf720423978

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4041a0bbe4c04b17b9bb669ef487490d

### Fawe Version

FastAsyncWorldEdit version 1.16-666;ceacd7b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Try using this build https://ci.athion.net/job/FastAsyncWorldEdit-Starlight/

**Comment by rudde0** [comment]
> Try using this build https://ci.athion.net/job/FastAsyncWorldEdit-Starlight/
> 
> > <img alt="" width="48" src="/static/f3f33655/favicon.ico">**[FastAsyncWorldEdit-Starlight [Jenkins]](https://ci.athion.net/job/FastAsyncWorldEdit-Starlight/)**

thanks a lot!
