### ISSUE TITLE
Outdated Nashorn Engine

### ISSUE THREAD

**Issue by KolakZ** [IntellectualSites/FastAsyncWorldEdit#1036]
### What feature do you want to see added?

I keep getting this warning on startup and was wondering if FAWE could use a different engine.

[17:43:30 WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release

### Are there any alternatives?

Worldedit didn't have this issue.

### Anything else?

Thanks for all the hard work you do and keep it up!

**Comment by NotMyFault** [comment]
The nashorn scripting engine was deprecated since Java 11 and scheduled for removal within 15. If you are using a Java version equal or greater than 15, craftscripts, and the js.jar you downloaded, can no longer work.
