### ISSUE TITLE
PS: added player can use worldedit when owner offline

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#1037]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Added players on a PS plot can still use worldedit even if the plot owner is offline.

### To Reproduce

1. Add a player on a plot
2. Log off the owner off the plot
3. The other Player can still use WorldEdit (can't use axe to set 2 position, need to use `//pos2`)
4. Even after a restart the added player can still use WoeldEdit

### Expected behaviour

The player should not be able to use WorldEdit on the plot when the owner is offline.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/104bf9e2a4564aa5998e8b5d3d2424f0

### Fawe Version

FastAsyncWorldEdit version 1.16-666;ceacd7b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

Plotsquared Version: PlotSquared version 5.13.11-Premium

**Comment by Orlaando-dev** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/8b69d8a8e2eee74df81beb21cc0d8b250582d0c7/worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/regions/plotsquared/PlotSquaredFeature.java#L98

I believe just this line would need editing. Perhaps checking if the plot owner is online.

**Comment by NotMyFault** [comment]
@IntellectualSites/fawe-team We may need to discuss whether we want classify this as bug or long-standing usability change.
I wouldn't be opposed to change it, yet it may break a few workflows needing to be addressed separately.

**Comment by RedstoneFuture** [comment]
Added player can only build if the owner is online. And he can't never use worledit!

But forwarding this report this behavior has changed, so it's definitv  bug.


In difference trustet user can build and use worldedit anytime.

**Comment by RedstoneFuture** [comment]
Update: I've tested the report with the wrong permission (`fawe.plotsquared.member`) and thought the restriction problem was the bug. Sorry ... 

@NotMyFault Now I understand, what do you mean. Maybe it's a long time standing logic-issue. And maybe reparable with a new main-version number to increase the usability.
