### ISSUE TITLE
//undo does not change inventory of blocks

### ISSUE THREAD

**Issue by QuickWrite** [IntellectualSites/FastAsyncWorldEdit#1039]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When blocks are placed with any WorldEdit command and they have an inventory (like a chest) this inventory does not get changed with `//undo` and the containers still do have the Inventory.

### To Reproduce

1. Have a block with an inventory placed (like a dropper).
2. Copy, Stack another inventory Block (works best if the block is the same) with different items in the inventory over the other inventory block.
3. Do `//undo`.
4. Then the old block (in step 1) does contain the items of the other inventory block.

### Expected behaviour

When the `//undo` command is executed the inventory of the block should be the same as the old inventory.
When you have 3 Gold Ingots in it and it is overwritten with 6 Gold Nuggets it should change back to 3 Gold Ingots.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5f5527fd661d49e7bf62ac1cfad079f0

### Fawe Version

FastAsyncWorldEdit version 1.16-667;7e3525a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by PapiCapi** [comment]
I got an issue certainly related to thisbut with command blocks. 
Here is the record : https://youtu.be/xSbIus1kkek

**Comment by MattBDev** [comment]
So if I understand this issue correctly, //undo can duplicate the contents inside of any container block?

**Comment by QuickWrite** [comment]
> So if I understand this issue correctly, //undo can duplicate the contents inside of any container block?

Not quite. Undo does not change the data of a container to the data that were before the last edit.
When I have a container with `3 Iron Ingots` and `2 Grass Blocks` and then I am replacing that with WorldEdit with a container with `6 Bread` and `1 Gold Ingot` the container will still have `6 Bread` and `1 Gold Ingot` and not the `3 Iron Ingots` and `2 Grass Blocks` before that.

**Comment by PapiCapi** [comment]
If i remember well, this issue is already fixed by a more recent build

**Comment by dordsor21** [comment]
This does seem to be fixed.
