### ISSUE TITLE
Crash on huge changes

### ISSUE THREAD

**Issue by kacperleague9** [IntellectualSites/FastAsyncWorldEdit#1040]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

When i do massive changes, server hangs (starlight version)

### To Reproduce

1. For my scenario i used command //cyl netherrack 5000.
2. Check logs.

### Expected behaviour

It should generate blocks.

### Error log (if applicable)

https://paste.md-5.net/okavihaqov.css

### Fawe Debugpaste

I can't include this information

### Fawe Version

1.16-14;421a499

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Link a `/fawe debugpaste` and/or `/timings paste` or we will close the issue.

**Comment by NotMyFault** [comment]
The information requested has no been provided, closing issue due invalid template.
