### ISSUE TITLE
Block break queue creating ghost blocks

### ISSUE THREAD

**Issue by GC-spigot** [IntellectualSites/FastAsyncWorldEdit#1043]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Since ~2 months ago, FAWE started creating ghost blocks which disappear upon relogging.

We're using the FAWE block set queues:
```java
public static void breakBlocks(List<Block> blockList) {
        com.boydti.fawe.beta.IQueueExtent<com.boydti.fawe.beta.IQueueChunk> queue = com.boydti.fawe.FaweAPI.createQueue(com.boydti.fawe.FaweAPI.getWorld(blockList.get(0).getWorld().getName()), false);

        Block b = blockList.get(0);

        com.sk89q.worldedit.world.block.BlockState bs = com.boydti.fawe.FaweAPI.getWorld(b.getWorld().getName()).getBlock(b.getX(), b.getY(), b.getZ());
        for (Block block : blockList) {
            queue.setBlock(block.getX(), block.getY(), block.getZ(), bs);
        }

        queue.flush();
    }
```
Dont mind the debug link writing 1.16.3, was trying out all 1.16 versions and just haven't changed it back yet to latest

### To Reproduce

Use code above and ghost blocks appear

### Expected behaviour

Previously it used to set the blocks without causing ghost block issues

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/511aaa7c4f024bbd9452df8d943519b4

### Fawe Version

1.16-668;5dafa5f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Are you using the starlight build? https://ci.athion.net/job/FastAsyncWorldEdit-Starlight/
It's a build of a branch which covers that as well afaik.

**Comment by GC-spigot** [comment]
> Are you using the starlight build? https://ci.athion.net/job/FastAsyncWorldEdit-Starlight/
> It's a build of a branch which covers that as well afaik.
> 
> > <img alt="" width="48" src="/static/edc4a3cd/favicon.ico">**[FastAsyncWorldEdit-Starlight [Jenkins]](https://ci.athion.net/job/FastAsyncWorldEdit-Starlight/)**

Here is me trying it on latest Starlight build, latest PaperMC at the moment (Build 631):
(!)[https://i.imgur.com/DMBWSPl.gif](https://i.imgur.com/DMBWSPl.gif)

**Comment by LaurenceBarnes** [comment]
Would you mind testing it with Tuinity? Might be good to know whether it this bug restricted to Paper only.

**Comment by GC-spigot** [comment]
> Would you mind testing it with Tuinity? Might be good to know whether it this bug restricted to Paper only.

Sure, we do have over 100 people reporting the same issue in past ~2 months using various server integrations, not just paper. Will let you know the results

**Comment by GC-spigot** [comment]
> Would you mind testing it with Tuinity? Might be good to know whether it this bug restricted to Paper only.

Same issue: https://i.imgur.com/8zTNAPH.gif

**Comment by LaurenceBarnes** [comment]
well looks like at least the light updates seem to work :p
Hard to see due to the resolution. Otherwise, use /paper fixlight <radius> to solve that (it is really fast in Tuinity) or use the classical //fixlighting provided by FAWE, which at least works on Tuinity (I cannot account for Paper)

I hope that this issue with the ghost blocks can be solved though.
thanks!

**Comment by GC-spigot** [comment]
bump, this is affecting a lot of servers
