### ISSUE TITLE
Ability to disable waterlog operations

### ISSUE THREAD

**Issue by nikitushu2** [IntellectualSites/FastAsyncWorldEdit#1045]
### What feature do you want to see added?

A variable in the config: 

`waterlog: true/false`

The problem is that if you spawn sponges with waterlogged blocks, and then if you start breaking them, a lag occurs. Seemingly because the system tries calculating which block to drain.

The same problem is with `/p set floor sponge, stone_slab[waterlogged=true]` in Plotsquared, which uses FAWE too. So, canceling commands with the waterlogged argument is not a solution since other plugins may use FAWE to spawn sponges with waterlogged blocks. That's why a waterlog option should be built straight into FAWE's config.

### Are there any alternatives?

Canceling a command that uses the waterlogged argument (using separate addon for that), which is not the best solution as explained above.

**Comment by NotMyFault** [comment]
PlotSquared v5 has a configuration option to disallow blocks in the same way WorldEdit and Fawe do. Simply add yours there.
