### ISSUE TITLE
AbstractDelegateExtent broken with FAWE

### ISSUE THREAD

**Issue by FrankHeijden** [IntellectualSites/FastAsyncWorldEdit#1046]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

All of the following methods are not called in AbstractDelegateEvent when executing `//set dirt`:
`setBlock`,
`setBlocks`,
`replaceBlocks`

### To Reproduce

1. Download this:  [FaweExtentBug.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6411918/FaweExtentBug.zip)
2. Compile with `./gradlew clean build`
3. Or download the compiled plugin: [FaweExtentBug-1.0-SNAPSHOT.jar.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6411921/FaweExtentBug-1.0-SNAPSHOT.jar.zip)
4. Place into plugins folder
5. Execute `//set dirt`
6. Watch nothing being printed to the console, even though print statements are put for all methods

### Expected behaviour

At least one of the methods being called for said action.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b9cef9b04af84660b759e3a7338c49dd

### Fawe Version

1.16-668;5dafa5f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by Bullob** [comment]
Same problem for me. I need to cancel any manipulation (copy, set, cut, ...) executed on defined block types. The workaround with the AbstractDelegateEvent's methods works well with regular WorldEdit but not with FAWE

**Comment by SirYwell** [comment]
You need to add the name of the Extent (just the class name) to the `allowed-plugins` section in the FAWE config.yml. That should resolve the problem.

**Comment by SirYwell** [comment]
If `debug` is set to true, it should actually print a warning. At least that's what happening for me with the linked test plugin.

**Comment by Bullob** [comment]
Yeah, I turned debug true at the same time I added my custom extent (a bit useless but..). Maybe would it be better to set this setting to true by default?

**Comment by SirYwell** [comment]
It was true by default until @NotMyFault changed it, I don't know what the reasoning was at that point.

**Comment by NotMyFault** [comment]
_Certain_ logging plugins require to set this true, however, we may change this back now since we no longer support those via third party bridges but them can use the WorldEdit/Fawe API directly.

**Comment by KyGuy2002** [comment]
As of right now I was able to get it working only by adding “WorldEditExtent” to allowed-plugins.  Just my solution for other users having this issue
