### ISSUE TITLE
BeaconDeactivatedEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by LaurenceBarnes** [IntellectualSites/FastAsyncWorldEdit#1048]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

Not much to say, Beacons (activated beacons?) cannot be removed, they must be destroyed by hand.

EDIT: Perhaps check whether there are other similar things that should be triggered synchronously, can only make things more stable.

### To Reproduce

1. Have Beacons
2. Try to remove them with //set 0
3. Error - Selection is not removed

### Expected behaviour

Beacons can be removed, for that the BeaconDeactivatedEvent must be done synchronous.

### Error log (if applicable)

https://gist.github.com/LaurenceBarnes/00dfe5f1122e588a59a5ba4afff43606

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/cee0b2b1603d4b509ee8b4210e9e1a3c

### Fawe Version

FastAsyncWorldEdit Starlight build #14

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

Did you ever hear the tragedy of Darth Plagueis the Wise?

**Comment by NotMyFault** [comment]
Looks like something down to some pr Paper merged recently.

**Comment by Log1x** [comment]
Related: https://github.com/PaperMC/Paper/pull/5121

**Comment by Drc-DEV** [comment]
Any way to fix this?

**Comment by Xemorr** [comment]
Is any work being done on this? It's causing major issues for my use case.
