### ISSUE TITLE
Unload Schematic leads to error

### ISSUE THREAD

**Issue by doppelkool** [IntellectualSites/FastAsyncWorldEdit#1049]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

It happens when you unload any schematic. If it is from an earlier version of minecraft or from the latest, it happens with both and any.

### To Reproduce

1. Get any schematic (earlier or latest version)
2. Load it
3. Unload it -> Error (pastebin)

### Expected behaviour

Expected to load without errors

### Screenshots / Videos

https://ibb.co/7t4f8W1

### Error log (if applicable)

https://paste.gg/p/anonymous/1e4caaf5895d484dab8196bfc7453473

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/179795c3e0954b86a2597313d0649c0f

### Fawe Version

1.16-669;22be741

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Unloading schematics from the multi clipboard is currently not implemented.
