### ISSUE TITLE
Tool tree goes over plot border

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1059]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When using /tool tree the tree goes outside of the plot border:
![2021-05-09_14 55 18](https://user-images.githubusercontent.com/10485646/117574785-a56ff580-b0d6-11eb-8803-241ef0d58097.png)

![2021-05-09_14 55 30](https://user-images.githubusercontent.com/10485646/117574787-a739b900-b0d6-11eb-9ace-bc5ea1041bcd.png)

### To Reproduce

1. Use /tool tree
2. Right click on the edge of a plot

### Expected behaviour

The tree should be cut off at the border of the plot.

### Error log (if applicable)

https://pastebin.com/UPuQuLee

### Fawe Debugpaste

https://pastebin.com/a0KgYVX0

### Fawe Version

FastAsyncWorldEdit version 1.16-673;00d689a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Superseded by https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1060
