### ISSUE TITLE
Tool tree can bypass region restrictions

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1060]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When using `/tool tree` on a plot you are not added to it prevents you from using the tool which is correct:
![2021-05-09_15 13 00](https://user-images.githubusercontent.com/10485646/117575336-4069cf00-b0d9-11eb-9eb5-772bdd7a2672.png)

But if you hold down right click on a block and then move your mouse to the next block it will place the tree:
![2021-05-09_15 13 12](https://user-images.githubusercontent.com/10485646/117575369-5e373400-b0d9-11eb-8ff8-49c2bbe0b2e6.png)

This is problematic because it allows users to place trees in plots they do not own.

### To Reproduce

1. Do /tool tree
2. Hold right click and move your mouse to the next block

### Expected behaviour

You should not be able to use tool tree on plots you are not added to.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/023480f1c5c144438b3b1522c7ef965e

### Fawe Version

FastAsyncWorldEdit version 1.16-673;00d689a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

PlotSquared Settings file: https://pastebin.com/gjEzLPHZ

**Comment by aurorasmiles** [comment]
Please provide a proper server version/debugpaste

**Comment by SecretlyJealous** [comment]
> Please provide a proper server version/debugpaste

https://athion.net/ISPaster/paste/view/023480f1c5c144438b3b1522c7ef965e

**Comment by NotMyFault** [comment]
The same behavior can be obtained when using WorldEdit. Labeling this as upstream issue for now since this is apparently an issue on regular WorldEdit too and should probably be addressed there.
