### ISSUE TITLE
//undo does not work on tool tree

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1061]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

A `/tool tree` cannot be undone:
![2021-05-09_15 20 53](https://user-images.githubusercontent.com/10485646/117575556-4613e480-b0da-11eb-8d16-d0a3b0abec35.png)

`//brush inspect` does not log it either:
![2021-05-09_15 21 06](https://user-images.githubusercontent.com/10485646/117575590-693e9400-b0da-11eb-89fd-1f86545dffc1.png)

### To Reproduce

1. Do /tool tree
2. Do //undo
3. Do //brush inspect

### Expected behaviour

//undo should undo the edit

### Error log (if applicable)

https://pastebin.com/UPuQuLee

### Fawe Debugpaste

https://pastebin.com/a0KgYVX0

### Fawe Version

FastAsyncWorldEdit version 1.16-673;00d689a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Resolved in https://github.com/EngineHub/WorldEdit/issues/1745, incase someone is interesting in submitting a pr to paper.
