### ISSUE TITLE
FAWE stops working for all users after performing /mask /[0d][45d]

### ISSUE THREAD

**Issue by TaisenSchettler** [IntellectualSites/FastAsyncWorldEdit#1067]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If a user uses a brush in combination with an angle mask "/mask /[0d][45d]".  the brush is not working and FAWE stops working for all users until the server gets restarted. 

### To Reproduce

1. Equip a brush. //br sphere 22 10
2. Set an angle mask //mask /[0d][45d]
3. Use the brush.
4. Try using any other FAWE command (even /fawe debugpaste breaks)

### Expected behaviour

The mask, too affect the brush. And not break FAWE.

### Screenshots / Videos

https://youtu.be/aBlRk9o0_Iw

### Error log (if applicable)

https://gist.github.com/TaisenSchettler/80ef04899dd926ab85c388b9ec677702

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/37bf4023b3994cba93e278310d7dab03

### Fawe Version

Bukkit-Official(1.16-680;fb90e77e)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by TaisenSchettler** [comment]
the debug paste is from after restarting the server since no feedback was given back, while the issue is apparent.

**Comment by SirYwell** [comment]
#1024 #1025 probably related

**Comment by JoshA20** [comment]
confirmed,

purpur v1111
fawe 688

in my experience, issue starts with a angle mask, rather than negate. After someone does the command, it just breaks fawe all together, no commands go through, no responses, no errors, nothing. utter silence. Fix for me at the moment is a simple server restart

happy to provide any debug files if needed

**Comment by JoshA20** [comment]
./br surface gray_concrete,gray_wool,gray_glazed_terracotta 10
./mask /[60d][90d]

are two commands that crashed worldedit

**Comment by JoshA20** [comment]
https://paste.dedimc.io/oxenahexix.hs

got an error!

just spammed this in console

**Comment by blek-id** [comment]
Happening on me as well, any expected time this gets a fix?

**Comment by turtton** [comment]
I've encountered the same problem in spigot/paper v1.16.5. I know now that the range of sphere that FAWE stops depends on the processing performance of the CPU.
On i7-2600K CPU, FAWE stops in the range of about 13, while the Ryzen5 3600 environment can withstand up to nearly 25. It may stop within a narrower range than these, but the probability of this also seems to decrease with higher CPU performance.
Also, there was no error log when this problem occurred.

**Comment by dordsor21** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/f6af9925e8366ee7055a7dd95515c09021a152b4
