### ISSUE TITLE
Spams errors in console and may crash server if using nether_portal block with FAWE

### ISSUE THREAD

**Issue by BullobilyMC** [IntellectualSites/FastAsyncWorldEdit#1070]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

This issue has crashed my server once, and spammed the console with the error 
"POI data mismatch: never registered at BlockPosition"
while using fawe with nether_portal.

It also causes a BIG tps drop when the concerned chunks are loaded.

### To Reproduce

1. Create a selection of ~500 000 blocks
2. Use //set nether_portal
3. Use //undo

All portals blocks weren't well removed, just a part of them. I quit/join the server, the blocks were still here.

4. Break one of the remaining block by hand. This will spam the error in console you can see on the debugpaste.

### Expected behaviour

The //undo should have completely cleared portals blocks.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2af637a7815f4fcfbcfe0ed8139b718f

### Fawe Version

1.16-685 ; 9aa25ce

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
There is currently no way to address this as it's a CB around how POI stuff is handled.

**Comment by BullobilyMC** [comment]
Do you know if there are other blocks concerned by this issue? I think I will just block them

**Comment by NotMyFault** [comment]
Not out of my mind, tho other blocks with POI will be affected by it too.
