### ISSUE TITLE
Improve command //count

### ISSUE THREAD

**Issue by BullobilyMC** [IntellectualSites/FastAsyncWorldEdit#1073]
### What feature do you want to see added?

I think that //count performances could be improved. This command is simpler than //replace but consumes much more time to execute. 

### Are there any alternatives?

Current //count command works well, but use //replace (which print blocks changed count) and //undo is much faster.

**Comment by MattBDev** [comment]
This is potentially a bug instead of an enhancement. I'll assign myself to this issue.
