### ISSUE TITLE
SuperPickaxe not functioning correctly.

### ISSUE THREAD

**Issue by jacklollz2** [IntellectualSites/FastAsyncWorldEdit#1079]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

SuperPickaxe recursive/area does not follow the size limit settings, 5 is always the maximum.
SuperPickaxe does not drop items like how the WorldEdit implementation is designed to do.

### To Reproduce

1. WorldEdit config.yml
super-pickaxe:
    drop-items: true
    many-drop-items: true
max-super-pickaxe-size: 10
2. Hold a pickaxe.
3. Run the command /superpickaxe area 10
4. Get the error: Maximum radius is 5. **Problem one.**
5. Run the command /superpickaxe area 5
6. Click a block with the pickaxe.
7. No items drop. **Problem two.**

### Expected behaviour

Setting the superpickaxe size above 5 to work if the config file says so.
Breaking blocks with the superpickaxe will drop items if the config file says so.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5b49b8b2bd9b4b23ba9bb303f1fafc0c

### Fawe Version

FastAsyncWorldEdit version 1.16-688;71f7103

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by dordsor21** [comment]
Your debugpaste has none of the config options set to the values that are required for a superpickaxe of size >5. And I could not replicate this issue. With commit referenced above, it is assumed all issues fixed.
