### ISSUE TITLE
Message output malformed

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#1080]
Currently Fawe mangles the output of text components used by plugins such as WorldGuard.

![](https://i.imgur.com/efVGIlB.png)

**Comment by aurorasmiles** [comment]
Duplicate of #756 
😘

**Comment by NotMyFault** [comment]
Oh, I thought someone would've bothered the couple of minutes not maltreating stringified inputs.
