### ISSUE TITLE
Errors on Relighting large edits

### ISSUE THREAD

**Issue by GreatWyrm** [IntellectualSites/FastAsyncWorldEdit#1085]
### Server Implementation

Spigot

### Server Version

1.15.2

### Describe the bug

When editing a large region of blocks (Shows up when we are editing 32-50 chunks at a time), a relighting error shows up in console. It is often accompanied by #1083 .

### To Reproduce

1. Select a large region of blocks (Around 600 blocks in the x or z directions, and at least 40 blocks vertically, a selection of greater than 5 million blocks was fairly consistent at giving this error, if it doesn't happen, make a bigger selection)
2. Perform an edit (//faces bedrock.magma_block,obsidian, //undo will cause the error again if the first command caused it)
3. Error should display on console

### Expected behaviour

No Errors

### Error log (if applicable)

https://gist.github.com/GreatWyrm/8e2bf1616d70f19ba9c2787dcebc6063

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0b46a41d7adb498781220281a330b6e7

### Fawe Version

1.16-689;a7cbf1d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Try using Paper, afaik it adds some custom nms on top Fawe benefits from.
