### ISSUE TITLE
FAWE server crash related to undo

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1086]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

I have this crash which mentions FAWE and the /undo command: https://pastebin.com/3xq92cTs

### To Reproduce

1. Not sure, seems related to /undo?

### Expected behaviour

The server should not crash

### Error log (if applicable)

https://pastebin.com/3xq92cTs

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/563c1b0dcfc44e56bf93f8482ebc3ec7

### Fawe Version

1.16-687;706ac35

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
> com.boydti.litelog.api.AbstractLogger.logFrom(AbstractLogger.java:63)

If you want support you should consider using our official builds.

**Comment by SecretlyJealous** [comment]
> > com.boydti.litelog.api.AbstractLogger.logFrom(AbstractLogger.java:63)
> 
> If you want support you should consider using our official builds.

I think the issue is related to FAVS which I left on my live server on accident, I'll be removing the plugin and the logging plugin to see if this still occurs: https://haste.athion.net/ufuxonodob.md

**Comment by NotMyFault** [comment]
> > > com.boydti.litelog.api.AbstractLogger.logFrom(AbstractLogger.java:63)
> > 
> > 
> > If you want support you should consider using our official builds.
> 
> I think the issue is related to FAVS which I left on my live server on accident, I'll be removing the plugin and the logging plugin to see if this still occurs: https://haste.athion.net/ufuxonodob.md
> 
> > **[hastebin](https://haste.athion.net/ufuxonodob.md)**

> [11:07:05] [ForkJoinPool-7-worker-29/WARN]: 	at com.thevoxelbox.voxelsniper.sniper.Sniper.snipeOnCurrentThread(Sniper.java:280)

Apparently you are still using (FA)VS

**Comment by libraryaddict** [comment]
Check out #870
