### ISSUE TITLE
gravel/sand not falling (br sphere)

### ISSUE THREAD

**Issue by galathil** [IntellectualSites/FastAsyncWorldEdit#1087]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When you use a "//br sphere 35%13,65%0 4". Gravel (13) will spawn but not fall on the floor.
Sand not falling too

### To Reproduce

1) Login
2) Use commands below on a tool : 
 - //br sphere 35%13,65%0 4
 - //mask 0
3) Right click on the floor

### Expected behaviour

Gravel/sand should falling

### Screenshots / Videos

![gravel-not-fall](https://user-images.githubusercontent.com/7411973/119237106-78dac580-bb3b-11eb-8fec-9a5ba5f39246.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dc2b2a503fcb403c8887f103eac1ec77

### Fawe Version

FastAsyncWorldEdit 1.16-690;d48808f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

Paper version : 714
Fresh world
No other plugin

**Comment by NotMyFault** [comment]
That is the intended behavior. If you want to keep it, you need to enable the experimental settings in your config.yml

**Comment by galathil** [comment]
Which option should be activated? Am I lost in all these experimental options..

**Comment by NotMyFault** [comment]
> Which option should be activated? Am I lost in all these experimental options..

allow-tick-placed and allow-tick-existing

**Comment by galathil** [comment]
I've set the two options to true and restarting the server.
It doesn't work :(

**Comment by NotMyFault** [comment]
Use `//fall` then. Fawe not ticking blocks is generally per design and not intended to change.
