### ISSUE TITLE
NPE while using //replace

### ISSUE THREAD

**Issue by Nishh** [IntellectualSites/FastAsyncWorldEdit#1089]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

NPE error in console

### To Reproduce

Select a big area and do //replace

### Expected behaviour

No errors

### Error log (if applicable)

https://paste.gg/p/anonymous/26d7285c82e042dda7e0b977c40c913d

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b2772ee63e2a49c6896cb578e5fcc5a1

### Fawe Version

1.16-688;71f7103

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

It only happens sometimes, not always.
I'm using default config (fawe)

**Comment by MattBDev** [comment]
Looks like our threads aren't playing nice again.
