### ISSUE TITLE
FAWE 1.13 not properly importing NBT from .schematic file type (1.12 format)

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#109]
RE: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/99 Legacy schematic importing NBT issues

Related: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/90#issuecomment-479194160 (unfinished serialization?)
Old: https://github.com/boy0001/FastAsyncWorldedit/issues/1192

When trying to use a 1.12 FAWE schematic in a 1.13 FAWE environment using WorldEdit to transfer chests with various contents & NBT data, as well as custom heads, they end up pasted without all of their corresponding data.

(New Server on 1.13.2)
Paper dev 614 (Spigot 1.13.2)
FastAsyncWorldEdit-Breaking dev 20

(Old Server on 1.12.2)
Paper dev 1612 (Spigot 1.12.2)
FAWE dev 1263

* Go into old server (1.12), make a selection around build/chests, copy to clipboard, save as schematic.
* Upload schematic to new server.
* Attempt to paste schematic in new server (1.13), all the NBT data is missing.

Config
https://paste.ubuntu.com/p/C5HzHxFgCJ/

Config-Legacy
https://paste.ubuntu.com/p/9FCsptD8nD/

**Comment by Tsoccerguy3** [comment]
The changes in 1.13.x make the game drastically different to 1.12.2 . For the same reason you would not expect command blocks to work when copied over to 1.13.2 , the same goes for some other NBT data and commands
Unless someone writes some sort of converter . This is not a bug your experiencing. You would need a converter or edit manually if tools for 1.13.2 existed.

**Comment by boy0001** [comment]
I think mojang has a converter, that's how it loads old worlds.

**Comment by Tsoccerguy3** [comment]
Would like to get a command block convertor from 1.12.2 to 1.13.2 . to hard to manually update chests , command blocks , etc ..

**Comment by MattBDev** [comment]
I am going to add mojang's datafixerupper as a dependency to FAWE. Hopefully that tool will help us convert schematics easier.

**Comment by dordsor21** [comment]
I believe this is fixed
