### ISSUE TITLE
Java: '16.0.1' , FAWE: 1.16-695

### ISSUE THREAD

**Issue by Chypik** [IntellectualSites/FastAsyncWorldEdit#1090]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

the player leaves the server

### To Reproduce

the player leaves the server

### Expected behaviour

Server thread/WARN

### Error log (if applicable)

https://gist.github.com/Chypik/e3779878320c66ea85feeee708f085e0/revisions

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f3eb98d969134898a5da9037182b5c9b

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.16-695

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by aurorasmiles** [comment]
FAWE is not fully compatible with Java 16 yet. See 
#1082
