### ISSUE TITLE
Replacing enderchests generates errors/half chests

### ISSUE THREAD

**Issue by markaabo** [IntellectualSites/FastAsyncWorldEdit#1092]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

**The bugs:**
When trying to `//replace` enderchests to trapped chests it either generates an error, or it makes half block trapped chests depending on which way you do it.

Doing `//replace ender_chest ^trapped_chest` results in this:
![2021-05-22_12 58 12](https://user-images.githubusercontent.com/68380434/119630652-71533f00-be0f-11eb-956b-f188564ccbc1.png)

Doing `//replace trapped_chest[type=single] ^ender_chest` results in an error:
[ReplaceError.txt](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6545227/ReplaceError.txt)

**Server plugins:**
BKCommonLib-1.16.5-v2, F3NPerm-2.5, FastAsyncWorldEdit-Bukkit-1.16-688, HolographicDisplays, LightCleaner-1.16.5-v1, LuckPerms-Bukkit-5.3.42, PlaceholderAPI-2.10.9, RollbackCore-3.5.0-BETA (for 1.13.2 or newer), simplereserve-1.0.1, SurvivalGames, TitleManager-2.3.3, worldguard-bukkit-7.0.4

### To Reproduce

Place `ender_chest` and/or `trapped_chest`
Select the area of the placed chests
Do `//replace ender_chest ^trapped_chest` to reproduce the half chest bug
Do `//replace trapped_chest[type=single] ^ender_chest` to reproduce the error

### Expected behaviour

When doing `//replace ender_chest ^trapped_chest` it should just replace any `ender_chest` with `trapped_chest` and keep original orientation.

When doing `//replace trapped_chest[type=single] ^ender_chest` it should replace any single `trapped_chest` with `ender_chest` and keep original orientation.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b6a5fe23f1b84476b9c9900a9b2aec6c

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.16-688

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

The 2 bugs was firstly posted by me in another issue report, but it got closed before finding the new issues, hense the new issue post. [https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1081](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1081)

**Comment by MattBDev** [comment]
This is an interesting issue because I thought that we previously resolved this.

**Comment by dordsor21** [comment]
Ender chests do not have the "type" tag in their blockstate and thus the `^` flag cannot be used. You will instead need to use individual `[facing=DIRECTION]` states for replacing, much like you would assume to need to be used for replacing chests with stairs, for example. This is therefore technically a feature request to allow the blockstates that _can_ be kept, to be kept and discarding others.
