### ISSUE TITLE
copy/cut/clipboards do not work properly

### ISSUE THREAD

**Issue by LaurenceBarnes** [IntellectualSites/FastAsyncWorldEdit#1095]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

On builds between Starlight build-19 (the Starlight build right before the merge into the main branch I believe) and FAWE main branch build-687, a bug was introduced that sometimes caused issues with the copying/cutting/creating-a-clipboard action. At first I assumed it was the paste, but given the fact that the buggy clipboard could be fixed by trying to copy/cut the same selection again, it definitely seems to be a copy/cut issue.
The annoying thing with it was that a //undo does not undo all changes properly or rather, does not restore the previous stuff, hence it always breaks a part. It DOES NOT throw any errors, which is quite inconvenient. However I have made two screenshots that show how it consistently behaves when it happens. I'd say it happens in 1-5% of cases, so it should be possible to reproduce with regular attempts of copying/cutting & pasting (ideally different) objects in a row.

### To Reproduce

1.) Select something you want to copy and use the affected FAWE versions (the selection is visible at the lower windows)
2.) Paste it to have the same window above, like this:

![2021-05-20_16 23 47](https://user-images.githubusercontent.com/77249464/119780758-7fb26100-beca-11eb-9ee3-44dfa7e76763.png)

3.) As you can see, only a part of the selection was copied and something is missing
4.) That's not all?
5.) //undo because it fecked up

![2021-05-20_16 24 09](https://user-images.githubusercontent.com/77249464/119780988-c011df00-beca-11eb-8e87-d0aa99b8502a.png)

6.) as you can see, a part of the window frame I made before (would be exactly mirrored on the other side) is also gone. What the heck?

PS.: I built everything by hand before, so it is not FAWE having issues which its own operations. It happens with hand-built structures being copied.

### Expected behaviour

copy/paste works without issues, as it did on the Starlight build I tested to narrow down the range of patches.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e8806a470148404d8bca48611348eb89

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.16-19 (Starlight) & FastAsyncWorldEdit-Bukkit-1.16-687.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

Because of the nature of this issue, I did not update to the latest version of FAWE yet, as I had to reliably confirm it does not happen because of any changes in the Starlight Build before the merge. I will test it as well with newer versions from today, very much likely with Java 16 and the connected branch (as we need Java 14+ for our own plugin).

@MattBDev wanted to take a look at this.

**Comment by LaurenceBarnes** [comment]
okay it did not happen even once on the Java 16 branch (build 3) during testing for six days, that could have been a coincidence.
I just had it happen on the main branch build 698 which I updated to yesterday. That bug is weird.

**Comment by dordsor21** [comment]
Have you come across this issue in any subsequent FAWE versions?

**Comment by LaurenceBarnes** [comment]
well, seems to not occur anymore as of build 721. I will comment here again in case it occurs, which I doubt - it would definitely have happened already otherwise. Thanks for your attention!

**Comment by zagdrath** [comment]
https://athion.net/ISPaster/paste/view/61976f795aaf4fe6b16702c46849ffb5

I seem to be getting this issue on 1.17.
