### ISSUE TITLE
//set does random hole that are 1 block deep.

### ISSUE THREAD

**Issue by resprune** [IntellectualSites/FastAsyncWorldEdit#1096]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Whenever I use the //set command, I eventually return, seeing that there are some holes which a 1 block deep. I also tried checking console.

Posting it here because on the World Edit github they said it's not the same version.

### To Reproduce

1. Use the //set command.
2. Go away from the location, and go back.

### Expected behaviour

None of these holes, perfect.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/74532477/120012906-6996c480-bfe0-11eb-9c55-9a816849d0f0.png)
![image](https://user-images.githubusercontent.com/74532477/120012916-6d2a4b80-bfe0-11eb-9a5c-274916a01038.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/71edb564ad1f4fe19ce9a0fd2fd4a4b0

### Fawe Version

FastAsyncWorldEdit version 1.16-673;00d689a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
![](https://i.imgur.com/ZgR66Lq.png)
![](https://i.imgur.com/I1yP6KO.png)
Please consider reading the instructions and following what they tell you to do before blindly ticking them.
Thanks in advance.
