### ISSUE TITLE
Pasted schematics have waterlogged blocks

### ISSUE THREAD

**Issue by MetalWarLord** [IntellectualSites/FastAsyncWorldEdit#1099]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Loading and pasting a schematic causing some blocks to become waterlogged. The schematics were made under Paper 1.14.4.

### To Reproduce

1. Make a schematic containing a lantern under 1.14.4
2. Load and paste under 1.16.5

### Expected behaviour

Pasting without waterlogging

### Screenshots / Videos

![schematic_waterlogged_lantern](https://user-images.githubusercontent.com/85002487/120084411-3b90ad80-c0d0-11eb-8fbd-83a55110a2db.png)

### Error log (if applicable)

No error logs were produced during this operation

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/fa58b6e7f71745f5911cc4019dce854d

### Fawe Version

1.16-696;53681cc

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by MattBDev** [comment]
We need to test this using WorldEdit too.

**Comment by NotMyFault** [comment]
I was unable to replicate this. Creating a schematic with Fawe on 1.14.4 pastes lanterns fine on 1.16.5.
Please attach your schematic affected.

**Comment by MetalWarLord** [comment]
I checked the old server configuration and plugins and I found that we had only WorldEdit on the 1.14.4 server.
Is it possible that this is the cause of the problem?

If it is not, I'll send the schematic.

**Comment by dordsor21** [comment]
It would be worth having the schematic. Can you replicate this on WorldEdit rather than FAWE (on 1.16.5), with the specific schematic?

**Comment by NotMyFault** [comment]
No response, assume no longer relevant or resolved.
