### ISSUE TITLE
PlatformReadyEvent error 

### ISSUE THREAD

**Issue by Poulpinounette** [IntellectualSites/FastAsyncWorldEdit#1101]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When we start the server we got this error : [error](https://paste.gg/p/anonymous/76c13442475243089c9f79ee792f16da)

### To Reproduce

i dunno

### Expected behaviour

work properly

### Screenshots / Videos

The error log

### Error log (if applicable)

https://paste.gg/p/anonymous/76c13442475243089c9f79ee792f16da

### Fawe Debugpaste

plugin disabled :/

### Fawe Version

the latest build :/

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

This error fuck essentials & other plugin :/

**Comment by LaurenceBarnes** [comment]
what is your Java version?

**Comment by aurorasmiles** [comment]
Please provie a FULL startup log.

**Comment by Poulpinounette** [comment]
Full log: https://hastebin.com/jaqufisice.yaml
Java version : 11 (we use docker : quay.io/pterodactyl/core:java-11)

**Comment by NotMyFault** [comment]
> com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 1005598 path $.sp

You somewhere have an invalid formed translation key in your lang/strings.json file

**Comment by LaurenceBarnes** [comment]
also a general advice: Update Paper more often, you are way over 100 builds behind.

**Comment by Poulpinounette** [comment]
> > com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 1005598 path $.sp
> 
> You somewhere have an invalid formed translation key in your lang/strings.json file

this file is empty




> also a general advice: Update Paper more often, you are way over 100 builds behind.

Sure, i have update and got the same problem so

**Comment by NotMyFault** [comment]
> > > com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 1005598 path $.sp
> > 
> > 
> > You somewhere have an invalid formed translation key in your lang/strings.json file
> 
> this file is empty
> 
> > also a general advice: Update Paper more often, you are way over 100 builds behind.
> 
> Sure, i have update and got the same problem so

That explains it then lol
Delete the folder and Fawe will generate you an up to date one.

**Comment by Poulpinounette** [comment]
> > > > com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 1005598 path $.sp
> > > 
> > > 
> > > You somewhere have an invalid formed translation key in your lang/strings.json file
> > 
> > 
> > this file is empty
> > > also a general advice: Update Paper more often, you are way over 100 builds behind.
> > 
> > 
> > Sure, i have update and got the same problem so
> 
> That explains it then lol
> Delete the folder and Fawe will generate you an up to date one.

Well, delete the string.json work properly and fix the bug. essentials still bug with the path blabla..
