### ISSUE TITLE
Some History Inspections Produce 'Stream is Corrupted'

### ISSUE THREAD

**Issue by Colin-Wahl** [IntellectualSites/FastAsyncWorldEdit#1104]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Some FAWE inspections will fail and produce a 'java.io.IOException: Stream is corrupted' error.

### To Reproduce

1. //inspect
2. Inspect FAWE usage
3. Some FAWE edits will inexplicably produce the critical error

### Expected behaviour

Command should return inspection data.

### Error log (if applicable)

https://paste.gg/p/anonymous/62f5757302444353845d1721c9d1718b

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b9339da0302b463e92bdd254efd05f80

### Fawe Version

1.16-700;c87a19d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by dordsor21** [comment]
This signifies the edit was cancelled without completing writing the history. This is usually due to the server being shut down, FAWE hitting a deadlock, etc. Do you know that the edits were definitely interrupted by such a reason, and what edits they were?

**Comment by NotMyFault** [comment]
No response over a month, assume no longer revelvant.
