### ISSUE TITLE
Error when pasting & loading specific schematic

### ISSUE THREAD

**Issue by 6u5t4v** [IntellectualSites/FastAsyncWorldEdit#1110]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I am trying to load a schematic, but it just gives me an error something with "missing Blocks tag".

### To Reproduce

I get 2 different messages depending on how I attempt to load it:
Method 1:
  step.1) do /schematic list
  step.2) press the '+' associated with the specific schematic. It says `..\<schematic>.schematic loaded. Paste it with //paste`
  step.3) run //paste. It says `The clipboard has been pasted at (x, y, z)`
  step.4) large beatiful error in console.

### Expected behaviour

I expect to paste the schematic and not return an error

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/41763143/121220006-8951a680-c884-11eb-806f-e0c319d2c182.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/f084efa104f94caa88dc9989d2a972f7

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b20e2840cd854dbf9bcdb1b90b8615b7

### Fawe Version

1.16-708;ef5211d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Attach the schematic. It's likely been created improperly.

**Comment by 6u5t4v** [comment]
[enderdungeon_notworking.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6618264/enderdungeon_notworking.zip)

**Comment by dordsor21** [comment]
Do not change the file ending of schematics. That is a .schem format, not a .schematic.
