### ISSUE TITLE
Unable to customize "Invalid value for <something>..." message

### ISSUE THREAD

**Issue by joshwenke** [IntellectualSites/FastAsyncWorldEdit#1115]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

In [strings.json](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/b7f595cc50706f8292c3ed2339d47dad373ac3a2/worldedit-core/src/main/resources/lang/strings.json) there is not a section for this message. I can customize other messages just fine.

### To Reproduce

Run //set randomthinghere
You will see the built-in error. The default one includes usage information, and that can easily be removed/changed in strings.json. But the line below it cannot be changed.

Example:
"Invalid value for <pattern> (Does not match a valid block type: randomthinghere), acceptable values are any pattern"

### Expected behaviour

The block of text should be customizable.

### Screenshots / Videos

https://i.imgur.com/3MpQSJG.png

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0495807feed74e1faf6cfdf96d00cb5c

### Fawe Version

1.16-713;09b2cfe

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by joshwenke** [comment]
This extends to all commands with argument as well:

//calc, //eval
"Missing argument for <input...>" 

//inset, //contract
"Missing argument for <amount>"

**Comment by NotMyFault** [comment]
Exceptions are generally not translatable.
