### ISSUE TITLE
Someblocks of decoration blocks can't link to blocks

### ISSUE THREAD

**Issue by IAMGOLFz** [IntellectualSites/FastAsyncWorldEdit#1117]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Dear FAWE developer 
I come for report bug who I had found out since 1.15.2 , now I find out in 1.16.5 again. Issue of bug report is Someblock of decoration blocks [**default and stained glass pane, cobblestone and other wall, woods fence , iron bars**] didn't link to block with **//set** or **//paste** of schematics 

I found it since 1.15.2 who I must place it by hand after used //paste or //set it. Please see this report and advise me for fixing this problem... Thank you :]   

### To Reproduce

1. //pos1 and //pos2 or use wand to set position 
2.  //gmask 0 
3.  use //set or //paste it  
4.  I will see problem [please follow **Describe the bug**

### Expected behaviour

I think this happen is I forget fix on configuration 

### Screenshots / Videos

![2564-06-11_11 30 14](https://user-images.githubusercontent.com/85722884/121634083-30655680-caae-11eb-9dc1-52a120b70c30.png)
![2564-06-11_11 31 42](https://user-images.githubusercontent.com/85722884/121634093-34917400-caae-11eb-88cc-0563df48783e.png)
![2564-06-11_11 32 56](https://user-images.githubusercontent.com/85722884/121634099-36f3ce00-caae-11eb-9855-a622829df566.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f4956d0e4a8f43f58a0d067f9dac02b6

### Fawe Version

FastAsyncWorldEdit1.16-716;7ef8b2f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
Like told previously, you need to apply a blockstate e.g `//set oak_fence[east=true]`
See https://minecraft.fandom.com/wiki/Block_states for a full list of blockstates.

**Comment by IAMGOLFz** [comment]
Thank you for your suggestion 😃
