### ISSUE TITLE
Transform functions not working on double slab

### ISSUE THREAD

**Issue by NikBrouw** [IntellectualSites/FastAsyncWorldEdit#1122]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

When using transform functions (e.g. //rotate, //flip) on a double slab (possibly all blocks that allow for multiple blocks in one square), using //paste pops an ArrayIndexOutOfBoundsException. The error does not occur during the rotation, but rather upon pasting.

### To Reproduce

1. Place two slabs on top of each other (in the same square)
2. Copy the slabs
3. Rotate any number (except 360)
4. Paste

### Expected behaviour

Normal paste of the rotation.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/33279182/121824854-645b9a00-ccaf-11eb-8df2-8f76bbdee201.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4126b0ddf9334be584732356ea77178e

### Fawe Version

FastAsyncWorldEdit version 1.16-725;d015e6b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

Bug likely occurs on any object that allows for multiple blocks in one square.

**Comment by dordsor21** [comment]
Use the latest build for now whilst a proper fix is implemented
