### ISSUE TITLE
Add `~` mask to FAWE

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/FastAsyncWorldEdit#1126]
### What feature do you want to see added?

Not sure if this is a glitch or if it's just not implemented yet, but on 1.12.2 FAWE you could use the `~` mask to place adjacent blocks but it comes up as "No match" when using //gmask, for example.

### Are there any alternatives?

None that I know of.  This was a mask that FAWE used to have.

**Comment by MattBDev** [comment]
The Adjacent mask is implemented. Make sure you are using the proper syntax when using masks. @SirYwell is an expert on mask and pattern syntax. Maybe he can help out here and close this issue.

**Comment by SirYwell** [comment]
I don't really know how the old syntax was like, but `~[stone]`, `~[stone][1]`, or `~[stone][2][4]` should be working examples. If that does not work, please provide screenshots for the exact message and a fawe debugpaste.

**Comment by braceyourself07** [comment]
I spoke with the builder and I think the discrepancy is that FAWE does not automatically bracket it like it does with other masks.

**Comment by SirYwell** [comment]
Currently, all FAWE masks of that kind require explicit bracketing. The implementation is basically the same as for `/[<min>][<max>]`, just with a different name (`~`), one required and two optional parameters. The masks from WorldEdit like `>` and `<` don't have optional parameters and are therefore easier to parse (but on the other hand it causes issues with precedence).

I was thinking a lot about possibilities to make the overall syntax easier and more consistent, but the biggest issue with changing it is that people don't want to re-learn the syntax of patterns.

We *could* implement the mask, but that would be more of a hacky workaround than a proper solution, making things worse in terms of maintainability.
