### ISSUE TITLE
[1.17] Actions performed above y = 256 and below y = 0 do not work

### ISSUE THREAD

**Issue by DaJokni** [IntellectualSites/FastAsyncWorldEdit#1134]
### Server Implementation

Paper

### Server Version

1.17

### Describe the bug

Performing an edit outside of the range 0-256 will result in an error. Minecraft versions before 1.17 were previously limited to a world height of 256. The game now allows negative y values and an increased height range.

No blocks are set with any command. An error appears every time a block is set outside of the 0-256 height range.

### To Reproduce

1. Load up FAWE on a Paper server
2. Try to set any blocks outside of the 0-256 height range. 
3. Observe that nothing happens
4. Look into the console

### Expected behaviour

I would expect the blocks to be set, and an error wouldnt appear in console.

### Screenshots / Videos

Tried to set air to the grass, nothing happened and an error appeared in console.
![2021-06-23_15 16 46](https://user-images.githubusercontent.com/56400974/123094930-204a6100-d436-11eb-91b4-4311f87cdc6d.png)

### Error log (if applicable)

https://gist.github.com/DaJokni/3310dfda3c8f934bef4ddd8a3ecbf5c2

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dab33e1e6ac64d90a561a672d7f5019a

### Fawe Version

FastAsyncWorldEdit version 1.17-10;dec29c8

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by MattBDev** [comment]
Were you trying to set blocks above y=256 or below y=0?

**Comment by DaJokni** [comment]
> Were you trying to set blocks above y=256 or below y=0?
No, i were not. The world is 384 blocks tall though, so id assume thats the issue then?

**Comment by SirYwell** [comment]
Yes, likely caused by the custom world height

**Comment by DaJokni** [comment]
> Yes, likely caused by the custom world height

Alrighty, ill test with a normal height.

Conclusion of the test: It works with the normal world height.

**Comment by MattBDev** [comment]
I'm going to edit this issue a bit so it can track the support of new world heights.
