### ISSUE TITLE
//smoth bug

### ISSUE THREAD

**Issue by AntiHunter1** [IntellectualSites/FastAsyncWorldEdit#1135]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

//smoth generates lines

### To Reproduce

1. Select the area
2. //smooth

### Expected behaviour

No lines

### Screenshots / Videos

![2021-06-23_20 10 19](https://user-images.githubusercontent.com/65368551/123147345-328cc500-d45f-11eb-8c48-cdfcdaa8b78c.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e16f8bfa47a646c6bfa34f08909afbaf

### Fawe Version

FastAsyncWorldEdit version 1.16-620;cde52f9

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

sad

**Comment by NotMyFault** [comment]
Don't tick the checklist if you didn't go thru it.

**Comment by LaurenceBarnes** [comment]
over 100 builds behind with FAWE and over 300 builds behind with paper. Mad respect.

**Comment by LaurenceBarnes** [comment]
plus you are using Java 10 when you should be using Java 11 or Java 16
