### ISSUE TITLE
[1.17] Undo misses some chunks

### ISSUE THREAD

**Issue by deelux13** [IntellectualSites/FastAsyncWorldEdit#1138]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

when loading and pasting a schematic from local or from online, the undo command does not completely remove. It leaves chunks (actual Minecraft chunks) untouched. it seems to generally be east-west strips that are both removed and left behind, with some variability. also, is constant when pasting the same schematic at the same position, and with undo->redo it is the same chunks missed each time (for each individual paste).

copying from an in-world selection seems to mostly undo correctly unless the paste coincides with an improperly undone previous paste, then the same chunk has issues and some surrounding might too. 

### To Reproduce

1 start server, login
2 //schematic load schem url:e1971648-ebfd-4282-a93d-d173db6cb1b0
3 //paste
4 //undo

    

### Expected behaviour

I expect all of the changes (new blocks) from //paste to be reverted to their original state by //undo

### Screenshots / Videos

![2021-06-23_18 19 41](https://user-images.githubusercontent.com/16197508/123181215-76c59880-d452-11eb-968a-4b92c087e964.png)
![2021-06-23_18 19 59](https://user-images.githubusercontent.com/16197508/123181216-77f6c580-d452-11eb-9181-b1a66bda08a7.png)

### Error log (if applicable)

none

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ead25dae5b8b45009d10543427acfee3

### Fawe Version

FastAsyncWorldEdit:   • Version: 1.17-11;2bbf284

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by MattBDev** [comment]
In the future please leave a more helpful issue title. 1.17 is extremely vague and doesn't provide us any information.

**Comment by zagdrath** [comment]
https://athion.net/ISPaster/paste/view/61976f795aaf4fe6b16702c46849ffb5

I am having the same issue but it does this when I copy and paste and undo it.

**Comment by OstriySous-dev** [comment]
in my opinion, it is no longer reproduced

**Comment by dordsor21** [comment]
Is someone able to confirm if they are still experiencing/replicating this issue?

**Comment by dordsor21** [comment]
Over a month with no reproductions
