### ISSUE TITLE
NPE in saving schematics on 1.17

### ISSUE THREAD

**Issue by NoVPN5717** [IntellectualSites/FastAsyncWorldEdit#1141]
### Server Implementation

Paper

### Server Version

1.17

### Describe the bug

https://athion.net/ISPaster/paste/view/8d834b817792410292c47f04e773cead
my version is 1.17 btw__

### To Reproduce

//schem save
//paste

### Expected behaviour

to paste and save the schem without issue

### Error log (if applicable)
Uncaught exception occurred in task: Saving schematic MangoliaTrainStation.schem
java.lang.NullPointerException: Cannot invoke "com.sk89q.jnbt.CompoundTag.getValue()" because "this.cachedValue" is null

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8d834b817792410292c47f04e773cead

### Fawe Version

FastAsyncWorldEdit-11

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment]
I was able to reproduce that stacktrace attempting to save schematics containing signs with letters on.
