### ISSUE TITLE
//smooth bug v2

### ISSUE THREAD

**Issue by AntiHunter1** [IntellectualSites/FastAsyncWorldEdit#1143]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

//smooth generates some random lines in floating islands.

### To Reproduce

1. Have a floating island
2. Select the region
3. //smooth

### Expected behaviour

No lines after //smooth.

### Screenshots / Videos

![2021-06-25_19 52 32](https://user-images.githubusercontent.com/65368551/123466404-9645f800-d5ef-11eb-92e6-a30f60f2b2a2.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bee48a85c1d74bc2b1417872a165bdfd

### Fawe Version

FastAsyncWorldEdit version 1.16-734;78acb85

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

sad
and I updated FAWE && Java to 16

**Comment by NotMyFault** [comment]
Can you attach a schematic of the screenshot linked? So we can test it out in action.

**Comment by AntiHunter1** [comment]
A piece of it is enough too? Like the left edge for example 70-80 block long.

**Comment by AntiHunter1** [comment]
https://www.dropbox.com/s/zr0q4amuh7pzxkm/LineTest.schem?dl=0
