### ISSUE TITLE
Brush Activation not limited to right click.

### ISSUE THREAD

**Issue by DocCodeSharp** [IntellectualSites/FastAsyncWorldEdit#1144]
### Server Implementation

Spigot

### Server Version

1.17.+

### Describe the bug

When using a bush in FAWE, when you go to active the said brush it will work on left or right click. This feature should only fire when you right click like in WE as having both option can cause confusing and do some damage. 

### To Reproduce

1. Grab Stick
2. //br <target>
3. Left or Right Click

### Expected behaviour

Should only active when the user right clicks with the set brush.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a335c3984c6846c6a2365e4ae2e97341

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-12.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

**Comment by NotMyFault** [comment]
Fawe has always listened to both actions. Removing one now is a breakage and undesired.

**Comment by DocCodeSharp** [comment]
Can a option be placed in the Config to limit it right click only and default to both?
