### ISSUE TITLE
Error on PlayerInteractEvent (NoClassDefFoundError) with FAVS and goBrush

### ISSUE THREAD

**Issue by chickenputty** [IntellectualSites/FastAsyncWorldEdit#1146]
### Server Implementation

Spigot

### Server Version

1.17.+

### Describe the bug

Error with player interact causing FAVS and goBrush to not function.

### To Reproduce

1. Download the versions specified (all latest)
2. Attempt to use FAVS or goBrush
3. View error in console

### Expected behaviour

The plugins to work when interacting with the tools.

### Error log (if applicable)

https://paste.gg/p/anonymous/982113839feb47f7be669ccfa4263576

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9bbe05106613496db5e42ce46dea81d6

### Fawe Version

1.17-12;90e6eba

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

### Anything else?

For versions:

- 3161-Spigot-f773da8-f81f499 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
- FastAsyncWorldEdit 1.17-12;90e6eba
- goBrush 3.7.2-27
- VoxelSniper 1.0.4-backward

**Comment by NotMyFault** [comment]
Named plugins need to update their hooks, report it to them.
