### ISSUE TITLE
Copying and pasting an entity inside the minecart only pastes the minecart.

### ISSUE THREAD

**Issue by PatrickMSM** [IntellectualSites/FastAsyncWorldEdit#1147]
### Server Implementation

Purpur

### Server Version

1.17.+

### Describe the bug

Copying an entity inside a minecart and pasting it pastes only the minecart, or sometimes the minecart and the entity dismounted on top of the minecart.

### To Reproduce

1. Copy a region that has an entity riding a minecart.
2. Paste it, and observe the bug.

### Expected behaviour

Pasting would paste the entity riding the minecart.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/45915226/123536282-0fe5ff00-d732-11eb-8d17-5ffa85128eea.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2345e98661884ae59568dcdc20973035

### Fawe Version

FastAsyncWorldEdit version 1.17-17;1b88827

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

### Anything else?

Originally, this was discovered by copying a farm from a world to another and getting the snow golem ejected out of the minecart.
Edit: I am using GraalVM 16

**Comment by NotMyFault** [comment]
Update Fawe.
