### ISSUE TITLE
Wand is broken 

### ISSUE THREAD

**Issue by OstriySous-dev** [IntellectualSites/FastAsyncWorldEdit#1148]
### Server Implementation

Purpur

### Server Version

1.17.+

### Describe the bug

Enter the command / / wand and get an error (the axe is not issued)

### To Reproduce

1. use //wand

### Expected behaviour

Issuing a tool

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/67519432/123537401-e16b2280-d737-11eb-8666-547f00c6b7f9.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e7234326cf504cdabe41f06fdd3bc8a4

### Fawe Version

1.17-17

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

**Comment by MattBDev** [comment]
Fixed in 3f1e4f7
