### ISSUE TITLE
[1.17] ArrayIndexOutOfBoundsException while using //paste

### ISSUE THREAD

**Issue by einTosti** [IntellectualSites/FastAsyncWorldEdit#1149]
### Server Implementation

Tuinity

### Server Version

1.17.+

### Describe the bug

When using `//paste` after coping a region (`//copy`), the following exceptions are thrown:
- `ArrayIndexOutOfBoundsException` 
- `ExecutionException`

and the region isn't pasted

### To Reproduce

1. Select a region (`//pos1`, `//pos2`)
2. Copy the region (`//copy`)
3. Paste the region (`//paste`)

### Expected behaviour

The copied region should be pasted

### Error log (if applicable)

https://paste.gg/p/anonymous/ff6826eb33974f7385aadad8d62b904c/files/ddbfc8e360a64f86941f87581ce68b54/raw

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/129836fe3d5643b38ba3acd2535ecef5

### Fawe Version

FastAsyncWorldEdit version 1.17-17;1b88827

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

### Anything else?

The world in which I want to paste the region has the 1.18 datapack installed

**Comment by einTosti** [comment]
Might be related to #1134 (custom world height in datapack worlds)?

**Comment by MattBDev** [comment]
@einTosti Are you using custom height in your world? If so, we can just merge this issue with #1134

**Comment by einTosti** [comment]
Closed, as this issues is a duplicate of #1134
