### ISSUE TITLE
//Brush -  java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096

### ISSUE THREAD

**Issue by narcarsiss** [IntellectualSites/FastAsyncWorldEdit#1151]
### Server Implementation

Purpur

### Server Version

1.17.+

### Describe the bug

----------------
**NOTE: as plugin crashed I was unable to run debug paste, it does not give any command, nother does any command. /fawe version, etc...**
---------------

Was running command
//brush cylinder 10%gravel,10%sandstone,80%sand 100 2

- 64 View Distance
- Spamming command (constant right click) , then Ground started freaking out (see image) and then the plugin stopped working.
- As you can see via the log I have not ommited any of the commands I was running 
- Logged out and back in to see if it was client crash.

/tpsbar showed no sign on TPS drop (but it is using average rather than accurate)

### To Reproduce

---------
Unable to Reproduce, don't want to risk corruption of world.
---------

### Expected behaviour

Expected Behavior was  for command to keep working, or eventually go Async and not crash? not sure how your plugin works.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/3479268/123579402-2a47d780-d81b-11eb-8f47-0b53c3c0ce69.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/69c14655402e482e9055963bb7daa426

### Fawe Debugpaste

Unable to run as Plugin crashed.

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-21

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

### Anything else?

Most likely because I was being a stupid spamming the command to populate a large area fastly.

**Comment by narcarsiss** [comment]
Can confirm:  
Does reproduce when Replacing Terrain, It looks like the Command `/mask sand` for example is breaking out of the detection range (edges of that block, radius, range) and trying the next best thing and thus creates floating Islands.

**Comment by NotMyFault** [comment]
Do you use a datapack with custom word height?

**Comment by dordsor21** [comment]
No response in a month, and without sufficient information.
