### ISSUE TITLE
Cant //undo //brush populateschematic and //caves without rejoining the server

### ISSUE THREAD

**Issue by Lukasz825700516** [IntellectualSites/FastAsyncWorldEdit#1152]
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

Cant undo edits of populateschematic brush if they were created in current play session (there was no reloging to the server) or they where done after rejoining

### To Reproduce

0. Bind brush to tool `//brush populateschematic #solid crystal/0`
1. Place stuff using brush
2. Type `//undo` - Can say that undid something, but not the brush edit from step 1.
3. rejoin the server
4. Again place stuff using previous brush
5. Type `//undo` - Works
6. Again use brush
7. `//undo` - Can say that undid something, not the brush edit from step 6., but .1

### Expected behaviour

`//undo` should undid the last changes

### Screenshots / Videos

![bugreport](https://user-images.githubusercontent.com/38139742/123618282-931d5880-d7f7-11eb-8364-2ece900f5cf4.gif)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a4c3895142434c61b99218f71a1bdac9

### Fawe Version

17-21;c13760a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

**Comment by narcarsiss** [comment]
Suffering this Issue also, when placing Cactus schematics, unable to undo, re-loggin does indeed fix the issue.

**Comment by NotMyFault** [comment]
Same applies to `//caves`
