### ISSUE TITLE
Error when using any command for editing and checking in the world

### ISSUE THREAD

**Issue by 0neEyedDemon** [IntellectualSites/FastAsyncWorldEdit#1153]
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

When trying to edit the world using FAWE, an error returns asking to be reported. 

### To Reproduce

Use any world changing or checking commands. //set //count etc.

### Expected behaviour

//set 0 was expected to remove the blocks chosen before with the //pos1 and //pos2 commands

### Error log (if applicable)

https://paste.gg/p/anonymous/d4bb7ce4f72d4e8882c0c5bc09f499cc

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d7b9e696fdd24cbfb526472c904c74de

### Fawe Version

FastAsyncWorldEdit version 1.16-735:b0c0689

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

### Anything else?

The error was printed to console as a warn on one of the attempts.
Pastebin here: https://paste.gg/p/anonymous/fc9ae4101edb45829a709befb8a0076c

**Comment by NotMyFault** [comment]
Don't use the 1.16 builds on 1.17 https://ci.athion.net/job/FastAsyncWorldEdit-1.17/
