### ISSUE TITLE
//regen error

### ISSUE THREAD

**Issue by OstriySous-dev** [IntellectualSites/FastAsyncWorldEdit#1154]
### Server Implementation

Purpur

### Server Version

1.17.+

### Describe the bug

when executing the //regen command, an error always occurs

### To Reproduce

1. Use //regen

### Expected behaviour

The territory must be restored

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/67519432/123849639-b3e1cd00-d921-11eb-8e82-3875ac2594fa.png)
![image](https://user-images.githubusercontent.com/67519432/123849664-b93f1780-d921-11eb-92cb-0839673e2a53.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/2afb49f1b1b443469ff77f16a39ddd58

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/872717f40a8c405e946c2ac05a8b90e8

### Fawe Version

1.17-21

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

**Comment by NotMyFault** [comment]
Tested on git-Paper-64, can't reproduce. This appears to be a mapping issue at Purpurs end.

**Comment by LaurenceBarnes** [comment]
It might also just not have been upstreamed yet

**Comment by narcarsiss** [comment]
Can confirm still happening on latest purpur as of this Comment
