### ISSUE TITLE
how do i install it fore 1.17

### ISSUE THREAD

**Issue by windetrsfugwq** [IntellectualSites/FastAsyncWorldEdit#1156]
### Server Implementation

Spigot

### Server Version

1.17.+

### Describe the bug

q

### To Reproduce

q

### Expected behaviour

cant

### Screenshots / Videos

cant

### Error log (if applicable)

q

### Fawe Debugpaste

q

### Fawe Version

newist

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

### Anything else?

q

**Comment by SirYwell** [comment]
Visit our discord server if you need help. No need to spam the issue tracker.
