### ISSUE TITLE
reobf Patch (temp fix)

### ISSUE THREAD

**Issue by narcarsiss** [IntellectualSites/FastAsyncWorldEdit#1159]
#### reobf-mappings-patch.tiny

https://github.com/PaperMC/Paper/blob/master/build-data/reobf-mappings-patch.tiny

### Are there any alternatives?

Not at this time until the PaperMC dev has time to fix.

### Anything else?

Temporary patch to resolve Issue with mappings.

**Comment by NotMyFault** [comment]
It appears you do not understand how mappings work, Fawe cannot magically remap something on your server to a different value.
