### ISSUE TITLE
Problem with loading schematics

### ISSUE THREAD

**Issue by 27chandler** [IntellectualSites/FastAsyncWorldEdit#1160]
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

When attempting to paste a schematic from 1.16, I found that FAWE was unable to load the schematic and produced an error.

### To Reproduce

1. Save a schematic in 1.16
2. Update to 1.17
3. Attempt to load the schematic
4. Observe the error

### Expected behaviour

The schematic should load properly without any errors

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/19729460/124116681-20b2af80-da67-11eb-8a37-83a5471ca714.png)
![image](https://user-images.githubusercontent.com/19729460/124116719-2b6d4480-da67-11eb-960f-56e1e9a34dd8.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/7deaa068369a4039aa8e2959278d5e12

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ffb069503d4248649153e033e9e674ea

### Fawe Version

FastAsyncWorldEdit version 1.17-28;5073532

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

**Comment by jt47915** [comment]
This is also true for the Fabric build
