### ISSUE TITLE
Cannot load old huge schematic file

### ISSUE THREAD

**Issue by FolfyBlue** [IntellectualSites/FastAsyncWorldEdit#1167]
### Server Implementation

Spigot

### Server Version

1.17.+

### Describe the bug

I have a schematic file of a very old map, which I believe uses the MCEdit schematic format. Upon loading the schematic, I get a console error asking me to report it.

### To Reproduce

1. Download this schematic: https://folfy.blue/i/Woosh2_xs4y7mqgte.schematic
2. Try to load it using FAWE
3. See the error

### Expected behaviour

For the schematic to load and then being able to paste it

### Screenshots / Videos

https://folfy.blue/i/javaw_3ba821a699_oiplbopbqw.png

### Error log (if applicable)

https://paste.gg/p/anonymous/aa0210cd444d494684d24603dd17f376

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/cdf46c79539e4058a8775a4b0bb4c41e

### Fawe Version

1.17-42;35b1202

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

Schematic: https://folfy.blue/i/Woosh2_xs4y7mqgte.schematic

**Comment by NotMyFault** [comment]
Do you use a datapack with custom word height?

**Comment by FolfyBlue** [comment]
No, the only datapack there is is used to create new loot chests and doesn't change anything else

**Comment by Tsoccerguy3** [comment]
![2021-07-18_12 25 30](https://user-images.githubusercontent.com/22108822/126075562-8e312ac7-b8f0-4154-b3ad-a67fef27630e.png)
![2021-07-18_12 25 57](https://user-images.githubusercontent.com/22108822/126075563-222c30c0-eff6-4aa9-ad61-03f7a52f2f6a.png)

Confirm serious bug
To recreate this bug log onto Paper 1.17.1 build 112 server
select pos
//copy
//rotate
//paste

**Comment by Tsoccerguy3** [comment]
Do not use the //rotate command until this bug is fixed . It just does not work

**Comment by Tsoccerguy3** [comment]
Just tested this fix using FastAsyncWorldEdit-Bukkit-1.17-63 , I can confirm that the copy , rotation and past is not fixed
[Paper server log.txt](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6844317/Paper.server.log.txt)
Same as before , broken
