### ISSUE TITLE
some mistake, I don't understand, sorry)

### ISSUE THREAD

**Issue by rkfsociety** [IntellectualSites/FastAsyncWorldEdit#1170]
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

...

### To Reproduce

when starting the server

### Expected behaviour

...

### Error log (if applicable)

https://pastebin.com/4W6NxXYA

### Fawe Debugpaste

I have disabled it for now, as it just doesn't work.

### Fawe Version

the latest version is on 2021-07-07

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
1.17.1 is not supported yet. For future reference, don't put `...` in a field but actually provide the information requested.

**Comment by rkfsociety** [comment]
unfortunately, I don't understand what should be written there, either Google translates strangely, or I'm stupid, most likely the second, I'm sorry.
