### ISSUE TITLE
Reading schematic in 1.17.1 causes error

### ISSUE THREAD

**Issue by Pugabyte** [IntellectualSites/FastAsyncWorldEdit#1171]
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

Using the `feature/1.17.1` branch at commit https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/565b7a56cab3c561d5293d1a97ca305ffda2de17 on our test server, we are experiencing this error when trying to load a schematic: https://paste.projecteden.gg/fepuh.yml

Schem file: https://dl.projecteden.gg/wither_arena.schem

### To Reproduce

1. Download the schematic
2. Install correct FAWE build on 1.17.1 Paper server
2. //schem load wither_arena

### Expected behaviour

Schematic loads properly

### Error log (if applicable)

https://paste.projecteden.gg/fepuh.yml

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b45078a4613946f4b380787f39cd65e1

### Fawe Version

FastAsyncWorldEdit 1.17-565b7a5

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

I know the branch isn't supported yet, just wanted to report the bug to help out in the update process

**Comment by NotMyFault** [comment]
That branch is not meant to be used yet.

**Comment by Pugabyte** [comment]
@NotMyFault Would you mind throwing a FAWE jar with that update at me? That project won't compile for me, I tried a few things but I'm not sure what I'm doing wrong.

Thank you!
