### ISSUE TITLE
[1.17] //stack <amount> only stacks onces

### ISSUE THREAD

**Issue by StealWonders** [IntellectualSites/FastAsyncWorldEdit#1178]
### Server Implementation

Tuinity

### Server Version

1.17.+

### Describe the bug

Selecting anything and then executing //stack <amount greater than 1> only stacks your selection once instead of the number of times you really want.

### To Reproduce

Select region -> Execute stack command -> Error :-(

### Expected behaviour

Stack the amount of times I tell it to stack

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/6114858/125270257-c5f04200-e309-11eb-81c1-0acce50d7f2c.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c9af650474004daba49c01dde937c78a

### Fawe Version

Bukkit-Official (1.17-49; 41073bb)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by Tsoccerguy3** [comment]
I have verified that this also happens on all builds for 1.17.1 b49 to present . Staying on build 48 for now , but it has its own issues with rotating and flipping stairs.

**Comment by LaurenceBarnes** [comment]
that issue with rotating and flipping stairs has been fixed in newer builds already

**Comment by Tsoccerguy3** [comment]
> 
> 
> that issue with rotating and flipping stairs has been fixed in newer builds already

That"s what I said .
