### ISSUE TITLE
90 degrees rotations with doors not working

### ISSUE THREAD

**Issue by pascal541** [IntellectualSites/FastAsyncWorldEdit#1179]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

A selection doesn't paste completely when rotating 90 or 270 degrees a selection which contains any door

### To Reproduce

1. Create a selection which include a door
2. Copy the selection
3. Use //rotate 90
4. Use //paste

### Expected behaviour

I expect the doors to rotate normally

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/7486865/125277867-47e46900-e312-11eb-9024-178856d7075b.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/178ec515aa80427796b02360394d6667

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bf794802836c497c90dfc2f356819e3e

### Fawe Version

FastAsyncWorldEdit version 1.16-734;78acb85

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Fawe.

**Comment by LaurenceBarnes** [comment]
>  I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

why did you tick that off when you obviously did not use the newest build?
also you gotta use these builds https://ci.athion.net/job/FastAsyncWorldEdit-1.17/
