### ISSUE TITLE
//drain

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/FastAsyncWorldEdit#118]
# Bug report for FastAsyncWorldEdit 1.13.x
**Debug paste link**:

https://incendo.org/paste/view/1e79d2bcafed4d48a43243ed7317cfa6

**Description of the problem:**

Draining an area doesn't get a rid of seagrass. Well, that makes sense as seagrass isn't water but if you try to drain a river and everywhere stays seagrass it can be a bit annoying.
A flag to remove seagrass on draining looks quiet handy.
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
//drain -p exists now
