### ISSUE TITLE
Console Error - Failed to initialize integration

### ISSUE THREAD

**Issue by TimGraham777** [IntellectualSites/FastAsyncWorldEdit#1182]
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

Get this error in console:
13.07 12:35:13 [Server] WARN Failed to initialize integration. Is FastAsynchWorldEdit up to date?
13.07 12:35:13 [Server] WARN java.lang.NoClassDefFoundError: com/boydti/fawe/regions/FaweMaskManager
13.07 12:35:13 [Server] WARN at me.angeschossen.lands.integration.Ftlnw.Ftlnw(?:30)
13.07 12:35:13 [Server] WARN at me.angeschossen.lands.Lands.Ftlnw(?:371)
13.07 12:35:13 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
13.07 12:35:13 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
13.07 12:35:13 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
13.07 12:35:13 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
13.07 12:35:13 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
13.07 12:35:13 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
13.07 12:35:13 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
13.07 12:35:13 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
13.07 12:35:13 [Server] WARN Caused by: java.lang.ClassNotFoundException: com.boydti.fawe.regions.FaweMaskManager
13.07 12:35:13 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
13.07 12:35:13 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
13.07 12:35:13 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
13.07 12:35:13 [Server] WARN ... 10 more

### To Reproduce

Server start produces error

### Expected behaviour

No console error.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2ad0361ef3fc4d45baab24048184d02d

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-52.jar	

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
> 13.07 12:35:13 [Server] WARN java.lang.NoClassDefFoundError: com/boydti/fawe/regions/FaweMaskManager
13.07 12:35:13 [Server] WARN at me.angeschossen.lands.integration.Ftlnw.Ftlnw(?:30)
13.07 12:35:13 [Server] WARN at me.angeschossen.lands.Lands.Ftlnw(?:371)

Named plugin needs to update their integration. Report it to them.
