### ISSUE TITLE
Error of pasting something had set //rotate -90 , 90 , 45 and -45 

### ISSUE THREAD

**Issue by IAMGOLFz** [IntellectualSites/FastAsyncWorldEdit#1192]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hello.. I will report something error in FAWE, it paste something had set rotate 45, -45, 90 and -90 otherwise 180 and -180 and I get something had pasted and it broke.... I want to know how to fix it for //rotate 

### To Reproduce

1. I will //pos1 and //pos2 on structure
2. Then //copy and //schem save [name]
3. Then //schem load [name] and //rotate 90, -90, -45 or 45
4. Finally I //paste and it error early.

### Expected behaviour

I think different version between PAPER 1.16.5 and FAWE 1.17

### Screenshots / Videos

![rotate -90  2](https://user-images.githubusercontent.com/85722884/126594468-66e41774-22ec-4cde-924c-bfa22c6dab78.png)
![rotate 90  2](https://user-images.githubusercontent.com/85722884/126594484-e36aa561-cc2a-4c4b-9fb9-99d4effce931.png)
![rotate -90](https://user-images.githubusercontent.com/85722884/126594491-41ac3cda-bffd-48c3-a91d-12637fa17daf.png)
![rotate 90](https://user-images.githubusercontent.com/85722884/126594507-b8b29ab8-ef7f-4996-b2e5-b25860970a89.png)
![Screenshot 2021-07-22 124559](https://user-images.githubusercontent.com/85722884/126595223-0286bc11-abfb-4fbe-acff-cacd7df0c1a2.png)

### Error log (if applicable)

java.lang.ArrayIndexOutofBoundsException: Index -1 out of bounds for length 17113

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/26bb1221ef28488fa354c1aa94e05178

### Fawe Version

FastAsyncWorldEdit1.17-05;6d360db

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Why would you tick the box saying you're using the latest version when you're not...

**Comment by IAMGOLFz** [comment]
I edited it

**Comment by IAMGOLFz** [comment]
> Why would you tick the box saying you're using the latest version when you're not...

I edited it. I got suggestions this version of FAWE support with Arceon from Arcaniax

**Comment by dordsor21** [comment]
So why don't you now do what it says ...???? I thought that was obvious

**Comment by IAMGOLFz** [comment]
> So why don't you now do what it says ...???? I thought that was obvious

Sorry. must I do what next? I used latest version of FAWE for 1.16.5 before I will install Arceon but it didn't happen this problem while I installed Arceon and have this problem after 12 July. I didn't suspect it but I found for 1 hours before report it....... I just know how to fix it..

**Comment by dordsor21** [comment]
You're not using the latest version of FAWE so update it... Again I thought that was quite obvious

**Comment by IAMGOLFz** [comment]
> You're not using the latest version of FAWE so update it... Again I thought that was quite obvious

Thank you so much, it worked :)
