### ISSUE TITLE
Support for custom biomes

### ISSUE THREAD

**Issue by ThereIsNoLogic** [IntellectualSites/FastAsyncWorldEdit#1193]
### What feature do you want to see added?

In 1.16 Mojang was added the feature to create your own biomes with datapacks. And there is also the ability to create your own biomes programmatically: https://www.spigotmc.org/threads/how-to-create-custom-biomes.512105/

It would be great if FAWE could work with custom biomes (now fawe can work only with default minecraft biomes). You can do some cool things with this:
![2021-07-20_23 38 39](https://user-images.githubusercontent.com/53514252/126615711-727b598d-8e02-48a7-b91f-fcfd0c8b67ea.png)

![2021-07-19_23 57 41](https://user-images.githubusercontent.com/53514252/126615691-dab15228-60cb-437b-944a-b32dc3bb1dc5.png)
![2021-07-20_00 28 47](https://user-images.githubusercontent.com/53514252/126615699-96f18665-8d36-43ab-9e04-54345e4c985e.png)
![2021-07-20_20 02 10](https://user-images.githubusercontent.com/53514252/126615700-435b95b1-cb83-4802-a59e-b2c801570365.png)
![2021-07-20_20 02 50](https://user-images.githubusercontent.com/53514252/126615703-6910696e-761b-4bf9-98df-e88c930ab803.png)
![2021-07-20_20 06 32](https://user-images.githubusercontent.com/53514252/126615705-eadd17b9-77d4-4241-8fcc-5e1c654aba4e.png)

### Are there any alternatives?

There's no alternatives I guess.

**Comment by dordsor21** [comment]
This should now work as long as biomes are registered before FAWE is loaded. Otherwise, using `BiomeType.REGISTRY.register("key:biome", new BiomeType("key:biome"))` will be required.
