### ISSUE TITLE
Extensible region system

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/FastAsyncWorldEdit#1198]
### What feature do you want to see added?

Not sure if I'm asking the right question, but does FAWE have an extensible region hooking system?  Like, if we are using a custom made plugin to manage build areas (worlds, plots, etc) that FAWE is agnostic to, can it "be taught" what the regions are and who can build in them so we can still use region restrictions and not fawe.bypass?

### Are there any alternatives?

This is more of a question than a feature request but was probably too obscure to answer in Discord.

**Comment by dordsor21** [comment]
Answered on Discord
