### ISSUE TITLE
Can no longer edit inside towny claim. Likely Towny Updated API.

### ISSUE THREAD

**Issue by SoraShiunin** [IntellectualSites/FastAsyncWorldEdit#1201]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

 FAWE is working perfectly except in town claims with towny.
 I get an error when someone tries to edit inside their claim and nothing happens.
Guess towny updated their API.

### To Reproduce

1. Try to edit your towny claim (Without admin permissions etc)
2. Nothing will happen and an error is generated.

### Expected behaviour

The edit would go through.

### Error log (if applicable)

https://gist.github.com/SoraShiunin/f3fb4e4945ad19d7e61921e148213955

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/16838198e1334016ba4c222076a14858

### Fawe Version

FastAsyncWorldEdit version 1.17-101;d62a1b5

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by MattBDev** [comment]
Towny recently updated their API. I think that dropping support for old versions of Towny and updating to the new API is the best course of action.
