### ISSUE TITLE
Getting .schematic file instead .schem file by downloading with //download in Minecraft 1.13+

### ISSUE THREAD

**Issue by IAMGOLFz** [IntellectualSites/FastAsyncWorldEdit#1203]
### What feature do you want to see added?

Hello :]
 **I don't know** this has or not this feature who I will request and it is get .schematic file instead .schem file via //download like **Builder's Refuge in 1.12.2**. I think it might better because if who is builder want to get .schematic just make animation or render his project for Minecraft 1.13 or above...

Thank you.....  

### Are there any alternatives?

if it had alternative about editing FAWE configuration for this feature, I do this follow you feedback but it hasn't I might have 2 alternatives are :
1. Adding specially command in FAWE 1.13+ can convert some schematic I want to convert from .schem to .schematic before use //download it.
2. Adding specially website for convert .schem to .schematic in Minecraft 1.13+  

For 2 alternatives, if it can't edit configuration in plugin directly....

**Comment by NotMyFault** [comment]
While writing this, we're in the middle of getting another schematic version revision. A converter is unnecessary and wont work out well for all caveats like datapack biomes, custom tags or simple meta. If you want to receive a .schematic file, use a version prior to 1.13.

**Comment by IAMGOLFz** [comment]
> While writing this, we're in the middle of getting another schematic version revision. A converter is unnecessary and wont work out well for all caveats like datapack biomes, custom tags or simple meta. If you want to receive a .schematic file, use a version prior to 1.13.

OK, Thank you ☺️
