### ISSUE TITLE
Allowed Regions API is broken

### ISSUE THREAD

**Issue by RelocationDev** [IntellectualSites/FastAsyncWorldEdit#1206]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Whenever I set a sphere in my world it goes out of the allowed regions I set using the FastAsyncWorldEdit API.

Here's my code:
`esBuilder.allowedRegions(new RegionWrapper(min.getBlockX(), min.getBlockY(), min.getBlockZ(), max.getBlockX(), max.getBlockY(), max.getBlockZ()));`

### To Reproduce

Set blocks using the API and set allowed regions with the code above.

### Expected behaviour

For it to set the blocks without going outside of the allowed regions.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/62983431/127720822-989beaad-a58f-4cf8-9de5-26d6f9609843.png)

### Error log (if applicable)

No errors.

### Fawe Debugpaste

"No such method error"

### Fawe Version

Latest

### Checklist

- [ ] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

No.

**Comment by NotMyFault** [comment]
Make sure to fill out the issue template and checklist properly.
