### ISSUE TITLE
EditSession#moveRegion not working (API bug)

### ISSUE THREAD

**Issue by noah-iversen** [IntellectualSites/FastAsyncWorldEdit#1209]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When attempting to use EditSession#moveRegion, it does not move the blocks at all. However, using the //move (which uses the exact same function) works as expected.

The region is a valid CuboidRegion, so rule that out. The region coordinates are also correct.

Here is my code:
`				if (region != null) {  
					EditSessionBuilder sessionBuilder = new EditSessionBuilder(FaweAPI.getWorld(player.getWorld().getName()));
					sessionBuilder.fastmode(true);
					EditSession editSession = sessionBuilder.build();
					editSession.moveRegion(region, BlockVector3.UNIT_MINUS_X, 10, false, null);
					player.sendMessage("Moved " + editSession.moveRegion(region, BlockVector3.UNIT_MINUS_X, 10, false, null) + " blocks");
				} `

I receive the sent message with the correct amount of blocks... but nothing happens to the blocks within the region.

### To Reproduce

Create a valid CuboidRegion
Create an EditSession
Attempt to use moveRegion() to move the blocks

### Expected behaviour

The blocks within the region were expected to move 10 blocks in the -X direction.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/98668a33fff54a2997e08f9042ee5037

### Fawe Version

version 1.17-103;9f3a451

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

To give broader context, I'm attempting to spawn a schematic, create a region from it, and the move the blocks within that region.

Here is the full snippet of code:

```	
		if (args.length == 0) {

				File file = new File(Nations.getInstance().getDataFolder() + "/schematics/ship.schem");

				try {
					ClipboardFormat format = ClipboardFormats.findByFile(file);
					ClipboardReader reader = format.getReader(new FileInputStream(file));
					Clipboard clipboard = reader.read();
					EditSessionBuilder builder = new EditSessionBuilder(FaweAPI.getWorld(player.getWorld().getName()));
					builder.fastmode(true);
					EditSession editSession = builder.build();
					Operation operation = new ClipboardHolder(clipboard).createPaste(editSession)
							.to(BlockVector3.at(location.getX(), location.getY(), location.getZ())).copyEntities(true)
							.ignoreAirBlocks(true).build();
					Operations.complete(operation);
					
					editSession.flushQueue();
					player.sendMessage(ChatColor.GREEN + "Placed!");

					region = new CuboidRegion(FaweAPI.getWorld(player.getWorld().getName()), clipboard.getMinimumPoint(), clipboard.getMaximumPoint());

				} catch (FileNotFoundException e) {
					player.sendMessage(ChatColor.RED + "Schematic not found.");
				} catch (IOException e) {
					player.sendMessage(ChatColor.RED + "Could not read schematic file.");
				}
			} else if (args[0].equalsIgnoreCase("move")) {

				if (region != null) {  
					EditSessionBuilder sessionBuilder = new EditSessionBuilder(FaweAPI.getWorld(player.getWorld().getName()));
					sessionBuilder.fastmode(true);
					EditSession editSession = sessionBuilder.build();
					player.sendMessage("Moved " + editSession.moveRegion(region, BlockVector3.UNIT_MINUS_X, 10, false, null) + " blocks");
				} 
			}
```

**Comment by SirYwell** [comment]
`EditSession` is `AutoClosable` and needs to be handled like that. Use a `try-with-resources` statement

**Comment by noah-iversen** [comment]
> `EditSession` is `AutoClosable` and needs to be handled like that. Use a `try-with-resources` statement

I got it working. There's no bug, thanks for your help.
