### ISSUE TITLE
java.lang.NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by andreasdc** [IntellectualSites/FastAsyncWorldEdit#1210]
### Server Implementation

Paper

### Server Version

1.15.2

### Describe the bug

java.lang.NoSuchFieldException: modifiers
when running fawe
fix java 16
then stop updating

### To Reproduce

fix java 16
then stop updating

### Expected behaviour

fix java 16
then stop updating

### Fawe Debugpaste

fix java 16 then stop updating

### Fawe Version

fix java 16 then stop updating

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

fix java 16
then stop updating

**Comment by andreasdc** [comment]
@SirYwell why don't you just add simple support for this java version?

**Comment by SirYwell** [comment]
Why don't you fill out the template properly?

**Comment by andreasdc** [comment]
> Why don't you fill out the template properly?

Why don't you let people use outdated versions of plugin at their own risk by simply adding java support/fixing reflections?

**Comment by MattBDev** [comment]
> > Why don't you fill out the template properly?
> 
> Why don't you let people use outdated versions of plugin at their own risk by simply adding java support/fixing reflections?

The code is open source an hosted on a separate repository. Feel free to go ahead and add Java 16 support for that version and submit a PR.
