### ISSUE TITLE
Wooden axe sometimes doesn't work

### ISSUE THREAD

**Issue by cui0v0** [IntellectualSites/FastAsyncWorldEdit#1214]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Wooden axe sometimes doesn't work

### To Reproduce

1.Use wooden axe to select pos.
2.Doesn't work.

### Expected behaviour

Wooden axe can work properly when select pos.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1ad7a804308142fab304fe4a4aef37f0

### Fawe Version

FastAsyncWorldEdit version 1.17-108;3ccb5e0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Cannot replicate based on the information provided, `//wand` -> right/leftclick always worked out of the box.
