### ISSUE TITLE
Chunk Saving Issues when using FAWE

### ISSUE THREAD

**Issue by hamcoremusic** [IntellectualSites/FastAsyncWorldEdit#1216]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When doing big FAWE edits, our team encounters issues when where they relog all of their blocks disappear and their work is effectively gone. This has been present through 1.17 version 90-107 of FAWE.

They can make a full 200x200 build and only 1/4 of it will save on default PaperMC settings.

On top of that, we have seen it produce ghost blocks below where a brush wont fix it but everything around it (no mask enabled). Please see this GIF of me using the wand's right and left click on the affected area: https://gfycat.com/ChiefMeatyGerbil

I am trying to pinpoint exactly what is causing this, but I fear it might be FAWE not actually writing the blocks into the chunks properly.

### To Reproduce

For the ghost blocks specifically:

1. `//set gold` on a bigger area
2. VoxelSniper `/b e lift`
3. Some `//br height
4. The copy, flipped, and pasted the same mountain design to the other side

For the ones where whole builds don't save after a 100% clean shutdown, its effectively just a full build made mostly with FAWE then on a relog the blocks dissapear.

### Expected behaviour

For both scenarios, we would expect the blocks to stay where they need to be rather than delete or become ghost blocks.

### Screenshots / Videos

As noted above, here is the ghost block issue when clicking on it with a wand https://gfycat.com/ChiefMeatyGerbil

**As for the build that wiped itself (this has happened multiple times):**

Before: 
![whatitshouldbe](https://user-images.githubusercontent.com/28895283/128405702-54766dbb-a6cc-44e0-9f41-52acd82e73a7.png)
After:
![XC4oLuthgQVVTmKQENDNbR](https://user-images.githubusercontent.com/28895283/128405718-9b81920c-0edb-4f86-b66e-ed2be0598de0.png)

### Error log (if applicable)

N/A

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d3c4a35f858f4bc3a65d91d27194b46a

### Fawe Version

FastAsyncWorldEdit version 1.17-107;2bcf3ee

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

Since this plugin pretty much every day it's hard to test the current version (even though I marked it as such). I will update now and see if that's still happening.

**Comment by NotMyFault** [comment]
- `//set gold` is not accepted, because it's not a valid material.
- Use an up to date version Favs https://dev.bukkit.org/projects/favs/files/3401615
- Try to reproduce without any other plugins but Fawe & Favs and a a clean Fawe history folder.

**Comment by hamcoremusic** [comment]
> * `//set gold` is not accepted, because it's not a valid material.
> * Use an up to date version Favs https://dev.bukkit.org/projects/favs/files/3401615
> * Try to reproduce without any other plugins but Fawe & Favs and a a clean Fawe history folder.
> 
> > **[Attention Required! | Cloudflare](https://dev.bukkit.org/projects/favs/files/3401615)**

Thats my bad I meant `gold_block`! But I will do that now.
