### ISSUE TITLE
Issues with //regen on Purpur

### ISSUE THREAD

**Issue by DebugOk** [IntellectualSites/FastAsyncWorldEdit#1218]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

Using //regen more then once after a restart will cause it to throw an error, this only happens on Purpur and not on any other upstream versions. I've tested both Paper and Tuinity and neither have this issue.

### To Reproduce

1. Have used //regen at least once since restart
2. Make an selection
2. Run //regen

### Expected behaviour

Fawe regenerates the chunk without any issues

### Error log (if applicable)

https://pastebin.com/raw/MPLm8bLu

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1b7fe8d344554a2da9548648c10b11e9

### Fawe Version

FastAsyncWorldEdit version 1.17-111;14b3fd2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

I found that Purpur [adds this patch](https://github.com/pl3xgaming/Purpur/blob/ver/1.17.1/patches/server/0216-Populator-seed-controls.patch#L10), which I think may be the issue because it modifies the biome object. There are 2 other patches that also mess with world generation but I'm not so sure which one it is ([Patch 2](https://github.com/pl3xgaming/Purpur/blob/ver/1.17.1/patches/server/0086-Configurable-feature-seed-settings.patch) [Patch 3](https://github.com/pl3xgaming/Purpur/blob/a8ea5b179ba2bdf3aa237858e784f5be4fb040e1/patches/server/0225-Structure-seed-options.patch#L15)), I didn't find either of these upstream too.

I hope I got everything down right

**Comment by NotMyFault** [comment]
Touches #1226 but appears to be a Purpur issue as it works on every other fork (that does not include or is Purpur).
