### ISSUE TITLE
Build 123 not using certain //br commands

### ISSUE THREAD

**Issue by YourSenpaiOnly** [IntellectualSites/FastAsyncWorldEdit#1224]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When using //br spline or a few other commands I get the option to tab complete the command but I cant use them. Instead I am told that it is an invalid sub command.

### To Reproduce

1. //br spline
2.  Invalid sub command. Options forest, butcher, paint, none, clipboard, gravity, heightmap, extinguish, sphere, raise, smooth, cylinder, set apply, deform, lower, snow, biome.

### Expected behaviour

1. //br spine 100
2. Spline brush quipped

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f31c7867ce7345cd9d14063c4debb530

### Fawe Version

Version 1,17-123;57f7c93

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
> [09:27:09] [Server thread/WARN]: `plugins/FastAsyncWorldEdit-Bukkit-1.17-123.jar provides `WorldEdit' while this is also the name of `plugins/worldedit-bukkit-7.2.6-beta-02.jar' in `plugins'
> [09:27:13] [Server thread/WARN]: You installed WorldEdit alongside FastAsyncWorldEdit. That is unneeded and will cause unforeseen issues, because FastAsyncWorldEdit already provides WorldEdit. Stop your server and delete the 'worldedit-bukkit' jar from your plugins folder.

**Comment by YourSenpaiOnly** [comment]
I just took a look into it and was about to close this tread thank you.
