### ISSUE TITLE
Fawe - PlotSquared

### ISSUE THREAD

**Issue by Blocky38** [IntellectualSites/FastAsyncWorldEdit#1225]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

On regenerating the roads for the allready created Chunks fawe is printing out many warnings and the server is crashing.

### To Reproduce

1. Create Plot World with PlotSquared v6
2. Build a custom Road 
3. Create the Road schematic with `/plot createroadschematic`
4. Execute `/plot regenallroads <world>` to regenerate the roads of the already created Chunks.
5. Look into console.

### Expected behaviour

Fawe shouldn't print out warnings to the console and the server shouldn't crash.

### Error log (if applicable)

https://gist.github.com/Blocky38/b5836166c51416528206049fa9c4873d

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ebf5a15292cf4bb4b0aa63b47f639c22

### Fawe Version

1.17-134;3e4f1d5

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by Blocky38** [comment]
I saw, that the warnings / NullPointerException is comaing too, when new chunks are created with this schematic.

**Comment by NotMyFault** [comment]
Update Paper, a fix for that has been backported to 1.16.5. However, that has been fixed natively within 1.17.
