### ISSUE TITLE
/p swap doesnt move the content of the plot

### ISSUE THREAD

**Issue by crafter23456** [IntellectualSites/FastAsyncWorldEdit#1227]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

PlotSquared Paste: https://athion.net/ISPaster/paste/view/9a9103e0ee744395945e7d70344a9ee0
(There is an error in the log caused of swapping)

When I swap or move a plot the content and the boarder of the plot doesnt move with it.

### To Reproduce

1. Stand on a plot
2. Type /p swap ID
3. See that only the owner changes but not the content or boarder

### Expected behaviour

That like in v5 of PlotSquared the plot goes with the owner.

### Error log (if applicable)

https://paste.gg/p/anonymous/40b394e43d41427d997433c4f3a64f8f

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0760dc86ed2e45e9a2b74c6319940aed

### Fawe Version

1.17 build 134

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/c65c72b249c9fceb85f2e909233722dcdac4ed52
