### ISSUE TITLE
Chunk Rendering Issue after operations in chunks with complex block palettes

### ISSUE THREAD

**Issue by CS-Birb** [IntellectualSites/FastAsyncWorldEdit#1228]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

Worldedit operations affecting some chunks appear to "corrupt" the chunk. The chunk is fine serverside, but will not render on the player's end. On the client's end, an `ArrayIndexOutOfBoundsException` is thrown - seemingly in `net.minecraft.util.palette.ArrayPalette::read(PacketBuffer buf)`

The issue appears specific to chunks with sections that have large block palettes - In my case this was found where there were 255+ disctinct blocked, or 9 bits per index.

Selecting the large section and using `//set air` or even using `//replace` to remove blocks from the palette until it's smaller appears to resolve the issue, though further operations may cause the issue to occur again.

Copying the non-rendering chunk to a new location or different world causes the same issue - so long as it's still aligned to chunk borders (thus not splitting the palette up)
After a restart the chunk renders again.

Reproduced on 1.16.5 Spigot, 1.16.5 Paper and both 1.16.5 Purpur and 1.17.1 Purpur.
Each only had FAWE installed, and I have been unable to reproduce with solely WE.

### To Reproduce

[world.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6986097/world.zip)

1. Load the attached world in a 1.16.5 or 1.17 Spigot, Paper or Purpur server w/ FAWE installed
2. Perform `//snow 30` or other worldedit operation next to the chunk at `0x, 0z` 
3. See that the chunk no longer renders correctly. If no changes are visible, relog.
4. Optionally, perform `//undo`. While the snow will be removed, the chunk does not render correctly.
5. Select Section 4 (0,64,0 to 15,79,15) on the attached chunk, and set it to Air
6. Watch as the rest of the chunk magically appears.

### Expected behaviour

For chunks to remain rendered following Fast Async Worldedit operations, without need for Restart

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/5267414/129439067-1e790c2f-05a9-49d6-86e3-55e6a56aef23.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dfd3324a75184dbfb0dbad7c0d4acf94

### Fawe Version

FastAsyncWorldEdit version 1.17-137;98673b5

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

Have experienced this issue sporadically for a while, but only recently had the patience to try and debug and find a reliable reproduction. 
Happy to help reproduce and debug further as needed.

**Comment by dordsor21** [comment]
Please provide the actual error stacktrace

**Comment by CS-Birb** [comment]
Vanilla clients do not seem to produce a stacktrace rendering these areas, though they most certainly render things incorrectly.

Logs for earlier reproduction of this bug, on 1.16.5 Fabric w/ Optifine & Optifabric: https://gist.github.com/CS-Birb/af0f16f3ee50be69e7b6ba6768a024d4

Unable to produce any Stacktraces on 1.17.1 with Standalone Optifine (Despite reproducing the errored rendering), but do get the same AIOOB with 1.17.1 Fabric w/ Optifine & Optifabric. https://gist.github.com/CS-Birb/9cd94ac456a7b121f1b3f35d76bbacf5 (Solely the relevant stacktrace provided, as 1.17.1 Optifine currently throws countless IllegalAccessExceptions prior to logging in)

As the stack trace is so specific to Fabric + Optifine, I'm not confident in how helpful it'll be in debugging the issue.
