### ISSUE TITLE
Issues with `//count *` and its tab completion

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#1231]
Likely some regression or a happy coincidence with our recent transormers and patterns pr (or nobody reported it previously)
On tab: https://paste.gg/p/anonymous/e8e1f37f13bf4876b34dd9bfcd888dd0
On command execution: https://paste.gg/p/anonymous/516c4762b1e34e65acae21f37931d450

**Comment by dordsor21** [comment]
I literally just fixed this lol

**Comment by NotMyFault** [comment]
For the record, resolved in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/443c86e29a34f89f2c72c10e8f404f82b40c0232
I didn't look at other issues today yet lol

**Comment by dordsor21** [comment]
I fixed it cos I found it while looking at #1230
