### ISSUE TITLE
Custom Chunk creating problem

### ISSUE THREAD

**Issue by OverBrave** [IntellectualSites/FastAsyncWorldEdit#1233]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

FAWE custom chunk creating not working, at least with PlotSquared. But if i use vanilla WorldEdit, chunk perfectly creates.

### To Reproduce

Try to create new plot world with PlotSquared plugin.

### Expected behaviour

Chunks should have formed without problems.

FAWE:
![image](https://user-images.githubusercontent.com/47111280/129916330-c7aab0d7-80ce-4e80-b72c-4f5aa1576eae.png)
![image](https://user-images.githubusercontent.com/47111280/129916418-b176d4e5-9cf3-4922-95f3-f88393977de5.png)

After Use vanilla WE:
![image](https://user-images.githubusercontent.com/47111280/129916389-d3818b26-5935-4a79-a501-a4d7ffd66751.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/938eadb5fd0748939228bb8d691d712b

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-160

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Fixed in ecaa99f93d1debf624f42c024c06e64291f5c8fe and f412796f28f438f766b5389d07bdeab09d7f0b3c
