### ISSUE TITLE
NoSuchFileException

### ISSUE THREAD

**Issue by Blocky38** [IntellectualSites/FastAsyncWorldEdit#1235]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When loading an schematic trough `//schematic list` autocomplete `//schematic load ../brr_1.schematic` there is an error in the console and MY server is crashing (I don't know if it is coming from this bug).

### To Reproduce

1. Paste an schematic in the FastAsyncWorldEdit/schematics/ directory (Unix / Linux)
2. /schematic list
3. Click on the schematic to load it
4. Look into console.

### Expected behaviour

No Warning in the Console (and no server crash.)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/40493ae67ee24a14a18fc545acfadfc6

### Fawe Version

1.17-160;188e4b6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

I don't know if this is a bug from worldedit itself, but I reported it here, because in the error is the fastasyncworldedit directory.

**Comment by NotMyFault** [comment]
Disable per player schematics or utilize it.

**Comment by Blocky38** [comment]
What do you mean with "utilize"?

**Comment by NotMyFault** [comment]
You have per player schematics enabled so Fawe won't bother looking in other/the root schematic directory. Disable it or put in your dedicated schematics folder matching your UUID.

**Comment by Blocky38** [comment]
Thanks. It would be nice if there will be added any check, that prints to the player, that the schematic wasn't found.

**Comment by NotMyFault** [comment]
>  It would be nice if there will be added any check, that prints to the player, that the schematic wasn't found.

That's what the exception is for.

**Comment by Blocky38** [comment]
But when any Builder from my team loads an schematic he doesn't see the console of the server with the exception. Thanks, for the fast support.

**Comment by NotMyFault** [comment]
The exception header also appears ingame. Reading is key.
