### ISSUE TITLE
"/br shatter" does not work

### ISSUE THREAD

**Issue by muterulo** [IntellectualSites/FastAsyncWorldEdit#1239]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

The command "/br shatter magma_block" throwing errors in the server consol and does not work

### To Reproduce

1. apply /br shatter magma_block 20 20
2. try to use it

### Expected behaviour

should shatter the area

### Error log (if applicable)

https://paste.gg/p/anonymous/309ea7c05f1240608065edd563db1f42

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/39cd1c20d40c454584b28cbe0fe88a86

### Fawe Version

FastAsyncWorldEdit version 1.17-160;188e4b6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Should be fixed by 563ad7761a6724bb141385e94456e8ea80ca9905
