### ISSUE TITLE
Not working Extent

### ISSUE THREAD

**Issue by Gnacik** [IntellectualSites/FastAsyncWorldEdit#1242]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Im using EditSessionEvent to add own Extend and override setBlock() to check what blocks are modified by user after schematic paste. Everything working in clean WorldEdit, but after installing FAWE if got warning:

https://clip2net.com/s/4d49B3T

after adding my plugin into allowed list in FAWE config warning is no longer displayed, but setBlock() is not called at all.

ps. there is info 'for block logging is recommended to use faweAPI but i dont see any methods in faweAPI to add extent and/or check what blocks are modified...

### To Reproduce

1.

### Expected behaviour

override setBlock should be called

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1450fba54640429ca2e09e6561bd4663

### Fawe Version

FastAsyncWorldEdit version 1.17-164;cf68caf

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Make sure to override both setblock methods (BlockVector3 and int, int, int). Without seeing your code we cannot know that this is a bug. Assume incorrect usage of API as it works for others.

**Comment by Gnacik** [comment]
on server start:

`WorldEdit.getInstance().getEventBus().register(new WorldEditSchematicListener(this));`

and WorldEditSchematicListener code here:  https://pastebin.com/fxAiTe8t

working on clean WorldEdit.
