### ISSUE TITLE
FAWE issue with (pl3xmap)-Griefprevention load order

### ISSUE THREAD

**Issue by ZDaPlaY** [IntellectualSites/FastAsyncWorldEdit#1244]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

When the fastasyncworldedit is put on the server the pl3xmap addon called pl3xmap-Griefprevention loads before the GriefPrevention and should load after for it to work

### To Reproduce

There is no error

### Expected behaviour

When the fastasyncworldedit is put on the server the pl3xmap addon called pl3xmap-Griefprevention loads before the GriefPrevention and should load after for it to work

### Fawe Debugpaste

 I have remove FAWE to fix the issue, so i can't do it

### Fawe Version

FastAsyncWorldEdit version 1.17-167

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
This is a spigot bug with the "provides" option in plugin.yml. If I change FAWE's plugin name to WorldEdit in the plugin.yml and remove "provides" then it works.

**Comment by dordsor21** [comment]
pl3xmap-Griefprevention were to use "depend" as it should be doing, it would work...

**Comment by NotMyFault** [comment]
For the record, this has been resolved in https://github.com/PaperMC/Paper/pull/6687 as it being a bug in the providing system and can be mitigated by updating Paper.
