### ISSUE TITLE
1.17.1: Outside selections removed, this time worse.

### ISSUE THREAD

**Issue by toxicsnails** [IntellectualSites/FastAsyncWorldEdit#1245]
### Server Implementation

Tuinity

### Server Version

1.17.1

### Describe the bug

I've had this issue before, but my report was marked as fixed and I thought that was the end of it.
Its not.

![2021-08-22_19 31 27](https://user-images.githubusercontent.com/86858026/130366185-1e05f6c3-83fb-4c47-94e3-44c3c47c094d.png)

My selection was between the two deepslate blocks.
I did //set stone
Everything around it that's gone? That only deleted when I did //set stone.

### To Reproduce

1. Make a selection.
2. //set stone
3. Watch as things around it go ~poof~

### Expected behaviour

Just for it to set it as stone.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f0f420c08cfe4703b159331e6cb67be2

### Fawe Version

FastAsyncWorldEdit version 1.17-168;cf671ad

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Duplicate #1237
