### ISSUE TITLE
Schematic Paste per Own Plugin crash the Server.(Builder 168+)

### ISSUE THREAD

**Issue by Pyario** [IntellectualSites/FastAsyncWorldEdit#1246]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

Since build version 168+ where "upstream" was, pasting with its own plug-in no longer works. Build 167 is fine. Here's the mistake: [21:22:20] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.TuinityRelighterFactory_1_17_1 as relighter factory.

### To Reproduce

Paste a Schematic with a Own Plugin.(I can't say more about how to reproduce it, but build 167 still worked without errors.)

### Expected behaviour

The whole time it was no idea why this no longer works since build 168+.

### Error log (if applicable)

https://paste.gg/p/anonymous/b9018521cb594a0a93a8a0dfef7fc51b

### Fawe Debugpaste

Nothing while back to older Version.

### Fawe Version

FastAsyncWorldEdit version 1.17-167;df8b280

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

Sorry if I can't say more about it, I suspect it has something to do with this Tuinity error. I can't say whether it has to do with Fawe directly, but I would tap it because the server crashes when a schematic is pasted.

**Comment by dordsor21** [comment]
Use FAWE api from an async thread as suggested in the documentation https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/API-Usage. The tuinity message is not the "mistake"...
