### ISSUE TITLE
error when using /p set border enchanting_table

### ISSUE THREAD

**Issue by LeJosplayy** [IntellectualSites/FastAsyncWorldEdit#1248]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

if i run  /p set border enchanting_table in the console is a big error 

### To Reproduce

1 goto a claimed plot
2 run  /p set border enchanting_table
3 see a big error

### Expected behaviour

That the plotborder canged to enchanting_table

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d76f012d02574c57ab51646febdf7108

### PlotSquared Version

PlotSquared-6.0.10

### Checklist

- [X] I have included a Plot debugpaste.
- [x] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Possibly fixed by 46fb0c9418ee945afced301bda8e5bde22bd9033 but cannot be tested due to mvn repo being down.
