### ISSUE TITLE
Not modify message "Too many arguments"

### ISSUE THREAD

**Issue by Lennord** [IntellectualSites/FastAsyncWorldEdit#1259]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hello, I modified some messages but when I use a bad argument it tells me "Too many argument" but suddenly I want to change it !

Example: //wand "Example"
  Send Message default + "Too many argument"

### To Reproduce

None

### Expected behaviour

None

### Screenshots / Videos

None

### Error log (if applicable)

None

### Fawe Debugpaste

None

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-190

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

None

**Comment by NotMyFault** [comment]
Exceptions are not translatable.
