### ISSUE TITLE
FAWE does not discriminate between slab types of a block, worldedits them all

### ISSUE THREAD

**Issue by craftyfoxe** [IntellectualSites/FastAsyncWorldEdit#1265]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

when I try replacing a slab type, it seems to not follow the type, but worldedits all of the types regardless of whether its a top, bottom or double slab

For example I wanted to only replace top slabs, but it does all slab types instead
![image](https://user-images.githubusercontent.com/48233056/131569294-92167e68-b29e-4002-a5d2-73aa91d18af1.png)
![image](https://user-images.githubusercontent.com/48233056/131569317-db78a142-cbcb-4242-8bfb-d19dbc570c41.png)

### To Reproduce

1.Have at least two types of slabs
2. Try to replace only upper slabs or only lower slabs e.g. //replace stone_slab[type=top] 2

### Expected behaviour

It is expected only to affect the type of slab used in the command

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d721713275f64828becfc43d1fe19a8a

### Fawe Version

1.17-190;ebc38a6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by w1tcherrr** [comment]
Same issue for me with build 192. Just to mention it: Any type of property (inside of the square brackets) gets ignored for the first block, but not for the second. "//replace stone_brick_slab[type=top] acacia_slab[type=top]" all stone_brick_slabs (also those not satisfying the type=top property) get replaced, but the resulting blocks (acacia_slab) will all be top-slabs. All blocks with these properties seem to be affected, slabs, stairs, etc.

**Comment by wa66rpg** [comment]
Same problem here!
Please have a look of the bug it’s really really really annoying.

**Comment by SirYwell** [comment]
Could you test if that's a regression from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/139/ to https://ci.athion.net/job/FastAsyncWorldEdit-1.17/140/ ?

**Comment by craftyfoxe** [comment]
Yes it is a regression. in #139, it works fine, but not in #140
