### ISSUE TITLE
Deadlock causing FAWE to stop working

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1266]
### Server Implementation

Tuinity

### Server Version

1.17.1

### Describe the bug

After using a couple of WorldEdit commands I noticed that WorldEdit stopped working and wasn't providing feedback in game. I used VisualVM to see what was going on and it said "Deadlock detected" so I've taken a thread dump hoping it will help debug the issue.

Thread dump: https://pastebin.com/S5dsV45p

When I disconnected from the server my console was spammed with: https://pastebin.com/cW8ueK6k

### To Reproduce

1. I'm not sure what causes this I just happen to use a couple of fill commands and undo

### Expected behaviour

Commands should continue to work

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/27e70ce679db46bd88a6a1c62e537c1d

### Fawe Version

1.17-190;ebc38a6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by GriffinCodes** [comment]
I'm experiencing a lot of deadlocks on 201

[my code](https://github.com/ProjectEdenGG/Nexus/blob/master/src/main/java/gg/projecteden/nexus/utils/WorldEditUtils.java#L336-L357)

[debug paste](https://athion.net/ISPaster/paste/view/04710074e9b44619ae86f3a1920b5203)

[output of `jstack <pid>`](https://paste.projecteden.gg/deadlocks)
