### ISSUE TITLE
Schematic pastes with WorldEdit but not FAWE

### ISSUE THREAD

**Issue by SamB440** [IntellectualSites/FastAsyncWorldEdit#1268]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

After switching from standard WorldEdit to FAWE, our plugin is no longer able to paste schematics correctly. It also happens when using //schem load.

The schematic fails to paste and an error appears in console. Also, the world is modified with random blocks in a straight line from the schematic after the attempted paste? Not sure if that is related - see screenshot.

The schematics were saved via API using the SPONGE_SCHEMATIC format.

I have tried two ways:
```FaweAPI.load(schematic).paste(adaptedWorld, BlockVector3.at(x, y, z), true);```
and what I used with standard WE:
```java
World adaptedWorld = BukkitAdapter.adapt(world);
ClipboardFormat format = ClipboardFormats.findByFile(schematic);
try (ClipboardReader reader = format.getReader(new FileInputStream(schematic))) {
	Clipboard clipboard = reader.read();
	try (EditSession editSession = WorldEdit.getInstance().getEditSessionFactory().getEditSession(adaptedWorld, -1)) {
		clipboard.setOrigin(BlockVector3.at(x, y, z));
		ClipboardHolder clipboardHolder = new ClipboardHolder(clipboard);
		Operation operation = clipboardHolder.createPaste(editSession)
				.to(BlockVector3.at(x, y, z))
				.ignoreAirBlocks(false)
				.build();
		Operations.complete(operation);
	}
} catch (IOException e) {
	e.printStackTrace();
}
```

And also pasting with //schem load. //paste will paste nothing.
This is the schematic it was attempting to use (had to upload with ZIP), but it happens with all existing schematics:
[mainhelms_CLOSED.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/7106350/mainhelms_CLOSED.zip)

### To Reproduce

1. Attempt to paste schematic
2. See error in console

### Expected behaviour

The schematic should paste like it does with normal WorldEdit.

### Screenshots / Videos

Strange blocks:
![image](https://user-images.githubusercontent.com/11319274/132016977-129c839f-8c44-481f-b711-c1cb7ffec5ad.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/98c67afa2bcc41c1acf176807f0395c3

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8a9513035805463484f3d5515a11c73d

### Fawe Version

1.17-199;4bf2781

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by GriffinCodes** [comment]
I think I am having a similar problem. 

Recently my copy util crashed the server, so I moved it into an asynchronous task. Since then, the clipboards are mostly full of acacia buttons, in random directions & pressed states, sometimes acacia doors and trapdoors (which there are none of in builds)

```java
	public CompletableFuture<Clipboard> copy(Region region) {
		final CompletableFuture<Clipboard> future = new CompletableFuture<>();

		Tasks.async(() -> {
			Clipboard clipboard = new BlockArrayClipboard(region);
			try (EditSession editSession = getEditSession()) {
				ForwardExtentCopy copy = new ForwardExtentCopy(editSession, region, clipboard, region.getMinimumPoint());
				Operations.completeLegacy(copy);
				future.complete(clipboard);
			} catch (WorldEditException ex) {
				ex.printStackTrace();
			}
		});

		return future;
	}
```

I do not receive any errors in console, however.

https://athion.net/ISPaster/paste/view/7572d2a01d6f40b386b0cfa65b2719e0

![image](https://user-images.githubusercontent.com/12417961/132117590-3220a548-91c2-497c-97d4-1e3cf368b930.png)
