### ISSUE TITLE
/fastasyncworldedit:/ Commands are not working

### ISSUE THREAD

**Issue by Tanerx** [IntellectualSites/FastAsyncWorldEdit#1271]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

None of "/fastasyncworldedit:/" commands are working. No ingame or console error.

### To Reproduce

/fastasyncworldedit:/paste
/fastasyncworldedit:/br
/fastasyncworldedit:/cut
etc..

### Expected behaviour

Commands are working like //paste - //br etc...

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ee2dc8915d314f448bb192b59c7b55ce

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-201

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
This seems like it's an anvil issue. We would have to do a string replace or something to make it work :/
