### ISSUE TITLE
Server Freezing because FAWE?

### ISSUE THREAD

**Issue by LowScarlet** [IntellectualSites/FastAsyncWorldEdit#1272]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Freezing/Crash

### To Reproduce

none

### Expected behaviour

.

### Screenshots / Videos

.

### Error log (if applicable)

https://gist.github.com/LowScarlet/51d330d940b72d2d8a1254879a72a5cd

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/239411df943c4786861f427270882767

### Fawe Version

1.11-SNAPSHOT-f17f9d9

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
That's a Paper issue that has been resolved recently, so update Paper and Fawe while you're at it.
