### ISSUE TITLE
FAWE deadlock detected and commands not working

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1289]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

WorldEdit commands stopped working, I was unable to use the fawe threads command but with VisualVM it said "Deadlock detected" Here's the thread dump: https://pastebin.com/3zzAhV3F

Here's the log before things stopped working, the log mentions an error: https://pastebin.com/kQVmWLaR

### To Reproduce

Not sure how to reproduce this

### Expected behaviour

Fawe commands should continue to work

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bccfecf3bd814036a17bcfe2111c2cee

### Fawe Version

1.17-210;195a13a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
update
