### ISSUE TITLE
clipboard is null, when clipboard is saved in central folder

### ISSUE THREAD

**Issue by muterulo** [IntellectualSites/FastAsyncWorldEdit#1291]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When something is copied from one server on a bungee and then you try to paste your clipboard on an other, which was saved in an central folder, you get this error that the clipboard is null.
The central folder is used by both servers and both plugin configs are the same.
It worked with the same cofnigs and settings in version 201.

### To Reproduce

1. copy someting on the first server
2. switch to the second server
3. paste your clipboard

### Expected behaviour

your clipboard shold be pasted

### Error log (if applicable)

https://paste.gg/p/anonymous/ade6ce5ec9b8464b961f67ada5b6b36c

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/51de47fe00ba4d399f6fbde3901b113c

### Fawe Version

FastAsyncWorldEdit version 1.17-231;8e214b1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by dordsor21** [comment]
Please retry with the latest build

**Comment by muterulo** [comment]
Now it works.
Thanks
