### ISSUE TITLE
FAWE deadlock detected and commands not working

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1292]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

WorldEdit commands stopped working even after updating from build 210 to build 222, VisualVM says deadlock detected here's the thread dump: https://pastebin.com/KgdXts67

Here's the log where WorldEdit commands stopped working: https://pastebin.com/P6gWR7XJ

### To Reproduce

1. Not sure

### Expected behaviour

WorldEdit commands should continue to work

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1a3cda2674f841b18c3d0d3c070c30c6

### Fawe Version

1.17-222;5fb4434

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Yes, no.
![](https://i.imgur.com/2tKz3wr.png)
I'd advice checking whether you're actually using a new build or one that is 10 updates behind.

**Comment by SecretlyJealous** [comment]
It's just that I experienced this problem on build 210 then was told to update to the latest build which was build 222 at the time and I still had the same bug. I'll use build 231 since that's the latest now but if I experience this bug again I really hope it's within hours otherwise I'll just naturally be outdated by a couple of builds
