### ISSUE TITLE
FAWE doesn't work on my 1.16.5 server

### ISSUE THREAD

**Issue by RonoLag** [IntellectualSites/FastAsyncWorldEdit#1295]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

Fawe is not detected by my mc server. When I put the plugin in the plugins file and reload or restart the server the plugin is not detected by the server.

### To Reproduce

go to the plugins file
drag FAWE in it
and start the server

### Expected behaviour

the plugin work

### Fawe Debugpaste

Unknown command. Type "/help" for help.

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-242

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Provide your `/logs/latest.log`: https://paste.gg/

**Comment by RonoLag** [comment]
https://paste.gg/p/anonymous/7a5c5ce4180146c58c5cb194c7f69d70

**Comment by NotMyFault** [comment]
Use [Paper](https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/788/downloads/paper-1.16.5-788.jar) and [Java 16](https://paper.readthedocs.io/en/latest/java-update/).
