### ISSUE TITLE
[HELP] Document translation

### ISSUE THREAD

**Issue by FZDNSZYT** [IntellectualSites/FastAsyncWorldEdit#1308]
### What feature do you want to see added?

I want to translate the instruction description of [HELP], but I can't find the corresponding file. Does the author have a way?

### Are there any alternatives?

No way

### Anything else?

I hope the author can reply as soon as possible, and I hope it can be sent to discord after the localization. Bless everyone.

**Comment by NotMyFault** [comment]
`/plugins/FastAsyncWorldEdit/lang/strings.json`, everything that is translatable can be found there.

**Comment by FZDNSZYT** [comment]
> `/plugins/FastAsyncWorldEdit/lang/strings.json`，所有可翻译的东西都可以在那里找到。

After translation, [help] is still in English, and nothing else. So I want to know how to translate [help]

**Comment by NotMyFault** [comment]
If said string is not in named file, it's not translatable. Nor do I know where you got it from, Fawe doesn't contain it at all.

**Comment by FZDNSZYT** [comment]
> `/plugins/FastAsyncWorldEdit/lang/strings.json`，所有可翻译的东西都可以在那里找到。

[help] cannot be translated, it is extremely unfriendly to beginners

**Comment by NotMyFault** [comment]
Yet again, where is named string shown?

**Comment by FZDNSZYT** [comment]
> 再次，在哪里显示命名字符串？
The untranslatable [help] I mentioned is the output of the command "//help". The twenty pages of instruction help cannot be translated and are all in English. This affects the use very much.

**Comment by FZDNSZYT** [comment]
> 再次，在哪里显示命名字符串？

[help] Can't translate, what I described

**Comment by NotMyFault** [comment]
So it's not about the individual 4 letters but an actual command, you should've mentioned that. Gist is that command descriptions and exceptions are not translatable at all at this time.

**Comment by FZDNSZYT** [comment]
> So it's not about the individual 4 letters but an actual command, you should've mentioned that. Gist is that command descriptions and exceptions are not translatable at all at this time.

What a pity, there is no way to translate. Can you guys try to kernel translation

**Comment by FZDNSZYT** [comment]
> So it's not about the individual 4 letters but an actual command, you should've mentioned that. Gist is that command descriptions and exceptions are not translatable at all at this time.

For now, it can only be the kernel translation, the language file of "//help" is not independent, it is really a painful thing

**Comment by NotMyFault** [comment]
Pull requests are welcome to add named behavior.
