### ISSUE TITLE
can't set tile-entity

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#1310]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Trying to set a tile entity without `*` permissions causes error message
![grafik](https://user-images.githubusercontent.com/46501008/133940500-a4c60af5-57ed-4c70-887a-d27adb68a481.png)

### Permission/s used:
- `fawe.permpack.basic`

### Steps to reproduce
1. Try to set a tile-entity (example: chest)

### Expected behaviour

The block should be placed or a required permission should be added to the message or the wiki.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e5cac8a3f48e4a5b94a2974dd0165d73

### Fawe Version

FastAsyncWorldEdit version 1.17-277;8cc93a2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by Xaver106** [comment]
The permission missing message still doesn't display which permission is missing.
In the commit changes I found `worldedit.anyblock.nbt`, which works and let' players set tile-entitys.

**Comment by NotMyFault** [comment]
You'll need to remove existing string and let Fawe regenerate it.

**Comment by Xaver106** [comment]
that makes sense... sorry
After regenerating the strings.json the message shows up correctly
