### ISSUE TITLE
Scatter brush with fullcopy pattern not working

### ISSUE THREAD

**Issue by SignorPollito** [IntellectualSites/FastAsyncWorldEdit#1322]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

The scatter brush doesn't work when used with fullcopy pattern.

### To Reproduce

**Single file version**
1. Make a clipboard of a structure and save it as a schematic
2. Bind the scatter brush to a tool (//br scatter #fullcopy[schematic_name] 30 10 10)
3. Click on the ground and nothing will happen
4. Use scatter brush without fullcopy pattern and it will work

**Folder version (not related to scatter brush)**
1. Make multiple schematics and save them in a folder
2. Bind any brush to a tool (//br <brush> #fullcopy[folder_name] <parameters>)
3. The folder will not be found.

### Expected behaviour

The scatter brush with the fullcopy pattern should paste the schematic.
The folder put in the fullcopy pattern should be found.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b97a5030d9a44a9aa7e826254785dec4

### Fawe Version

1.17-324;2682441

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Disable `per-player-schematics` if you aren't using it.

**Comment by SignorPollito** [comment]
It was already set to false, but the scatter and the folder inside fullcopy still not working for me.

**Comment by NotMyFault** [comment]
Going of the debugpaste linked, at the time reported this was definitely not set to false:
![](https://i.imgur.com/BqHRVP2.png)

**Comment by SignorPollito** [comment]
Sorry my fault, MobaXTerm didn't save the config file the first time, but I have modified it a minute after posting this issue.
https://athion.net/ISPaster/paste/view/c329e3b1547740c88c39650d66ec5b0b

I also tried to paste the schematic to check if there were errors, but it got pasted normally.
Forgive me if I'm wasting your time.
