### ISSUE TITLE
Commit e97c945b2fc6ac1f66df551737c863174041cc98 by dordsor21 breaks clipboard for plugins such as Craftbook

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/FastAsyncWorldEdit#1328]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

There is a bug here , in this commit http://ci.athion.net/job/FastAsyncWorldEdit-1.17/320/changes . In your attempt to fix the clipboard , you caused other issues with plugins such as Craftbook , probably others as well.  I have pointed this out in Discord . but now 11 builds later the bug is still there in build 1.17-331

### To Reproduce

use plugin Craftbook latest version on your server , probably other plugins as well that reference the clipboard

select area
enter a FAWE command , example //copy
server broken

### Expected behaviour

expect the FAWE clipboard not to crash the server

### Screenshots / Videos

![2021-09-28_07 58 51](https://user-images.githubusercontent.com/22108822/135085494-32094fac-bd92-4f57-a62f-715c3ba05046.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/828fc03eba2c4d3fbfdc258e4b0b2535

### Fawe Debugpaste

not possable FAWE breaks server

### Fawe Version

Commit e97c945b2fc6ac1f66df551737c863174041cc98 by dordsor21

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

Please fix

**Comment by dordsor21** [comment]
Cannot replicate. The commit added attempting to lock the clipboard file for editing. If it works fine without craftbook, then craftbook is creating a lock on files in the FAWE clipboard folder which seems like their issue.

**Comment by dordsor21** [comment]
e94b85a0fcb00f8e0375f8a35754bc9c7dcf0270

**Comment by Tsoccerguy3** [comment]
Seems to be fixed , closing issue
