### ISSUE TITLE
AbstractDelegateExtent requires FaweMaskManager to work

### ISSUE THREAD

**Issue by Invvk** [IntellectualSites/FastAsyncWorldEdit#1330]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

As the title says, this issue prevents use of custom extent if the plugin doesn't provide a custom `FaweMaskManager`. the issue is that `Extent.setBlock` will always return false and it won't send the changes, which makes almost all worldedit commands not working (`//set`,`//replace`... etc.. not sure if there are others).

so, it won't work if:
 - There is no `FaweMaskManager` provided by my plugin itself
 - if the provided `FaweMaskManager.getMask(LocalPlayer, Location)`: 
    - returns null
    - returns a dummy `FaweMask` with randomly selected points
    - if you are not inside the region that has been specified in the `getMask(LocalPlayer, Location)` (see below)

To understand this issue I will use this picture:
![](https://i.imgur.com/dLrfah2.png) 

First case: no FaweMaskManager. it will break no matter what.

Second case: Using the custom `AbstractDelegateExtent` , a custom `FaweMask` with the minimum and the maximum point is selected randomly. if as an example if I use  (`//set`,`//replace` etc...) commands and I want my custom `AbstractDelegateExtent` to set all blocks to sponge blocks regarding the user's input specifically in `setBlock(BlockVector3, block)` inside the redstone area it won't work. However if I change the minimum and maximum position pointing to the redstone area in the picture, it will work only inside the redstone area.

Third case: FaweMaskManager, with the `getMask(LocalPlayer, Location)` using the `global` region as minimum and maximum points. it will work everywhere and as expected.

### To Reproduce

1. Download [This plugin](https://www.udrop.com/5Zfp/BugReport.jar
).
2. start the server.
3. add [this](https://paste.gg/p/anonymous/9acf55e6f964480ebe06b1f2645e7ca8) to your `/plugins/WorldGuard/worlds/world/regions.yml`.
4. modify `allowed-plugin` like [this](https://paste.gg/p/anonymous/953227ae22ca41889141f1611ddd1b92) inside `/plugins/FastAsyncWorldEdit/config.yml`.
5. make sure you are `not op` and you have access to worldedit commands and don't forget to add permission `fawe.fawe-bug-report` & `fawe.worldguard`
5. reload FAWE.
4. try `//set 1` inside the region I provided and it should ignore your input and set it to sponge block.
5. now test it outside the region and it should not work at all, not even changing the blocks to stone.
6. type `/makeitglobal` and restart the server. (This will set the minimum and maximum points using global region)
7. now test it in and outside the region, it should ignore your input and set it to sponge blocks.
8. type `/breakitall` and restart the server. (This will prevent the mask from being added)
9. now test it in and outside the region, worldedit commands should stop working.
10. to revert back to the original state type `/makeitdefault`

### Expected behaviour

The expected behaviour is that `AbstractDelegateExtent` should work without relying on the fact that if the plugin provides a `FaweMaskManager`.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/15824e698b8f4d5a9071d36a7b7d12cc

### Fawe Version

1.17-336;0ed9872

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

This only applies to players who is not op but have the permission to use WorldEdit. But the question here is this how it is intended to work?

**Comment by Folas1337** [comment]
I'd like to express my interest in this issue and that I'd like to see it fixed as it would allow the worldedit flag of WorldGuardExtraFlags to work again.

**Comment by dordsor21** [comment]
I believe I'd found the root cause of this some time ago, but have since forgotten and I cannot find it again :))

**Comment by OneLiteFeather** [comment]
@dordsor21 what can we do for now?

**Comment by OneLiteFeather** [comment]
> I'd like to express my interest in this issue and that I'd like to see it fixed as it would allow the worldedit flag of WorldGuardExtraFlags to work again.

Does it work with newer versions again?

**Comment by dordsor21** [comment]
No new reports of this so will close
