### ISSUE TITLE
Exception when block Azalea used

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/FastAsyncWorldEdit#1332]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Exception is throw when block Azalea used

### To Reproduce

1. `//set azalea`
2. See error into console

### Expected behaviour

No exception

### Error log (if applicable)

https://paste.gg/p/anonymous/23f087e705bd4fd6b79285a6786f6926

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7f769b581db04f26a80405b72579df85

### Fawe Version

FastAsyncWorldEdit version 1.17-336;0ed9872

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

Not lasted version, but there are just one commit for Towny lib update, so not reliente

**Comment by dordsor21** [comment]
Is this very replicable for you? I've not managed to replicate (actually on the same paper version by a stroke of luck too).

**Comment by jewome62** [comment]
I will close the ticket for the moment, the //set command with azalea was not work well after a brush with azalea (i will try to find this command and retry on latest version)
