### ISSUE TITLE
brush height "Outside allowed region" error even though it is in the allowed region

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1346]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When using `/brush height` for some reason it will refuse to work at times and just spam "Outside allowed region" errors while I'm using the brush even though I'm not outside of the allowed region. You can see in the picture below how I'm able to use the brush but some of the actions are not going through:
![2021-10-08_10 52 09](https://user-images.githubusercontent.com/10485646/136536613-38b2dc76-2d90-4e86-8f60-23170bbdb15f.png)

![2021-10-08_10 55 42](https://user-images.githubusercontent.com/10485646/136536811-e9fde018-4286-40ee-b75c-456af0440c9c.png)

### To Reproduce

1. Use /brush height
2. Move across a region while holding right click with the brush

### Expected behaviour

There should be no errors when using brush height in the allowed region

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2eca24b88aa44a8786f0f3573f42b563

### Fawe Version

1.17-346;2eb6451

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by SecretlyJealous** [comment]
Change `max-fails: 5000000` to `max-fails: 0` and you will be able to reproduce it

**Comment by dordsor21** [comment]
What height is the plotworld at?

Also if you set fails to zero, then one fail will create the error and print the error (thus if your brush goes below y=0, you will get the error...)

**Comment by SecretlyJealous** [comment]
> What height is the plotworld at?
> 
> Also if you set fails to zero, then one fail will create the error and print the error (thus if your brush goes below y=0, you will get the error...)

The height of the plotworld is 256
```
    world:
      border: false
      max_height: 256
      gamemode: creative
      min_height: 1
```
When standing on a plot the height is at 65, I'm getting the error even when I'm above y=0. I'm not sure which commit caused this because this was never a problem until recently, unfortunately I'm unsure which commit introduced this problem. Here's a video of me with the debug screen open so you can see me using the brush and also see my height:
https://gfycat.com/singlecrazyladybug
