### ISSUE TITLE
Invalid config field with PS v4

### ISSUE THREAD

**Issue by FZDNSZYT** [IntellectualSites/FastAsyncWorldEdit#1372]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

[com.fastasyncworldedit.core.configuration.Config] Invalid config field: enabled-components.plotsquared-v4-hook for enabled-components
[07:51:37 ERROR]: [com.fastasyncworldedit.core.configuration.Config] Failed to set config option: enabled-components.plotsquared-v4-hook: true | com.fastasyncworldedit.core.configuration.Settings$ENABLED_COMPONENTS@3feeb857 | Settings.yml

### To Reproduce

This error will appear every time the server is restarted

### Expected behaviour

Update the ".jar" file can not be repaired

### Error log (if applicable)

[com.fastasyncworldedit.core.configuration.Config] Invalid config field: enabled-components.plotsquared-v4-hook for enabled-components [07:51:37 ERROR]: [com.fastasyncworldedit.core.configuration.Config] Failed to set config option: enabled-components.plotsquared-v4-hook: true | com.fastasyncworldedit.core.configuration.Settings$ENABLED_COMPONENTS@3feeb857 | Settings.yml

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/08a679de0a184fd8a65e8944031dabee

### Fawe Version

FastAsyncWorldEdit version 1.17-365;e7a6c3e

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by srnyx** [comment]
What is even "invalid" about it?
