### ISSUE TITLE
Plot upload/paste bug

### ISSUE THREAD

**Issue by MADS0LADEN** [IntellectualSites/FastAsyncWorldEdit#1377]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

It says the schematic is invalid because it is not in gzip format.

### To Reproduce

Create a schematic from FAWE, upload it to the [website](https://schem.intellectualsites.com/plots/), copy the command, issue the command in-game.

### Expected behaviour

It would paste the plot

### Error log (if applicable)

https://gist.github.com/MADS0LADEN/824d229c606c201edf86ffcbdb30a701

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/529e096603a34d42a79207767a2803d4

### PlotSquared Version

PlotSquared-6.1.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Can you attach the schematic please?

**Comment by NotMyFault** [comment]
No response, closing.
