### ISSUE TITLE
Console/Command block command inplementation

### ISSUE THREAD

**Issue by ProfessorZel** [IntellectualSites/FastAsyncWorldEdit#1385]
### What feature do you want to see added?

Classic WG has a system of commands which allows to lay out foundation for some actions from console/command block, such as copying schematic.
For that following command sequence will be used `//schem load <name> -> //world <world_name>`, so we have schem loaded, world selected, however command `//paste <pos>` is player-only, and also don't have arg <pos>, that would be nice to have ability to paste from console.
Same situation with `//pos1 <pos>, //pos2 <pos>`, we have selection ready, but `//copy` is player-only, so we can't copy from console/command block, and save to schema for example.

### Are there any alternatives?

None i am aware of.

### Anything else?

This will help to automate a lot of tasks, like periodic regeneration of selected regions `//pos1 <pos> -> //pos2 <pos> -> //regen`, so that would be noce to have such functions added!
Ty for your time, and efforts you put in this plugin. 

I did my do diligence and searched for similar requests, however was not able to locate any, sry if this was already dealt with.

**Comment by NotMyFault** [comment]
> For that following command sequence will be used //schem load <name> -> //world <world_name>, so we have schem loaded, world selected, however command //paste <pos> is player-only, and also don't have arg , that would be nice to have ability to paste from console.

Paste does not take coordinate arguments at all. A paste is always done relative to the position the clipboard has been copied from.

> Same situation with //pos1 <pos>, //pos2 <pos>, we have selection ready, but //copy is player-only, so we can't copy from console/command block, and save to schema for example.

Copy takes an actor, so you can use it from console too.

**Comment by ProfessorZel** [comment]
Hellow, i think i expressed myself not clear enough, i don't assume that it exist, and nor i report it as a bug, i put it in Enhancement category, to ask for possibility for such things being added, so //paste can be used from console, if it exist already, then i ask you for grace to point on this functionality described in docs.
Ty for your time and effort, in text you write `... console **too**.` so i assume such functionality exist, so please if possible point out a docs about this.

PS: `//paste <pos> is player-only, and also don't have arg `, i know that it `don't have arg`, but still ty for your response.
