### ISSUE TITLE
The WE Wand destroys hanging entities

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#1397]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Hanging Entities get destroyed by the wand and don't place position.

### To Reproduce

1. place a Hanging Entity
2. use the wand and left click on it
3. the hanging entity will de destroyed

### Expected behaviour

The Hanging Entity shouln't be destroyed, instead the event should be canceled and the position set to the position of the entity.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9eac93e06ab3444781414fa48796de94

### Fawe Version

FastAsyncWorldEdit version 1.17-387;21b6f58

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
That works fine for me https://streamable.com/wt6p6e

**Comment by Xaver106** [comment]
Hanging entities: paintings and item frames. The vines are blocks.

**Comment by NotMyFault** [comment]
Oic, I read that wrong apparently. However, if I remember correctly, that is the default behavior for WorldEdit as well, so it would make sense to raise an issue/feature request on upstream.

**Comment by NotMyFault** [comment]
Considering named blocks are always attached to a block, attempting to copy them makes no sense.
