### ISSUE TITLE
FAWE history list (//history list <player>) shows nothing

### ISSUE THREAD

**Issue by MarvinKlar** [IntellectualSites/FastAsyncWorldEdit#1401]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

FAWE history list (//history list <player>) shows nothing

### To Reproduce

1. Make any worldedit changes like `//pos1`, `//pos2` and `//set 1`
2. Run `//history list <yourName>`
3. You see and empty list of edits

### Expected behaviour

The `//history list <player>` command should show the history of changes made by that player

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/34421947/140654134-dde85221-7e04-4af6-a9f1-e3782d489059.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/da671f22e7084064a69635494506a9d1

### Fawe Version

FastAsyncWorldEdit version 1.17-389;95ecb56

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
Can't replicate, do you have some form of client modifications? That used to mess up things in the past.

**Comment by NotMyFault** [comment]
No response, assume resolved or no longer relevant.
