### ISSUE TITLE
Not working with Cannons

### ISSUE THREAD

**Issue by ConaII** [IntellectualSites/FastAsyncWorldEdit#1407]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

When using Cannons, it completely breaks when loading cannon designs. 
This breaks Fawe too, and this causes worldguard to misbehave, having lag protecting, errors with flags, etc.
Specially breaking protection against lecterns, empty item frames and paintings.
It did work fine in 1.13, so it could work in 1.16 too.

### To Reproduce

1. Download FAWE, any version above 1.13
2. Download WorldGuard 1.16
3. Download Cannons 1.16
4. Start the server and the issue is BUSTED in the logging.
5. Cannons, FAWE and WorldGuard are now misbehaving.

### Expected behaviour

Work just fine, like worldedit.

### Error log (if applicable)

https://paste.gg/p/anonymous/38abe37f8e42462b9bbcc0629b15a703

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8aa8a777b7174e3997502661b717ce3f

### Fawe Version

1.17-391;4272f96

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
For reference, please link the issue you've risen at "Cannons" issue tracker.

**Comment by ConaII** [comment]
https://github.com/DerPavlov/Cannons/issues/32

**Comment by ConaII** [comment]
This is the issue:

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/4272f96aded08a1c0c5b784521aefc58ee5ab29d/worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java#L449
https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html

**Comment by ConaII** [comment]
Will this be fixed or do I have to do it on my own?

**Comment by dordsor21** [comment]
The main issue here is that the saving-to-clipboard code in Cannons is incredibly poorly implemented. The only reason it "works" with WorldEdit is because WE checks that the clipboard's region contains the block location attempting to be added, and _will not save the block to the clipboard_ if it's outside the clipboard region. Cannons is loading a schematic from disk into a clipbard and not checking the regions match between the stored schematic and the region it's attempting to save, at all.

**Comment by DerPavlov** [comment]
Cannons does not write to the schematic, it only loads designs from the clipboard. However, the error might occur during translation of the clipboard using the Worldedit Transform method.
https://github.com/DerPavlov/Cannons/blob/0b14460eaa313240b03c005dcec1c3a8c1ebd901/src/main/java/at/pavlov/cannons/cannon/DesignStorage.java#L399

I assume that Worldedit handles the new schematic dimensions, I have no clue how FAWE handles this operation internally.
The part can be modified if needed, but I would require an example.

`        AffineTransform transform = new AffineTransform().translate(cc.getMinimumPoint().multiply(-1));
        BlockTransformExtent extent = new BlockTransformExtent(cc, transform);
        ForwardExtentCopy copy = new ForwardExtentCopy(extent, cc.getRegion(), cc.getOrigin(), cc, BlockVector3.ZERO);
        copy.setTransform(transform);
        try {
            Operations.complete(copy);
        } catch (WorldEditException e) {
            e.printStackTrace();
        }`

**Comment by dordsor21** [comment]
that's writing to the clipboard... https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ForwardExtentCopy.java#L116

**Comment by DerPavlov** [comment]
I changed the code and FAWE seems to be happy with it. Thanks to SebasSV for pointing this out
https://www.spigotmc.org/threads/rotate-clipboard-in-worldedit-api-7-0-1-13-2.407940/

```
ClipboardHolder clipboardHolder = new ClipboardHolder(cc);
clipboardHolder.setTransform(new AffineTransform().translate(cc.getMinimumPoint().multiply(-1)));
cc = clipboardHolder.getClipboard();
```

**Comment by ConaII** [comment]
Thank you all!
I'm going to test it.
