### ISSUE TITLE
Bug with asc

### ISSUE THREAD

**Issue by DjeyMute** [IntellectualSites/FastAsyncWorldEdit#1408]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When we made /asc while being on a slab.
So the plugin teleports us 0.5 block above.
And not upstairs.

### To Reproduce

1. Go on a slab
2. Make /asc

### Expected behaviour

I wish that would teleport to the floor above

### Screenshots / Videos

I wish that would teleport to the floor above

### Error log (if applicable)

no

### Fawe Debugpaste

no

### Fawe Version

1.17-192;0c9270d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

No

**Comment by NotMyFault** [comment]
The same occurs when using WorldEdit, this is likely something that should be fixed in upstream.

**Comment by NotMyFault** [comment]
//asc teleports you to the next full block, if you are standing on a block that is lower than 1, simply add +n to asc.
