### ISSUE TITLE
Cannot set Extent during EditSessionEvent

### ISSUE THREAD

**Issue by einTosti** [IntellectualSites/FastAsyncWorldEdit#1436]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When setting the `Extent` during `EditSessionEvent`, a `java.lang.UnsupportedOperationException` is thrown.
This error does *not* appear when using WorldEdit (Not FAWE)

### To Reproduce

The following code throws the error:

```java
@Subscribe
public void onEditSession(EditSessionEvent event) {
    if (event.getStage() == EditSession.Stage.BEFORE_CHANGE) {
        event.setExtent(new NullExtent());
    }
}
```

### Expected behaviour

No error should occurs

### Error log (if applicable)

https://paste.gg/p/anonymous/9a95ae2f360f46b7a4aadbdd226f1c92

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f16fdc3bda12433fa51f57b3c8f1d18f

### Fawe Version

FastAsyncWorldEdit version 1.17-407;fc4517f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Shouldn't be marked as stale, as FAWE extents (HeightmapProcessor + RelightProcessor) throw an exception on `construct()` - which shouldn't be the case (or the call to `construct` in Extent#addProcessor should not be done when it's one of those extents)
