### ISSUE TITLE
console error when using command //brush paint

### ISSUE THREAD

**Issue by crimsson** [IntellectualSites/FastAsyncWorldEdit#1437]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

This came up when I use brush paint command
.eq //brush paint cuboid 2 20 set grass_path

### To Reproduce

just do normal command for //brush paint

in my case, it is : //brush paint cuboid 2 20 set grass_path

### Expected behaviour

in normal WorldEdit command, it should do "paint" function on your wand

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/91674702/143661260-3d4fab30-c2d4-4247-b899-726b2789ee1e.png)

### Error log (if applicable)

https://pastebin.com/Uw9FrNdA

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8c2c5734f53248d29eb4b04504a55ca6

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-408

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate that. However, you should update Paper and consider using the proper naming, grass_path is internally deprecated.
