### ISSUE TITLE
Limits aren't working

### ISSUE THREAD

**Issue by xR4Z3R** [IntellectualSites/FastAsyncWorldEdit#1443]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I have made some limits for certain groups but they are not working. I will paste this as an example:
https://paste.gg/p/anonymous/406cfc4280c04fe3b4353f29e36f415a
I want players with group "default" to be able to use commands like //set with limit set on 15000. The problem is that it isn't working and their limit is 5000. VIP can change max 10000 blocks (when I set it up on 30000) etc. I also gave them permissions (for example "fawe.limit.default" for default).

### To Reproduce

1. Make limits as in example above
2. Give permission as in example above
3. Test

### Expected behaviour

I expect limitations to be working properly (or if I made something wrong, to receive answer with correct setup)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1744f46094314aeb861ef460bdafc625

### Fawe Version

FastAsyncWorldEdit version 1.17-410;05c22a6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

BTW - If someone can explain to me what are "max-iterations" xD as I am not really into worldedit so I don't know what setting would be the best xD

**Comment by NotMyFault** [comment]
I'm unable to replicate that. Cloning your limits onto a sample server lead to the results expected.
