### ISSUE TITLE
//copy causes NPE on Purpur

### ISSUE THREAD

**Issue by sxphirus** [IntellectualSites/FastAsyncWorldEdit#1444]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

After using //copy on a structure the plugin will throw errors,
This issue is only intermittent and is does not occur every time.

### To Reproduce

1. //copy structure
2. Server most likely dies as container rate limits it

### Expected behaviour

//copy works without NPE spam

### Error log (if applicable)

https://mclo.gs/dwDzmno

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4fcd96c7c6984ea9bcd4cd38e7077a05

### Fawe Version

1.17-410;05c22a6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

```
[15:39:29 INFO]: This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
[15:39:29 INFO]: You are running the latest version
[15:39:29 INFO]: Previous version: git-Purpur-1423 (MC: 1.17.1)
```

**Comment by NotMyFault** [comment]
Can you replicate that on Paper?

**Comment by NotMyFault** [comment]
No response and apparently nobody else is able to reproduce it, closing.

**Comment by sxphirus** [comment]
Issue no longer persists after changing to Paper, sorry I completed the testing and never replied here, my bad
