### ISSUE TITLE
Tick limiter limits per chunk, but not per world

### ISSUE THREAD

**Issue by Elioby** [IntellectualSites/FastAsyncWorldEdit#1453]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Two chunks at the same coordinates but in different worlds will be limited by the tick limiter. For example, iitems spawned in 0, 0 "world" and 0, 0 "world_nether" will be counted as the same chunk. Check the code here: https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/075d5302ef13938dbf8c698d279d4c4ad87d2c79/worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/listener/ChunkListener.java#L400

getCount returns counts of items etc for a specific set of chunk coordinates, regardless of the world. Calling getCount(0, 0) in two different worlds will return the same counts, even though they should be different as they are different chunks.

### To Reproduce

This is fairly hard to reproduce as it's a very specific bug, the best way to check is by looking at the code linked above. However:

1. Setup some system that drops x items in chunk 0, 0 in "world"
2. Setup some system that drops x more items in chunk 0, 0 in "world_nether"
3. These two item spawn counts are aggregated and the limiter will be triggered even if the count < limit in each individual chunk

### Expected behaviour

Limits should be counted per chunk, and be unique for each world.

### Fawe Debugpaste

Not required in this case.

### Fawe Version

1.17-343;4ffddd8

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by MattBDev** [comment]
I may be wrong but I believe there have been discussions in the past on removing the tick limiter.

**Comment by NotMyFault** [comment]
The tick limiter is indeed sunset. It's a left over from pre 1.13 days when components were added that have nothing to do with world editing.
