### ISSUE TITLE
Users can see Schematics of other players

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#1457]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

With `//schem list ../` players can list all UUIDs of players that have schematics saved and list their schematics.

### To Reproduce

1. Save a schematic with a different account.
2. Use `//schem list ../` on the main account.
3. You can now click on the listed UUIDS to list their Schematics.
4. But without `worldedit.schematic.load.other` the schematics can't be loaded.

### Expected behaviour

I don't think you should be able to see others UUIDs or Schematics, as they could be working on something.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/97e2c7723ccc424a93b196da0252da6f

### Fawe Version

FastAsyncWorldEdit version 1.17-419;9fdff97

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

I would reccomend to check if the filter contains `../` so you could check for a permission, like `worldedit.schematic.list.other`. I did not make this a feature request, as I think this is somewhat severe.

**Comment by RedstoneFuture** [comment]
Others players can't load her own schematic, but all peoples can see your schematic list. I'm not sure, if it's useful. In older version the player hasn't the permission to list other schematic list, if he can't load it too.

**Comment by NotMyFault** [comment]
First time I hear about that, I'd rather label that as RFE than as bug, thoughts?
