### ISSUE TITLE
Brush paint error

### ISSUE THREAD

**Issue by illudota** [IntellectualSites/FastAsyncWorldEdit#1458]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

error

### To Reproduce

do //brush paint cyl set blockname

### Expected behaviour

just an error

### Screenshots / Videos

no pics but i have log

### Error log (if applicable)

https://pastebin.com/V3muiitQ

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d47e40f452924aa894a8e28dbd42a3f6

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-419.jar	

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment]
I can't replicate that on an up to date version of Paper.
