### ISSUE TITLE
FAWE API Schematic Error

### ISSUE THREAD

**Issue by ZandyDEV** [IntellectualSites/FastAsyncWorldEdit#1484]
### Server Implementation

Spigot

### Server Version

1.18.1

### Describe the bug

I'm trying to load a schematic with FAWE's API on 1.18.1 and throws a stacktrace.
The exact same code, works fine on 1.17.1.

### To Reproduce

Load a schematic thru FAWE API

### Expected behaviour

Load a schematic.

### Screenshots / Videos

-

### Error log (if applicable)

https://paste.gg/p/anonymous/4644fd07a4704257bae2d758e754c811

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/013b046243aa4f1d912c2b0390ae8527

### Fawe Version

2.0.0-SNAPSHOT-10;34f971c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Please link the code you are using as well.

**Comment by ZandyDEV** [comment]
com.sk89q.worldedit.extent.clipboard.Clipboard
com.sk89q.worldedit.world.World
com.sk89q.worldedit.math.BlockVector3
org.bukkit.Location

Clipboard clipboard = .....
World world = .....
Location loc = .....
clipboard.load(world, BlockVector3.at(loc.getX(), loc.getY(), loc.getZ()));

**Comment by dordsor21** [comment]
This was fixed in 4ab140f6a13e892097e4c2ff5c9feb6956a1897a
