### ISSUE TITLE
Big Areas, when not selecting that area

### ISSUE THREAD

**Issue by shadowtigercool** [IntellectualSites/FastAsyncWorldEdit#1486]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When I World Edit, it makes a random big area, but I didn't pick those area

### To Reproduce

//wand
//set air
select both areas
Then It randomly makes a huge area

### Expected behaviour

Big Chunk of Area Gone

### Screenshots / Videos

https://imgur.com/a/sqjQ50y

### Fawe Debugpaste

No Permission, Not Opped

### Fawe Version

2.0.0-SNAPSHOT

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Please link a debugpaste. If you have no permission to, get it from someone who does.
