### ISSUE TITLE
Chunks being deleted while using a brush

### ISSUE THREAD

**Issue by DoTrONoL** [IntellectualSites/FastAsyncWorldEdit#1488]
### Server Implementation

Spigot

### Server Version

1.18.1

### Describe the bug

FAWE keep deleting chunks when I use a brush to create an island or something else.

### To Reproduce

1. Create a brush: `/br blob 1 20 30 45 50`
2. Start clicking with a brush until you be done;
3. Then go with Spectator game mode and see if it generated a bug;
4. You see the error.

### Expected behaviour

This is supposed to fill my island without chunks being deleted...

### Screenshots / Videos

https://user-images.githubusercontent.com/71497422/147252156-d5b8b5c0-bad8-40fc-9460-16281379383d.mp4

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/392ee61ff92a44978ddcb73e7b7f89e1

### Fawe Version

FastAsyncWorldEdit version 2.0.0-SNAPSHOT-14;ca5ad58

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Command for fast reproduction's:
/br blob 1 20 30 45 50

**Comment by NotMyFault** [comment]
The spectator mode shows it quite well, it appears that chunks are affected where the brush edits in. They chunks are not randomly picked.

**Comment by JasonHorkles** [comment]
I'm also seeing the issue when setting blocks underground in general
https://athion.net/ISPaster/paste/view/1e3d1cf2105b403cb97bd38914739a89

Video:
https://1drv.ms/v/s!ArOS099NaR9Lo-ZnGwr02wbmIAoyaw?e=hAAnAg

**Comment by SirYwell** [comment]
Should be fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/f9ecb449cf601328a818e629343b8f5107f8cb96 (build 24), would be nice if you could verify that.

**Comment by JasonHorkles** [comment]
I'll happily test tomorrow, thanks for the quick update!

**Comment by JasonHorkles** [comment]
Looks like everything is working properly
