### ISSUE TITLE
Tabcomplete for Fawe doesn't work!

### ISSUE THREAD

**Issue by supermem99** [IntellectualSites/FastAsyncWorldEdit#1489]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Tab complete doesn't work if I type fawe commands.
It will be colored red, like the command don't exist.

### To Reproduce

1. Type in a fawe command like //walls
2. it will show red colored with text unknown command
3. entering the command
4. //walls will be executed

### Expected behaviour

it should be white colored the command.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/cb6e2c9c593b4853a4d9a51238c1f8b7

### Fawe Version

FastAsyncWorledit version 2.0.0-SNAPSHOT-15;28079e8

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

It was since 1.17

**Comment by PierreSchwang** [comment]
Could be related to https://github.com/PaperMC/Paper/issues/6936

**Comment by NotMyFault** [comment]
> Could be related to [PaperMC/Paper#6936](https://github.com/PaperMC/Paper/issues/6936)

No, the JVM bug only affects systems that run on explicit 1 core.

Looks like you simply have no permission to access the commands. Check with your permission plugin.

**Comment by PierreSchwang** [comment]
> No, the JVM bug only affects systems that run on explicit 1 core.

Oh, okay - Had the problem as well in another plugin https://github.com/SourceWriters/SmoothTimber/issues/20

**Comment by NotMyFault** [comment]
> Oh, okay - Had the problem as well in another plugin [SourceWriters/SmoothTimber#20](https://github.com/SourceWriters/SmoothTimber/issues/20)

If the flag does nothing, you are not running into the bug. Also paper implemented a workaround for it afaik if you are on an early version of 1.18.
Improper tab completion often boils down to wrong permission handling at runtime, considering it always effects people using non-standard permission plugins, e.g. something different than LuckPerms.

**Comment by supermem99** [comment]
i have * permission, i dont think that it caused by permissionsystem

**Comment by NotMyFault** [comment]
> i have * permission, i dont think that it caused by permissionsystem

Please attempt to replicate it on a fresh server with LuckPerms.
