### ISSUE TITLE
/setbiome console error

### ISSUE THREAD

**Issue by sos1sk** [IntellectualSites/FastAsyncWorldEdit#1490]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Basically setbiome does not work and gives an error;

https://paste.gg/p/anonymous/494efeac4c3b49c383190fca2da73a8e

### To Reproduce

1. Select the positions `1` and `2`
2. `//expand vert`
3. `//setbiome <any biome>`

### Expected behaviour

https://paste.gg/p/anonymous/494efeac4c3b49c383190fca2da73a8e

### Error log (if applicable)

https://paste.gg/p/anonymous/494efeac4c3b49c383190fca2da73a8e

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/067fd7ea760e441ca740be2d771f9c95

### Fawe Version

2.0.0-SNAPSHOT-15;28079e8

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Can replicate, edited the issues to display the steps to reproduce.
