### ISSUE TITLE
Add suitable fallbacks for Spigot, if present

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#1491]
https://paste.gg/p/anonymous/2dac2510368147999bcfff8817391c61

**Comment by MattBDev** [comment]
This is why I love Paper.

**Comment by CoreyJ87** [comment]
I'm getting this error too with pretty much any command.

**Comment by NotMyFault** [comment]
Resolved in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/018042769d00d04e5c0a12043079773a8dcd024c and  https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/4ab140f6a13e892097e4c2ff5c9feb6956a1897a
