### ISSUE TITLE
Segmentation fault when disconnecting while saving a schematic

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#1492]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

If you disconnect while saving a schematic, the server will crash.

### To Reproduce

1. Copy a big area and save it to a schematic 
2. While the schematic saves to disc disconnect from the server
3. The server crashes

### Expected behaviour

The server shouldn't crash

### Error log (if applicable)

https://gist.github.com/Xaver106/3dc75fe0d0bf85b99ec412ad7bc11890

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ebdfc4706a1a4fb58576801f48d205d4

### Fawe Version

FastAsyncWorldEdit version 1.17-425;37cc817

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by MattBDev** [comment]
A segment fault in Java is extremely rare. Can we confirm this behavior on other servers too?

**Comment by NotMyFault** [comment]
I could replicate it, hence I labeled it as "Approved".

**Comment by MattBDev** [comment]
Just double checking. 😛

**Comment by SirYwell** [comment]
FAWE is closing the `DiskOptimizedClipboard` when the player quits, but this is not synchronized with the save process. Therefore, we're accessing native memory after it was freed.
