### ISSUE TITLE
//stack -a not working

### ISSUE THREAD

**Issue by ArderMaxim** [IntellectualSites/FastAsyncWorldEdit#1494]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When I try to use the //stack id -a command, the plugin writes "0 blocks changed" and nothing happens.

### To Reproduce

1. Select the territory
2. Look in the any direction
3. Execute the command "//stack 5 -a"
4. Get the error

### Expected behaviour

Stack the territory

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/77189345/147354827-eb83e52c-9950-4ce4-86ad-7d7888ffa838.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/55816eeaafee4eee930590cad3a540b9

### Fawe Version

FastAsyncWorldEdit version 2.0.0-SNAPSHOT-15;28079e8

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate that based on the steps provided. Try updating Paper, using a default configuration for Fawe and testing without other plugins.

**Comment by ArderMaxim** [comment]
Thank you, updating the plugin helped me!
