### ISSUE TITLE
FAWE with mcmmo(tree feller)

### ISSUE THREAD

**Issue by NCSV** [IntellectualSites/FastAsyncWorldEdit#1495]
### Server Implementation

Purpur

### Server Version

1.18.1

### Describe the bug

after installed lastest  version of fawe, wood was not given when player use tree feller with sprint.
(1.18 purpur, FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-17),
log was dropped only it about 1/7 of the time. 

### To Reproduce

improve compatibility with mcmmo.

### Expected behaviour

player can't earn money properly

### Screenshots / Videos

video link : https://www.youtube.com/watch?v=rByYfE1Iwzc (i can't upload because size of file is bigger than 10mb.)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f9c2119287264ed4af4aa2d0f82d4611

### Fawe Version

1.18 purpur, FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-17

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Fawe does not interact with McMMO at all. A good start would be to setup a clean Paper server with a default McMMO configuration and test it with your plugins one by one.

**Comment by NCSV** [comment]
> 
The same problem occurs in clean. Can I turn off the related settings in fawe?
