### ISSUE TITLE
Smooth brushes go brrrr on negative heights

### ISSUE THREAD

**Issue by mrMaruda** [IntellectualSites/FastAsyncWorldEdit#1499]
### Server Implementation

Purpur

### Server Version

1.18.1

### Describe the bug

Affected brushes:
- smooth
- snow smooth

### To Reproduce

-

### Expected behaviour

-

### Screenshots / Videos

https://user-images.githubusercontent.com/73335003/147469677-a2d190e1-49f5-4fb6-86d8-6218f7391a41.mp4

### Error log (if applicable)

-

### Fawe Debugpaste

-

### Fawe Version

2.0.0-SNAPSHOT-17

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Please fill out the issue form properly.
