### ISSUE TITLE
`/rg select` only selects within old height limits

### ISSUE THREAD

**Issue by JasonHorkles** [IntellectualSites/FastAsyncWorldEdit#1500]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Using `/rg select` on a region that goes for example below 0 will only select down to 0

### To Reproduce

1. Make a region that goes above y 0 and below it
2. Clear your selection and history
3. Select the region with `/rg select`
4. Perform an operation like `//set dirt`

### Expected behaviour

It should select the whole region

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/23ff7f01770143c08b577bea138fc282

### Fawe Version

2.0.0-SNAPSHOT-24;f9ecb44

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Doesn't happen with normal WE

**Comment by NotMyFault** [comment]
Either the steps to reproduce are not clear enough or I'm not able to replicate that.
![](https://i.imgur.com/2naCwQr.png)
Using `/rg select` on a region with bounds below 0 works fine for me

**Comment by JasonHorkles** [comment]
Region info shows properly, but when you do a command like `//set dirt` it'll only go to 0

**Comment by NotMyFault** [comment]
I've updated the steps accordingly.

**Comment by NotMyFault** [comment]
Fixed in PR branch.
