### ISSUE TITLE
bug for new verison of fawe on 1.17.1 servers

### ISSUE THREAD

**Issue by LeitoCc187** [IntellectualSites/FastAsyncWorldEdit#1503]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

the plugin isnt loading up

### To Reproduce

[latest (2).log](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/7787030/latest.2.log)
there are the most recent logs

### Expected behaviour

i expected the plugin to load

### Screenshots / Videos

![2021-12-29](https://user-images.githubusercontent.com/84422709/147620607-5fad55c0-ecbc-40d3-a2b8-e5ff342d93af.png)
as you can see teh files are there but wont load

### Fawe Debugpaste

wont work

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-28.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by LeitoCc187** [comment]
i have the same fawe version and the same favs version runing on 1.18.1 on another server i use and it works fine so idk why its not working here

**Comment by dordsor21** [comment]
Use java 17.

> We're following Mojang's policy and require modern Java versions for our plugins too. Currently, all our plugins require Java 17. > If you are unsure how to update your Java version, checkout this guide: https://paper.readthedocs.io/en/latest/java-update/.
> If you are using a version prior to 1.16, add -DPaper.IgnoreJavaVersion=true to your JVM flags and your server skips the Java version check.
