### ISSUE TITLE
/fixwater not finding blocks below y=0

### ISSUE THREAD

**Issue by HkB115** [IntellectualSites/FastAsyncWorldEdit#1504]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

/fixwater would not find any flowing water or air below y=0 that needs replacing, but would work fine above y=0. This same issue might exist for /fixlava, but is untested.

### To Reproduce

Try to use /fixwater below y=0 on an area that needs to be filled with water that has an existing source block.

### Expected behaviour

/fixwater would replace an area of flowing water and air with source blocks of water up the Y level that the command was ran.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c91e5982805e484387cb45c8819b1d1d

### Fawe Version

2.0.0-SNAPSHOT-28;c28a5ee

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
The same applies to `//fixlava`.
