### ISSUE TITLE
Tab complete for multiple blocks

### ISSUE THREAD

**Issue by Help3rL** [IntellectualSites/FastAsyncWorldEdit#1509]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

The tab complete doesn't work &/ doesn't accept multiple blocks input

### To Reproduce

1. //set grass,[doesnt give secondary blocks opinion]
2. //replace block block,[block]

### Expected behaviour

to give more options for 2nd & more inputs

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5c88b6031c764f90813d8b4345b466c0

### Fawe Version

2.0.0-SNAPSHOT-46;7e96853

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Java version (build 17.0.1+12-LTS-39
OS Ubuntu 21.04 
Kerner ver Linux 5.11.0-1023-raspi
Server resources 6gb ram 
Server run on rasberypi4 8G
Extra plugins [works with WE]:
Worldguard
Advanced region market 
CoreProtect
WG Extra Flags

**Comment by Help3rL** [comment]
This server is running Paper version git-Paper-102 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 692283d)

**Comment by NotMyFault** [comment]
That would be a potential bug or regression then, considering it used to work before.

**Comment by PierreSchwang** [comment]
Information: Regression introduced with https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/ef61ecccaab13481aaa9e6c305c200980d098387
