### ISSUE TITLE
Clipboard error while copying an area

### ISSUE THREAD

**Issue by Ammarillo** [IntellectualSites/FastAsyncWorldEdit#1511]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

03.01 06:43:00 [Server] INFO Aui__ issued server command: //sel cuboid
03.01 06:43:17 [Server] INFO Aui__ issued server command: //copy
03.01 06:43:17 [Server] ERROR An unexpected error while handling a FastAsyncWorldEdit command
03.01 06:43:17 [Server] INFO java.nio.channels.OverlappingFileLockException: null
03.01 06:43:17 [Server] INFO at sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229) ~[?:?]
03.01 06:43:17 [Server] INFO at sun.nio.ch.FileLockTable.add(FileLockTable.java:123) ~[?:?]
03.01 06:43:17 [Server] INFO at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1252) ~[?:?]
03.01 06:43:17 [Server] INFO at java.nio.channels.FileChannel.lock(FileChannel.java:1089) ~[?:?]
03.01 06:43:17 [Server] INFO at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.init(DiskOptimizedClipboard.java:174) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:120) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:72) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.extent.clipboard.Clipboard.create(Clipboard.java:101) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.<init>(BlockArrayClipboard.java:114) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:142) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:270) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:726) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:747) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:728) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:698) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-46.jar:?]
03.01 06:43:17 [Server] INFO at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428) ~[?:?]
03.01 06:43:17 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
03.01 06:43:17 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
03.01 06:43:17 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
03.01 06:43:17 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
03.01 06:43:17 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

### To Reproduce

i had to reload the server and after that my clipboard was broken

### Expected behaviour

pls fix xD

### Error log (if applicable)

https://paste.gg/p/anonymous/1c6f42b95fc44c0cbd5a6851a2ef394c

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e9bd8a36bce94ce292680d681bddc9ac

### Fawe Version

2.0.0-SNAPSHOT-46;7e96853

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Don't use reload. Always restart your server.
