### ISSUE TITLE
(FAWE) Invalid value for [mask] (Invalid dangling character &.), acceptable values are any mask

### ISSUE THREAD

**Issue by ryantheleach** [IntellectualSites/FastAsyncWorldEdit#1517]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When using the following gmask (which should be valid afaik) you get the following error:

`//gmask =x>-146&&x<146&&y>44&&z<146&&z>-146`

`(FAWE) Invalid value for [mask] (Invalid dangling character &.), acceptable values are any mask`

### To Reproduce

type the command `//gmask =x>-146&&x<146&&y>44&&z<146&&z>-146`

### Expected behaviour

Expected a global mask to be created, restricting the bounds to -145 to 145 inclusive in both x and z, above y = 45.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7a292dbb887f43b99b656210c66b95a8

### Fawe Version

FastAsyncWorldEdit-47

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm not very into masks and stuff, but this is something I can reproduce so I'll label it as potential bug as of the time being.

**Comment by ryantheleach** [comment]
For what it's worth, the workaround above is changing the format to read

`//gmask [=x>-146]&[=x<146]&[=y>44]&[=z<146]&[=z>-146]`

however it's my suspicion that creating a mask from that many expressions is likely not the fastest way of doing it.

I believe the problem is that the eager matching of the & operator for normal mask and operations is blocking the usage of && in the expression.

Once the expression is being evaluated, I'm surprised that the & (lexer? i forget my terminology) is still in effect.

expressions don't have an explicit way to start and end, so I would have expected my original mask to be interpreted as a single expression.
