### ISSUE TITLE
Stable tag naming for plugin builds

### ISSUE THREAD

**Issue by Toucan-Sam** [IntellectualSites/FastAsyncWorldEdit#1519]
### What feature do you want to see added?

Currently, "stable" builds get a SNAPSHOT-## and version number as part of the name. It would be great if there was a stable tag with a standardized name. eg, `FastAsyncWorldEdit-Bukkit-STABLE.jar`

This would allow for automated plugin pulls instead of manual updates. It would however increase bandwidth significantly I imagine. In that case, publishing builds directly to github to serve the data might be preferred by the project.

### Are there any alternatives?

Alternatively, publish FAWE on spigot.org directly to allow use of the SPIGET API. This allows automated updates without downloading new copies if the version you already have is current.

### Anything else?

Manual updates are always possible, but given things like the recent log4j issues, being able to automatically update things on a regular basis is super handy. This is absolutely a nice to have and not a functional requirement.

**Comment by ryantheleach** [comment]
They already deploy to a maven site. You do *not* need to pull the large files over and over with the same name just to get the latest version.

As it stands, this is a terrible suggestion that would increase load unecessarially.

That said, I understand the intent, and why you want the functionality.

If you are defining 'stable' builds as 'stable' on jenkins, It's my understanding there is zero difference between those and dev builds, except they are the ones that compiled successfully, and passed unit tests.

They are by no means 'stable' in the sense they are the recommended version to use.

The only difference between 'success' and 'stable' on Jenkins is that 'publishers' can flag them as unstable.

https://wiki.jenkins-ci.org/display/JENKINS/Terminology

It's also my understanding that maven repo's only publish successful builds, so to get almost the exact same functionality, all that is required is to get the latest snapshot using maven dependency rules, which allows you to parse the XML to get the latest version without downloading the huge jars over and over.

There's probably already plugin libraries available that can do this.

**Comment by NotMyFault** [comment]
>> Currently, "stable" builds get a SNAPSHOT-## and version number as part of the name. It would be great if there was a stable tag with a standardized name. eg, FastAsyncWorldEdit-Bukkit-STABLE.jar

>If you are defining 'stable' builds as 'stable' on jenkins, It's my understanding there is zero difference between those and dev builds, except they are the ones that compiled successfully, and passed unit tests.

Describes it well, if the build has no test failures or flaky tests, the build will be considered as stable. There are no smoke or sanity tests that determine whether a build is stable for an end user during compile tile.

> Manual updates are always possible, but given things like the recent log4j issues, being able to automatically update things on a regular basis is super handy

FAWE was not subject to the Log4J vulnerabilities, we don't shade Log4J and rely on what the server provides at runtime.
Auto updates are not recommended, especially not in production environments. There's always the chance a bad build is published you have to restore from, like you can view it on a regular basis on the Paper discord, because people are screwed over by their auto updaters.
