### ISSUE TITLE
1.13.2 Schematics Redstone broken (Load from 1.12.2 to 1.13.2)

### ISSUE THREAD

**Issue by SkykillerTV** [IntellectualSites/FastAsyncWorldEdit#152]
# Bug report for FastAsyncWorldEdit 1.13.2
Hello

I use Fawe FastAsyncWorldEdit-bukkit-1.13.109 (test also older version) and Paper-1.13.2-b624.
When i paste a 1.12.2 Schematic on a 1.13.2 Server that contains redstone, the redstones dont connect to each other.
https://image.prntscr.com/image/nya40jo0TsyTy-hPNjEn6g.png

When i update a single redstone... all redstones update:
https://image.prntscr.com/image/emYx7DnHQRuVFwrp5mcUGg.png

**Comment by Tsoccerguy3** [comment]
I don't know why the links to the images are , 403 Forbidden .

I think this has to do with block states that update depending on the block beside it . It is being developed in breaking dev.

**Comment by SkykillerTV** [comment]
> 
> 
> I don't know why the links to the images are , 403 Forbidden .
> 
> I think this has to do with block states that update depending on the block beside it . It is being developed in breaking dev.

If you want you can add me on Discord: SchildkroetenTV#0893 
Then i can show you more images.

And yes this problem comes from the new blockstates because when i (code a plugin) update a lever, the redstone behind the lever wont update his state.

**Comment by Tsoccerguy3** [comment]
Try using the FAWE 1.13 breaking , it has more features .

**Comment by Tsoccerguy3** [comment]
Tested 1.12.2 schematics pasted into 1.13.2 FAWE 1.13.2 build 144
affects redstone , but also affects all connected blocks .
Redstone
fences
glass panes
iron bars
oak stairs (corner) direction specific
etc ..

**Comment by dordsor21** [comment]
This is likely fixed.
