### ISSUE TITLE
Cannot load plugin

### ISSUE THREAD

**Issue by MoTastisch** [IntellectualSites/FastAsyncWorldEdit#1525]
### Server Implementation

Paper

### Server Version

1.15.2

### Describe the bug

I cannot load the plugin because on 1.15.2 only up to java 14 is supportet and then the plugin will no longer work.
I need it to run PlotSquared

### To Reproduce

1. Load the Server
2. Switch java to 17
3. get mad beacause it is not working

### Expected behaviour

That fawe and plotsquared v6 load without issues

### Fawe Debugpaste

I cannot load it

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-57

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Add `-DPaper.IgnoreJavaVersion=true` to your JVM flags.
