### ISSUE TITLE
//brush spline has limited/incorrect funcitionality

### ISSUE THREAD

**Issue by Miiib** [IntellectualSites/FastAsyncWorldEdit#1527]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Currently, the spline brush has only limited functionality, it will only ever create a thin spline through selected points.

Several sources of information, including images linked in-game, point towards there being additional functionality around creating larger splines via sets of curves or loops. 
Example sources include
- https://www.planetminecraft.com/blog/fawe-tutorial/ (old guide)
- /brush spline entry on this page https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Commands#brush-commands-edittop
- In-game info when you input //brush spline and no parameters
- This video embedded on the spigotmc page for FAWE https://www.youtube.com/watch?v=GOpRy1Y2cYk 

### To Reproduce

Below is assuming FAWE is installed and you are currently in-game with the correct permissions.

1. Change selection to convex polyhedral with //sel convex
2. Create a simple curve selection through 3+ points, using //pos1 for the first and //pos2 for the subsequent points
3. Use //curve [block name] to create a curve through those points
4. Ensure there are no points in the curve that have purely diagonal connections e.g ensure all block faces are touching at least one other block face
5. Repeat steps 2-4 one or more times 
6. While holding a valid non-block item, use //brush spline [block name] to create a spline brush
7. Right click on the end block of each created curve with the brush
8. When all curves have been selected, right click again on the last selected block
9. Observe

### Expected behaviour

Expected behaviour is what is depicted in these images
https://i.imgur.com/CeRYAoV.jpg -> https://i.imgur.com/jtM0jA4.png

Current behaviour (screenshots taken today)
![Spline1](https://user-images.githubusercontent.com/19582161/148732853-7458bd4f-0ef2-4d3a-94a2-854eda24c6d5.PNG)
![Spline2](https://user-images.githubusercontent.com/19582161/148732864-7c6b8bc8-e574-412d-99fd-d81b277073f9.PNG)
 

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/baba5a4b24964e5788b9cfde089c02d1

### Fawe Version

2.0.0-SNAPSHOT-59;c2f3c13

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

From memory, this may have been broken since 1.17, I vaguely remember trying the same command and getting similar results

**Comment by NotMyFault** [comment]
Can you try build 58 please? 59 addresses https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1510 which is likely the behavior you are describing?

**Comment by Miiib** [comment]
> Can you try build 58 please? 59 addresses #1510 which is likely the behavior you are describing?

@NotMyFault  
Behaviour is identical and also incorrect on build 58 
![image](https://user-images.githubusercontent.com/19582161/149049721-a152c8f0-e963-4d6a-9c3f-f5a683b804fa.png)

**Comment by santuchoagus** [comment]
Having the same problem. It always makes the fartest connection and stops. Sometimes it just connect diagonally when the line us a //curve.
Didn't work with previous builds, last time it worked for me was 1.12.
I've seen this is a regular issue.

![image](https://user-images.githubusercontent.com/97124374/150657709-0fb622b7-168b-4f26-b540-c9ee559dd0b8.png)
