### ISSUE TITLE
Freshly-saved schematic fails to load

### ISSUE THREAD

**Issue by trainphreak** [IntellectualSites/FastAsyncWorldEdit#1534]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

A brand-new schematic that was just saved by the server cannot be loaded, either by other servers or the server that just wrote the file. It fails with a console stacktrace (linked below).

### To Reproduce

1. Select an area
2. `//copy`
3. `//schem save foo`
3a. (optional) copy file to another server
4. `//schem load foo`
5. Receive error

### Expected behaviour

The schematic that was just saved by the server should load correctly.

### Error log (if applicable)

https://paste.gg/p/anonymous/a5b4a75d606b418796c76495dfe00f47

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bae35903f00c47f381b0cf2d867a0376

### Fawe Version

FastAsyncWorldEdit version 2.0.0-SNAPSHOT-63;5fc0de0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I can replicate it with the schematic you shared on Discord. May be good to attach it here for testing purposes as well.

**Comment by trainphreak** [comment]
Shoot, I thought I was forgetting something...
[iceboats.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/7849135/iceboats.zip)

**Comment by cooperisdunn** [comment]
Having the exact same issue describe above with this schematic
[Charis.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/7849956/Charis.zip)
.

**Comment by trainphreak** [comment]
Additional note: I can load the schematic with regular WorldEdit and paste it normally.

**Comment by cooperisdunn** [comment]
I too can load and paste the schematic with regular WorldEdit.
