### ISSUE TITLE
//distr fails to work on console.

### ISSUE THREAD

**Issue by ryantheleach** [IntellectualSites/FastAsyncWorldEdit#1537]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

The output of `//distr` when performed by console is blank.

```
[00:35:45] [ForkJoinPool-8-worker-14/INFO]: ------------- Block Distribution -------------
Total Block Count: 43088256
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  2               
  0.000%  3               
  0.000%  3               
  0.000%  3               
  0.000%  3               
  0.000%  3               
  0.000%  3               
  0.000%  4               
  0.000%  4               
  0.000%  4               
  0.000%  4               
---------------- Page 2 of 10 ----------------
```

### To Reproduce

select a loaded region by a player using the console,
```
//world world
//pos1 165,165,165
//pos2 -165,165,-165
//expand vert
//distr
```

### Expected behaviour

expected that the console would dump the output to chat, unpaginated (since console), with blocks filled in.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8f0b40fc6029476bb5b7b1d0eceecd1d

### Fawe Version

FastAsyncWorldEdit- 2.0.0-SNAPSHOT-47

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
It looks like the block distribution list is displayed inverted. The entry with the highest value (%) is displayed on the last page, yet it should be a descending list, not an ascending one.

**Comment by ryantheleach** [comment]
regardless of being inverted, there is no block information.

**Comment by dordsor21** [comment]
Upstream doesn't have much better luck
![image](https://user-images.githubusercontent.com/10080017/174299565-540c2a41-415f-4aa4-a06e-f0df8e4ae929.png)
