### ISSUE TITLE
Paste flag -m is failing.

### ISSUE THREAD

**Issue by ryantheleach** [IntellectualSites/FastAsyncWorldEdit#1538]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

The -m flag is giving no result.

Copy an area containing a mix of blocks including purpur_block in a known pattern, e.g checkerboard.

paste this area over another area.

Note that using `//paste -m !purpur-block` does not have the expected effect, of treating purpur_block as transparent, or really any distinguishable result at all.

### To Reproduce

Copy an area containing a mix of blocks including purpur_block in a known pattern, e.g checkerboard.

paste this area over another area.

Note that using `//paste -m !purpur-block` does not have the expected effect, of treating purpur_block as transperent.

### Expected behaviour

I expect the source mask to be applied, and what was existing in the world already to shine through.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7a292dbb887f43b99b656210c66b95a8

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-47

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I barely work with masks, but I can reproduce what has been described, if that is some kind of issue.
