### ISSUE TITLE
//undo and //redo does not work, errors in console

### ISSUE THREAD

**Issue by partridge420x** [IntellectualSites/FastAsyncWorldEdit#1541]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

unable to use //undo //redo, possibly other commands,
Errors out in console

### To Reproduce

//undo, or //redo a action

### Expected behaviour

for it to work

### Error log (if applicable)

https://www.toptal.com/developers/hastebin/coreguzama.md

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/112ef769ca9344d0ae7ce22d61926781

### Fawe Version

2.0.0 snapshot 1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Can you provide your full `latest.log` additionally please? FWIW you can update Paper and Fawe as well if you're at it.

**Comment by partridge420x** [comment]
i have to wait until the player can come back on and test again, as it is apparently working for me

**Comment by partridge420x** [comment]
[latest.log](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/7874298/latest.log)

**Comment by partridge420x** [comment]
Update, try doing it in a world guard region
