### ISSUE TITLE
Disallowed-blocks is not working in config

### ISSUE THREAD

**Issue by partridge420x** [IntellectualSites/FastAsyncWorldEdit#1542]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Disallowed-blocks within the limit config appears to not be working

### To Reproduce

Put "minecraft:bedrock" in disallowed blocks
restart server/reload plugin (ive done both)
select bedrock
 //set 0 
 bedrock still vanishes

### Expected behaviour

If a selection contains a "blacklisted block/item" deny the usage of //set and similar commands

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/01f78e8e9f694cab876885da86d187c2

### Fawe Version

2.0.0 snapshot 1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by partridge420x** [comment]
ive ended up misunderstanding how Dissalowed-Blocks work in the config, and have now moved this to a Feature Request here #1543

**Comment by partridge420x** [comment]
Disallowed block is not working regardless and players can still place/break/change bedrock with fawe

(Config.yml | Limits )
![image](https://user-images.githubusercontent.com/26298829/149747018-1a8e7e2b-8698-4b7b-820c-abd0dd9d3e23.png)

![image](https://user-images.githubusercontent.com/26298829/149747060-54ca1ce0-fe4d-4f60-aea3-8aa3128bc3b0.png)


(worldedit-config.yml)

![image](https://user-images.githubusercontent.com/26298829/149747103-9d73b9d4-718e-4e17-be55-605e04eb8620.png)

**Comment by partridge420x** [comment]
Player report here: https://github.com/partridge420x/Midnight-Gaming/issues/22

**Comment by NotMyFault** [comment]
The disallowed block lists are, to my understanding, not meant to restrict any interaction with the existing blocks, but new operations.
