### ISSUE TITLE
Disallowed-blocks list for breaking //set and similar commands

### ISSUE THREAD

**Issue by partridge420x** [IntellectualSites/FastAsyncWorldEdit#1543]
### What feature do you want to see added?

i would like to see the ability to restrict blocks from being broken by FAWE

a Possible implantation would be a separate list in the config

- disallowed-blocks-place:
    - "minecraft:bedrock"
 
- disallowed-blocks-break:
    -  "minecraft:bedrock"
 
 when executing a command such as //set, //cut, //copy, etc, Scan the selection for the disabled blocks
 
 If a disallowed block is found within the selection, //set and similar commands will not work
 

### Are there any alternatives?

No known alternatives

### Anything else?

This would be cool for survival servers as it could be implemented in a way that could balance FAWE into a survival server

**Comment by NotMyFault** [comment]
A more fine grained setting can be found at the config.yml under default.<group>.universal-disallowed-blocks and .disallowed-blocks..
