### ISSUE TITLE
Plot Regeneration , Server Crashes and Errors

### ISSUE THREAD

**Issue by Hajatoby** [IntellectualSites/FastAsyncWorldEdit#1544]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

If I want to insert a road schematic with Plotssquared with /p regenallroads cb1
then, as can be seen in the attachment, I get a lot of errors and at some point the server times out. 

### To Reproduce

1. Go on your Plot 
2. /p createroadschematic 
3.  Disconnect from the Server 
4. console : /p regenallroads (world)

And Wait for erros :D

### Expected behaviour

Normally, the roads should simply be regenerated.
Without errors or errors in the console and without the server crashing 

### Screenshots / Videos

![Screenshot_7](https://user-images.githubusercontent.com/50121920/149507671-89844b47-bd96-4ca7-b917-ab8a40e389eb.png)
![Screenshot_8](https://user-images.githubusercontent.com/50121920/149507676-5ad2ae70-d52c-4230-abd4-a37f3555479e.png)
![Screenshot_9](https://user-images.githubusercontent.com/50121920/149507679-6a5f6ea1-1cbb-4cf6-8433-07e477265ab5.png)
![Screenshot_10](https://user-images.githubusercontent.com/50121920/149507680-b6cc6efd-6ad3-43e1-9bd0-40c26de2cf07.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/b697d5898d3940709be955cdd34ec847

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/38cefbba3f9b43dabb085f23e06722c9

### Fawe Version

FastAsyncWorldEdit version 2.0.0-SNAPSHOT-64;9e40b97

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I have already reported this error to PlotSqaured where the moderator said that this is a known problem from FAWE, but I should report it here anyway!!! His name was: Pierre 🇩🇪
Pierre#9657

**Comment by PierreSchwang** [comment]
Note: Happens also with plot expiry / plot clear and is an issue in WNA, the notify of block neighbors when their chunk is unloaded and couldn't be loaded

**Comment by PierreSchwang** [comment]
![grafik](https://user-images.githubusercontent.com/27054324/149556901-31f39074-f4a3-45b1-8525-6887a57111ed.png)
Happens with standard WorldEdit as well - more likely bug / breaking change in paper?

**Comment by PierreSchwang** [comment]
Additional logs with PlotSquared ExpireManager: https://h.pschwang.eu/esajoyeday.md

**Comment by dordsor21** [comment]
Is this still an issue with the latest P2/WE/FAWE versions?

**Comment by dordsor21** [comment]
No response and should effectively have been addressed in P2. Much of the lag in the original log is likely caused by an old issue in paper/spigot with setting biomes, and P2 doing it too many times. P2 also edits chunks in a more reasonable order when performing road updates
