### ISSUE TITLE
Create incremental schematics

### ISSUE THREAD

**Issue by Darkvodou** [IntellectualSites/FastAsyncWorldEdit#1545]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When i want create a bundle in fawe 1.12.2, i use this command :
`//schem save name_foler/`

This create a schematics ( if not exist already ) named "1.schem"
If i retape the command "2.schem", "3.schem" ...

Now it create a schematics ".schem" without name.

Can create some troubles if i use some pattern like the `#fullcopy[name_folder/]` causing to use the single schem ".schem" in place of the folder

### To Reproduce

1. Selection and copy things
2. Do the command `//schem save folder/`
3. It saved the ".schem" in folder "folder"

### Expected behaviour

Should create a schematics "1.schem" or "2.schem" if exist or "3.schem" if exist ....

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/cbd97c8b178b41d28ed562b1eebc38a2

### Fawe Version

FastAsyncWorldEdit-1.17-426

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'd rather label that as RFE, because that behavior does not exist at the moment. I don't recall that being a thing on 1.12, but I barely remember anything from 1.12 anyway, but I'm unsure how useful such RFE would be and if it wouldn't be better to work with precompiled patterns 🤔
