### ISSUE TITLE
World Edit (using survival inventory) x McMMO dupe

### ISSUE THREAD

**Issue by partridge420x** [IntellectualSites/FastAsyncWorldEdit#1550]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

using world edit players can //set their ores down, then the player would mine said ores

McMMO offers a "double drop" mechanic, though it does not work on player placed blocks (only natural)

therefor effectively duplicating their ores (high enough levels its pretty much guaranteed 

### To Reproduce

Server:
  -Install McMMO and FAWE together
  - Set FAWE to use survival inventory

Ingame:
  - Set mining level to 1000 (MCMMO)
  - Give yourself silk touch pickaxe
  
  (Pre testing | Control test )
  - Place ores by hand, Mine them, Observe expected behavior
  
  (Preforming the duplication glitch)
   - //set the ores in an area
   - Mine said ores with a silk touch pickaxe, Observe results
  

### Expected behaviour

Ores placed via FAWE (using survival inventory) should not produce the multiple drops

### Screenshots / Videos

https://youtu.be/6aJUMO4cjhM

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2f794994156847c6ad5e3fcaab74906c

### Fawe Version

2.0.1 snapshot 70

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

This dupe WILL NOT work IF the player places the blocks beforehand, exmaple

Place a line of blocks, Then set those same blocks,  the dupe will not work

This dupe will only work if the terrain is originally natural

**Comment by dordsor21** [comment]
That's not anything FAWE can fix. This is up to McMMO to add FAWE and WE integration.
