### ISSUE TITLE
`//regen` ignores biomeType parameter for different biome parsing

### ISSUE THREAD

**Issue by Gamemap** [IntellectualSites/FastAsyncWorldEdit#1552]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Please excuse me for asking my question here, but I don't have Discord and I don't see any other place to ask.

I want to generate a specific biome in a plot. I found the BiomeGenerator plugin (https://www.spigotmc.org/resources/biomegenerator.1663/) and installed FAWE because of the warning. The WorldEdit command on the BiomeGenerator page does not work. I changed it according to the wiki page, but it does not generate the specified biome.

Please tell me if I used the wrong command or if this isn't possible with FAWE.

### To Reproduce

1. Select a region (with //wand)
2. //expand vert
3. //regen cold_ocean [SEED]
4. Output: Too many arguments
---
1. Select a region (with //wand)
2. //expand vert
3. //regen [SEED] cold_ocean
4. Generates a biom from the seed (e.g. plains) and change the biom type to cold_ocean

### Expected behaviour

Generate a cold_ocean (or any other configured biom) in the selected area.

### Screenshots / Videos

Screenshot to reproduce (2.)

(The blocks are not the cold_ocean, but the biome in the F3 Screen is cold_ocean)

![grafik](https://user-images.githubusercontent.com/71942164/149981302-bb7a9d5c-546a-4c50-97dc-227db1c5bd66.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e07e2862f00c4810bed421fc1db0b8b7

### Fawe Version

FastAsyncWorldEdit version 2.0.1-SNAPSHOT-71;4d2a34f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Gamemap** [comment]
I just saw that you have a discussion page. Please excuse me for writing it here. Maybe you could transfer this to the discussion page.

**Comment by NotMyFault** [comment]
The biome part is a boolean flag, you set `-b` to determine whether you want to regenerate the biome as well.
You don't set the biome to regenerate.

The latter part I am able to reproduce, you currently can't specify a new seed, or basically any input behind the command.

**Comment by Gamemap** [comment]
@NotMyFault Sorry, I had a formatting error. There should be two different attempts by me to use the command (is now corrected.)

Does -b only change the biome type (diffrent grass color) or does it generate the specified biome?

**Comment by NotMyFault** [comment]
> @NotMyFault Sorry, I had a formatting error. There should be two different attempts by me to use the command (is now corrected.)
> 
> Does -b only change the biome type (diffrent grass color) or does it generate the specified biome?

I see, thanks for the split up.

> Select a region (with //wand)
//expand vert
//regen cold_ocean [SEED]
Output: Too many arguments

> Select a region (with //wand)
//expand vert
//regen [SEED] cold_ocean
Generates a biom from the seed (e.g. plains) and change the biom type to cold_ocean

This refers to my previous comment. The proper syntax would be `//regen -b <seed>`
You can't specify a certain biome to regenerate, it takes a snippet from the world's seed or the current world, if none is provided.
-b is an optional boolean parameter you can specify, if you want to regenerate the biome as well, it takes no further input.

However, what I can see is not working is the biome type parameter. It currently is ignored 
```java
 @Arg(desc = "Biome to apply for this regeneration (only works in overworld)", def = "")
                    BiomeType biomeType
```

**Comment by Gamemap** [comment]
So that I have not misunderstood, if the bug was not there, could FAWE replace the biome generator function to create a specific biome in a selection? (Like the images on the BiomeGenerator Bukkit page).

**Comment by Gamemap** [comment]
The page says: From the developers of PlotSquared, we bring you BiomeGenerator!
(The last release is from 2016)

This is a picture from this Site (I want to generate such a terrain):
![grafik](https://user-images.githubusercontent.com/71942164/150147875-08b24c91-0630-4958-9919-a9c0e86cc1f7.png)

**Comment by NotMyFault** [comment]
That is actually build into Fawe but not what the `//regen` command can do. Though that functionality is not updated as of the time being.

**Comment by Gamemap** [comment]
Is there another command or is it not available?

**Comment by NotMyFault** [comment]
Currently it's commented out.

**Comment by dordsor21** [comment]
Whilst it's relatively trivial to re-add the decorations for a given biome, it's not possible to "force" the correct terrain shape (i.e. ocean/mountains/badlands etc. need to have a seed randomly chosen that works at the given world coordinates)

**Comment by Gamemap** [comment]
Thank you for looking into this.
Would it be possible (but difficult) to also generate the terrain shape in a later pr?
I don't know if this feature I'm looking for was the [/generatebiome command](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/63f031b01a96837922b6f2c2425834c8401e727a/worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java#L437) in previous versions. If this is the case I think this should be added to the /generatebiome command instead of the //regen command.

**Comment by dordsor21** [comment]
> it's not possible to "force" the correct terrain shape

**Comment by Gamemap** [comment]
Thank you

**Comment by dordsor21** [comment]
The "old source code" is... old. It also never attempted to place the correct terrain either.

**Comment by Gamemap** [comment]
@dordsor21 Thank you very much, it is working wonderful!
