### ISSUE TITLE
Reimplement auto rotate (`-r`) parameter of pattern `#fullcopy`

### ISSUE THREAD

**Issue by Darkvodou** [IntellectualSites/FastAsyncWorldEdit#1561]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

**The parameter rotate of the pattern #fullcopy is not working**

Syntaxe on the wiki :

`#fullcopy [schem|folder|url=#copy] [rotate=false] [flip=false]`

The schem | folder | url | #copy will be not auto rotate ( maybe the flip, i can't test it )

You have also the same issue on the `brush copypaste` with the parameter `-r` ( and maybe other ? )

### To Reproduce

1. Create a schem with directional particularity
2. Save it in a folder
3. Use the pattern `#fullcopy[test/][true]` in a command like a  `//replace 41 #fullcopy[test/][true]`
4. See they are have all the same rotation

### Expected behaviour

Have multiple rotation

### Screenshots / Videos

![2022-01-24_02 47 00](https://user-images.githubusercontent.com/46628306/150709200-bb1d98ba-9786-41ff-b82b-ec100f167049.png)

### Fawe Debugpaste

An unexpected error while handling a FastAsyncWorldEdit command /fawe debug paste java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseString(java.lang.String)'

### Fawe Version

FAWE 2.0.1-SNAPSHOT-73;016b4ba

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
The parameter is currently not implemented, labeling as RFE.
