### ISSUE TITLE
DelegateSemaphore implements synchronized incorrectly

### ISSUE THREAD

**Issue by libraryaddict** [IntellectualSites/FastAsyncWorldEdit#1565]
### Server Implementation

Spigot

### Server Version

1.18.1

### Describe the bug

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/DelegateSemaphore.java

Both acquire() and release() are both synchronized methods, however this fails to account for when two threads are both accessing the same lock.

This is mostly noticeable to us as I often perform some laggy world saving operations.

### To Reproduce

Thread $1 calls acquire(), and starts doing some work.
$2 calls acquire(), but has to wait as $1 has the underlying lock.
$1 finishes doing some work, moves to call release()
$1 waits for $2 to finish calling acquire(), because the method is synchronized and release() cannot be called while $2 is calling acquire()

So because $1 has the underlying lock, $2 cannot finish calling acquire(), because $2 has the synchronized lock, $1 cannot call release()

### Expected behaviour

$1 calls acquire(), $2 calls acquire(), $1 is not blocked from calling release()

### Error log (if applicable)

https://gist.github.com/ec9b489ef20fe333000a8eb646dd0c7e

### Fawe Debugpaste

N/A

### Fawe Version

2.0.1-SNAPSHOT-76;e8f72d6

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Note that this only happens on Spigot
