### ISSUE TITLE
//brush sspl Cannot set location when player is not an admin

### ISSUE THREAD

**Issue by MiunaPA** [IntellectualSites/FastAsyncWorldEdit#1569]
### Server Implementation

Paper 1.18.1-176

### Server Version

1.18.1

### Describe the bug

When using //brush sspl，After using the command setting, even if the player already has `fawe.admin`, `fawe.bypass`, `worldedit.*` permissions, it cannot be used.

### To Reproduce

1. Start a server and install FastAsyncWorldEdit, 2.0.1-SNAPSHOT-76 and LuckPerms-Bukkit-5.3.98
2. Set global permissions to have `fawe.admin`, `fawe.bypass`
3. Hold an item in the game, set `//brush sspl stone 3`
4. Left click anywhere

### Expected behaviour

There should be a setup complete message, but it only display message when the player is an operator.

### Screenshots / Videos

https://www.youtube.com/watch?v=7knm0M0Vf-w

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3f1ba6dd5e1f4a77ac618ee134978ead

### Fawe Version

2.0.1-SNAPSHOT-76

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
The .admin permission controls administrative commands and .bypass controls region bypass. Both permissions do not provide additional permissions to access brushes. Interpreting asterisk permissions is down to your permission plugin.
Take a look at the [documentation](https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/] if you are unsure which permission to assign.
