### ISSUE TITLE
invalid command don't send syntaxes of command

### ISSUE THREAD

**Issue by Darkvodou** [IntellectualSites/FastAsyncWorldEdit#1585]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hi ! 

Recently, commands don't send anymore syntaxes of the command when we mistake it.

As in previously version all commands should send syntaxes.

### To Reproduce

1. mistake a command
2. Saw we mistake a parameter and don't have the syntaxe of the actual command

### Expected behaviour

have the syntaxe 

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/46628306/151723343-900861f6-40d0-4e8e-b925-bb5ca3c279fa.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/613a73e80bc94adc941e074660860fc4

### Fawe Version

2.0.2-SNAPSHOT-82;f013646

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
That is the actual behavior, if you want to view the entire command nevertheless, you can use `//help <command>` or take a look at the wiki.

**Comment by Darkvodou** [comment]
It's way usefull to have directly the syntaxe when we miss the command than use and other command ( that user can don't know )
