### ISSUE TITLE
Original Plugin?

### ISSUE THREAD

**Issue by FrostBlade5** [IntellectualSites/FastAsyncWorldEdit#1590]
### What feature do you want to see added?

I am confused.
So there is worldedit, then we have async worldedit, and we also have fast async worldedit.
Now im lost.
Which is the original plugin and which plugin? And most important which has the best performance?

I am speaking about this:
https://github.com/SBPrime/AsyncWorldEdit/
https://github.com/IntellectualSites/FastAsyncWorldEdit
https://dev.bukkit.org/projects/worldedit/files

Thank you.

### Are there any alternatives?

zero

**Comment by PierreSchwang** [comment]
WorldEdit is the "normal" plugin. 
FastAsyncWorldEdit is a fork maintained by IntellectualSites, which provides better performance for larger scale operations.

I would suggest you using FAWE instead of AsyncWorldEdit, but I can't take that decision from you.
