### ISSUE TITLE
Error when using //copy

### ISSUE THREAD

**Issue by Skyslycer** [IntellectualSites/FastAsyncWorldEdit#1594]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When running //copy on a selection, [this](https://haste.skyslycer.de/tukuzewini.sql) error occurs.

### To Reproduce

Not really sure, as it worked right after I restarted the server.
- Select an area
- Expand the selection vertically
- Run //copy

### Expected behaviour

It should copy the selection.

### Error log (if applicable)

https://haste.skyslycer.de/tukuzewini.sql

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4be4ed36f962437a97ef202aeb30b674

### Fawe Version

2.0.2-SNAPSHOT-84;faa2477

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I frankly don't recall why I labeled this as backburner. Based on the steps provided, I'm not able to replicate it. Do you mind updating Paper and Fawe and possibly provide new steps how to replicate the issue?
