### ISSUE TITLE
NPE when invoking the byteBuffer of the DOC

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/FastAsyncWorldEdit#1595]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

On use of long mask, the server crash

### To Reproduce

1. Make a selection of something with wand or //pos1 & //pos2
2. `//copy`
3. take a item for create a brush
4. `//br clipboard -a`
5. `//mask light_gray_wool,smooth_stone,gravel,andesite,smooth_basalt,granite,terracotta,pink_terracotta,light_gray_concrete_powder,deepslate_coal_ore`
6. Click somewhere and the server crash

### Expected behaviour

The server may not crash

### Error log (if applicable)

https://paste.gg/p/anonymous/1bdc2633199b46a4a3633bc10def2616

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/97c88c1c15c94f189a4ff6e4b27501d3

### Fawe Version

FastAsyncWorldEdit-2.0.2-SNAPSHOT-84

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

fawe debugpaste did not have relevant log because the server crash on click.
See error log into paste.gg link

Thanks

**Comment by NotMyFault** [comment]
Based on the steps provided, I'm not able to replicate that.
