### ISSUE TITLE
Not using worldedit is also taking up resources

### ISSUE THREAD

**Issue by AdminHcat** [IntellectualSites/FastAsyncWorldEdit#1597]
### Server Implementation

Purpur

### Server Version

1.18.1

### Describe the bug

Not using FastAsyncWorldEdit is also taking up resources

### To Reproduce

When used

### Expected behaviour

Not using FastAsyncWorldEdit is also taking up resources

### Error log (if applicable)

https://timings.aikar.co/?id=6c0e8ab2bac140028faf6077fd01aaa3

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0ad6a3809ac84149bc47ed0f5120019e

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-84

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
You can disable the tick-limiter in the config.yml, however, a timings cost of 2234 implies wrong/overloaded hardware, so don't expect a miracle performance boost.
