### ISSUE TITLE
//undo doesn't bring back block entity data

### ISSUE THREAD

**Issue by Aeltumn** [IntellectualSites/FastAsyncWorldEdit#1600]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When block entities are affected by //undo their data is completly lost. Redo works and brings the data back.

### To Reproduce

1. Place down a chest with some items in it
2. Select a region containing the chest
3. Run `//air`
4. Run `//undo`
5. The chest will have become invisble and is empty when opened.

### Expected behaviour

Block entities have their data returned when an operation is undone.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/55f179cc20f74614957da1ed5b64bc81

### Fawe Version

2.0.2-SNAPSHOT-87;15b9b83

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by leumas1960** [comment]
I just ran into this issue on my Aternos server. It appears to have inconsistent issues with //cut, //copy, and //undo. I don't think it's copying nbt data in the first place. It works sometimes, then breaks after you do it once or twice.

**Comment by aurorasmiles** [comment]
> I just ran into this issue on my Aternos server. It appears to have inconsistent issues with //cut, //copy, and //undo. I don't think it's copying nbt data in the first place. It works sometimes, then breaks after you do it once or twice.

That sounds like #1548 ?

**Comment by leumas1960** [comment]
I'm also using paper, latest build of FAWE and FAVS available on Aternos.
