### ISSUE TITLE
Make /to command optional.

### ISSUE THREAD

**Issue by kidney-bean** [IntellectualSites/FastAsyncWorldEdit#1601]
### What feature do you want to see added?

An option in the config to remove /to command

### Are there any alternatives?

No

### Anything else?

I know I, and probably others, have a /to command to go to other players. But now I can't use it, because FAWE has taken over the command.

**Comment by NotMyFault** [comment]
Such a specific option will not be added. You can work with the plugin's namespace to delegate the command to the appropriate target, e.g /fastasyncworldedit:to
