### ISSUE TITLE
Does it support 1.15?

### ISSUE THREAD

**Issue by MrXiaoM** [IntellectualSites/FastAsyncWorldEdit#1604]
### Server Implementation

Paper

### Server Version

1.15.2

### Describe the bug

> 1.15.2, 1.16.5, 1.17.1, 1.18, 1.18.1 - FastAsyncWorldEdit actively develops against and supports these versions.

I launch my server with Zulu openjdk 17.0.2 but it shows

> Unsupported Java detected (61.0). Only up to Java 14 is supported.

It's it not support? or I have to use some Server Implementation I do not tried?

### To Reproduce

1. Start the server with Java 17
2. Server shut down.

### Expected behaviour

FAWE needs Java 17 but Spigot seems support up to Java 14

### Fawe Debugpaste

none

### Fawe Version

latest

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Add `-DPaper.IgnoreJavaVersion=true` to your JVM flags when launching the server. If it is not recognized, update Paper.

**Comment by MrXiaoM** [comment]
> Add `-DPaper.IgnoreJavaVersion=true` to your JVM flags when launching the server. If it is not recognized, update Paper.

ok, thanks.

**Comment by MrXiaoM** [comment]
But many plugins does not work with Java 17. I found legacy version in ci. It works. Maybe we should remove 1.15 support for latest version?

**Comment by SirYwell** [comment]
As FAWE itself works fine on 1.15, I don't see any reason to do that.
