### ISSUE TITLE
Panel does not respond

### ISSUE THREAD

**Issue by vanlueckn** [IntellectualSites/FastAsyncWorldEdit#1606]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

I have a bug with the latest fawe version on paper 1.18.1. With fawe activated the server crashes on startup. Without fawe the server does start without any issues.

### To Reproduce

1. Install latest paper and fawe 1.18.1 versions
2. start the server
3. server crashes

### Expected behaviour

Start without crash

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/53119369/153186338-ce544c8d-c972-447f-adf3-5d3ad164638c.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/67ef94e1d86b44219fc55f8ed9cfa144

### Fawe Debugpaste

not possible

### Fawe Version

v2.0.2-SNAPSHOT-88;7e17a5c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Paper Version is 1.18.1 #187

**Comment by NotMyFault** [comment]
This doesn't look like a crash but your panel stop displaying the actual console output. Take a look at the actual console to see whether it aligns with the displayed output.

**Comment by vanlueckn** [comment]
The process does not really crash. But the process freezes as soon as FaWe is loaded. Then the CPU usage of the container goes to 0% and nothing happens. I have also already displayed the direct log via the console.

I have also waited a few hours to see if something happens.

As soon as I uninstall FaWe everything works again. The freeze always happens at the same point of the startup.

**Comment by NotMyFault** [comment]
That doesn't provide much information, attach a jstack please.

**Comment by vanlueckn** [comment]
This is the jstack dump:

https://paste.gg/p/anonymous/5a017a71b9f3474d8446ea7cb3ce6368

**Comment by dordsor21** [comment]
Try disabling the update checker?

**Comment by vanlueckn** [comment]
Oh yes, now it works
