### ISSUE TITLE
Brush height yscale does not work

### ISSUE THREAD

**Issue by fulwerin** [IntellectualSites/FastAsyncWorldEdit#1612]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

**The command:**

`/brush height [radius=5] [file|#clipboard|imgur=null] [rotation=0] [yscale=1.00] [-h]`

you can only specify the [rotation=0] but not the [yscale=1.00] or the flag [-h]

### To Reproduce

1. Enter command
`/brush height [radius=5] [file|#clipboard|imgur=null] [rotation=0] [yscale=1.00] [-h]`
2. error message received
`Too many arguments.`

### Expected behaviour

Could this be fixed or is this a bigger deal? 

### Screenshots / Videos

![javaw_2022-02-14_22-47-30](https://user-images.githubusercontent.com/25588081/153952587-c71bcc57-d650-499f-b842-0717bedd8c6c.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6c4081facd294779b2c229dafbec701f

### Fawe Version

FastAsyncWorldEdit 2.0.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [ ] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Thanks.

**Comment by NotMyFault** [comment]
I updated the wiki to adjust the syntax displayed. Use `//br height 20 0 https://i.imgur.com/mTe11fY.png 5`, the y scale accepts full integers. See `//help brush height` ingame for all possible parameters
