### ISSUE TITLE
Incompatibility with WorldGuard

### ISSUE THREAD

**Issue by ConaII** [IntellectualSites/FastAsyncWorldEdit#1613]
### Server Implementation

Pufferfish-purpur-8  (git-Purpur-1428)

### Server Version

1.17.1 (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Describe the bug

N/A

### To Reproduce

N/A

### Expected behaviour

N/A

### Error log (if applicable)

https://paste.gg/p/anonymous/11c08a1f0d7345a4b7e6951f0a293ca4

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8c8e9d64a102409889e726cdf3d95da0

### Fawe Version

FastAsyncWorldEdit-2.0.2-SNAPSHOT-9 (Build 91)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate that on an up to date version of Paper, Fawe and with WorldGuard v 7.0.7-SNAPSHOT+2175-dca0515.
Some more information would be helpful, alongside using a supported environment.
