### ISSUE TITLE
Cannot load FAWE with Minecraft 1.16.5

### ISSUE THREAD

**Issue by ClemFR** [IntellectualSites/FastAsyncWorldEdit#1625]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Minecraft 1.16.5 require Java 16 version but FAWE minimal Java version is 17.

### To Reproduce

1. Put FAWE.jar in ./plugins
2. Start the server

### Expected behaviour

Expected: successful loading of FAWE

### Error log (if applicable)

https://paste.gg/p/anonymous/5ceba0a3ff44400996dad57978aad0b3

### Fawe Debugpaste

Unknown command. Type "/help" for help.

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-101

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
"We're following Mojang's policy and require modern Java versions for our plugins too. Currently, all our plugins require Java 17.
If you are unsure how to update your Java version, checkout this guide: https://paper.readthedocs.io/en/latest/java-update/.
If you are using a version prior to 1.17, add -DPaper.IgnoreJavaVersion=true to your JVM flags and your server skips the Java version check."
