### ISSUE TITLE
[Feature Request] /roof /floor commands and /wall improvement

### ISSUE THREAD

**Issue by lrmtheboss** [IntellectualSites/FastAsyncWorldEdit#1627]
### What feature do you want to see added?

/roof <material> <thickness (optional, defaults to 1)>
/floor <material> <thickness (optional, defaults to 1)>
these commands would fill the top or bottom-most layers (specified by the thickness int) will the specified material, similar to how /wall only does the outermost layer of the selection

If this is added then to make a box you would only need to select the 2 diagonal corners then run /wall /roof and /floor (in any order). For those of us that need to make several boxes quite often, it would save us a lot of time

For the /wall improvement, adding the thickness argument as mentioned above for /roof and /floor would help a ton if you need multi-layer thick walls, instead of having to do each layer individually

### Are there any alternatives?

selecting the diagonal corners or (if you know the cords) doing /pos1 x,y,z and /pos2 x,y,z, both of which (can) take a lot of time

**Comment by dordsor21** [comment]
`//faces` already exists. Setting the "floor" and "ceiling" of a region is pointless as you can just select the single-y-level and //set
