### ISSUE TITLE
Large nether portals don't break correctly on default tick limiter settings

### ISSUE THREAD

**Issue by Leomelonseeds** [IntellectualSites/FastAsyncWorldEdit#1628]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

On a default implementation of FAWE with no config changes, it is possible to create glitched nether portals due to the tick limiter stopping some of the portal blocks from breaking when a large nether portal is destroyed due to water/breaking obsidian. Disabling the tick limiter fixes this issue.

### To Reproduce

1. Make sure the tick limiter is enabled.
2. Create a 23x23 nether portal and light it
3. Break the portal through any means
4. Some portal blocks will be left behind, and you will not be able to relight the portal until all the portal blocks are destroyed/

### Expected behaviour

All nether portal blocks should break simultaneously and you should immediately be able to relight the portal.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/806cdb1cae1b4b0785f7b917a172e4b4

### Fawe Version

FastAsyncWorldEdit version 2.0.2-SNAPSHOT-101;f8e6feb

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
The tick limiter is designed to cancel possible noise causes, like you described. You can safely turn it off in the config.yml
