### ISSUE TITLE
//chunk selects the old dimensions on 1.18.1

### ISSUE THREAD

**Issue by sphings79** [IntellectualSites/FastAsyncWorldEdit#1630]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

If you run //chunk the y coords will only selected from 0 to 255

### To Reproduce

1. run //chunk
2. look at the selection or do //set 0

### Expected behaviour

should select from y -64 to 319

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dca4b21d82414147b9aa07fb3522a174

### Fawe Version

§aFastAsyncWorldEdit§f version §a2.0.2-SNAPSHOT-105;b8ab2a5

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
That is how it works, take a look at `//help chunk` how to parse chunk coordinates.
