### ISSUE TITLE
Please update bukkit

### ISSUE THREAD

**Issue by ikafly144** [IntellectualSites/FastAsyncWorldEdit#1652]
### What feature do you want to see added?

We are running the server on aternos. Your FAWE cannot be used in aternos as https://dev.bukkit.org/projects/fawe/files has not been updated :(

### Are there any alternatives?

Please update it to the new version

### Anything else?

私は日本人です。この文章は"google翻訳"で翻訳しています。読みにくかったら申し訳ありません。
I am Japanese. This sentence is translated by "google translate". I'm sorry if it's hard to read.

**Comment by NotMyFault** [comment]
I uploaded version 2.1.0 to devbukkit short after I announced the release.
It's yet still in review:
![](https://i.imgur.com/bvYIgaP.png)
