### ISSUE TITLE
p delete or p clear create a hole after Version 2.0.2.120

### ISSUE THREAD

**Issue by magicmener** [IntellectualSites/FastAsyncWorldEdit#1666]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Paper 1.17.1-409
PS6.6.1
FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-121 to FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-132 
When i use the Version FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-88.jar p delete or p clear works, with FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-125 i get the hole
and after p claim i would be teleported 150 Block high

I tested now with all version from 2.0.2.88 to 2.0.2.122 p delete and p clear works not after version 2.0.2.12
![unknown](https://user-images.githubusercontent.com/101211284/158471204-ab4c01be-080e-4188-ad0f-b2a7d4265938.png)
0

### To Reproduce

/p claim
/p delete
or
/p claim
/p clear
/p confirm

### Expected behaviour

Reset the Plot like in Version 2.0.2.88 to Version 2.0.2.120 it works

### Screenshots / Videos

![unknown](https://user-images.githubusercontent.com/101211284/158471553-ca66b3fa-b16c-4d34-8bcf-ad84dc84935c.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d90a113a75a540bd85ae66e61f058127

### Fawe Version

2.1.0 to 2.1.1.132

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
I wasn't able to replicate that based on the steps provided. Do you mind sharing your world and a plot debugpaste? That could provide additional intel.

**Comment by magicmener** [comment]
https://athion.net/ISPaster/paste/view/535763d6cd3546b0b833bdf6f952357d
World is to big i cant share

**Comment by NotMyFault** [comment]
> https://athion.net/ISPaster/paste/view/535763d6cd3546b0b833bdf6f952357d World is to big i cant share

You can compress it or share the first few region files.

**Comment by magicmener** [comment]
How


> 

How

**Comment by magicmener** [comment]
https://easyupload.io/ofttj8

**Comment by NotMyFault** [comment]
Hm, I'm unable to replicate that in your provided world with your configuration:

https://user-images.githubusercontent.com/13383509/158487400-a4524c57-3046-4e31-8755-ce4229c55eb8.mp4

See my configuration at the end of the clip.

**Comment by magicmener** [comment]
https://ufile.io/abf76u9n

**Comment by zOIDAdaJulian** [comment]
Hey, I can also replicate that bug! :D
Server Software: git-Paper-402 (MC 1.17.1)
PlotSquared Version: 6.6.1-Premium
FAWE Version: 2.1.1-SNAPSHOT-134;465c81d

Video:
https://gyazo.com/84c3eef2a560273fa57d8d100bdccc23

**Comment by NoltoxGit** [comment]
Hi!
I can also testify about the bug.

I use :
FAWE v2.1.1-SNAPSHOT-134
PlotSquared v6.6.1-Premium
([and other plugins](https://prnt.sc/A50surEceojh))

With as version :
[Puffer-21 (MC: 1.17.1)](https://prnt.sc/yCI_ReWh1Rdk)

**Comment by NotMyFault** [comment]
Please link a `/plot debugpaste` and use an up to date version of Paper while doing so.

**Comment by NoltoxGit** [comment]
I'm using the latest version of Pufferfish (which normally includes the latest Paper maj), and yes here is the debug link: [here](https://athion.net/ISPaster/paste/view/65950a40de094cab86ba5a161bfe780c)

**Comment by NotMyFault** [comment]
> I'm using the latest version of Pufferfish (which normally includes the latest Paper maj), and yes here is the debug link: [here](https://athion.net/ISPaster/paste/view/65950a40de094cab86ba5a161bfe780c)

That was not the point. Please use an up to date version of Paper, not some fork.

**Comment by NoltoxGit** [comment]
Okay, I'm doing this tomorrow on one of my dev' servers ^^' (I can't afford to change without testing my main server version)

**Comment by magicmener** [comment]
These plugins i have also installed like [NoltoxGi](https://github.com/NoltoxGit) and [zOIDAdaJulian](https://github.com/zOIDAdaJulian) can you tell us which Plugins you also have installed which here below listed 
CMILIB
CoreProtect
FastAsyncWorldEdit
FastAsyncVoxelSniper
Luckperms
Litebans
Multiverse-Core
PlaceholderAPI
Protocollib
Plotsquared
Vault
WorldGuard

**Comment by zOIDAdaJulian** [comment]
> These plugins i have also installed like [NoltoxGit](https://github.com/NoltoxGit).
> 
> 
> 
> [zOIDAdaJulian](https://github.com/zOIDAdaJulian) can you tell us which Plugins you also have installed which here below listed 
> 
> CMILIB
> 
> CoreProtect
> 
> FastAsyncWorldEdit
> 
> FastAsyncVoxelSniper
> 
> Luckperms
> 
> Litebans
> 
> Multiverse-Core
> 
> PlaceholderAPI
> 
> Protocollib
> 
> Plotsquared
> 
> Vault
> 
> WorldGuard
> 
> 

All except of Litebans and FastAsyncVoxelSniper ;)

**Comment by NoltoxGit** [comment]
Hello!
Here is a [video ](https://www.youtube.com/watch?v=lSBv2yWpp-c)and the [pastedebug](https://athion.net/ISPaster/paste/view/ae1dd4fa6ee74d6e83ae078eefdd0476).

**Comment by magicmener** [comment]
Plugin                           me                                                         Noitoxgit                              
Diffrent Version
_CMILIB             Version: 1.1.2.1                                               Version: 1.1.2.3_

_CoreProtect    Version: 20.1                                                    Version: 21.2_        

_FastAsyncVoxelSniper  Version: 2.2.4                                       Version: 2.3.0_                 

_Luckperms Version: 5.4.2                                                        Version: 5.4.13_                   

_Vault                Version: 1.7.3-b131                                             Version: 1.7.3-CMI_        

_FastAsyncWorldEdit  2.1.1-SNAPSHOT-132;c672d7a              2.1.1-SNAPSHOT-134;465c81d_               
                    
Same Verison:

Litebans Version: 2.8.13                                                           Version: 2.8.13

Multiverse-Core  Version: 4.3.1-b861                                       Version: 4.3.1-b861

PlaceholderAPI Version: 2.11.1                                                 Version: 2.11.1

Protocollib Version: 4.8.0                                                             Version: 4.8.0

Plotsquared Version: 6.6.1-Premium                                           Version: 6.6.1-Premium

WorldGuard Version: 7.0.6+1cff55f                                                 Version: 7.0.6+1cff55f

Which Version do you have? [zOIDAdaJulian](https://github.com/zOIDAdaJulian)

**Comment by NoltoxGit** [comment]
> Hello! Here is a [video](https://www.youtube.com/watch?v=lSBv2yWpp-c) and the [pastedebug](https://athion.net/ISPaster/paste/view/ae1dd4fa6ee74d6e83ae078eefdd0476).

Would it be possible to have a new one please? It's quite annoying as a bug :/

**Comment by NoltoxGit** [comment]
Hellow,
Would it be possible to have a new one please? It's quite annoying as a bug :/

~ Noltox ~
