### ISSUE TITLE
Crash when trying to delete a plot in plotsquared with /p delete.

### ISSUE THREAD

**Issue by SteffoSpieler** [IntellectualSites/FastAsyncWorldEdit#1670]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When I try to delete a plot with PlotSquared (/p delete), I get a crash message in the console.

### To Reproduce

1. Create a plot.
2. (Build something in it)
3.  Use `/p delete`

### Expected behaviour

The plot should be deleted.

### Error log (if applicable)

https://paste.gg/p/anonymous/0663e4b1e48b43de86b6fa4a2bdaa668

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f255b030d2d1443fafcd2a00c266ff98

### Fawe Version

FastAsyncWorldEdit version 2.1.1-SNAPSHOT-134;465c81d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update PlotSquared
