### ISSUE TITLE
[Experimental options] Dynamic Chunk Rendering

### ISSUE THREAD

**Issue by TheDevTec** [IntellectualSites/FastAsyncWorldEdit#1672]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

After the player connects to the server, an error is sent to the console

### To Reproduce

1. Purpur 1.18.2
2. Enable dynamic-chunk-rendering
3. Join to the server

### Expected behaviour

Sets the player's view-distasnce too early

### Error log (if applicable)

https://paste.gg/p/anonymous/cc6aa2503a9245a1bb7be0945570b23c

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/260753de43364c27970632a8cc96293c

### Fawe Version

2.1.1-SNAPSHOT-134;465c81d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
If your server platform does not exist on the platform dropdown, it's not supported. Please try to reproduce issues on a supported platform first.
