### ISSUE TITLE
Convert world from Bedrock Edition to Java Edition

### ISSUE THREAD

**Issue by Subject-4** [IntellectualSites/FastAsyncWorldEdit#168]
**Is your feature request related to a problem? Please describe.**
Currently when trying to remap worlds between Bedrock ID's and PC IDs (on FAWE for Spigot 1.13) the output is "0 blocks changed" however it works with schematics. 

**Describe the solution you'd like**
I want to be able to use the "/anvil replaceall <world>" command properly. So it can convert Bedrock Block ID's to Java Edition Block ID's. 

**Describe alternatives you've considered**
I've tried finding tools to convert Bedrock block ID's to Java Edition ID's but they don't exist. 

**Additional context**
I just want to be able to convert my Anvil map running on Nukkit (Bedrock Server Software) to Spigot

**Comment by dordsor21** [comment]
There are various existing tools for this. I recommend MCCToolChest.
