### ISSUE TITLE
dosent work Fawe v2.1.0 aternos server ip denistesting.aternos.me im online for maybe 1 more hour

### ISSUE THREAD

**Issue by Denisbg2011game** [IntellectualSites/FastAsyncWorldEdit#1682]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

commands for modifiying the world like //set //air //center and others dont work

### To Reproduce

make aternos server
select paper 1.18.2 server software
install fawe 2.1.0 from plugins i naternos
start server
get a wand //wand
select two regions
do //air or //set air or any other block, and it will give u error, anddd if u use //replace air block it will give a different error

### Expected behaviour

would do the command

### Screenshots / Videos

https://drive.google.com/file/d/17GlVaa2aS9kobkc1G6dQ-1eSfkLbrhnm/view?usp=sharing
its loud

### Error log (if applicable)

https://paste.gg/p/anonymous/abdecad64f8c43b7aa76c89d3ce0d900

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/15d65296dfa94e5eaeb3ab2ac8a6eca7

### Fawe Version

2.1.0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

unfortunately i cant use the most latest build becasue im on "aternos" and they havent updated it to the latest snapshot so i am on 2.1.0, theres nothing i can do

**Comment by NotMyFault** [comment]
Update Fawe and Paper. If your host doesn't offer you the newest builds, there's nothing we can do about it.

**Comment by Denisbg2011game** [comment]
> Update Fawe and Paper. If your host doesn't offer you the newest builds, there's nothing we can do about it.

oh okay
