### ISSUE TITLE
1.16.5 Java 17 Unsupported

### ISSUE THREAD

**Issue by illudota** [IntellectualSites/FastAsyncWorldEdit#1686]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

1.16.5 isn't possible with Java 17, it says: 'Unsupported Java detected, Only up to Java 16 is supported.' How can we use FAWE in 1.16.5 if 1.16.5 can't run Java 17?

### To Reproduce

1. Install 1.16.5 Jar
2. Run it with Java 17
3. Then see your server won't start

### Expected behaviour

Crashing on start

### Screenshots / Videos

```container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -Xmx16G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:InitiatingHeapOccupancyPercent=20 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar nogui
Unsupported Java detected (61.0). Only up to Java 16 is supported.
container@pterodactyl~ Server marked as offline...
[WitherPanel Daemon]: ---------- Detected server process in a crashed state! ----------
[WitherPanel Daemon]: Exit code: 0
[WitherPanel Daemon]: Out of memory: false
[WitherPanel Daemon]: Checking server disk space usage, this could take a few seconds...
[WitherPanel Daemon]: Updating process configuration files...
[WitherPanel Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[WitherPanel Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[WitherPanel Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```

### Error log (if applicable)

Pasted above.

### Fawe Debugpaste

None, because server is crashing on start due to Java 17 1.16.5

### Fawe Version

Latest

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

None

**Comment by einTosti** [comment]
Add
`-Paper. IgnoreJavaVersion=true` to
your VM flags (before `-jar`) and your server skips the
Java version check.

**Comment by einTosti** [comment]
Add `-Paper.IgnoreJavaVersion=true` to
your VM flags (before `-jar`) and your server skips the Java version check.

**Comment by MaicolFrantech** [comment]
This flag is incorrect. The correct flag is `-DPaper.IgnoreJavaVersion=true`
