### ISSUE TITLE
java.io.IOException: locked a portion of the file

### ISSUE THREAD

**Issue by purejosh** [IntellectualSites/FastAsyncWorldEdit#1695]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Console log spam, unsure if affecting world. 

### To Reproduce

Unable to reliably reproduce. 

### Expected behaviour

No console log spam. 

### Error log (if applicable)

https://gist.github.com/purejosh/0c5cfe8e02eb9cd340eccf180b8d6c31

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/df1783887eeb4bb29cda55e038e93b36

### Fawe Version

2.1.2-SNAPSHOT-150;ed9317b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by aurorasmiles** [comment]
Looks like something else is accessing your disk clipboards, are you sharing those across multiple servers or something similar?

**Comment by purejosh** [comment]
Being totally honest, I didn't know you could use a clipboard across servers. I should only be using it in one server. I do use a velocity server network though.

**Comment by NotMyFault** [comment]
Looks like the typical Windows shenanigans of bad access restrictions to files in use.
Basically a non-issue on any UN*X environment.
