### ISSUE TITLE
Could not pass event PlayerJoinEvent & PlayerTeleportEvent

### ISSUE THREAD

**Issue by Rokhnir** [IntellectualSites/FastAsyncWorldEdit#1696]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

After setting up `dynamic-chunk-rendering`, errors are dumped in the console when a player join.
The feature however seems to work.

### To Reproduce

- Setting `dynamic-chunk-rendering` to 32 while `view-distance` in `server.properties` is set to 3
- Join the server

### Expected behaviour

Since it's an experimental feature, I wasn't expecting this to run without any issue, this bug report is only there to share these errors

### Error log (if applicable)

https://paste.gg/p/anonymous/332ab17295a0495ca6de83d161ef95d0

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e6d3196ed6614752b47bd51c8c285f85

### Fawe Version

FastAsyncWorldEdit version 2.1.2-SNAPSHOT-151;2483eac

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
This doesn't look like something we should take care of and is caused by a misconfiguration on your end:
> java.lang.IllegalArgumentException: Simulation distance must be a number between 2 and 32 or -1, got: 1

**Comment by Rokhnir** [comment]
Unfortunately, I've got my simulation distance set top 8 in the `server.properties` and `spigot.yml` is using the default values specified in `server.properties` for both `view-distance` and `simulation-distance`.
