### ISSUE TITLE
Clipboard issue?

### ISSUE THREAD

**Issue by michiexe** [IntellectualSites/FastAsyncWorldEdit#1704]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I wanted to copy something and while I executed "//copy" I got an error, and it told me to report this.

### To Reproduce

//wand
Select an area
//copy
See error

### Expected behaviour

I expected it to copy something for me so I would be able to paste it somewhere else.

### Screenshots / Videos

![Bild_2022-04-16_202535688](https://user-images.githubusercontent.com/42840496/163687028-eab34f82-7609-4279-96f2-b3bdb8abea6f.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/2e8afe0cd627425da1e2c00fe2e67e08

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f50540a9456747e89f9795076b13dc11

### Fawe Version

FastAsyncWorldEdit version 2.1.2-SNAPSHOT-153;6e26741

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
> [18:15:12] [Server thread/WARN]: Server reload detected. This may cause various issues with FastAsyncWorldEdit and dependent plugins. Reloading the server is not advised.

https://madelinemiller.dev/blog/problem-with-reload/#a-note-on-plugman

If you can replicate that without reloading the server, please provide the updated steps for it.
