### ISSUE TITLE
//schem list throwing java.nio.file.NoSuchFileException for players that are not OP

### ISSUE THREAD

**Issue by TomLewis** [IntellectualSites/FastAsyncWorldEdit#1714]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Players that have the permission `worldedit.schematic.list` throws the exception `java.nio.file.NoSuchFileException` for every single schematic in the root schematic directory if you have `per-player-schematics: true`, there must be no logic to decide if these schematics should be shown to this user (they should not).
I suggest an additional permission(s) be created for people to see these root directory "shared" schematics `worldedit.schematic.list.all` I also suggest adding folder based permissions `worldedit.schematic.list.foldername` then server owners can create folders for schematics that give permissions appropriately. 

A lot of us organize schematics in folders, folders can also be in folders.

### To Reproduce

1. Give user `worldedit.schematic.list`
2. Enable `per-player-schematics: true`
3. Have schematics in the root schematics folder
4. run `//schem list` from that user.

### Expected behaviour

To not list schematics outside of the users folder because `per-player-schematics: true` is set.

### Error log (if applicable)

https://gist.github.com/TomLewis/b234b62015ff411d4e55f92800496f85

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1c6be9b25b2a454dab0cf49566727905

### Fawe Version

FastAsyncWorldEdit version 2.1.3-SNAPSHOT-160;c94cbf2 

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Disable `per-player-schematics:` in the config.yml if you don't use it.

**Comment by TomLewis** [comment]
> Disable `per-player-schematics:` in the config.yml if you don't use it.

I do use it, that is why I created this bug report.
