### ISSUE TITLE
Add a //setbiome but for a specific gauge

### ISSUE THREAD

**Issue by Jqnnies** [IntellectualSites/FastAsyncWorldEdit#1716]
### What feature do you want to see added?

When I do //setbiome it always makes it cubular, mainly in the biome selection I make. I have a major problem with this because I generally just want to replace a certain biome with another.

Command could go something like *//setbiome {selectedbiome} {newbiome}*

### Are there any alternatives?

None

**Comment by dordsor21** [comment]
Mask: https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Main-Commands-and-Permissions#-biome
and
Pattern: https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Main-Commands-and-Permissions#biome-biome

**Comment by Jqnnies** [comment]
> Mask: https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Main-Commands-and-Permissions#-biome and Pattern: https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Main-Commands-and-Permissions#biome-biome
> 
> You can therefore use //replace ${biome} #biome[{biome}]

Oh tysm! I didnt know that!
