### ISSUE TITLE
//copy -b not properly copying biomes

### ISSUE THREAD

**Issue by Fa113n5tar** [IntellectualSites/FastAsyncWorldEdit#1717]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When trying to copy biomes from a selection, using the proper -b flag, the biomes seem to not be saved right. When you use //paste -b instead of the intended biomes, it pastes in different patterns of ocean and plains over the area instead. I've seen alternating straight lines of each, checkerboard patters, and something akin to houndstooth. This also occurs if you try and save the copy as a schematic and then paste it in that way.

### To Reproduce

1. Select an area that contains biomes
2. Use //copy -b to copy those biomes with the selection
3. Paste the selection somewhere using //paste -b
4. Biomes will be changed but not to the correct ones

------------------------------------------------------------

1. Select an area that contains biomes
2. Use //copy -b to copy those biomes with the selection
3. use /schem save to save the selection as a schematic
4. load the schematic that you just saved
5. Paste the schematic somewhere using //paste -b
6. Biomes will be changed but not to the correct ones

### Expected behaviour

Biomes in the copied area to be pasted as they were in the original area

### Screenshots / Videos

Used a snowy biome with snow as the texture pack I use makes snow look like sand in ocean biomes, so it's clearer.

https://gyazo.com/6ae4e91b63e022883adf33b0319096ac
https://gyazo.com/dd6953ae53baf7a423766aac172385d6
https://gyazo.com/39c51445142700a963dc26dfe6acd5c7

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0ba2d57075e542f4a6949ffaf97dd458

### Fawe Version

FastAsyncWorldEdit version 2.1.3-SNAPSHOT-163;3f970cd

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

screenshots and debug paste above are from build 163, but i updated to build 164 and tested again before submitting, still doesn't work as intended. debugpaste from build 164 is https://athion.net/ISPaster/paste/view/8e5f15d2bc13431b96f37c6805d76b31

**Comment by dordsor21** [comment]
May be addressed by #1743
