### ISSUE TITLE
signs with different block states not properly affected when using //replace or /mask

### ISSUE THREAD

**Issue by Aedesius** [IntellectualSites/FastAsyncWorldEdit#1724]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Using //replace oak_sign air on a selection of oak signs will only affect oak signs with no block state data (or rather with rotation=0,waterlogged=false or facing=north,waterlogged=false for wall signs, I don't know the technical details). This is true for all wood types as well as wall signs. 

Text has no effect. 

Adding the "minecraft:" prefix (minecraft:oak_sign) properly affects all block state types, which seems to be the intended behavior. Selecting a specific block state will work without the prefix ("//replace oak_sign[rotation=10] air" works)

### To Reproduce

1. Place a sign with any block state tag (waterlogged, rotation not equal to 0, or wall sign facing not equal to north) 
2. Use "//replace woodtype_sign x" or "/mask woodtype_sign" in an operation to select the signs as a source block
3. Only woodtype_sign[rotation=0,waterlogged=false] (or woodtype_wall_sign[facing=north,waterlogged=false] if using "woodtype_wall_sign") will be affected

### Expected behaviour

Using "//replace woodtype_sign x", "//replace woodtype_wall_sign x", "/mask woodtype_sign" or "/mask woodtype_wall_sign" should affect all different rotations, facings, or waterlogged of the selected sign type, without having to add a "minecraft:" prefix

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f5eb581d823e46d2abc1560751644468

### Fawe Version

Latest Release (2.1.2 build 159)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Covered by https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1626
