### ISSUE TITLE
Copy paste issue.

### ISSUE THREAD

**Issue by JamieNan** [IntellectualSites/FastAsyncWorldEdit#1740]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I get this error when copying something that contains blocks that have NBT data (chests, jukeboxes, furnaces etc.), rotating by 45 (or any non 90° angle) and then using //paste -a (pasting with air doesn't result in this error).

### To Reproduce

1.) Select an area that contains blocks containing NBT data e.g., a 2x2 square of furnaces.
2.) //copy
3.) //rotate 45 (or any non-90 degree angle)
4.) //paste -a

### Expected behaviour

Normally: expect the selection to paste properly.

### Screenshots / Videos

https://youtu.be/3T6ownp3tzU

### Error log (if applicable)

https://paste.gg/p/anonymous/6ecb09f52a9a4dea8d3f89cb9ebd7fc9

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e6815430155d41f39fbd08be2ba60ce1

### Fawe Version

Currently reverted back to 168, however as seen in the error log, the issue also occured on 174. (Reversion due to 174 giving a different issue)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

FAWE debugpaste conducted in V.168, however issue still present in V.174 (as seen in the Error log)

**Comment by NotMyFault** [comment]
I'm unable to replicate that on Paper 339 and Fawe 183, you should start updating your environments and using the platforms you actually ticked.
