### ISSUE TITLE
/fixwater Error

### ISSUE THREAD

**Issue by TallEnderman101** [IntellectualSites/FastAsyncWorldEdit#1747]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

/fixwater, /fixlava dont work it always comes with an error

### To Reproduce

Go to lava or water and where there is a empty spot do /fixwater 600 (i tried with 50 too and it was the same) and there should be an error

### Expected behaviour

should not be an error each time i do this

### Screenshots / Videos

https://drive.google.com/file/d/1glKeT4vCRybcmftsBrFGM1XcQu2-quW8/view?usp=sharing

### Error log (if applicable)

https://paste.gg/p/anonymous/dc07aba482424345b91d06fbf0eb44f0

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/407c4cf224f54260bcaff0dc18a154c8

### Fawe Version

FastAsyncWorldEdit 2.1.3-SNAPSHOT-178;2c1ffd4

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Don't see how this is a FAWE issue? CoreProtect is the cause of this

**Comment by TallEnderman101** [comment]
Then what can I do to fix this? And also how was I meant to know that it was CoreProtect
