### ISSUE TITLE
Attach release artifacts to GitHub releases

### ISSUE THREAD

**Issue by TwinkleToes777** [IntellectualSites/FastAsyncWorldEdit#1749]
### What feature do you want to see added?

I see that you are posting releases on GitHub which is very nice, but it would be nice if you upload plugin.jar together with the release post, for ease of downloading, because SpigotMC is often hard to access (very strict cloudflare blocking)

Alternatively, add easier link to development builds in GitHub.

### Are there any alternatives?

1. Downloading from SpigotMC (takes 5-10~ minutes to get through cloudflare)
2. Opening development builds directly, but it is not linked anywhere on GitHub, which makes it hard to find outside SpigotMC.

**Comment by NotMyFault** [comment]
The release API isn't very extensive, if you want to upload an artifact to a release, you need to specify its full path and name, which, with our current version pattern, requires some extra work, like extracting the version from the Gradle workflow and parsing it as version to a possible release workflow.

Overall, not a difficult but tedious task. I've reopened the issue, incase someone else wants to work on it.
