### ISSUE TITLE
FAWE Crash 1.13.2

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#175]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.144

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/s51kTVcn
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
When using paper 1.13 with async chunks enabled I believe that FAWE is causing the server to crash (maybe due to the way it's accessing chunks but I'm not too sure about this) I tried setting parallel threads to 1 and to 12 but it did not make any difference.

When using paper 1.13 with async chunks and FAWE parallel threads greater than 1 the server crashes with this:

Crash report: https://pastebin.com/D3id8n4Y
Crash log: https://pastebin.com/FvzmbjAh

When setting the threads to 1 it still crashes with:

https://pastebin.com/Ridpmhy1
https://pastebin.com/f7F3szG5

I've tried using AsyncWorldEdit for a day and never experienced this problem

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**How to replicate**:
Not quite sure, this happens on my server around every hour or two.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dextonanderson** [comment]
Can confirm, this is an issue for me as well and I think it is FAWE

**Comment by aurorasmiles** [comment]
If I remember correctly the issue with paralell threads was fixed ages ago, can this be closed?

**Comment by aurorasmiles** [comment]
Since I am pretty sure this was fixed I'm going to close this issue now, if not please comment
