### ISSUE TITLE
Chunk edge processing

### ISSUE THREAD

**Issue by TerraMiner** [IntellectualSites/FastAsyncWorldEdit#1753]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Problem with //gmask and block handling

### To Reproduce

Prepare the form with which you will work (//cyl 57 50 50)

1. Write //gmask ~[0]
2. Stand on center this disc and lets try //replacenear 100 57 #simplex[10][41,133,152]
3. After these steps, turn off your gmask (write //gmask), and run //replacenear 100 41,133,152 0

After, you can see this bug!
 

### Expected behaviour

When I use //gmask || //mask and start replacing some blocks, a strange thing happens, the edges of the chunk (Not all, but only part of these edges) are not subject to the filter //gmask || //mask, because of which, lines appear that interfere very much in work.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/29194071/168994703-95d11ec2-e486-446a-b1bf-6e6ba27d581e.png)
![image](https://user-images.githubusercontent.com/29194071/168995913-000f22d5-7cdc-4280-9fd1-4bba589e3204.png)
![image](https://user-images.githubusercontent.com/29194071/168995979-fa833ab2-2fee-438d-b6e8-e910e5bb8003.png)

### Error log (if applicable)

https://pastebin.com/KbP5xcPt

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8ae3f9de38244431bf0c10d663b0b9d4

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-166.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Nothing more. Please solve this problem and answer me.
You can contact me at this email address: sasha0koreckij@gmail.com

**Comment by dordsor21** [comment]
Possibly fixed by #1715

**Comment by dordsor21** [comment]
Please retry on the latest version

**Comment by dordsor21** [comment]
No response to the initial comment a month ago stating its possible fix and unable to replicate at all so closing
