### ISSUE TITLE
Some modifications on signs are not working

### ISSUE THREAD

**Issue by PapiCapi** [IntellectualSites/FastAsyncWorldEdit#1758]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

For example a replace of a sign does not work. It shows that 0 blocks have been replaced.

### To Reproduce

- Place a sign
- Define your positions so that they include the block
- Try to replace it with air ( for example )
- The sign is still here

### Expected behaviour

Setting air instead of doing nothing.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4c8dc7ffa0f04532a4a2df017527402c

### Fawe Version

FastAsyncWorldEdit version 2.2.1-SNAPSHOT-183;ace325a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Covered by https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1626
