### ISSUE TITLE
please, help

### ISSUE THREAD

**Issue by 1Pootis1** [IntellectualSites/FastAsyncWorldEdit#1762]
### Server Implementation

Paper

### Server Version

1.17.1

### 
I wrote to your discord, but they haven't answered me for several days ..
In general, I want to increase the limit of blocks that can be set with a hatchet, well, or the limit for other similar commands
![image](https://user-images.githubusercontent.com/73141732/170851262-e94e7318-a348-4b9a-967e-a56826e7c141.png)

I wrote in the configuration, gave the right "fawe.limit.default", but nothing works, the player writes "there are too many blocks in this territory" and that's it

What do I need to do to increase the limit for players?

**Comment by NotMyFault** [comment]
Read the comment, that is the wrong file, as we told you before.
