### ISSUE TITLE
Make Fawe jar smaller

### ISSUE THREAD

**Issue by josephjthomas** [IntellectualSites/FastAsyncWorldEdit#1767]
### What feature do you want to see added?

Can you make the jar size a bit smaller please? FAWE is packaging more than 14 (!!) megabytes of data which is a lot for a bukkit plugin.
Other plugins I use barely go beyond 2 megabytes of data, the majority is around 1 megabyte, yours sticks out.

### Are there any alternatives?

Use an older version with a lower jar size.

**Comment by NotMyFault** [comment]
Hey,

we're trying our best to keep the jar size as low as we can. Fawe bundles several core dependencies, like zstd jni, which ship necessary platform bindings on runtime, to assure different architectures.
