### ISSUE TITLE
Pasting between worlds causing issues with clipboard

### ISSUE THREAD

**Issue by Naigus** [IntellectualSites/FastAsyncWorldEdit#1771]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Attempting to paste a selection from another world causes the plugin to error and not paste.

### To Reproduce

Copy selection in one world, move to another world, attempt paste.

### Expected behaviour

Clipboard pastes.

### Error log (if applicable)

https://paste.gg/p/anonymous/9a2d8d45b10b4825ab4df062a82782cb

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/109949ed68a14802aafb5923176a64da

### Fawe Version

FastAsyncWorldEdit version 2.2.1-SNAPSHOT-186;32231b4

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Are you pasting between worlds with different min/max heights? I cannot replicate this

**Comment by Naigus** [comment]
I did not even think about that; yes! It's been happening between the Nether & Overworld type worlds (and vice-versa.)

So sorry about that it didn't even register as a thought.
