### ISSUE TITLE
ForwardExtentCopy places a structure 1 block off if the x and z coordinates are negative

### ISSUE THREAD

**Issue by dmdinnc** [IntellectualSites/FastAsyncWorldEdit#1777]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

We're using fawe to place a structure in the world, in this style using "new ForwardExtentCopy" found in the paste.gg below. The issue we're finding is that if we are trying to paste a structure at negative coordinates for the source location, it shifts the structure +1 xpos and +1 zpos (not sure about ypos)
https://paste.gg/p/anonymous/447ce15c6ced40e4862e4ebb9850a4cc

### To Reproduce

1. Use ForwardExtentCopy in the style used in the paste.gg link above
2. Point it towards negative coordinates, such as pasting at -1350 45 -1350
3. See it paste at -1349 45 -1349

### Expected behaviour

Pastes directly to the marked coordinates regardless of positive/negative

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e777c95f22e942299bb80f3778439f25

### Fawe Version

FastAsyncWorldEdit version 2.2.1-SNAPSHOT-184;d1f3ac8

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
When you say it pastes at -1349,-1349, are you accounting for the fact that the coordinates are negative...? -1349.5 is effectively the block at -1350.

**Comment by dordsor21** [comment]
No response for a week, there is nothing to suggest the above is not the case in code or any testing.
