### ISSUE TITLE
FAWE "corrupt tile entity"

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#178]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.144

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/s51kTVcn
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
Paper has a config option which removes corrupt tile entities, I've been getting these errors spammed ocasionally. It mentions FAWE in the logs so I'm assuming tile entities are in this state because of FAWE. I had this error in my console around 700 times but when I removed FAWE I only triggered this error once and it mentiond PlotSquared

Log while using FAWE: https://pastebin.com/UacUURNN
Log without using FAWE: https://pastebin.com/h4RSUkhn

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
This needs a separate issue on PlotSquared too.

**Comment by MattBDev** [comment]
This has been fixed by #416
