### ISSUE TITLE
Commands Fail To Execute

### ISSUE THREAD

**Issue by LimeDev8756** [IntellectualSites/FastAsyncWorldEdit#1785]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I can select but no commands even work

### To Reproduce

1. I think this is the hardware im using but first select something
2. do //set air
3. see it doesnt work

### Expected behaviour

It Sets to air

### Screenshots / Videos

https://user-images.githubusercontent.com/100384210/173187296-2dab7270-0bba-487d-82c6-fb7af3a2f54a.mp4

### Error log (if applicable)

https://gist.github.com/LimeDev8756/bfa2094805937b9de67fa6171a070d81

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/61fdae4dd9cb46d094114c3e0eeca03e

### Fawe Version

FastAsyncWorldEdit version 2.3.1-SNAPSHOT-196;c62f0c1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

No commands work at all
Not even the //sel command

**Comment by NotMyFault** [comment]
Update Paper, you are more than 100 updates behind.

**Comment by LimeDev8756** [comment]
ok thanks
