### ISSUE TITLE
//pos1/2 Throw An Error In A Command Block

### ISSUE THREAD

**Issue by LimeDev8756** [IntellectualSites/FastAsyncWorldEdit#1786]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Putting //pos1/2 throws and error and does not set the position

### To Reproduce

1. Place A Command Block
2. Put //pos1 0,0,0
3. The Output Says See Console

### Expected behaviour

It sets the position

### Error log (if applicable)

https://gist.github.com/LimeDev8756/6458f00e68ec6f3aa78bdbaa32034178

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2a4f4312dd2b48adb6f9121d19c56e02

### Fawe Version

FastAsyncWorldEdit version 2.3.1-SNAPSHOT-196;c62f0c1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

The command blocks were in the same chuck as the area need to select

**Comment by dordsor21** [comment]
Retry with command block support enabled in worldedit-config.yml

**Comment by LimeDev8756** [comment]
Same Outcome
