### ISSUE TITLE
Loaded class com.sk89q.worldguard.protection.association.RegionAssociable from WorldGuard v7.0.7+216b061 which is not a depend or softdepend of this plugin

### ISSUE THREAD

**Issue by SavageCore** [IntellectualSites/FastAsyncWorldEdit#1814]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

The following warning is displayed on server start:

`[16:20:00 WARN]: [FastAsyncWorldEdit] Loaded class com.sk89q.worldguard.protection.association.RegionAssociable from WorldGuard v7.0.7+216b061 which is not a depend or softdepend of this plugin.`

Incomplete existing issue #865

### To Reproduce

1. Download the plugins:
a. [Paper](https://api.papermc.io/v2/projects/paper/versions/1.19/builds/17/downloads/paper-1.19-17.jar)
b. [FAWE](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.3.1-SNAPSHOT-208.jar)
c. [WorldGuard](https://dev.curseforge.com/projects/worldguard/files/3677516/download)
2. Run server

### Expected behaviour

No warning is printed

### Error log (if applicable)

https://paste.gg/p/anonymous/0d3ae6730a794d488b44fc85e56aba3f

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/001f6c5153be4eb0b3ea5c3d0ca59581

### Fawe Version

FastAsyncWorldEdit version 2.3.1-SNAPSHOT-208;cb6e200

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
This can be ignored. There is no way to remove this message and it is not an issue.

**Comment by Firetop** [comment]
> This can be ignored. There is no way to remove this message and it is not an issue.

FYI. I fixed this in your plugin simply by adding WorldGuard to the plugin.yml softdepend list...
Going from: softdepend: [ Vault, WorldGuard ]
To: softdepend: [ Vault, WorldGuard ]

**Comment by Firetop** [comment]
Created merge request: #1895 to address this.

**Comment by Firetop** [comment]
Re-created: #1896 to address this.
