### ISSUE TITLE
Get rid of the sun.misc imports in ReflectionUtil (worldedit-core)

### ISSUE THREAD

**Issue by yannicklamprecht** [IntellectualSites/FastAsyncWorldEdit#183]
**Describe the solution you'd like**
I would like to get rid of the sun.misc imports. 

**Describe alternatives you've considered**
Using ByteBuddy and/or imports that are not removed in later versions of Java.

**Comment by SirYwell** [comment]
We‘re aware of the incompatibility. For now, other problems have a higher priority, but I‘ll try to find some time to take a look at it.

**Comment by MattBDev** [comment]
This is extremely low on the todo list.

**Comment by MattBDev** [comment]
I would like to note that progress has been made on this issue.

**Comment by NotMyFault** [comment]
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/396
Yet this is the older version, however, we've got reflections and other methods under 396.
