### ISSUE TITLE
No commands can be run

### ISSUE THREAD

**Issue by Zoleeee** [IntellectualSites/FastAsyncWorldEdit#1836]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

No commands work. When I type this command: // br blob #simplex [10] [5: 2,24] 50,50,50 100 100. Then write this to the chat: fawe invalid value for fill.

### To Reproduce

 // br blob #simplex [10] [5: 2,24] 50,50,50 100 100

### Expected behaviour

Put the blocks down

### Error log (if applicable)

https://gist.github.com/Zoleeee/821351d5cea63dce479727fe0c26b799

### Fawe Debugpaste

a

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.3.1-SNAPSHOT-213.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Paper.
