### ISSUE TITLE
Undo of schematics does not work

### ISSUE THREAD

**Issue by PapiCapi** [IntellectualSites/FastAsyncWorldEdit#1837]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When i try to undo a schematic paste using the API, nothing happens.

### To Reproduce

Here is the paste code : 
https://paste.gg/p/anonymous/a3815b453aed4355aded97cb6993d85a

Here is the undo code : 
https://paste.gg/p/anonymous/3ca034ceffc749c0b3f9f1cf9e1ad430

### Expected behaviour

Undo the paste

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7413bf1985ad4324b884bbb958ecdc85

### Fawe Version

FAWE 2.3.1-SNAPSHOT-225

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I think i don't use properly the methods but really can't find a way to make it work

**Comment by dordsor21** [comment]
Are you attempting to undo multiple schematics that were pasted at the same location/overlapping?

**Comment by PapiCapi** [comment]
Well, no. Here is a record of what's happening. With the delete command, the method UndoMultipleSchematic is called for only 1.
![image](https://user-images.githubusercontent.com/49530141/175058788-a516c6ef-b904-497f-b446-8ad848f97173.png)



https://youtu.be/U4UKz4I0DZM

**Comment by PapiCapi** [comment]
I'm sorry but i don't really understand how i am supposed to undo with my new EditSession.
I just set the BukkitRunnable to run async and it did not changed anything : my schematic is still here.
![image](https://user-images.githubusercontent.com/49530141/175064087-54367743-743d-4905-94c6-819cdcac8648.png)

For the iterator, yeah, you're right, i'll take a look at it when my undo method will work !

**Comment by MozenZ** [comment]
> Are you attempting to undo multiple schematics that were pasted at the same location/overlapping?

How to undo multiple schematics that were pasted at the same location/overlapping?
