### ISSUE TITLE
The latest 1.19 FAWE version affects the randomtickspeed

### ISSUE THREAD

**Issue by ZityGoneCrazy** [IntellectualSites/FastAsyncWorldEdit#1842]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

Hello, so.
FAWE affects our grass spread, crop growth and everything that can be affected by randomtickspeed.
The problem is definitely FAWE, when we removed the plugin, the grass suddenly spread, then we added the plugin again and the grass stopped growing again. Not even bonemeal works.
I guess thats all, there's not much to it.
ZityGoneCrazy#6579 if you need any more info

### To Reproduce

Add the latest FAWE version to your server
Set /gamerule randomtickspeed 10000
The grass or the crops wont grow.

### Expected behaviour

I expected for it to not affect any crops or grass etc...

### Screenshots / Videos

![Uploading 2022-06-26_11.30.34.png…]()
![Uploading 2022-06-26_11.28.29.png…]()

idk if the photos uploaded, it's been over 5 minutes and they're still uploading so,,, in case you want the photos, just contact me on my discord.

### Error log (if applicable)

Nothing

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/29bd310652784180bb35aa2000e78f3d

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.3.1-SNAPSHOT-234

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

help pls

**Comment by dordsor21** [comment]
I'm completely unable to replicate this, including with the tick-limiter enabled

**Comment by ZityGoneCrazy** [comment]
> 

No, i just replicated them rn, the same thing happened
I wrote out all the steps.
Still the same thing, when FAWE is on my server, crop doesnt grow and grass doesnt spread. Then i removed FAWE and it suddenly worked. I even tried some plugins that are created for crops etc... still didnt fix anything.
Sorry for the late reply.
