### ISSUE TITLE
Allowed filenames can be problematic with windows

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#1872]
### What feature do you want to see added?

Add a check if the filename is forbidden on windows, as it can be a problem when hosting on windows or letting users download those schematics. All forbidden filenames/characters on windows can be found here: https://stackoverflow.com/a/31976060

### Are there any alternatives?

no

**Comment by RedstoneFuture** [comment]
Unix and Linux usually use a case-sensitive file systems, but Windows does not. A backup of the schematics can therefore still lead to problems.
