### ISSUE TITLE
#blend

### ISSUE THREAD

**Issue by yjj71044** [IntellectualSites/FastAsyncWorldEdit#1882]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

//set #blend 2 is entered and executed.

### To Reproduce

1. Specify pos1 and pos2.
2. type command "//set #blend 2"

### Expected behaviour

The error log is output.

### Error log (if applicable)

https://paste.gg/p/anonymous/728e8b7381524a078bb557a093153fbe

### Fawe Debugpaste

 https://athion.net/ISPaster/paste/view/44daa565bd564102a211f02d4526cb97

### Fawe Version

 FastAsyncWorldEdit-247

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
That can be ignored, not every asset jar ships the same files depending on the game version you are using.
