### ISSUE TITLE
//chunk only selects from y=0 to y=255

### ISSUE THREAD

**Issue by OsmiiDev** [IntellectualSites/FastAsyncWorldEdit#1890]
### Server Implementation

Spigot

### Server Version

1.19.1

### Describe the bug

When using //chunk, the region selected only extends down to y=0 and up to y=255.

### To Reproduce

1. Run //chunk
2. Run //set 0

### Expected behaviour

//chunk selects the current chunk, from y=-64 to y=319

### Screenshots / Videos

![2022-08-01_12 58 34](https://user-images.githubusercontent.com/76014006/182212216-071c2332-08a4-45a9-9cbd-251453d9e1ff.png)

After running //chunk and //set 0

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a5096cb20dc54dbf978042e8e06955aa

### Fawe Version

FastAsyncWorldEdit 2.4.3

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
If you want to switch from chunk to block coordinates, stand in a chunk region lower than 0, above 255 or use the corresponding flags.
