### ISSUE TITLE
Add support for MultiPaper

### ISSUE THREAD

**Issue by MADS0LADEN** [IntellectualSites/FastAsyncWorldEdit#1891]
### What feature do you want to see added?

[https://github.com/MultiPaper/MultiLib](https://github.com/MultiPaper/MultiLib)

When using FAWE on one server the blocks doesn't appear on the other server - It works with WorldEdit

### Are there any alternatives?

WorldEdit works like it should.

**Comment by NotMyFault** [comment]
[-0](https://www.apache.org/foundation/voting.html#expressing-votes-1-0-1-and-fractions) from my side.

Supporting the industry standard server implementations keeps us busy enough, I don't see myself in maintaining yet another implementation.
