### ISSUE TITLE
//regen is bugged 

### ISSUE THREAD

**Issue by PapiCapi** [IntellectualSites/FastAsyncWorldEdit#1894]
### Server Implementation

Paper

### Server Version

1.19.1

### Describe the bug

Depending on the place of where you cut, the //regen command just sets all blocks to air.
I first tried on a world generated in 1.18. As i said, the command creates a hole. I then tried on a freshly generated world ( so in 1.19.1 ) , and it kind of create the same hole but with some things added ( see screenshot ) .

### To Reproduce

1) create a selection 
2) //regen

### Expected behaviour

Regenerate the terrain.

### Screenshots / Videos

Here is what happened on the 1.19.1 world : 
![regenOn1 19 1](https://user-images.githubusercontent.com/49530141/182586540-ffa5fbb7-e9b1-414b-9ef6-1ba61765a263.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2d86b1bd533749e4a6310a8fb9f4fa62

### Fawe Version

FastAsyncWorldEdit version 2.4.3-SNAPSHOT-254;e942175

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I tried to join the 1.18 world on github but the zip is too large so here it is using another website : https://gofile.io/d/TnBMDm

**Comment by NotMyFault** [comment]
I'm not able to replicate that.

**Comment by ComictypX** [comment]
For me this Bug happens after loading a 1.17 Map in 1.19.1.

**Comment by NotMyFault** [comment]
> For me this Bug happens after loading a 1.17 Map in 1.19.1.

Please zip the world up and provide it.

**Comment by ComictypX** [comment]
Running FAWE 254 on Paper 110 (Java 17 GraalVM EE)
https://drive.google.com/file/d/1_upBNlcH5fLxGqReASM6n0sgZ-7MmRO2/view?usp=sharing

**Comment by SirYwell** [comment]
FAWE can only regenerate whatever the *current* chunk generator provides. Old chunks cannot be regenerated.

**Comment by PapiCapi** [comment]
Here is a record of what happens. As you can see, i just created the world and my issue is still the same.

https://youtu.be/_8mdp8FeWCM


In this record here is my fawe debugpaste : https://athion.net/ISPaster/paste/view/486bef42586f4662baba134bc1696c79
I'm using FastAsyncWorldEdit version 2.4.4-SNAPSHOT-266;ab659ea and running Paper version git-Paper-132 (MC: 1.19.2)
