### ISSUE TITLE
FAWE not loading on 1.16.5 with java 16

### ISSUE THREAD

**Issue by MaxxQc** [IntellectualSites/FastAsyncWorldEdit#1903]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

I'm trying to load FAWE on 1.16.5 with java 16 because I can't use java 17 with 1.16.5 but it simply won't load.
Caused by: java.lang.UnsupportedClassVersionError: com/sk89q/worldedit/bukkit/WorldEditPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

### To Reproduce

1. Use java 16 and spigot
2. put fawe jar inside plugins folder
3. start server
4. /plugins show the plugin in red / not loaded

### Expected behaviour

the plugin should load in a way

### Fawe Debugpaste

cant run the command

### Fawe Version

2.4.4-SNAPSHOT-263

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Trichtern** [comment]
You have to use Java 17 in order for FAWE to work.

This should solve your problem
1. Install and boot the server with Java 17
(For help, see https://docs.papermc.io/
java-install-update)
2. Add
`-Paper. IgnoreJavaVersion=true` to
your JVM flags (before -jar)
