### ISSUE TITLE
frb rollback not working

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1910]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When using `//frb rollback -u Togusta -r 500 -t 5m` it asks for confirmation but when confirming the rollback nothing happens.
Here's a video of what's happening: https://gfycat.com/klutzypotabledungbeetle
In the video I also use the `/tool inspect` command to make sure that the edit has actually been logged.

### To Reproduce

1. Do a large worldedit operation
2. Do `//frb rollback -u [name] -r 500 -t 5m`

### Expected behaviour

It should undo the wordedit operation

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2d779fbcfa3c4f07b0bd8af13bd39027

### Fawe Version

2.4.4-SNAPSHOT-265;cc1b466

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Closing in favour of #2366 is gfycat is discontinued
