### ISSUE TITLE
Support tab completions in FAWE commands owned/overwritten by other plugins

### ISSUE THREAD

**Issue by mergu** [IntellectualSites/FastAsyncWorldEdit#1912]
### What feature do you want to see added?

hey folks, i am on the denizen team. we've had a number of reports of the FAWE `/ex` command overwriting tab completions for denizen's `/ex` command for a long time now. the same thing happened with WE's `/ex` command back in 2019, and I reached out and a fix was promptly made on their end. they were sending out tab completions even when they did not own the command. it seems FAWE is doing the same.

the tab completions for denizen's `/ex` command are almost essential for the plugin, it is quite disruptive for those to be unavailable. can we get a patch for this made on FAWE's end as well?

### Are there any alternatives?

what we are currently recommending is for people to use WE until this is patched if they really need tab completions

### Anything else?

a link to the WE patch: https://github.com/EngineHub/WorldEdit/commit/d81fd99340607f408324cd6baa1ce4daaff12127

a quick search over FAWE's codebase, this is likely the same culprit and a similar fix: https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java#L654

**Comment by Gemuseparty** [comment]
i can replicate, please fix

**Comment by NotMyFault** [comment]
If someone is interested in contributing to the issue, be our guest and create a PR.
