### ISSUE TITLE
Enforce max-blockstates for the //stack command

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1923]
### What feature do you want to see added?

Enforce the `max-blockstates` limit for the `//stack` command. The problem with allowing the stack command at the moment is that people can stack millions of block entities such as hoppers for example which will cause a lot of lag.

### Are there any alternatives?

The only alternative to this problem is to disable access to the //stack command

**Comment by dordsor21** [comment]
This seems to work fine for me, attempting to place more than 2 chests/hoppers with max-blockstates set to 2 fails.

**Comment by SecretlyJealous** [comment]
> This seems to work fine for me, attempting to place more than 2 chests/hoppers with max-blockstates set to 2 fails.

I updated to the latest build and it's working for me too, I'll close the issue
