### ISSUE TITLE
Running multiple FAWE commands from another plugin crashes FAWE/WE Entirely 

### ISSUE THREAD

**Issue by TomLewis** [IntellectualSites/FastAsyncWorldEdit#1927]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

This used to work in earlier versions, not sure when it broke, but I used it for a good 5+ years.

I have a script in CommandHelper that runs these commands to replace all "container" blocks
```
   run('//replace chest chest')
   run('//replace barrel barrel')
   run('//replace furnace furnace')
   run('//replace hopper hopper')
   run('//replace dropper dropper')
   run('//replace grindstone grindstone')
   run('//replace cartography_table cartography_table')
   run('//replace stonecutter stonecutter')
   run('//replace smithing_table smithing_table')
   run('//replace loom loom')
   run('//replace smoker smoker')
   run('//replace brewing_stand brewing_stand')
   run('//replace blast_furnace blast_furnace')
   run('//replace trapped_chest trapped_chest')
   run('//replace dispenser dispenser')
   run('//replace white_shulker_box white_shulker_box')
   run('//replace orange_shulker_box orange_shulker_box')
   run('//replace magenta_shulker_box magenta_shulker_box')
   run('//replace light_blue_shulker_box light_blue_shulker_box')
   run('//replace yellow_shulker_box yellow_shulker_box')
   run('//replace lime_shulker_box lime_shulker_box')
   run('//replace pink_shulker_box pink_shulker_box')
   run('//replace gray_shulker_box gray_shulker_box')
   run('//replace silver_shulker_box silver_shulker_box')
   run('//replace cyan_shulker_box cyan_shulker_box')
   run('//replace purple_shulker_box purple_shulker_box')
   run('//replace blue_shulker_box blue_shulker_box')
   run('//replace brown_shulker_box brown_shulker_box')
   run('//replace green_shulker_box green_shulker_box')
   run('//replace red_shulker_box red_shulker_box')
   run('//replace black_shulker_box black_shulker_box')
   run('//replace black_shulker_box black_shulker_box')
   run('//replace command_block bedrock')
   run('//replace repeating_command_block bedrock')
   run('//replace chain_command_block bedrock')
```

Ive also tried it using alias in CMI, same output.

It starts, and then it just breaks itself, and the only fix is to restart the server.

https://gist.github.com/TomLewis/2784f0647740757acd2ffae975c9d13b

### To Reproduce

1. Run multiple FAWE commands as a player using another plugin such as CMI or CommandHelper, for tedious tasks that require automation, such as replacing all containers when moving builds from creative so things are not hidden in containers. 
2. Fawe breaks.

### Expected behaviour

To just run the commands, this used to work perfectly fine when I was running 1.12, now im on 1.18 it no longer works.

### Error log (if applicable)

 https://gist.github.com/TomLewis/2784f0647740757acd2ffae975c9d13b

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8d257edeceea44fbba0472df57aa92df

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-273

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Looks like a CoreProtect issue to me.

**Comment by TomLewis** [comment]
Would it be worth disabling coreprotect worldedit logging to test to make sure?

**Comment by TomLewis** [comment]
So I disabled coreprotect worldedit logging, and the same thing happens now, just without console error.

It still breaks FAWE/WE entirely and does not complete itself.

This is a valid bug and should not be closed.

**Comment by TomLewis** [comment]
Bump
