### ISSUE TITLE
Error while using "/br paint sphere set grass_block, moss_block" command

### ISSUE THREAD

**Issue by FlexStudios** [IntellectualSites/FastAsyncWorldEdit#1930]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

While I used the following command:

/br paint sphere set grass_block, moss_block

I got an error in the console (Mentioned later)

### To Reproduce

1. Execute the command /br paint sphere set grass_block, moss_block
2. The problem happens

### Expected behaviour

The command had to be executed without any errors.

### Screenshots / Videos

![immagine_2022-09-02_221350366](https://user-images.githubusercontent.com/110140319/188229300-22b6d32a-84f5-4a48-a59a-2e69b0ba7c14.png)
![immagine_2022-09-02_221357521](https://user-images.githubusercontent.com/110140319/188229313-a58b112f-8849-4347-b347-419a812d5bb6.png)

### Error log (if applicable)

https://gist.github.com/FlexStudios/d3e562c10a9134c1ee5f6ca0ffbb5194

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/60839eeecadf46ec92e1d0cff62514d8

### Fawe Version

FastAsyncWorldEdit version 2.4.5-SNAPSHOT-273

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
> Server Version: git-Mirai-13 (MC: 1.19.2)

You ticked Paper, but you are using an unsupported derivate. I'm not able to replicate the issue on an up-to-date version of Paper.
