### ISSUE TITLE
History is not showing edits past a certain radius

### ISSUE THREAD

**Issue by bananasmoothii** [IntellectualSites/FastAsyncWorldEdit#1931]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I'm having a lot of troubles with the history tool from fawe, I can't find or rollback any edits. I recently found a weak point: having a radius too large makes it impossible to view history

### To Reproduce

https://user-images.githubusercontent.com/45853225/188287069-e568e861-3138-4a73-b861-abd39f188c3b.mp4

### Expected behaviour

Finding every edit in `//history`

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/788ef3ef81ab43f19d7262e7ebccbabb

### Fawe Version

2.1.3-SNAPSHOT-176;1c7643b

### Checklist

- [X] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Sorry, I could not use the latest version because my server is still in 1.18.2 but I am having this issue since a long time.
Here is also the history folder for that world:
[rp.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/9483380/rp.zip)

**Comment by NotMyFault** [comment]
![Screenshot 2022-09-28 at 10 50 13](https://user-images.githubusercontent.com/13383509/192734452-81db4d76-cc23-460a-b11d-eb030471bfd5.png)

I'm able to replicate the issue based on the steps provided. History entries are listed fine for me.

**Comment by dordsor21** [comment]
I've been able to replicate this exact behaviour with "too-large" radii
