### ISSUE TITLE
tool tree gives no feedback when used outside of a certain distance

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1934]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When using `/tool tree` and right clicking on a block 6 blocks away from where I am standing instead of creating trees or telling me that I'm not in the correct range it just gives no feedback in chat. To a normal user it makes them assume the tool is not working.

![2022-09-05_08 47 14](https://user-images.githubusercontent.com/10485646/188397035-25968102-e23b-4b74-bc97-cf205a5844d9.png)

### To Reproduce

1. Use `/tool tree`
2. Right click on a block 6 blocks away from where you are standing

### Expected behaviour

It should either give feedback saying that you are not in the required range or it should work regardless of the range

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/15afdd6954e04dbca81fb41cade11a73

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-275

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
The most a client is able to select is 5 blocks, which works fine for me. Anything higher without hitting the ground is not working, as expected. Trees don't float.
