### ISSUE TITLE
disallowed-blocks is bypassable with commands like //stack and others

### ISSUE THREAD

**Issue by iLemon** [IntellectualSites/FastAsyncWorldEdit#1935]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Players can bypass the disallowed-blocks list (in worldedit-config.yml) by running commands that don't specify the material in the command.

The ones I've found so far are:
- //stack
- //replace <material> #clipboard

### To Reproduce

1. Configure your worldedit-config.yml to include the following:
```
    disallowed-blocks:
    - "minecraft:spruce_sign"
```
2. Place a spruce_sign
3. Select with worldedit
4. Type //stack

### Expected behaviour

All worldedit operations should ignore any disallowed blocks.

I can imagine situations where a player is copying their house and it might be better to just paste without the disallowed blocks, instead of blocking it entirely.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d9c63b371d5848f09ac5438e8b5dd46d

### Fawe Version

FastAsyncWorldEdit 2.4.5-SNAPSHOT-273;8233f13

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
That's how this configuration option is intended to work. Take a look at the config's disallowed-blocks block working on a per-group basis via limits.

**Comment by iLemon** [comment]
@NotMyFault are you maybe referring to this?

```
    # If the disallowed blocks listed in worldedit-config.yml should be disallowed in all edits,
    # not just where blocks patterns are used.
    #  - Can prevent blocks being pasted from clipboards, etc.
    #  - If fast-placement is disabled, this may cause edits to be slower.
    universal-disallowed-blocks: true
```
If so, this does not work, and I can open a separate issue.
