### ISSUE TITLE
ForwardExtentCopy doesn't overwrite existing item frames at the destination

### ISSUE THREAD

**Issue by md5sha256** [IntellectualSites/FastAsyncWorldEdit#1941]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When using a `ForwardExtentCopy` to paste a schematic which contains only blocks, existing item frames are not removed at the destination. 

### To Reproduce

1. Create a schematic in a 2x2x2 area
2. Place an item frame anywhere within the target destination
3. Paste the schematic at the 2x2x2 area
The item frame should still be there. 

### Expected behaviour

The item frame should not be there. 

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/40da6ca507fe454ba5208c5f2051fca2

### Fawe Version

FastAsyncWorldEdit-v2.4.5-SNAPSHOT-273;8233f13

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Using FAWE-273 as 276 has an issue with the AsyncCatcher (see: https://discord.com/channels/268444645527126017/344128526435221505/1018058263813693480)

Debugpaste contains AreaShop which is the plugin I'm working on which performs the schematic pasting.

**Comment by PierreSchwang** [comment]
I'm not really sure if that's a bug or wanted. ItemFrames are not blocks but hanging entities - and entities may exist inside blocks (in that particular case the frame will pop of the block after a few seconds - at least native).
How does WorldEdit handle those cases?
