### ISSUE TITLE
Flip command giving error (ver 2.4.5 SNAPSHOT-376)

### ISSUE THREAD

**Issue by apexfinity** [IntellectualSites/FastAsyncWorldEdit#1942]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Whenever the flip command is run, it gives an error when run command //flip or //flip with any argument

### To Reproduce

1. Select pos1 and pos2 with wand
2. Run //flip
 (

### Expected behaviour

It is supposed to flip the item on the clipboard.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/52583315/189542619-482a1066-df9e-4486-85ba-f8f9331289c4.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1d19535598b6420f9864b0d0ac030692

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-276

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
The direction you are passing is not valid. Either use `me` or any of the tab-completed values
![grafik](https://user-images.githubusercontent.com/27054324/189770693-f1dc7cdf-48ce-4ae9-bb87-9745696a07c2.png)
