### ISSUE TITLE
//hsphere not working properly

### ISSUE THREAD

**Issue by Tekyo23** [IntellectualSites/FastAsyncWorldEdit#1943]
### Server Implementation

Spigot

### Server Version

1.18.2

### Describe the bug

First, clarify that I put "Spigot" but I'm using "Arclight".

So, I was trying FAWE in the server because, although WorldEdit is working, I wanted to test this one because it has more options.
And everything was going in the right way, but when I tried to create a empty glass sphere with a radius bigger than 50, it popped up an error with a message saying "Please report", so here I am.
I'm adding some images to help you.

PD: I tried it again but in a higher place and it worked. I'm guessing it has some incompatibilty when the sphere is being builded close to some blocks of the mod "Oh The Biomes You'll Go"

### To Reproduce

1. Install "FAWE" in the server
2. Install "Oh The Biomes You'll Go"
3. Create a glass sphere with a radius of 51
4. Try it close to the floor 
5. Try it far from the floor

### Expected behaviour

It's supposed to generate just some parts of the sphere. Generally they're from the centre and not from the "borders".

### Screenshots / Videos

In-game error > https://imgur.com/a/ATuPa7y
In-game error message >https://imgur.com/a/O49urLm
Console error > https://imgur.com/a/grWxmbM

### Error log (if applicable)

https://paste.gg/p/anonymous/82357204acae4a128312d4684e347424

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dc7ecf6d92d64cb4b20b6d1d40191fd7

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.5-SNAPSHOT-276

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Tekyo23** [comment]
Ok, I tried it in a plains biome and it still doesn't work properly when executing the command close to the floor.

**Comment by PierreSchwang** [comment]
FAWE does not support hybrid servers at all

**Comment by Tekyo23** [comment]
Oh! Thank you!
