### ISSUE TITLE
/br cmd

### ISSUE THREAD

**Issue by Ivain1** [IntellectualSites/FastAsyncWorldEdit#1952]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

In FAWE, there is a /br cmd (and its sibling, /br scmd, or scatter-command). The intent of this brush is to execute one or more commands at the brush location.
Once upon a time, this brush actually worked. The last time I can recall it working was back in 1.12. Unfortunately, since then the syntax appears to have changed to where it is no longer possible to actually execute any command. 
I have tried even single-word commands such as /br cmd 5 /fall, when binding the brush it gives no issue, but nothing actually happens.
variations I have tried:
[12:03:02 INFO]: Ivainir issued server command: /br cmd 5 fall
[12:03:05 INFO]: Ivainir issued server command: /br cmd 5 /fall
[12:04:41 INFO]: Ivainir issued server command: /br cmd 5 [/fall]
[12:04:45 INFO]: Ivainir issued server command: /br cmd 5 [fall]
[12:04:51 INFO]: Ivainir issued server command: /br cmd 5 [/fall;]
[12:05:27 INFO]: Ivainir issued server command: /br cmd 5 [fall;]

No result, no indication of an attempt at executing the command being made, not ingame or in the server logs.
It is theoretically possible that I'm still using the wrong syntax despite trying to stay as close to the instructions of the documentation as I could, but I doubt it.

The reason I'm reporting this now, after many years, is that I'm really starting to miss it. /br cmd was one of the most powerful tools in FAWE, easily on par with //g, /br clipboard and similar tools that save enormous amounts of time.
I would really love to see it return to functionality.

**Summary:** The /br cmd tool does not actually do anything, does not give any response to incorrect syntax beyond <radius> and <input> but input can be practically anything without error or feedback, This has been the case since 1.13 but likely has gone unnoticed due to very few people even using it in the first place (which is a major shame)

### To Reproduce

Start a paper or spigot server with FAWE installed, Minecraft version 1.13+ (Issue tested on a 1.19 server).
Open a world, a standard vanilla survival world will do.
Equip an item to serve as brush. type /br cmd <radius> <input> where radius is an integer and input is a FAWE command.
Example: /br cmd 5 /fall
Right-click to execute the brush on a tree or something else that has blocks above air (to see the effect of /fall).
Observe as nothing happens.

### Expected behaviour

From previous experience using FAWE for Minecraft 1.12, upon binding one or more commands to this brush, upon right click it should execute said commands at the location. I expect there to be a square selection with the given radius created, within which the command is executed as if the selection was created and the command was executed manually.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/efe197c4891b4262b193f0d7975bd84c

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.1-SNAPSHOT-241

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

NOTE: I am aware I'm not quite using the very most recent build, however this has been an issue since 1.13 and I never quite got around to making a proper report of it, so unless you deliberately fixed it in the last 2 months and I somehow missed this I doubt it's quite relevant.

**Comment by NotMyFault** [comment]
According to the code, the supported syntax would be something like `/br command 5 "br sphere 5 5"`

**Comment by Ivain1** [comment]
> 
Thank you for the information
Brushes work, but generative commands don't appear to? I can't do /br cmd 5 "cyl 5 5 5", for instance. Nor does something as simple as /br cmd 5 "fall" work. Is that part of the code? Because if so, it would be a rather disappointing change, since it effectively renders 75% of the potential uses obsolete. Even if only //g worked, that would already be a major increase.
Arceon brushes seem to work fine. Unfortunately, br scmd does not seem to do any scattering at all? It's just the exact same effect as /br cmd.
On another note, what is the system for multiple commands? I've already tried `br cmd 5 "br sphere 5 5" br cmd 5 "br sphere 5 5; cyl 5 5" br cmd 5 "br sphere 5 5, br cyl 5 5" br cmd 5 "br sphere 5 5","br cyl 5 5"`
