### ISSUE TITLE
1.16.5 java.lang.IllegalArgumentException: Unsupported class file major version 61

### ISSUE THREAD

**Issue by AkariDream** [IntellectualSites/FastAsyncWorldEdit#1957]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

i used jdk11 first. It prompts: Unsupported class file major version 61
after i configure jdk17 (-DPaper.IgnoreJavaVersion=true) 
it went from "unable to load plugin" to "Fatal error trying ... *.class"
then i try used jdk18. The problem still occurs
when it does not send error logs in the console. the debugging plugin prompts FAWE to handle an exception for (like PlayerMovementEvent, PlayerTeleportEvent) events [class com.sk89q.worldedit.bukkit.BukkitPlayer cannot be cast to class com.sk89q.worldedit.bukkit.BukkitPlayer (com.sk89q.worldedit.bukkit.BukkitPlayer is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1d716adc; com.sk89q.worldedit.bukkit.BukkitPlayer is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @46ca75ff)]

### To Reproduce

i am using Akarin-6be3d57(1.16.5 paper fork)
an error occurred after using jdk17
i just wanted to use it. If thats really Akarin problem. i will try to use Tuinity.
i know though that using this core will not be supported. but i still want to ask

### Expected behaviour

successfully running. console are no any errors or spam

### Fawe Debugpaste

Fatal error trying to convert FastAsyncWorldEdit v2.4.7-SNAPSHOT-281;10b852d:com/sk89q/worldedit/internal/util/ErrorReporting.class java.lang.IllegalArgumentException: Unsupported class file major version 61 :|

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.7-SNAPSHOT-281

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
FastAsyncWorldEdit requires Java 17 or above. From the spare information, I assume you installed both FAWE and WE, while you should only have one of them installed.

 Anything else is most likely unrelated (and we can't tell you more without logs from running the server with Java 17+).
Feel free to join [our Discord](https://discord.gg/intellectualsites) if you need further assistance.

**Comment by AkariDream** [comment]
i am now using jdk18. if u want to see spam. then I can consider uploading logs
WorldEdit was deleted when started server testing

**Comment by AkariDream** [comment]
it really is Akarin problem. no need to discuss it again :|
