### ISSUE TITLE
Upload FAWE to modrinth

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#1967]
[modrinth](https://modrinth.com/) has a great [API](https://docs.modrinth.com/docs/getting-started/) we could use with ease to upload FAWE releases to modrinth, too.

**Comment by PierreSchwang** [comment]
I'd say, this is blocked until Fabric Support is added? (#656 / @JayemCeekay)

**Comment by NotMyFault** [comment]
> I'd say, this is blocked until Fabric Support is added? (#656 / @JayemCeekay)

Modrinth allows plugins for a few weeks now, got already 200+ published ones.

**Comment by JayemCeekay** [comment]
> I'd say, this is blocked until Fabric Support is added? (#656 / @JayemCeekay)

I currently just need #1945 merged to finish my Forge update and create a PR for that one. I don't think any of what I'm doing would really conflict with uploading the spigot binaries to Modrinth. Also @NotMyFault is right, the Spigot and Forge/Fabric binaries will be separate.
