### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by costin33l** [IntellectualSites/FastAsyncWorldEdit#1984]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Im downloading a schem. from google and i cant import it on my server

### To Reproduce

downloading schem from google
paste it there https://hawks-romania.ro/faweplay/index.php
copy the command
paste in game
and the building should appear but it wont

### Expected behaviour

i expected the building to paste in my world

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/115091731/195948491-0f4ef5b1-ae66-4433-bcbf-f436eef2707e.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9e66bb0f56404b09813a612a765939ac

### Fawe Version

Build 200

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Schematics have to be gzipped according to the specification. If your file isn't gzipped, it's not a valid schematic.
