### ISSUE TITLE
Items are disappearing when dropped or broken

### ISSUE THREAD

**Issue by Abwasserrohr** [IntellectualSites/FastAsyncWorldEdit#1989]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Once a item is dropped, the item disappears into thin air near bigger farms from time to time. This happens either by dropping it from the inventory or by breaking blocks.

This is frustrating for survival players, since their stuff disappears randomly. Sometimes it also happens while farming somewhere else, but were only able to replicate it near bigger farms.

### To Reproduce

1. Setup a server with PaperMC and FAWE, I tried it also with just Paper Minecraft, but couldn't reproduce, just with FAWE + Paper.
2. Build a few bigger farms that have a huge output (see screenshot, random tick speed set to 50 for demo purposes, I have a demo world appended below)
3. Drop items near the bigger farms, sometimes they vanish. In the console `FAWE Tick Limiter` appears. Not sure if it's connected.

### Expected behaviour

The items drop like usual

### Screenshots / Videos

[video of items vanishing](https://user-images.githubusercontent.com/44294954/197268342-17c8c9b4-00d6-4c69-acd1-4b738c1f79c6.webm)

[Server World + Setup (without FAWE/Paper JAR)](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/9841774/ItemVanishServer.zip)

![2022-10-21_20 37 04](https://user-images.githubusercontent.com/44294954/197268519-fb63627d-07d6-4062-ae1e-09a81731e839.png)

[latest.log](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/9841759/latest.log)

### Error log (if applicable)

https://github.com/IntellectualSites/FastAsyncWorldEdit/files/9841759/latest.log

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/96a4d8d20ed94d1e97e71d483ab2b2d3

### Fawe Version

FastAsyncWorldEdit version 2.4.9-SNAPSHOT-293;4f74cc6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Thank you for all the work on FAWE, it's a great tool! ❤️

**Comment by PierreSchwang** [comment]
That's related to the TickLimiter, yes - see https://intellectualsites.github.io/fastasyncworldedit-documentation/configuration/configuration.html
Can be disabled by setting `tick-limiter.enabled` to `false`

**Comment by Abwasserrohr** [comment]
Oh wow, I didn't know this setting existed, thank you! 👍
