### ISSUE TITLE
Cannot use //confirm command in console

### ISSUE THREAD

**Issue by GodDirtman** [IntellectualSites/FastAsyncWorldEdit#1994]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When I do the FAWE operations from the console, and something needs confirmation, the `//confirm` command always returns `You have no actions pending confirmation.` error.

After this error occurred on my main server, I also tried running it on a local server with no other plugins - the same result.

### To Reproduce

1. Open your server's console
2. Select a large part of your world using `//pos1` and `//pos2` (or `//1` and `//2`)
3. Try to modify this selected area. For example: //replace lava water
4. FAWE will give you a confirmation request. Example: `Your selection is large ((0, 0, 0) -> (1000, 0, 1000), containing 101000 blocks). Use //confirm to execute /replace lava water`
5. Type `//confirm`  in the console.
6. You get the `You have no actions pending confirmation.` error.

### Expected behaviour

FAWE should execute the command and start the requested process.

### Error log (if applicable)

https://gist.github.com/GodDirtman/412100af5b6ce1317eca072f4171031c

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9e6211532cf846c4bd8abf623b408ceb

### Fawe Version

2.4.9-SNAPSHOT-296;0d112b2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
> Type //confirm in the console.

Use `/confirm` at console.

**Comment by GodDirtman** [comment]
Maybe typed this wrong here.

Doesn't work either.

**Comment by OneLiteFeather** [comment]
I can reproduce that with Fawe-408 and Paper-519 (1.19.4)
The //confirm (/confirm) command just don't work via console

**Comment by OneLiteFeather** [comment]
@TheMeinerLP looked at this further, looks like this command was never really supposed to be executed via console (players only) and the message you get via feedback is wrong at that spot. It's rather an upstream issue.

**Comment by TheMeinerLP** [comment]
Okay for your information. 
I know now why that happend currently i try to fix that.
On this error i found now another one with console interaction of fawe/worldedit.
