### ISSUE TITLE
Lighting glitches when removing blocks

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#1996]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Paper build: git-Paper-245
I don't know if this is because of the latest paper build but when removing an area with WorldEdit lighting glitches appear:

Example of `//set 0` on the ground:
![2022-10-29_11 41 38](https://user-images.githubusercontent.com/10485646/198827006-c7752d62-a06c-4344-807c-3b6fc2b93ae6.png)

![2022-10-29_11 45 30](https://user-images.githubusercontent.com/10485646/198827089-72ce9949-e99c-49fc-91e2-72e4dfb5d503.png)

### To Reproduce

1. Select a region on the ground
2. Use //set 0

### Expected behaviour

There should not be any lighting glitches

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/426550cb049a4b36b747bc9abb874a96

### Fawe Version

FastAsyncWorldEdit version 2.4.9-SNAPSHOT-296;0d112b2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Trichtern** [comment]
Can confirm.
However after downgrading to an older Paper version and using `//fixlighting`, all issues are fixed. Seems to be a Paper issue (?)

**Comment by NotMyFault** [comment]
This is caused by a recent Paper change, https://github.com/PaperMC/Paper/commit/519cb4b214d35333c703985ae11b94e70f569a27

Starting with build 236 onwards, Paper versions are affected.
