### ISSUE TITLE
"{0} biomes affected" is not / wrongly counted

### ISSUE THREAD

**Issue by tihe30** [IntellectualSites/FastAsyncWorldEdit#1999]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Copying biomes with copy -b (and paste -b) won't work on my server. It won't work anywhere in any world. I tried few blocks and a lot of blocks. Every time it says 0 biomes affected. It works perfectly for copying entities.

### To Reproduce

I tried using normal Worldedit and it works nicely.  I also tried fresh fresh paper server with only FAWE plugin and it still didn't work. I also tried few different plugin versions.

### Expected behaviour

Since copying biomes works normally with normal Worldedit it should work just fine with FAWE.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/fe00cd7769f142a4b4eb8b47ec6d1b7f

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.9-SNAPSHOT-297

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
The biome copying works without any issues (as seen in F3) - the amount-counting of affected biomes is just broken. I'm gonna rephrase the title of your bug report

**Comment by tihe30** [comment]
Oh, Great. It was confusing when count showed 0 so I didn't notice that copying biomes works.

**Comment by OneLiteFeather** [comment]
Can reproduce on 1.19.3 with Fawe version 381 (latest atm)
Do custom biomes work with this command as well?

**Comment by OneLiteFeather** [comment]
The count of banners doesn't show up as well
![grafik](https://user-images.githubusercontent.com/77929075/235785578-ad36baa8-99c1-4169-8a09-67ad24b00138.png)
I used //copy -e and //paste -e on this build with many banners
![grafik](https://user-images.githubusercontent.com/77929075/235785789-d7d6013c-9f62-47a6-a84a-d97b5f921100.png)

This could lead to confusion if the command works for these tile-entities. It works but doesn't show up.

**Comment by OneLiteFeather** [comment]
I suggest adding this as well - it relates to the same problem. There is a PR, but not sure if an extra issue would be necessairy. What can we do?
