### ISSUE TITLE
Re-add light commands

### ISSUE THREAD

**Issue by Wolfyxon** [IntellectualSites/FastAsyncWorldEdit#2005]
### What feature do you want to see added?

I'd like all light commands such as //setblocklight, //setskylight, //removelight, //fixlightning to be re-added. They were really useful to me and light blocks don't work the same.

### Are there any alternatives?

There are light blocks of course, but they can only add light, not remove it. That's why I really want the old light methods.

### Anything else?

You can also make a text warning that will say that light blocks are better to use when you run one of these commands.

**Comment by LXY010327** [comment]
I hope so too!

**Comment by NotMyFault** [comment]
Given there is no standard but light blocks across clients, versions and software vendors anymore, it's not feasible to reimplement lighting manipulation commands as on older versions.

**Comment by Wolfyxon** [comment]
Are there any alternatives? I really liked the thing that the light could be removed or decreased,

**Comment by SirYwell** [comment]
Not really, the server can decide to relight the chunk at any time. There is no way to make sure that data is really persisted.
