### ISSUE TITLE
Wall Buttons can't be replaced properly

### ISSUE THREAD

**Issue by Chrisi06** [IntellectualSites/FastAsyncWorldEdit#2009]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When typing in this command: //replace stone_button[face=wall,facing=west,powered=false] stone_button[face=wall,facing=west,powered=true] which means that only the buttons on walls that are facing west should be replaced, it replaces the buttons placed in all directions.

### To Reproduce

Normal World Edit can handle that command but FAWE somehow not and in the server console/log nothing unusual can be seen.

### Expected behaviour

Only the buttons that are placed in the certain direction should be replaced and no others.

### Screenshots / Videos

Here the problem can be seen when replacing those stone buttons with powered stone buttons (the command used for this is displayed already above):
(https://imgur.com/a/N4FTFGs)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e69fbe0aa7f14d4a846de6c524df654b

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.10-SNAPSHOT-304.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

It seems to be a bug and my team members are really getting annoyed by this because it's a distribution to their projects on the server. So please look into this as soon as possible.

Best regards
Chrisi

**Comment by dordsor21** [comment]
The issue seems to be that FAWE is ignoring all block data after the first
