### ISSUE TITLE
WG player left NOTIFY region whenever someone disconnects.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#2010]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Whenever someone disconnects, FAWE sends out a WG NOTIFY region message.

### To Reproduce

* Download Paper dev 265 (latest)
https://papermc.io/downloads
* Download WorldGuard dev 2207 (latest) & put in a plugin folder.
https://builds.enginehub.org/job/worldguard?branch=master
* Download FAWE dev 304 (latest) & put in a plugin folder.
http://ci.athion.net/job/FastAsyncWorldEdit/
* Launch Paper (double click). Closed.
* Open EULA file and set to true, relaunch Paper.
* Log in ``localhost`` on account 1. 
* Log in ``localhost`` on account 2.
* ``OP`` account 1 from console.
* Disconnect account 2.
* Message occurs to account 1.

Everything clean and fresh default generated. There are no regions called NOTIFY or any regions which make use of any notify flags.

### Expected behaviour

No FAWE/WG notification whenever someone disconnects. While I don't normally hand out OP in my main environment, I do make use of permission wildcards in LuckPerms for staffing groups which seems to trigger the same message occurring on disconnect of anyone.

### Screenshots / Videos

![link](https://cdn.discordapp.com/attachments/344128526435221505/1039240932924608654/image.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4ca619191fb84b13bb443cb126ab0e8a

### Fawe Version

FastAsyncWorldEdit version 2.4.10-SNAPSHOT-304;1aa213f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Maybe caused by this change upstream? https://github.com/EngineHub/WorldGuard/commit/bd1d772faa22d48f5d619b070908cb06600e45fd

> Introduces uninitialize for sessions that is called when the player disconnects or the server is shut down. Currently handlers don't get any notifications when the mentioned events occur and are unable to restore any player state they are holding to.
> 
> For example, this can be seen when entering to a region in survival with a game-mode creative flag, disconnecting and waiting for the session to timeout. When connecting back to the server and walking out of the region you can see that the player is not switched back to survival as they normally would be.

**Comment by download042** [comment]
Same issue at me. So irritating.

**Comment by PierreSchwang** [comment]
Are you able to replicate the issue using WorldGuard and "normal" WorldEdit? I can't seem to find any connection between FAWE and the named issue.
btw, the region does not have to be called NOTIFY, the NOTIFY is hardcoded https://github.com/EngineHub/WorldGuard/blob/master/worldguard-core/src/main/java/com/sk89q/worldguard/session/handler/NotifyExitFlag.java#L59

**Comment by download042** [comment]
I just downgraded my WG and now the problem is gone.

**Comment by PierreSchwang** [comment]
Based on https://github.com/EngineHub/WorldGuard/issues/1966 this behaviour seems to be wanted. No problem with FAWE here.

**Comment by JOO200** [comment]
Use the 7.0.x branch, not the master branch.
https://builds.enginehub.org/job/worldguard
