### ISSUE TITLE
Leaves not decaying from trees when logs are removed via any replacement command

### ISSUE THREAD

**Issue by Melliez** [IntellectualSites/FastAsyncWorldEdit#2011]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

I am attempting to remove a large forested area. I decided to replace all the logs in the selection with air (//rep ##logs air).
I would expect that once the logs disappear, the leaves would decay afterward since there is no adjacent log block to keep the leaves there. 
Instead, the tree leaves sit there, and I would have to break them manually.

### To Reproduce

1. Set the world randomTickSpeed to a large number for fast leaf decay. (I used 1500 in this example.)
2. Place two saplings beside each other to compare. One will be used for breaking the logs (like you are in survival mode), and another for the //set command to replace the logs on the tree with air blocks. The tree leaves must be separated from each other and not attached.
3. (Optional) Break the first tree's logs usually. When all the logs are gone, that tree's leaves will instantly disappear.
4. Select the tree (all logs are required, but the region doesn't matter), and do the command: //rep ##logs air
5. What should happen is that the logs will disappear, but the leaves will remain, not decaying.

### Expected behaviour

What I expected to happen was that the tree leaves would update and automatically decay, after issuing the command to replace the logs.

### Screenshots / Videos

Screenshots:
![2022-11-11_16 27 39](https://user-images.githubusercontent.com/118023333/201433837-a0b52bba-2036-47a3-8021-d30904b769ab.png)
![2022-11-11_16 27 45](https://user-images.githubusercontent.com/118023333/201433838-a13e8346-3196-4b74-a97e-f05a00258705.png)

Video (Google Drive shared file, 579MB):
https://drive.google.com/file/d/1AwS40ETEgyNNLNdBR9ZQ7wolTRNpPG1j/view?usp=sharing
(The file may not process on the drive, but I believe that it can be downloaded.)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/01c8d119c6094301ba58da0f9a7d868b

### Fawe Version

FastAsyncWorldEdit-2.4.10-SNAPSHOT-305

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

If I were to break the top four leaves on the tree (example in the attached video), the leaves would then update and disappear.

![tree_leaf_break](https://user-images.githubusercontent.com/118023333/201436152-8ab3b028-efd6-4404-88ff-f598225b5566.png)

**Comment by NotMyFault** [comment]
Leaves are intended to persist across operations. This is considered a helpful feature for mapmakers, who need to place leaves outside of trees.
