### ISSUE TITLE
[1.12.2] WorldGuard dont working with FAWE

### ISSUE THREAD

**Issue by NoxyYT** [IntellectualSites/FastAsyncWorldEdit#2014]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

My WorldEdit Dont wanna loading without original worldedit, another plugins too!

### To Reproduce

1.Deleted WorldEdit
2. Moved FAWE to /plugins folder
3. Starting Server

### Expected behaviour

i am just installed a fawe because it cool plugin, but it dont wanna loading for many plugins!

### Screenshots / Videos

And i have this problem too!
:
![javaw_N7cQI7zZQE](https://user-images.githubusercontent.com/107372460/201523944-0f8b09d5-02e8-4158-8785-ca4d82035224.png)

### Error log (if applicable)

Log `[15:16:46] [Server thread/ERROR]: Could not load 'plugins\worldguard-bukkit-6.2.2.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Location 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-79a30d7-f4830a1] 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-79a30d7-f4830a1] 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [server.jar:git-Spigot-79a30d7-f4830a1] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [server.jar:git-Spigot-79a30d7-f4830a1] 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [server.jar:git-Spigot-79a30d7-f4830a1] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1] 	at java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Location 	at com.sk89q.worldguard.protection.flags.DefaultFlag.<clinit>(DefaultFlag.java:134) ~[?:?] 	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.<init>(WorldGuardPlugin.java:136) ~[?:?] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] 	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?] 	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?] 	at java.lang.Class.newInstance(Class.java:645) ~[?:?] 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[server.jar:git-Spigot-79a30d7-f4830a1] 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-79a30d7-f4830a1] 	... 6 more Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Location 	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-79a30d7-f4830a1] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at com.sk89q.worldguard.protection.flags.DefaultFlag.<clinit>(DefaultFlag.java:134) ~[?:?] 	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.<init>(WorldGuardPlugin.java:136) ~[?:?] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] 	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?] 	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?] 	at java.lang.Class.newInstance(Class.java:645) ~[?:?] 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[server.jar:git-Spigot-79a30d7-f4830a1] 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-79a30d7-f4830a1] 	... 6 more `

### Fawe Debugpaste

https://intellectualsites.github.io/download/fawe.html

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.4.10-SNAPSHOT-307

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Unsupported version.

**Comment by NoxyYT** [comment]
it have 1.12 version, no?



![brave_ZOS8B0WfDs](https://user-images.githubusercontent.com/107372460/201525602-8aba2e98-c62a-4e81-a4e6-418904e425f1.png)

**Comment by SirYwell** [comment]
![a](https://user-images.githubusercontent.com/11150076/201526757-18fe6c15-fe7e-4f17-96d5-225924f552b1.png)

**Comment by NoxyYT** [comment]
oh thank u
