### ISSUE TITLE
Redstone Dust not Pasting using //paste after //copy

### ISSUE THREAD

**Issue by JoMaZu787** [IntellectualSites/FastAsyncWorldEdit#2024]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When I `//copy` a Structure with Redstone Dust in it and then `//paste` it somewhere else, all the Redstone dust is gone!

### To Reproduce

1. Place a solid Block
2. Put Redstone Dust on it
3. Left-Click the Block with your Selection wand (wooden axe)
4. Right-Click the Redstone Dust with your Selection wand
5. Run the Command `//copy`
6. Move a little bit to the side
7. Run the Command `//paste`

### Expected behaviour

The Block with the Redstone on it should be copied over with said Redstone placed on it.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ac77541eff8449b6949cc8e368b7ea94

### Fawe Version

FastAsyncWorldEdit version 2.4.9

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Server is Hosted on Aternos.org

**Comment by SirYwell** [comment]
Remove `minecraft:redstone_wire` from the disallowed-blocks list in your config
