### ISSUE TITLE
Weird EditSession#undo behaviour [1.14]

### ISSUE THREAD

**Issue by Blueyescat** [IntellectualSites/FastAsyncWorldEdit#203]
# Bug report for FastAsyncWorldEdit 1.14.3
**FastAsyncWorldEdit Version:** 
- **Date:** Jul 18, 2019 12:00:00 AM (no idea what the date is, the build is at 29 Jul)
- **Commit:** 93ccbf2
- **Build:** 16

**Server:** git-Paper-124 (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**Links to config.yml and config-legacy.yml file:** default, not changed

### Description of the problem:
undo(newEditSession) on a totally fresh EditSession undos a totally unrelated edit, it undos the last edit.

```
es1 = a new edit session
es2 = a new edit session
es3 = a new edit session

Schematic#paste(es1, v, true, false, true, null)

es1.changes = 7 (correct)
es2.changes = 0
es3.changes = 0

es2.undo(es3)
es3.flushQueue()

*undos changes of es1, totally unrelated*

es1.changes = 7 
es2.changes = 0
es3.changes = 1
```

**Used code to get a new edit session:**
```java
new EditSessionBuilder(w).autoQueue(true).checkMemory(false).limitUnlimited().build();
```
I have tried with different properties, i'm sure that i didn't use the same editsession objects, tried with my own paste method using operations, tried with a different edit like replacing blocks.

I think it is better if you do some tests, i wish you won't close the issue because this repo is for 1.13; it is not really possible to get fawe api help in Discord and there is 1.14 branch.

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.14) ([16](https://ci.athion.net/job/FastAsyncWorldEdit-1.14/16))
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Note to self: do not close. This is also a 1.13 problem.

**Comment by boy0001** [comment]
if you want to undo es1 us es1.undo(...)

**Comment by Blueyescat** [comment]
@boy0001 read the issue before closing it. If a totally unrelated edit session undos the last change, yes that is literally a bug. However, undoing es1 will do the same. Won't undo es1.

**Comment by MattBDev** [comment]
@dordsor21 Can you check this issue since you recently touched the undo functionality?

**Comment by dordsor21** [comment]
I feel like this is incorrect usage of the API. There isn't enough information here (history config, the actual code, etc) either.
