### ISSUE TITLE
Small Text Bug - Wrong UpdateNotification in console

### ISSUE THREAD

**Issue by BlockyTheDev** [IntellectualSites/FastAsyncWorldEdit#2030]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

I tried the FastAsyncWorldEdit version attached to the last Github-Release and one maked as Release from Jenkins and both times FAWE prints following line in my server console:
```
[17:29:00 WARN]: [com.fastasyncworldedit.core.util.UpdateNotification] You are using a snapshot or a custom version of FAWE. This is not an official build distributed via https://www.spigotmc.org/resources/13932/
```

### To Reproduce

1. Use a FAWE version from a release
2. Look into console

### Expected behaviour

No information about an SNAPSHOT or CUSTOM version, because it isn't one.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c75a209c226542c6bfbf7db4a4278722

### Fawe Version

FastAsyncWorldEdit version 2.4.10

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
I am unable to replicate this

**Comment by BlockyTheDev** [comment]
> I am unable to replicate this

I tried it again with the last version of FAWE in the Github Release, which is linked in the SpigotMC update message, and the problem persists on my side.
![image](https://user-images.githubusercontent.com/86119630/212375759-15f5bbf5-cb86-45d7-b310-12574e271433.png)

But i think I found out why it happens after letting the code print out all field values in the class `FaweVersion ` after following code is done: https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/bb0e201c52e23c85e9e7e262fb40906cea7cd28c/worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweVersion.java#L30
It ends in these values in with the details out of the file fawe.properties located in the release jar of 2.5.0
```
year: 22
month: 12
day: 11
hash: 224762365
build: 0
semver: [2, 5, 0]
snapshot: false
```
In the version of the bug report it ends in following values:
```
year: 22
month: 11
day: 15
hash: 24582660
build: 0
semver: [2, 4, 10]
snapshot: false
```

As seen here, both `build` fields end in the value `0` and here https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java#L38 there is a if statement, which checks this build field and because it is `0` it prints out the message.
