### ISSUE TITLE
Error when using the //snow command

### ISSUE THREAD

**Issue by Overwrite987** [IntellectualSites/FastAsyncWorldEdit#2031]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When I tried to use the //snow command to cover the spawn area with snow, I came across an error. The territory was covered with snow only in one small area (on the left by the Z coordinate, if you look to the east), and an error was displayed in the console.

### To Reproduce

1. randomly use the //snow command
2. see an error

### Expected behaviour

I expected that the entire area in the specified radius would be covered with snow, but only a part was covered

### Screenshots / Videos

![2022-12-01_21 33 46](https://user-images.githubusercontent.com/92237090/205133129-bb564578-3c94-4c11-a5a3-2efafb45ac0d.png)
![2022-12-01_21 33 49](https://user-images.githubusercontent.com/92237090/205133141-be0039ab-39bf-4574-aaa6-8b7bca6f8814.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/d2270eb74fc844a7bdbf611d9c0b5151

### Fawe Debugpaste

 https://athion.net/ISPaster/paste/view/f177b759e4e949a6836010edb4124c1e

### Fawe Version

FastAsyncWorldEdit version 2.4.10;1771a04

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
> Server Implementation
> Paper

Don't select 'Paper' if you are not using Paper. Please open a new issue if you can replicate the issue on a supported platform.

Thanks!
