### ISSUE TITLE
make commands none case sensitive

### ISSUE THREAD

**Issue by TaisenSchettler** [IntellectualSites/FastAsyncWorldEdit#2032]
### What feature do you want to see added?

In the past commands in Minecraft were not case-sensitive. 
It would be cool to have the option for commands still to work if you capitalize the first later. 

Problem:
if you type commands fast, you sometimes type the first letter in caps. It is resulting in the command not being executed. In the past this still worked.

### Are there any alternatives?

I guess our users could get better at typing.

**Comment by NotMyFault** [comment]
We're following the same logic as WorldEdit here. If you want to see a change in the command handler, I recommend initiating a discussing with the WorldEdit people.
Breaking the standard logic on our end is undesired.
