### ISSUE TITLE
[FAWE] Schematic MySQL Database

### ISSUE THREAD

**Issue by JamesBach93** [IntellectualSites/FastAsyncWorldEdit#2034]
### What feature do you want to see added?

An MySQL Database for Schematics.
So when you have an Network with more than two Servers with an Extra Build Server for Builders (Team)
you can Easly save it as Schematic and go to the other Server and load this instant. 

Because without it you need to go to the Files Copy Paste it to the other Server.

### Are there any alternatives?

I think no ?

### Anything else?

There is no more to say. =)

**Comment by NotMyFault** [comment]
Is there a particular reason why you want a MySQL database for this specific task? Storing blobs in single-table schemes is a nightmare to manage, if columns get bigger. A filestream column would make it less painful to manage, but there's no guarantee hosts out there provide one, and I don't think this is something we can safely put on people's shoulders.

I recommend looking into cloud based storage types, like S3 buckets, Backblaze B2, etc., which are not only cheap in terms of hosting, but also easy to integrate. You can share schematics with ease via NFS.
