### ISSUE TITLE
Error at the //regen command

### ISSUE THREAD

**Issue by dwdsty** [IntellectualSites/FastAsyncWorldEdit#2035]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

After selecting the territory I write in the chat //regen and I get an error

### To Reproduce

1. Taking a wooden axe in your hand
2. Allocate an area
3. write //regen

### Expected behaviour

The allocated area should be restored to its original appearance 

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/123b2279427f4484a6b6a931fe517177

### Fawe Version

FastAsyncWorldEdit-322 Authors: Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Given I'm not able to replicate that on 1.19.3, this looks like a specific issue on 1.16.5.

**Comment by Kamillaova** [comment]
> Given I'm not able to replicate that on 1.19.3, this looks like a specific issue on 1.16.5.

yes, this interface (or class?) is from 1.17
...in 1.16.5 impl

**Comment by TheMeinerLP** [comment]
Yeah is a specific error.
The class of BiomeProvider what we use. Is only available up to 1.17. Also fallback its not possible
<img width="591" alt="image" src="https://user-images.githubusercontent.com/6745190/230090973-eaa090fa-4268-4373-8896-69170c2498b7.png">
1.16.5 Docs https://helpch.at/docs/1.16.5/org/bukkit/World.html
1.17.1 Docs https://helpch.at/docs/1.17.1/org/bukkit/World.html#getBiomeProvider()

**Comment by OneLiteFeather** [comment]
This issue can be closed as it isn't possible to fix this problem in your minecraft version (1.16.5). Your issue is solved > 1.17 so you should update your server and FAWE and it should work.
