### ISSUE TITLE
Allow people use WE in __global__

### ISSUE THREAD

**Issue by lynrayy** [IntellectualSites/FastAsyncWorldEdit#2037]
### What feature do you want to see added?

I want allow people to use worldedit in `__global__` region (not claimed by anyone, and without OP). At the same time people shouldn't be allowed to use worldedit in someone's region.

It can be possible by permissions or parameter in config

### Are there any alternatives?

No alternatives found

### Anything else?

I waited 3 days in ds fawe support but nobody helped. Also i'm not found anything in docs

**Comment by NotMyFault** [comment]
There's no such functionality build in WorldGuard (as far as I am aware of), that allows control of WorldEdit access in specific regions.
There's WorldGuardExtraFlags (?) but no native we could build upon.
