### ISSUE TITLE
Error with //snow command with a radius greater than 80

### ISSUE THREAD

**Issue by Chevels** [IntellectualSites/FastAsyncWorldEdit#2038]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When using the snow command with a radius greater than 80 (personally I did //snow 160), only part of the area is covered with snow (the northern half) and FAWE reports an error and asks to report the console error.
I tried on the last version of FAWE and the penultimate one, same error.
I did tests with different radii, but as soon as you try 81 and beyond it gives this error.

### To Reproduce

Type //snow [with a radius greater than 80]

### Expected behaviour

I want to snow cover an area with a radius of 160 blocks as I have been doing every winter for many years to cover my spawn city with snow. Before I used Worldedit, this is my first winter with FAWE.

### Error log (if applicable)

https://paste.gg/p/anonymous/57a87ca9447d447a91793b08b6d4cb10

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ba4373c3c65a4d4daaadca34f1cdc2a4

### Fawe Version

FastAsyncWorldEdit version 2.4.10

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
I am unable to replicate this issue

**Comment by dordsor21** [comment]
Still cannot replicate, assume not an issue
