### ISSUE TITLE
AsyncWorld feature

### ISSUE THREAD

**Issue by huanmeng-qwq** [IntellectualSites/FastAsyncWorldEdit#2056]
### What feature do you want to see added?

create world in async thread

### Are there any alternatives?

I used com.boydti.fawe.bukkit.wrapper.AsyncWorld in mcversion 1.8 to complete this requirement, but I couldn't find any clues about it in mcversion 1.19

**Comment by SirYwell** [comment]
Such a feature should be provided by the server software itself. Otherwise, it's our burden to maintain it (which is why the functionality was removed).
