### ISSUE TITLE
Invalid Spawners "SpawnData"

### ISSUE THREAD

**Issue by LcyDev** [IntellectualSites/FastAsyncWorldEdit#2067]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

I don't know why are these invalid spawners all over my world but my only option is to remove them with replacenear

Altough, doing this freezes the server a bit and generates these dumps

https://paste.gg/p/ConaII_/ada32c5e087a4591b4e112e3e41cf8d2

### To Reproduce

N/A

### Expected behaviour

N/A

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e34b2ecc6e024c208ace28b84c3ca3e0

### Fawe Version

FastAsyncWorldEdit version 2.5.1-SNAPSHOT-339;bb0e201

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by LcyDev** [comment]
Ugh i should just make a plugin..

**Comment by NotMyFault** [comment]
FAWE is not the right tool to remove invalid blocks from your world.

**Comment by LcyDev** [comment]
What tool can i use :(
The map weights like 60 GB at least
It's from https://earth.motfe.net/

**Comment by dordsor21** [comment]
https://www.amuletmc.com/ or similar out-of-game world editors
