### ISSUE TITLE
//regen

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [IntellectualSites/FastAsyncWorldEdit#2077]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Hello, I've been trying to figure out how to limit the //regen command for a while now.
I would like to give a maximum regeneration option for 10 million blocks.
In the configuration I have it set and I have set the permissions and unfortunately still here to regenerate an unlimited area.
Thank you

Permissions:
fawe.admin false
fawe.bypass true
fawe.limit.default true (I also tried false)
fawe.limit.* true (I also tried false)

Translated with www.DeepL.com/Translator (free version)

### To Reproduce

//regen

limits:
  default:
    # Max actions that can be run concurrently (i.e. commands)
    max-actions: 1
    # Max number of block changes (e.g. by `//set stone`).
    max-changes: 10000000
    # Max number of blocks checked (e.g. `//count stone` which doesn't change blocks)
    max-checks: 10000000
    # Number of times a change can fail (e.g. if the player can't access that region)
    max-fails: 10000000
    # Allowed brush iterations (e.g. `//brush smooth`)
    max-iterations: 1000
    # Max allowed entities (e.g. cows)
    max-entities: 1337
    # Blockstates include Banner, Beacon, BrewingStand, Chest, CommandBlock, 
    # CreatureSpawner, Dispenser, Dropper, EndGateway, Furnace, Hopper, Jukebox, 
    # NoteBlock, Sign, Skull, Structure
    max-blockstates: 1337
    # Maximum size of the player's history in Megabytes:
    #  - History on disk or memory will be deleted
    max-history-mb: -1
    # Maximum time in milliseconds //calc can execute
    max-expression-ms: 50
    # Cinematic block placement:
    #  - Adds a delay to block placement (nanoseconds/block)
    #  - Having an artificial delay will use more CPU/Memory
    speed-reduction: 0
    # Place chunks instead of individual blocks:
    #  - Disabling this will negatively impact performance
    #  - Only disable this for compatibility or cinematic placement
    fast-placement: true
    # Should WorldEdit use inventory?
    # 0 = No inventory usage (creative)
    # 1 = Inventory for removing and placing (freebuild)
    # 2 = Inventory for placing (survival)
    inventory-mode: 0
    # Should large edits require confirmation (>16384 chunks)
    confirm-large: true
    # If undo and redo commands should be restricted to allowed regions
    #  - Prevents scenarios where players can delete/reset a region, and then continue to undo/redo on it
    restrict-history-to-regions: true
    # List of nbt tags to strip from blocks, e.g. Items
    strip-nbt: []
    # If the disallowed blocks listed in worldedit-config.yml should be disallowed in all edits,
    # not just where blocks patterns are used.
    #  - Can prevent blocks being pasted from clipboards, etc.
    #  - If fast-placement is disabled, this may cause edits to be slower.
    universal-disallowed-blocks: true
    # List of blocks to deny use of. Can be either an entire block type or a block with a specific property value.
    # Where block properties are specified, any blockstate with the property will be disallowed (e.g. all directions
    # of a waterlogged fence). For blocking/remapping of all occurrences of a property like waterlogged, see
    # remap-properties below.
    # Example block property blocking:
    #  - "minecraft:conduit[waterlogged=true]"
    #  - "minecraft:piston[extended=false,facing=west]"
    #  - "minecraft:wheat[age=7]"
    disallowed-blocks: 
    - "minecraft:wheat"
    - "minecraft:fire"
    - "minecraft:redstone_wire"
    # List of block properties that should be remapped if used in an edit. Entries should take the form
    # "property_name[value1_old:value1_new,value2_old:value2_new]". For example:
    #  - "waterlogged[true:false]"
    #  - "age[7:4,6:4,5:4]"
    #  - "extended[true:false]"
    remap-properties: []

### Expected behaviour

Everyone can regenerate an unlimited area

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/68572049/214178223-86474338-d7da-4974-892c-78155f5983e4.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ef55e29a8d66449aa2adb62379d7ae52

### Fawe Version

FastAsyncWorldEdit-344

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
![grafik](https://user-images.githubusercontent.com/77929075/232869842-8467f809-2813-4766-a7bf-3877ba3af5d0.png)
This is the documentation from worldedit about //limit
https://worldedit.enginehub.org/en/latest/commands/#utility-commands
The important thing to note is: if you have an bypass permission, it is possible to still have more than the limit you set. It is useful for people who likewise "overdo" their selection size and don't have the limit bypass permission. If you set both permissions for default max size and bypass, it bypasses the block limit as well.

For the future, it would be better to check out the documentation for worldedit and [fastasyncworldedit](https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Main-Commands-and-Permissions)

Note: the fawe documentation lacks the permission fawe.limit.*, I will open an issue for that.

If you need help with commands, ask the community on the IntellectualSites Discord as well.
