### ISSUE TITLE
//image does not work on merge branch, build 146+

### ISSUE THREAD

**Issue by Hexical1** [IntellectualSites/FastAsyncWorldEdit#208]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
https://i.imgur.com/TCgYcW2.png

**[REQUIRED] Spigot/Paper Version Number:** 
Paper(642) 1.13.2-R0.1-SNAPSHOT

**Links to config.yml and config-legacy.yml file:** 
[Config.yml](https://pastebin.com/LrB6EJZU)
[ConfigLegacy.yml](https://pastebin.com/HC6gUXVB)
[DebugPaste](https://athion.net/ISPaster/paste/view/911def4eaebe4fd0bf3ea59fd5737131)

**[REQUIRED] Description of the problem:**
//image spits out an error whenever used, even with the latest 1.13 jar being put in the /textures folder. 

[Error on player Screen](https://i.imgur.com/8Uasp2r.png)
[Error in Console](https://pastebin.com/1p4mxHi6)

**Plugins being used on the server:**
[Plugins](https://i.imgur.com/ygH7wAT.png)

**How to replicate**:
Step 1.) Find an image
Step 2.) run the //image command with it
Step 3.) Encounter Error

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
//image does does not work merge, typing `//image` will get you http://haste.athion.net/pacularate.bash

**Comment by TheoRetisch1** [comment]
Confirmed for Paper 1.13.3 build #198 + FAWE 369, the _image_ or _br image_ command just outputs the help menu.

**Comment by PhilippUlti** [comment]
Currently not working in build #423 (and upwards) because you cannot use a link as an argument http://prntscr.com/vcfy5v

**Comment by TheoRetisch1** [comment]
That's awesome thank you dordsor 💯
