### ISSUE TITLE
It doesn't show me lava when I'm doing set block via API

### ISSUE THREAD

**Issue by robalmeister** [IntellectualSites/FastAsyncWorldEdit#2084]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

My code:
`
RandomPattern pat = new RandomPattern();
            CuboidRegion region = new CuboidRegion(BlockVector3.at(-50, arena.getLavaLevel(), 50), BlockVector3.at(50, arena.getLavaLevel(), -50));
            EditSession editSession = WorldEdit.getInstance().newEditSession(new BukkitWorld(arena.getWorld()));
            pat.add(BukkitAdapter.adapt(Material.LAVA.createBlockData()), 100.0);
            editSession.setBlocks((Set<BlockVector3>) region, pat);
`
Lava is invisible but deals damage

### To Reproduce

.

### Expected behaviour

.

### Fawe Debugpaste

not required

### Fawe Version

latest

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
I recommend you to read about the concepts you're using, especially about EditSessions (https://worldedit.enginehub.org/en/latest/api/concepts/edit-sessions/). If you need further assistance, feel free to join our discord.
