### ISSUE TITLE
Can not rotate 

### ISSUE THREAD

**Issue by YesItsLeon** [IntellectualSites/FastAsyncWorldEdit#2085]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

When I use the command //rotate 0 10 5 on the ship, some pieces of the ship are missing: 

### To Reproduce

1. Copy the building
2. Rotate it
3. Wait until its pasted in the world (long time)
4. The building is broken.

### Expected behaviour

See above

### Screenshots / Videos

http://yesitsleon.de/MD26

### Error log (if applicable)

https://pastebin.com/d8RbXPWc

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f88da6e58a4640e7991ddc3a6831fc64

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-348.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
I can't seem to reproduce that issue with the steps provided. Can you try reproducing that on a fresh Paper-Server using just FAWE (eg. locally)?
If the issue persists, would you be able sharing that schematic or a simpler schematic which produces that error? You are free to send it to Sheriff on Discord in case the schematic has to stay private

**Comment by dordsor21** [comment]
This is specific to clipboards containing tiles
