### ISSUE TITLE
redstone does not copy

### ISSUE THREAD

**Issue by SirvydasS** [IntellectualSites/FastAsyncWorldEdit#2088]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

When copying the block with Redstone and pasting, Redstone doesn't appear.

### To Reproduce

1. Build redstone
2. Select redstone with wand
3. Write //copy
4. Fly away a little
5. Write //paste

### Expected behaviour

Redstone appeasrs when copying

### Screenshots / Videos

https://youtu.be/wHSf8jRd02A

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/161e98a960d046c2810bbe5741e96d28

### Fawe Version

FastAsyncWorldEdit version 2.5.3-SNAPSHOT-355;1e5b2fe

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
remove `- "minecraft:redstone_wire"` from your disallowed blocks section in the FAWE config
