### ISSUE TITLE
passenger entity disappears after copy paste operation

### ISSUE THREAD

**Issue by LedariaTim1** [IntellectualSites/FastAsyncWorldEdit#2091]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Initial situation: freshly installed Paper 1.19.3 server with the latest FAWE version without any other plugins
when copying a area containing entities which ride entities (as an example a pig with a cow as a passenger) with the command //copy -e and subsequent pasting with //paste -e the upper entity is lost. 

And in the console an error is printed.

### To Reproduce

create a clean paper 1.19.3 server (Build 392) and latest FAWE (2.5.3-SNAPSHOT-356)
build a flat area
summon an entity with a passenger
/summon cow ~ ~ ~ {NoGravity:1b,Invulnerable:1b,NoAI:1b,Passengers:[{id:"minecraft:pig",NoGravity:1b,Invulnerable:1b,NoAI:1b}]}
select and copy the area with //copy -e
paste it to a free area with //paste -e

### Expected behaviour

I would have expected that at the inserted place also the entity with the passenger would be inserted again

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/76794156/218200267-dbba4a13-2b14-4c94-9851-182910267e15.png)
![grafik](https://user-images.githubusercontent.com/76794156/218201081-03311ba2-806e-4c69-9a07-ea7e7faf2c74.png)

![grafik](https://user-images.githubusercontent.com/76794156/218201649-05722bc9-515c-4c2f-a640-950e864941c0.png)
![grafik](https://user-images.githubusercontent.com/76794156/218203852-51c60a0f-ea6c-42ab-a8d3-267e493f609b.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/599fb09dea2a4dc08e8ab2fa43c3495f/files/0ac8074ba8444f91ba177e80e1bc3e43/raw

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ee3dd95dc60d41b3847fc84972cd1c46

### Fawe Version

FastAsyncWorldEdit version 2.5.3-SNAPSHOT-356;783dc35

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by yannicksuc** [comment]
I have the same problem. Thanks for the report

**Comment by OneLiteFeather** [comment]
`BinaryTagType[CompoundBinaryTag 10]{tags={"UUIDMost"=BinaryTagType[LongBinaryTag 4 (numeric)]{value=-3682752965797655454}, "Pos"=BinaryTagType[ListBinaryTag 9]{tags=[BinaryTagType[DoubleBinaryTag 6 (numeric)]{value=176.2415854339166d}, BinaryTagType[DoubleBinaryTag 6 (numeric)]{value=64.18999998211861d}, BinaryTagType[DoubleBinaryTag 6 (numeric)]{value=-673.061920999834d}], type=BinaryTagType[DoubleBinaryTag 6 (numeric)]}, "UUIDLeast"=BinaryTagType[LongBinaryTag 4 (numeric)]{value=-5245839892364430806}, "WorldUUIDMost"=BinaryTagType[LongBinaryTag 4 (numeric)]{value=-3682752965797655454}, "PersistentIDLSB"=BinaryTagType[LongBinaryTag 4 (numeric)]{value=-5245839892364430806}, "PersistentIDMSB"=BinaryTagType[LongBinaryTag 4 (numeric)]{value=-3682752965797655454}, "Id"=BinaryTagType[StringBinaryTag 8]{value="minecraft:pig"}, "UUID"=BinaryTagType[IntArrayBinaryTag 11]{value=[-857457744, -1910682526, -1221392279, 1527476778]}, "WorldUUIDLeast"=BinaryTagType[LongBinaryTag 4 (numeric)]{value=-5245839892364430806}}}`
It's even the same information on console.

**Comment by LedariaTim1** [comment]
issue still exists in Minecraft 1.21 with FAWE 2.11.1-SNAPSHOT-858
