### ISSUE TITLE
FAWE performance regression

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#210]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.178

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/s51kTVcn
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
FastAsyncWorldEdit is much more ineffecient in 1.13.2 compared to 1.12.2 to the point where I've bumped down the max block changes from 500k to 100k. Here's a timings sample: https://timings.aikar.co/?id=45e61c24341a462883c8ddc40667090a
Screenshot in case the timings expires.:
![Untitled](https://user-images.githubusercontent.com/10485646/63038368-ec589900-beb8-11e9-983d-5cbe707afcd8.png)

Another sample: https://timings.aikar.co/?id=7c8516efd13c41d48405ac0ade1b3141

In this sample there's also issues with "WorldEdit::Event: c.b.f.b.FaweBukkit (PlayerQuitEvent) https://timings.aikar.co/?id=8f1b13de0c1044f6a07d0498d0a9c8c6":
![QuitEvent](https://user-images.githubusercontent.com/10485646/63067218-c4dbed80-bf05-11e9-9bae-0989f0ce1e93.png)

It was very rare to ever see FAWE in timings during 1.12.2 even when I was trying to do something intense on purpose to make it show up: https://timings.aikar.co/?id=517efdac42604732bebd40552c0b195b

**Plugins being used on the server:**
FastAsyncWorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
This is already a known issue

**Comment by MattBDev** [comment]
Title changes to reflect the fact that FAWE performance regressed on all versions newer than Minecraft 1.12.2

**Comment by dordsor21** [comment]
This is now pretty outdated and no longer an issue I believe.

**Comment by Misio12320** [comment]
still occur in 1.16.4
FastAsyncWorldEdit::Event: c.b.f.b.FaweBukkit (PlayerQuitEvent)
count(1)  total(0.01% 0.032s, 0.01% of tick)avg(32.31ms per - 0.00ms/0.00 per tick)
https://timings.aikar.co/?id=8fdee16f47ed4ce4a5060b7ca0e1ff58
@dordsor21

**Comment by SirYwell** [comment]
Better profilings (e.g. using spark profiler) would be useful.
