### ISSUE TITLE
The //undo does not remove a certain part of the //paste

### ISSUE THREAD

**Issue by Flamiz** [IntellectualSites/FastAsyncWorldEdit#2104]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

We use FAWE 
We have a problem when we paste a schematics and when we do //undo it removes a big part of the build

### To Reproduce

//schematic loadall test.schem
//paste
//undo
//paste
//undo

### Expected behaviour

A part of the build has not been removed

### Screenshots / Videos

![2023-02-19_22 57 28](https://user-images.githubusercontent.com/12258905/219977578-c6686aa9-b3a7-4082-b472-6944b2966bc9.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2945cc9902af4876925f3df1c088a8bc

### Fawe Version

FastAsyncWorldEdit version 2.5.2-SNAPSHOT-346;214954b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by craftyfoxe** [comment]
We've had the same issue for a while, I found a way to do it consistently with this schematic: 
https://schem.intellectualsites.com/fawe/?key=3607c8e9-6d0e-4c51-99fa-f270d7c3dd41&type=schem

just paste it and undo it several times. I've even tried pasting and waiting after its done, with similar effect.

I've got it on video:
https://www.youtube.com/watch?v=EErzPpE8tnE

There's no errors in the console. I had a theory maybe it's like pasted, it's not fully loaded into the game file, only appearing to be complete from client side. But I do have the max actions that can be run concurrently at 1. Please fix this bug, we had it for too long

https://cdn.discordapp.com/attachments/344128526435221505/1077305667586642030/2023-02-20_14.07.47.png

FAWE debugpaste: https://athion.net/ISPaster/paste/view/e88cabd75e094e02befdff8406d3e521

**Comment by Zeranny** [comment]
Some additional context on the above comment & schematic:

If pasted without anvils (//paste -m !anvil), then //undo works just fine.

https://user-images.githubusercontent.com/1365964/220206833-8c34adfa-fcfc-45f2-9505-34ffbd60b3d9.mp4

**Comment by craftyfoxe** [comment]
Made a new schematic file link since old is deleted: https://cdn.discordapp.com/attachments/268444645527126017/1079078343699333200/fox1.schem

Just tested it again, it fails after the 2nd undo.

**Comment by PierreSchwang** [comment]
Okay - So, I can kind of reproduce it. When waiting until the paste is fully done, the undo works flawlessly. Otherwise, if I undo before everything was pasted / sent fully the named error happens

**Comment by craftyfoxe** [comment]
Waiting until the paste is fully done does not remedy the situation.
I made a video showing it still messes up even after waiting 1 min after it's fully pasted
https://www.youtube.com/watch?v=Lu7qlLh8MBw

If you do what Zeranny suggested (//paste -m !anvil), fox1 does paste flawlessly without anvils even if you do it quick, but if you paste a bigger schematic fox2 w/o anvils, it still messes up. Like she said it may have to do with entities or special blocks like heads or something. 

Here's fox2, a larger schematic you can try: https://cdn.discordapp.com/attachments/268444645527126017/1079182846608023693/fox2.schem

**Comment by TheMeinerLP** [comment]
I try it on my pc with FAWE 2.5.3 on a 1.19.3 Server. And works fine in less as 10 seconds.
Also undo make no bug at me

**Comment by dordsor21** [comment]
It seems to me to be related to the `queue.target-size` config option, mixed with "overloading" the server, from what I can tell. I.e. lower values of target size will cause more chunk updates to be flushed to the server, causing the issues.

**Comment by OneLiteFeather** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1861 might be a duplicate

**Comment by dordsor21** [comment]
> #1861 might be a duplicate

It is actually tbf
