### ISSUE TITLE
delete support 1.16.5

### ISSUE THREAD

**Issue by robalmeister** [IntellectualSites/FastAsyncWorldEdit#2110]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

1.16.5 max java version: 16. FAWE java version: 17

### To Reproduce

.

### Expected behaviour

.

### Fawe Debugpaste

.

### Fawe Version

.

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
FAWE works fine on Paper 1.16.5. If you need assistance, please visit our discord.
