### ISSUE TITLE
Memory leak causing high cpu usage

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#212]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.175

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/s51kTVcn
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
FastAsyncWorldEdit on 1.13.2 has a memory leak problem that can cause lag spikes on the server at a constant interval and this can be seen in timings.

**Memory leak suspect:**
![Memory leak suspect](https://user-images.githubusercontent.com/10485646/63223135-f9230880-c1a8-11e9-8514-371fdb1d4110.png)
![FAWE Dominator tree](https://user-images.githubusercontent.com/10485646/63223176-79e20480-c1a9-11e9-8f18-cda67b1fb4f6.png)
![leak suspect link](https://user-images.githubusercontent.com/10485646/63260813-e4627580-c279-11e9-950b-8fe981400801.png)

This is causing garbage collection issues and tripping Old Gen too:
https://timings.aikar.co/?id=048604ca26894b8ea48794e71def3174#config
![Gen](https://user-images.githubusercontent.com/10485646/63223199-e1984f80-c1a9-11e9-87da-949459288028.png)

An attempt to fix the issue was made in this commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/80e6a31f05ad4d2ba8295c3f558da658de5c5863 but it only made the issue worse.

Creating this ticket so that the issue isn't lost.

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Is this still an issue in a recent version?

**Comment by SecretlyJealous** [comment]
I'll create a new report if I still encounter this issue on newer builds
