### ISSUE TITLE
Wheat not copied with //copy

### ISSUE THREAD

**Issue by PancakeCatsss** [IntellectualSites/FastAsyncWorldEdit#2124]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Wheat is not copied during //copy or //paste, all other crops seem fine and are copied.

### To Reproduce

Plant some wheat, select the area and type //copy and then //paste you will see the wheat is not copied and you're left with just farmland. 

### Expected behaviour

For wheat to be copied like the rest of the crops.

### Screenshots / Videos

https://i.imgur.com/yXKH7P5.png

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a63aebc843fe439c9c3d55710de841a4

### Fawe Version

FastAsyncWorldEdit-370

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Remove wheat from disallowed blocks

**Comment by PancakeCatsss** [comment]
Oh wow, not sure why wheat is in the disallowed blocks by default but non of the other crops are but thank you.
