### ISSUE TITLE
Working on plot from outside of it

### ISSUE THREAD

**Issue by FETXU** [IntellectualSites/FastAsyncWorldEdit#2137]
**PlotSquared Feature Suggestion:**
Are we able to set this up so players can world edit inside their own plots while standing outside of it? This is important for 16x16 block plots as working from outside the plot is kinda necessary :slight_smile:

**How should it be implemented?**
Players should be able to run worldedit and Voxelsniper commands on areas inside their plots while standing outside of their plots.

**Additional context**
https://imgur.com/a/cbUebJE

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by PierreSchwang** [comment]
Transferred as the issue is in the PlotsquaredFeature.java

**Comment by FETXU** [comment]
Amazing! Thanks team <3

**Comment by dordsor21** [comment]
Just as a note, you sill need to enter the plot first still, and then it will cache the region
