### ISSUE TITLE
Entities containing data of other entities don't work with copy and paste operation

### ISSUE THREAD

**Issue by Hasenzahn1** [IntellectualSites/FastAsyncWorldEdit#2140]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When trying to copy an area that contains entities that store other entities nbt data, those entities are not copied (or only partially copied). 
Entities that are affected:
- All entities that have a passenger on board (boat, minecart, strider... ) (Also mentioned in bug #2091)
- Leash Knots (Entities that are leashed to a fence)
- fishing_bobber (The fishing rod that is cast by a player)

### To Reproduce

Entity with passenger:

1. Summon entity with passenger or get an entity inside a boat.
2. Copy the area `//copy -e`
3. Paste the area in the world `//paste -e`

Leash Knot:

1. Spawn Entity in the world
2. Leash entity to a fence
3. Copy the area `//copy -e`
4. Paste the area in the world `//paste -e`

Fishing Bobber:

1. Select an area
2. Cast the fishing rod. The bobber has to be inside of the area
3. Copy the area `//copy -e`
4. Paste the area `//paste -e`

### Expected behaviour

The entities should be copied correctly and no error should appear in the console

### Screenshots / Videos

Leashed Entity:
![image](https://user-images.githubusercontent.com/75828222/223800102-a83b0225-e25c-4997-8ea6-f512c068da02.png)

Entity passenger of another entity:
![image](https://user-images.githubusercontent.com/75828222/223800468-a3bea4a0-8c34-474a-99cc-cb61b34c2a2b.png)

Fishing Bobber:
![image](https://user-images.githubusercontent.com/75828222/223800679-59db0e08-2c38-4139-bb19-e9b2a0e2f89a.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/04fd914c406c457f90d49c3d9ab0f5ad

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f6e34485da754567a2c14306580a6b1d

### Fawe Version

FastAsyncWorldEdit version 2.5.3-SNAPSHOT-381;bfd919b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2091

**Comment by TheMeinerLP** [comment]
@Hasenzahn1 
I have already looked inside. 
Passangers are fixed. Leashes and bobbers are still buggy for some reason.

**Comment by TheMeinerLP** [comment]
Leashes now also fixed. But only 1.19.4 i will continue on this.

**Comment by dordsor21** [comment]
Going to close in favour of #2427 as from what I understand it is just passengers now
