### ISSUE TITLE
Tried to replicate another issue and this error happened

### ISSUE THREAD

**Issue by OneLiteFeather** [IntellectualSites/FastAsyncWorldEdit#2148]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

We tried to replicate #2104 with same schematic as given in the issue, but also we stumbled upon an different error. 

### To Reproduce

1. Replicate the situation given in #2104
2. Deactivate "send before history" in config as @SirYwell recommended to us
3. Paste schematic and //undo it after the chat message says, it is done

### Expected behaviour

No exceptions in console, everything should be fine (except the issue we replicated)

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/77929075/224578109-d5d3122a-a1d3-4f75-8f2d-d7bde3c15d33.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/496ae85b225c4a77847b1a0b18eca78c

### Fawe Version

FastAsyncWorldEdit-381

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Not sure that this is a replicable issue and I think it could be just a random "it just happened the once"...? Unless someone else has had this/you've had it since

**Comment by dordsor21** [comment]
Yeah, but has anyone actually been able to replicate it since?

**Comment by Texbio** [comment]
I am also having this issue on purpur 1.19.3, I paste a schematic inside some terrain and then try //undo, and it leaves horizontal lines of blocks.
