### ISSUE TITLE
worldedit.anyblock permission is not honored

### ISSUE THREAD

**Issue by Bobcat00** [IntellectualSites/FastAsyncWorldEdit#2159]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Having the permission `worldedit.anyblock` is supposed to bypass worldedit’s disallowed-blocks, but the permission has no effect. Even with the permission, the player cannot paste or set blocks in the disallowed-blocks list.

### To Reproduce

1. Set up a new server with FAWE and LuckPerms.
2. Connect to the server and for convenience op yourself and set your gamemode to creative.
3. Go to a suitable place to do edits.
4. Place some redstone wire on the ground.
5. Select the region (I use //hpos1/2) being sure to expand up so the redstone wire is within it.
6. Do //copy
7. Move a bit and do //paste. Observe that the redstone wire is not pasted (and it should not be).
8. Give yourself the worldedit.anyblock permission: `/lp user <player> permission set worldedit.anyblock true`
9. For good measure check the permission: `/lp user <player> permission check worldedit.anyblock`
10. Do the //paste command again. Now that you have the correct permission, the redstone wire should be pasted, **but it isn't.**
11. Just for good measure, remove redstone_wire from the disallowed blocks list in the FAWE config file.
12. Do `/fawe` reload`
13. Do //paste again. Observe the redstone wire is pasted this time.

The same behavior can be observed using the `//set` command.

### Expected behaviour

The player should be able to //paste and //set blocks on the disallowed-blocks list if he has the permission `worldedit.anyblock`.

This is a bit of a big deal for me, because I have 241 blocks on the disallowed block list.

### Screenshots / Videos

![2023-03-21_19 51 36](https://user-images.githubusercontent.com/3617206/226769501-a7e110f8-08a6-4e8b-951e-92d9f8eb8043.png)
This is what I used for my test. The region copied is on the left. The result of the paste command is on the right.

![anyblock](https://user-images.githubusercontent.com/3617206/226769782-6792213c-3db7-4dc4-95d0-97131b66e1c0.png)
Screenshot showing the worldedit.anyblock permission check and the result of doing `//set redstone_wire`

### Error log (if applicable)

N/A

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/fabedc9261a24e8bb25a2316038c24fc

### Fawe Version

FastAsyncWorldEdit version 2.6.0-SNAPSHOT-391;eb1c9dc

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

This was tested on a brand new server with only FAWE and LuckPerms, using the default configs for both.

**Comment by Bobcat00** [comment]
P.S. I noticed that plugin.yml doesn't list `worldedit.anyblock` in the list of permissions. I don't know if that matters or not.

**Comment by dordsor21** [comment]
This is effectively by design. `worldedit.anyblock` within WorldEdit is specifically for the `disallowed-blocks` in the WorldEdit config. Given limits in FAWE are configurable, it is expected that if users want differing disallowed blocks for differing players, then different limits should be assigned. Perhaps another @IntellectualSites/fastasyncworldedit-team can offer their opinion on if we should just have `worldedit.anyblock` allow bypass of the blocks disallowed by the limit?

**Comment by Bobcat00** [comment]
> it is expected that if users want differing disallowed blocks for differing players, then different limits should be assigned.

Oh! I didn't realize that part of the config supported multiple user groups and was controlled by permissions. In that case, this issue can be closed.

Do I need to duplicate all the sub-items under limits.default, or can I just specify only the disallowed-blocks key (and the others will use the default value)?

**Comment by dordsor21** [comment]
Yeah just copy-paste all the limit values, name it something different and give `fawe.limit.<limit>`. I would be cool to have cascading limits though o.o
