### ISSUE TITLE
Misaligned SVG In IJ project view

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#2173]
![Screenshot 2023-04-07 at 14 52 49](https://user-images.githubusercontent.com/13383509/230612020-1e0fe7d7-4bcd-45c1-8046-b53806a1ac22.png)

It appears that a recent update changed the view boxes. We have to update our icon in https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/.idea/icon.svg.

**Comment by TheMeinerLP** [comment]
Thats a issue in IJ. In my idea works sometime

**Comment by NotMyFault** [comment]
> Thats a issue in IJ. In my idea works sometime

The icon has to be made smaller nonetheless. The misalignment is not acceptable and looks awful, regardless it's working for some people.

**Comment by TheMeinerLP** [comment]
Yeah in new IJ when you copy it. IJ will it convert it to a png for perfect size

**Comment by TheMeinerLP** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/6745190/230618149-f5f4629c-7e8a-4c7e-b433-4af83d495a3c.png">
Like so ?

**Comment by NotMyFault** [comment]
Yes.
