### ISSUE TITLE
1.19.4 Support

### ISSUE THREAD

**Issue by KleinCrafter** [IntellectualSites/FastAsyncWorldEdit#2175]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Installed paper 1.19.4 Build #501 and updated FAWE.
Try to paste a schematic and got an exception in console.
Blocks got placed. structure_void not..

### To Reproduce

Have an old schematic containing structure_void

run commands in console:
`/world ...`
`schematic load ...`
`/paste -aso`
java.lang.NoSuchMethodError
`/replace structure_void air`
java.lang.NoSuchMethodError

### Expected behaviour

No exceptions in console.
Pasted schematic with structure_void placed..

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9f057dd7d4ec4b17b496d226c5952a7e

### Fawe Version

FastAsyncWorldEdit version 2.6.0-SNAPSHOT-398;a42864e

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
For context: <https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/1fddefce1cdce44010927b888432bf70c0e88cde#src/main/java/org/bukkit/craftbukkit/CraftChunk.java> changes here must be adapted.

**Comment by SecretlyJealous** [comment]
This affects `/plot clear` too, from my testing the clear works but console is spammed with errors: https://athion.net/ISPaster/paste/view/7f3282f72df24779a50f69cc90d76617
