### ISSUE TITLE
Users without OP are unable to copy, paste, or set, but can receive the wand via //wand

### ISSUE THREAD

**Issue by PoseidonGames** [IntellectualSites/FastAsyncWorldEdit#2180]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Builders on my server receive the wand tool when executing //wand, but there is no operation completion notice when they run //copy, //paste, or //set; nothing happens. They are able to select positions but unable to operate on them. 

### To Reproduce

1. Use luckperms to give the following permission: 
fawe.worldguard
fawe.admin
fawe.selection.pos
fawe.select.pos
fawe.
/lp user <username> parent add builder world
      Which entails:
      permission set fawe true
      permission set worldedit true
      permission set worldguard true
2. User runs //wand
3. //wand succeeds
4. User selects two positions
5. The two positions select succeeds
6. User attempts //paste, //copy, //set
7. No effect

### Expected behaviour

I expected my building staff to have access to all world edit commands. 

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/07863f9cf245422ab692fcc22c782147

### Fawe Version

FastAsynbWorldEdit-401

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PoseidonGames** [comment]
The user is no longer receiving errors in chat, it's just that nothing is happening even after they select.

**Comment by OneLiteFeather** [comment]
You need to use the right permissions which are listed in the FastAsyncWorldEdit documentation [here](https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Main-Commands-and-Permissions#pos2-coordinates)
I tested your issue with paper 1.19.4 and your version of FAWE, giving myself via Luckperms the right permissions in the documentation worked as intended.
Also check out the documentation for addional permissions you might need.
