### ISSUE TITLE
Disallowed-Blocks config and perm issue

### ISSUE THREAD

**Issue by 360shvit** [IntellectualSites/FastAsyncWorldEdit#2183]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

The **Disallowed-Block** list inside the FAWE-Config is not persisting across server restarts. 
Attempting to delete the list completely results in a full reset to the default strings. 
Leaving the list symbols up front (-) results in the values not being set to default but to null instead.

Furthermore, attempting to bypass the disallowed-blocks via **fawe.bypass**, **fawe.admin**, and **worldedit.anyblock** using LuckyPerms for permissions was not possible. 

Setting Universal-disallowed-blocks to **false** also has no impact, cant use it in non pattern commands.

Additionally, when attempting to perform the **//wea** command, the output only shows "_Your FAWE edits are now restricted_" and does not indicate whether the restriction is on or off.

### To Reproduce

1. Use a Server with the given information (1.19.4, Paper 514, FAWE 402)
2. Stop the Server
3. Delete the disallowed-blocks list inside FAWE config 
4. Additionally change a Value inside the config (e.g debug = true o. universal-disallowed-blocks = false)
5. Save the config
6. Start up the server

7. Check the Config for changes, compare if everything got set to default or just the disallowed-blocks

### Expected behaviour

The Disallowed-Block list should persist across server restarts and not reset to default strings.
The Bypass permission/OP on the server should allow the use of disallowed-blocks even if they are reset to default values.
Universal-disallowed-blocks = false should include the disallowed-blocks to operations similar to Copy, Paste, Stack, and //repl brush.
The //wea command should allow the restriction to be toggled on and off.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/89588c131b654262b2a8f72e24acaa1f

### Fawe Version

FastAsyncWorldedit-Bukkit-2.6.0-SNAPSHOT-402.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I have thoroughly tested different methods to resolve the issue, including downloading the file, modifying it, and re-uploading it.  Furthermore, I have tested older versions of the plugin such as FastAsyncWorldedit-Bukkit-2.1.3-SNAPSHOT-165.jar. Although the configuration resets as in version 401, the behavior is different. For instance, it allows me to use the disallowed-blocks in operations like //copy //paste and so on with universal-disallowed-blocks = true.

 Config values changed: debug = true, universal-disallowed-blocks = false, disallowed_block = - - -
 Clearing the - symbole results in it just reseting, disallowed_block = - - - results in an error, so i used this for the debugpaste
 otherwise it would performs with the default disallowed-blocks and thus does not create errors (Used for the debugpaste)

I hope this information helps identify the issue or clarify whether there is a mistake on my part.
If you require any additional information or testing, please do not hesitate to let me know.
I am more than willing to provide any further details to help resolve this issue.

**Comment by 360shvit** [comment]
I can give that a try, didn't think of that one.

**Comment by 360shvit** [comment]
Alright that works!
Maybe this should be added to the comment. 
Thanks alot, really appreciate the quick response.

**Comment by TheMeinerLP** [comment]
No problem. If it solve please close the issue 😄
