### ISSUE TITLE
Universal-disallowed-blocks

### ISSUE THREAD

**Issue by 360shvit** [IntellectualSites/FastAsyncWorldEdit#2184]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Setting the 'universal-disallowed-blocks' to false does not change the behavior of the 'disallowed-blocks' set.

### To Reproduce

1. Set any block to be disallowed (tested with "minecraft:stone").
2. Set the 'universal-disallowed-blocks' to false.
3. Execute any non-pattern related command (tested with //copy/paste, //move, and //stack).
4. Check whether it moves or stacks the previously disallowed blocks.

### Expected behaviour

From my understanding of the configuration, changing the value to false should allow the previously disallowed blocks to be used in certain actions. The configuration file states:

 If the disallowed blocks listed in worldedit-config.yml should be disallowed in all edits,
 not just where blocks patterns are used.
  - Can prevent blocks being pasted from clipboards, etc.
  - If fast-placement is disabled, this may cause edits to be slower.

To me, this means that the user should be disallowed to use these blocks in larger operations like //set, //replace, and inside of brushes, but may still be allowed in certain situations like when pasting from a clipboard.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3845c797b7b1403ca0a4158b4c57d4d6

### Fawe Version

FastAsyncWorldedit-Bukkit-2.6.0-SNAPSHOT-402.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Provided the debugpaste even tho there is no error produced.

In previous versions (1.16.5+), using disallowed blocks in certain commands was a useful way to ensure performance on a build server. It prevented major edits from being performed with lag-intensive blocks, while still allowing experienced users to use them via certain commands even bypass some of restrictions with the copy/clipboard pattern.

If the general purpose of 'universal-disallowed-blocks' is to provide players with more flexibility in their use of blocks, please let me know, as I want to make sure I understand what this feature is intended to allow.

**Comment by 360shvit** [comment]
Afterlooking at the code, I believe it is being used differently than what is described in the configuration. 
It appears that the plugin should use the list of disallowed blocks even for players with bypass permissions when set to true.(please correct me if I'm mistaken, as the code was  difficult to follow for me atleast).
Despite setting "universal-disallowed-blocks" to false, indicating that disallowed blocks should only affect players without bypass permissions, the plugin is still using the disallowed blocks list for all players.
I tested this by disallowing "stone" and attempting to copy or use stone blocks with OP and bypass permissions, but was unable to do so.

**Comment by OneLiteFeather** [comment]
I'll look into that deeper, maybe @TheMeinerLP can take a look on that code as well
