### ISSUE TITLE
//hollow removing more blocks than it should

### ISSUE THREAD

**Issue by masterX244** [IntellectualSites/FastAsyncWorldEdit#2187]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

when running //hollow it removes the outside walls at some sides, too instead of leaving the shell of the selected blocks intact.

### To Reproduce

having a irregularly shaped object and running //hollow

### Expected behaviour

Only the outermost wall blocks left to remove any interior blocks that would be hidden

### Screenshots / Videos

![2023-04-24_18 34 13](https://user-images.githubusercontent.com/1544922/234061166-1a7ec3ed-dd07-437c-be9c-d555877b7f48.png)
![2023-04-24_18 34 16](https://user-images.githubusercontent.com/1544922/234061177-ec58dea6-c4bd-4cf3-8b94-e439fbc22a17.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/66a68d15840145f2bdbb31155f851031

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-408

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Main-Commands-and-Permissions
Use strg + F to search for hollow
Find out that the value in the command does not change how many blocks are changed in game. The number stays the same - all blocks are removed instead of hollowed out.
Replicated with Paper 1.19.4 (519) and Fawe-408

Tried with different thickness values:
![grafik](https://user-images.githubusercontent.com/77929075/234104074-f290dc4b-2577-446f-9b18-d828b699c52c.png)

**Comment by TheMeinerLP** [comment]
![image](https://user-images.githubusercontent.com/6745190/235270090-e33bc48e-7274-4cb2-9845-c6b43af46a50.png)

**Comment by Zeranny** [comment]
The recurseHollow() method in EditSession.java is what causes this behaviour.

Starting from the center block, it expands outwards checking adjacent blocks for the edge of the shape, ignoring blocks outside of the region.

For the sake of simplcity, if the face of a cybe is on the face of the region it will be considered "inside" and hollowed.


I have done a very quick/crude test implementation of what I think is your desired functionality?

https://user-images.githubusercontent.com/1365964/235274377-a4ac7032-114c-4a6e-9d1b-fb685077c5ac.mp4

**Comment by TheMeinerLP** [comment]
Okay i got it. 
Hollow is working as expected. Also WE is same working way.
The workaround for working with these use the `//outset 1` command before hollow.

**Comment by OneLiteFeather** [comment]
This behaviour was not properly documented, I will add an issue for the documentation. Thank you for your issue :)
