### ISSUE TITLE
Invalid region mask: PlotSquaredMask (unnecessary/slightly spammy message)

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2188]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

After updating from FAWE 2.6.0 to 2.6.1 players on my server complained about an error appearing in chat every time they use a worldedit command. The operation still works but it gives an error in chat, also the first operation does not give this error but any operation after that will give the error.

First operation gives no error:
![2023-04-27_09 16 41](https://user-images.githubusercontent.com/10485646/234802170-b5fb3f0c-57a1-4600-9aa3-e9298ae3d2a3.png)

Every operation after the first gives this error in chat "Invalid region mask: PlotSquaredMask":
![2023-04-27_09 16 48](https://user-images.githubusercontent.com/10485646/234802194-47b37103-982d-40b9-bf6f-b0927e5e0695.png)

### To Reproduce

1. Make sure you are not OP
2. Select a region with the wand and do `//set 0`
3. Do `//set stone` on the same region and you will get an error in chat

### Expected behaviour

There should be no error in chat

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/487f28fdfaa74188acd4ba24a4a22ecd

### Fawe Version

FastAsyncWorldEdit version 2.6.2-SNAPSHOT-408;9f3c909

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
I had this issue days ago but I forgot to open an issue for it. It happens when the wea is restricted and you are not OP.
This one is new as well, we should check out what changes made that

**Comment by TomLewis** [comment]
I too am having this issue.

**Comment by dordsor21** [comment]
This is not a bug. This is the correct behaviour that was not in done until recently. As stated in the PR above, perhaps the message is un-needed or would server better if debug is enabled.

**Comment by Synkstar** [comment]
You can actually modify stuff outside of your plot since the region mask is broken. I just put my server on regular worldedit since that works fine.

**Comment by dordsor21** [comment]
Any steps to replicate/details?

**Comment by OneLiteFeather** [comment]
> I had this issue days ago but I forgot to open an issue for it. It happens when the wea is restricted and you are not OP. This one is new as well, we should check out what changes made that

@dordsor21 /wea on the plot, then use fawe on plotsquared (for example, a sphere brush)

**Comment by dordsor21** [comment]
...... /wea disables your worldedit restrictions......

**Comment by Synkstar** [comment]
> Any steps to replicate/details?

Setup a plots server using steps on https://intellectualsites.github.io/plotsquared-documentation/installation/installation.html and install fawe. I just compiled the latest github release of plotsquared though myself. 

Use a permission plugin such as luckperms and give the default rank these permissions
```
worldedit.brush.* 
worldedit.history.* 
worldedit.region.* 
worldedit.selection.* 
fawe.permpack.basic 
plots.claim 
plots.claim.1 
plots.permpack.basic 
plots.permpack.basicflags 
plots.permpack.basicinbox 
plots.plot.1 
plots.plot.10 
plots.use 
worldedit.wand 
```

Claim a new plot by doing /plots claim.
From inside the plot do //pos1
Move outside of the plot and do //pos2
Now from inside of the plot do //set stone
It will spit out the invalid region mask error and you now have just modified blocks outside of your plot. This can be used to grief other plots and the road. This error does not occur with regular worldedit and the plot restriction works correctly.

**Comment by OneLiteFeather** [comment]
> ...... /wea disables your worldedit restrictions...... that's the point of the command. The /wea command getting "stuck" sometimes is an entirely different issue

https://athion.net/ISPaster/paste/view/e8174171f7404f0cae514c532d2b750d It only happens when you restrict it as you can see here. If you repeat the command to bypass the restriction it happens. Also on this server OP is disabled.
