### ISSUE TITLE
Correct version of: Error while i'm using wand

### ISSUE THREAD

**Issue by TBAProgramming** [IntellectualSites/FastAsyncWorldEdit#2190]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

While i'm using fawe just not working its not do anything

### To Reproduce

1 see if i'm in lastest version fawe
2 check lastest.log
3 console errors

### Expected behaviour

not working

### Screenshots / Videos

https://imgur.com/qIBSZCI video

### Error log (if applicable)

https://paste.gg/p/anonymous/9918a87b91fb4c40b98c4d757629adf8/files/e03f169f9d66485386189168092aa27e/raw

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/35d738de164a4fe2ac4df03b0f16e712

### Fawe Version

2.6.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Paper.

**Comment by TBAProgramming** [comment]
i made another issue and closed by not correct, that correct bug i deleted all plugins and keep only fawe and viaversion and viaversion addons

**Comment by TBAProgramming** [comment]
`what do
now?`

**Comment by PierreSchwang** [comment]
NMF already told you what to do. If you continue to spam in those issues you'll be blocked from posting any further issues.

**Comment by TBAProgramming** [comment]
hm bro that a bug rly

**Comment by TBAProgramming** [comment]
trust me

**Comment by NotMyFault** [comment]
I recommend you take the advice given and do the necessary maintenance tasks, instead of spamming replies.

Once that is addressed, we can assist you. Otherwise, we can't help you.

**Comment by TBAProgramming** [comment]
see that video https://imgur.com/qIBSZCI
