### ISSUE TITLE
Error when trying to //set

### ISSUE THREAD

**Issue by GStudiosX2** [IntellectualSites/FastAsyncWorldEdit#2192]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

I selected region using the worldedit wand and did //set dirt and it gave me a error in console

### To Reproduce

1. Put dev build of worldedit or latest github release on a paper 1.19.4 server
2. //wand and then select a region
3. run //set dirt
4. error

### Expected behaviour

to set the area to dirt and not throw a error

### Error log (if applicable)

https://gist.github.com/GStudiosX2/387c33d5af2d2afbfeca515547bec171

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b89b628cdf5f4b1c8ad59a3866854aba

### Fawe Version

it says FastAsyncWorldEdit-2.6.1 but I first tried on FastAsyncWorldEdit-2.6.2-SNAPSHOT-408 i only went to 2.6.1 so I can see if that works

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Paper.

**Comment by GStudiosX2** [comment]
> Update Paper.

the host im using currently doesn't have custom server jars so that's the latest version of paper for 1.19.4 i can use on it i mean i could ask their support if they can update paper but i dont see what changed in newer versions to fix fawe ?

**Comment by NotMyFault** [comment]
Then ask your host to update Paper for you. At the point of writing this, you are 55 updates behind.
It's expected to run up-to-date version of Paper, instead of an arbitrary outdated one.

**Comment by GStudiosX2** [comment]
ok
