### ISSUE TITLE
//brush mangrove

### ISSUE THREAD

**Issue by Scot-Survivor** [IntellectualSites/FastAsyncWorldEdit#2197]
### What feature do you want to see added?

Currently, the tree brush does not support mangrove trees. 

I would like this to support mangrove trees.

### Are there any alternatives?

Not that I know of, I checked other issues I couldn't find any with the content "mangrove".

**Comment by OneLiteFeather** [comment]
This PR will add it because it is clearly missing in newer minecraft versions. Nice catch!

**Comment by Scot-Survivor** [comment]
Awesome, thank you :)
