### ISSUE TITLE
FAWE not working when using CoreProtect extent

### ISSUE THREAD

**Issue by denisapain** [IntellectualSites/FastAsyncWorldEdit#2200]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

When I tried to use FAWE it asked me to add a plugin extent since when I used //set no blocks where set, when I do add coreprotect logger extent to the Fawe config it just gives me this error.

https://pastebin.com/GM4gpZeW

FAWE worked before with CoreProtect, and we haven't updated fawe or coreprotect

### To Reproduce

Install FAWE and CoreProtect on Paper 1.19.4 server
Try using //set
Fawe tells you about coreprotect extend
You add coreprotect extent
Fawe gives error when using //set (I can set the selections using //wand)

### Expected behaviour

For the blocks to appear and for no error to appear

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/126583428/235375057-8c23be67-420a-4cd3-8d30-78e79ed0f004.png)

![image](https://user-images.githubusercontent.com/126583428/235375071-8fa13398-95ef-4323-aef3-85b0685cb209.png)

![image](https://user-images.githubusercontent.com/126583428/235375080-795daccc-d48e-49eb-8331-41620edad140.png)

### Error log (if applicable)

https://pastebin.com/GM4gpZeW

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0632408456364c7ba66fc2de0fc6f29b

### Fawe Version

FAWE 408

### Checklist

- [X] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Update paper

**Comment by denisapain** [comment]
> Update paper

Ok I will!

**Comment by denisapain** [comment]
> Update paper

This has fixed it, thank you :D ❤️
