### ISSUE TITLE
1_19_3_R3.PaperweightPlatformAdapter class could not be initialized (NoClassDefFoundError)

### ISSUE THREAD

**Issue by BuggyAl** [IntellectualSites/FastAsyncWorldEdit#2208]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Error appears in chat when attempting to use //replacenear stating the 1_19_3_R3.PaperweightPlatformAdapter class could not be initialized (NoClassDefFoundError)

### To Reproduce

1. Create a Paper 1.19.4 server on Minehut
2. Install the latest FAWE snapshot
3. Attempt to use //replacenear

### Expected behaviour

The command works as normal without errors and replaces the blocks using the specified parameters.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/64368488/235541757-8123d200-946d-4f00-9adb-ecc5ac3792c9.png)

### Error log (if applicable)

https://gist.github.com/BuggyAl/d6436c323d0196c933d482a9647ddd67

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4c30f1858f74489a8d474aabf5d13127

### Fawe Version

FastAsyncWorldEdit version 2.6.2-SNAPSHOT-413;92a6ff5

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Paper, you are more than 50 updates behind.
