### ISSUE TITLE
Broken Clipboard

### ISSUE THREAD

**Issue by OneLiteFeather** [IntellectualSites/FastAsyncWorldEdit#2209]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

The chat shows that the own clipboard is broken.
![grafik](https://user-images.githubusercontent.com/77929075/236215775-697cfebc-0bea-4bfc-a1d3-febe914998ed.png)

### To Reproduce

1. Select a huge area with //pos1 and //pos2 (for example >120 mio blocks)
2. //copy
3. Wait for the copy feedback in chat
4. Leave the server
5. Rejoin and see the error in chat

### Expected behaviour

No error message, also the clipboard is empty somehow. Should not happen.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dcdeada304084a178804f6974c93ab29

### Fawe Version

FastAsyncWorldEdit-413

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

FAWE might need a higher value than int (long or biginteger) to do more huge clipboards because the hardware and software for minecraft servers are evolving as well - people can build and do more with their hardware as 10 years ago. Also they might have more disk space than in the past.

**Comment by Tsoccerguy3** [comment]
[server error log.txt](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/11412458/server.error.log.txt)
Tested FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415 and verified clipboard broken and this error happens

**Comment by OneLiteFeather** [comment]
Thank you a lot, this issue is known and the problem goes way back to worldedit as well.
The best thing would be to make a different solution for saving huge clipboards, for example:

"Your selection is too huge, if you want to copy it, try //lazycopy instead as it can save on maximum approximately 2GB"
Or on //copy run for the user //lazycopy instead if it mets the right permission.

These are my quick fix ideas, but it's temporary.

**Comment by MattBDev** [comment]
I think the best course of action would be a long-term solution.
I'm just not sure that the issue is the size of the clipboard. I could be wrong of course.
