### ISSUE TITLE
//set command does not work

### ISSUE THREAD

**Issue by felix25364** [IntellectualSites/FastAsyncWorldEdit#2213]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

So i select a region using a Wooden Axe and as soon as i do //set and any Block it just spits an this error message into the server console

### To Reproduce

Download the Bukkit 2.6.2 SNAPSHOT-415
Sellect a region
Use //set

### Expected behaviour

It doesnt do anything exept spitting out an error

### Error log (if applicable)

https://gist.github.com/felix25364/febbfd19096045ec99056f196d9d938e

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/29eabfd4eb064794a5d2897a4a989424

### Fawe Version

2.6.2 SNAPSHOT-415

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Update paper
