### ISSUE TITLE
io/papermc/paper/util/MCUtil

### ISSUE THREAD

**Issue by ImboredTech** [IntellectualSites/FastAsyncWorldEdit#2215]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

I was trying to cut and certain part of my world by doing //cut and the chat tells me to Report the error and to see console with it saying java.lang.NoClassDefFoundError: io/papermc/paper/util/MCUtil.

### To Reproduce

1. do //wand
2. select 2 regions
3. do //cut

### Expected behaviour

It should cut the selected regions.

### Screenshots / Videos

https://user-images.githubusercontent.com/106279751/236937246-751991b9-7fbf-44b5-9bd8-6024f404df12.mp4

### Error log (if applicable)

https://paste.gg/p/anonymous/8b90ebc7e3df49a48e10e15c64093373

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e072e7219548410a887ec5982c8b2265

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
Update paper

**Comment by OneLiteFeather** [comment]
@ImboredTech can you tell me after updating paper if it fixed it?
