### ISSUE TITLE
Folia Bug

### ISSUE THREAD

**Issue by Yomamaeatstoes** [IntellectualSites/FastAsyncWorldEdit#2216]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Exact Error

https://mclo.gs/PuFmNpK

Full Console

https://mclo.gs/UHP5YlD

### To Reproduce

Load in the game

I believe you have to have //schematic load a structure of decent size

### Expected behaviour

No error

### Screenshots / Videos

None

### Error log (if applicable)

https://mclo.gs/UHP5YlD

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c00b53695a7f4e3db2406a4e7dd9488a

### Fawe Version

FastAsyncWorldEdit version 2.6.0-SNAPSHOT

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

None

**Comment by TheMeinerLP** [comment]
This error is not directly a FOLIA error. Its just a generic issue

**Comment by OneLiteFeather** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2209 Duplicate and not a "bug" directly just the edge of schematic saving.
