### ISSUE TITLE
Trying to do edits with circles or cylinders gives me an error

### ISSUE THREAD

**Issue by JediM4ster** [IntellectualSites/FastAsyncWorldEdit#2217]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

I logged on to do some building and any edit I do gives me an error and tells me to report it.

### To Reproduce

1. Select a cylinder or try using //cyl to generate a circle
2. Try to //set stone or anything

### Expected behaviour

Nothing will happen except give an error in chat and in console

### Screenshots / Videos

![Screenshot_7](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/72643339/8880e4d6-82b5-4f6f-a18b-603a3732ab6b)

### Error log (if applicable)

https://pastebin.com/euUp1HzZ

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/836d4f49c3174d82b2b3cb7067bc6a2f

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-416

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Update paper

**Comment by JediM4ster** [comment]
ah alright XD I'm dumb thank you
