### ISSUE TITLE
FAWE + PS | You can set blocks on other plots

### ISSUE THREAD

**Issue by Luke2206** [IntellectualSites/FastAsyncWorldEdit#2227]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Hi, I have a problem with FAWE on my Creative Server.

I installed FAWE there today. so far everything works but now I noticed that users without OP/* can use Worldedit on a plot where they are not added. ->Video

PS Debugpaste: https://athion.net/ISPaster/paste/view/aed228979b00473abf267ec0db44d012

FAWE Debugpaste: https://athion.net/ISPaster/paste/view/42197f4cb6e24edeb371529262a3b0fe 

### To Reproduce

1. install FAWE
2. give the perms from the image
3. mark a position on another plot and position 2 on your plot
4. try to set blocks

### Expected behaviour

That it is not possible to set blocks on other plots

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/102369468/156e585d-6b1a-4ec4-a85e-0c65f929d357)

https://cdn.discordapp.com/attachments/344128526435221505/1107364702138413156/problem.mp4    <-Video

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/42197f4cb6e24edeb371529262a3b0fe 

### Fawe Version

FastAsyncWorldEdit-2.6.2-SNAPSHOT-420

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

--

**Comment by dordsor21** [comment]
You can use build 414 for now (https://ci.athion.net/job/FastAsyncWorldEdit/414/)
