### ISSUE TITLE
clipboard use-disk set to false will set random distorted blocks

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#224]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.179

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/BSAdYzSG
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
In 1.12.2 you were able to keep use-disk set to false for the clipboard however in 1.13.2 if you have this setting on false all worldedit operations will stop functioning correctly and will set random distorted blocks.

In this example I'm using copy and paste with slabs but it causes a random combination of blocks to be set like this:
![fawe glitch 10233](https://user-images.githubusercontent.com/10485646/66708234-41901a00-ed45-11e9-8ebd-740dc9af6dc5.png)

```
clipboard:
  # Store the clipboard on disk instead of memory
  #  - Will be slightly slower
  #  - Uses 2 bytes per block
  use-disk: false
```

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**How to replicate**:
In the config for `clipboard` set `use-disk` to false and then try to copy / paste blocks.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Fixed in 5197ed0
