### ISSUE TITLE
Pasting doors not working

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2245]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Pasting doors does not work, I'm not sure if there are other blocks affected:

Doing a copy:
![2023-05-24_09 55 57](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/10485646/392bb7f6-8348-450c-962e-d362477da5fd)

Doing a paste:
![2023-05-24_09 56 04](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/10485646/3ca12c79-7a97-4011-80fa-ddf3a3de5faf)

### To Reproduce

Copy a door with worldedit then use //paste

### Expected behaviour

The door should be pasted

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8c21fcdfda2a4eafa6dc1769c8701633

### Fawe Version

FastAsyncWorldEdit version 2.6.2-SNAPSHOT-437;362f6cc

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Could you also take a look at other double-height blocks (tall grass e.g.) and trapdoors if you've got a minute?

**Comment by SecretlyJealous** [comment]
> Could you also take a look at other double-height blocks (tall grass e.g.) and trapdoors if you've got a minute?

Same thing happens with tall grass and trapdoors, they don't get pasted

**Comment by OneLiteFeather** [comment]
I'll take a look if I can replicate it with only FAWE and Paper and try it with Plotsquared as well

**Comment by OneLiteFeather** [comment]
I wasn't able to replicate this issue with plotsquared and fawe and also latest paper version. Looks more like an issue with Coreprotect to me. Can you try it without CoreProtect to see if it works @SecretlyJealous ?

**Comment by SecretlyJealous** [comment]
I reproduced it without CoreProtect, fawe debugpaste: https://athion.net/ISPaster/paste/view/148f745aac5a423b92863cbfbfe4d9a7

![2023-05-24_11 29 40](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/10485646/3e62f52b-670f-4f02-b198-9b2332047385)

![2023-05-24_11 29 47](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/10485646/1c671d78-3779-499e-915b-2395d2127326)

**Comment by OneLiteFeather** [comment]
Second guess: I saw Panilla working with NBT and FAWE. That might be the problem. Can you test it without it as well @SecretlyJealous ?

**Comment by SecretlyJealous** [comment]
> Second guess: I saw Panilla working with NBT and FAWE. That might be the problem. Can you test it without it as well @SecretlyJealous ?

I figured out the problem, it's because of this change: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2184. I've changed "Universal-disallowed-blocks" from true to false. I don't want players to set doors for example but I still want them to be allowed to paste them.
