### ISSUE TITLE
region-restrictions implementation for towny seems to be broken

### ISSUE THREAD

**Issue by DreiFxn** [IntellectualSites/FastAsyncWorldEdit#2249]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

When using region-restrictions with Towny in FAWE, most commands do not really work, i.e. commands e.g. //set stone do not get any reaction in the chat after sending the command. When using e.g. //move, on the other hand, it says in the chat that something has been moved, but nothing happens. Likewise with //setbiome xy there is a reaction that something has been changed [when selction is very big] but nothing happens. 

### To Reproduce

1. Install Towny, FAWE, LuckPerms & Worldguard
2. Create a Town 
3. Give required permissions to non-op Account [fawe.towny   fawe.towny.member   fawe.towny.*   fawe.worldguard    worldedit.*]
4. Try using //set stone //move //setbiome and so on - inside and outside your towny plot

Optional:
4.1 Remove Worldguard 
4.2 Delete __global__ Region
4.3 Add Yourself to __global__ Region
4.4 Set Towny as  exclusive-managers

The result is the same

### Expected behaviour

Permission to use WorldEdit if the user is a member or owner of the region

### Screenshots / Videos

https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/63371457/129217c6-af72-4870-8b4e-a3dcd1950759

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8827d4445024434d931378be2aca65f5

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-438.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I have found that it works reasonably well in FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-415.jar, where the biome change function does not work, but functions //set //move and so on do. However, in this version it seems to be mainly a problem with the regulation whether World Edit may be used there or not. Apparently, the permission test is based on whether the player is standing in one of his plots or not when executing the command, regardless of whether the actual selection is actually in the plot.

**Comment by LlmDl** [comment]
How big are your townblocks? What is your town_block_size in the towny config?

**Comment by DreiFxn** [comment]
A town block is exactly one chunk
town_block_size: '16'

I hope this is helpful.

**Comment by LlmDl** [comment]
Using F3+G can you show us another video, so I can see if you're cross plots in town?

In your video I cannot tell if you're in the wilderness or in town or what.

**Comment by DreiFxn** [comment]
Before recording this video, I updated to the latest Towny Fullrelease & latest FAWE Snapshot.
Towny 0.99.1.0 &  FastAsyncWorldEdit-Bukkit-2.6.3-SNAPSHOT471 

Furthermore, I have activated F3 + G and the Plot Perm Hud, of course my test account is within its city at all times.
Accordingly, apart from //move 10 attempt, I have never had a selection between multiple plots

Hope this video helps.


https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/63371457/c46f767c-a786-4eea-bdae-0155c812a3e6

**Comment by LlmDl** [comment]
It's because FAWE has been only allowing selections between 0 and 156 y level, instead of the full height of the world (and Towny's TownBlocks.)

Go up to between y level 0 and 156 and see if works, then go up above y 156 and retest again.

**Comment by DreiFxn** [comment]
In fact, I'm sorry to cause so much trouble, so of course it would be nice to see an implementation that makes it possible to use FAWE all over the world. Apparently it is only a problem with restrictet regions, because of course with my admin account it also works outside these "world heights".

**Comment by LlmDl** [comment]
Yes, but can you tell me if the issue disappears when you're operating between 0 and 156 y?

**Comment by DreiFxn** [comment]
Basically it seems to work, apart from the height problems, however I still noticed a small "possible bug", I don't know if it just doesn't work better or is not meant that way, I'd best make another video.

[the hight problem is a fawe issue tho right?]

**Comment by LlmDl** [comment]
The height issue is in the FAWE code, and I will make a pull request to fix it, I just want to confirm that your issue is fixed if you operate between 0 and 156 y. Can you make a video of that?

**Comment by DreiFxn** [comment]
So I tested it, it actually only works between y 0 and 156 - apart from the problem in the video, it seems to work "basically" between these heights. All this chunks are inside of my city.

https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/63371457/e7a20244-2af4-4112-9727-791706be0ce2
