### ISSUE TITLE
ClipboardBrush error

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#225]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.179

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/XuhJEDjM
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
I think this error is either caused by //mask >sand or //paste -a as they were both used recently.

Error log: https://pastebin.com/Z0C2XLXS
Another error: https://pastebin.com/P2JbcG7s

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**How to replicate**:
Not quite sure.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
I believe this error was already fixed, @SecretlyJealous can this be closed?

**Comment by aurorasmiles** [comment]
assuming this issue was fixed ages ago
