### ISSUE TITLE
- [Sat 14:21:18 ERROR com.sk89q.worldedit.extension.platform.PlatformCommandManager] An unexpected error while handling a FastAsyncWorldEdit command

### ISSUE THREAD

**Issue by M3rcena** [IntellectualSites/FastAsyncWorldEdit#2250]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

When I try to set something using //set for example //set air it gives me an error and says to report it

### To Reproduce

1: Select an area using your wand
2: Try to use //set air
3: Get the Error

### Expected behaviour

If you run //set air we expect it to clear the selected blocks

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/102794864/48fddb33-afbb-4ae9-bc63-d2e908bb142c)

### Error log (if applicable)

https://gist.github.com/M3rcena/ab4c7aadba49482b23cfe847bda0f2c5

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4a05536156ab4747a011842d0ad5d9d1

### Fawe Version

FastAsyncWorldEdit version 2.6.2-SNAPSHOT-438;3041ff3

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Paper.
