### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dinobossytnew** [IntellectualSites/FastAsyncWorldEdit#2253]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

https://bin.bloom.host/oburopijuq.properties

### To Reproduce

set the plugin to 1.19.4

### Expected behaviour

.

### Error log (if applicable)

https://mclo.gs/zrhoqoh

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0407c8558cd444c88df70d1cb5961a56

### Fawe Version

15:27:53 INFO]: FastAsyncWorldEdit version 2.6.2-SNAPSHOT-439;a553961 [15:27:53 INFO]: Blazingly fast world manipulation for builders, large networks and developers. [15:27:53 INFO]: Website: https://www.spigotmc.org/resources/13932/ [15:27:53 INFO]: Authors: Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

not

**Comment by MattBDev** [comment]
This is an issue with one of your other plugins that adds custom Biomes to the game. This is not an FAWE issue.
