### ISSUE TITLE
[BUG] //regen not working and crashing

### ISSUE THREAD

**Issue by yorik100** [IntellectualSites/FastAsyncWorldEdit#2275]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

//regen crashes the server for 2 mins and doesn't do anything at all

### To Reproduce

1. Select pos1
2. Select pos2
3. Do //regen
4. Server crashes for like 2 mins
5. //regen didn't do anything at all

### Expected behaviour

//regen working

### Error log (if applicable)

https://pastebin.com/b0WXDXb8

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d2592a4bbfe84cfbbb4f6bacbf33c916

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.3-SNAPSHOT-467

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Not an issue cased by FAWE, rather by hardware and missing optimization.
I suggest applying [Aikar's flags](https://docs.papermc.io/paper/aikars-flags) and increasing your memory to at least 6-10GB, as recommended by the Paper guide linked.

**Comment by yorik100** [comment]
> Not an issue cased by FAWE, rather by hardware and missing optimization. I suggest applying [Aikar's flags](https://docs.papermc.io/paper/aikars-flags) and increasing your memory to at least 6-10GB, as recommended by the Paper guide linked.

Tried, same result 1:1, using 6 GB, 10 or 15, still timing out.

**Comment by NotMyFault** [comment]
>  rather by hardware

The second most important factor, nor am I able to replicate the issue based on the information given.
