### ISSUE TITLE
deform failing

### ISSUE THREAD

**Issue by ItzSkyy** [IntellectualSites/FastAsyncWorldEdit#2281]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

During deform, it will only do 1/2 the deform and then abruptly stop/cancel.

Console states nothing

Chat says completed

### To Reproduce

//pos1 -2048,1,-1536
//pos2 2047,300,2047
//deform x/=1.5;y/=1.5;z/=1.5

### Expected behaviour

Complete deformation of selection to correct variables

### Screenshots / Videos

![failure](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/9542130/f944de49-2b60-4a46-a061-f517767056d6)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d3ab2dd1620a4669b3de2c1d3234257d

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.3-SNAPSHOT-471

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Could not reproduce it as well, this is more like a shortage of threads / purpur instead of paper issue. That selection even needs to be confirmed, it is too huge for a small server like that (it worked here great without "rifts").  If you take a smaller selection, it works fine.
