### ISSUE TITLE
Huge performance loss while setting spawners

### ISSUE THREAD

**Issue by OneLiteFeather** [IntellectualSites/FastAsyncWorldEdit#2284]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

You might want to overdo things, but somehow this is really broken and can lead to server crashes and world corruption.

### To Reproduce

1. Select two positions
2. //set spawner
3. wait and observe
4. You might notice huge fps drop with /tps

### Expected behaviour

They should be placed like in the past and no errors in log like this:

[06:19:06] [Server thread/INFO]: Seelenretterin issued server command: //pos1
[06:19:11] [Server thread/INFO]: Seelenretterin issued server command: //pos2
[06:19:21] [Server thread/INFO]: Seelenretterin issued server command: //set spawner
[06:19:21] [ForkJoinPool-7-worker-1/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightStarlightRelighterFactory as relighter factory.
[06:19:23] [Server thread/WARN]: Invalid SpawnData: No key entity in MapLike[{id:"minecraft:pig"}]
[06:19:23] [Server thread/WARN]: Invalid SpawnPotentials list: No key weight in MapLike[{Entity:{id:"minecraft:pig"},Weight:1}]; No key data in MapLike[{Entity:{id:"minecraft:pig"},Weight:1}]

### Screenshots / Videos

![grafik](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/77929075/b53acc79-858a-4be6-8fed-1d55f11581ef)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1b1d5e32bf38496f926d76938c578bba

### Fawe Version

FastAsyncWorldEdit-471

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Not entirely sure if the world might be broken but the error only happens after doing the reproduce.

**Comment by OneLiteFeather** [comment]
This I might add as well:
![grafik](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/77929075/5d82c902-0291-4309-8f98-7c334dad6f00)

Timings Report (deprecated):
https://timings.aikar.co/dev/?id=6c2719be605342a496673caef9775ec2#plugins

Spark tps after reconnect:
![grafik](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/77929075/049ae643-9243-4d29-a185-58f3d0bdbdee)

**Comment by dordsor21** [comment]
Tbh I think that that's just Minecraft spawner things, not sure there's much FAWE can do about it. Ticking blocks are automatically added to the server's tick list (in paper for certain, unsure about Spigot) when the ChunkSection is constructed by FAWE

**Comment by OneLiteFeather** [comment]
> Tbh I think that that's just Minecraft spawner things, not sure there's much FAWE can do about it. Ticking blocks are automatically added to the server's tick list (in paper for certain, unsure about Spigot) when the ChunkSection is constructed by FAWE

I think this problem is quite new and wasn't here till now. How to find out if this is on FAWE site?
