### ISSUE TITLE
Undo makes entities nearby like skulls/banners invisible

### ISSUE THREAD

**Issue by craftyfoxe** [IntellectualSites/FastAsyncWorldEdit#2287]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

When you undo, it makes entities in the same chunk such as skulls, banners invisible, until you left click it with the worldedit axe.
Even if you relog, only the blocks you left clicked with the axe will appear, rest stay invisible

### To Reproduce

1. place skulls down
2. //set 0 next to the skulls
3. //undo
4. see the skulls become invisible

### Expected behaviour

not to become invisible after undoing nearby.

### Screenshots / Videos

Video: https://www.youtube.com/watch?v=Kjcqp_0CSW8

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dde82712e49d429f82eae5ff30128155

### Fawe Version

2.6.3-SNAPSHOT-472;083f8a4

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by ShawnPR1** [comment]
Just want to +1 this, but for 1.20 paper as well.

The undo command makes nearby chests invisible.

Reloading chunks with F3+A makes them re-appear, but their contents are empty.

This was easy to replicate as I placed a bunch of items in a few double chests, set a few blocks to glass (about 10 blocks away from the chests) then undid the command, and the chests were empty afterwards.

**Comment by OneLiteFeather** [comment]
I can replicate both on 1.19.4 on FAWE 471 (Updating soon test server to 1.20 as well), the player head/banner thing appears as the tile entity is on the wall and you select the block that supports it and do the changes there. The chests needs to be selected as well which is a difference.
I suggest changing the name of the issue to include all tile entities as we are not 100% what is affected yet but it might happen on every tile entity
