### ISSUE TITLE
//setbiome action cancelled, outside safe edit region

### ISSUE THREAD

**Issue by mrfloris** [IntellectualSites/FastAsyncWorldEdit#2292]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

It looks like no matter what selection I made or region I select, the result is the same. With the message that //setbiome action cancelled, outside safe edit region, 30,000,000 .. 

Logging out and back into the game, and then checking with F3, the old biome type is still there.

### To Reproduce

/region info
/region select name
//setbiome plains

and/or

//pos1 
..move
//pos2
//setbiome plains

### Expected behaviour

For it to set the biome type to the selection.

### Screenshots / Videos

```
[15:04:28 INFO]: mrfloris issued server command: /region info
[15:04:33 INFO]: mrfloris issued server command: /region select shops
[15:04:42 INFO]: mrfloris issued server command: //setbiome cherry_grove
[15:04:54 INFO]: mrfloris issued server command: //setbiome plains
```
<img width="696" alt="Screen-Shot 2023-06-13 at 15 15 07" src="https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/28841349/ff0e8e8c-dde2-45d5-95ac-3dca14f1ce9a">

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2dc08154e2874d48a61430de51ad7286

### Fawe Version

FastAsyncWorldEdit version 2.6.4-SNAPSHOT-479;d9463ce

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

No msgs in the console besides the player running the command, there are no error msgs.

**Comment by Psheek** [comment]
![Capture](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/136540691/22bc4645-dd6f-46ec-858b-cdf7427ae852)
 I am having this issue too, no idea what to do, I can't use any commands

**Comment by mrfloris** [comment]
> ![Capture](https://user-images.githubusercontent.com/136540691/245649487-22bc4645-dd6f-46ec-858b-cdf7427ae852.PNG) I am having this issue too, no idea what to do, I can't use any commands

The msg above yours says it's completed, which might imply it's addressed. Make sure you have the latest FAWE build https://ci.athion.net/job/FastAsyncWorldEdit/
