### ISSUE TITLE
//undo doesnt work with //walls

### ISSUE THREAD

**Issue by EnvisagedMyron** [IntellectualSites/FastAsyncWorldEdit#2294]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

whenever i use //walls i cant use //undo to undo them so i have to manually delete them if i make an accident

### To Reproduce

1. make a selection
2. do //walls <any material>
3. do //undo

### Expected behaviour

//undo is supposed to undo the action of making the walls but instead it undoes the action before the //walls

### Error log (if applicable)

the console shows no error

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d6849345c9c24d1b8b437a866bd577ee

### Fawe Version

latest

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

nope have a nice day

**Comment by OneLiteFeather** [comment]
Looks like this error with this.extend is null should be fixed as well, the cache is broken here

**Comment by OneLiteFeather** [comment]
I am missing the startup log of the server, would be nice if you have it and post it here.

**Comment by RedstoneFuture** [comment]
We can replicate that. https://youtu.be/t9JFoBiP7dc
