### ISSUE TITLE
update #lighten and #darken

### ISSUE THREAD

**Issue by EnvisagedMyron** [IntellectualSites/FastAsyncWorldEdit#2295]
### What feature do you want to see added?

i want to see them use newer blocks because right now its 1.16 blocks

### Are there any alternatives?

no  i dont think there are any alternatives

### Anything else?

nope

**Comment by dordsor21** [comment]
Put a 1.20 minecraft jar file in the textures folder in the plugin config folder. The Minecraft jar is found in .minecraft/versions
