### ISSUE TITLE
Schematics will load but when i past them nothing will paste.

### ISSUE THREAD

**Issue by VibrantColours** [IntellectualSites/FastAsyncWorldEdit#2303]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

I transferred old schematics from a server, they were created using normal Worldedit. i know the files will work correctly as the smallest schematic will paste using normal Worldedit. However I need FAWE to paste the rest as they are quite large. when i try to load any schematics with it says the schematic was successfully loaded, but when i press paste literally nothing changes, there is no error on the console or anything. i am using fallout hosting as of rn.

### To Reproduce

1.) Go to the FAWE files and click on schematics
2.) Move any schematics into the schematic folder
3.) Go into the world and run the command //Schematic load "filename"
4.) Run the command //paste, but nothing will happen.

### Expected behaviour

when i ran //paste the schematic should've pasted into the world

### Screenshots / Videos

[2023-06-17 20-25-21.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/11780579/2023-06-17.20-25-21.zip)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2777d10daeb14cf39881cfac7273bda1

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-483.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Paper

**Comment by VibrantColours** [comment]
Paper is updated, it is at the newest version.
