### ISSUE TITLE
Not working on PaperMC 1.19

### ISSUE THREAD

**Issue by MicroshiftDev** [IntellectualSites/FastAsyncWorldEdit#2315]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

I have a problem on Minecraft PaperMC 1.19 server //set command not working I have latest version of FAWE Please help

### To Reproduce

You must have a server on paperMC 1.19 and java 17, select any area and enter the command //set (any block)
The error can be seen in the console

### Expected behaviour

I wanted to replace the sponge with two blocks with a nice paternen #simlex but I got an error other commands also do not work

### Screenshots / Videos

![2023-06-22_18 44 19](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/98481959/704ec13b-7347-4676-b6a3-131888f3122f)
![2023-06-22_18 59 17](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/98481959/ccf4dc0c-7e1d-4f2f-82e3-5179ac8f91f0)
![2023-06-22_18 59 21](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/98481959/35cf4844-23aa-4145-a941-3de2134f1db4)

### Error log (if applicable)

https://paste.gg/p/anonymous/65b9890db66642e48252ff18ab00a81e

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c0192ee66ee442ecb5398808ce182785

### Fawe Version

aFastAsyncWorldEditf version a2.6.4-SNAPSHOT-492;d961aa9

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I'm building a map on boxpvp and I need to make a nice floor but fawe won't work and the original world edit works perfectly

**Comment by NotMyFault** [comment]
Update Paper.

**Comment by MicroshiftDev** [comment]
Thanks, everything works now, I didn't expect the solution to be so simple
