### ISSUE TITLE
Extinguish command doesn't work

### ISSUE THREAD

**Issue by daniel-skopek** [IntellectualSites/FastAsyncWorldEdit#2317]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

If I use the //ex command, it says that 0 blocks of fire have been extinguished - while I am standing next to it

### To Reproduce

1. Find or make fire
2. Use //ex command
3. Nothing is extinguished

### Expected behaviour

It should extinguish the fire.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f5ed4075f06f490fb9f1854320f37cb3

### Fawe Version

FastAsyncWorldEdit version 2.6.4-SNAPSHOT-479;d9463ce

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Don't tick the checkboxes if you didn't go through them.
