### ISSUE TITLE
Allow '%' pattern to be used without not entirely necessary [] bracing

### ISSUE THREAD

**Issue by Bbro122** [IntellectualSites/FastAsyncWorldEdit#2321]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

While attempting to use the pattern "75%#simplex[5][cobblestone,andesite,mossy_cobblestone,cracked_stone_bricks],25%dirt" it will result in a bracket issue, despite the same pattern working without percents.

### To Reproduce

1. Run a command using the aforementioned pattern

### Expected behaviour

1. It runs as expected

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8dd3e9fd5ad44967954656f39a75a316

### Fawe Version

2.6.5-SNAPSHOT-502;903064f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
The correct format would be 75%#`[`simplex[5][cobblestone,andesite,mossy_cobblestone,cracked_stone_bricks]`]`,25%`[`dirt`]`
