### ISSUE TITLE
FAWE becomes unresponsive

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2332]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

This is the second day in a row I've had this issue so I thought I would report it since I was able to get a thread dump which should hopefully help. For some reason fawe stops working but I'm not sure what causes it, I'm unable to use /fawe threaddump or any worldedit related command. Using a worldedit command produces no feedback in chat. It's acting as if the plugin is stuck or something. In the log file I see an error but I'm not sure if it's related to this problem or not.

Log: https://pastebin.com/sEwHH4hD
Thread dump from visualvm: https://www.dropbox.com/s/xbccnbe8zoxv0gn/fawe%20commands%20not%20working.tdump?dl=1

### To Reproduce

1. Not sure

### Expected behaviour

WorldEdit commands should continue working

### Fawe Debugpaste

The fawe commands don't work when this happens so I'm unable to run this

### Fawe Version

https://ci.athion.net/job/FAWE-PS-v7/24

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Can you do a /fawe debugpaste after a restart or send us the beginning of the log so we can look deeper into it? @SecretlyJealous

**Comment by dordsor21** [comment]
Nah based on the threads there, it looks like There's a chunk taking a while to load (paper tings I guess, it seems to have forgotten about the chunk request), so if a brush is used a lot more afterwards, then the queue will completely block, preventing new submissions, and also preventing history from being written (assuming history db is enabled) causing the soft-"crash" of FAWE seen in this instance.

**Comment by OneLiteFeather** [comment]
Well then I guess this can be approved as a bug. Thank you for the explaination 👍

**Comment by SirYwell** [comment]
Did you by any chance unload the world where the FAWE action took place? Currently, this seems to be the only reason why the future wouldn't get completed.
