### ISSUE TITLE
//generate with wrong octaves value of perlin noise infinitely causes EvaluationException (maybe upstream issue)

### ISSUE THREAD

**Issue by Feniksovich** [IntellectualSites/FastAsyncWorldEdit#2335]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Using `//generate` with specific formula of perlin noise infinitely causes EvaluationException and nothing happens further.
As a result, sooner or later the server's `latest.log` will grow huge and exhaust the available container/OS storage quota.

### To Reproduce

1. Select a cuboid
2. Run `//generate light_blue perlin(1,x,y,z,3,0.3,0)>(y+0.2)*(1)` (where octaves = 0.3)
3. See infinite invocation of the EvaluationException in console (see error log)

### Expected behaviour

The corresponding noise map should be generated without exceptions.
User should be informed about incorrect specified parameters if any.

### Error log (if applicable)

https://paste.gg/p/anonymous/4db14a1eda5e4ebf9d1d2d6793d272a8

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/02951b14d0124d9baa7035207ba0ba1d

### Fawe Version

FastAsyncWorldEdit version 2.6.5-SNAPSHOT-510

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
This has been fixed
