### ISSUE TITLE
Internal error on paste schematic PaperMC

### ISSUE THREAD

**Issue by ElHacker1000** [IntellectualSites/FastAsyncWorldEdit#2344]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

It does nothing but show an error log in the console and in the chat

### To Reproduce

1. Load a schematic to the clipboard. All my tests were done with //schem loadall [schematic_name]
2. Paste the schematic.

### Expected behaviour

Have the world modified in such a way that the schematic would paste at the specified coordinates

### Error log (if applicable)

https://paste.gg/p/anonymous/7ef60a0a21af46d6a94c88bf9a0d05c3

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/55dcc640457140a1a9184b5e6f687dff

### Fawe Version

2.6.5-SNAPSHOT-517;68eb4e2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

This error can only be reproduced with PaperMC (Now that I've tried the latest build, I'm not sure about this statement). Switching to Spigot is not an option offered to me by the host.

The debugpaste tells me that I am with an outdated version. In addition, the provided link had visited it a few hours ago. I haven't checked the version name since "517", but I don't think an update has just come out.

**Comment by dordsor21** [comment]
Use a supported version (1.19.4). 1.19 is not supported any more.

**Comment by ElHacker1000** [comment]
Before deciding not to support recent versions, consider that there are people who cannot open versions higher than 1.19 nor can we always be with the latest version that they just released the day before.

**Comment by dordsor21** [comment]
There's literally no reason not to be able go update past 1.19... 1.19.4 released nearly 6 months ago. We support all minor versions for the latest major Minecraft version (1.20, 1.20.1 in the current case).
