### ISSUE TITLE
structure blocks to fawe?

### ISSUE THREAD

**Issue by Shadowfflare** [IntellectualSites/FastAsyncWorldEdit#2345]
### What feature do you want to see added?

hello i am setting up a server and i run into the issue that i always need to redo the terrain after i placed a schematic from the things i build early. i thought what if fawe had anything like structure blocks for schematics. what structure blocks do is placing the original block when a structure generate so u can find round structures for example

### Are there any alternatives?

the plugin betterstructures does it with barrier blocks but then i make a structure so its maybe worth it to check their code if this gets added

### Anything else?
hope on a fast respons 
best regards Shadowfflare

**Comment by SirYwell** [comment]
Do you have any scenario where a mask or a source mask aren't sufficient?

**Comment by 360shvit** [comment]
May just be //paste -a skipping air being pasted if terrain is the only issue

**Comment by dordsor21** [comment]
No response and pasting without air is the solution tbh

**Comment by Shadowfflare** [comment]
> May just be //paste -a skipping air being pasted if terrain is the only issue

this worked thx
