### ISSUE TITLE
FaweCache null pointer errors

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2348]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I'm not sure how serious these errors are but I thought I would report it anyway: https://pastebin.com/MMuP71dT and https://pastebin.com/da9WiqDz

### To Reproduce

1. Not sure

### Expected behaviour

No errors in console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/374855805e0a48ce97f64847c6e258c1

### Fawe Version

https://ci.athion.net/job/FAWE-PS-v7/25/

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Update to latest once built
