### ISSUE TITLE
/mask is ignored by brush

### ISSUE THREAD

**Issue by oxolotel** [IntellectualSites/FastAsyncWorldEdit#2350]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

When using a mask, with a brush, it seems like the mask is sometimes ignored. This does not seem to be limited to the >grass_block mask but effects at least a mask of 0 as well.

Using the brush sometimes places the grass correctly. So multiple tries might me necessary. In my testing it took a maximum of 10 attempts for it to fail. When using lapis_block it seems like it is more likely to fail.

Swapping the mask and the gmask yields a similar result as "/mask 0" is then ignored and existing blocks are replaced.

### To Reproduce

/br sphere tall_grass[half=lower] 5
/mask >grass_block
/gmask 0

OR

/br sphere lapis_block 5
/mask >grass_block
/gmask 0

Place blocks using the specified brush.

### Expected behaviour

Masks are respected when using a brush.

More specifically: Blocks are only placed on Grass Blocks and not above them.

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/48567305/f7d63bee-96a3-4cfc-a32e-9badb8daa53d)
![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/48567305/c048c560-1903-4fe3-a707-da4e62909c66)

### Fawe Debugpaste

 https://athion.net/ISPaster/paste/view/0bc378b6912947cfb0673488c33fd9b5

### Fawe Version

2.6.5_SNAPSHOT-521:0a19f64

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by 360shvit** [comment]
Its the gmask, mask combination. Fix until addressed would be to either //gmask 0&>[2] or //mask 0&>[2].
