### ISSUE TITLE
Cannot invoke "com.sk89q.worldedit.util.formatting.text.Component.children()" because "component" is null

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2352]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Got this error: https://pastebin.com/nE9YAr6n

### To Reproduce

1. Not sure but from the logs it looks related to /undo all ?

### Expected behaviour

No error

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/701d639ba1b240b2a58d3c1c97ae924b

### Fawe Version

https://ci.athion.net/job/FAWE-PS-v7/27/

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
FYI: "//undo all" will not undo all history, it will attempt to undo for the player "all"
