### ISSUE TITLE
Extreme freakout when rolling back history

### ISSUE THREAD

**Issue by Mirosinos** [IntellectualSites/FastAsyncWorldEdit#2366]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I inputted the command //history rollback -u (username hidden for privacy) -r 50 -t 12h and the server began to create odd chunks *everywhere* around the area.

![2023-07-18_15 56 14](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/139924486/c7bf37b8-5c8b-4bfd-bc85-91f16c7af959)
![2023-07-18_15 56 17](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/139924486/38a21886-b590-4512-a18f-27cc362ffc82)
![2023-07-18_15 56 13](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/139924486/8b1da7ee-e279-4c95-9323-cda20c0b4b75)

All of this goes underground and overground. It eventually crashed the server. The log for this is below.
[2023-07-18-2.log.gz](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/12089053/2023-07-18-2.log.gz)

### To Reproduce

//history rollback -u (username hidden for privacy) -r 50 -t 12h

//confirm

Watch your server crash.

### Expected behaviour

Roll back worldedits. Not... destroy everything.

### Screenshots / Videos

![2023-07-18_15 56 13](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/139924486/13d4b09a-aa17-428f-b6e0-bfc7992922a0)
![2023-07-18_15 56 14](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/139924486/2b412afb-b826-4531-868c-af1b1af13265)
![2023-07-18_15 56 17](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/139924486/69aac5dc-fb31-4e9a-a670-cbcbb02049bc)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/032b2e4cae1543bebc6defc88a2a9715

### Fawe Version

2.6.5-SNAPSHOT-522;a680c7c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
@Mirosinos 
We wrote together in fawe-support after it happened and I am thankful you opened this issue. I'll look into reproducing that in a few hours when my development infrastructure is operable again. 
Have you found that one log before latest I told you? It might be very useful to the developers and contributors. You can open that log file, copy the whole log and paste it into https://pastebin.com/ after hitting the green button "new" into that field below, save it and post the link here.
Make sure it's under "unlisted"
