### ISSUE TITLE
Cannot invoke "com.fastasyncworldedit.core.queue.IChunkGet.getBlock(int, int, int)" because "chunk.chunkExisting" is null

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2371]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I think gmask and a brush is causing this error? https://pastebin.com/DWX0sHHt and https://pastebin.com/p7f0Pb0m I'm not able to upload a debugpaste because I'm getting this error: "Failed to upload files: request must contain a file list"

I'm also seeing a lot of this in the console (I'm assuming it's related to a brush)
```
[18:56:47 WARN]: [com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent] java.lang.NullPointerException
[18:56:47 WARN]: [com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent] java.lang.NullPointerException
```

### To Reproduce

1. Not sure

### Expected behaviour

No errors in console

### Fawe Debugpaste

Failed to upload files: request must contain a file list

### Fawe Version

https://ci.athion.net/job/FAWE-PS-v7/29/

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Try with the latest v7 branch version
