### ISSUE TITLE
Cannot invoke "java.nio.MappedByteBuffer.getChar(int)" because "this.byteBuffer" is null

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2376]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Getting this error in console: https://pastebin.com/L3QCFChm

### To Reproduce

1. Not sure

### Expected behaviour

No errors

### Fawe Debugpaste

Failed to upload files: request must contain a file list

### Fawe Version

https://ci.athion.net/job/FAWE-PS-v7/31/

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
I still don't know how you manage to get this, but it could be useful to adress that as seen in other of your issues. "Failed to upload files: request must contain a file list" 
In addition, can you update FAWE, there is already a new release and shapshot. Tell us if you still have the errors after updating
https://ci.athion.net/job/FastAsyncWorldEdit/

**Comment by dordsor21** [comment]
This occurs when the clipboard is changed after the brush is loaded iirc

**Comment by dordsor21** [comment]
Unless it's something else (doubtful, looking at the logs), duplicate of #2376
