### ISSUE TITLE
Using worldedit near containers clears its inventory leading to losing all the items inside.

### ISSUE THREAD

**Issue by hahahaLdawdadd** [IntellectualSites/FastAsyncWorldEdit#2378]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Whenever I use FAWE near ANY container (Chest, Shulker box, Furnace) it clears its inventory even If I undo/redo the operation. (I'm using it on aternos server)

### To Reproduce

1. Go to a Paper Sever with FAWE using version 1.20.1
2. For Example, build a cactus farm using hoppers to store the produced cacti in chests (set RandomTickSpeed to a higher number so it's producing the cacti faster
3. Copy the farm and paste it next to the original one/change blocks around the farm using //sphere and //mask
4. Check the items inside the container (it should be empty)

### Expected behaviour

Using FAWE around containers keep the containers inventory as it was before using FAWE

### Fawe Debugpaste

-

### Fawe Version

FastAsyncWorldEdit version 2.6.3

### Checklist

- [ ] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Update
