### ISSUE TITLE
FastAscynWorldEdit Use Inventory Doesn't Work

### ISSUE THREAD

**Issue by michael-b-jordan** [IntellectualSites/FastAsyncWorldEdit#2381]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

The use inventory option in FastAscynWorldEdit does not work.

### To Reproduce

1. Enable Use Inventory
2. WorldEdit does not use blocks from inventory

### Expected behaviour

WorldEdit uses blocks from inventory

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/fe302548294a4cbfbcc6cf0ac886b986

### Fawe Version

2.6.5-SNAPSHOT-506;a0acbc7

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Your platform used does not match the platform selected on the issue, making this issue invalid. Additionally, please provide a comprehensive list of steps to replicate the issue, "does not work" is extremely hard to debug.
