### ISSUE TITLE
Add timeout for update checking on startup

### ISSUE THREAD

**Issue by noiverre** [IntellectualSites/FastAsyncWorldEdit#2384]
### What feature do you want to see added?

Add timeout for update checking on startup, preferably 5 minutes

On 29/07/2023 ~00:00(?) UTC+7, FAWE ci.athion server is down, resulting in FAWE making the server stall while waiting for FAWE update request, so I had to kill it, disabling update-notifications in config.yml, and restarting the server

### Are there any alternatives?

Manually turning off update notifications should fix this issue, but I think the root problem isn't solved

### Anything else?

None

**Comment by NotMyFault** [comment]
That does already exist since https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2331/, make sure you're using an up to date version of FAWE.
