### ISSUE TITLE
Edits seemingly randomly stop working in newer 2.7.x

### ISSUE THREAD

**Issue by MrJoshuaT** [IntellectualSites/FastAsyncWorldEdit#2388]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Edits will get stuck forever, for only some people though even when others do the same selection and commands. 
Tested on;
* FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-542.jar
* FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-538.jar
* FastAsyncWorldEdit-Bukkit-2.7.0.jar

When a person has a stuck edit, `//cancel` will always say `Cancelled 1 edits` forever even if sent multiple times. To confirm also `/fawe version` doesn't return anything either for the person with the stuck edit

When moving back to `FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar` the edits work as expected

### To Reproduce

1. Start server
2. Place a few diamonds blocks in a line, so they have neighbouring sand
3. Do `//gmask ~57`
4. Do `//replace sand redstone_block`
5. Some people will get a stuck edit command. `//cancel` doesn't cancel. Doing `//pos1` again doesn't respond

### Expected behaviour

Edits to not get stuck in v2.7.x

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/1721365/ba748dcf-bb3b-40c1-82d1-7a57f98a2651)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0f28606384df4ad897191e425f45570a

### Fawe Version

FastAsyncWorldEdit version 2.6.4-SNAPSHOT-481;51e238c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

There isn't much to go off. I could never get it to happen to me, but someone else always had it happen.

**Comment by dordsor21** [comment]
542 doesn't exist yet and the debugpaste is 481. Could you clarify the versions you tested with there?

**Comment by MrJoshuaT** [comment]
Ah that would be my bad, I typed the wrong versions. The versions I tried were:
* FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-538.jar
* FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-536.jar
* FastAsyncWorldEdit-Bukkit-2.7.0.jar

Then worked on FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar

**Comment by MrJoshuaT** [comment]
Just tried latest version `FastAsyncWorldEdit-Bukkit-2.7.1-SNAPSHOT-543.jar` and still happens. I've confirmed it's broken for the user. For them it stopped responding after doing `//gmask /0d;45d` and `//replace stone gold_block`. Running `/fawe version` doesn't respond as before, and doing `//cancel` says 1 edit cancelled but doesn't do anything.

This seems to hint that the max block checks is possibly kicking in but it's recursively retrying.

At this point, it's still working for every other user.

**Comment by OneLiteFeather** [comment]
Hello there, I have tested it with 1.20.1 Paper and FastAsyncWorldEdit-2.7.2-555 and the error did not occur, it worked fine. Maybe there is more information needed for replicating it or it was fixed in this version.

Can you retry it with the latest version @MrJoshuaT ?

**Comment by OneLiteFeather** [comment]
We were pointing out that it might be thread related as it always happen for one player but not for the others on his server with non op and basic perm permission with default configuration but restrictions set to false so that the first command can be run. It might be related to Pterodactyl as well, so extern configuration. 

If run locally, this issue also can't be replicated by @MrJoshuaT and also can't be on my test server.

**Comment by OneLiteFeather** [comment]
@IntellectualSites/core-team it worked on 2.6.x versions but not for him anymore but also for me it works. Can anyone figure out when there was a change regarding threading or race conditions?
