### ISSUE TITLE
Moving objects a certain distance leads to disfiguration

### ISSUE THREAD

**Issue by thomasmny** [IntellectualSites/FastAsyncWorldEdit#2394]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

After defining an area using `//pos1` and `//pos2`, any `//move` action with a value above **20** will result in the destruction of the selected area. It appears that the command functions as if the object is being stacked instead of moved.

### To Reproduce

1. Create an object (e.g. with `//br s stone 100`)
2. Move the object 50 blocks away (`//move 50`)
3. Observe that the object is disfigured
4. Undo the move (//undo)
5. Move the object 15 blocks away
6. Observe that the object was moved normally

### Expected behaviour

The object to be moved in the same way as `//move <20`

### Screenshots / Videos

https://youtu.be/MxpXE4-B5gI

### Error log (if applicable)

None

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/686b1015adf743b280c0d985b6549e03

### Fawe Version

2.7.1-SNAPSHOT-545;50e45f0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by thomasmny** [comment]
It seems that only moving along the Z coordinate is not possible. To the east and west works fine without problems

**Comment by SirYwell** [comment]
I'm not able to reproduce this

**Comment by thomasmny** [comment]
We stopped the server, deleted the config and used a fresh one. Now everything works fine
