### ISSUE TITLE
Original entity will not be generated after undo

### ISSUE THREAD

**Issue by GsTio86** [IntellectualSites/FastAsyncWorldEdit#2398]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

Original entity will not be generated after undo

### To Reproduce

1.First place the entity (armor stand/item frame)
2.Load a scheme with entities, my demo is an invisible item frame
3.Then use //paste -e to paste
4.Then execute //undo

### Expected behaviour

Tthe original entity will be regenerated under normal circumstances, but it does not

### Screenshots / Videos

https://gyazo.com/c003674f49fbae763de8ccad91402f9f

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/12329f2f5a7943bf8a596b8622dee9ee

### Fawe Version

2.7.1-SNAPSHOT

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
arclight-1.16.5-1.0.26-SNAPSHOT-15f6e1b9 (MC: 1.16.5)
That is legacy and not Paper / Spigot
Please use 1.17.1 or higher along with Paper to ensure that FAWE can work as supposed
