### ISSUE TITLE
Operation in a chunk that contains a Polygonal Worldguard region not working

### ISSUE THREAD

**Issue by mAxYoLo01** [IntellectualSites/FastAsyncWorldEdit#2399]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Operations such as //set that are done on multiple chunks will not be done on a chunk if it also contains a polygonal Worldguard region that the user is not a part of.
![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/19358286/372867eb-aa14-4b81-b305-c02575d3f232)
In image above, gold blocks are the chunk boundary, diamond blocks represent the polygonal region border and the emerald blocks the region that should be modified (`//set emerald_block`). As you can see, only one chunk is actually modified

### To Reproduce

1. Create a polygonal Worldguard region
2. Set passthrough flag to deny, so that the user can NOT build/use operations in it
3. Create a FAWE region that covers a chunk where the WG region is in
4. Execute a FAWE operation such as //set

### Expected behaviour

The entire FAWE region should be filled with emerald blocks since none of these blocks actually are in the WG region

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/19358286/372867eb-aa14-4b81-b305-c02575d3f232)

### Error log (if applicable)

None

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f9970cde39c2424fa9dcba07a40ca954

### Fawe Version

FastAsyncWorldEdit-2.7.1-SNAPSHOT-545

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Bug very similar to #2258, #2265, #2268, except here the issue is when a user is NOT member of a region

**Comment by dordsor21** [comment]
Is this still an issue?

**Comment by mAxYoLo01** [comment]
To my knowledge yes this has not changed.
