### ISSUE TITLE
[bug] Problem with Plotsquared + FAWE

### ISSUE THREAD

**Issue by Luke2206** [IntellectualSites/FastAsyncWorldEdit#2411]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I found out through a player report that you can use //brush and //tree on plot roads without permission and thus destroy the road.

Please see the video for more details

### To Reproduce

1. Minecraft server with fawe + Plotsquared
2. get //wand
3. type //brush smooth    or   //brush tree | //tree 
4. edit the border of ur plot  or place tree at the plotborder
5. Plot road = bummed

### Expected behaviour

I guess you shouldn't be able to edit the road.

### Screenshots / Videos

too large for github -> https://youtu.be/i2AoaYnvKVg

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7c910c00a7fc4fa6859a0215ce378387

### Fawe Version

FastAsyncWorldEdit-2.7.2-SNAPSHOT-552

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Using the following setup, I'm unable to replicate the issue: https://athion.net/ISPaster/paste/view/3a9419d801be40a29b97dfdf59ecac3b

![Screenshot 2023-09-01 at 10 30 05](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/13383509/51e329c1-373a-497d-bf8c-1658953dbf1f)

Commonly, this is the case when the user inherits permission they shan't have. In my case, trees are cut off properly on the plot edge.

**Comment by Luke2206** [comment]
After a config reset, it works without problems. 
still many thanks
