### ISSUE TITLE
Copying villagers in minecard using //copy -e and pasting them using //paste -e pastes the minecart, but not the villager.

### ISSUE THREAD

**Issue by SfSuralias** [IntellectualSites/FastAsyncWorldEdit#2417]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

If you have a villager in a minecart in a region that you are copying with //copy -e and you copy it and paste it with //paste -e the minecart appears, but it doesn't have the villager inside of it.

### To Reproduce

1. Place a minecart on a circular minecart track so that you can easily capture a villager in it.
2. Spawn a villager in the center of the minecart track while the minecart is going in circles to capture the villager.
3. Once the villager is in the minecart, make a region selection around the villager in the minecart.
4. Copy the villager in the minecart using //copy -e
5. Move to another location and paste the villager in the minecart using //paste -e

You will now have an empty minecart with no villager inside of it.

### Expected behaviour

The expected behavior would be to have the same villager inside the minecart upon doing //paste -e

### Error log (if applicable)

https://pastebin.com/wG3tkNN4

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/fc566ed6c0e6446380b3baf4def45cd2

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-555

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
#2427 might be related because of passengers

**Comment by dordsor21** [comment]
closing in favour of #2427
