### ISSUE TITLE
Lighting breaks

### ISSUE THREAD

**Issue by Wyndolinn** [IntellectualSites/FastAsyncWorldEdit#2418]
### Server Implementation

Spigot

### Server Version

1.20.1

### Describe the bug

When using the commands //replace, //set, etc., the lighting will break.  I think this is due to block updates
Broken light remains broken even after updating illuminated blocks and restarting the server

### To Reproduce

1. Select region
2. Use //set 0 command
3. Blocks update and break lighting

### Expected behaviour

It is necessary that the lighting does not break

### Screenshots / Videos

![2023-09-05_23 07 07](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/57833168/83b73473-ff1f-47cc-a222-ce208f3b1eab)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2eb29598dfd04a52a595417048c3b554

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-555

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
I'd recommend you to use Paper instead.

**Comment by OneLiteFeather** [comment]
There is in the fawe / worldedit config a part where you can say which lighting mode you want to use so that the light errors are less happening. It might take a little more performance but it might help as well.

**Comment by Wyndolinn** [comment]
> 

This unfortunately doesn't solve the problem completely. 

I changed the lighting mode to 2 and now the blocks that emit light leave this light behind them even when they are broken or upgraded by placing other blocks nearby

**Comment by OneLiteFeather** [comment]
You could also try /paper fixlight if you change from spigot to paper. Paper is recommended for FAWE and also your plugins should still work then.
