### ISSUE TITLE
Error with FAWE

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [IntellectualSites/FastAsyncWorldEdit#2424]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Could not dispatch event: com.sk89q.worldedit.event.extent.EditSessionEvent@c92d2bc to handler EventHandler{priority=VERY_EARLY}

error in console
https://paste.gg/p/anonymous/5d9cb1ead5e34192a82233068d927532

### To Reproduce

/up 1

### Expected behaviour

Commands work normally, but spam the console

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/68572049/2435d9d9-be71-4348-a150-ab166ffd2a08)

### Error log (if applicable)

https://paste.gg/p/anonymous/5d9cb1ead5e34192a82233068d927532

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/19a269a586664272affa03d6e5995395

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-557

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Well I can't reproduce that on git-Paper-176 (MC: 1.20.1) latest and the latest FAWE. It might be related to your FAWERestrictions plugin or to pufferfish.
Also it would be good to see the startup log where FAWE and FAWERestrictions is loaded and enabled @Sh3r1ffCZ

**Comment by Sh3r1ffCZ** [comment]
Here you can see the full log + today's errors

https://paste.gg/p/anonymous/fa83e77426544c5e809561e4a4e539c9

**Comment by OneLiteFeather** [comment]
Please use Paper instead of Pufferfish as Paper is recommended for FAWE.
