### ISSUE TITLE
sweet_berry_bush name

### ISSUE THREAD

**Issue by LucasT-dev** [IntellectualSites/FastAsyncWorldEdit#2428]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Change the name of "sweet_berry_bush" to "sweet_berry_bush" to match the name given by mojang
This poses some problems when using the API

### To Reproduce

//set sweet_berries

/setblock 0 0 0 minecraft:sweet_berry_bush

### Expected behaviour

//set sweet_berry_bush

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/332cc6ebf5494eaf9fdaffcee828be3a

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.7.2-SNAPSHOT-560

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
I don't understand this issue. The block id is `sweet_berry_bush` and this is also the value that is accepted by FAWE.
What exactly is the problem here?

**Comment by LucasT-dev** [comment]
I'm sorry, but in fact the problem doesn't come from Minecraft,

The item in the hand is sweet_berries

But by placing it it turns into a block and becomes: SWEET_BERRIES_BUSH

So when I get the item in my hand and it is a sweet berry I get an error.

Whereas when I use SWEET_BERRIES_BUSH I have no problems.

![CaptureSWEET](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/90644350/89897880-3ee4-4ec5-a8b3-ecce49aabd4e)


![2023-09-18_20 58 03](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/90644350/3c5739e4-7cf6-4638-b604-b847c1ad3fe8)

**Comment by SirYwell** [comment]
Items aren't blocks. This is handled terribly in Spigot but not an issue with FAWE.

Spigot will also prevent you from creating a BlockData object (the equivalent of BlockState) for items: `Material.SWEET_BERRIES.createBlockData()` throws an exception.

By the way, there is no 1 to 1 mapping of items to blocks. For example an `oak_sign` item can be, when placed, either result in an `oak_sign` block or an `oak_wall_sign` block. Another example: spawn eggs, they don't have any associated block type at all!

I don't know if Spigot exposes a way to simulate placing an item to get the resulting block state, but this is out of scope of this bug tracker, so you'll need to ask somewhere else.
