### ISSUE TITLE
Error on console java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]:

### ISSUE THREAD

**Issue by Bossbirdyman51** [IntellectualSites/FastAsyncWorldEdit#2432]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Hi,

I have this error on my server on launch :

https://pastebin.com/JEUbC19E

### To Reproduce

I have plugin Iris for World Gen, and now my biome was cherry

### Expected behaviour

They probably change my chunk with another biome

### Error log (if applicable)

https://pastebin.com/JEUbC19E

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4c8cf5bbf0b84f36b402e4ef31da6f38

### Fawe Version

2.7.2-SNAPSHOT-560;7b0f1b3

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Why do you think this has anything to do with FAWE, when there's no such indicator.
`Invalid key. Must be [a-z0-9/._-]:` is part of a validity check within the source code of the minecraft server itself: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/NamespacedKey.java#114
