### ISSUE TITLE
//regen throws an error when trying to regen terrain

### ISSUE THREAD

**Issue by CortezJEL** [IntellectualSites/FastAsyncWorldEdit#2454]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

//regen throws an error when trying to regen terrain

### To Reproduce

make a selection, type //regen

### Expected behaviour

regenerate the chunks in the region

### Error log (if applicable)

https://paste.gg/p/anonymous/4b5fe125e44c4875b5c6538d4dd417ee

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a2b459a76336413aa1632281c5a0edaa

### Fawe Version

FastAsyncWorldEdit version 2.8.2-SNAPSHOT-581;186d24b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Paper, you are ~4 months out of date.

You can use `/version` to check how many versions you are behind.
