### ISSUE TITLE
Brush paint command

### ISSUE THREAD

**Issue by etcroot** [IntellectualSites/FastAsyncWorldEdit#2455]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Running the command 
`//brush paint cyl 2 set 40%dirt_path,20%dirt,20%coarse_dirt,10%podzol`
Returns an error in the console and won't let you use the paint brush.

### To Reproduce

**Command**:
`//brush paint cyl 2 set 40%dirt_path,20%dirt,20%coarse_dirt,10%podzol`

### Expected behaviour

Expected behaviour would be that the tool becomes a brush that allows you to paint on surfaces.

### Screenshots / Videos

[Youtube Video](https://www.youtube.com/watch?v=p0sauSlhKxc)

### Error log (if applicable)

https://paste.gg/p/anonymous/31fad4af27044fc78c8ecb1cd6fc558c

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1675468a414346568e5cee39ff86f241

### Fawe Version

2.8.1;639e956

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I ticked the "I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists." but I'm on 1.20.1 due to my server needing to be on that, so I'm using the latest build for that version.

**Comment by NotMyFault** [comment]
> > > I ticked the "I am using the newest build from [ci.athion.net/job/FastAsyncWorldEdit](https://ci.athion.net/job/FastAsyncWorldEdit/) and the issue still persists." but I'm on 1.20.1 due to my server needing to be on that, so I'm using the latest build for that version.
> > 
> > 
> > I'm unable to replicate the issue using a maintained build of Paper on 1.20.2, given Paper dropped support for 1.20.1, try to replicate the issue once you update.
> 
> I have updated to the latest version now `2.8.2-SNAPSHOT-581;186d24b` still getting the same error.

I didn't mean your FAWE version but your Paper version. 1.20.1 will not receive any updates by Paper anymore and I'm unable to replicate the issue on 1.20.2

**Comment by PierreSchwang** [comment]
> > > > > I ticked the "I am using the newest build from [ci.athion.net/job/FastAsyncWorldEdit](https://ci.athion.net/job/FastAsyncWorldEdit/) and the issue still persists." but I'm on 1.20.1 due to my server needing to be on that, so I'm using the latest build for that version.
> 
> > > > 
> 
> > > > 
> 
> > > > I'm unable to replicate the issue using a maintained build of Paper on 1.20.2, given Paper dropped support for 1.20.1, try to replicate the issue once you update.
> 
> > > 
> 
> > > 
> 
> > > I have updated to the latest version now `2.8.2-SNAPSHOT-581;186d24b` still getting the same error.
> 
> > 
> 
> > I didn't mean your FAWE version but your Paper version. 1.20.1 will not receive any updates by Paper anymore and I'm unable to replicate the issue on 1.20.2
> 
> 
> 
> Ah, so I'm forced to update to 1.20.2 in this case? Because there's certain features in that update I don't want on my server :/

1.20.2 literally adds the /random command as well as reworked villager trading (which has to be enabled manually as that is still experimental) alongside bugfixes. There is no reason to not update nor is there any feature you wouldn't have on 1.20.1

**Comment by etcroot** [comment]
> > > > > > I ticked the "I am using the newest build from [ci.athion.net/job/FastAsyncWorldEdit](https://ci.athion.net/job/FastAsyncWorldEdit/) and the issue still persists." but I'm on 1.20.1 due to my server needing to be on that, so I'm using the latest build for that version.
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > I'm unable to replicate the issue using a maintained build of Paper on 1.20.2, given Paper dropped support for 1.20.1, try to replicate the issue once you update.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I have updated to the latest version now `2.8.2-SNAPSHOT-581;186d24b` still getting the same error.
> > 
> > 
> > > 
> > 
> > 
> > > I didn't mean your FAWE version but your Paper version. 1.20.1 will not receive any updates by Paper anymore and I'm unable to replicate the issue on 1.20.2
> > 
> > 
> > Ah, so I'm forced to update to 1.20.2 in this case? Because there's certain features in that update I don't want on my server :/
> 
> 1.20.2 literally adds the /random command as well as reworked villager trading (which has to be enabled manually as that is still experimental) alongside bugfixes. There is no reason to not update nor is there any feature you wouldn't have on 1.20.1

I updated to 1.20.2, it broke nearly all of my plugins + the initial command that i started this thread with still throws the same error.

New paste: https://athion.net/ISPaster/paste/view/f4718221db574df887be3d075bcf2827
