### ISSUE TITLE
InvocationTargetException at //set

### ISSUE THREAD

**Issue by StarryCamile** [IntellectualSites/FastAsyncWorldEdit#2460]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

![图片](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/123795586/81842e05-9777-4b4d-8272-6ce98e4167bc)
like this image, throw error when i use //set command

### To Reproduce

1.Select a area
2.//set <any block>

### Expected behaviour

Have error when //set

### Screenshots / Videos

![图片](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/123795586/fa90b50d-48d6-41fb-98d9-7938acfd823c)

### Error log (if applicable)

https://gist.github.com/StarryCamile/dfb3fcc6fdd12af73ad7a1793eaa97ca

### Fawe Debugpaste

 https://athion.net/ISPaster/paste/view/30f47f2e79d54e7293962647e90c240a

### Fawe Version

2.6.4

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by StarryCamile** [comment]
hmmm, i added this Class in ****config.yml****

**Comment by dordsor21** [comment]
Update FAWE. Your version does not support 1.20.2.........
