### ISSUE TITLE
low priority bug : /p generatebiome can spawn water on roads

### ISSUE THREAD

**Issue by TsCode1** [IntellectualSites/FastAsyncWorldEdit#248]
**Description of the problem:**  https://hastebin.com/ebiyodelom
/plot generatebiome mutated_savanna_rock sometimes generates water on top of road

**How to replicate:** 
/p generatebiome mutated_savanna_rock multiple times

**Checklist**:

- [x] I included a `/plot debugpaste` link 
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by leviem1** [comment]
Can confirm. Test by placing water block near road next to default half-slab sandstone borders. Water cascades over. The water physics aren't updating after the source block is placed. I have players who have surrounded their plots with water.

**Comment by leviem1** [comment]
Can someone just check if this is an easy fix or something more involved? I totally understand not working on this if it requires a larger rework, but I think it's worth investigating.

**Comment by IronApollo** [comment]
I am confused with the issue. Is it an issue with PlotSquared's handling of liquid flow, or is it an issue with FAWE placing blocks outside of the plot boundaries?

**Comment by leviem1** [comment]
I think it's PS. Place water inside a plot near the half-slab border and it will flow onto the main road. Might be how FAWE is handling it, but that's why I think it should be looked into. I haven't looked into this in a while, but will try to reconfirm today and attach images

**Comment by leviem1** [comment]
So, from what I can remember, players placed water on the border, and something like this happened. I deopped myself for this test/screenshot, but I may still have some additional LuckPerms permissions. Nonetheless this was reported by a player who didn't have any extra permissions. 

It'd be nice if someone else could at check if this affects them to make sure I'm not just doing something wrong with permissions.

![2021-04-16_09 00 04](https://user-images.githubusercontent.com/6848225/115043948-4251c100-9e92-11eb-8642-5cba6c101e34.png)
