### ISSUE TITLE
Offset mask does not work reliable with `//br s`

### ISSUE THREAD

**Issue by thomasmny** [IntellectualSites/FastAsyncWorldEdit#2485]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

Using the offset mask with a sphere brush only seems to work around 50% of the time

![2023-11-03_09 58 16](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/29168243/060be1fd-f313-4483-a61e-3388d2eb54cb)

### To Reproduce

In this example I'm using red tulips, but it also happens with other blocks
1. `//br s red_tulip 3`
2. `/mask >water`
3. `/gmask 0`

Using the brush (sometimes) leads to semi-spheres of roses:
![2023-11-03_09 52 36](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/29168243/b9885f80-ce77-438e-9f07-325017c986af)

### Expected behaviour

All roses should be flat

![2023-11-03_09 52 25](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/29168243/f1dadb29-1a32-4c5a-b1cd-fe05db4f8b8c)

### Error log (if applicable)

None

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f05eb4e1d79448d39852ce8b03c740cb

### Fawe Version

FastAsyncWorldEdit 2.8.2-SNAPSHOT-602;8e2691c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Is this still an issue?

**Comment by thomasmny** [comment]
I can still reproduce it using the lastest Paper & FAWE versions. 

However, after further testing I think I have found the cause of the issue:
Since the water is only 1 block deep, whenever I aim at it from further away, the targeted block seems to be the dirt below. Therefore a semi-sphere is placed:
<img width="1512" alt="Screenshot 2024-03-18 at 11 23 25" src="https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/29168243/54e4b995-bf40-46bd-8817-23e14e3d515a">

On the other hand, when I'm standing in the water itself the roses are flat
<img width="1512" alt="Screenshot 2024-03-18 at 11 14 21" src="https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/29168243/158004a4-4d43-4adf-870c-5c6c814085f9">

Is this behaviour intended?

**Comment by SirYwell** [comment]
Might also be related to #2546?
