### ISSUE TITLE
java.lang.IllegalStateException: Copy key already used.

### ISSUE THREAD

**Issue by DeadMaster121** [IntellectualSites/FastAsyncWorldEdit#2486]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

When using the FAWE's API, attempting to do a edit causes a "Copy key already used".

This recent commit seems to be causing it: https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2461/commits/0b321ba3fd42eb86852aafbcb82722bd3781e280#diff-8259dd003f4dff384965cf85a6fa2519f2f048c6cfb1bfb5b7d9d3958f520d17R420

### To Reproduce

```java
        try (EditSession editSession = WorldEdit.getInstance().newEditSessionBuilder().world(BukkitAdapter.adapt(brokenBlockLocation.getWorld()))
                .fastMode(true)
                .changeSetNull()
                .relightMode(RelightMode.NONE)
                .limitUnlimited()
                .build()) {

            for (Block block : getExplosion(brokenBlockLocation, brokenBlockLocation.getWorld(), rage ? ++level : level)) {
                if (!(canBreak(block))) continue;
                final Material materialType = block.getType();

                minedAmount++;
                tokenBlock(player, pickaxe, block, materialType);
                editSession.setBlock(block.getX(), block.getY(), block.getZ(), BlockTypes.AIR);
            }
            Operations.complete(editSession.commit());
```

### Expected behaviour

No error & editSession's operation should complete successfully

### Error log (if applicable)

https://paste.gg/p/anonymous/53e13038fb2245159fd5694db44b3229

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f49503af38674ee0923deb4460b11efe

### Fawe Version

FastAsyncWorldEdit version 2.8.2-SNAPSHOT-602;8e2691c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Try running the task async for now

**Comment by zingeer** [comment]
async task not work

**Comment by OneLiteFeather** [comment]
There is a fix merged regarding this error 2 days ago, so I guess it won't happen with the Api anymore too

**Comment by OneLiteFeather** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2567
