### ISSUE TITLE
AutoCleanUp - Residence regen with FAWE

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [IntellectualSites/FastAsyncWorldEdit#2487]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Hello, I'm currently solving a problem with the automatic regeneration of residences https://github.com/Zrips/Residence/issues/1112.

The residential plugin says that regeneration is in progress:
"01:57:36] [Server thread/INFO]: [Residence] Auto-cleaning is starting (3163/1568)!
[01:57:36] [Server thread/INFO].
[01:57:36] [Server thread/INFO]: I'm using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightStarlightRelighterFactory as a lighter factory.
[01:57:44] [Server thread/INFO].
[01:57:44] [Server thread/INFO].
[01:58:31] [Server thread/INFO]: [Residences] Auto-cleaning deleted 8 residences!"

It's supposed to delete and regenerate residences. However, when the server is turned on, an error pops up, see the log https://paste.gg/p/anonymous/f6332547f61b4d22b76b89b7500f9280.
The server then immediately starts up again, but the residences are already deleted, but the regeneration did not take place.

I tried "WorldEdit" on the server and the server loaded and regenerated the old residences successfully. Is it possible to look for possible errors with FAWE? Thank you

### To Reproduce

Start server with AutoCleanUp and Regenerate: true

### Expected behaviour

Older residences should be deleted and regenerated. Which is when the server crashes, so after power up the residences are deleted but not regenerated.

### Error log (if applicable)

https://paste.gg/p/anonymous/f6332547f61b4d22b76b89b7500f9280

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1963e4f55a0540f592ff2a4d25e2402c

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.8.2-SNAPSHOT

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I also tried the latest version, but unfortunately the problem still persists.
FastAsyncWorldEdit-Bukkit-2.8.3-SNAPSHOT-605.jar

**Comment by OneLiteFeather** [comment]
It is not clear if FAWE does the crash after a start. Can you try it with only FAWE and Residence?

**Comment by Sh3r1ffCZ** [comment]
I'll test it, but I'll have to create residences on the test server and have them automatically regenerated the next day.

**Comment by Sh3r1ffCZ** [comment]
> It is not clear if FAWE does the crash after a start. Can you try it with only FAWE and Residence?

Finally I was able to test it on my test server, where I added only the necessary plugins.
I created around 30 residences and had them automatically deleted and regenerated. However, the problem occurred again, the ress were deleted, the server crashed, but unfortunately the region was not regenerated.

Log: https://paste.gg/p/anonymous/9d22fa9829104d15a0bd7097c3729f19

Versions:
FastAsyncWorldEdit-Bukkit-2.8.2-SNAPSHOT (I've also tried the latest builds)
Residence5.1.4.0

**Comment by SirYwell** [comment]
It looks like Residence is trying to use FAWE before the server is fully started. That might be an issue, but I also see anything regarding FAWE in the stack traces. Can you test with Paper instead of Pufferfish?

**Comment by Sh3r1ffCZ** [comment]
Paper version git-Paper-196 (MC: 1.20.1)
Log: https://paste.gg/p/anonymous/d530231b600c4c4e97b41385a653257a
Same problem

**Comment by SirYwell** [comment]
Looking into Residence a bit, that definitely looks like an issue caused by improper use of the WorldEdit API on their end.

**Comment by Sh3r1ffCZ** [comment]
I created a ticket on their github as well and attached this one (2487). I'm hoping or wishing that the problem could be solved though it is unfortunately like this through 2 plugins.
