### ISSUE TITLE
FAWE not pasting schem files

### ISSUE THREAD

**Issue by revvyys** [IntellectualSites/FastAsyncWorldEdit#2492]
### Server Implementation

Spigot

### Server Version

1.20.2

### Describe the bug

We updated to the newest snapshot and schem files stopped pasting, I went back to the old version to test it and still nothing.

This is the command used 
//schematic load schem url:addce903-46af-433a-8951-2b1811dbd913

### To Reproduce

Pasted logs below

### Expected behaviour

For the schematic to paste in

### Error log (if applicable)

https://pastebin.com/YpWv4vMa

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c15b0c29342641eeb4332cc1c7fbcbf0

### Fawe Version

Newest Snapshot

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
I suspect this is a 1.20.1 specific issue, I can't reproduce it on 1.20.2. Can you recheck if that's the case @revvyys?

**Comment by bumpyJake** [comment]
Can confirm on 1.20.1

**Comment by NotMyFault** [comment]
No response, assume no longer relevant.
