### ISSUE TITLE
Use renovate to keep paperweight versions up to date

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#2498]
Instead of updating the paperweight versions in https://github.com/IntellectualSites/FastAsyncWorldEdit/tree/main/worldedit-bukkit/adapters manually, it would make sense to define a [regex](https://docs.renovatebot.com/modules/manager/regex/) pattern with renovate to automate the task.

**Comment by PierreSchwang** [comment]
Why not just dropping the revision at all?
`1.20.4-R0.1-20240106.182028-62` -> `1.20.4-R0.1-SNAPSHOT`

**Comment by NotMyFault** [comment]
> Why not just dropping the revision at all? `1.20.4-R0.1-20240106.182028-62` -> `1.20.4-R0.1-SNAPSHOT`

Specifying an explicit version ensures we all develop with the same version. `1.20.4-R0.1-SNAPSHOT` might lead to cached artifacts, given the sub-versions of `1.20.4-R0.1-SNAPSHOT` differ.
