### ISSUE TITLE
FAWE not detecting 1.20.4 properly and says unsupported

### ISSUE THREAD

**Issue by mrjasonn** [IntellectualSites/FastAsyncWorldEdit#2516]
### Server Implementation

Spigot

### Server Version

1.20.4

### Describe the bug

It doesn't detect 1.20.4 properly and says need to update

### To Reproduce

1. open a Minecraft CraftBukkit or Spigot server 1.20.4
2. Have FAWE installed
3. You will find the unsupported error

### Expected behaviour

It doesn't throw that error and I can use the functions that require supported versions properly

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/63d93dcd384b4167805f07917cad47fa

### Fawe Version

FastAsyncWorldEdit Build 624

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
Please use paper instead CraftBukkit (unsupported).
