### ISSUE TITLE
FAWE causing CPU to get stuck at 300%+

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#252]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-bukkit-1.13.191

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-a9c95b59 (MC: 1.13.2)

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/XuhJEDjM
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
Just before this occurs this error is thrown in the console: https://pastebin.com/8y1Hittb
Profiler shows this: 
![FAWE Endless Loop Issue](https://user-images.githubusercontent.com/10485646/69012710-b53ecb80-0970-11ea-8cca-71d53c1c7f88.png)

Keeping this here for reference:
![Untitled](https://user-images.githubusercontent.com/10485646/69484538-24fafd80-0e2c-11ea-8660-ee79d4a7bb81.png)

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**How to replicate**:
Not quite sure.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
I'm actively looking at this issue right now.

**Comment by aurorasmiles** [comment]
Is this still an issue with the latest version?

**Comment by SecretlyJealous** [comment]
I'll create a new ticket if I still encounter this issue on newer builds
