### ISSUE TITLE
World already unloaded

### ISSUE THREAD

**Issue by zingeer** [IntellectualSites/FastAsyncWorldEdit#2532]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Calling an exception when exiting the server.

### To Reproduce

1. Load world and use fawe in world
2. Unload world
3. Leave from server

### Expected behaviour

Not call exception

### Error log (if applicable)

https://gist.github.com/zingeer/b5a01f7cf9f2f7b20047e59b48d2f9c4

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/73f43e30622c44d4ae8eb70bd9602116

### Fawe Version

625

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
That's not Paper or anything we know.
