### ISSUE TITLE
fawe.plotsquared.trusted set to false does not work...

### ISSUE THREAD

**Issue by homerek111** [IntellectualSites/FastAsyncWorldEdit#2537]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

How can i disable FAWE usage for trusted players (plotsquared)

setting permission fawe.plotsquared.trusted to false does not work...

All i want is to allow only specific ranks to use worldedit while they are trusted to the plot - so i woud like to make it negative for default rank (but this permission does not work properly...)

### To Reproduce

1. set permission fawe.plotsquared to TRUE for player
2. set permission fawe.plotsquared.trusted to FALSE for player
3. trust him on your plot (plotsquared plugin)
4. he can still use worldedit on the plot (with permission that should prevent him from using it)

### Expected behaviour

when fawe.plotsquared.trusted is set to FALSE it should block trusted player to use worldedit on the plot

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8e9162600cbc444bbc8166f6dc6719da

### Fawe Version

2.8.4-SNAPSHOT-632;28ab566

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Trusted always allows use of WE on a plot. Add the player instead
