### ISSUE TITLE
[Feature Request] Regenerator NMS ChunkGenerators Support 

### ISSUE THREAD

**Issue by ojmaster** [IntellectualSites/FastAsyncWorldEdit#2538]
### What feature do you want to see added?

Hello, I am using the Terra Plugin which uses a NMS ChunkGenerator, currently it is unsupported as when i try to do the `//regen` command I get this error `[ERROR] Unsupported generator type com.dfsek.terra.bukkit.nms.v1_20_R1.NMSChunkGeneratorDelegate`. I'd really appreciate it if this was added!

### Are there any alternatives?

Nope

**Comment by SirYwell** [comment]
The reason why custom NMS-based chunk generators aren't supported is that it is impossible to support them without explicitly writing code for each of them. The newer spigot API also supports far better chunk generation than before, and it should be used instead.

**Comment by dordsor21** [comment]
@SirYwell is regernating with custom generators something that would be possible when using the new generation API?

**Comment by SirYwell** [comment]
We currently try to create custom generators that are written using the bukkit api (whether old or new), and those work. But arbitrary classes extending the NMS stuff aren't supported.

**Comment by dordsor21** [comment]
Mm can probably close this then, and if people have issues with custom generators using the proper API we can investigate
