### ISSUE TITLE
[BUG] //undo may not clear all blocks when a paste has the -a switch

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/FastAsyncWorldEdit#2539]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

When a //copy is done and then a //paste -a ( -a switch) , the //undo will not clear all the blocks . This does not seem to effect a regular //paste .

### To Reproduce

//copy
//paste -a
//undo
and any subsequent //redo //undo of that paste

### Expected behaviour

expect a clean return to previous state

### Error log (if applicable)

No errors or warnings

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9de1e31f7cf34adebfc5e47412bd5e6e

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.8.5-SNAPSHOT-639

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Tsoccerguy3** [comment]
Updated Paper to 1.20.4 build 381 and FastAsyncWorldEdit-Bukkit-2.8.5-SNAPSHOT-641 . Testing and issue seems to not happen now . Will keep testing and report back here. 
The Ghost in the Machine !

**Comment by Tsoccerguy3** [comment]
More testing with new FAWE version and //undo is now becoming more clear with an error being produced . Look at this new debugpaste here https://athion.net/ISPaster/paste/view/6d8407a49dc849ce9089d1a3b25c182f

**Comment by Tsoccerguy3** [comment]
![2024-01-21_17 29 53](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/22108822/56edc51f-ba87-4bc7-9935-12aa261ecd58)
![2024-01-21_17 30 23](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/22108822/4aaa5fe6-1b7f-4ad4-8caa-351fa09222d3)

showing a //paste -a , then a //undo . not all blocks are removed

**Comment by Tsoccerguy3** [comment]
This may or may not be related, but after i updated plotsquared , The error with FAWE went away

**Comment by Tsoccerguy3** [comment]
More testing with updated FAWE and Plotsquared  , error is back after a clean FAWE directory and reboot . New Debugpaste here https://athion.net/ISPaster/paste/view/b984540217c44ac7b8bf033b7e285acc .

Some copy key error that surfaces after a few //undo //redo commands

![2024-01-22_19 16 39](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/22108822/544fc8b0-6077-418c-b36e-33841e58ddc8)
![2024-01-22_19 16 53](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/22108822/37801e4d-6ed4-427b-8631-40c5f6587c81)


schematic

[ship01.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/14016843/ship01.zip)

**Comment by Tsoccerguy3** [comment]
This issue is back with FAWE build 669

**Comment by dordsor21** [comment]
Can you try build 666

**Comment by Tsoccerguy3** [comment]
You made a build with that number ? I rolled back to the last build working on the server 661
. 
Let him that hath understanding count the number of the beast: for it is the number of a man; and his number is six hundred and sixty-six." Revelation 13:18 states that if one is wise and has an understanding to count the number of the beast, which is also the number of a man, the number comes to 666.
