### ISSUE TITLE
1.20.2 - Glitches/Errors when performing basic WE functions

### ISSUE THREAD

**Issue by FoxesVenom** [IntellectualSites/FastAsyncWorldEdit#2543]
### Server Implementation

Spigot

### Server Version

1.20

### Describe the bug

attempted to perform //set minecraft:sand in the a small selected area.  FAWE changed the whole chunk and replaced with other blocks from various mods (biomes o plenty and nifty are some of the noteable ones).  It did this before too and I thought this was an issue with the other mods overwriting the IDs of the minecraft items and I removed them only to encounter the same issue on mods that previously was fine.

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/23228401/f737f483-1c04-4a5b-a35d-60d81dbbf563)

### To Reproduce

the below mods:

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/23228401/20ff8013-1b5e-4e87-8caf-6507480f5b9c)

select pos1 and pos 2
//set minecraft:grass_block

### Expected behaviour

set the selected area of the floor to sand

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/23228401/1e8cc42b-e3c7-4fb8-ad91-db6cde65cd10)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9b12f24bcc804c99a14f0b4ffcec01e9

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.8.5-SNAPSHOT-641

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
That is not spigot. Hybrids are not supported.
