### ISSUE TITLE
FAWE pastes wrong then wont undo bits of it

### ISSUE THREAD

**Issue by Arctic-foxxy** [IntellectualSites/FastAsyncWorldEdit#2545]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Sometimes when a player pastes something and trys to undo it, fawe will either refuse to revert it or just leave chucks of it still there

### To Reproduce

Kinda difficult but all we did was paste big ish items of the world

### Expected behaviour

it pastes normally

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/36e418a9d300429cb224a972ff87cff3

### Fawe Version

2.7.1-SNAPSHOT-545;50e45f0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Please update your FAWE and also switch to Paper, we don't support purpur as it breaks compatibility.
