### ISSUE TITLE
Gmasks and Masks not working together

### ISSUE THREAD

**Issue by SpringToger** [IntellectualSites/FastAsyncWorldEdit#2546]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

When using "gmask 0" and "mask >gold_block" with a sphere brush, the brush doesn't follow the masks. 

![2024-01-18_15 15 32](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/79346056/475f93c9-2dec-40d4-99f7-a79320795bd6)

https://discord.com/channels/268444645527126017/344128526435221505/1197635519312560218

### To Reproduce

1. "/br s diamond_block"
2. "/gmask 0"
3. "/mask >gold_block"
4. Brush ontop of a gold block pile. 

### Expected behaviour

![2024-01-18_15 29 08](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/79346056/00884a23-5537-4281-8fb7-54a540d29994)
It should create a top layer of diamond blocks, without cutting into the gold blocks. 

### Screenshots / Videos

![weird](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/79346056/0ba2f7c6-4f88-4986-8faf-1e6cb0a71630)
The left side is with the method explained, the right side is placed by hand and is the expected outcome. 

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7aabd1467b9e43f9affede1aea657444

### Fawe Version

FAWE 12.8.5-SNAPSHOT (1.20.4)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
so the gmask logic is ignored while the mask logic is used? I could reproduce your issue

**Comment by SpringToger** [comment]
Yes, the gmask is being overriden by the mask.
