### ISSUE TITLE
Add support for sponge schematic v3

### ISSUE THREAD

**Issue by Strongis13** [IntellectualSites/FastAsyncWorldEdit#2547]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

When attempting to load a .schem file which was saved using the 1.20.2 fabric version of WorldEdit, FAWE will throw an error

### To Reproduce

1. Open a server/world running fabric (in this case 1.20.2) with world edit installed
2. Make a selection, copy, save
3. Switch to a 1.20.2/1.20.4 server running Paper with FAWE
4. //schem load \<name\>
5. See error in chat "This schematic version is not supported"

ALTERNATE: 
4. //schematic loadall \<name\>
5. //paste
6. See error in console "This schematic version is not supported"

### Expected behaviour

.schem file can be loaded and pasted with no errors

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9574e984e15645538d6de934aa44c602

### Fawe Version

2.8.5-SNAPSHOT-641;b3905c2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

[fawe-demo.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/13995358/fawe-demo.zip)
Here is the .schem file I used to verify this issue.

**Comment by EncryptSL** [comment]
Yep yep, i have same issue.

**Comment by SirYwell** [comment]
Seems like you are using the Beta version of WorldEdit 7.3 to create the schematic, which will be written as v3 by default. You can use `//schem save mySchematicName sponge.2` to use the v2 format. FAWE should be able to load that. 

We'll keep this issue open until FAWE supports the v3 format.

**Comment by Strongis13** [comment]
> Seems like you are using the Beta version of WorldEdit 7.3 to create the schematic, which will be written as v3 by default. You can use `//schem save mySchematicName sponge.2` to use the v2 format. FAWE should be able to load that.

Yep this is working for what I need, thank you
