### ISSUE TITLE
Phantom blocks on 1.18

### ISSUE THREAD

**Issue by thatnickisgeek** [IntellectualSites/FastAsyncWorldEdit#2558]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

While using the latest version of FAWE on 1.20.4 with viabackwards (needed for my players to play on lower version ex. 1.18) wand tool creates phantom blocks on first pos.

### To Reproduce

1. Use 1.18 mc version
2. Get the wand tool via //wand
3. Create phantom blocks via first pos (left click)

### Expected behaviour

Not creating phantom blocks like on the latest mc versions

### Screenshots / Videos

Video: https://imgur.com/a/DiV5fOg

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9c45d8fac1cf4eb3993775d887ca7d2f

### Fawe Version

2.8.5-SNAPSHOT-648;9ffe76d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
It might be related to ViaVersion / ViaBackwards for example: https://github.com/ViaVersion/ViaVersion/issues/3643

**Comment by OneLiteFeather** [comment]
In addition, you might have to update both ViaVersion and ViaBackwards to the same version and retry if the error still persists

**Comment by thatnickisgeek** [comment]
I have changed server version to Paper 1.19.4 and bug doesn't appear on 1.18 versions anymore. Hard to say what to do next, because ViaVersion and ViaBackwards are on their latest versions now.
