### ISSUE TITLE
Could not pass event PlayerItemHeldEvent to FastAsyncWorldEdit v2.9.1-SNAPSHOT-659;c93ec87

### ISSUE THREAD

**Issue by djoveryde** [IntellectualSites/FastAsyncWorldEdit#2580]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

I'm having an issue where every time a player joins the server (1.20.1) FAWE throws a null error.
Not sure why its happening or how to fix it.

 [https://pastebin.com/VD2fHkue](url)

### To Reproduce

Run a 1.20.1 server with  FastAsyncWorldEdit v2.9.1-SNAPSHOT-659.
Player joins.
Error throws.

### Expected behaviour

No error should be thrown.

### Fawe Debugpaste

https://pastebin.com/VD2fHkue

### Fawe Version

FastAsyncWorldEdit v2.9.1-SNAPSHOT-659

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
That's not Paper.
