### ISSUE TITLE
my //cut randomly stopped working

### ISSUE THREAD

**Issue by KingTurtle1000** [IntellectualSites/FastAsyncWorldEdit#2588]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

whenever i do //cut or //set on any amount of blocks it says 
Please report this error: [see console] 
java.lang.NoSuchMethodError:
com.google.common.collect.ImmutableMap
com.google.cmmon.collect.immutableMap$Buider.buildOrThrow()'

### To Reproduce

//cut 
//set

### Expected behaviour

cut the blocks of the selected area
set the blocks to a block in the selected area

### Screenshots / Videos

<img width="651" alt="Screen Shot 2024-02-22 at 8 35 43 AM" src="https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/150104149/bbab7d0a-87e4-49cc-9869-1ce49d1523eb">

<img width="748" alt="Screen Shot 2024-02-22 at 8 35 49 AM" src="https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/150104149/e1b0c1dd-b283-4675-852c-477b16abffda">

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/62760e2ea1f442989df20ebc10509f77

### Fawe Version

FastAsyncWorldEdit version 2.9.1-SNAPSHOT-660;f94b96d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

PLS HELP I NEED IT FOR MY SERVER

**Comment by KingTurtle1000** [comment]
Ive tested other commands none of the FAWE commands work anymore

**Comment by Cryodev1** [comment]
Saw this issue, for any devs looking through, this problem is with piston.
Piston uses guava version 21.0 (because that's what works with minecraft according to comments in code) but attempts to use ImmutableMap.Builder.buildOrThrow which was implemented in version 31.0, so it attempts to call a method that doesn't exist in that version. Never worked in mods before but code hunting brought me to this, hope it helps!

**Comment by Atticuss26** [comment]
@Cryodev1 would you be willing to make a fork of FAWE that has this patched so I can use a working version on my server

**Comment by NotMyFault** [comment]
1.17.1 is no longer supported, I recommend updating your server to a maintained version, such as 1.20.4.
