### ISSUE TITLE
Cherry Sign acting as Navigation Wand

### ISSUE THREAD

**Issue by GrumpyCatJen** [IntellectualSites/FastAsyncWorldEdit#2589]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Instead of being able to place a Cherry Sign in creative mode, it acts like the navigation wand.  I tried correcting this with commands like /none or /unbind or the Essentials /powertooltoggle command.  It does not fix it.  I have tried reloading the FAWE config and have tried restarting the server.  None of these actions have fixed it.

### To Reproduce

1. Go into AdminMode to access FAWE perms.
2. Go into creative mode
3. Get a Cherry Sign out of inventory
4. Right-click a surface to place the sign, but instead it teleports like the navigation wand or //thru command.

### Expected behaviour

Expected to be able to place a Cherry Sign as if I was in survival mode.  It does not do this to other signs like Oak; it is only Cherry Sign.

### Error log (if applicable)

N/A

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9a1725b34ede49ba831c5f10c022c579

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.9.1-SNAPSHOT-660

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Well, your AdminMode Plugin is the main reason you can do that. "Bind commands to a specific item and perform them in admin mode". You could open an issue to the developer of it. FAWE just cares what is in the default configuration. I tested it before with just fawe and you are not able to do this like in your issue.
The AdminMode developer could look out for your navigation item in fawe and disallow using the same item you have in your configuration.
But I am not the wisest, it is up to him/her.

**Comment by GrumpyCatJen** [comment]
We were able to fix it.  We essentially did a /navwand bind to another item (diamond hoe), and then we were able to do /tool unbind on the diamond hoe, and everything was returned to normal.  SO, it was FAWE and it could not be fixed in the config... I just had to force some type of "reset" by rebinding it..
