### ISSUE TITLE
Cannot invoke "com.fastasyncworldedit.core.queue.IQueueExtent.getCachedGet(int, int)" because "this.extent" is null

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2590]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Player tried to use `//set 0` and this error appears in console: https://pastebin.com/0AXDR5iM

### To Reproduce

1. Not sure

### Expected behaviour

No errors in console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3032aedddb594bb4ae145b498f8efaf6

### Fawe Version

2.9.0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
I am wondering what the user had on the selection causing //set 0 to cause the exception. Do you have any custom mobs, blocks or other custom stuff on your server? If yes, can we take a look at it?
