### ISSUE TITLE
Eror at block_display if paste

### ISSUE THREAD

**Issue by XxleynaxX** [IntellectualSites/FastAsyncWorldEdit#2592]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

I found a bug related to the paste function; it is erroneously recognized as a copy, even when I attempt a schematic. Upon pasting, nothing happens, and upon inspecting the local server console, numerous white errors are visible. It appears that "block_display" cannot be rendered properly, and there is an absence of animation.

### To Reproduce

1. pos1 & pos2
2. //copy -e
![2024-02-27_17 24 06](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/161495475/04b7a652-167e-4fd9-89df-0832ca44e28f)
3. //paste -e 
![2024-02-27_17 24 30](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/161495475/d01001ad-51ca-4556-a19e-0b9dc0fec702)

### Expected behaviour

When I paste that I have the block_display right there next to it

### Error log (if applicable)

https://paste.gg/p/anonymous/4af33a2a11d84deab7c62362ef779d9f

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a063f3a2752349c7af99d6595a14a928

### Fawe Version

2.9.1-SNAPSHOT-660;f94b96d

### Checklist

- [X] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

no 
```[tasklist]
### Tasks
```

**Comment by XxleynaxX** [comment]
> ### Server Implementation
> Paper
> 
> ### Server Version
> 1.20.4
> 
> ### Describe the bug
> I found a bug related to the paste function; it is erroneously recognized as a copy, even when I attempt a schematic. Upon pasting, nothing happens, and upon inspecting the local server console, numerous white errors are visible. It appears that "block_display" cannot be rendered properly, and there is an absence of animation.
> 
> https://athion.net/ISPaster/paste/view/a063f3a2752349c7af99d6595a14a928
> 
> ### To Reproduce
> 1. pos1 & pos2
> 2. //copy -e
>    ![2024-02-27_17 24 06](https://private-user-images.githubusercontent.com/161495475/308256833-04b7a652-167e-4fd9-89df-0832ca44e28f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTE5MjQsIm5iZiI6MTcwOTA1MTYyNCwicGF0aCI6Ii8xNjE0OTU0NzUvMzA4MjU2ODMzLTA0YjdhNjUyLTE2N2UtNGZkOS04OWRmLTA4MzJjYTQ0ZTI4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjMzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmYwMmNiYTQzYzFjZDJkNWFjY2U3NTg5ZmQzM2M3Zjc5Y2M4MzY2MmZlZWQ4MDkwZDg0ZGMyNjFhZWE2NDMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.icv05uDMQwHMM1l7XRihnModwmj-afpsO42rKLM3gQ0)
> 3. //paste -e
>    ![2024-02-27_17 24 30](https://private-user-images.githubusercontent.com/161495475/308256843-d01001ad-51ca-4556-a19e-0b9dc0fec702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTE5MjQsIm5iZiI6MTcwOTA1MTYyNCwicGF0aCI6Ii8xNjE0OTU0NzUvMzA4MjU2ODQzLWQwMTAwMWFkLTUxY2EtNDU1Ni1hMTllLTBiOWRjMGZlYzcwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjMzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTE0NjA0NTc1MTJhYjk5NTQ4MDJjZWIxMDk0ZmU4YTYzMTg1NTJjYzRlYjI0OTc1MmUyMDNkYWYxMGY1MTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vUCl6cDRPIfiSnkupClXsoLijx_G8BKMBh1XGvICC8s)
> 
> ### Expected behaviour
> When I paste that I have the block_display right there next to it
> 
> ### Screenshots / Videos
> _No response_
> 
> ### Error log (if applicable)
> https://paste.gg/p/anonymous/4af33a2a11d84deab7c62362ef779d9f
> 
> ### Fawe Debugpaste
> https://athion.net/ISPaster/paste/view/a063f3a2752349c7af99d6595a14a928
> 
> ### Fawe Version
> 2.9.1-SNAPSHOT-660;f94b96d
> 
> ### Checklist
> * [x]  I have included a Fawe debugpaste.
> * [x]  I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.
> 
> ### Anything else?
> no

**Comment by OneLiteFeather** [comment]
So it happens when you do //paste -e, just an information to note down

**Comment by OneLiteFeather** [comment]
(for context, I asked her to upload the display entities as a schematic for testing from the same server / our server)

> [schematic.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/14423352/schematic.zip)

**Comment by PierreSchwang** [comment]
Can't reproduce this (anymore?). Copy-Paste of Block Entities works as expected - schematic pastes fine without errors.
