### ISSUE TITLE
BR Height Error

### ISSUE THREAD

**Issue by Bramsies** [IntellectualSites/FastAsyncWorldEdit#2593]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

When binding a height brush, an error follows.
The error is only thrown if an imagemap is provided.

Providing additional parameters does not change anything (size and rotation parameters for example)

This bug persists in the latest version (FastAsyncWorldEdit-Bukkit-2.9.1-SNAPSHOT-661)

### To Reproduce

1. Install Paper-196 (MC 1.20.1)
2. Install FAWE 2.9.0
3. Hold any tool
4. Run `/br height https://i.imgur.com/HSPfNbu.png`

### Expected behaviour

The tool is supposed to bind a heightmap brush 

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/89806653/4bb15854-1b84-405d-bf47-23163ab628a4)
![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/89806653/c099073f-3578-49a3-9c0c-ffa2ced8365e)

### Error log (if applicable)

https://paste.gg/p/anonymous/51ed33343ba848e2a6523bcee8894dec

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/115d50ff387a4648bddac4047df8ab9e

### Fawe Version

FastAsyncWorldEdit version 2.9.0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
I'm not sure if that's due to the age of the Issue - but that image link results in a 404 Not Found. That'd explain your error, as no image decoder may read that file (as it's no image but an HTML error page). We should presumably / most certainly handle null values there better either way.
