### ISSUE TITLE
Plugins interacting with FAWE broken since build #632

### ISSUE THREAD

**Issue by DieEchteRatteMan** [IntellectualSites/FastAsyncWorldEdit#2606]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

The commit #2365 broke several plugins including WorldGuard interaction with FAWE, allowing people to use //cut at spawn, this caused my server to perform a rollback, please resolve this.

### To Reproduce

By updating to build 632

### Expected behaviour

The plugins are supposed to correctly limit world edit actions

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/96522b9de38744dd85527fe0ca469869

### Fawe Version

2.9.0 release

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
`Pufferfish version git-Pufferfish-35 (MC: 1.20.2)` can you try replicating with Paper instead?

**Comment by GriefUnion** [comment]
> `Pufferfish version git-Pufferfish-35 (MC: 1.20.2)` can you try replicating with Paper instead?

https://athion.net/ISPaster/paste/view/9610396c193b4c40ba21bc690fe65289

Tested on Paper 1.20.4, and tests have been performed on the build after, and before build 632, i think it's safe to say, that commit broke several plugins interacting with FAWE

**Comment by TheMeinerLP** [comment]
> Tested on Paper 1.20.4, and tests have been performed on the build after, and before build 632, i think it's safe to say, that commit broke several plugins interacting with FAWE

I would never say that it is. I've seen that the plugin hasn't had any real updates for 2 years. So far we speak from https://github.com/InsightsPlugin/InsightsWorldEditExtension

Can you please provide 2 test cases? Currently, I am not sure what plugins does. Same plugin as above mention

**Comment by dordsor21** [comment]
You have region restrictions set to false in your config...

**Comment by GriefUnion** [comment]
> You have region restrictions set to false in your config...

Doesn't affect Insights, or WorldGuard w/ WorldGuardExtraFlags & the worldedit flag set to false
