### ISSUE TITLE
Beside Mask Shorthand Parsing Error

### ISSUE THREAD

**Issue by Zeranny** [IntellectualSites/FastAsyncWorldEdit#2622]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

When you use the shorthand `|` for the `#beside` mask, the parser produces an error

```
[00:39:31 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[00:39:31 WARN]:        at FastAsyncWorldEdit-Bukkit-2.9.1.jar//com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:343)
```

### To Reproduce

1. Type `//replace |air stone`
2. `Index 0 out of bounds for length 0` error will appear in console when parsing for suggestions

### Expected behaviour

No error (Identical behaviour to `#beside`)

### Error log (if applicable)

https://paste.gg/p/anonymous/20e3b35c3d434f84a8bce76c937209dc

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/56589f18ad3646328857ae6aa4e975db

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.9.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Zeranny** [comment]
I believe I can fix this in the DefaultBlockParser - will raise a PR if the fix works

**Comment by dordsor21** [comment]
I cannot replicate this at all
