### ISSUE TITLE
Fences Do Not Connect to Each Other

### ISSUE THREAD

**Issue by Poseidon-I** [IntellectualSites/FastAsyncWorldEdit#2638]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

When using //set or other filling commands, fences do not connect with each other or with any other blocks around them.

### To Reproduce

1. Select any two blocks as pos1 and pos2
2. Run //set oak_fence
3. Note that said fences do not connect with each other.

### Expected behaviour

Expected behavior is that the fence posts connect with each other and with any blocks that they are next to, similar to as if Minecraft's vanilla /fill command is run.

### Screenshots / Videos

https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/65434062/7c0c9bba-a5f6-42b3-a03d-7c1aaeb31d10

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/58aed7e1aef24403afc6a0e6c2ef6240

### Fawe Version

2.9.2-SNAPSHOT-688;36da507

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
#313
