### ISSUE TITLE
//paste being jumbled

### ISSUE THREAD

**Issue by FeroxDrood** [IntellectualSites/FastAsyncWorldEdit#264]
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
24.11 06:47:20 [Server] INFO FastAsyncWorldEdit-139 created by Empire92
24.11 06:47:20 [Server] INFO FAWE version:
24.11 06:47:20 [Server] INFO - Date Nov 24, 2019 12:00:00 AM
24.11 06:47:20 [Server] INFO - Commit f9870b15
24.11 06:47:20 [Server] INFO - Build 139
24.11 06:47:20 [Server] INFO - Platform bukkit

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-221 (MC: 1.14.4)

**Links to config.yml and config-legacy.yml file:** 
Config.yml - https://pastebin.com/59yfM1Rn
Config-legacy.yml - https://pastebin.com/YVe8BPby

**[REQUIRED] Description of the problem:**
When pasting in a schematic some of the blocks get jumbled up and start pasting in the sky in weird patterns also some of the water is missing. (see image below)
I have tried some fixes people recommened in discord such as deleting the history/clipboard folder, this did not work and i have also tried changing the clipboard use-disk setting to false and true
https://i.imgur.com/oSClHE4.png

**Plugins being used on the server:**
Checked without plugins, not plugin related.

**How to replicate**:
Load in any schematic and paste it in, some schematics are fine and paste if perfectly however some glitch out as seen in the picture

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
- Update Fawe (delete its entire folder) and PaperMC.

I was able to paste schematics fine.

**Comment by boy0001** [comment]
Could you attach one of the schematics you used that gets jumbled?

**Comment by FeroxDrood** [comment]
https://drive.google.com/open?id=1_YBf6DCYGrNXUZSSVCjvQtxD1ijH0tmG

Has to upload it to google drive as github does not support schematics but here you are, and this is ws a fresh install NotMyFaultOG

**Comment by FeroxDrood** [comment]
Getting this error when pasting this build gonna remove all mobs spawners in the schematic and see if this changes anything
. 
https://pastebin.com/XL60vYaL

**Comment by dordsor21** [comment]
This is fixed
