### ISSUE TITLE
Invalid blocks still stored

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#265]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.14-141.jar

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-226 (MC: 1.14.4)

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/XuhJEDjM
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
The error is harmless but the old material names for signs are still stored:
```
[15:34:48] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_14_R4 as the Bukkit adapter
[15:34:48] [Server thread/INFO]: Ignoring invalid block minecraft:sign
[15:34:48] [Server thread/INFO]: Ignoring invalid block minecraft:wall_sign
```

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**How to replicate**:
Console will give this error on startup as long as FAWE is installed.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by mibby** [comment]
I can also confirm still getting the sign invalid block messages as of FastAsyncWorldEdit-1.16 dev 595. 

@NotMyFault Should a new ticket be created since it's still present over 2 new game versions & 15+ months later?
