### ISSUE TITLE
Crash caused by IndexOutOfBoundsException

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2652]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Here is the crash report: https://pastebin.com/Za7QAgzt When I asked about what caused this crash a member of the papermc core team replied with "**Something would have to be editing the chunk palette while the packet is being filled (which for chunk packets is on main)**" and the only plugin I have which interacts with chunk palette's is fawe. I know this is not a lot of information but thought someone with more knowledge could have a look at the crash report to see what's going on

### To Reproduce

1. Not sure

### Expected behaviour

Server should not crash

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1936beef9d28403ea63b9281d9036879

### Fawe Version

FastAsyncWorldEdit v2.9.2-SNAPSHOT-681

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Closing in favor of new report https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2729 which contains an error. 

Will link over there as the note from the PaperMC team gives important context.
