### ISSUE TITLE
//copy java.lang.NullPointerException

### ISSUE THREAD

**Issue by Eloslav** [IntellectualSites/FastAsyncWorldEdit#266]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
https://athion.net/ISPaster/paste/view/61c243937f094f32b733bff0dbb6a563

[19:57:42 INFO]: &7FastAsyncWorldEdit-141 created by Empire92
[19:57:42 INFO]: &7FAWE version:
 - Date Nov 24, 2019 12:00:00 AM
 - Commit f16a6a1d
 - Build 141
 - Platform bukkit
[19:57:42 INFO]: &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[19:57:42 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.14-141;e9595e3)

[19:57:42 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
Paper version git-Paper-226 (MC: 1.14.4)

**[REQUIRED] Description of the problem:**
There is error from console. I tried to coppy and paste some building.
https://mega.nz/#!lO41mQgK!D_JqHk27RSOr0a8zIuONmD01DPT1u_JJwp9PSxHj08s

**How to replicate**:
Copy building about 50x50x50 blocks and you should see it.

**Plugins being used on the server:**
[20:03:29 INFO]: Plugins (8): DiscordSRV, dynmap*, FastAsyncWorldEdit, Herochat*, SkinsRestorer, Vault, WorldBorder, WorldEdit

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
- Update Fawe and PaperMC.
What blocks are trying to copy? I just tried to copy some general blocks, but it works fine for me.

**Comment by SecretlyJealous** [comment]
I got a similar issue, not sure you even reproduce this but I was just messing around with //cut and //undo with hoppers: https://pastebin.com/ecqU9Y9A

**Comment by Eloslav** [comment]
I tried to copy part of building with some building blocks, RS lamps and torches, nothing special.
@SecretlyJealous thanks for comment, did you solve it somehow or is that still happening?

**Comment by SecretlyJealous** [comment]
@Eloslav The issue is not fixed yet, I got the error when using the latest version available

**Comment by dordsor21** [comment]
I've not been able to replicate as of 5197ed0 I'll close but please reopen if the issue persists, with a new error log.
