### ISSUE TITLE
Cannot copy-paste signs

### ISSUE THREAD

**Issue by InfectedCatBite** [IntellectualSites/FastAsyncWorldEdit#2669]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Using Plotsquared and FAWE, copying and pasting a sign doesn't work. The sign isn't pasted, even when using `-e`

### To Reproduce

1. Place a sign
2. Create a cuboid containing the sign
3. //copy
4. Move then //paste

### Expected behaviour

The sign should be there after the //paste.

### Screenshots / Videos

Original on left, //paste result on right. Note the missing sign. (Blocks demonstrate that the cuboid was created properly.)

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/93386304/50420df5-2798-4b06-a829-60756aea5458)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/296154f4bcf242278021f87c44fa51af

### Fawe Version

FastAsyncWorldEdit version 2.9.3-SNAPSHOT-719;8b59741

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Have you looked for an invisible sign inside the selection?

**Comment by InfectedCatBite** [comment]
> Have you looked for an invisible sign inside the selection?

Note sure how to do that. Pointing the cursor at that spot doesn't reveal any block outlines.

**Comment by PierreSchwang** [comment]
Does it work when having OP / all permissions?

**Comment by InfectedCatBite** [comment]
> Does it work when having OP / all permissions?

Yes, it works if an OP user does it.

**Comment by InfectedCatBite** [comment]
Problem was that I had signs on the disallowed-blocks list. Solved.
