### ISSUE TITLE
Spawn a ModelEngine Model Send a Error

### ISSUE THREAD

**Issue by 527953120** [IntellectualSites/FastAsyncWorldEdit#2673]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

![fawe](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/71014798/463c0bf0-81b8-4d61-b5c4-b5b4451db4c8)

### To Reproduce

Summoning a model into the world with ModelEngine will result in this error,Not all models will be generated, and I can provide you with the one that generates the error

### Expected behaviour

solved!

### Screenshots / Videos

https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/71014798/5718bc71-c885-4172-a344-19d7ca447cd0

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d0dbc23589304a318b2cd29118b807e6

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-722

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
We are missing Upstream Changes here and still use deprecated (and nullable) methods
https://github.com/EngineHub/WorldEdit/blob/master/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitAdapter.java#L396
