### ISSUE TITLE
max-blockstates config limit is not enforced on //set

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2679]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

I have `max-blockstates: 5` however this restriction doesn't seem to be enforced when using `//set` or `//set #clipboard`.

Here is an example of where I was able to set 59,000 hoppers when it should have stopped me:
Example: //set hopper
![2024-04-09_10 07 32](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/10485646/124e1205-cb0a-43ff-99b2-2a87af0d2959)

### To Reproduce

1. Set max-blockstates: to a low number
2. Set a block entity beyond the limit you set

### Expected behaviour

WorldEdit action should be prevented

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a64ea766b59b41a796b4fb6fe87c1008

### Fawe Version

2.9.3-SNAPSHOT-724;ca2c18e

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
This is because LimitExtent currently does/can not act as a processor, so edits that are applied as Filters (i.e. setBlocks using ParallelQueueExtent) will not have several limit checks applied to them
