### ISSUE TITLE
Auto-updates.

### ISSUE THREAD

**Issue by MagmaBro123** [IntellectualSites/FastAsyncWorldEdit#2692]
### What feature do you want to see added?

Title. Since this plugin is basically updated daily (or even faster then that) it'd be nice not to have to open my server's panel and file manager constantly to manually update the plugin.

This is starting to get very annoying.

### Are there any alternatives?

N/A?

### Anything else?

N/A.

**Comment by PierreSchwang** [comment]
I don't think that's really possible from my point of knowledge. You can't just replace the JAR while the server is running and refresh the classes in the currently active classloader without breaking anything

**Comment by NotMyFault** [comment]
> I don't think that's really possible from my point of knowledge. You can't just replace the JAR while the server is running and refresh the classes in the currently active classloader without breaking anything

Indeed, Bukkit supports no such concept.

**Comment by MagmaBro123** [comment]
> I don't think that's really possible from my point of knowledge. You can't just replace the JAR while the server is running and refresh the classes in the currently active classloader without breaking anything

Do it upon reboot.

**Comment by NotMyFault** [comment]
> > I don't think that's really possible from my point of knowledge. You can't just replace the JAR while the server is running and refresh the classes in the currently active classloader without breaking anything
> 
> Do it upon reboot.

That's what the "Update" folder is for, however, auto-updating brings a certain level of risk onto your server you cannot evaluate. Therefore, is any kind of auto-updating generally not recommended.

**Comment by PierreSchwang** [comment]
Just as an additional thought of mine - what could be possible (as I guess the source of the issue is the amount of update notifications) is to make the update checker configurable as to either notify on new builds or new released versions. But that should be part of another discussion (as this issue is locked either way :p)
