### ISSUE TITLE
Confirm-large does nothing to "unlimited" limit

### ISSUE THREAD

**Issue by TomLewis** [IntellectualSites/FastAsyncWorldEdit#2706]
### What feature do you want to see added?

I would like to see the flag -confirm added to //replace so that you don't have to run //confirm after the command, because when you are doing mass replaces on worlds, like cleaning up containers, you cant script //confirm to run after //replace because everything is async! There is no other way around it.

Here is the script im trying to use with CommandHelper
https://gist.github.com/TomLewis/8c305cdeca6c712587602c0a05d5e552

I need to constantly replace all containers from a Creative server with empty versions of the containers, so that I can copy the builds/worlds to Survival.

But I cant, as I'm constantly getting the error about "your selection is too large" and `confirm-large: false` in the config does not work, it must be hard coded to (>16384 chunks) as that's whats in the comments.

A //confirm flag would solve this.

### Are there any alternatives?

Creating a client side script that picks a random wait time and hope to hell its enough for FAWE to complete the task.

**Comment by TomLewis** [comment]
Bump

**Comment by dordsor21** [comment]
Set confirm-large to false in your config

**Comment by TomLewis** [comment]
> Set confirm-large to false in your config

In the initial message, it states this does nothing, it does not work.
