### ISSUE TITLE
//gen doesn't accept custom #biome

### ISSUE THREAD

**Issue by Taiyou06** [IntellectualSites/FastAsyncWorldEdit#2707]
### What feature do you want to see added?

Would be great if we can use //gen with #biome to biome color stuff faster in larger scale terrain

### Are there any alternatives?

It is possible with brush but it would be a time saver for anyone who works on massive terrains.

**Comment by Taiyou06** [comment]
WAsn't really sure if this is a bug or feature request, sorry if it is a bug. 🙏

**Comment by dordsor21** [comment]
Most likely duplicate of #2147
