### ISSUE TITLE
Door bug when transferred by schematic from 1.12.2

### ISSUE THREAD

**Issue by xfenilafs** [IntellectualSites/FastAsyncWorldEdit#2712]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

When transferring the schematic from 1.12.2 with doors, the upper door block takes the wrong position

### To Reproduce

1. Save the schematic on Minecraft version 1.12.2
2. Paste it on minecraft version 1.19.4

### Expected behaviour

door fix

### Screenshots / Videos

![screenshot](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/76786122/05b788b8-94a2-48e1-afd9-d0465f490502)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/eba0505e4bf54b0691a8b391fc7a20ac

### Fawe Version

FastAsyncWorldEdit 2.9.3-SNAPSHOT

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
This is because this data is not properly saved in older schematics and cannot therefore be read from the schematic
