### ISSUE TITLE
Forest generation IllegalArgumentException when density is specified

### ISSUE THREAD

**Issue by EarthCow** [IntellectualSites/FastAsyncWorldEdit#2717]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

`//forest largeoak 2` causes an `IllegalArgumentException`. Trees are still generated but they seem to not follow the specified density.

### To Reproduce

1. Make a cuboid selection
2. Perform the command `//forest largeoak 2`
3. Witness the error message both in game and in console (sometimes apparently)

### Expected behaviour

Trees of the specified type to generate in the selected region with the specified density.

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/56940983/0646f630-25c0-4a2b-aa6c-c5811f8aa4d7)

I restarted my server a bunch of times to see if that would fix it and it did **not** fix it but then when I went to go take a screen recording for this report I could not get it to happen again. 

### Error log (if applicable)

https://paste.gg/p/anonymous/1deb05734a0f45babfe1ca02eb49ff65

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/67b972a5b18f4dbdb7a28a2b539373bf

### Fawe Version

2.9.3-SNAPSHOT-757;a96b620

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Not sure that this is an FAWE issue. We're calling a standard bukkit method. If you have any evidence to the contrary please reopen
