### ISSUE TITLE
Please let 1.13+ servers can download .schematic files

### ISSUE THREAD

**Issue by SeaOrangejuice** [IntellectualSites/FastAsyncWorldEdit#2726]
### What feature do you want to see added?

I wish I could download the .schematic file in 1.13+ server.

### Are there any alternatives?

1.12.2 Server(Bad building experience)   
converter(Loss and replacement of blocks)   
https://github.com/PureGero/SchemToSchematic   
Amulet(The converted map light source is abnormal)   
https://github.com/Amulet-Team/Amulet-Map-Editor   

### Anything else?

My build friends and I think that the game version in 1.12.2 is not as good as the experience in higher versions.(Higher versions have more building auxiliary functions.)   
We hope to complete the main building in a high version and paste it into another low version server to export the world.   
I believe it doesn't require too many features, as long as the block states and types in the .schematic file are normal, it can provide a better gaming experience.   
Please, add it.🥺

**Comment by dordsor21** [comment]
The mcedit (.schematic) file format was deprecated with 1.13 with the changes to IDs as the old schematic format could not support it. Furthermore, "downgrading" schematics is not something we will not support as it introduces a number of issues and annoying problems, and a lot of different ways of implementing how to handle different blocks.
