### ISSUE TITLE
Track upstream API incompatibilities

### ISSUE THREAD

**Issue by PierreSchwang** [IntellectualSites/FastAsyncWorldEdit#2740]
FAWE has collected quite a few upstream diffs over the years, which need to be addressed to ensure compatibility (especially with 3rd-party plugins interacting with the WE api).
This issue contains known problems:
- https://github.com/EngineHub/WorldEdit/commit/6e2b0a1df8a6077c3cf8193e38dc9817038bcbe9 (`Clipboard#transform(Transform)` does not exist in FAWE)
- Record-style getters are missing (affects WorldGuard support): https://github.com/EngineHub/WorldEdit/commit/0df2b6af4c1ce18b77eedd5c62eeb45011512103

**Comment by AndyReckt** [comment]
bump
