### ISSUE TITLE
NoSuchFileException when generating new config files (fresh setup)

### ISSUE THREAD

**Issue by Nick31629** [IntellectualSites/FastAsyncWorldEdit#2742]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

All warns (see the Error log)

### To Reproduce

Start only the server with paper-1.20.4-496.jar downloadable from [here](https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/496/downloads/paper-1.20.4-496.jar).

### Expected behaviour

No warn at all, if possible

### Error log (if applicable)

https://gist.github.com/Nick31629/a07fd500a17715cd1fbaad6c390821ac

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/820b8f643aab4835b86a890bd994569a

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-776

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Does the file exist on disk? Is there any permission-issue on file-system-level?
