### ISSUE TITLE
//gmask throwing ClassCastException

### ISSUE THREAD

**Issue by Lothiredon** [IntellectualSites/FastAsyncWorldEdit#276]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/b6d52bb70591421f8ba5544fcded91bd

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

FastAsyncWorldEdit-149 (1.14.4)

**[REQUIRED] Spigot/Paper Version Number:** 

git-Spigot-56f8471-7554e05 (MC: 1.14.4)

**[REQUIRED] Description of the problem:**

Using a brush like sphere or cyl in conjunction with //gmask throws an exception:

https://pastebin.com/VvZw67Qy

**How to replicate**:

Using a shape brush with //gmask

**Plugins being used on the server:**

https://imgur.com/a/daw4YYP

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Couldn't replicate that issue with a newer version, assuming this is fixed
