### ISSUE TITLE
Failed to load the built-in legacy id registry (1.20.6)

### ISSUE THREAD

**Issue by jan-osicka** [IntellectualSites/FastAsyncWorldEdit#2762]
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

When loading server on newest version of minecraft (paper, purpur 1.20.6) with loaded FaWe and RS the server is crashing on startup or getting errors and crashing after a few minutes. Replicated on clean install of server. 
Issue appeared on version 1.20.6. Lower versions are working fine. 
When RS installed without FaWe, there are no issues. 

### To Reproduce

1. Install latest purpur/paper dev build (1.20.6)
2. Install latest FaWe build 
3. Install latest Realistic survival (https://www.spigotmc.org/resources/realistic-survival-1-17-hardcore-modded-experience.93795/)

(tested several versions of FaWe and purpur builds)

### Expected behaviour

Loading without crash

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/589363674dd142f48781ac2d807a4ce6

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-790

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
I'm not sure FAWE is doing anything wrong here. Presumably it'll also be an issue in WE and it seems only to happen with RS installed, so I imagine they're inserting some funky stuff
