### ISSUE TITLE
FAWE not working with 1.21

### ISSUE THREAD

**Issue by BurkenDev** [IntellectualSites/FastAsyncWorldEdit#2779]
### Server Implementation

Spigot

### Server Version

1.20.5/6

### Describe the bug

Will not work with 1.21. Please fix yesterday.

### To Reproduce

Add plugin in spigot 1.21
//wand works
selecting two blocks works
//set stone
ERROR

### Expected behaviour

Not working in 1.21.

### Fawe Debugpaste

n/a

### Fawe Version

2.10.1-SNAPSHOT-801

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Lol WorldEdit doesn't work with 1.21 yet either
