### ISSUE TITLE
FAWE biomes do not get set to a chunk section with only one biomes (i.e. SingleValuePalette)

### ISSUE THREAD

**Issue by itinstructor** [IntellectualSites/FastAsyncWorldEdit#2790]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

A few FAWE updates ago, the Biome brush stopped working.

### To Reproduce

1. Use the Biome brush, nothing changes

### Expected behaviour

The biome normally changes.

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/d5ad16546cb84950a499b08f749aad62

### Favs Version

Favs 3.11

### Checklist

- [X] I have included a debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by dordsor21** [comment]
This is specifically when biomes are set to a chunk that only has one biome.

**Comment by itinstructor** [comment]
Hi,

No, it is also when there are more than one biome in a chunk. I paint the biome on not paying attention to the chunks.

Bill

----------------------------------------------------------------------------------------------------------
William A Loring
Information Technology Instructor | Western Nebraska Community College
MSCIS, MCT, MCSE, MCP, MOS, Security+, Network+, A+  |  1601 E 27th St, Scottsbluff NE  69361
p: 308.635.6163  |  e: ***@***.******@***.***>  | Scottsbluff Office: Room B7F
Setup an appointment online with www.calendly.com/loringw<http://www.calendly.com/loringw>
www.facebook.com/WNCCITProgram<http://www.facebook.com/WNCCITProgram> “Like us on Facebook to keep up with current IT happenings!”
“If it’s your job to eat a frog, it’s best to do it first thing in the morning.
And if it’s your job to eat two frogs, it’s best to eat the biggest frog first.” Mark Twain

**Comment by dordsor21** [comment]
The chunk packets do not seem to send every time, and also sometimes it doesn't appear changes have been made due to the way minecraft 3D biome noise now works

**Comment by dordsor21** [comment]
The issue is with copying SingleValuePalette as it returns itself, meaning if (when) it is resized, it is updating the wrong PalettedContainer

**Comment by itinstructor** [comment]
It works now. Thank you for you swift response!
