### ISSUE TITLE
Java 17 Support Required for 1.8.8 Server

### ISSUE THREAD

**Issue by ArifErdoganK** [IntellectualSites/FastAsyncWorldEdit#2792]
### What feature do you want to see added?

Java 17 has been made mandatory by ViaVersion. FAWE is no longer supported on a 1.8.8 server version.
We need Java 17 support for Spigot/Paper version 1.8-1.12.2.

### Are there any alternatives?

I tried Java 17, Java 18, Java 19, and Java 20 but it's not working.

**Comment by PierreSchwang** [comment]
Minecraft 1.8-1.12.2 is not supported anymore. Use an up-to-date version.
