### ISSUE TITLE
Crash while using //undo on mohist

### ISSUE THREAD

**Issue by techno314** [IntellectualSites/FastAsyncWorldEdit#2795]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

The server decides to crash if you try to run //undo more than once or twice

### To Reproduce

1. Do something, copy cut, whatever.
2. Use //undo 1 or 2 times

### Expected behaviour

It should not crash

### Error log (if applicable)

https://paste.gg/p/anonymous/7e6c0bc4432c46d4bf2ebb1dba4f0f6b

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6a9cd92b6c3e436eadf9fff2bc0d523b

### Fawe Version

2.10.1-SNAPSHOT-810;6154c5b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Don't select Paper as your Server Software if you are not running it. There is a reason why Mohist isn't listed there as an option.
