### ISSUE TITLE
bug with Realistic Survival

### ISSUE THREAD

**Issue by IllyaVasilev1** [IntellectualSites/FastAsyncWorldEdit#2796]
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

It turns out that when I try to upload a plugin to the server (https://www.spigotmc.org/resources/realistic-survival-1-17-hardcore-modded-experience.93795/), I can't upload it. It turns out to start the server only if I disable WorldEdit or if I remove the Real Survival plugin.
But at the same time, on the test server, the plugins do not conflict if you upload only two of them, World Edit and Realistic Survival, but when I try to upload them to the server, there is an error with the launch, the server just freezes.

At the same time, I still have 300 gigabytes of SSD and 20 gigabytes of RAM in reserve. I don't know why it freezes.

I tried to download each of my plugins separately in turn, but it is not clear why the server does not want to work. You cannot access it, and the responses to commands in the console are empty.

### To Reproduce

Need to download all the plugins I have... And the console freezes at startup, if you delete World Edit or Realistic Survival, then everything works fine.

List of my plugins:
[09:05:41 INFO]: Server Plugins (50):
[09:05:41 INFO]: Bukkit Plugins:
[09:05:41 INFO]:  - ajParkour, AnimatedScoreboard, AuctionHouse, AuthMe, AutoMessage, BedrockPlayerManager, BetterCommandSpy, Brewery, ChestCommands, CMI
[09:05:41 INFO]:  CMILib, CoreProtect, DiscordSRV, dynmap, Dynmap-Towny, FastAsyncWorldEdit, Geyser-Spigot, GeyserHacks, InteractiveChat, InteractiveChatDiscordSrvAddon
[09:05:41 INFO]:  LuckPerms, MapTowny, MoneyFromMobs, NBTAPI, PL-Hide, PlaceholderAPI, PlugManX, ProtocolLib, PvPManager, QualityArmory
[09:05:41 INFO]:  RealisticSeasons, SelectionVisualizer, SkinsRestorer, TAB, Towny, TownyChat, TownyCombat, TownyCultures, TownyResources, UltraRegions
[09:05:41 INFO]:  Vault, Vegas, Vehicles, ViaBackwards, ViaRewind, ViaVersion, Vulcan, WorldGuard, WorldGuard-Towny, XConomy

### Expected behaviour

Normal server startup, running the plugin on Realistic Survival

### Error log (if applicable)

https://paste.gg/p/anonymous/922b75bff9c849ae94148f21be3cadf7

### Fawe Debugpaste

- console crash  https://imgur.com/a/rSBordr

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-811.jar, also 810 same problem

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by IllyaVasilev1** [comment]
It turns out that the plugins conflict for some reason, World edit has a bug. But at the same time, if these 2 plugins are just downloaded, then you can go to the server. And there are answers from the console.

**Comment by IllyaVasilev1** [comment]
Now I will send a dump of java

**Comment by IllyaVasilev1** [comment]
https://1drv.ms/u/s!ArleilWMSS2ai8Yv-CZbHZtpb71TXw?e=6vudaX

I'll send it via OneDrive because I can't upload it here, the file is too big.

**Comment by IllyaVasilev1** [comment]
> A [thread dump](https://docs.oracle.com/en/java/javase/17/docs/specs/man/jstack.html) would be helpful

I don't really know how to do it...
I just looked on the Internet what they did there through the task manager...
I have Windows visualization... Not Linux
I don't know how to do it on Windows.


But there I threw the dump file above:
> https://1drv.ms/u/s!ArleilWMSS2ai8Yv-CZbHZtpb71TXw?e=6vudaX
> 
> I'll send it via OneDrive because I can't upload it here, the file is too big.

**Comment by SirYwell** [comment]
That's not a thread dump, look up how to use the `jstack` tool.

**Comment by dordsor21** [comment]
No response
