### ISSUE TITLE
FAWE issue with not replacing block

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#280]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.14-152.jar

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-226 (MC: 1.14.4)

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/XuhJEDjM
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
Using `//replace dark_oak_stairs air` for example does not work with FAWE, instead you have to make sure you use `//replace minecraft:dark_oak_stairs air`. Normal WorldEdit does not have this behavior and will still replace the blocks regardless of whether you used `minecraft:` before the block name. This problem also exists in 1.13.2 and was discovered by some users on my server who had difficulty getting the command to work properly.
Example: https://gfycat.com/lazyglaringeelelephant

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**How to replicate**:
Place down a dark oak stair and use `//replace dark_oak_stairs air`

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Tested it in build 178, seems to be working fine now, cannot reproduce
