### ISSUE TITLE
Error on first startup

### ISSUE THREAD

**Issue by Dragonox77** [IntellectualSites/FastAsyncWorldEdit#2801]
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

Hello, I got an error on server startup, if the plugin is loaded for the first time (no FastAsyncWorldEdit in plugin folder)

### To Reproduce

- Delete FastAsyncWorldEdit folder inside the plugins folder
- Run the server

### Expected behaviour

No error :D

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/522ba2be03ae4dada0b6a4dff146644c

### Fawe Version

FastAsyncWorldEdit version 2.10.1-SNAPSHOT-819;75af797

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
Can you replicate that issue at paper, because Purpur as a Fork is unsupported

**Comment by Dragonox77** [comment]
Yessir https://athion.net/ISPaster/paste/view/9c2af1c656864f20a5cd634c5cb179e7

**Comment by PierreSchwang** [comment]
Due to latest commit (https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/75af797d4c7462b445461cc96590ac0f59fd841c, @dordsor21)
