### ISSUE TITLE
Using //Copy returns Java.io.IOExecption: Requested operation cannot be performed on a file with a user mapped section open.

### ISSUE THREAD

**Issue by ShadowTech12** [IntellectualSites/FastAsyncWorldEdit#2806]
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

When selecting a zone with the wand or manually using //pos1/2 then executing the command //copy it will not perform the copy operation and instead return an error. 

### To Reproduce

1: Make selection with wand or //pos1/2
2: Execute command //copy

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/73977660/ae266717-7b37-41eb-bc07-8e200294c40b)

### Expected behaviour

Expected behavior is to successfully copy a selection.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8e8983ca6858480b80221b7c8a41c875

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.20.0.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by ShadowTech12** [comment]
Just found that a different player can use the //copy normally.

**Comment by dordsor21** [comment]
Deleting the clipboard file for your UUID or restarting the server should fix this

**Comment by ShadowTech12** [comment]
Restarting entire server seems to have resolved the issue! Ive not run into a plugin that couldn't be fixed by restarting the server haha! 

Resolved the issue, Thanks!
