### ISSUE TITLE
Brush pasting Y=0 height and ignoring terrain when using /br populateschematic 

### ISSUE THREAD

**Issue by Snivo-Online** [IntellectualSites/FastAsyncWorldEdit#2815]
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

First my server is running paper in 1.21

Fawe : FastAsyncWorldEdit-Bukkit-2.11.0

When using "/br populateschematic #solid SCHEMATIC_NAME -r", it paste always at Y=0 for an unknown reason.

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/121866887/9d7a7a94-731f-4757-9d72-d1bacbbbb5da)

As seen here at bedrock level (flatgrass )

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/121866887/191491b6-8678-46b1-aef0-2a53ce6be2dd)

### To Reproduce

To reproduce, use /br populateschematic #solid SCHEMATIC_NAME -r

### Expected behaviour

Your brush will paste at Y=0, no matter where you aim.

### Error log (if applicable)

No error in console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c5ee1ada69ca41dea7ac9511b9963c4f

### Fawe Version

2.11.1-SNAPSHOT-833;15c6027

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
I can't replicate it on a normal generated world, but I know that this issue only happens on flat worlds. I looked inside the populateschematic class and found out that the default brush size (30) is rounded and then used on the cuboid edit session for max and min x,y and z. So min is always on flat worlds on min y on default brush size 30 as bedrock is the last block to brush on.

**Comment by dordsor21** [comment]
> @dordsor21 you had the last changes on this, how would you fix this brush on flat worlds as seen on the issuers picture?

There were a few extra related changes I wanted to make

**Comment by Snivo-Online** [comment]
> I can't replicate it on a normal generated world, but I know that this issue only happens on flat worlds. I looked inside the populateschematic class and found out that the default brush size (30) is rounded and then used on the cuboid edit session for max and min x,y and z. So min is always on flat worlds on min y on default brush size 30 as bedrock is the last block to brush on.

I've tried on a "normal" map and sometimes it still paste underground but not at y=0, it will paste to underground caves as shown in this video i've just recorded : https://youtu.be/qGGWadrPOT0
