### ISSUE TITLE
Half bricks and stairs that are copied and pasted with FAWE will leak rain

### ISSUE THREAD

**Issue by YXMHanChen** [IntellectualSites/FastAsyncWorldEdit#2819]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Hello, half-bricks and staircase blocks on buildings that are copied and pasted with FAWE will leak rain, is there any solution to this? I have successfully updated the latest build of FAWE but the issue is still not resolved. I restarted the server and reloaded FAWE but it still leaks. For example, complete blocks such as stone and grass blocks will not leak rain, but incomplete blocks such as half bricks and .

### To Reproduce

1.Select the selection that the building contains
2.//copy
3.//paste -a

### Expected behaviour

I hope this can be fixed in the new FAWE build. Let the half bricks and stairs copied and pasted by FAWE be able to shelter from the rain. In case it rains indoors.

### Screenshots / Videos

![42355D256C4D4E9E6F31117746B7E663](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/174427654/68725d7b-640c-4078-92ad-e20caa328d13)
![QQ截图20240702163240](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/174427654/0a53a537-c15e-4ff0-85ee-c3e03fb0ea4f)
![C990A67441C4947DA4FA451DE5C219D9](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/174427654/4644f0be-cb78-4677-85e9-031192b4e964)
![QQ截图20240702161529](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/174427654/9108c0be-6c39-43fb-86de-4bdb675e0542)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b4732385eaaf4dbc803aa36bd3522f2d

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-836

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by EasyMochi** [comment]
I can confirm the same behaviour on a Paper 1.21 server
