### ISSUE TITLE
FAWE commands stop working: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#2820]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

When a player cleared their plot the console spammed errors and all worldedit related commands stopped working for players. The server continues to run but worldedit basically stops functioning.
Log: https://mclo.gs/QDKRdnE

![Untitled](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/10485646/be851a98-ec2d-46b6-8010-62f3bc515ee7)

I was not able to use the debugpaste command because of this.

### To Reproduce

1. Not sure

### Expected behaviour

WorldEdit commands should still work

### Fawe Debugpaste

Unable to use fawe commands when this occurs

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-818

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
Your OS doesn't allow the minecraft server process to create more threads. That typically comes down to a rather restrictive limit. We can't really do anything about that, but you can configure FAWE to create less threads if you have that limit for a specific reason and want to stick with it.

**Comment by SecretlyJealous** [comment]
> Your OS doesn't allow the minecraft server process to create more threads. That typically comes down to a rather restrictive limit. We can't really do anything about that, but you can configure FAWE to create less threads if you have that limit for a specific reason and want to stick with it.

Oh I've never had to mess with that before, the limit is currently: 513611 (I used cat /proc/sys/kernel/threads-max to check this value) and it's not something I've ever touched. Is this limit too low?

**Comment by SirYwell** [comment]
That limit sounds reasonable. I'm not sure if it applies to all threads created during the lifetime of the process or only the ones currently alive. In the case of the latter, there might be some other plugin/functionality causing too many threads to be created. In that case, creating a thread dump using `jstack` might be insightful.

**Comment by dordsor21** [comment]
I believe there is a "per process" max threads somewhere which could be different too

**Comment by dordsor21** [comment]
Guessing this hasn't occurred again? Not sure it was explicitly an FAWE issue. FAWE does create a few threads but likely it coincided  with a couple of other rare things going on with the OS

**Comment by SecretlyJealous** [comment]
> Guessing this hasn't occurred again? Not sure it was explicitly an FAWE issue. FAWE does create a few threads but likely it coincided with a couple of other rare things going on with the OS

It has not occurred since, I'll mark this issue as closed since I don't think it's related to FAWE
