### ISSUE TITLE
//regen throws error in 1.21

### ISSUE THREAD

**Issue by JoeTheOrangeCat** [IntellectualSites/FastAsyncWorldEdit#2821]
### Server Implementation

Spigot

### Server Version

1.21

### Describe the bug

I make a selection and do //regen, this is 1.21, but that listed as supported here: https://ci.athion.net/job/FastAsyncWorldEdit/ but isn't selectable as version here.

### To Reproduce

Break blocks then do //regen on a selection

### Expected behaviour

It regens from chunk generation.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/23b3b9f157a34506a6b350faa7969620

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-836.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Note: That not only applies to the named field in the Error but has quite a few underlying issues

**Comment by dordsor21** [comment]
Just gonna leave #2818 open to track regen for 1.21 in general
