### ISSUE TITLE
//extinguish not working on paper fork

### ISSUE THREAD

**Issue by DaddyRobLIVE** [IntellectualSites/FastAsyncWorldEdit#2828]
### Server Implementation

Paper - Forked (SparklyPaper)

### Server Version

1.20.5/6

### Describe the bug

I'm using this fork > https://github.com/SparklyPower/SparklyPaper
And whenever I use //extinguish this error comes out
![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/109517972/450ca08e-75be-459a-82ab-a1a46218a1ea)

Detailed error log > https://mclo.gs/BuDZ09Q

### To Reproduce

1. Install SparklyPaper > https://github.com/SparklyPower/SparklyPaper
2. Install FAWE
3. Do //extinguish

### Expected behaviour

//extinguish should clear out nearby fires without errors

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/109517972/71ccbfbd-99aa-4c06-a2da-f983cf009189)

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/109517972/d3ee02ac-22de-4a5b-8f19-cc114b92d6c3)
![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/109517972/e93cf2f0-27bf-4837-96e1-7d815942d62e)

### Error log (if applicable)

https://mclo.gs/BuDZ09Q

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d4b4845fb59e4be09fb002aa0c377def

### Fawe Version

2.11.1-SNAPSHOT-844;ef064cb

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Thanks for your hard work on developing this plugin!in

**Comment by SirYwell** [comment]
The problem is CoreProtect.

**Comment by DaddyRobLIVE** [comment]
What seems to be the problem with coreprotect?

**Comment by OneLiteFeather** [comment]
https://github.com/SparklyPower/SparklyPaper
Well the fork aims to be similar like Folia and tries to do the hacky async stuff with parallel world ticking
https://github.com/SparklyPower/SparklyPaper/blob/ver/1.20.6/docs/PARALLEL_WORLD_TICKING.md

which is experimental. @SirYwell

**Comment by PierreSchwang** [comment]
CoreProtect attempts to access the Bukkit World in the ExtentEvent - which should not be guaranteed to be called synchronously: https://github.com/PlayPro/CoreProtect/blob/master/src/main/java/net/coreprotect/worldedit/WorldEditLogger.java#L150
