### ISSUE TITLE
Partial Paste execution after other actions

### ISSUE THREAD

**Issue by janLindner** [IntellectualSites/FastAsyncWorldEdit#283]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://pastebin.com/XuhJEDjM
https://pastebin.com/6qLz3Ckh

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit 1.14.4 - Build 152

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-230

**[REQUIRED] Description of the problem:**

1. Paste a selection
2. Build something within the pasted boundaries
3. Use any worldedit command (we used //set //stack or //fill) 
--> The initial pasted selection will be pasted again (No feedback in chat to this action)

The paste then was always just partial. --> In a radius around the new worldedit action.

**How to replicate**:
We did not find a reliable way to reproduce it. But it occured several times using the just mentioned steps. 

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by janLindner** [comment]
Debug Paste after on of this errors occured: https://athion.net/ISPaster/paste/view/955616c287c14880bb67fb968591dbe7

**Comment by dordsor21** [comment]
This is likely fixed
