### ISSUE TITLE
"java.io.IOException: This schematic version is not supported; Version: -1, DataVersion: -1. It's very likely your schematic has an invalid file extension, if the schematic has been created on a version lower than 1.13.2, the extension MUST be `.schematic`, elsewise the schematic can't be read properly."

### ISSUE THREAD

**Issue by thedankeststorm** [IntellectualSites/FastAsyncWorldEdit#2832]
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

When attempting to load the schematic that was converted from litematica using Lite2Edit tool, this error shows up. Original WorldEdit could load it just fine.

### To Reproduce

1. Grab a .litematic and convert it using this tool: https://github.com/GoldenDelicios/Lite2Edit
2. A .schem file is then output from the software. Put it into FAWE's schematic plugin folder
3. On the server, attempt to load the schematic file

### Expected behaviour

The schematic file should be loaded.

### Screenshots / Videos

![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/17909070/8f709667-20b3-475f-b56f-17252ce9b600)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f52416d18e1743a08943650cb436d596

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-846

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

The issue also happens on 1.20.4 MC version of FAWE, not just this version. I didn't have time to report this error back then.

**Comment by thedankeststorm** [comment]
When loaded using WorldEdit, it can load and paste without any issue.
![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/17909070/8b35518b-ca88-4878-a535-287f7d71ae3d)

**Comment by thedankeststorm** [comment]
The schem file if needed further testing.
[House.zip](https://github.com/user-attachments/files/16162704/House.zip)

**Comment by dordsor21** [comment]
Either incorrectly used or a v3 schem (so therefore now fixed)
