### ISSUE TITLE
Undo / Redo not working properly

### ISSUE THREAD

**Issue by Mvkbesteu** [IntellectualSites/FastAsyncWorldEdit#2840]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

So basically whe i paste something, and i want to remove it by using //undo, it just doesnt undo it, or it undos it and corrupts the build by splitting it in half, only undo-ing 30% of it / etc. I do not have this issue on localhost, only when i build on a server, i don't believe is a spigot issue or anything is very odd, i tried updating the plugin and server s
pigot to the latest, but didnt fix anything, however on localhost same files, same configs, it works perfectly. Any idea why?

### To Reproduce

//copy something, //paste, //undo

### Expected behaviour

It should undo the whole build, not a percentage of it, is like it forgets the build i just pasted. 

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/b1c7ba6e-c290-4e95-8e74-d0ff86136d5d)
![image](https://github.com/user-attachments/assets/0b635c12-5519-4530-b1de-5bb858621b35)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/21059c683ff9495bafea156aeb321b37

### Fawe Version

FastAsyncWorldEdit 2.11.0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
When you test locally are you using Oraxen? It's caused several other issues with FAWE in the past

**Comment by Mvkbesteu** [comment]
> Member

yes, i am using oraxen, same plugins and configs the same, is a server copy but on my local.

**Comment by dordsor21** [comment]
What happens without Oraxen on the server? Also try without Lands, BiomeManager, RealisticSeasons and Codex (i.e. any plugins that show WorldEdit or FAWE as a dependency in the debugpaste). There could be a silent error with one of those plugins.

**Comment by Mvkbesteu** [comment]
> What happens without Oraxen on the server? Also try without Lands, BiomeManager, RealisticSeasons and Codex (i.e. any plugins that show WorldEdit or FAWE as a dependency in the debugpaste). There could be a silent error with one of those plugins.

still the same, those plugins shouldn't affect anything since im not even inside any of those region.

**Comment by dordsor21** [comment]
> Can confirm on latest build with 1.20.4. Some chunks get processesed and some not.

Please also provide a debugpaste, and identify which command/s the history does not work for

**Comment by BGBrad** [comment]
I am having the same problem (here recreated with FAVS stencils but occurs also with pure FAWE commands)
![2024-07-31_17 53 45](https://github.com/user-attachments/assets/c0b1383c-e6e9-4c35-a2a3-c9bd8a03f8ca)
![2024-07-31_17 53 55](https://github.com/user-attachments/assets/ceb3e75c-6a4c-4efa-8784-8e0f736ed602)

Here is the debugpaste https://athion.net/ISPaster/paste/view/7847ccb527584114b3a16a72e783f0bb

**Comment by OneLiteFeather** [comment]
Well the issuer of this post used pufferfish 1.20.2, that is not supported, just as a notice

**Comment by BGBrad** [comment]
Should I open a new issue ?

**Comment by dordsor21** [comment]
No, there's a number without pufferfish also providing information.

**Comment by BGBrad** [comment]
Hello, just a quick update: I installed the latest FAWE version (2.11.2) and it looks like the issue is now gone.

**Comment by OneLiteFeather** [comment]
great to know!
