### ISSUE TITLE
1.8 Branch - Java 21 Support

### ISSUE THREAD

**Issue by linsaftw** [IntellectualSites/FastAsyncWorldEdit#2843]
### What feature do you want to see added?

There are modern 1.8.8 forks like FlamePaper that now allow the usage of Java 21 on Minecraft 1.8.8, but this plugin does not support it but only running on java 8. Make a branch out of the 1.8.8-1.12 release and commit a update to support all Java versions, thus allowing the usage of modern Minecraft 1.8.8 software.

### Are there any alternatives?

No.

### Anything else?

We are currently developing a big network, if someone with experience with this source could give us some tips on where is the last 1.8.8-1.12 commit and where are the Java checks, we could solve it ourselves and make a fork in a different repo for 1.8 FAWE. ¡Thanks!

**Comment by dordsor21** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit-Legacy is the old 1.12 code
