### ISSUE TITLE
Problem with Region-restriction

### ISSUE THREAD

**Issue by jaboy** [IntellectualSites/FastAsyncWorldEdit#285]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/b34010b04c754409bbf503e69ba0f060

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
[19:20:07] [Craft Scheduler Thread - 3/INFO]: &7FastAsyncWorldEdit-159 created by Empire92
[19:20:07] [Craft Scheduler Thread - 3/INFO]: &7FAWE version:
 - Date Dec 11, 2019 12:00:00 AM
 - Commit fe1f1d65
 - Build 159
 - Platform bukkit
[19:20:07] [Craft Scheduler Thread - 3/INFO]: &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[19:20:07] [Craft Scheduler Thread - 3/INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.14-159;1e0e29b)

[19:20:07] [Craft Scheduler Thread - 3/INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 

```
[19:20:00] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-56f8471-3e3818b (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[19:20:00] [Server thread/INFO]: This is a final build for 1.14.4. Please see https://www.spigotmc.org/go/1.14.4 for details about upgrading.
```

**[REQUIRED] Description of the problem:**

On a fresh server install, fresh FAWE and fresh Luckperm, then FAWE will refuse to work.

This only happens when the config setting "region-restrictions" has been set to true, which is the default setting for the plugin.
With "region-restrictions" set to false.
Or
If giving a user the permission node "fawe.bypass.regions".
then FAWE will work as intended.

(This attempt was made through waterfall(bungee), with the spigot.yml changed to allow for bungee connections) 

**How to replicate**:

Install a new server, and only put fawe and luckperm on it.
Start and restart the server to make fawe and luckperm make all necessary files.
do the 2 following commands to setup luck perms.
lp user weboy permission set *
lp user weboy permission set fawe.bypass false

Attempt to use //pos1, //pos2 then //set stone.

FAWE reports "(FAWE) Operation completed." but no blocks are placed.

**Plugins being used on the server:**

LuckPerms, (Dummy)WorldEdit, FastAsyncWorldEdit

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment]
did you set the basic permissions in lp fawe.permpack.basic

**Comment by jaboy** [comment]
As you see in "how to replicate"
the 2 following commands was run
lp user weboy permission set *
lp user weboy permission set fawe.bypass false

the "set *" will give the fawe.permpack.basic.

And included in the debugpaste, there is also a "lp verbose on" running in the latest.log while i attempt to do the worldedit commands, it shows all the permissions that was checked.

**Comment by Tsoccerguy3** [comment]
I was asking , because we cant get Paper 1.15.1 , LP ver5.23 and FAWE 1.15 b8 to work at all with players .OP works , I'll open a new issue , but i think that FAWE needs to be compiled with the LP ver5 API . I gave up trying to get permissions working with the 1.14.4

**Comment by jaboy** [comment]
i was told specifically to use luckperm
https://discordapp.com/channels/268444645527126017/344128526435221505/650484641857536011

You can attempt to turn off the Region-restriction, its in the fawe config about 3 from the top, after the 6 that says dont configure.

If that works, reenable the region restriction, and give yourself the permission "fawe.bypass.regions", if that works, then it seems you have been affected by the bug described in this issue.

**Comment by Tsoccerguy3** [comment]
I set region restrictions to off . Only OP works with FAWE 1.15 . I am almost positive FAWE permissions will not work with LP ver5 , until FAWE code updates to the new ver5 LP API

**Comment by aurorasmiles** [comment]
Is this still an issue?
