### ISSUE TITLE
schematic format detection not working

### ISSUE THREAD

**Issue by oncoursemail** [IntellectualSites/FastAsyncWorldEdit#2854]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

The bug I've discovered is that it can't find the file when trying to load a scheme.

### To Reproduce

//schematic loadall or load Loma.schematic
or
//schematic loadall or load spawn.schem

### Expected behaviour

(FAWE) Schematic Loma.schematic does not exist! (false|null|false)
(FAWE) Schematic spawn.schem does not exist! (false|null|false)

### Screenshots / Videos

![Screenshot 2024-07-26 171435](https://github.com/user-attachments/assets/1642b438-5700-45fa-8a14-63195338cd02)
![Screenshot 2024-07-26 171446](https://github.com/user-attachments/assets/c0d7ff52-e9f4-4f87-a7ce-728473f89c42)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0f032b315b804e818a8778838beed6a8

### Fawe Version

FastAsyncWorldEdit verison 2.11.1-SNAPSHOT-859;8c3df59

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I was discussing this issue in the discord with "pierreschwang".
They help find a temp solution and told me to make a ticket to look at the files as well.
[2024-07-26T22_18_35.zip](https://github.com/user-attachments/files/16397167/2024-07-26T22_18_35.zip)

**Comment by PierreSchwang** [comment]
For context: specifying the format explicitly using the formatName argument (mcedit / fast.2) works. The determination on nonExplicitFormat seems to not work as expected.

**Comment by ScrapMetalGolem** [comment]
Removing the file extension from the command (e.g. ```//schematic load Loma```) seems to work for me as a workaround.
