### ISSUE TITLE
Inability to ban patterns

### ISSUE THREAD

**Issue by PrOsToNiK13** [IntellectualSites/FastAsyncWorldEdit#2855]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

I banned a certain number of blocks in the config, for example, spawner. Players cannot place a spawner using //set spawner, but can do so using //set ##features_cannot_replace, where a spawner will randomly appear.  And as far as I understand, using fawe it is impossible to prohibit the use of certain patterns which causes unpleasant moments in which players gain access to prohibited items

### To Reproduce

1. You prohibit using a spawner in the config
2. You observe how //set spawner is inaccessible to you
3. Write //set ##features_cannot_replace
4. Enjoy life

### Expected behaviour

Either you need to be able to prohibit certain patterns, or you need to be able to completely prohibit meshing anything other than regular blocks.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7d2d074185a04c4598e053684f7df2d4

### Fawe Version

FastAsyncWorldEdit version 2.11.1-SNAPSHOT-836;15c6027

### Checklist

- [X] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
You need to use the `disallowed-blocks` list in a `limits` section. The list defined in the worldedit-config only applies to the command input, equally to how it is handled in WorldEdit.

**Comment by PrOsToNiK13** [comment]
I used the same prohibitions in both files. In limits I also have such a ban and it doesn’t work

**Comment by dordsor21** [comment]
You need to list the actual blocks in disallowed-blocks, not the category
