### ISSUE TITLE
passenger entity disappears after copy paste operation

### ISSUE THREAD

**Issue by LedariaTim1** [IntellectualSites/FastAsyncWorldEdit#2859]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

Initial situation: freshly installed Paper 1.21 server with the latest FAWE version (FAWE 2.11.1-SNAPSHOT-858) without any other plugins
when copying a area containing entities which ride entities (as an example a pig with a cow as a passenger) with the command //copy -e and subsequent pasting with //paste -e the upper entity is lost.

And in the console an error is printed.

Duplicate of #2091 but the bug still exists

### To Reproduce

create a clean paper 1.21 server and latest FAWE (FAWE 2.11.1-SNAPSHOT-858)
build a flat area
summon an entity with a passenger
/summon cow ~ ~ ~ {NoGravity:1b,Invulnerable:1b,NoAI:1b,Passengers:[{id:"minecraft:pig",NoGravity:1b,Invulnerable:1b,NoAI:1b}]}
select and copy the area with //copy -e
paste it to a free area with //paste -e

### Expected behaviour

I would have expected that at the inserted place also the entity with the passenger would be inserted again

### Screenshots / Videos

#2091

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/29f629b00f474dc3ac2d847b8a848483

### Fawe Version

2.11.1-SNAPSHOT-858;ddacb97

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Duplicate of #2427
