### ISSUE TITLE
//regen consistently taking around 10 minutes

### ISSUE THREAD

**Issue by ShinyJustyZ** [IntellectualSites/FastAsyncWorldEdit#2861]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Whenever I use a //regen command, regardless of the region size (I even tested with one chunk), it consistently takes around 650-680 seconds to process. On regular worldedit, it's done processing almost instantly. Is there a way to fix this? No errors show up in the console

### To Reproduce

1. Select any region size
2. Run //regen
3. Wait 650 seconds

### Expected behaviour

The regeneration is done almost instantly, like with regular worldedit

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/58ce889e4a144271ba9c623a229bc54b

### Fawe Version

FastAsyncWorldEdit version 2.11.1-SNAPSHOT-865;638344d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

It will say that I'm using Purpur, however I tested this with Paper also and it's the same issue.

**Comment by PierreSchwang** [comment]
That's kind of a backburner - Mojang and the Paper team changed world and chunk generation kind of tremendously in the last few versions. There is some kind of temporary logic which requires many more chunks to be generated - just for it to work. That's absolutely not the final solution, but the best we could and can currently offer. (There was some internal discussion re-using the WorldEdit way to regenerate, but there were a few reasons why we can't do that - but I don't remember the details)
