### ISSUE TITLE
Mojang-mapped bukkit plugin version

### ISSUE THREAD

**Issue by BoBkiNN** [IntellectualSites/FastAsyncWorldEdit#2862]
### What feature do you want to see added?

I want an ability to download mojang-mapped bukkit plugin jar that will load on paper 1.20.6+ without remapping

### Are there any alternatives?

When paper remaps plugin it takes 2 seconds. No alternatives found

**Comment by ShinyJustyZ** [comment]
This would probably be alot of work to save just 2 seconds. Is that really bothering you?

**Comment by anmvc** [comment]
> This would probably be alot of work to save just 2 seconds. Is that really bothering you?

Couldn't you just auto spin up a server just to remap every single time?

**Comment by Zoriot** [comment]
I think it would be worth it. Mojang Mapped is the Future i guess

**Comment by anmvc** [comment]
But that also kinda kills spigotmc

**Comment by Zoriot** [comment]
> But that also kinda kills spigotmc

As far as I know you can remap it via gradle plugin. So it should be easily possible to offer a "legacy spigot build"
