### ISSUE TITLE
Schematics dont remember their positions

### ISSUE THREAD

**Issue by Teslicek** [IntellectualSites/FastAsyncWorldEdit#2864]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

When you load a schematic on 1.21 and then paste it using //paste -o, the schematic forgets its position and gets pasted to 0, 0, 0.

### To Reproduce

1. Launch the server on 1.21
2. Select & copy an area -> //copy
3. Save the area as a schematic -> //schem save
4. Load the schematic using -> //schem load
5. Type //paste -o -> it will get pasted at 0, 0, 0

### Expected behaviour

Schematics should remember their positions, just like clipboard.

### Screenshots / Videos

https://github.com/user-attachments/assets/a1ff1693-3c18-4a6f-89e2-eb7b28261363

### Fawe Debugpaste

Can give in Discord DMs

### Fawe Version

2.11.1-SNAPSHOT-865;638344d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Does `//place -o` work? (I think pasting without transform and masks should use the place logic internally)

**Comment by Teslicek** [comment]
No, not even //place -o works. It still pastes it at 0, 0, 0.

**Comment by PierreSchwang** [comment]
Works for me without any issues, can you provide the Debugpaste please.

**Comment by PierreSchwang** [comment]
For a temporary workaround, use `//schem save <filename> fast.2` for saving the schematic. Loading and pasting should work with that then.

**Comment by dordsor21** [comment]
Origin is never read from the schematic it looks like. Probably also worth writing the FAWE version into the schematic if the WorldEdit version is not already specifically the FAWE version

**Comment by PierreSchwang** [comment]
> Origin is never read from the schematic it looks like. Probably also worth writing the FAWE version into the schematic if the WorldEdit version is not already specifically the FAWE version

Tried yesterday, but couldn't get the math working in my head. 

The version is defined implicitly, as the platform is prefixed with IntellectualSites.

**Comment by dordsor21** [comment]
Origin = clipboard min position and offset = offset from the origin where the schematic was taken iirc

**Comment by PierreSchwang** [comment]
> Origin = clipboard min position and offset = offset from the origin where the schematic was taken iirc. Should be enough just to track through where the WEOffsetXYZ from V2 goes I suppose

Yeah, I know - I did exactly that. The paste position was seemingly right, but the offset inside the clipboard was not working I would say - at least no blocks were pasted
