### ISSUE TITLE
Ghost blocks, after removing the schematics

### ISSUE THREAD

**Issue by X1aLeXO** [IntellectualSites/FastAsyncWorldEdit#2865]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Hello everyone. I use a plugin for airdrops - "BairDropX". This plugin allows you to insert schematics together with the airdrop, and delete them later. So, when the event ends and it's time to remove the schematics, it does not visually disappear, and everything consists of ghostly blocks
The developer of the "BairDropX" plugin claims that the problem is on the side of your plugin. And also, if you use "WorldEdit", then the schematic is quietly deleted. But "WorldEdit" doesn't suit me!

### To Reproduce

I don't know what to write here)

### Expected behaviour

I expected a complete removal of the schematics, without ghost blocks

### Screenshots / Videos

I'm showing you clearly. (The command I use on the video /bair unsafe reload just disables all events). I live in Russia, so I don't pay attention to the text - https://drive.google.com/file/d/1C5SXQ-oCIx7DuRBL3lkbAQ9Ns3YJS7Mq/view?usp=sharing

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4c7b1e515545453ebdde8029af0f8544

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-865

### Checklist

- [x] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment]
Looks like the BairDropX plugin is not closing/using the editsession properly. It could also be an issue with PurPur, I would also try on Paper instead of PurPur

**Comment by X1aLeXO** [comment]
I can write about this directly to the BairDropX developer. As for using Paper, I'm unlikely to be able to try it in the near future, and I don't plan to switch completely to Paper.

**Comment by X1aLeXO** [comment]
I can write about this directly to the BairDropX developer. As for using Paper, I'm unlikely to be able to try it in the near future, and I don't plan to switch completely to Paper.

**Comment by dordsor21** [comment]
Looking at the plugins it could also be as a cause of using ViaBackwards/Version // connecting with a client of a different server.

**Comment by X1aLeXO** [comment]
It's just that the proposed solutions to this problem add new problems, and I can't remove viaversion/backwards. How to change the core. Honestly, I would like to get a less radical solution to this problem

**Comment by X1aLeXO** [comment]
I'm still waiting for a response from the BairDropX developer. But first I would like to clarify. Will it be possible to fix this problem at all without removing plugins, changing the server core and other things that will interfere with the server's operation?

**Comment by dordsor21** [comment]
If it's that the EditEditsession is not being closed/used properly, should be easy. Otherwise, I don't know there's much that can be done if the chunk packets are being blocked, unless someone wants to dig around in ViaVersion/Backwards. If it's PurPur, then they should probably fix it themselves

**Comment by X1aLeXO** [comment]
As a result, the problem was on the BairDropX side, the developer fixed it, after a full explanation, when I passed your comment to him. Thanks!

**Comment by dordsor21** [comment]
Okay, great
