### ISSUE TITLE
1.21.1 is unsupported.

### ISSUE THREAD

**Issue by anmvc** [IntellectualSites/FastAsyncWorldEdit#2876]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

FAWE on 1.21.1 dies

### To Reproduce

Download FAWE
Run FAWE on a 1.21.1 server
Watch the log as FAWE errors

### Expected behaviour

FAWE Works fine on 1.21.1

### Error log (if applicable)

https://paste.gg/p/anonymous/8269e818cca440d88aa80aca48a4211c

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5bf665dbfcf1487b93f4f1f056577176

### Fawe Version

Latest

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Bobcat00** [comment]
I'm seeing the same thing with the same error messages.
