### ISSUE TITLE
Can't use //set.

### ISSUE THREAD

**Issue by MagoLione** [IntellectualSites/FastAsyncWorldEdit#2878]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

When i try to use //set stone command it gives me an error.

I use coreprotect.

### To Reproduce

Use //wand to get the we tool.
Select a region full of sand with the we tool.
Use //set stone command.
See the error.

### Expected behaviour

It'll gives you an error and makes the //set command fails.

### Error log (if applicable)

https://paste.gg/p/anonymous/23898e676f8b4c4ebb7df96b8ebbd1cf

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/051854e9421448dc84ee2ad7a230cbe2

### Fawe Version

FastAsyncWorldEdit version 2.11.1-SNAPSHOT-871;fcbd346

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PierreSchwang** [comment]
I've already answered you that: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2872

Don't create new issue without changing anything.
