### ISSUE TITLE
//cut not working; Requested operation cannot be performed on a file with a user-mapped section open

### ISSUE THREAD

**Issue by Owehttamy** [IntellectualSites/FastAsyncWorldEdit#2882]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

I tried using `//cut`. For whatever reason, it didn't want to do this one specific time. I selected a new area that cut just fine—simply a weird one-off.

### To Reproduce

- Log on
- Select a medium-sized cuboid area
- Do `//set air`
- Move to another area, select another tiny cuboid area
- Try `//cut`, which resulted in and ended up with an error

Unfortunately, I didn't do anything out of the ordinary, so I have zero leads as to what caused this bug. Sorry for the nothing-burger. :(
Looked through similar reports (#356, #1260, and #1909), but they all appear fixed with no signs as to user error, so maybe a new instance of this issue?

### Expected behaviour

`//cut` works and doesn't spit out an error.

### Error log (if applicable)

https://paste.gg/p/anonymous/7ab5c8ce45cd47d585f2bd4b5cedbf5a

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c2f7deccc3c64e3b87afba1aaabe4d9c

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.2-SNAPSHOT-879

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

All I did was log on, select a medium-sized cuboid area, do `//set air`, then move to another area, select another tiny cuboid area, then try `//cut` and ended up with an error. I didn't do anything out of the ordinary for me to theorize being a cause of the bug, so sorry for the nothing-burger.
Looked through similar reports (#356, #1260, and #1909), but they all appear fixed with no signs of user error, so maybe a new instance of this issue?
Running Paper version 1.21-122-master@58c7ea3 (2024-07-30T19:05:08Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
Only other plugins are DiscordSRV (1.28.0) and AxiomPaper (1.5.12)
> I DID NOT DO ANYTHING WITH AXIOM BEFORE; I DO NOT BELIEVE IT IS WHAT RESULTED IN THE ERROR

**Comment by PierreSchwang** [comment]
The error generally occurs when another process is accessing the file (in this case the clipboard). Do you mount the clipboard folder across multiple servers perhaps? That's generally nothing that'd be FAWEs fault imo

**Comment by Owehttamy** [comment]
> The error generally occurs when another process is accessing the file (in this case the clipboard). Do you mount the clipboard folder across multiple servers perhaps? That's generally nothing that'd be FAWEs fault imo

Nope. Just a single Paper instance. There is nothing fancy or unusual going on here. That is a good theory, though.
I _was_ using FAWE simultaneously with another player, so _maybe_ they were doing something with their clipboard—which should be completely independent of mine—but all-in-all, I'm assuming this must be some odd edge case where some process hangs when selecting and caching my clipboard.

**Comment by PierreSchwang** [comment]
Yeah, that is sadly nothing that can be reproduced in any way. My only guess would be that Windows Defender maybe locked the file while scanning - but no idea. If that happens again, feel free to re-open or create a new issue referencing this one.
