### ISSUE TITLE
FAWE LocalVectorSet limit causing me to be unable to hollow areas with vectors larger than 1024 blocks (cuboid) of the first entry

### ISSUE THREAD

**Issue by HopeJ-Personal** [IntellectualSites/FastAsyncWorldEdit#2897]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

If you attempt to hollow areas farther than 512 blocks out from pos1 (or 1024 blocks cuboid as in 1024 square centered on pos1) then the game will throw the following error LocalVectorSet can only contain vectors within 1024 blocks (cuboid) of the first entry. Unfortunately for me, this is stopping me from moving my build to my server as it has too many blocks to save as schematic (Attempting to save as schematic just sends, attempting to... please wait.) so what I felt the best next step was, was to hollow it out. However, doing so throws this error.
- My first support request on the discord server was on 8/21/2024 when I got on, did the commands I remembered had caused the issue, took screenshots, and wrote down the information.
- My second message in the support request channel on the discord server was on 8/24; On this date. I wrote down as much
information as possible and posted it to the following link
  - https://gist.github.com/Hope)-Personal/1383f2a3fdbb4accb35a19164ef6e6ba
- As of today (8/25/2024) I am attempting to make a better-formated support request and bug report to allow the developers to understand better what's happening. On top of this, I think I've found something that shocks me and begs the question, is this a bug report or a feature request

Please allow me to elaborate on the latest event further, I opened the GitHub repository, then clicked code and opened in vs. Once inside I opened Solution Explorer and searched locally as the error I got from the game/plugin/FAWE was referencing Local VectorSet and with my limited coding experience, I believe branded error messages are defined by the plugin not game as in they were purposely and thoughtfully written as a response to an already known error, leading me to search the error message and event that triggers it.

After making said search it revealed multiple files but the one that caught my eye was in <source code>\worldedit- core\src\main\java\com\fastasyncworldedit\core\math and was titled LocalBlockVectorSet.java: Within this file. I then searched once more in the file using ctrl+f (Control + F as in Control + Find) and searched for 1824 as the error message referenced the number 1024, and low and behold I found the error message and what looked to be the code causing/handling this issue or error message: This includes the check to see if a selection is over 1024 and if true it then cancels the operation and the code that throws the error message

### To Reproduce

# 1. Optional pos reset
### (To ensure both pos are reset before starting I will set them to 0,0,0 as in the past sometimes for some reason it will use
coordinates that aren't what I had set using the pos commands but this isn't necessary)
//pos1 0,0,0
//pos2 0.0.0

#2. Set positions for operation
### (a smaller area than desired for the final product, but it's just for testing as it is still larger than 1024)
//pos1 3012-64.372
//pos2 5059,125,-2360

### FAWE chat response:
(FAWE) First position set to (3012, -64, 372).
(FAWE) Second position set to (5059.125,-2360) (1063464960).

# 3. Run the hollow command
### (It should hollow out the region leaving a skin of 4 blocks width where the solid shape was)
//hollow 4

***FAWE chat response:
(FAWE) Your selection is large ((3012, -64, -523)-> (5059,125,-2360), containing 1062945690 blocks). Use //confirm to execute
/hollow 4

#4. Confirm command
### The plugin asks you to confirm so you use the confirm command to proceed
// Confirm

# 5. FAWE console response:
### FAWE sends some information in the console stating it will use 'Paper Weight's Starlight Relighter Factor' as the relighter
factory
[11:07:52 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_R1.PaperweightStarlightRelighterFactory as relighter
factory.

#6. Wait (in my case for 54.144 seconds)

#7. See Error
### Error Message in chat (Console Log with Error Message will be in separate link/attachment/attached file):
- (FAWE) Please report this error: [See console]
-(FAWE) java.lang.Unsupported OperationException: LocalVectorSet can only contain vectors within 1024 blocks (cuboid) of the
first entry. Attempted to set block at 4036, -63,-2360. With origin 3012 128-2360
-(FAWE) 54.144s elapsed (history: O changed; 0 blocks/sec)

### Error Message in console
-Separate link in the 'Error log (if applicable)" section

### Expected behaviour

The shape contained within the set positions ((3012, -64, -523)-> (5059,125,-2360)) should be hollowed out, and look the same on
the outside and 4 blocks in facing the center, then be hollow/filled with air.

#### In VS
![in-file-search-1](https://github.com/user-attachments/assets/b2c958ef-28a3-458e-8380-0ac87ca95b97)
![in-file-search-specified-1](https://github.com/user-attachments/assets/36c52d60-2e83-4bcd-adaf-979be3850ac9)
![in-file-search-specified-2](https://github.com/user-attachments/assets/9481304b-4497-44b5-ab98-028daf301df8)

#### Game
![image](https://github.com/user-attachments/assets/52828abf-a7fd-41c0-b2df-698afeee6062)
![image](https://github.com/user-attachments/assets/043164a5-03fc-4cc9-904b-98627e4fe67b)

### Error log (if applicable)

https://gist.github.com/HopeJ-Personal/f383f2a3fdbb4accb35a19164ef6e6ba

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ea6db2f8a79748adb9f6263e2cae50c4

### Fawe Version

FastAsyncWorldEdit version 2.11.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Nothing besides the fact that I'll post this in Discord in the FAWE support channel (shortened) with a link to this GitHub bug report so that if anyone wants to help from Discord they can go here and get more info. Hopefully, this gets solved or at least someone can help and allow me to do what I want to do :D

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by PierreSchwang** [comment]
I've locked this issue for now, as somehow a ton of spam bots are doing their thing rn here
