### ISSUE TITLE
//br smooth casues ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by StealWonders** [IntellectualSites/FastAsyncWorldEdit#292]
# Bug report for FastAsyncWorldEdit 1.15-12

**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/90022d51a35b4efdbe65eb5b61694643

**FastAsyncWorldEdit Version Number:** FAWE-4 (1.13.2 - 1.15.1)

**Paper Version Number:** git-Paper-236 (MC: 1.14.4)

**Description of the problem:**
When using the following brush: `//br smooth 10` and smooth some terrain you will get an `ArrayIndexOutOfBoundsException`.

The console displays the following when brushing:
`[15:32:16 WARN]: java.lang.ArrayIndexOutOfBoundsException`

**How to replicate**:
Use the described brush and smooth some terrain.

**Comment by aurorasmiles** [comment]
I just smooth'd down a complete hill in build 178 and did not get any exception. Maybe this has been fixed already

**Comment by StealWonders** [comment]
Possibly, I shall test.
