### ISSUE TITLE
Moving a selection is not possible due to an exception

### ISSUE THREAD

**Issue by paaulhier** [IntellectualSites/FastAsyncWorldEdit#2921]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

After selecting an region with //pos1 and //pos2 the region can not be moved with e.g. //move 2.

`This server is running Paper version 1.21.1-77-master@4ff58c4 (2024-09-12T18:05:09Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)`

### To Reproduce

1. select a region with //pos1 and //pos2
2. move it with e.g. //move 2

### Expected behaviour

The region should be moved 2 blocks

### Error log (if applicable)

https://gist.github.com/paaulhier/0cefe0f656f1c8a3a4cc446a921fe079

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4fd07396ace448469620f86711c7961b

### Fawe Version

2.11.3-SNAPSHOT-912;71b99f9

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
This is a problem in CoreProtect, not much we can do about that.
