### ISSUE TITLE
1.21.1 Disappearing items when dropped.

### ISSUE THREAD

**Issue by sennby** [IntellectualSites/FastAsyncWorldEdit#2937]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

I have been hunting this issue for quite some time. I did a full binary test and thought it was GP, further binary testing says it is FAWE. i just tested on the latest jenkins build as well with no luck. Basically under heavy heavy loads in a chunk/area (i believe), if you drop an item, it poofs completely. This has led to many spawners and items being poofed from players which is a very big issue, especially when some of the items are fully upgraded and take a ton of effort.

I fully binary tested this on 1.21.1 - I ran ONLY essentials, and FAWE latest. Im in a chunk where theres a redstone farm machine, spawner grinders, farms everywhere etc.

Shut off server - check plugins are only essentials and FAWE.
turn on server
join when it boots up
drop 1 by 1 items, all poof, after the chunk loads more and things catch up, you can drop them, but not a 100% success rate.
I tested this across probably 10+ boots with ONLY fawe, i did a pretty long binary test plugin by plugin.

### To Reproduce

Shut off server - check plugins are only essentials and FAWE.
turn on server
join when it boots up
drop 1 by 1 items ( i dropped 25 spawners), all poof, after the chunk loads more and things catch up, you can drop them, but not a 100% success rate.

### Expected behaviour

Items should never disappear. ever.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/cacfd998e813455a9e52ac75370faea7

### Fawe Version

[19:41:08 INFO]: FastAsyncWorldEdit version 2.11.3-SNAPSHOT-930;7192e14 [19:41:08 INFO]: Blazingly fast world manipulation for builders, large networks and developers. [19:41:08 INFO]: Website: https://www.spigotmc.org/resources/13932/ [19:41:08 INFO]: Authors: Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

senby8 is my discord if you would like to test on my server/dev server or have questions.

**Comment by SirYwell** [comment]
Disable the `tick-limiter` in the FAWE config

**Comment by sennby** [comment]
> Disable the `tick-limiter` in the FAWE config

fixed
