### ISSUE TITLE
High memory usage after commands with a big selection

### ISSUE THREAD

**Issue by PapiCapi** [IntellectualSites/FastAsyncWorldEdit#2938]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

After executing some commands, the GC takes a lot of time (because of a high memory usage ?).
As you can see on [this ](https://spark.lucko.me/WwzUsJxcKA)spark report everything is fine until some FAWE commands are executed (when the TPS drops).

### To Reproduce

![rose_port schem](https://github.com/user-attachments/assets/af2abb82-c1c1-4cbb-a5a3-13057135f67c)
- Get the schematic i supplied (this is a .jpg file because Github doesn't want me to upload a .schem)
- Paste it
- Select the whole region pasted with //pos1 and //pos2 
- Execute the following commands : 
//replace fire_coral_wall_fan 0
//replace bubble_coral_wall_fan 0
//replace brain_coral_wall_fan 0
//replace tube_coral 0
//replace tube_coral_wall_fan 0
//replace dead_brain_coral_wall_fan 0
//replace short_grass 0
//replace large_fern 0
- Wait a bit
- Open a spark profiler (/spark profiler open) and keep it open a bit if no noticeable spike is seen.
-> You should see the GC take a surprising amount of the server time

### Expected behaviour

Don't make the GC explode

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a69162cfa61b40df85b08bd24bed8c47

### Fawe Version

2.11.3-SNAPSHOT-930;7192e14

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by PapiCapi** [comment]
Here is the schem in a .zip because a .jpg doesn't seem to be usable 
[rose_port.zip](https://github.com/user-attachments/files/17267295/rose_port.zip)

**Comment by SirYwell** [comment]
Could you run the spark allocation profiler and share that too?

**Comment by PapiCapi** [comment]
> Could you run the spark allocation profiler and share that too?

What do you mean by the "spark allocation profiler" ?

**Comment by SirYwell** [comment]
e.g. `/spark profiler start --alloc --thread * --combine-all`

**Comment by PapiCapi** [comment]
Here is the spark output : https://spark.lucko.me/1v2qdHRqgv

**Comment by PierreSchwang** [comment]
Please try removing CoreProtect and see if the issue persists.

**Comment by PapiCapi** [comment]
> Please try removing CoreProtect and see if the issue persists.

I tried unloading CoreProtect using `plugman unload CoreProtect` and then reloading FAWE using `/fawe reload` and the lags are the same : https://spark.lucko.me/6ois4TN1Sr

**Comment by dordsor21** [comment]
You will need to restart the server. Unloading the plugin with plugman does completely disable a plugin's integrations. For that it's worth, this is what makes it obviously CoreProtect:
<img width="1887" alt="image" src="https://github.com/user-attachments/assets/a4e23f9c-2724-46fa-a7c9-2e3a4d1e0a02">

You should just not use CoreProtect for logging FAWE edits as it is poorly coded and puts all blocks into a massive queue to then write to its database. FAWE on the other hand already has integrated edit logging if using history on disk and enabling database, which does not cause massive memory overhead, and also does not slow edits down.

**Comment by PapiCapi** [comment]
As you said, the issue is fixed without CoreProtect !
Just a quick question about FAWE logging : does it allows me to see if a specific block at a specific location was edited and by who ? I've never heard about this feature so i'll definetely check into that :)

**Comment by dordsor21** [comment]
Yeah exactly that see https://intellectualsites.gitbook.io/fastasyncworldedit/features/main-commands-and-permissions#history-commands

You need history on disk enabled, database enabled, and delete disk history on logout disabled (there's a warning on startup for this)

**Comment by PapiCapi** [comment]
Great, thanks a lot for your help !
