### ISSUE TITLE
`//set oak_sign` places invisible signs

### ISSUE THREAD

**Issue by thomasmny** [IntellectualSites/FastAsyncWorldEdit#2944]
> Edit: After creating the issue I figured out this **also applies for player heads**

### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

Using `//set oak_sign` results in invisible sings being placed. However, `//set hand` whilst holding an oak sign does not result in this behaviour.

### To Reproduce

1. Select a region with `//pos1` and `//pos2`
2. Use `//set oak_sign`
3. Observe that the signs are invisible

### Expected behaviour

Signs are visible

### Screenshots / Videos

1) Using `//set oak_sign`

![2024-10-12_14 03 40](https://github.com/user-attachments/assets/2f0a1ed1-0223-4395-b572-7e8c787c2df9)

2) Using `//set hand` whilst holding an oak sign

![2024-10-12_14 05 07](https://github.com/user-attachments/assets/0d729755-25c3-404c-85f9-eaaf0d275f1d)

### Error log (if applicable)

None

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6758d277497f47b4ba4763c112768842

### Fawe Version

2.11.3-SNAPSHOT-934;b343be4

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

It's also worth mentioning that after having placed signs via `//set hand`(i.e. visible signs), then replacing the region to air (`//set 0`) and then undoing the action (`//undo`), then the signs are invisible. No error in console

**Comment by SirYwell** [comment]
I can't reproduce your issue, but that might come down to client mods I'm using. What I noticed is that using `//set hand` causes my client to lag while the signs appear (both rendering and packet sending seems to be impacted, as can be seen when using `F3 + 2`/`F3 + 3` and even afterwards just looking at the signs causes significant fps drops. None of that is the case with `//set oak_sign`. I'll try without mods, but it definitely looks like there's a difference it what information the client gets.

**Comment by SirYwell** [comment]
Without mods, the client performance totally tanks when looking at the signs placed using `//set hand`, and the ones set using `//set oak_sign` are invisible.

**Comment by Tsoccerguy3** [comment]
I tried //set oak_sign and got a lot of errors
https://athion.net/ISPaster/paste/view/f0f2358181f64234bc7bd54c1e571976
