### ISSUE TITLE
No-permission player actions throw stacktraces [1.15.1]

### ISSUE THREAD

**Issue by voodootje0** [IntellectualSites/FastAsyncWorldEdit#295]
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-12 created by Empire92
FAWE version:
Date Dec 23, 2019 12:00:00 AM
Commit faf3e60b
Build 12
Platform bukkit
Bukkit-Official(1.15-12;50c19f5)

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-27 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
https://haste.jartexnetwork.com/xuqacepowu.sql

**How to replicate**:
Simply start a new 1.15.1 with FAWE, give a non-operator player access to world edit, and he won't be able to use it.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Right. I tested Build 13 and only a staff can use FAWE Commands on plotsquared.

It's like the normal player hasn't the permission, but FAWE show a normal output-messages like "operation completed."

https://pastebin.com/mR5U6zca

**Comment by aurorasmiles** [comment]
Is this still an issue with the latest version?

**Comment by aurorasmiles** [comment]
No answer, assuming this is fixed
