### ISSUE TITLE
Replacing walls with fences keeping equal block states throws error

### ISSUE THREAD

**Issue by Infinite-Blocks** [IntellectualSites/FastAsyncWorldEdit#2961]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

An IllegalArgumentException is thrown when replacing walls with fences keeping equal block states.

### To Reproduce

1. Place any type of wall
2. Attempt to replace the wall with any type of fence of equal block state with `^`

### Expected behaviour

Connected fences replace the walls with equal block states as they do in reverse when replacing fences with equal block state walls.

### Error log (if applicable)

https://paste.gg/p/anonymous/880e3ccb23ac4171a071549e7a1eedb6

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/598f6942863948ec897815d43c9b5880

### Fawe Version

2.12.1-SNAPSHOT-949;c252850

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

The latest version was installed after reading the checklist points.

**Comment by SirYwell** [comment]
Note that the block states can't be "equal". The north/east/south/west properties on walls allow none/low/tall while they only allow true/false for fences. So there won't be any mapping between them.

**Comment by Infinite-Blocks** [comment]
Correct, I understand. Since the developers were able to implement the reverse when replacing fences with "equal" block state walls by adding, I assume, default block states for the missing properties of none/low/tall, I thought fences could ignore the walls additional block states instead of throwing an error.
Thank you for the fix.
