### ISSUE TITLE
New set blocks not rendered in previously empty chunks

### ISSUE THREAD

**Issue by shaijana** [IntellectualSites/FastAsyncWorldEdit#2989]
### Server Implementation

Paper

### Server Version

1.21.3

### Describe the bug

When using //set (or similar commands) with the latest versions of Paper and FAWE, block changes are not rendered correctly in chunks that were previously empty. However, after relogging, the changes appear as expected.

This issue does not occur when using a Fabric client with Sodium installed. The error also occurs with the latest version of Spigot.

### To Reproduce

1. Create a server with the newest snapshot of paper and fawe and their default config.
2. Start a vanilla client.
3. Select two cornors in empty chunks and use //set 1.

### Expected behaviour

The block change should be visible .

### Screenshots / Videos
![image](https://github.com/user-attachments/assets/93a95805-dce6-4705-95e5-5a64d7b5ef5f)

https://youtu.be/q_Qc5Eex8Q8

### Error log (if applicable)

No errors reported

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f90b1418834f4c7daeeedfbee191525e

### Fawe Version

2.12.1-SNAPSHOT-964

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by northeastprince** [comment]
Can replicate, same versions.
