### ISSUE TITLE
Custom schematic folder config option or file link read processor

### ISSUE THREAD

**Issue by Infinite-Blocks** [IntellectualSites/FastAsyncWorldEdit#2992]
### What feature do you want to see added?

I would like to see the feature of a custom file path option in the FAWE config added. This would be great for organizing and syncing a personal library on a localhost or shared cloud without duplicates.

### Are there any alternatives?

Alternatively, I could imagine FAWE being able to process links .lnk (Windows) to load schematics from.

### Anything else?

The Microsoft store offers several folder sync apps.

**Comment by dordsor21** [comment]
It already exists in the worldedit-config.yml
