### ISSUE TITLE
FAWE ошибка 

### ISSUE THREAD

**Issue by Sqw6qq** [IntellectualSites/FastAsyncWorldEdit#2993]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

(версия 1.16.5, там не было варианта)
FAWE работал, но в какой-то момент перестал. В плагинах он подсвечивается зелёным, но не работает. На сервере также есть PlotSquared (у меня режим Креатив) и WorldGuard. Я пытался скачать самые новые версии, но везде одно и то же. Скачал буквально все версии, но ни одна из них не заработала. Вот логи, может, там есть ответ на мою ошибку https://pastes.dev/bZiUaXtyg9

### To Reproduce

1. Зайти на сервер. 2. Написать команду //cyl (или другие команды с сетом) 3. Получение ошибки посмотрите в консоль (я логи скинул)

### Expected behaviour

Команды должны работать, ведь они работали ранее. А сейчас нет.

### Screenshots / Videos

![2024-11-17_04-59-38](https://github.com/user-attachments/assets/5cabf2f0-50b7-41e5-ae91-9522a5441910)

### Error log (if applicable)

https://pastes.dev/bZiUaXtyg9

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ead258c8ce6e4db393c622e235973619

### Fawe Version

FastAsyncWorldEdit Bukkit 2.12.0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Пытался переустановить плагин, ничего не работало. Пытался удалить папку плагина, не работало.

**Comment by PierreSchwang** [comment]
> This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Unsupported

**Comment by Sqw6qq** [comment]
она ж поддерживалась сегодня, но резко перестала

**Comment by PierreSchwang** [comment]
The issue is the underlying server software, which does not provide a library with its expected version. Using the latest build should fix that ig, but still - that version of FAWE and your server is not supported. We can't change anything about that.

**Comment by HauserGrim** [comment]
https://modrinth.com/plugin/fastasyncworldedit/version/2.8.2
