### ISSUE TITLE
Rotate doesn't work with NBT data

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#302]
**FastAsyncWorldEdit Configuration Files:** 
config.yml: https://pastebin.com/ujeAs9cC
config-legacy.yml: https://pastebin.com/46pr1EFy
logs/latest.log: https://pastebin.com/vhBTiFQY

**FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-13 created by Empire92
FAWE version:
 - Date Dec 25, 2019 12:00:00 AM
 - Commit f6102278
 - Build 13
 - Platform bukkit
[19:16:13 INFO]: &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
------------------ Platforms ------------------
* Bukkit-Official(1.15-13;9efdd88)

---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-32 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Description of the problem:**
If you rotate blocks with NBT data (chests, custom heads or signs) they will appear as invisible blocks after pasting. Chest contents are also lost in the process.

**How to replicate**:
1. //copy a chest with any content
2. //rotate 90
3. //paste

**Plugins being used on the server:**
https://pastebin.com/Tsn1XUWp

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.1]
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
I was able to replicate the issue with the latest build 144 on paper 146. Also, not only chests are empty, but for example sign texts are also gone

**Comment by dordsor21** [comment]
Fixed in 76efbed4b2881b797c91c925513b6c7a276460f2
