### ISSUE TITLE
Schematic Pasting Workaround

### ISSUE THREAD

**Issue by A-Chicken-Nugget** [IntellectualSites/FastAsyncWorldEdit#309]
_This is not an issue, just a feature request to inform anyone who may find this useful_

**_Explanation:_**
So I've seen a lot of people having problems with their schematics not being pasted properly in the newest version of FAWE. I myself had this problem and it was a major issue for my server as it will work off of schematics being pasted for game worlds. I noticed that when I copied large areas and pasted them, they would paste just fine and still be async of course. But when I saved that copied area as a schematic and attempted to load/paste it, it will completely break. With this in mind I attempted to find a way to replicate the player copying/pasting with code. I noticed that the players clipboard is saved in a .bd file, so I saved the .bd file for my copied schematic where I wanted my schematics to be saved. Then I dug through the source code of FAWE trying to find a way to load a .bd file and paste it. After a good bit of digging/trying A LOT of things I managed to find a working solution that fixes my issue perfectly.

_**Workaround:**_
The first step is to copy each schematic you would like to save one by one. Each time copy the saved .bd file in the plugins/FastAsyncWorldEdit/clipboard/{your unique id} to where ever you would like to store your schematics.

Next use the following code to paste that schematic:
`DiskOptimizedClipboard clipboard = new DiskOptimizedClipboard(new File({path to .bd file}));`
`clipboard.paste(new BukkitWorld(Bukkit.getWorld({world name})),BlockVector3.at(x,y,z),false,false,null);`
`clipboard.close();`

I hope this helps!

**Comment by dordsor21** [comment]
Schematic pasting is now working using `use-disk: false` for clipboards. The issue with using disk is very embedded into the code as the clipboard disk file does not get closed properly.

**Comment by dordsor21** [comment]
This is fixed

**Comment by aurorasmiles** [comment]
Since this is closed (and fixed) - could someone "unpin" it?

**Comment by redbrain** [comment]
Maybe you should unpin this?
