### ISSUE TITLE
Multiple people editing with heightmap causes mixup when undoing.

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit#31]
![2019-01-16_19 57 34](https://user-images.githubusercontent.com/22693741/51290362-40ee7100-19c9-11e9-8fd1-09d9d316bf7f.png) <<< FLat Ground

![2019-01-16_19 58 00](https://user-images.githubusercontent.com/22693741/51290368-48ae1580-19c9-11e9-99c7-a48af879630d.png) << Player a uhses brush
![2019-01-16_19 58 25](https://user-images.githubusercontent.com/22693741/51290379-51065080-19c9-11e9-9d16-3abb0fa4728d.png) <<< Player B uses brush

![2019-01-16_19 58 36](https://user-images.githubusercontent.com/22693741/51290397-5b284f00-19c9-11e9-967e-fb45457dc8db.png) <<< PLayer A undoes

![2019-01-16_19 58 46](https://user-images.githubusercontent.com/22693741/51290404-624f5d00-19c9-11e9-99c9-225cb8d2e93a.png) <<< Player B undoes

Blocks are left over

using @IronApollo Vector update

**Comment by RealmportalMC** [comment]
This probably extends beyond heightmaps

**Comment by dordsor21** [comment]
We've had many undo fixes, presume fixed?
