### ISSUE TITLE
Connections Command

### ISSUE THREAD

**Issue by CJCrafter** [IntellectualSites/FastAsyncWorldEdit#313]
# Issue
Whenever you paste in a block with connections (Example: `//paste spruce_fence`, `//replace air iron_bars`), the block **does not have any connections**.

# Solution
I would like a `//update` command. This would update every single block in a region and **set connections** if it should have connections.

Alternate explanation:
```
foreach (x in region)
    foreach (y in region)
        foreach (z in region)
            if (block can have connections) update connections
        rof
    rof
rof
```
Need a 3rd one? From this:

![](https://cdn.discordapp.com/attachments/633356310192062504/663506638929395806/2019-12-21_17.37.17.png)

to this:

![](https://cdn.discordapp.com/attachments/633356310192062504/663506690469265409/2019-12-21_17.37.25.png)

# Extra
Possible arguments are `//update dir[south,west,north,east]` which could specify which directions are allowed.

Blocks that should have connections:
* Stairs
* Fences
* Walls
* Bars
* Glass

**Comment by CJCrafter** [comment]
#### Paintsplatters suggested to add:
```
//paste -u
```
(Or maybe `-update`)
---
This would essentially run `//paste` then `//update`, effectively **automatically updating** every block inside the Player's clipboard, **and** pasting.

**Comment by Zeswen** [comment]
What about **stairs**? How can you know these are facing forwards/backwards?
> Case 1: 
![image](https://user-images.githubusercontent.com/37448151/72439115-9446fb00-37a6-11ea-9794-84e0d877dbfb.png)

**Comment by RedstoneFuture** [comment]
Basically I like this idea. No matter all praxis problems at here. Maybe the normal direction check are simple to implement.

> This would essentially run `//paste` then `//update`, effectively **automatically updating** every block inside the Player's clipboard, **and** pasting.

Bukkit has more than one update behaviors, as I know. So it needs tests to find the right may to update the blocks correctly.

**Comment by VL4DST3R** [comment]
I see a pull request for this has been made for a while now, when will it be merged? This is one of the most important features this amazing plugin has been lacking for years now!

**Comment by dordsor21** [comment]
> I see a pull request for this has been made for a while now, when will it be merged? This is one of the most important features this amazing plugin has been lacking for years now!

Once it's been reviewed + approved ¯\_(ツ)_/¯

**Comment by VL4DST3R** [comment]
I see all the commits above from the past weeks all being verified but the issue still open. Has this _still_ not been merged?
