### ISSUE TITLE
An unexpected error while handling //removelighting and //fixlighting command (tested spigot-1.14.4 and 1.13.2)

### ISSUE THREAD

**Issue by miglas** [IntellectualSites/FastAsyncWorldEdit#314]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

config(default):
https://pastebin.com/XkBiabM9
issue:
https://pastebin.com/zzLBexXT

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

FastAsyncWorldEdit-1.15-45.jar
**[REQUIRED] Spigot/Paper Version Number:** 

spigot1.14.4
**[REQUIRED] Description of the problem:**
An unexpected error while handling //removelighting and //fixlighting command

**How to replicate**:

**Plugins being used on the server:**

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by TheCalypso** [comment]
Hello, 
I had the same problem when I tested today. The version I am using is Paper-102 1.15.2. with version of FAWE 1.15.2 # 71

Well done for the work you have done to ensure version 1.15.2! I know there has been a lot of work done and I wanted to congratulate you!

- TheCalypso -

**Comment by aurorasmiles** [comment]
The lighting commands have been disabled for a while, and need to be reimplemented again. Maybe backburner for now. I'd suggest using LightCleaner
