### ISSUE TITLE
Fawe blocks come back

### ISSUE THREAD

**Issue by endminecraffter** [IntellectualSites/FastAsyncWorldEdit#315]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/78ca991841194f41884c3ed516396248

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
http://prntscr.com/qomh7v

**[REQUIRED] Spigot/Paper Version Number:** 
Paper version git-Paper-50 (MC: 1.15.1)

**[REQUIRED] Description of the problem:**
When I change blocks from an paste or break blocks from an brush, the change blocks come back when I do something with FAWE nearby.

**How to replicate**:
In this video you can see that when I change blocks from an paste or break blocks from an brush, the change blocks come back when I do something with FAWE nearby.
https://youtu.be/shUYhGsvKjw

**Plugins being used on the server:**
Fawe
CloudNet

**Checklist**:
- [X] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Please retry this with build 60 (http://ci.athion.net/job/FastAsyncWorldEdit-1.15/60/artifact/worldedit-bukkit/build/libs/FastAsyncWorldEdit-1.15-60.jar). If it's still occurring, please say so. Otherwise, close the issue.

**Comment by endminecraffter** [comment]
I try it

**Comment by endminecraffter** [comment]
It does not really work.

https://youtu.be/DFnQ5BZlbQU
You can see old brushes comes back. ): But this from the other video does not happen anymore.
Sorry if my English is bad, I'm coming from Germany (:

**Comment by aurorasmiles** [comment]
I could not replicate the original issue in build 144.
I don't really understand what's happening in your second video, but I could not replicate that either, maybe try explaining that issue a bit further
