### ISSUE TITLE
BSkyBlock Support

### ISSUE THREAD

**Issue by partyp770** [IntellectualSites/FastAsyncWorldEdit#316]
ASkyblock was deprecated upon the release of 1.13.

I'd like for FAWE to support its successor, Bentobox.

I've drafted up a skript script that creates a region around players' islands, but I haven't quite figured out how to restrict worldedit with it.

On my server, I'm trying to make the protection radius around a player's island get bigger over time, which I've already done. Players can't place blocks outside of the island protection radius, but they CAN set blocks outside of the protection radius using worldedit.

I'm open to any alternative solutions, but so far, this is all I was able to come up with. I'm not sure if the plugin already has BSkyBlock support, or if this is a thing that needs to be added on tastybento's end, but I wasn't able to find anything online about the subject.

**Comment by MattBDev** [comment]
Link to BSkyBlock repo: https://github.com/BentoBoxWorld/bskyblock

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.

**Comment by AnghiYt** [comment]
+1

**Comment by NotMyFault** [comment]
BSkyBlock/BentoBox would optimally add support for WorldEdit which Fawe could simply hook into.
We can't add support for any third party plugin.
