### ISSUE TITLE
 addNotifyTask is missing

### ISSUE THREAD

**Issue by OmerBenGera** [IntellectualSites/FastAsyncWorldEdit#317]
There was a method (addNotifyTask from EditSession) that we could add tasks to be ran when a FAWE's task is finished.
It was removed in one of the versions, but no replacement was given.
Is it possible to run a runnable after a schematic was placed (A schematic that I paste using the API of the plugin)?

**Comment by MattBDev** [comment]
The entire Task system is poorly written. It needs to be redone. This will be added but it's going to be awhile.

**Comment by OmerBenGera** [comment]
> 
> 
> The entire Task system is poorly written. It needs to be redone. This will be added but it's going to be awhile.

Thanks for the reply.
Is it possible to add a temp fix for that?
Because right now, the entire schematics system (and probably others) are useless.

**Comment by MattBDev** [comment]
I'll see what I can do. If I do anything though I am annotating it with `@Beta ` (you can read about that annotation in the Google Guava Javadoc)

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.

**Comment by escape9179** [comment]
Was anything done about this? I'm running into the same issue @OmerBenGera is describing. Some legacy code I'm maintaining relies on `addNotifyTask`.

**Comment by NotMyFault** [comment]
Seeing the issue still being open, assuming no. No pull request has been risen.

**Comment by dordsor21** [comment]
I don't think this is something we need to add? EditSession#close(), the Operations#complete methods, etc. are all blocking, and thus it's trivial to run everything in a separate thread, await the close, and run any tasks then. It's also likely to be safer, as you can ensure that a notify task is always run upon exception, or be run differently if an exception is thrown somewhere.

Closing unless someone has a good reason why this should be implemented, as I cannot see one, other than for very inexperienced developers.
