### ISSUE TITLE
Server crash on pasting schematic

### ISSUE THREAD

**Issue by justinbea** [IntellectualSites/FastAsyncWorldEdit#321]
I am trying to paste a schematic (700x800) and after pasting the console is spamming wildly and crashing the server and dont realy know what to do and how to fix
[fawe.txt](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/files/4103567/fawe.txt)

**Comment by aurorasmiles** [comment]
Could you please provide all the information required in the issue template? Otherwise no one can really help you much.

**Comment by IronApollo** [comment]
Closed, please re-post the issue **with the proper issue template** if your issue persists on the latest build.
