### ISSUE TITLE
Pasting Schematic Class Cast Exception

### ISSUE THREAD

**Issue by berryfd1995** [IntellectualSites/FastAsyncWorldEdit#324]
Debug Info: https://athion.net/ISPaster/paste/view/e538cd95570c4a4d9454be896fefe20e
Spigot Version: 1.14.4

Description:
I loaded in a 1.12.2 schematic. I am attempting to paste it in a 1.14.4 server. I am unsure if this is a supported feature but it is the only way I can currently would know how to move my build over.

It loads in the schematic just fine, but on paste I get this issue.

**Comment by aurorasmiles** [comment]
If I remember correctly, the schematic format changed between 1.12 and 1.13, maybe thats causing this issue

**Comment by MattBDev** [comment]
This error was fixed.
