### ISSUE TITLE
Error after //copy

### ISSUE THREAD

**Issue by Nety01** [IntellectualSites/FastAsyncWorldEdit#327]
FAWE 1.15. Build 58
Paper 1.15.2 Build 85

I get that error after typing //copy https://hastebin.com/epacazerun.bash (selected only a few blocks)

**Comment by aurorasmiles** [comment]
Copy works fine for me. Can you please provide all the information that are required in the issue template, or try with the latest build?

**Comment by Nety01** [comment]
Yeah it works with latest build 😄
