### ISSUE TITLE
Paper 1.15.2 NullPointerException on plugin load

### ISSUE THREAD

**Issue by PrincessRTFM** [IntellectualSites/FastAsyncWorldEdit#330]
Server version: `This server is running Paper version git-Paper-85 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
Configuration files: [config.yml](https://pastebin.com/raw/NHUx3eAL) and [config-legacy.yml](https://pastebin.com/raw/Qv88Qnus) (both defaults, generated by plugin load and left untouched for debugging)
Server log: [startup to loading-finished](https://pastebin.com/raw/L9kLxry2), immediately shut down since it's not working
FAWE version: [1.15-58](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/lastSuccessfulBuild/artifact/worldedit-bukkit/build/libs/FastAsyncWorldEdit-1.15-58.jar), deleted FastAsyncWorldEdit folder on updating from server version 1.14.4

On starting the server, FAWE immediately throws a null pointer exception from `com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:183)` while attempting to load the built-in legacy ID registry.

No issue reporting template or guidelines were found, but a check of all open issues did not show a duplicate.

**Comment by MattBDev** [comment]
We do not support 1.15.2 yet. We are working on adding support soon.

**Comment by PrincessRTFM** [comment]
The installation page said [1.13.2 - 1.15.2](https://i.imgur.com/VkpHked.png) so I was confused, thanks for letting me know.
