### ISSUE TITLE
Crashing on 1.15.1 "DataPaletteBlock"

### ISSUE THREAD

**Issue by Pugabyte** [IntellectualSites/FastAsyncWorldEdit#331]
FAWE: Build#45
Spigot: 1.15.1

Crash log: https://paste.bnn.gg/gerux
Debug paste: https://athion.net/ISPaster/paste/view/bbd10dc8b88e4df2b62a3bc17e1fa970

**How to replicate**: Unsure, seems random. Build team is keeping an eye out for me

**Plugins being used on the server:** (14): WorldEdit, FastAsyncWorldEdit, VoxelSniper, PermissionsEx, PlugMan, Vault, Multiverse-Core, WorldGuard, Essentials, Multiverse-Inventories, Herochat, HeadDatabase, Multiverse-NetherPortals, EssentialsSpawn

**Comment by MattBDev** [comment]
I was actually working on something earlier today regarding this issue. Now I have a reason to continue that work.

**Comment by Pugabyte** [comment]
Do you happen to know what specifically can cause this, so my build team can avoid that scenario?

**Comment by alexp9982** [comment]
Although I'm using 1.14.4, I think I am getting the same issue

Crash Logs (Happened on several occasions, here's 2 of them): 

- [http://haste.athion.net/bimesocelo.php]
- [http://haste.athion.net/zosojefuha.md]

Debug Paste:

- [https://athion.net/ISPaster/paste/view/8d84a6e5fd5c4577ab9de702178d36b5]

**Comment by dordsor21** [comment]
Tentatively closing
