### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException, Layer variable was, Tried Setting Block at

### ISSUE THREAD

**Issue by JH3Y50N** [IntellectualSites/FastAsyncWorldEdit#336]
http://prntscr.com/qx45lv

[20:37:25 INFO]: Layer variable was = 16
[20:37:30 INFO]: Tried Setting Block at x:11, y:256 , z:8
[20:37:25 WARN]: java.lang.ArrayIndexOutOfBoundsException

I'm getting this error on 1.15.1 server when i paste a schematic

**Comment by IronApollo** [comment]
Duplicate of #307 , only with additional debug information. Closed.

**Comment by IronApollo** [comment]
Also, please use the bug template next time or your issue may be closed before consideration.
