### ISSUE TITLE
Blocks get replaced while successive //stack

### ISSUE THREAD

**Issue by clarissa-au** [IntellectualSites/FastAsyncWorldEdit#340]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/f06ebd87682747c9b0fd224be12bf99d

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
[09:16:00] [Craft Scheduler Thread - 28/INFO]: FastAsyncWorldEdit-81 created by Empire92
[09:16:00] [Craft Scheduler Thread - 28/INFO]: FAWE version:
 - Date Feb 14, 2020 12:00:00 AM
 - Commit f1041e59
 - Build 81
 - Platform bukkit
[09:16:00] [Craft Scheduler Thread - 28/INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[09:16:00] [Craft Scheduler Thread - 28/INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-81;efbe1a7)

[09:16:00] [Craft Scheduler Thread - 28/INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running CraftBukkit version git-Spigot-56f8471-6567017 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Changed blocks are reverted back to their original form when successively stacked them.

**How to replicate**:
1: Place an iron block.
2: Select the iron block and use //stack 20
3: Break the iron block and place an obsidian block in that space
4: Use //stack 20 again. The obsidian block will be changed back to iron block.

**Plugins being used on the server:**
Plugins (34): LuckPerms, dynmap, PluginConstructorAPI, Skript, PlaceholderAPI, Lift, Multiverse-Core, FastAsyncWorldEdit, SignEdit, VoxelSniper, ImageOnMap, KixsChatAnnouncer, ViaVersion, MinecartSpeedPlus, Elevators_v2, HeadsPluginAPI, Vault, ServerRestorer, ViaBackwards, WorldEdit, Essentials, ProtocolLib, WorldGuard, Citizens, BlockBall, LockettePro, EssentialsChat, RFChairs, BuyRegion, BKCommonLib, BuildBattle, LightCleaner, Train_Carts, TCHangRail

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Unable to reproduce. Please retry on the latest build (http://ci.athion.net/job/FastAsyncWorldEdit-1.15/) and comment with a status update.

Closed until OP posts comment updating their issue status.
