### ISSUE TITLE
Fawe commands will not load

### ISSUE THREAD

**Issue by AwesomeTy79** [IntellectualSites/FastAsyncWorldEdit#350]
I tried to load fawe on nukkit, bun none of the commands will load. The plugin is loaded, but won't work.

[https://hastebin.com/uhuqifidab](https://hastebin.com/uhuqifidab)

**Comment by MattBDev** [comment]
We don't support nukkit.

**Comment by AwesomeTy79** [comment]
Sorry but
https://nukkitx.com/resources/fastasyncworldedit.30/
and https://intellectualsites.github.io/download/fawe.html
has a nukkit option?

**Comment by MattBDev** [comment]
🤦‍♂ "Versions below 1.14 are classified as legacy and receive limited to no support." That goes for Nukkit too.

**Comment by AwesomeTy79** [comment]
Oh sorry didn't see that that wasn't 1.14+

Will there be an updated nukkit version eventually?

**Comment by MattBDev** [comment]
No
