### ISSUE TITLE
FAWE worldguard issues /fawe reload bug

### ISSUE THREAD

**Issue by chrisdunc1** [IntellectualSites/FastAsyncWorldEdit#354]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/6f7ad3ab93c34db79450390ac06bc93e

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
Bukkit-Official(1.15-113;c1fe16b)

**[REQUIRED] Spigot/Paper Version Number:** 
Git-Paper-243 MC 1.14.4 (PaperMC)

**[REQUIRED] Description of the problem:**
Basically I run a prison server where there are different mines for each rank. A rank has A mine, B rank has B mine and so on. I have created regions using worldguard with the flag entry deny (this prevents entry to any user who tries to enter the region) then each specified region also has ex: /rg addmember g:c (this adds members to that region and the "g" is for group) so each region has its member added. Upon starting the server there are 0 console errors however if you are rank b you are not able to enter the b region same goes for c ranks and above. After I run the command /fawe reload only then does it allow my players to enter their specified regions

**How to replicate**:

1) install worldguard 7.00 , latest version of fawe, and luckperms
2) create any group in luckperms for ex: group default
3) create a region using worldedit (/rg create defaulttest)
4) flag the region with entry deny /rg flag defaulttest entry deny
5) add the default group as a member to the region /rg addmember defaulttest g:default
6) now try entering the region as a player (you should not be able to enter) then try doing /fawe reload (should then allow you to enter)

**Plugins being used on the server:**
https://gyazo.com/8e0938be27d2b84a49268b9e27f239ed**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
This is likely fixed with #617 - if not please open a new issue
