### ISSUE TITLE
Clipboard issues/ Can not //copy

### ISSUE THREAD

**Issue by SpeshulBoi** [IntellectualSites/FastAsyncWorldEdit#356]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
[latest.log](https://pastebin.com/UpnuJRVs)
[config.yml](https://pastebin.com/Uh94Hqc6) (unedited)
[config-legacy.yml](https://pastebin.com/mj0C2tHX) (unedited)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
[22:41:29 INFO]: FastAsyncWorldEditunknown created by Empire92
[22:41:29 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[22:41:29 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-113;c1fe16b)

[22:41:29 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
[22:43:50 INFO]: This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Can not //copy more then once in one server session, will get error message "The requested operation cannot be performed on a file with a user-mapped section open" (error trace in latest.log). Only way to remedy the error is to restart the server and delete the users clipboard file. Then you can copy once before getting the error again. Similar to #159 , but is marked closed and is slightly different e.g Mine is always triggered by all users, isn't fixed by /clearclipboard , and happens as soon as you generate a clipboard file. 

It seems to be caused by one of the commits in build 88. Tested a few versions before and after. Also changing to 'clipboard: use-disk: false' leads to #224 .

**How to replicate**:
Do //copy twice or //copy once while having a clipboard file already generated.

**Plugins being used on the server:**
Just FAWE

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Known issue. Use-disk: false is fixed now as of 5197ed0

**Comment by dordsor21** [comment]
Fixed 3cd30eb
