### ISSUE TITLE
//move cannot be undo'd

### ISSUE THREAD

**Issue by Kuouo** [IntellectualSites/FastAsyncWorldEdit#360]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/5e3e5cb8bd5e4e8f842c4037f4cf2cca

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

10.03 15:22:19 [Server] INFO ------------------ Platforms ------------------
10.03 15:22:19 [Server] INFO * Bukkit-Official(1.15-113;c1fe16b)
10.03 15:22:19 [Server] INFO ---------------- Capabilities ----------------
10.03 15:22:19 [Server] INFO GAME_HOOKS: Bukkit-Official
10.03 15:22:19 [Server] INFO CONFIGURATION: Bukkit-Official
10.03 15:22:19 [Server] INFO USER_COMMANDS: Bukkit-Official
10.03 15:22:19 [Server] INFO PERMISSIONS: Bukkit-Official
10.03 15:22:19 [Server] INFO WORLDEDIT_CUI: Bukkit-Official
10.03 15:22:19 [Server] INFO WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Previous version: git-Paper-225 (MC: 1.14.4)
**[REQUIRED] Description of the problem:**

**How to replicate**:

1. Make a selection
2. Try //move it any direction you'd like
3. Attempt //undo
**Plugins being used on the server:**
ArmorStandEditor, Autorank, BeSocial, ChatLock*, CommandHook, CommandSpy*, CoreProtect, DecoHeads*, DiscordSRV, e6c40*, EditableSign, EntityDetection, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, Factions, FastAsyncWorldEdit, HeadDatabase*, HolographicDisplays, HungerGames, Ikea, ImageMaps*, LuckPerms, MarriageMaster, Matrix, MaxBans*, MineableSpawners, MorePlayerModels2*, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, NametagEdit*, PacketListenerApi*, PerWorldInventory, PlotSquared, PluginLibrary, PluginManager, ProjectKorra, ProtocolLib, Rankup, SimpleRoll*, StaffChat*, SuperbVote, SuperTrails*, TiasChatColors*, TimeistsDekos, TimiettesAPI*, VarLight, Vault, Vivecraft-Spigot-Extensions*, Votifier, VPN-fucker*, WorldEdit, WorldGuard

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Can confirm this bug in the latest build for 1.15, 144

**Comment by dordsor21** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/69bd0274ddaf06da8b1e9e75c033dbe6ad97c579
