### ISSUE TITLE
FAWE 1.15.2 for some reason pastes stairs and slabs weirdly or not at all..

### ISSUE THREAD

**Issue by DogeTennant** [IntellectualSites/FastAsyncWorldEdit#361]
Basically what the title says..

https://athion.net/ISPaster/paste/view/cbd7fc9c31e04a52a36f03898e4db1ef Debug

https://www.youtube.com/watch?v=mPQK6OX30Gs&feature=youtu.be Youtube Demonstration

If you need any more info just ask,

thanks in advance!

**Comment by aurorasmiles** [comment]
I tested this with build 144 for 1.15 and was not able to replicate it
