### ISSUE TITLE
When I place stone there is a huge hole in my cave.

### ISSUE THREAD

**Issue by endminecraffter** [IntellectualSites/FastAsyncWorldEdit#363]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/958de250d0314795bf2d9c912487ce3f

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
http://prntscr.com/ridm4m <- a screen

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-138 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
When I want to place blocks there(the location in the video) you can see there is a huge hole.
Little Information: The big stone Hole made with fawe
https://youtu.be/OkgzJEUa59c

**How to replicate**:
https://youtu.be/OkgzJEUa59c

**Plugins being used on the server:**
https://athion.net/ISPaster/paste/view/958de250d0314795bf2d9c912487ce3f <- there is the list

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin <- i deleted every plugin

**Comment by Jaskowicz1** [comment]
I'm getting the exact same issue on all my server instances. Having to avoid FAWE as it's causing builds to just get chunks removed as if they become corrupted. /stop doesn't fix it at all.
