### ISSUE TITLE
When i break trees from an brush, it comes back later.

### ISSUE THREAD

**Issue by endminecraffter** [IntellectualSites/FastAsyncWorldEdit#364]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/20a51c14b9a646fe9852dadfa76d1367

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
http://prntscr.com/rijduk <- as screen

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-138 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
https://youtu.be/LkSRvfNmb_M
When i place blocks with /brush forest cyl 3 15 oak , break them, place blocks with /brush forest cyl 3 15 spruce and do //undo the oak trees comes back

**How to replicate**:
https://youtu.be/LkSRvfNmb_M <---

**Plugins being used on the server:**
https://athion.net/ISPaster/paste/view/20a51c14b9a646fe9852dadfa76d1367 <- there is a list

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
I was not able to replicate this issue with build 144, please try the latest build and see if that fixed it

**Comment by dordsor21** [comment]
I've managed to break it down to an issue specifically when using paperspigot and having randomTickSpeed greater than 0. If you can live without paper, or without a randomTickSpeed, then this is a temporary fix for the issue.

**Comment by aurorasmiles** [comment]
> Using the latest Paper builds for 1.15.2 seems to completely fix the issue mentioned above. If, however, you still experience this, then adding   use-optimized-ticklist: false under settings in paper.yml should also fix it (again 1.15.2 only).
