### ISSUE TITLE
debugpaste link click

### ISSUE THREAD

**Issue by endminecraffter** [IntellectualSites/FastAsyncWorldEdit#365]
**Is your feature request related to a problem? Please describe.**
When I make an issue for a FAWE bug, I do /fawe debugpaste and I can't click on this link. );

**Describe the solution you'd like**
I want, when I click on this /fawe debugpaste Link, that the link opens in my browser.

**Describe alternatives you've considered**
I have no alternatives, or I don't understand the question.

**Additional context**
http://prntscr.com/rijmau i want to click on THIS stupid long Link.

**Comment by aurorasmiles** [comment]
I'm able to click on the link in the latest version, so maybe this was included already

**Comment by MattBDev** [comment]
I forgot to close this since I fixed it last week.
