### ISSUE TITLE
Console spam after startup

### ISSUE THREAD

**Issue by wellnesscookie** [IntellectualSites/FastAsyncWorldEdit#367]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/2e8cb9f141814f169c1ee2b8a9a9c4f9

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
```
[18:19:51] [Craft Scheduler Thread - 12/INFO]: &7FastAsyncWorldEdit-45 created by Empire92
[18:19:51] [Craft Scheduler Thread - 12/INFO]: &7FAWE version:
 - Date Jan 15, 2020 12:00:00 AM
 - Commit ff35280e
 - Build 45
 - Platform bukkit
[18:19:51] [Craft Scheduler Thread - 12/INFO]: &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[18:19:51] [Craft Scheduler Thread - 12/INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-45;0cad7f2)

[18:19:51] [Craft Scheduler Thread - 12/INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```
**[REQUIRED] Spigot/Paper Version Number:** 
PAPER 1.13.2 - 655

**[REQUIRED] Description of the problem:**

- A console log is included in the link above from debug-paste
- I have downloaded the 1.13.2 version from the official site
- I am reporting because of the console log, in  game it kinda seems that it's working okay

**How to replicate**:
- Nothing special, I just started the server and the console spammed above 

**Plugins being used on the server:**
`[18:24:42] [Server thread/INFO]: Plugins (13): ArmorStandTools, CoreProtect, EditableSign, Essentials, EssentialsChat, FastAsyncWorldEdit, HeadDatabase*, LuckPerms, Multiverse-Core, SCLock*, Vault, VoidGenerator, WorldEdit`

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure the bug/error is not caused by any other plugin

- I have not checked a 1.14.4 box because I expected an official version of 1.13.2 to be free of bugs
- I think I have seen a similiar issue, but I'd say it's on 1.14 or 1.15 version, so I'm creating a new one

**Comment by MattBDev** [comment]
1.13.2 is no longer supported.

**Comment by wellnesscookie** [comment]
How comes an official version has critical bugs that people mention on git and discord, but the support is dropped, so there's no help? Have asked the same question on discord, waiting for the answer wherever.
