### ISSUE TITLE
//pos clamping incorrectly

### ISSUE THREAD

**Issue by thislooksfun** [IntellectualSites/FastAsyncWorldEdit#369]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/cb921a42c221476b9ea1204b31f9f60f

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
```
[18:19:18 INFO]: FastAsyncWorldEdit-589 created by Empire92
[18:19:18 INFO]: FAWE version:
 - Date Mar 17, 2020, 12:00:00 AM
 - Commit f758f069
 - Build 589
 - Platform Bukkit
[18:19:18 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[18:19:18 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-589;8a70f97)

[18:19:18 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 
`This server is running Paper version git-Paper-142 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**[REQUIRED] Description of the problem:**
The `//pos1` and `//pos2` commands are limited to strictly positive integers.

**How to replicate**:
1. Install FAWE 1.15.2
2. Type `//pos1 -123,5,10`
3. The position will be set to `1, 5, 10`

**Plugins being used on the server:**
Just FAWE

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Now I really hate that Jesse created the PrimitiveBindings class. Thanks for the report and PR
