### ISSUE TITLE
max-changes:

### ISSUE THREAD

**Issue by iZerus** [IntellectualSites/FastAsyncWorldEdit#37]
**Description of the problem:**
limits:
  default:
...
    # Max number of block changes (e.g. by `//set stone`).
    max-changes: 5

Set a limit on the number of blocks. But when I call the command / / set 1, where more than 5 blocks should be updated, the chat says that the command is canceled. But 5 blocks are updated and this action is not recorded in the history. Therefore, the //undo and //redo commands do not work for this case.

(Russian)
Установил ограничение на количество блоков. Но когда вызываю команду //set 1, где должно обновиться блоков больше, чем 5, то в чате пишется, что команда отменена. Но 5 блоков обновляются и данное действие не записывается в историю. Следовательно, команды //undo и //redo для данного случая не работают.

**Comment by aurorasmiles** [comment]
Most likely fixed with #620
