### ISSUE TITLE
Leaves won't be replaced

### ISSUE THREAD

**Issue by LIWKK** [IntellectualSites/FastAsyncWorldEdit#372]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

![image](https://user-images.githubusercontent.com/35636315/77254572-7dbb9500-6c6a-11ea-8c76-2ff9844635d0.png)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

![image](https://user-images.githubusercontent.com/35636315/77254591-9f1c8100-6c6a-11ea-9f6d-9929bace029d.png)

**[REQUIRED] Spigot/Paper Version Number:** 

![image](https://user-images.githubusercontent.com/35636315/77254596-a8a5e900-6c6a-11ea-9a8f-7835c7be845f.png)

**[REQUIRED] Description of the problem:**
 No errors
 
![image](https://user-images.githubusercontent.com/35636315/77254610-c5dab780-6c6a-11ea-82ae-994acdcc96fa.png)

**How to replicate**:
 //replacenear 100 minecraft:oak_leaves air

**Plugins being used on the server:**

![image](https://user-images.githubusercontent.com/35636315/77254616-dab74b00-6c6a-11ea-9eb2-9509ee0236fe.png)

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
I was able to replicate that issue in the latest build 144 for 1.15

**Comment by aurorasmiles** [comment]
Issue confirmed in build 178, just tested it again with acacia_leaves

**Comment by Orlaando-dev** [comment]
I was able to replicate this on Build 191.

**Comment by DoogiePC** [comment]
Also able to replicate this issue, it only seemed to be oak_leaves though and not any other type of leaves.

**Comment by Orlaando-dev** [comment]
Able to replicate this with all types of signs- not just leaves. Build 192.

**Comment by MattBDev** [comment]
Was it really so hard to type in the debug paste url?

**Comment by MattBDev** [comment]
http://athion.net/ISPaster/paste/view/fe3eba5f3fae4f1f80498b5b49004c5f
