### ISSUE TITLE
Copying large chunk is done with loss of fragments.

### ISSUE THREAD

**Issue by bladbl** [IntellectualSites/FastAsyncWorldEdit#373]
PAPER 1.15.2-143 
https://athion.net/ISPaster/paste/view/aa53bbda80a44815bdd6ddb9355aab99
![image](https://user-images.githubusercontent.com/47465708/77422520-a6649b80-6dde-11ea-824b-cc43828cdd62.png)
![image](https://user-images.githubusercontent.com/47465708/77422620-d613a380-6dde-11ea-82b5-56dc91c2c367.png)
CONSOLE
``>.... [11:32:39 INFO]: bladbl issued server command: //copy
>.... [11:32:39 WARN]: [com.boydti.fawe.object.clipboard.DiskOptimizedClipboard] Creating new RandomAccessFile: plugins/FastAsyncWorldEdit/clipboard/01b87205-ee03-344d-8a61-c46a5ea875c8.bd
>.... [11:32:43 INFO]: bladbl issued server command: //paste
>.... [11:32:43 INFO]: [com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2] The following is not an error. It just a debugging message. There is no need to report this.
ordinal: 0NBT: false
>.... [11:32:43 INFO]: [com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2] The following is not an error. It just a debugging message. There is no need to report this.
ordinal: 0NBT: false

**Comment by MattBDev** [comment]
Seeing as you didn't fill out the template and your issue is very vague. Can you please describe what was supposed to happen and what actually happened?  Otherwise I will have to close the issue.
