### ISSUE TITLE
//set sometimes ignores selection and cuts off after chunk by height

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#377]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** https://athion.net/ISPaster/paste/view/5d585193335a403485d12cb8eb4a2549

**[REQUIRED] FastAsyncWorldEdit Version Number:** Build 144 (1.15)

**[REQUIRED] Spigot/Paper Version Number:** 146 (1.15)

**[REQUIRED] Description of the problem:**

Similar to the issue https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/332 part of the selection does not get set/undone
See https://media.discordapp.net/attachments/532569523610714127/693027042580758578/unknown.png?width=719&height=434
Or https://drop.cutiepie.at/fy0swguhpevfsx
The blocks are only set to the last complete chunk in the section. Anything above is ignored. This only happens for bigger selections (at least 10x10), small selections seem to work without any problems.
I could not replicate it every time I tried, but it happens fairly often. Just select the region of a chunk & expand the selection 3 up, most of the time that works
**How to replicate**:

1. Select an area containing multiple chunks by height
2. Use a command like //set 1
3. Sometimes the top part of the selection is not set 
**Plugins being used on the server:**

None other than FAWE
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

PS: Sorry IronApollo

**Comment by IronApollo** [comment]
"The blocks are only set to the last complete chunk in the section"

Can you explain this more? I'm not able to get online and test this currently so in-depth explanations of the issue help me to get an idea of where I should start looking when I do find time to work on it.

P.S. it's okay, I knew it wouldn't be a cure-all for chunks :P

**Comment by aurorasmiles** [comment]
It's easiest to see it with this screenshot, where we used //set gold_block in the selection you can see with WECUI
https://media.discordapp.net/attachments/532569523610714127/693027042580758578/unknown.png?width=719&height=434
The gold blocks end where the chunk ends, the last 4 rows above that, that are still in the selection, are in a new chunk
