### ISSUE TITLE
FAWE German Translation crashes the server

### ISSUE THREAD

**Issue by WeiiswurstDev** [IntellectualSites/FastAsyncWorldEdit#380]
# Bug report for FastAsyncWorldEdit 1.15
(I couldnt find a template for FAWE 1.15, so I chose this one and changed 1.14.4 to 1.15 as this made the most sense to me.)

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

latest.log: https://hasteb.in/unoyogid.log
config.yml: https://hasteb.in/imotadoy.yaml
config-legacy.yaml: https://hasteb.in/zorilaqo.yaml
Crash Report: https://hasteb.in/yurusohu.txt
(Although it isnt required, I think the crash report might help as this is a crash)
(I can't perform fawe debugpaste anymore because I already fixed it [described later] and made multiple changes afterwards. I did save the log, crash report and FAWE folder though, so thats where the required information comes from. If the above information isnt enough, I will try my best to restore the server to its broken form and perform /fawe debugpaste.)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

FastAsyncWorldEditunknown created by Empire92
Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
------------------ Platforms ------------------
Bukkit-Official(1.15-144;46d24ff)
---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

(I removed the * before Bukkit-Official because Markdown saw it as me trying to make a list and that ruined the formatting)

**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Paper version git-Paper-146 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

**[REQUIRED] Description of the problem:**

When the German translation is loaded:
Once PlotSquared loads and hooks into FAWE, a NullPointerException is thrown in the TranslationManager. (log: line 107)
After a player logs in and begins loading chunks, the server crashes (log: line 188).
When looking at the time the error occured and comparing it with the time I logged in, only 1 second passes, therefore I assume it was caused by me logging in.

When the English translation is loaded (language: '' in the config), everything works and no crash occures.

**How to replicate**:

Install FAWE and Plot² on Paper 1.15.2, generate a world with Plot² and teleport there. Stop the server, change the language to "de" in the fawe config and start it again. Once you log in, it should happen again.

**Plugins being used on the server:**

CreativeItemControl, **FastAsyncWorldEdit**, LeakParkour, LuckPerms, **PlotSquared**, WorldEdit, WorldGuard
Because the errors occur after Plot² does stuff and only WorldEdit and Plot² appear in the error callstacks, I assume the crash was caused by FAWE or Plot².

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15-2](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin
(I also checked the issues of Plot², it isn't there either)

**Comment by WeiiswurstDev** [comment]
I just saw that the language option in the config was removed 9 hours ago:
https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/62165250cef0529a678845c5829c371ef03bb06d

This might be connected.

**Comment by MattBDev** [comment]
@WeiiswurstDev I need to figure out how regular worldedit is handling translations now. All previous FAWE translations need to be redone. I may end up closing this issue but if I do please know that I am working on it and I will still try to follow up with an answer.

**Comment by N0tMyFaultOG** [comment]
Translations are currently not implemented and wip. If you want to help us out translating Fawe into german, you can do that here: https://intellectualsites.crowdin.com/translate/6b288d724f02e0794ec11212cbc43302/all/en-de/38
It would help us a lot.
