### ISSUE TITLE
AsyncWorld

### ISSUE THREAD

**Issue by derverdox** [IntellectualSites/FastAsyncWorldEdit#381]
Hey!
On the discord someone told me that AsyncWorld -> especially creating Worlds in an other thread is not working due to an exception caused by spigot -> WorldInitEvent may only be triggered synchronous.

Is there a way right now to create worlds async? Or do we have to find a workaround on our own?

Best regards?

Using 1.15

I am using the latest Version of FAWE (146)

**Comment by derverdox** [comment]
I am using 1.15

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.

**Comment by dordsor21** [comment]
Duplicate of #299
