### ISSUE TITLE
Any blocks will be penetrated by rain after pasting

### ISSUE THREAD

**Issue by vlssu** [IntellectualSites/FastAsyncWorldEdit#386]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
latest.log (null)
[config.yml](https://paste.ubuntu.com/p/M79xrmtNzS/) (unedited)
[config-legacy.yml](https://paste.ubuntu.com/p/9mHnc4HRWP/) (unedited)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
```
[22:12:22 INFO]: FastAsyncWorldEditunknown created by Empire92
[22:12:22 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[22:12:22 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-152;3d8303a)

[22:12:22 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 
Paper(243) 1.14.4-R0.1-SNAPSHOT

**[REQUIRED] Description of the problem:**
After copying the building, any slab (such as wooden_slab) will be penetrated during the rain, unlike normal conditions to prevent the rain, (can be understood as: the player can see this block, but the server may mistakenly think that there is no such block , Resulting in passing through the blocks when it rains, without blocking the rain's fall), although the impact is not great, this may cause some confusion for construction players.

**How to replicate**:
This happens on any slab, such as Smooth Stone Slab (minecraft: stone_slab), whether it is placed above or below, copied and pasted anywhere.

**Plugins being used on the server:**
Plugins (23): AntiExplosion*, antiRedstoneClock, BossShopPro, CMI, CMIEInjector*, CoreProtect, dynmap*, EliteMobs, FastAsyncWorldEdit, LockettePro, LuckPerms, Multiverse-Core, PlaceholderAPI, ProtocolLib, QuickShop, SaveRodOfficial*, Vault, VeinMiner, ViaVersion*, VillagerOptimiser, VipSystem*, WorldBorder, WorldEdit.

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Can confirm this issue, recreated without any Plugins and using build 154

**Comment by ValiantShishu** [comment]
> 可以确认此问题，无需任何插件并使用内部版本154重新创建

Same issue in version #156
```
[02:15:06 INFO]: FastAsyncWorldEditunknown created by Empire92
[02:15:06 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[02:15:06 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-156;a7e07dd)

[02:15:06 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**Comment by MattBDev** [comment]
This may require triggering a block update after pasting.

**Comment by TheoRetisch1** [comment]
Confirmed for FastAsyncWorldEdit-1.15-217 :/

**Comment by dordsor21** [comment]
The cause of the issue is known, but a solution is not easy.

**Comment by vlssu** [comment]
> The cause of the issue is known, but a solution is not easy. Technically an enhancement

I believe you can :)
Hard work.

**Comment by Kirrasio** [comment]
This is still happening on 1.16.1.

**Comment by Shark-vil** [comment]
1.16.3 - The problem is still there.
![javaw_MCtLW1ZRM6](https://user-images.githubusercontent.com/13109606/94320992-13780a00-ff97-11ea-8ed1-7ebff13b022c.png)

```
Paper version git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
```

```
Plugins (43): AuthMe, BKCommonLib, ChatControl, Citizens, ClearLag, CraftBook, CustomStructures, DeadChest, DiscordSRV, DragonSlayer, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP,  (WorldEdit)FastAsyncWorldEdit, GSit, Jobs, Kingdoms, LightCleaner, LuckPerms, mcMMO, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI*, MythicMobs, OpenInv, PlaceholderAPI, PlayerWarps, PlugMan, ProtocolLib, RandomTeleport, ServerRestorer, SuperVanish, UltimateTimber, Vault, ViaVersion, WorldBorder, WorldEditSUI, WorldGuard, WorldGuardExtraFlags
```

**Comment by dordsor21** [comment]
Use //fixlighting

**Comment by Shark-vil** [comment]
> Use //fixlighting

It's working, thx.

**Comment by VL4DST3R** [comment]
> 
> 
> The cause of the issue is known, but a solution is not easy. Technically an enhancement

May i ask, what exactly is the cause of this? And more importantly can it be at least mitigated in any way by say, changing the async options from the config when pasting? Expecting my players to always remember to do //fixlighting whenever they paste anything is not really feasible.

**Comment by LaurenceBarnes** [comment]
> > The cause of the issue is known, but a solution is not easy. Technically an enhancement
> 
> May i ask, what exactly is the cause of this? And more importantly can it be at least mitigated in any way by say, changing the async options from the config when pasting? Expecting my players to always remember to do //fixlighting whenever they paste anything is not really feasible.

Read more in #881 and #891. It is that the heightmaps are not updated or rather sent correctly. There is a workaround until it's fixed.

**Comment by MattBDev** [comment]
@VL4DST3R Unfortunately a lot of work and testing needs to be done to fix this. It's just a matter of putting aside the time and reading through a lot of decompiled Minecraft source code to fix this. Going through Minecraft source code is not easy (especially since it is incomplete and technically proprietary and a legal grey area). In a best case scenario I would say about 24 hours would be spent on just looking through the Minecraft code.

**Comment by LaurenceBarnes** [comment]
> @VL4DST3R Unfortunately a lot of work and testing needs to be done to fix this. It's just a matter of putting aside the time and reading through a lot of decompiled Minecraft source code to fix this. Going through Minecraft source code is not easy (especially since it is incomplete and technically proprietary and a legal grey area). In a best case scenario I would say about 24 hours would be spent on just looking through the Minecraft code.

The different issues you can close when this is done must be satisfying then xD
Is that heightmap update issue that complex? I didn't even know, but i guess it has something to do with how FAWE operates compared to WE?
Ironically, WE has the issue with observers and rails, but that they update wrongly instead. Also a really hard fix for them from what I read.

**Comment by MattBDev** [comment]
@LaurenceBarnes We would love to fix this one issue so we can get so many others on here closed. Unfortunately Minecraft isn't multi-threaded (only recently stuff has been changing) so we write directly to the world file and bypass many checks....etc. (I have 
a headache as of writing this so it isn't easy for me to explain even if I could) and the game wasn't designed for that.
I'm hoping Minecraft 1.7 improves the way worlds are saved but I'm not counting on it.

**Comment by VL4DST3R** [comment]
I was asking mostly because i figured since it's something that seems to affect only FAWE and not the classic worldedit (or at least i never noticed it misbehaving for the many years when i was using it), figured it was one of the methods that FAWE employs so the edits can happen so fast that's causing this.

**Comment by VL4DST3R** [comment]
> I'm hoping Minecraft 1.7 improves the way worlds are saved but I'm not counting on it.

Doubtful about 1.17 solving anything, it only seems to increase the size of the chunks and not much else.

> [...] so we write directly to the world file and bypass many checks....etc.

Given the current situation, instead of writing straight to the world file, can we revert to doing it "the old way" via configs?

**Comment by PellucidDice** [comment]
FYI updates the heightmap (type MOTION_BLOCKING) solves the problem.
