### ISSUE TITLE
FAWE returns wrong version on server start

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#388]
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** n/a

**[REQUIRED] FastAsyncWorldEdit Version Number:** Build 155

**[REQUIRED] Spigot/Paper Version Number:** n/a

**[REQUIRED] Description of the problem:**

When you start your server, you get 
[FastAsyncWorldEdit] Loading FastAsyncWorldEdit v1.14
[FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.14

This is the wrong version when using the 1.15 builds. Looking into the code I lost my will to live, so instead of a PR here is an issue for that.
Would also be cool to have the current build number displayed there as well
**How to replicate**:

Put Fawe in your plugins folder
Start your server

**Checklist**:

- [] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Can you try deleting your DummyFawe? I updated the version of it some time ago to 1.15.2.
> Looking into the code I lost my will to live, so instead of a PR here is an issue for that.
Haha, DummyFawe has been uploaded as jar, so it's hard to find if you don't know where to look for it :p

**Comment by aurorasmiles** [comment]
Ah, I completely forgot Dummy. Yeah, after deleting that it works fine.
