### ISSUE TITLE
Hand-placed blocks removed in chunks on WorldEdit action

### ISSUE THREAD

**Issue by Aequotis** [IntellectualSites/FastAsyncWorldEdit#389]
**Already reported in #FAWE-support by me, to IronApollo. This is here for record purposes.**

_Getting an issue where if I place blocks, any WE done in the same chunk causes those hand-placed blocks to be removed;
https://gyazo.com/872f26283b3445edaf38c2ab0c300104 
red is blocks placed by hand, I do //line 1 from the two blue blocks
The grey blocks are artifacts from blocks placed about 10 mins ago

FAWE version:

- Date Mar 30, 2020 12:00:00 AM
- Commit fc27cfc6
- Build 152
- Platform Bukkit

Server version:

This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)_

**Comment by IronApollo** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/4f3db6f3dae7add494349fd930f914119b164825 should be ported to other adapters

**Comment by IronApollo** [comment]
Fixed in a6a4400. Closed.
