### ISSUE TITLE
Brush masks sometimes don't work at chunk borders

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#390]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/3beb9380005f41d48241f88caf9bb73d

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

1.15 build 157
**[REQUIRED] Spigot/Paper Version Number:** 

Paper 1.15.2. 146
**[REQUIRED] Description of the problem:**

When you use masks for brushes, sometimes the cut out at chunk borders, ignoring the mask and just brushing everything
https://drop.cutiepie.at/d6bkravmw9z2vcb
https://drop.cutiepie.at/61mzuqc3ba13qps
**How to replicate**:

1. //brush sphere stone 30
2. /mask sand for example
3. See the results in the screenshots

**Plugins being used on the server:**

only FAWE
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Chezzer-ub** [comment]
I also get this but on //set or anything related, when I try set a 4x4 in a chunk and delete it and then if I set another 4x4 in the same chunk but somewhere else, the other 4x4 shows up.
