### ISSUE TITLE
Crashes upon Drain/replacing water/lava

### ISSUE THREAD

**Issue by CaptainAlienHD** [IntellectualSites/FastAsyncWorldEdit#394]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
 I did not changed any options from awe i'm using default config settings.
Aka. Default Config.

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
[01:58:56] [Craft Scheduler Thread - 50/INFO]: FastAsyncWorldEditunknown created by Empire92
[01:58:56] [Craft Scheduler Thread - 50/INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[01:58:56] [Craft Scheduler Thread - 50/INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-164;5cc7a09)

[01:58:56] [Craft Scheduler Thread - 50/INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
 CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
(I've also tried 1.14.4 which had same result)

**[REQUIRED] Description of the problem:**
Basically what's happening while trying to //drain or //replace or //replacenear 
WATER/LAVA with AIR in my case pretty much 0.5 to 1s later i get connection lost with text "Disconnected" from the server and the server itself crash with following error:
https://pastebin.com/DWzxeM3a
this is server crash report as well: https://pastebin.com/CTtdt5ws

**How to replicate**:
All you need to do it go to middle of ocean write //replacenear 100 water air
And you will see the magic happening. Instant disconnect + server crash.

**Plugins being used on the server:**
PluginConstructorAPI, PlaceholderAPI, MythicLib, VoxelSniper, HideStream, JobsmsMaintenance, CoreProtect, MineableSpawners, UltimateTimber, CancelElytraFirework, WorldBorder, Gringotts, ItemRestriction, Multiverse-Core, ProtocolLib, MCCore, AutoSaveWorld, LibsDisguises, FastAsyncWorldEdit, SignEdit, ObsidianBreaker, VoidGenerator, PermissionsEx, SQLibrary, CS-CoreLib, CalendarEvents, Vault, SalvageSmelter, MassiveCore, LastLoginAPI, PerWorldInventory, CreativeGates, HolographicDisplays, PlayerPoints, ServerMarket, ChestCommands, EpicCraftingsPlus, PlayerVaults, Multiverse-NetherPortals, WorldEdit, WorldEditSUI, Essentials, Citizens, TradeMe, JetsPrisonCells, EssentialsChat, JLib, EpicHeads, WorldGuard, ItemCommand, Factions, MythicMobs, LCCommands, EssentialsSpawn, InteractiveChat, EpicFarming, KoTH, FogusCore, EpicFurnaces, CommandConditions, Parties, PrisonUtils, Quests, QuestsGUI, QuantumRPG, RPGLS, CombatLogX, MythicMobsExtension.

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
I wasn't able to reproduce this issue using a clean install and build 173. I only noticed that with the //replacenear, some chunks of water did not get removed, but that seems like another issue

**Comment by aurorasmiles** [comment]
Tested again, cannot replicate in the latest build. I'm gonna close this now, if this happens again please comment or open a new issue
