### ISSUE TITLE
Issues with Region->Clipboard copying and saving to schematics

### ISSUE THREAD

**Issue by xikage** [IntellectualSites/FastAsyncWorldEdit#395]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

 https://athion.net/ISPaster/paste/view/902608249b844165b1b3672f1ec47f13

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

https://athion.net/ISPaster/paste/view/902608249b844165b1b3672f1ec47f13

**[REQUIRED] Spigot/Paper Version Number:** 

Bukkit-Official 1.15-164

**[REQUIRED] Description of the problem:**

Saving regions to clipboards and then to schematics via the API seems pretty broken. Chunks of blocks are randomly missing or are replaced with other blocks from previous copy/pastes.

Here is a picture of what I mean, using the test plugin I have included:
https://crazykingdoms.net/fawerip.gif

As of the more recent builds there are no longer any errors in the console.

**How to replicate**:

Here is code from a small test plugin I made to replicate the issues:
https://pastebin.com/H75hHWr8

**Plugins being used on the server:**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by pascal541** [comment]
I can confirm this issue.

With:
- Paper 1.15.2 build 164
- Fawe 1.15.2 build 164

My code (single class): https://pastebin.com/6Urzr1VC

**Comment by dordsor21** [comment]
You're closing the EditSession twice. That is bad... Either use the try with resources or the EditSession#flushSession()

**Comment by dordsor21** [comment]
This should be fixed by proxy of a number of ChunkSection improvements.
