### ISSUE TITLE
Unable to activate vanilla-cui

### ISSUE THREAD

**Issue by eatumup7** [IntellectualSites/FastAsyncWorldEdit#397]
Using Build 164
I am trying to install or activate CUI. Documentation I found shows a true/false statement under experimental safe for vanilla-cui

So far i have been unable to located documentation to activating CUI. I have tried the worldedit plugin but that seems incompatible with FAWE. 

i asked for assistance on discord and was directed to post my question here. 

How do I enable CUI or is there a compatible CUI plugin with FAWE 1.5?

**Comment by RedstoneFuture** [comment]
Can you write more info, please? What mod exactly, and what version do you use? Try the test again.

**Comment by NotMyFault** [comment]
The CUI module is currently not being compiled.

**Comment by NotMyFault** [comment]
Fixed/Enhanced in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/4d77771ea191502cbe3713cbe157ef0211c70dba.
Use `//drawsel` to toggle the build in CUI.
