### ISSUE TITLE
A flag in //copy for setting the origin of the Clipboard to the center of the defined region.

### ISSUE THREAD

**Issue by ChristianLieven** [IntellectualSites/FastAsyncWorldEdit#403]
**Is your feature request related to a problem? Please describe.**
Hi there, I'm Thamus_Knoward from [WesterosCraft](https://westeroscraft.com/). We're doing most of our world creation in-game using FAWE in combination with the [Macro/Keybind Mod](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1275039-macro-keybind-mod). Essentially, we're chaining a bunch of FAWE operations and use the control flow statements in the Macro/Keybind mod to make somewhat configurable scripts that allow us to do anything from [creating smooth gradients with snow](http://forum.westeroscraft.com/threads/river-pebble-script.1207/post-12984) to [automatically generating individual schematics](http://forum.westeroscraft.com/threads/list-of-schematic-brushes.328/post-12511) for each tree in [our large tree test.](http://puu.sh/FwrKB/46cf852041.jpg). A standardized way of generating schematics allows us to generate whole forests placing trees with the almighty /generate command. 

However, the biggest issue in this whole process is the fact that we cannot center the schematics upon creation from a cuboid region. We already use //toggleplace and //pos1 to give each schem the same origin, but smaller trees have a smaller square footprint which means that we need to account for different offsets upon placing the trees again in the world. This raises the complexity of our scripts and makes the procedure of auto-generating the schematics incompatible with the [schematic brush, another tool we use.](https://dev.bukkit.org/projects/schematicbrush).

**Describe the solution you'd like**
I'd love to be able to either add a flag in //copy for setting the origin of the Clipboard to the center of the defined region, or a flag while either loading a schematic with //schem load or on //paste. This has to work with region selections and commands that do not involve the player looking at a certain block.

**Describe alternatives you've considered**
We have considered writing a plugin, but currently lack the manpower and expertise to do so.

**Additional context**
We're currently using 
FAWE 18.7.21-a00345f-1159 by Empire92

**Comment by IronApollo** [comment]
"Fix" was committed before I received clarification on the enhancement request, so this enhancement has not properly been added, thus will be reopened.

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.
