### ISSUE TITLE
Blocks/Chunks errors after //replacenear blocks done with VoxelSniper

### ISSUE THREAD

**Issue by iamceph** [IntellectualSites/FastAsyncWorldEdit#404]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/b5572bfc8c7b41f289e80359fe45c57a

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
![image](https://user-images.githubusercontent.com/4377405/79070694-cc8fa400-7cd7-11ea-9ca4-fd762b055c0e.png)

**[REQUIRED] Spigot/Paper Version Number:** 
![image](https://user-images.githubusercontent.com/4377405/79070708-d4e7df00-7cd7-11ea-8df1-cb85ef9ee8f3.png)

**[REQUIRED] Description of the problem:**
When using VoxelSniper (simple /b b command) and then replacing some of the blocks created with it with //replacenear or //replace to air, the chunks get corrupted(?) and make the following blocks using voxel sniper not behave correctly. These block does not behave correctly even after reconnect, you need to replace them with another block to even see them. FAWE even says that -1 blocks has been replaced.

Video: https://youtu.be/6Xhv42YP_Jk
Used VoxelSniper: https://github.com/ervinnnc/VoxelSniper

**Plugins being used on the server:**
![image](https://user-images.githubusercontent.com/4377405/79070736-01036000-7cd8-11ea-9110-728f0f075581.png)

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Does this still occur in the latest build(s)?

**Comment by iamceph** [comment]
I will test this today/tomorrow!
