### ISSUE TITLE
Replace Shenanigans 

### ISSUE THREAD

**Issue by DeatlhyDiamond** [IntellectualSites/FastAsyncWorldEdit#407]
# Bug report for FastAsyncWorldEdit 1.15.2
Config:
https://pastebin.com/4ipS1V1e

FAWE Build Number:
Version 165

Version:
Paper version git-Paper-158 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Description:
replace command have weird behaviors, only replace one or two of the eight chunk corners in selection.

How to replicate:
Assemble a cube or any assembly of block that exist in 8 horizontally and vertically different chunk. f3+g should help in this. 

Video Demonstration: 
https://www.youtube.com/watch?v=rdDbHVH4-TQ

**Comment by aurorasmiles** [comment]
Could not replicate with build 171.
On another note please dont use IDs they won't be supported forever and only work because WorldEdit manually adds them

**Comment by dordsor21** [comment]
This should be fixed.
