### ISSUE TITLE
## Pattern ignores disallowed-blocks (causing extreme lag)

### ISSUE THREAD

**Issue by iLemon** [IntellectualSites/FastAsyncWorldEdit#408]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/b8fcbc1bc9d54088b64746e1ba343e58

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
[11:12:10 INFO]: FAWE version:
 - Date Apr 10, 2020, 12:00:00 AM
 - Commit f8ca5c81
 - Build 166
 - Platform Bukkit
[11:12:10 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[11:12:10 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-166;735a37f)

[11:12:10 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```
**[REQUIRED] Spigot/Paper Version Number:** 

```
[11:12:28 INFO]: This server is running Paper version git-Paper-184 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```
**[REQUIRED] Description of the problem:**

When a player uses a pattern in a command, it ignores the blocks on disallowed-blocks. For example, 
`//set ##minecraft:trapdoors`

**How to replicate**:

Add the following to your disallowed-blocks in config-legacy:
```
    - "minecraft:oak_trapdoor"
    - "minecraft:iron_trapdoor"
    - "minecraft:acacia_trapdoor"
    - "minecraft:birch_trapdoor"
    - "minecraft:dark_oak_trapdoor"
    - "minecraft:jungle_trapdoor"
    - "minecraft:spruce_trapdoor"
    - "##minecraft:trapdoors"
```
then type `//set ##minecraft:trapdoors` and it will take a long time to work but also cause lag if done in big selections.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Was this working in FAWE for 1.12.2 or an older version of FAWE for 1.13.2?

**Comment by iLemon** [comment]
Tried on 1.12.2 but the pattern doesn't exist https://imgur.com/a/tLbKCwf

I don't have a 1.13.2 server but can set one up if necessary.

**Comment by MattBDev** [comment]
no need. thanks for the info.
