### ISSUE TITLE
New brush/pattern or mask that uses rocks to make a nice pattern.

### ISSUE THREAD

**Issue by NeptunePlayz** [IntellectualSites/FastAsyncWorldEdit#409]
**New brush or pattern**

It's gonna go something like:
_//br rockpattern (background block) (block choice) (spacing) (size)_

It will be a rock pattern, but the rocks won't connect with each other.
What I mean with (background block) is the block that will make sure there's spacing between the rocks.
(spacing) is the spacing for the background, how many blocks before the rocks touch each other again.
(size) is the size of the rocks.
With (block choice), every block you put in there, will be a different rock in randomly selected rocks. What I mean with that is that I want it to have a different block for each rock, and it will not do like a splatter effect.

The end result should look something like this:
[https://i.imgur.com/PX88Y9e.png](https://i.imgur.com/PX88Y9e.png)

or like this:
[https://i.imgur.com/W0Kb2ca.png](https://i.imgur.com/W0Kb2ca.png)

Both of these images were taken on Hypixel, and thank you for taking your time reading this.
This wouldn't just help me, but dousens of others as well.

Yours Sincerely
- Narpzy

**Comment by NeptunePlayz** [comment]
Also, if people want scattered blocks, they do it by having [block1,block2],[block1,block2] etc.

**Comment by EgZiG** [comment]
That would be really cool

**Comment by dordsor21** [comment]
combine the //br scatter with //br rock
https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-scatter-pattern-radius5-points5-distance1--o

https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-scatter-pattern-radius5-points5-distance1--o

**Comment by NeptunePlayz** [comment]
> combine the //br scatter with //br rock
> https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-scatter-pattern-radius5-points5-distance1--o
> 
> https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-scatter-pattern-radius5-points5-distance1--o
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/11821084?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[IntellectualSites/FastAsyncWorldEdit](https://github.com/IntellectualSites/FastAsyncWorldEdit)**Blazingly fast world manipulation for artists, builders and everyone else: https://www.spigotmc.org/resources/13932/ - IntellectualSites/FastAsyncWorldEdit

Then how do you combine them, can you send a command example of how it can be done, I can't seem to figure out how.

**Comment by dordsor21** [comment]
Apologies, I meant https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-scmd-scatter-radius-points-cmd-radius1-cmd1cmd2

you could also use https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-shatter-pattern-radius10-count10 for doing the cracks, rather than doing the rocks.

If everyone actually read the commands on the wiki it might save everyone some time

**Comment by NeptunePlayz** [comment]
> Apologies, I meant https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-scmd-scatter-radius-points-cmd-radius1-cmd1cmd2
> 
> you could also use https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-shatter-pattern-radius10-count10 for doing the cracks, rather than doing the rocks.
> 
> If everyone actually read the commands on the wiki it might save everyone some time
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/11821084?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[IntellectualSites/FastAsyncWorldEdit](https://github.com/IntellectualSites/FastAsyncWorldEdit)**Blazingly fast world manipulation for artists, builders and everyone else: https://www.spigotmc.org/resources/13932/ - IntellectualSites/FastAsyncWorldEdit
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/11821084?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[IntellectualSites/FastAsyncWorldEdit](https://github.com/IntellectualSites/FastAsyncWorldEdit)**Blazingly fast world manipulation for artists, builders and everyone else: https://www.spigotmc.org/resources/13932/ - IntellectualSites/FastAsyncWorldEdit
I didn't quite understand this one:
https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-scmd-scatter-radius-points-cmd-radius1-cmd1cmd2

The other one I understood, but it wasn't how I wanted it.
Could you give me an example on how to use this one?
https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki/Commands#brush-scmd-scatter-radius-points-cmd-radius1-cmd1cmd2

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.

**Comment by dordsor21** [comment]
//br scattercmd <size> <count> <distance. "/blob <params". Shatter is still recommended for the original wanted outcome
