### ISSUE TITLE
//br sphere /mask 1 not working correctly

### ISSUE THREAD

**Issue by Stark2G** [IntellectualSites/FastAsyncWorldEdit#411]
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/7f9eca7e39c847b186d5a17a300a1697

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

Fawe--------Platforms--------
* Bukkit-Official(1.15-147;8c7d4c0)

Fawe--------Capabilities--------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 

16.04 13:24:40 [Server] INFO Checking version, please wait...
16.04 13:24:40 [Server] INFO You are 30 version(s) behind
16.04 13:24:54 [Server] INFO This server is running Paper version git-Paper-155 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
16.04 13:24:54 [Server] INFO You are 30 version(s) behind

**[REQUIRED] Description of the problem:**

Who:
every player is cursed with the problem
What:
when using //br sphere 2 15 with /mask 1 it not only replaces blocks that are already there. at the height of 10 or higher, it also replaces air. it kind of forgets that the mask is there.
When:
Always
Where:
everywhere
Why: 
no idea
Expected Behavior:
it should just replace the blocks that are already there

**How to replicate**:

using the steps above

**Plugins being used on the server:**

Plugins (14): ActivityTracking, BuildingUtilities, EthyriaCore, EthyriaEssentials, EthyriaPermission, EthyriaPermissionResolver, EthyriaWorlds, FastAsyncWorldEdit, goBrush, goPaint, ProtocolLib, Speedboost, VoxelSniper, WorldEdit

**Comment by dordsor21** [comment]
You are not using the latest FAWE. Update and if the problem persists, re-open.,
