### ISSUE TITLE
Broken lighting & shadows calculation for leaf blocks

### ISSUE THREAD

**Issue by bkane2** [IntellectualSites/FastAsyncWorldEdit#412]
# Bug report for FastAsyncWorldEdit 1.15.2

**FastAsyncWorldEdit Configuration Files:** 
https://hastebin.com/eqovoramih

**FastAsyncWorldEdit Version Number:** 
FAWE 18.7.21-a00345f-1159 by Empire92

**Description of the problem:**
Hi, I'm a builder from the [WesterosCraft](https://westeroscraft.com/) team.

Leaf blocks which are generated using WE do not appear to calculate lighting and shadows correctly, at least as of the version of FAWE we use for minecraft 1.11.2.

If I set a large cube of some solid block (e.g. wool), it correctly calculates shadows underneath. If I press F3 and look at the value for "light", this value decreases as I walk underneath the wool blocks.

However, if I set a large cube of leaf blocks, the shadow calculation breaks. If I press F3 and look at the value for "light" underneath them, the value is always 15 (max lighting) even though it's not exposed to full sunlight. If I place the leaf blocks by hand (or edit them in using Voxel brushes), it calculates the shadows correctly.

Using the //fixlighting commands also causes lighting underneath leaf blocks to break, changing all the light values to 15. It would be great if this command especially were fixed, since a large part of our forests have already been WE'd in and hence do not have realistic lighting currently.

**How to replicate**:
Just set a large cube of some solid block (e.g. wool), and press F3 while standing underneath it to check light values. Then set a large cube of leaf blocks and check light values underneath it. If needed, place a large cube of leaf blocks by hand and stand underneath it to compare.

Note that we're using FAWE (version above) on SpongeForge for Minecraft 1.11.2. I'm not sure if this issue has been fixed since then, or if it would be possible to fix this issue for the version we're using. But it would make a big difference for our project.

**Comment by MattBDev** [comment]
This project only supports Spigot/Paper for Minecraft 1.14.4 and newer.
