### ISSUE TITLE
Pasting Schematics Through //schem load or API produces an NPE

### ISSUE THREAD

**Issue by Blast-MC** [IntellectualSites/FastAsyncWorldEdit#413]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://i.imgur.com/0vAGmY4.png

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
https://i.imgur.com/ILM4y04.png

**[REQUIRED] Spigot/Paper Version Number:** 

CraftBukkit version git-Spigot-a03b1fd-5838285 (MC: 1.15.2)

**[REQUIRED] Description of the problem:**
https://i.imgur.com/0vAGmY4.png
When trying to paste a schematic, we get an NPE in the console and to the player. The schematics load onto the clipboard, but when trying to paste, the plugin errors.

**How to replicate**:
-Create a schematic
-Run /schem load ...
-Run //paste

**Plugins being used on the server:**
https://i.imgur.com/mahZ4VC.png

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You clearly did not search for duplicate issues, since the issue before this one is the same, and several others exist.
