### ISSUE TITLE
WorldGuard Issue with Regions

### ISSUE THREAD

**Issue by PancakeCatsss** [IntellectualSites/FastAsyncWorldEdit#414]
Debug Paste: https://athion.net/ISPaster/paste/view/6982267ff429470e80ff911f26f9447e
Server Version: git-Paper-199
FAWE Version: 
>.... [15:06:14 INFO]: FAWE version:
- Date Apr 19, 2020 12:00:00 AM
- Commit fccf03c7
- Build 172
- Platform Bukkit
>.... [15:06:14 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
>.... [15:06:14 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-172;330fc39)
>.... [15:06:14 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

WorldGuard Version: 7.0.2

Problem: 
Loading WorldGuard without any Regions saved Fawe works just fine even when we create a new region but when we restart the server Fawe no longer works unless we delete the WorldGuard Regions file and restart the server.

The server is also running PlotSquared: PlotSquared-4.491

How to re-create:
Load WorldGuard without any Regions saved and then create a region (or two) and restart the server.

Error: https://pastebin.com/J6p1A03x
This error only happens once 

Region Restriction being false in the config was after we found this bug so to re-create the issue that needs to be true

**Comment by PancakeCatsss** [comment]
Here is a short video showing the issue before we deleted all the region files and noticed the problem above https://medal.tv/clips/22707208/d1337uiO1KyN

**Comment by PancakeCatsss** [comment]
Also seems to be the same issue using the new v5 of PlotSquared

**Comment by MattBDev** [comment]
@PancakeCatsss PlotSquared v5 is not yet supported.

**Comment by PancakeCatsss** [comment]
It also doesn't work with versions of the v4 PlotSquared

**Comment by aurorasmiles** [comment]
The latest FAWE build 173 fixes PSv5 compatibility, could you try it again with that?

**Comment by IronApollo** [comment]
No response from OP in two weeks. Closing.
