### ISSUE TITLE
0 Blocks Affected

### ISSUE THREAD

**Issue by EgZiG** [IntellectualSites/FastAsyncWorldEdit#417]
# Bug report for FastAsyncWorldEdit 1.15.2

Link to info, plugins, config [./fawe report] [Info]
(https://athion.net/ISPaster/paste/view/7a3ac301ad384d50b95bd1567fd5401f)

Its not that important, but when i do whatever operation, it says 0 blocks affected or -1 blocks affected

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Somehow there actually isn't a duplicate issue for this that I can find. We know of the issue but it's super low priority obviously.

**Comment by dordsor21** [comment]
So this actually causes all our undo history perhaps.

**Comment by dordsor21** [comment]
Which commands is this? It has been fixed in stack, move, etc.

**Comment by orlaaando** [comment]
I believe this happens with almost every command.

**Comment by dordsor21** [comment]
I've tried paste, stack, set, move, sphere, cyl - all seem to work fine.

**Comment by EgZiG** [comment]
For me , it's every command

**Comment by aurorasmiles** [comment]
replace & replacenear still return -1, other commands report correct numbers in build 177

**Comment by MattBDev** [comment]
I believe it is because the -1 was hardcoded in.

**Comment by EgZiG** [comment]
umm, i got latest build, and I think its fixed

**Comment by EgZiG** [comment]
oh, some commands return good for e.g 15 blocks affected, but down of them still return -1

**Comment by EgZiG** [comment]
Umm so anyone will continue and fix this ? ...

**Comment by MattBDev** [comment]
@EgZiG This is a low priority issue. There are other critical bugs we need to fix first.
