### ISSUE TITLE
cant undo //stack :(

### ISSUE THREAD

**Issue by codydbgt** [IntellectualSites/FastAsyncWorldEdit#422]
any version iv tested alot of them on spigot recomended 1.15.2

**Comment by dordsor21** [comment]
Don't ignore the issue template.

**Comment by codydbgt** [comment]
so ur gunna ignore this?

**Comment by dordsor21** [comment]
Well given I'm able to undo a stack and you provided zero information, there's nothing to ignore in the first place.
