### ISSUE TITLE
Commands when identified by “id” don’t respond

### ISSUE THREAD

**Issue by soravoid** [IntellectualSites/FastAsyncWorldEdit#425]
[REQUIRED] FastAsyncWorldEdit Configuration Files:
Haven’t touched anything besides adding coreprotect to allowed plugins 

[REQUIRED] FastAsyncWorldEdit Version Number: build 180

[REQUIRED] Description of problem:

I’m not sure if plugin ids are a thing in bukkit, but when executing a command that also specifying the plugin it’s from, the command won’t respond or return anything.

Example:
//pos1 and //pos2 work, but /worldedit:/pos1 and /worldedit:/pos2 don’t

[REQUIRED] How to replicate:
Just typing it in the chat as a player

Plugins being used:
FAWE, CMI, BlocksHub, CoreProtect

Edit: I also messed up and accidentally closed and reopened the issue

**Comment by RedstoneFuture** [comment]
And why you need this?

**Comment by NotMyFault** [comment]
No response, assume no longer relevant.
