### ISSUE TITLE
Incorrect teleport behaviour of the navigation tool

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#426]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/a4954efda8514abcad817ecd7d5d2756

**FastAsyncWorldEdit Version Number:** 
WorldEdit version 1.15-180;004a60d

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-224 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
The compassport/worldedit navigation tool teleport (left click) teleports the player not to the top of the target block, but to the center of the target block. One will be stuck in the middle of the block after a teleport. The same teleport behavior applies to other commands, such as /ceil.

**How to replicate**:
1. Leftklick with the worldedit navigationtool
2. You will get stuck in a block

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Momonche** [comment]
+1

**Comment by TheoRetisch1** [comment]
Confirmed for FAWE version 1.15-192;5fb1825.

**Comment by Momonche** [comment]
Confirmed for FAWE version 1.15-193

**Comment by TheoRetisch1** [comment]
confirmed for version 204

**Comment by kikelkik** [comment]
confirmed for #227

**Comment by iamtheRichie** [comment]
I'm facing the same problem. As the compass teleport is a common teleportation tool on my server the bug affects almost all players, even apart from classic worldedit activities. It looks like an increasing number of other server owner in this thread are interested in this feature. So it would be cool if you don't rank this feature with the lowest priority. Especially as in this case no complex asynchron operations are required, but only a reasonable amount of maths.
