### ISSUE TITLE
No permission differentiation between navigation.jumpto and navigation.thru

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#427]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/a4954efda8514abcad817ecd7d5d2756

**FastAsyncWorldEdit Version Number:** 
WorldEdit version 1.15-180;004a60d

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-224 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
Actually one should be able to differentiate the right click and left click function of the navigation tool with the permissions _worldedit.navigation.jumpto.tool_ and _worldedit.navigation.thru.tool_. This is not the case with FAWE: If you have the permission _worldedit.navigation.jumpto.tool_ you can perform **both** actions.
Unfortunately the permission _worldedit.navigation.thru.tool_ has no effect, even if you explicitly set it to _false_ you can still port through walls with a right click. With Luckperms verbose you can see that FAWE only queries the permission _worldedit.navigation.jumpto.tool_ for both actions.

**How to replicate**:
1. Set your permission for _worldedit.navigation.jumpto.tool_ to true and for  _worldedit.navigation.thru.tool_ to false.
2. Left and right click with the navigation tool. Both actions will work.
3. Optional: Use luckperms in order to monitor the queried permission (_/lp verbose <user> & worldedit_). You will notice that only _worldedit.navigation.jumpto.tool_ will be queried.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by kikelkik** [comment]
I can confirm it. 
jumpto (in navtool or just the command) are not teleporting properly - you're always block-shifted.

**Comment by aurorasmiles** [comment]
FAWE only checks worldedit.navigation.jumpto.tool for the navigation wand, upstream does that different and checks the permissions elsewhere. 
(worldedit-core\src\main\java\com\sk89q\worldedit\command\tool\NavigationWand.java line 63)
