### ISSUE TITLE
Server Crash/ Clipboard broken

### ISSUE THREAD

**Issue by maaatthias** [IntellectualSites/FastAsyncWorldEdit#428]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/9e87eab9886649638c42d7f7249564d8

https://hastebin.com/zoyisofeca.rb // crash-report 1
https://hastebin.com/cebironilo.rb // crash-report2

FastAsyncWorldEdit Version Number :
[15:51:28] [Craft Scheduler Thread - 0/INFO]: FastAsyncWorldEdit-180 created by Empire92
[15:51:28] [Craft Scheduler Thread - 0/INFO]: FAWE version:
 - Date Apr 25, 2020 12:00:00 AM
 - Commit fffb59f3
 - Build 180
 - Platform Bukkit
[15:51:28] [Craft Scheduler Thread - 0/INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[15:51:28] [Craft Scheduler Thread - 0/INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-180;004a60d)

[15:51:28] [Craft Scheduler Thread - 0/INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running CraftBukkit version git-Spigot-e7dc2f5-a8ec1d6 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
The Server crashs, if i use for example buttons or repeater. 
I think, some data for these blocks are missing. 

**How to replicate**:
Probably pasting a schematic with complex redstone machines

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
I don't think I have seen this show up on Paper servers yet. Maybe it is a bug specifically with Spigot?

**Comment by dordsor21** [comment]
This should be fixed by proxy of a number of ChunkSection improvements. Also, the error logs have been deleted from Hastebin.
