### ISSUE TITLE
//undo doesn't bring back blocks for the second undo 

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#429]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

default
**[REQUIRED] FastAsyncWorldEdit Version Number:** 

build 180
**[REQUIRED] Spigot/Paper Version Number:** 

paper 220 1.15
**[REQUIRED] Description of the problem:**

Weird title, weird issue. Sometimes, when doing multiple operations in a row, only the first thing you did gets undone correctly. The operations after the first one are somewhat undone when using //undo, for example when undoing //set stone the stone dissapears, but the blocks that were there before the stones do not reappear as they should.
Videos because idk how to describe it better:
https://youtu.be/QOHxWKVGQCE
**How to replicate**:

Do a few things and then //undo, see what happens

**Plugins being used on the server:**

FAWE
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Have you checked to see if those emerald blocks may have been ghost blocks? You can check by relogging or placing a block next to where the emerald blocks should be. Sometimes right clicking where the block should be updates it too.

**Comment by aurorasmiles** [comment]
No ghost blocks :/

**Comment by dordsor21** [comment]
These blocks are ones placed/removed by the player. The latest build should fix it, as it correctly reads the world as and when needed (though perhaps a little at the detriment of performance, but that can be sorted later)

**Comment by aurorasmiles** [comment]
I'll go ahead and reopen this, since I was able to still replicate that issue.
It happens waay less often and not close to how often it happend before your changes, but I still managed to get this 2/10 tries

**Comment by dordsor21** [comment]
Interesting. Is this player placed/removed blocks? What commands were you using, how many chunks, etc? Is it the same as the video again?

**Comment by aurorasmiles** [comment]
Player placed, and it only seems to happen when I place those blocks next to stuff I worldedit'ed. Same as in the video basically^^
