### ISSUE TITLE
brush flatten on sand sometimes brings up stuff from below

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#430]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

unchanged
**[REQUIRED] FastAsyncWorldEdit Version Number:** 184#1.15

**[REQUIRED] Spigot/Paper Version Number:** 226#1.15

**[REQUIRED] Description of the problem:**

The flatten brush sometimes shows some unusual behaviour, most often when used on sand. You can often see that parts of dungeons/caves way below the surface, and sometimes even bedrock, get dragged up to the surface making weird structures, instead of just flattening the surface. Here are a few pictures to illustrate what i mean:
https://drop.cutiepie.at/6la9pjdch47rqumz
https://drop.cutiepie.at/p86i3g700ciix332
https://drop.cutiepie.at/h3atwx62mfjpg8po
**How to replicate**:

//brush flatten 10
Use it on sand, a beach for example
**Plugins being used on the server:**

FAWE
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
As you can see in the last picture, it's not just limited to sand, but I found that it happens most with sand

**Comment by Uirebaeron** [comment]
Having same issues is this what Is also happening with you? https://imgur.com/a/a7dlJ6R Please note I'm no dev just doing a friendly advice use imgur instead of other image sharing sites tried to view the 3 pictures but all them failed for me to see if you had the same problem as me.

**Comment by aurorasmiles** [comment]
Sorry, I just took the pictures as my builder send me. Fixed the links now.

**Comment by dordsor21** [comment]
Seems to have been fixed at some point
