### ISSUE TITLE
< 1.15 Schematics are not loaded

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#434]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/895cea08028047a0b48c251641011c7d

**FastAsyncWorldEdit Version Number:** 
1.15-192;5fb1825

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-229 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
Schematics from versions 1.12 and 1.13 can no longer be loaded. You can load and paste them without errors, but not a single block appears ingame. This is also true for all schematics created in previous versions from plugins like AreaShop or ARM for region management.

In some rare cases there is also an error in the log: https://pastebin.com/MVJWYmr1

Schematics created in version 1.15.2 work very well.

**How to replicate**:
1. load one of the two provided test schematics: https://cloud.minecraft-corp.de/index.php/s/TZzbFrSq6jyeYLP
2. //paste
3. no content appears

**Request <3**:
Maybe you would be so kind to write a short note if the bug can be fixed in the next weeks or if it would be reasonable if I start to work myself through of the hundreds of schematics by hand by creating a 1.13 world and upgrading it :) 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Fixed in 3abf964620fc968a2f23dad5310b84f2dd29ce43 - you used to have to manually specify the schematic format (it didn't use the file extension). On older versions use `//schem load <schematic> MCEDIT`

**Comment by TheoRetisch1** [comment]
Thank you for the info! The problem of loading legacy schematics is that the reference point is not converted. With legacy schematics, it is always at the same corner. In particular with schematics for planting (trees, bushes ...), which make up the main part of the schematic folder, you need the correct reference point to place the schematics correctly. Do you think it will be possible to convert the reference point or should we prepare ourselves for the renewal of all schematics?
