### ISSUE TITLE
Server crash after copying 3 million blocks

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#435]
**FastAsyncWorldEdit Configuration Files:** 
I logically don't have any debugpaste with the crash, but here is the general setup: https://athion.net/ISPaster/paste/view/6e6a4c89fa134020966089c1b42adc38

**FastAsyncWorldEdit Version Number:** 
1.15-192;5fb1825

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-229 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
After copying 3 million blocks, the server is shut down.The number was no problem in previous versions, the server runs on an i9-9900K. There was no warning that the selection is too large.
Error: https://pastebin.com/rF6sagBY

**How to replicate**:
Copy a large selection, but the error does not always occur.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin, at least I hope so xD. Tell me if I can specify the issue :)

**Comment by TheoRetisch1** [comment]
It happened again a user copied too many blocks and the server crashed :/

Error: https://pastebin.com/6iaSEiuG
FAWE - 195

**Comment by IronApollo** [comment]
Is this issue consistently replicable or does it only occur during seemingly random copies of large areas?

**Comment by TheoRetisch1** [comment]
Yes the bug is very consistent even on version 197, just provoke it and copy much more than 3 million blocks. With 5 million blocks it's guaranteed to crash on my server. It should be no problem to reproduce the bug, the effect is striking xD

**Comment by IronApollo** [comment]
I was unable to reproduce this on build 200. Try again on build 200 and we can go from there!

I copied ~5 million blocks and had no issue.

**Comment by TheoRetisch1** [comment]
Mhh my server is still crashing on version 201 copying ~5 million blocks, what information can I provide?

**Comment by TheoRetisch1** [comment]
Well, it'd be pretty cool if we could get forward with this ticket. Even small copy jobs crash the server. 

First of all, I would be interested to know which configuration is not causing the problem for you. Paper and FAWE are up to date and I even had the folder regenerated -> same error. Maybe you could send me a debugpaste here, so we can compare our setup.

Additionally, two more pieces of information:
1) It does not matter what is copied. Air and sandstone blocks lead to crashes as well as complex block mixes and entities.
2) When using //lazycopy and //lazycut even much higher numbers of blocks are copied quickly and without crashes.

If you can't find the cause of the crash, you could simply trigger the lazycopy mechanism on //copy. Getting people to stop using the //copy command is quit difficult.

FAWE - 217
Paper 1.15.2 - 273

**Comment by IronApollo** [comment]
I will retest on the latest release and update you later when I'm off work.

**Comment by TheoRetisch1** [comment]
The server still crashes if you do not use //lazycopy. What is the difference between //copy and //lazycopy?

FAWE - 245
Paper 1.15.2 - 304

**Comment by aurorasmiles** [comment]
I guess the difference is that lazycopy does some things with history different - what exactly I can't tell you tho.
But for me, copying over 64 million blocks just worked fine, it took 63 seconds but the server did not crash or anything

**Comment by TheoRetisch1** [comment]
That's weird for me it crashes every time and it won't be the hardware. Could you send me a FAWE debugpaste so I can compare our setups?

**Comment by aurorasmiles** [comment]
I just set up a bare paper server with 304 paper and 245 fawe, nothing out of the ordinary. Java 8

**Comment by TheoRetisch1** [comment]
The crash is caused by SelectionVisualizer. In the newer builds there is now also a nullpointer exception (https://pastebin.com/Dh5UPrU4). The plugin never had performance problems in the last three years, even if you selected the whole world. Very odd is also that //lazycopy does not crash the server. So if you know which API change could be responsible for the bug, this information would be very helpful for Zrips :)

FAWE - 252
Paper 1.15.2 - 318
SelectionVisualizer 3.0.0.7

**Comment by TheoRetisch1** [comment]
The issue has been fixed :)
