### ISSUE TITLE
Area superpickaxe does not differentiate between block type - deletes it all

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#436]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/6f1125d1f29242e98ce5b1dedf7120ca

**FastAsyncWorldEdit Version Number:** 
1.15-192;5fb1825

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-229 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
The area superpickaxe  (example: _/sp area 4_) should delete all blocks of the same type in the specified radius.
Now it simply deletes all blocks in the given radius.
It would be cool if you could restore the function this pickaxe had for years. Removing only the blocks of one type is much more useful than simply deleting all blocks.

**How to replicate**:
1. /sp area 4
2. left click
3. All blocks in the area get removed instead of all blocks of the block type one left clicked.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by TheoRetisch1** [comment]
Awesome thanks :)

**Comment by kikelkik** [comment]
Sorry, but /sp recur still doesn't work well while /sp area is fine now.

![fawe sp recur](https://user-images.githubusercontent.com/14167723/82869295-48fbe080-9f2e-11ea-99cf-2a59c3d0c6c6.png)

**Comment by aurorasmiles** [comment]
Can you tell me what exactly recur should do?

**Comment by kikelkik** [comment]
It should only break same blocks with a direct connection to the target block within the given radius.
In difference: /sp area breaks same blocks within the radius even if they aren't connected.
