### ISSUE TITLE
Simplex Comeback

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#437]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I can only achieve a reasonable distribution under high effort and think back to the good old simplex command.

**Describe the solution you'd like**
I would be very happy if the simplex distribution would be available again as pattern and mask. It was a great tool for texturing and flowering. I think the functionality of simplex doesn't need to be explained here again, because it was sufficiently implemented in the previous versions.

**Describe alternatives you've considered**
-

**Additional context**
Keep up your great work :)

**Comment by MattBDev** [comment]
I said yesterday on Discord I am working on it

**Comment by TheoRetisch1** [comment]
Ok awesome thank you! Shoudl I close this?

**Comment by MattBDev** [comment]
No it's fine. Let's leave it open until I push the changes. I found a bug in the simplex math I need to fix in addition to re-adding the masks/patterns

**Comment by TheoRetisch1** [comment]
I just want to add that it would be pretty cool to also use simplexes in simplexes again. Example: //br rock #simplex[50][50][0][#simplex[30][159:1,159:2,159:3,159:4,159:5]] 20. this allows a less constant  = more natural distribution.
If you need an overview of how and for what the simplex command was used, you can find a nice illustrated guide from Mulcho here: https://imgur.com/a/rwVAE

**Comment by SirYwell** [comment]
As of build 268, the simplex pattern *should* work again. It needed some basic changes on how commands are parsed so please report if any other commands aren't **accepted** anymore, please let me know.
