### ISSUE TITLE
Stairs replacement only works for one direction

### ISSUE THREAD

**Issue by Drc-DEV** [IntellectualSites/FastAsyncWorldEdit#440]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/553a8edaa6a345a787cae49c91a5e401

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
192

**[REQUIRED] Spigot/Paper Version Number:** 
1.15.2

**[REQUIRED] Description of the problem:**
replacing stairs does not work for 3 out of 4 directions

**How to replicate**:
place stairs like in picture, 
![immagine](https://user-images.githubusercontent.com/33911680/80868216-59a39880-8c99-11ea-8045-72a1191d0a7a.png)

execute //replace stone_stairs sandstone_stairs
enjoy

**Plugins being used on the server:**
read the paste above

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by TheoRetisch1** [comment]
I would like to point out that the bug report is not very specific, it's more a feature request. The shown replace command has _never_ worked like this with FAWE or Worldedit. In the past you specified the ID after the colon, today you specify the orientation in square brackets (example: //replace sandstone_stairs[facing=south] sandstone_stairs[facing=north]). In the past on was able to shorten the command using _#id_ (//replace sandstone_stairs sandstone_stairs#id[sandstone_stairs]), but unfortunately the #id pattern is not yet integrated in the 1.15 version. If this was too exhausting for you, you might have tried something like the external typereplacer feature of Arceon. But this is a thing of the past under version 1.15 at the moment xD.

**Comment by Drc-DEV** [comment]
Coming from 1.12 FAWE, if I did //replace oak_stairs spruce_stairs it would replace all stairs' material, keeping their data unchanged.

**Comment by TheoRetisch1** [comment]
Ohh ok, sorry, I didn't knew that. It has been some time since I played 1.12 xD. Would definitely be cool :D

**Comment by Drc-DEV** [comment]
This is more of an essential feature, than a cool one. Since post-flattening blocks do not have an ID, you basically can't replace those with a different facing than south at this point in time in any way via FAWE (that I know of).

**Comment by niborbb** [comment]
This behaviour extends to even more blocks. 
Every block that has a direction, so logs, pillars, gates, dispenser etc. can only be replaced if they face a specific direction or axis, which is "x" for 3-directional blocks and "north" for 4-directional or 6-directional blocks. If these blocks can have a type like "up" / "bottom" etc, only the "bottom" variant will be replaced.
Tested with FAWE build 192 and Paper 237
