### ISSUE TITLE
The masks > and < do not work

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#441]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/a1bf15fc1bde497ea808a1d80d8772d2

**FastAsyncWorldEdit Version Number:** 
WorldEdit version 1.15-192;5fb1825

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-229 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
The "larger/smaller than" masks does not work, even tho they give command feedback of "Global mask set". If you set them as a mask, nothing happens, regardless of the action you choose.

**How to replicate**:
1. /gmask >2 or /gmask <2
2. //set 1 on a gras area
3. Nothing will happen

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by kikelkik** [comment]
can reproduce it. 
The problem might be going further: I can't even combine masks within a gmask.
/gmask 0&[>2] is not been accepted. But it has been right syntax before 1.15.

Seems that lots of syntax characters like [, ], & aren't accepted anymore ( /gmask [1,2] fails)

**Comment by MattBDev** [comment]
This type of stuff is included in the work I am doing to reimplement patterns and masks like simplex.

**Comment by dordsor21** [comment]
Fixed in a2b0a5e6225e0530e0695e0b4c421db6c679163c

**Comment by TheoRetisch1** [comment]
Well the > and < mask work now and that is very cool! Unfortunately, the combinations mentioned by kikel, e.g. /gmask [>2]&0 does not work.The > and < mask is often used, but in the rarest of cases without additional parameters.  Can we please reopen the bug report until the full functionality is restored. I think MattBDev's current efforts give cause for hope :)

FAWE - 217

**Comment by aurorasmiles** [comment]
While I currently can't test your issue, I reopened this so that it doesnt get lost

**Comment by dordsor21** [comment]
& is a known issue but isn't to do with > and <. Closing
