### ISSUE TITLE
The biome functionality is broken in many places

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#443]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/85a231d84a4e4de69a7da8fb32631abd

**FastAsyncWorldEdit Version Number:** 
WorldEdit version 1.15-192;5fb1825

**Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-229 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
- Changing biomes in a selection changes the biome in the whole chunk.
- The #biome pattern does not work at all, it seems not to be implemented yet (example: //replace stone #biome[roofed_forest])
- Biomasks don't work properly (example: /gmask $savanna), they always provide a fragmented output where the biom ends 

**How to replicate**:
1. select a block
2. //setbiome forest
3. the whole Chunk changed its biome (display with f3 +g)
-------------------------------------------------------------------------------
1. //setbiome savanna in a rectangular selection
2. /gmask $savanna
3. //set 1 -> there is no square, but something like this: https://imgur.com/a/0qWGWiW

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
So this is half bug and half stuff I have to reimplement?

**Comment by dordsor21** [comment]
//setbiome should be fixed.

Biome masks are sort of fixed, but it will accept random blocks that are not the correct biome.

Leaving open till the random blocks are fixed.

**Comment by kikelkik** [comment]
Well //setbiome seems now to be fixed.

/gmask $savanna works well, but still neither /gmask #biome[savanna] nor /mask $savanna nor /br sphere $savanna

But I think thats already part of your mask rework ( &, [, ], don't work )
