### ISSUE TITLE
Region restrictions problem

### ISSUE THREAD

**Issue by kial1** [IntellectualSites/FastAsyncWorldEdit#444]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://pastebin.com/AYhd14TF https://pastebin.com/kED55Daa https://pastebin.com/NPYVKEe1
**[REQUIRED] FastAsyncWorldEdit Version Number:** 

build 192
**[REQUIRED] Spigot/Paper Version Number:** 

Paper git-Paper-237
**[REQUIRED] Description of the problem:**

When you are using worldedit in a worldguard region, it will "block" the player by using any command (no response). Region restriction with worldguard is in general not working, you can worldedit everywhere.

**How to replicate**:

Just create a worldguard region (where you are not a owner) and use worldedit.

**Plugins being used on the server:**

FastAsyncWorldEdit, LuckPerms, Multiverse-Core, PlotSquared, WorldEdit, WorldGuard
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Will you please retest this with current latest version, https://ci.athion.net/job/FastAsyncWorldEdit-1.15/lastSuccessfulBuild/artifact/worldedit-bukkit/build/libs/FastAsyncWorldEdit-1.15-196.jar ?
Thanks!
