### ISSUE TITLE
brush cannot mask or do cylinder

### ISSUE THREAD

**Issue by Sonic8608** [IntellectualSites/FastAsyncWorldEdit#446]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

(log)  https://wtools.io/paste-code/b0TR
(config) https://wtools.io/paste-code/b0TS
(config-legacy) https://wtools.io/paste-code/b0TT

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

* Bukkit-Official(1.15-195;6dec0ab)
**[REQUIRED] Spigot/Paper Version Number:** 

[23:12:12 INFO]: This server is running Paper version git-Paper-243 (MC: 1.14.4)
 (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**[REQUIRED] Description of the problem:**

who - anyone with worldedit permission
when - anytime
where- anywhere
why - I do not know
how & what - refer to the message below
The brush does not seem to be functional, it cannot do cylinder or masking. I am not even sure if the brush mechanic is working at all. It is supposed to clear everything with air using cylinder and the mask is supposed to define the brush to eliminate only the grass and tallgrass or whatever 2 blocks you want.
**How to replicate**:

I did //brush cylinder air 5 5
       /mask minecraft:grass,minecraft:tall_grass
**Plugins being used on the server:**
 [23:15:54 INFO]: Plugins (32): AntiCreeper*, AntiCurse, BottledExp, Chairs, Core
Protect, Elevator, Essentials, EssentialsChat, EssentialsSpawn, FarmProtect*, Fa
stAsyncWorldEdit, GroupManager, Jobs, mcMMO, MessageAnnouncer, Minepacks, Phanto
mSMP, PlayMoreSounds, ProtocolLib, ProtocolSupport, QuickShop, Rankup, SalvageSm
elter*, ServerListPlus*, ServerRestorer, skRayFall*, Skript, TreeGravity, Vault,
 ViaVersion*, Warping*, WorldEdit

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Both the brush and the brush with the mask works perfectly fine for me, could not replicate

**Comment by Sonic8608** [comment]
> Both the brush and the brush with the mask works perfectly fine for me, could not replicate

seems to be working with the new update
