### ISSUE TITLE
Schematics not working

### ISSUE THREAD

**Issue by Ridaaaaaaa** [IntellectualSites/FastAsyncWorldEdit#447]
When ever I try to load a schematic in the schematic centre or through the schematic file it won't paste. I've tried renaming the files to .schem and .schematic however this does not make a difference, please help.

**Comment by dordsor21** [comment]
Fixed in 3abf964620fc968a2f23dad5310b84f2dd29ce43 - you used to have to manually specify the schematic format (it didn't use the file extension). On older versions use `//schem load <schematic> MCEDIT`
