### ISSUE TITLE
Critical: FAWE affecting vanilla command mechanics

### ISSUE THREAD

**Issue by kikelkik** [IntellectualSites/FastAsyncWorldEdit#448]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/23ee7f9947b14741997c6cc36969b32d

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
```
[09:48:24 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-196;3abf964)

[09:48:24 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 
```
[09:49:07 INFO]: This server is running Paper version git-Paper-246 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[09:49:07 INFO]: Previous version: git-Paper-240 (MC: 1.15.2)
[09:49:07 INFO]: You are running the latest version
```

**[REQUIRED] Description of the problem:**
I thought it was the best to capture a short video to demonstrate the bug. It is quite obvious to see the actual problem (see "How to replicate").
Without FAWE (so just that paperspigot version *without any other plugin*) it just works fine. So it is for sure that FAWE produces this misbehaviour.
Without doing that clone command it also works fine. 

**How to replicate**:
https://www.youtube.com/watch?v=7HVm8Q47Qw0&feature=youtu.be

**Plugins being used on the server:**
Plugins (2): FastAsyncWorldEdit, WorldEdit

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Just to clarify, the issue you are having is that when FAWE is installed, chained command blocks after a clone are not executed correctly?

**Comment by dordsor21** [comment]
Try disabling the tick limiter.

**Comment by TheoRetisch1** [comment]
Well, with the tick limiter deactivated, everything is running fine. The paper dev was not at all happy to hear that a FAWE tick limiter exists, they were bothered with the bug first. It was difficult to trace the bug back to FAWE, because after deactivating FAWE/the tick limiter you have to update the redstone partly manually. What does the function do or doesn't do when it is disabled?

**Comment by kikelkik** [comment]
Allright as @TheoRetisch1 said, it works now with **tick-limiter** disabled. 

I think it's okay to close this ticket, 

But we're still interested why FAWE wants to control server ticks apart from WorldEdit actions? 
And due to potentially more problems with that setting it might be better to **change that default setting to a disabled tick-limiter**.

**Comment by kikelkik** [comment]
But we're still interested why FAWE wants to control server ticks apart from WorldEdit actions?
And due to potentially more problems with that setting it might be better to change that default setting to a disabled tick-limiter.
