### ISSUE TITLE
EditSession must be reusable

### ISSUE THREAD

**Issue by FunnyGameNS** [IntellectualSites/FastAsyncWorldEdit#449]
**Is your feature request related to a problem? Please describe.**
Idk is this a bug or not, but blocks that were modified during specific edit session cannot be modified again. But other blocks (that weren't touched) can be modified (sometimes this don't work too). Someone on discord said me that it's working as intended, but i don't think so.

**Describe the solution you'd like**
So i suggest that flushing a session will neither completely close it nor disable modification of blocks at previously modified positions. I think it should just push the changes to the world because creating a new session every time i edit some blocks is very annoying.

**Additional context**
Example code (the "test" gets printed, but the stone block remains):
<img width="824" alt="Аннотация 2020-05-03 162314" src="https://user-images.githubusercontent.com/25716433/81166653-0b0a3d00-8fbe-11ea-9580-50428abe15be.png">
maxBlocks = -1 (in the session constructor)

**Comment by dordsor21** [comment]
We won't diverge from upstream for this functionality, as we agree that EditSessions should not be reusable. You should consider revising how you're doing what you're doing.

Read: https://worldedit.enginehub.org/en/latest/api/concepts/edit-sessions/
