### ISSUE TITLE
//br pull not working

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#450]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

unchanged
**[REQUIRED] FastAsyncWorldEdit Version Number:** 

197
**[REQUIRED] Spigot/Paper Version Number:** 

paper 229 1.15.2
**[REQUIRED] Description of the problem:**

Yeah, /br pull not working. A few indexOutOfBounds in the Console, but nothing more
**How to replicate**:

Use /br pull
**Plugins being used on the server:**

FAWE
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
This seems to have been fixed
