### ISSUE TITLE
Mask Air is broken.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#452]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
Config - https://paste.ubuntu.com/p/gmWcNXdgJr/
Config Legacy - https://paste.ubuntu.com/p/RDvFq4ynDZ/

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FAWE Bukkit-Official 1.15-204;56c7209

**[REQUIRED] Spigot/Paper Version Number:** 
Paper dev 245 (Spigot 1.15.2)

**[REQUIRED] Description of the problem:**
Setting a mask type of air causes various issues such as brushes pasting with incomplete operations.

**How to replicate**:
* /brush sphere sponge 15
* Able to paste round spheres perfectly fine.
* /mask air
* Spheres pasted now are cut in half and various odd shapes.

![link](https://i.imgur.com/8QATTYR.jpg)

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Orlaando-dev** [comment]
I’m pretty sure masks are on the todo to be worked on at the moment.

**Comment by IronApollo** [comment]
Does this only happen with the air mask or any block mask applied?

**Comment by MattBDev** [comment]
The air mask should work without a problem. I wrote it myself and tested it.

**Comment by mibby** [comment]
I'm able to reproduce this 100% of the time with mask air. However the bug seems to exist when you replace air no matter the command, such as ``//replace air stone``, so it might be related to air itself instead of mask.

**Comment by MattBDev** [comment]
Maybe @dordsor21 can figure this out since he worked on the replace command recently.

**Comment by mibby** [comment]
@dordsor21 Still seem to be getting reports that commit https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/ffa25b1d9a5be02218e34bc81a01849fb061108e didn't fully fix the problem with air. 

FastAsyncWorldEdit dev 315
FastAsyncVoxelSniper dev 14

![link](https://i.imgur.com/52JtPbA.png)
