### ISSUE TITLE
Origin point is not being read / used when loading & pasting schematics.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#454]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
config: https://paste.ubuntu.com/p/9hDB8hdgSM/
config-legacy: https://paste.ubuntu.com/p/MkQDTRFwNw/

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit dev 217

**[REQUIRED] Spigot/Paper Version Number:** 
Paper dev 269 (Spigot 1.15.2)

**[REQUIRED] Description of the problem:**
Is there any way to paste schematics from the point it was saved at? Vanilla WorldEdit correctly pastes from the origin location of saving whereas FAWE seems to paste the schematic from the bottom corner of the schematic in relation to where the player currently is.

Just for clarification, this is an older schematic that does have its origin saved and is a schematic from vanilla WE. It pastes fine with WorldEdit dev 4997, just FAWE doesn't seem to read the origin location. I assume it's a clipboard issue if it can't read the origin from the schematic. 

I tried using ``/paste -o`` to see if the original location preserves origin point, but it ended up just pasting at 0,0 coordinate instead.

**How to replicate**:
https://cdn.discordapp.com/attachments/119102811421147138/707623483055538236/FullMetalBoon.schematic

This is the schematic I was using for testing. Normally it pastes from the middle, stood at the entrance to the house -- as that is where the schematic was saved. With FAWE trying to paste, it pastes from the corner of the schematic to your location.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Webbeh** [comment]
So I can confirm this issue happens with me.
Schematic created with an old version of worldedit (6 I believe), and they pasted correctly with WorldEdit 7.

The code I'm using :
`
 public void paste(String mapName, String schematicName)
    {
        World w = Bukkit.getWorld("Siege");
        schematicName = schematicName.replaceAll("\\.schematic", "");
        schematicName = schematicName.replaceAll("\\|", "+");


        try (EditSession session = WorldEdit.getInstance().getEditSessionFactory().getEditSession(BukkitAdapter.adapt(w), -1))
        {
            String folder = Base.getPlugin().getDataFolder().toPath().resolve("schematics").resolve(mapName).toString();
            File rep = new File(folder);

            File[] listOfFiles = rep.listFiles();

            if(listOfFiles==null) return;
            for (File f : listOfFiles)
            {
                if(f.isFile() && f.getName().toLowerCase().startsWith(schematicName.toLowerCase()))
                {
                    Clipboard clipboard;
                    ClipboardFormat format = ClipboardFormats.findByFile(f);
                    if(format==null) return;
                    try (ClipboardReader reader = format.getReader(new FileInputStream(f))) {
                        clipboard = reader.read();

                        Debug.info("Origin : "+clipboard.getOrigin());
                        Operation operation = new ClipboardHolder(clipboard).createPaste(session)
                                .to(clipboard.getOrigin())
                                .ignoreAirBlocks(false)
                                .copyEntities(true)
                                .build();
                        Operations.complete(operation);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }`

Vanilla worldedit 7 (latest dev build) takes the origin proplerly.
FAWE returns an origin of 0,0,0.

**Comment by Webbeh** [comment]
https://edelblack.dev/helms_wall_ok.schematic
https://edelblack.dev/helms_wall_broken.schematic

With FAWE :
https://youtu.be/bZMDbK9W1hc

With WE : 
https://youtu.be/eWBabYC2enU

**Comment by LihP** [comment]
Thanks for reporting this, I can confirm I have the same issue, the origin of loaded schematics is 0, 0, 0 for old and new.

**Comment by jaapieaapie1** [comment]
can this be fixed please 👍
