### ISSUE TITLE
Height brushes doesn't work properly

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#456]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/3bb1176c9a6f4c008df610fb3a306aa2

**FastAsyncWorldEdit Version Number:** 
WorldEdit version 1.15-217;4f2b0e6

**Spigot/Paper Version Number:** 
 git-Paper-273 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
1. If you use a height brush (e.g. /br height 5) every third click results in gigantic columns. If you undo the actions and edit the same place again with the same brush, the brush works reliably. But as soon as you work on a new position the columns will be created again.
![2020-05-10_15 54 45](https://user-images.githubusercontent.com/24480321/81501507-06ed6080-92d9-11ea-93d9-c1915cb6ff21.png)

2. It is not possible to use a height brush with a linked imgur image (I tried different combinations). The brush can not be laid on a tool. I assume that this is not a bug, but the feature has not been reimplemented yet?

**How to replicate**:
/br height 5
/br height 100 http://i.imgur.com/Z1Ocy8y.png 0.0 0.4 -r

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
Works for me on the latest build ([235](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/235/artifact/worldedit-bukkit/build/libs/FastAsyncWorldEdit-1.15-235.jar)). For the image, you need to use `https`.
![grafik](https://user-images.githubusercontent.com/11150076/82042956-0ffc7a00-96ab-11ea-85c4-1e9b75921975.png)

**Comment by TheoRetisch1** [comment]
You are right about the `https`, the embedding of height maps works great. Thank you for figurierung that out!
I still have the illustrated problems with the columns. However, it turned out that they only occur on my original test world.
The world has a y-level of 64, is flat and consists only of sandstone except for one level of bedrock.

In other worlds the height brush works wonderfully, I tested the following scenarios:
- Newly generated 1.15 vanilla world
- Converted vanilla world
- Flat world with a y-level of 50 consisting out of dirt-/grasblocks with one layer of bedrock

**Comment by SirYwell** [comment]
That's... interesting. I can confirm that behaviour on the world I tested it initially.

The only pattern I can find in this behaviour is that those spikes are on chunk corners/edges. Also, it seems to happen less often when editing an area a while, but that could be pure coincidence too (I used the brush on a plot and cleared it a few times. I didn't get spikes after the third one. Similar behaviour on another plot).

**Comment by TheoRetisch1** [comment]
Yes!, I have observed the same behaviour after working on an area and tried to describe it in the original report. Cool that you had the same problem. I thought already now my problem is getting much too special to deal with it properly xD.

**Comment by aurorasmiles** [comment]
Maybe related to #430 ?

**Comment by TheoRetisch1** [comment]
Yes, the bug I described also raises a layer of the world (in this case bedrock and sandstone) as a column to the surface. The only difference to your bug report is that I have not yet succeeded in reproducing the bug in a "normal" world.

**Comment by SirYwell** [comment]
As a temporary workaround: `//undo`ing spikes and using the brush again seems to _kind of reliable_ fix it at the used location

**Comment by dordsor21** [comment]
This appears to have been fixed.
