### ISSUE TITLE
Option to restrict commands / brushes / tool binding to "tools" only.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#458]
**Is your feature request related to a problem? Please describe.**
Using Vanilla WorldEdit, when you try to bind a worldedit tool such as ``/tree`` to anything other than a weapon/tool, it would give you an error that a tool cannot be bound to blocks. With FAWE, it binds to anything. This is causing some confusion with players when having persistent brushes where they can't place blocks down anymore unless / until they ``/tool unbind``.

**Describe the solution you'd like**
An option to restrict binding back to tools only instead of anything to avoid confusion with permanent persistent tools on blocks.

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.

**Comment by dordsor21** [comment]
This is now forced.
