### ISSUE TITLE
//rotate and //flip do not work nicely together

### ISSUE THREAD

**Issue by pascal541** [IntellectualSites/FastAsyncWorldEdit#462]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/8875084ee6394d38af84a45c6623cde4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-225 created by Empire92
FAWE version:
- Date May 11, 2020 12:00:00 AM
- Commit ff000247
- Build 225
- Platform Bukkit
Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
------------------ Platforms ------------------
* Bukkit-Official(1.15-225;0fffdb9)
---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Stairs don't align properly when pasting after using //flip

Selection
![image](https://user-images.githubusercontent.com/7486865/81727888-ed3f4b00-9489-11ea-9c9b-03cba0b496fb.png)

After //rotate 90
![image](https://user-images.githubusercontent.com/7486865/81727981-07792900-948a-11ea-9b8d-9e6dee22b75e.png)

After //flip
![image](https://user-images.githubusercontent.com/7486865/81728077-2972ab80-948a-11ea-949a-8dde9e755b9e.png)

**How to replicate**:
- Place some stairs
- Select the stairs
- Use //copy
- Use //rotate 90
- Use //flip
- Use //paste

**Plugins being used on the server:**
Plugins (7): Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, VoxelSniper, WorldEdit

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Peter-Crawley** [comment]
please fix this soon

**Comment by LaurenceBarnes** [comment]
I do encounter the same on build 715 and build 718 on Purpur 1.16.5, when using //rotate 90 and //flip south.

![2021-06-10_20 12 18](https://user-images.githubusercontent.com/77249464/121576414-a4f5b200-ca28-11eb-9953-167ad1c8eed3.png)
