### ISSUE TITLE
Using //mask creates weird pattern

### ISSUE THREAD

**Issue by StealWonders** [IntellectualSites/FastAsyncWorldEdit#463]
# Bug report for FastAsyncWorldEdit 1.15.2

**FastAsyncWorldEdit Version Number:** Bukkit-Official(1.15-227;32c30f4)
**Spigot/Paper Version Number:** git-Paper-280 (MC: 1.15.2)

**Description of the problem:**
When using `//br sphere 1 5` , `//mask <2` and then brushing near water
the following pattern seems to appear after a while of brushing near water:

![2020-05-12_19 58 25](https://user-images.githubusercontent.com/6114858/81729022-9dfa1a00-948b-11ea-971c-81d4ea06c9a4.png)

**How to replicate**:
Use `//br sphere 1 5`  & `//mask <2`

**Checklist**:
- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
This is fixed
