### ISSUE TITLE
//drain <radius> doesn't drain water-logged blocks

### ISSUE THREAD

**Issue by StealWonders** [IntellectualSites/FastAsyncWorldEdit#464]
# Bug report for FastAsyncWorldEdit 1.15.2

**FastAsyncWorldEdit Version Number:** Bukkit-Official(1.15-227;32c30f4)
**Spigot/Paper Version Number:** git-Paper-280 (MC: 1.15.2)

**Description of the problem:**
When using `//drain 100` in water it doesn't actually remove the water from water-logged blocks, 
for example, sea-grass. Screenshot:

![2020-05-12_20 04 54](https://user-images.githubusercontent.com/6114858/81729365-211b7000-948c-11ea-802f-05ee7acb2268.png)

**How to replicate**:
Use `//drain 100` in water

**Checklist**:
- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
using `//drain <radius> -w` will now work to remove water from waterlogged blocks. Kelp will remain waterlogged, and this is the same behaviour as default WorldEdit, as it cannot exist otherwise.
