### ISSUE TITLE
Schematic Load & then paste causes air to be stone

### ISSUE THREAD

**Issue by Kirrasio** [IntellectualSites/FastAsyncWorldEdit#468]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/e563a6b38f8b4da3b87bfca4b852dffb

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

13.05 18:00:11 [Server] Craft Scheduler Thread - 2/INFO FastAsyncWorldEdit-228 created by Empire92
13.05 18:00:11 [Server] Craft Scheduler Thread - 2/INFO FAWE version:
13.05 18:00:11 [Server] INFO - Date May 13, 2020 12:00:00 AM
13.05 18:00:11 [Server] INFO - Commit fee7c384
13.05 18:00:11 [Server] INFO - Build 228
13.05 18:00:11 [Server] INFO - Platform Bukkit
13.05 18:00:11 [Server] Craft Scheduler Thread - 2/INFO Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
13.05 18:00:11 [Server] Craft Scheduler Thread - 2/INFO ------------------ Platforms ------------------
13.05 18:00:11 [Server] INFO * Bukkit-Official(1.15-228;1183c7c)
13.05 18:00:11 [Server] Craft Scheduler Thread - 2/INFO ---------------- Capabilities ----------------
13.05 18:00:11 [Server] INFO GAME_HOOKS: Bukkit-Official
13.05 18:00:11 [Server] INFO CONFIGURATION: Bukkit-Official
13.05 18:00:11 [Server] INFO USER_COMMANDS: Bukkit-Official
13.05 18:00:11 [Server] INFO PERMISSIONS: Bukkit-Official
13.05 18:00:11 [Server] INFO WORLDEDIT_CUI: Bukkit-Official
13.05 18:00:11 [Server] INFO WORLD_EDITING: Bukkit-Official
**[REQUIRED] Spigot/Paper Version Number:** 

This server is running CraftBukkit version git-Spigot-2f5d615-d07a78b (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**[REQUIRED] Description of the problem:**
Schematic pasting causes air to become stone. 

no errors

**How to replicate**:
Save a schematic, load schematic and paste.

**Plugins being used on the server:**

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

This is not occuring on this previous version we were on, I reverted and it's working as expected
This is the last version we were on -
 
13.05 20:34:26 [Server] Craft Scheduler Thread - 6/INFO FastAsyncWorldEdit-190 created by Empire92
13.05 20:34:26 [Server] Craft Scheduler Thread - 6/INFO FAWE version:
13.05 20:34:26 [Server] INFO - Date Apr 29, 2020 12:00:00 AM
13.05 20:34:26 [Server] INFO - Commit faf72a6b
13.05 20:34:26 [Server] INFO - Build 190
13.05 20:34:26 [Server] INFO - Platform Bukkit
13.05 20:34:26 [Server] Craft Scheduler Thread - 6/INFO Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
13.05 20:34:26 [Server] Craft Scheduler Thread - 6/INFO ------------------ Platforms ------------------
13.05 20:34:26 [Server] INFO * Bukkit-Official(1.15-190;508d595)
13.05 20:34:26 [Server] Craft Scheduler Thread - 6/INFO ---------------- Capabilities ----------------
13.05 20:34:26 [Server] INFO GAME_HOOKS: Bukkit-Official
13.05 20:34:26 [Server] INFO CONFIGURATION: Bukkit-Official
13.05 20:34:26 [Server] INFO USER_COMMANDS: Bukkit-Official
13.05 20:34:26 [Server] INFO PERMISSIONS: Bukkit-Official
13.05 20:34:26 [Server] INFO WORLDEDIT_CUI: Bukkit-Official
13.05 20:34:26 [Server] INFO WORLD_EDITING: Bukkit-Official

**Comment by IronApollo** [comment]
Possibly related to 999b063762e209ad8fcb61af2bab3238e18e3077 and/or 32c30f45fea5e223c66e4209fa5fef35660154cc. Requesting input from @dordsor21

**Comment by Kirrasio** [comment]
I'm going to add an update here, I just tried version Build #225 & it's not occuring on this build either.

**Comment by Kirrasio** [comment]
I don't understand, why was this closed? I can post a video if the issue happening?

**Comment by dordsor21** [comment]
It was fixed..?

**Comment by Kirrasio** [comment]
Oh, I'm sorry. I have had a long day ^^, I didn't see the update.
