### ISSUE TITLE
Plot clear hook disabled

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#469]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://pastebin.com/XuhJEDjM
https://pastebin.com/6qLz3Ckh

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.15-227

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-280 (MC: 1.15.2)

**[REQUIRED] Description of the problem:**
FAWE will improve the performance of /plot clear on PlotSquared but in PlotSquared v5 it doesn't work (I'm guessing it's disabled on purpose but creating this ticket so that the issue isn't lost), PlotSquared will use its own bukkit method to clear the plot which has performance problems when used on large plots.
![image](https://user-images.githubusercontent.com/10485646/81942265-d0be2280-95f1-11ea-8676-20413d0210a1.png)
From my brief discussion last year with Jesse about plot clearing, he said that it's bad because it uses bukkit methods to clear the plot but FAWE will use NMS to clear the plot which is much more efficient.

**How to replicate**:
Install PlotSquared 5.11.0 and FastAsyncWorldEdit-1.15-227, then use /plot clear on a large plot. In my case (505x505).

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
This is something we're planning to implement, but it never technically existed in the first place. It's more complex than you might imagine.

**Comment by dordsor21** [comment]
this is implemented now
