### ISSUE TITLE
Honeycomb blocks disappear when WorldEditing near and within the same chunk

### ISSUE THREAD

**Issue by WakkaFlocka239** [IntellectualSites/FastAsyncWorldEdit#470]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

fresh/unchanged
https://athion.net/ISPaster/paste/view/97cdeae58ffe4cdfbfbd2b832a5f46a4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

<img src= https://i.imgur.com/BEUTVbL.png>
**[REQUIRED] Spigot/Paper Version Number:** 

<img src= https://i.imgur.com/Wjx8EYe.png>
**[REQUIRED] Description of the problem:**

A) Worldediting (from what I've tested this includes //set, //replace, /brush's) blocks near (distance seems to vary) and within the same chunk as honeycomb blocks makes the honeycomb blocks get replaced with air, sometimes throwing a null (per block I assume) in console:

<img src= https://i.imgur.com/DaHXZa7.png>
B) //replacing a block with honeycomb block does nothing "0 blocks have been replaced", but //set works fine

**How to replicate**:

1) Hand place or //set honeycomb blocks in between multiple chunks
2) Edit a block within the same chunk and near the honeycomb blocks, and watch the honeycomb blocks disappear.

**Plugins being used on the server:**

<img src= https://i.imgur.com/RQU8wr1.png>

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
It's a pity the full stack-trace isn't there. Those do look like FAWE threads.

**Comment by WakkaFlocka239** [comment]
I didn't post the whole thing because it just repeats itself, and there's nothing more to the stacktrace.
Here's the whole error: https://paste.bnn.gg/faluw.txt

**Comment by dordsor21** [comment]
Yeah that's what I'm saying lol, it's annoying there's no full stacktrace

**Comment by stonegray** [comment]
I'm also having this issue.

**Comment by aurorasmiles** [comment]
Can't replicate this anymore
