### ISSUE TITLE
Users cannot tab complete pattern/materials into commands

### ISSUE THREAD

**Issue by DanielRoberts21** [IntellectualSites/FastAsyncWorldEdit#472]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/70b5b2e2fff943109f502c739090e01d

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
17.05 15:48:24 [Server] INFO FastAsyncWorldEdit-235 created by Empire92
17.05 15:48:24 [Server] INFO FAWE version:
17.05 15:48:24 [Server] INFO - Date May 14, 2020 12:00:00 AM
17.05 15:48:24 [Server] INFO - Commit fa41ee3b
17.05 15:48:24 [Server] INFO - Build 235
17.05 15:48:24 [Server] INFO - Platform Bukkit
17.05 15:48:24 [Server] INFO Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
17.05 15:48:24 [Server] INFO ------------------ Platforms ------------------
17.05 15:48:24 [Server] INFO * Bukkit-Official(1.15-235;5be11c5)
17.05 15:48:24 [Server] INFO ---------------- Capabilities ----------------
17.05 15:48:24 [Server] INFO GAME_HOOKS: Bukkit-Official
17.05 15:48:24 [Server] INFO CONFIGURATION: Bukkit-Official
17.05 15:48:24 [Server] INFO USER_COMMANDS: Bukkit-Official
17.05 15:48:24 [Server] INFO PERMISSIONS: Bukkit-Official
17.05 15:48:24 [Server] INFO WORLDEDIT_CUI: Bukkit-Official
17.05 15:48:24 [Server] INFO WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
17.05 15:49:00 [Server] INFO This server is running Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
17.05 15:49:00 [Server] INFO Previous version: git-Paper-283 (MC: 1.15.2)
17.05 15:49:00 [Server] INFO You are 14 version(s) behind

**[REQUIRED] Description of the problem:**
My players have all of FAWEs permissions and world edit permissions, but they cannot tab-complete any materials into the commands. OP players can tab complete all of the materials fine, but non-OP players cannot even though they have full fawe permissions and worldedit permissions.

**How to replicate**:
Give a player all FAWE permissions by setting fawe.* to true and worldedit.* to true also.

**Plugins being used on the server:**
17.05 15:51:13 [Server] INFO Plugins (23): BiomeFinder*, BlocksHub, CoreProtect, Elevators_v2, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, HealthTools, InventoryRollback, KeepChunks, LuckPerms, PlayerListPlus*, ProtocolLib, ServerRestorer, SuperVanish, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Tab completion does not work yet. If you would have used the search bar, like you ticked, you'd find several issues like that.
