### ISSUE TITLE
//wand doesn't work.

### ISSUE THREAD

**Issue by Nexxuser** [IntellectualSites/FastAsyncWorldEdit#477]
// wand doesn't work.
I use Tuinity 1.15 fork.

https://athion.net/ISPaster/paste/view/3b7e6abb6cc94e948e832cde70ce9d2f

http://haste.athion.net/cobimudasa.makefile

**Comment by aurorasmiles** [comment]
Wasn't able to replicate that issue. Could you try with a fresh config and without any other plugin? Also, please don't ignore the issue template.
