### ISSUE TITLE
< = 1.13 schematics doesn't load - sign error

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#478]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/76906bd2783641e4948d12b4ab08627b

**FastAsyncWorldEdit Version Number:** 
WorldEdit version 1.15-246;8fa493c

**Spigot/Paper Version Number:** 
Paper-304 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
Schematics from versions < = 1.13, which have contained signs do not load anymore. The following error occurs in the log: https://pastebin.com/z4QnfKyz
It looks like FAWE does not import the sign names changed in version 1.14.

**How to replicate**:
1. Load the provided test schematics: https://cloud.minecraft-corp.de/index.php/s/Sb9rqXH5nS2X63x
2. Take a look at the error in the log.
3. //paste
4. The schematic won't appear.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by normanfeltz** [comment]
Hey,

I have the same bug, the schematics doesn't load !

Log : https://hastebin.com/uhoqixezeh.sql

Cordially

Norman FELTZ
Lead of MineDisney

**Comment by aurorasmiles** [comment]
@TheoRetisch1 could you test if this issue still exists?

**Comment by TheoRetisch1** [comment]
Yeah the issue still exists. 
error: https://pastebin.com/0aqNmRpd
You can still download the test schematic here: https://cloud.minecraft-corp.de/index.php/s/Sb9rqXH5nS2X63x

FAWE: 1.16-401
Paper: 1.16.3 - 204
