### ISSUE TITLE
Reimplementation of the -p flag of the clipboard brush

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#479]
**Is your feature request related to a problem? Please describe.**
I am always very frustrated when I don't have a tool to place trees and bushes properly. 
Since this is a very common activity and only one parameter is missing, I thought it would be worthwhile to point this out in a ticket.

**Describe the solution you'd like**
The -p flag of /br clipboard should be reimplemented. The flag ensures that the clipboard is pasted centered on the surface. More precisely, it ensures that the clipboard is set relative to the reference point of the clipboard/schematic. Without the flag, the paste will simply appear centered on the target location. This means, for example, that a tree is stuck halfway into the ground.

The basic procedure for placing botany used to look like this:
_schem loadall <schematicfolder/> -r
br clipboard -a -p
gmask 0_
All functions except the -p parameter are already working. The reimplementation would be a huge improvement!

**Describe alternatives you've considered**
_Not available for version 1.15_: Schematicbrush, Arceon or any other publicly available or buyable tool for this purpose
For the purpose of the use _worse_ and _not yet reimplemented_ FAWE feature: #offset and br copypaste
_Conclusion_: The -p br clipboard flag would be the best solution!

**Comment by TheoRetisch1** [comment]
We are still facing the situation that the -p parameter does not work and at the same time the FAWE API has massive bugs in terms of pasting. So there is no possibility to brush trees and plants with FAWE. Therefore I would be very happy if the -p parameter could be reimplemented. After all, ingame planting of landscapes is not an unimportant part of the functionality :)

**Comment by TheoRetisch1** [comment]
The API interface for placing schematics works again! So the reimplementation of the -p paramter is not very important, because you can simply use a plugin like this one (https://www.spigotmc.org/resources/schematic-brush-reborn.79441/) and get a even higher functionality.

**Comment by aurorasmiles** [comment]
@TheoRetisch1 What's the difference between -p and -o?

**Comment by TheoRetisch1** [comment]
Uhm -o works wonderfully for the intended purpose. Maybe I just mixed up something? So the ticket can be closed :)
