### ISSUE TITLE
Limits are not respected

### ISSUE THREAD

**Issue by aurel85** [IntellectualSites/FastAsyncWorldEdit#481]
Hi,

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/66d8e51d58db4be6a7660677d271777e

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-246

**[REQUIRED] Spigot/Paper Version Number:** 
Paper-309 (1.15.2)

**[REQUIRED] Description of the problem:**
With fawe.limit I feel like I'm doing everything I need, but it doesn't work.
I created my block limit 10,000 with //set for group "player" and then I gave fawe.limit.joueur to the group "player" (I also tried on personal permission) but when the players in this group make //set stone more than 10,000 blocks it works :/
Is there something that I did not understand well in the functioning of fawe.limit ?
No error in console.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

Thank you in advance.

**Comment by daffyyyy** [comment]
same issue on 1.16.1

**Comment by anerevandrey** [comment]
same issue on 1.16.1
