### ISSUE TITLE
LoadAsync in plugin unable to function

### ISSUE THREAD

**Issue by Dziaod** [IntellectualSites/FastAsyncWorldEdit#485]
I use a plugin ([](https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-async-loading-expiration-economy-support-1-8-1-15.72113/)) and a function called loadasync doesnt work on 1.15.2.
It takes utalization of FAWE.
If you need to troubleshoot I can send you the plugin.

Here are my other plugins:
![grafik](https://user-images.githubusercontent.com/62385459/82831812-bde10300-9eb9-11ea-9db3-3f5ed4561f69.png)

DM me on Discord @ Dziaod#1409 for the plugin and just enable loadasync and join. The console should instantly be spammed and the player wont be let in. The server will crash 10-30secs afterwards, depending on the server speed.

**Comment by aurorasmiles** [comment]
Please clarify your issue
Can you show us your code? What errors are you getting? Has this worked before?

**Comment by Dziaod** [comment]
This hasnt worked before.
The code is not mine, it is the plugin.
[2020-05-25-3.log](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/4678319/2020-05-25-3.log)

**Comment by Dziaod** [comment]
Also the plugin link like got removed. The plugin is called playerworldspro

**Comment by dordsor21** [comment]
We won't change code to support premium plugins that are not open-source as there is absolutely no way to know what is going on. Ask the PlayerWorldsPro developer to make a PR to FAWE or fully detailed issue explaining what the problem is.
