### ISSUE TITLE
/setbiome requires client restart with FAWE (And worldedit) but not with Plots2 

### ISSUE THREAD

**Issue by Tabletopcheese** [IntellectualSites/FastAsyncWorldEdit#489]
I was fowarded here from FAWE support. 

How do i update biome with out requiring client restart? Just like plots2 does it.

**Comment by Tabletopcheese** [comment]
When you are using world edit for plots2 , with the /p setbiome command, biome changes are instant.

With FAWE , you still need a client restart

I was told to post here and ask how to do it or if there is an issue/bug

**Comment by dordsor21** [comment]
Cannot replicate and not enough info. Just repeating the labels I added.
