### ISSUE TITLE
API Schematic pasting

### ISSUE THREAD

**Issue by Pugabyte** [IntellectualSites/FastAsyncWorldEdit#491]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/37317821246648048c7c4209d476115c

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

![image](https://user-images.githubusercontent.com/12417961/83063005-7da29180-a02d-11ea-8d19-8ba9edae6c70.png)

**[REQUIRED] Spigot/Paper Version Number:** 

![image](https://user-images.githubusercontent.com/12417961/83063049-8dba7100-a02d-11ea-9515-f4d98672b3fd.png)

**[REQUIRED] Description of the problem:**

I'm trying to paste schematics through the API and getting the following error: https://paste.bnn.gg/selon

My code: [[link to full source]](https://github.com/Pugabyte/BNCore/blob/master/src/main/java/me/pugabyte/bncore/features/BNCoreCommand.java#L159-L171)

Snippets:
```
	public void save(String fileName, Region region) {
		save(fileName, region.getMinimumPoint(), region.getMaximumPoint());
	}

	@SneakyThrows
	public void save(String fileName, BlockVector3 min, BlockVector3 max) {
		CuboidRegion region = new CuboidRegion(worldEditWorld, min, max);
		new DiskOptimizedClipboard(region, UUID.randomUUID()).save(getSchematicFile(fileName), BuiltInClipboardFormat.SPONGE_SCHEMATIC);
		// also tried: 
		// new BlockArrayClipboard(region).save(getSchematicFile(fileName), BuiltInClipboardFormat.SPONGE_SCHEMATIC);
		// also tried MCEDIT schematic
	}

// pasting

	@SneakyThrows
	public Clipboard getSchematic(String fileName) {
		File file = getSchematicFile(fileName);
		if (!file.exists())
			throw new InvalidInputException("Schematic " + fileName + " does not exist");

		return ClipboardFormats.findByFile(file).load(file);
	}

	public void paste(String fileName, Location location) {
		paste(fileName, toBlockVector3(location));
	}

	public void paste(String fileName, BlockVector3 vector) {
		paste(getSchematic(fileName), vector);
	}

	public void paste(Clipboard clipboard, BlockVector3 vector) {
		clipboard.paste(worldEditWorld, vector);
	}
```

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You are saving schematics in the Sponge format, but managing to load them in the MCEdit format. That's... odd, and quite possibly fixed recently.
