### ISSUE TITLE
/thru Causes InvokationTargetException

### ISSUE THREAD

**Issue by Auxilor** [IntellectualSites/FastAsyncWorldEdit#498]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

**[REQUIRED] Spigot/Paper Version Number:** 

**[REQUIRED] Description of the problem:**

**How to replicate**:

**Plugins being used on the server:**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Thanks for this detailed bug report.
