### ISSUE TITLE
The Java to Bedrock converter (Nukkit) does not work for MC versions >= 1.13

### ISSUE THREAD

**Issue by acs** [IntellectualSites/FastAsyncWorldEdit#499]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

I am using the converter.

![Screenshot from 2020-06-06 13-25-51](https://user-images.githubusercontent.com/209533/83943069-5c922b80-a7f9-11ea-988b-55efbc72c39d.png)

`[Downloads]$ java -jar FastAsyncWorldEdit-nukkit-19.11.13-5505943-1282-22.3.5.jar`

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

19.11.13, the last one for the anvil to leveldb comverter.

https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/

**[REQUIRED] Spigot/Paper Version Number:** 

**[REQUIRED] Description of the problem:**

When I try to convert a Java world created with versions >=1.13 it does not work.

![Screenshot from 2020-06-06 13-00-22](https://user-images.githubusercontent.com/209533/83942953-8bf46880-a7f8-11ea-8e07-61435769dd41.png)

**How to replicate**:

**Plugins being used on the server:**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
We don't support this feature at the moment. There are no plans to re-add it. We have no plans to support Nukkit again.
