### ISSUE TITLE
REQUEST: Remove /jumpto "(FAWE) Poof!"

### ISSUE THREAD

**Issue by Llamasquishy** [IntellectualSites/FastAsyncWorldEdit#500]
**Is your feature request related to a problem? Please describe.**
_It's frustrating to players seeing "(FAWE) Poof!" constantly when using the /jumpto command. It fills the whole chat if they use it consistently._

**Describe the solution you'd like**
_I would love to have an option to completely eliminate the verbosity of the /jumpto command via an option in config.yml, or, preferably, through the lang/strings.json file that was removed in build 145._

**Describe alternatives you've considered**
_I've considered using the /jump command from the EssentialsX plugin, but it has other side-effects that make it unusable for my situation._

**Additional context**
_N/A_

**Comment by N0tMyFaultOG** [comment]
The commit of build 145 is not related to that, we are using a gradle task to setup the folder structure of the language task.
