### ISSUE TITLE
site not working

### ISSUE THREAD

**Issue by sasha0645** [IntellectualSites/FastAsyncWorldEdit#506]
please fix your server
https://empcraft.com/fawe/

**Comment by aurorasmiles** [comment]
Nice issue, much information, very helpful.
empcraft has been down for a while and we replaced it int the default configs for a while as well, so I don't get your issue.

**Comment by IronApollo** [comment]
That website is no longer in use. Please use the following steps to correct your issue:

1. Head to your /plugins/FastAsyncWorldEdit/config.yml
2. Replace empcraft.com/fawe with https://schem.intellectualsites.com/fawe/
3. Run /fawe reload

Please join our Discord for additional assistance.
