### ISSUE TITLE
Can't undo the //line command

### ISSUE THREAD

**Issue by bf-dev** [IntellectualSites/FastAsyncWorldEdit#508]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
 https://athion.net/ISPaster/paste/view/f14c08a46875488ebd7cb04f0595490c

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

FastAsyncWorldEdit-260 created by Empire92
 FAWE version:
 - Date 2020. 6. 13 12:00:00
 - Commit fcc3c34e
 - Build 260
 - Platform Bukkit
------------------ Platforms ------------------
* Bukkit-Official(1.15-260;33c3cb2)

---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Paper version git-Paper-348 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**[REQUIRED] Description of the problem:**

We can't undo the //line command
**How to replicate**:

**Plugins being used on the server:**
[월, 15. 6월 2020 03:23:16 EDT INFO] Plugins (21): BKCommonLib, BlocksHub, CoreProtect, DiscordSRV, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, FastAsyncWorldEdit, HolographicDisplays, ImageOnMap, LightCleaner, LuckPerms, Multiverse-Core, Vault, VoxelSniper, WorldEdit

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by janLindner** [comment]
Can confirm this issue. This also applies to the //curve command.

**Comment by StealWonders** [comment]
Can confirm, have the same issue on my server. I can only undo //line sometimes (not always). It's very weird.

**Comment by NomadMC** [comment]
Can confirm, same issue. Undo only works occasionally with //lines and it usually undoes the wrong line.

**Comment by MattBDev** [comment]
@dordsor21 which commit fixed this bug? It would be useful to know for future reference.
