### ISSUE TITLE
Using multiple masks within the same command doesn't work. 

### ISSUE THREAD

**Issue by DecoratedMC** [IntellectualSites/FastAsyncWorldEdit#509]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/10377e8dfc2f4c0c833243f614ff2e03

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
* Bukkit-Official(1.15-260;33c3cb2) 

**[REQUIRED] Spigot/Paper Version Number:** 
The server is running Paper version git-Paper-350 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) 
Checking version, please wait…
Previous version: git-Paper-277 (MC 1.15.2)
You are running the latest version

**[REQUIRED] Description of the problem:**
using multiple masks within the same command doesn’t work. When trying to use use a mask such as 0&[>2] which masks air and above grass, it returns an invalid input message: 

(FAWE) Invalid value for [maskOpt] (No match for '0&[>2]) acceptable values are any mask. 

Making you unable to use different masks within the same command and only way to bypass this is  ( using 2 masks maximum) is to use a normal brush mask for the 1st mask and a gmask for the 2nd.
Using comma's instead of brackets does not change the outcome/result. 

**How to replicate**:
/br sphere 35:14 2 
/mask 0&[>2]
(or other combinations such as:)
/mask 0&[~98]

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by TheoRetisch1** [comment]
I'm facing the same problem using _build 315_ with Paper _1.16.1-138_.

**Comment by SirYwell** [comment]
The old syntax of FAWE isn't implemented right now, but WE allows using multiple masks too, e.g. `//mask "#air >grass_block"` will mask all air blocks above grass blocks. See [WE's mask documentation](https://worldedit.enginehub.org/en/latest/usage/general/masks/#combining-masks) for more information.
As this isn't as powerful as the syntax used by FAWE before, we're looking forward to reimplement it too.
