### ISSUE TITLE
//rotate not properly working for angles <90

### ISSUE THREAD

**Issue by pascal541** [IntellectualSites/FastAsyncWorldEdit#512]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/6963f8dfa26044b887d0b1b06aec4be5

**[REQUIRED] FastAsyncWorldEdit Version Number:**
```
[21:40:38 INFO]: FastAsyncWorldEditunknown created by Empire92
[21:40:38 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[21:40:38 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-260;33c3cb2)

[21:40:38 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 
```
[21:41:23 INFO]: This server is running Paper version git-Paper-353 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[21:41:23 INFO]: Previous version: git-Paper-350 (MC: 1.15.2)
[21:41:23 INFO]: You are running the latest version
```

**[REQUIRED] Description of the problem:**
//rotate is not properly working for angles that are not a multiplication of 90
![image](https://user-images.githubusercontent.com/7486865/84942951-f1433600-b0e3-11ea-87f7-d0f6d38de721.png)
Middle: selection
Left: WorldEdit
Right: FastAsyncWorldEdit
(Both rotated 45 degrees)

**How to replicate**:
1. Make a selection
2. Use //rotate 45 (or any number below 90)
3. Use //paste

**Plugins being used on the server:**
```
Plugins (3): CubedUtilities, FastAsyncWorldEdit, WorldEdit
```

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.
