### ISSUE TITLE
Edit message...

### ISSUE THREAD

**Issue by Lennord** [IntellectualSites/FastAsyncWorldEdit#513]
Hello, I have downloaded the last builds of version 1.15 of your plugin, I am under Spigot-1.15.2 but the plugin works well but how we do to modify the messages of the plugin.
Otherwise there is no error...

**Comment by N0tMyFaultOG** [comment]
`/FastAsyncWorldEdit/lang/strings.json` if that file exists, elsewise you don't rn.

**Comment by Lennord** [comment]
> `/FastAsyncWorldEdit/lang/strings.json` if that file exists, elsewise you don't rn.

I have no "lang" folder, I only have config and config-legacy then 1 "schematics" and "sessions" folder.

**Comment by N0tMyFaultOG** [comment]
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/500
