### ISSUE TITLE
FAWE-WorldGuard entry problem

### ISSUE THREAD

**Issue by DMan1629** [IntellectualSites/FastAsyncWorldEdit#516]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/744df028260b42b5817fe71b5ec1b7ad

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
------------------ Platforms ------------------
* Bukkit-Official(1.15-263;3d40336)
>.... [13:56:14 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-365 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
When trying to enter a region with limited members-only entry (provided by WorldGuard), I get blocked even though I have the proper permissions.
This may seem a problem with WorldGuard, **BUT** the problem does **not** consist when switching to regular WorldEdit.

**How to replicate**:
Create a region with WorldGuard, set entry to members only, add a group as a member, make sure you are in that group (or have the permission), try to enter - you can't.

**Plugins being used on the server:**
Unnecessary - problem does **not** consist when switching back to regular WorldEdit.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Punkred** [comment]
Can confirm having same issue after switching over to FAWE. Having proper permission in LP as well as WG properly set up for only those members allowed.

FastAsyncVoxelSniper-flattened-1.0.3-backward.jar
FastAsyncWorldEdit-1.15-263.jar
worldguard-bukkit-7.0.2.jar
WorldGuardExtraFlags.jar (Not sure if important but included)

**Comment by MattBDev** [comment]
This is odd considering we don't block movement based on WorldGuard permissions.

**Comment by DMan1629** [comment]
That's exactly what I thought, but that's how it is

**Comment by Haczyn** [comment]
> This is odd considering we don't block movement based on WorldGuard permissions.

It doesnt block movement. It break restriction on entry for specifited group add added to region from worldguard. After remove FAWE  itsnt back to normal, but when we add again(with fawe doesnt work) group of players to region it work.

**Comment by TheRealAws** [comment]
Same issue on 
Paper 1.16 Build-130
FAWE: FastAsyncWorldEdit-1.16-311
WorldGuard: worldguard-bukkit-7.0.4-SNAPSHOT-dist

I have tested this with using WorldEdit: worldedit-bukkit-7.2.0-beta-02 And the issue disappears when using original latest WorldEdit, however appears again when using FAWE.

**Comment by InfinityAspire** [comment]
WorldEdit devs have confirmed that FAWE breaks WorldGuard in numerous ways.
Including adding groups [and possibly players] as members of the global region. It blocks everyone from doing everything, regardless if they're added to the region via their group or not.
Acts properly on normal WorldEdit.

**Comment by aurorasmiles** [comment]
This has priority.
Apparently FAWE breaks something with WEPIF causing those issues with WorldGuard.

**Comment by IronApollo** [comment]
Would the OP or another user mind re-resting this on the latest release found [here](http://ci.athion.net/job/FastAsyncWorldEdit-1.16/354/artifact/worldedit-bukkit/build/libs/FastAsyncWorldEdit-1.16-354.jar)? I can not replicate it.

If the issue persists, please recreate a step-by-step way to replicate the issue starting with region creation and group creation.

**Comment by DMan1629** [comment]
Hey, I just tested it again and the bug is **still on**.
I tested it further and found out the problem occured **only** with groups. If you add a specific player to the region's members list he can get in, but adding a group does **not** let them enter.
And yes - this problem **does not** persist with regular World Edit.

**Comment by aurorasmiles** [comment]
Could you provide more information what you did exactly and what versions you used? Because we both couldnt replicate the issue

**Comment by DMan1629** [comment]
Server jar: **_git-Paper-189_** (Final 1.16.2 version)
FAWE version: **_FastAsyncWorldEdit-1.16-354_**

- Make a region the usual way: select an area with the wand (wooden axe), do: `/rg create test` (region named test or **anything** else).

- Do `/rg list`, select the region _test_, click on `flags`, go to page 4 and for the option _entry_ click `deny` (to deny access to anyone who isn't Op or a member of the region).

- Add the group _default_ (or **any** other group that has been set up using LuckPerms) to the member list of _test_ (the region): `/rg addmember test g:default`.

- Remove my Op status with `/deop DMan16` (yes, _DMan16_ is my ingame name - no, it's **not** a mistake). Try to enter the region _test_ - **can not** enter.

- While remaining **not** Op, use the command `/rg addmember test DMan16` **through the server's console** to add myself to the _test_'s members without using groups. Try to enter - **can** enter.

- Try the same with regular WorldEdit: works as it should - adding the _default_ group is enough to grant me access.

If something is still not clear, I'll be glad to make a video demonstrating every step - just let me know.

Hope this helps, thx for trying to fix this!!!

**Comment by IronApollo** [comment]
I hate to do this, but would you mind making the video? lol. I've tried this again and still am unable to replicate your issue. [Here is a short gyazo of my result.](https://gyazo.com/a866b1582a9b93e60caf2fe6d749ea47)

**Comment by InfinityAspire** [comment]
> I hate to do this, but would you mind making the video? lol. I've tried this again and still am unable to replicate your issue. [Here is a short gyazo of my result.](https://gyazo.com/a866b1582a9b93e60caf2fe6d749ea47)

I can't speak for others but all of my issues exist with the __global__ region, not player-made ones

**Comment by IronApollo** [comment]
@InfinityAspire Same method of replication but just with global, correct?

**Comment by InfinityAspire** [comment]
> @InfinityAspire Same method of replication but just with global, correct?

Pretty much
Player made regions act as they should for me

**Comment by MrAnonymous0** [comment]
@IronApollo @InfinityAspire That is quite weird. If i add groups to player made regions they cant build at all. Worldguard only acts as its supposed to if i add people individually to the regions.

**Comment by IronApollo** [comment]
I am still, even with the global region, unable to reproduce this. I must be doing something wrong; maybe the video will assist me in better testing this on my end.

In the meantime, [here is my setup](https://athion.net/ISPaster/paste/view/ca97e8658df8479185cd03fb2a57d6ac).

**Comment by MrAnonymous0** [comment]
@IronApollo Maybe vault? could be

**Comment by IronApollo** [comment]
You hit the nail on the head; I can easily replicate the issue now.

**Comment by DMan1629** [comment]
I tried this on a brand new server with nothing but LuckPerms, WorldGuard, and FAWE and it happens.
BTW, @IronApollo, I saw that you have both FAWE **and** WorldEdit - that's why you can't replicate the issue.
**With** WorldEdit this issue **doesn't occur**. It happens **only** with FAWE.
So if you remove WorldEdit (which you shouldn't have anyway - it says so on FAWE's page before installation) you'll be able to replicate it.

**Comment by aurorasmiles** [comment]
FAWE fakes WorldEdit as installed, it is just FAWE that is there.

**Comment by DMan1629** [comment]
FAWE fakes WorldEdit? Doesn't happen to me.
Just remove WorldEdit and try again - the issue will occur.

**Comment by aurorasmiles** [comment]
If you install FAWE and check /plugins you will see both FAWE and WorldEdit. That is intended behavior

**Comment by DMan1629** [comment]
So... has this been fixed?

**Comment by aurorasmiles** [comment]
Yes
