### ISSUE TITLE
Color codes do not apply to numbers in strings.json

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#519]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
config.yml: https://pastebin.com/qbx642wn
config-legacy.yml: https://pastebin.com/E4qmuBMb

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.15-256

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-301 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
In the FastAsyncWorldEdit/lang/strings.json file it allows you to customize the command feedback messages but there is no way to change the color for numbers. Example `"prefix": "&7[FastAsyncWorldEdit&7]&a {0}",` The color codes only apply to words but doesn't change anything that uses `{0}` it will use pink which is &d by default and there is no way to change that currently. This was not an issue in 1.13 when the plugin used the message.yml file and color codes would apply to numbers too.

**How to replicate**:
Edit any message in strings.json and add a color code to the message.

**Plugins being used on the server:**
FastAsyncWorldEdit, LuckPerms, PlotSquared

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Probably because the strings.json file wasn't built to handle color codes @N0tMyFaultOG

**Comment by N0tMyFaultOG** [comment]
If upstream does not provide the ability to change colors codes, you need to use the defaults for now.
