### ISSUE TITLE
Server crash 2 time 2 day round same error

### ISSUE THREAD

**Issue by Noiknez** [IntellectualSites/FastAsyncWorldEdit#521]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/bedce6b2b6704da383555c832cec998b

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**

The server was running normally then everything stopped, this was happening also the day before with the same error. The first crash report appear at 17:07:39 and the second one at 11:15:03. The FAWE version was updated in between (3 version) to see if it was this.
Two player used voxelsniper and gobrush thoses 2 day before the crash happened

**Full log (not the same on /fawe debugpaste)**

Crash 1 from 27/06/2020 : https://pastebin.com/dv3w5C4u
Crash 2 from 28/06/2020 : https://pastebin.com/eFPbmwVF

**How to replicate**:

Running the server, doing command and see what happen minutes after.

**Plugins being used on the server:**

Plugins (38): ArmorStandEditor, BKCommonLib, BuildersUtilities, BungeeTabListPlus, CraftingStore, Denizen, Depenizen, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, HeadDisplays, HolographicDisplays, IPWhitelist*, LightCleaner, LuckPerms, Multiverse-Core, Plan, PlayerMarkers*, PlotSquared, Prism, spark, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, VoxelSniper, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Noiknez** [comment]
Today it was the same, there was 2 player :
- One that used Voxelsniper (the fawe one)
- One that used GoBrush and dig with 3D mode

Full log : https://pastebin.com/HrHeDFeg

**Comment by dordsor21** [comment]
This is an issue with goBrush. I've mentioned it to arc
