### ISSUE TITLE
Conflict between Craftbook and FAWE in paper 1.16.1

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/FastAsyncWorldEdit#524]
# Bug report for FastAsyncWorldEdit 1.15.2

 

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

![2020-07-01_12 32 58](https://user-images.githubusercontent.com/22108822/86269023-21d0a880-bb97-11ea-86a4-46e0049a184f.png)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

FastAsyncWorldEdit-1.16-273
**[REQUIRED] Spigot/Paper Version Number:** 

Paper 1.16.1 build 34
**[REQUIRED] Description of the problem:**

https://github.com/EngineHub/CraftBook/issues/1211
**How to replicate**:

**Plugins being used on the server:**

[2020-07-01-3.log.gz](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/4859162/2020-07-01-3.log.gz)

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [] I made sure the bug/error is not caused by any other plugin

This has been a long standing bug between Craftbook and FAWE though many mincraft versions and exists in 1.16.1 . I think it has to do with palayer IDs

**Comment by MattBDev** [comment]
Invalid report for more than one reason:

1.  Outdated FAWE that wasn't even compatible with 1.16.1
2.  Didn't follow the bug report template.
3.  Don't make me download your log to figure out you were running an outdated build.

**Comment by Tsoccerguy3** [comment]
FAWE version as indicated above , FastAsyncWorldEdit-1.16-273 , says its the latest build
Paper 1.16.1 build 34 is the most current

There is a conflict between Craftbook and Fawe and has existed since 1.13 .  Matt from World Edit project already traced the conflict to the way FAWE handles player IDs It breaks the WE API and effect even Worldguard

I have no Idea why you closed this and fix the template , plus debug is broken

**Comment by aurorasmiles** [comment]
As Matt already said, please don't ignore the template, use a wasteBin to upload your log and describe the issue a bit more. You can open a new issue if you wan't, but this is invalid

**Comment by MattBDev** [comment]
Your log indicates that you are using build 268 of FAWE. You are correct that the current build is 273. If you want this issue reopened you need to provide me your FAWE config files and an updated log that shows you are running version 273.

**Comment by Tsoccerguy3** [comment]
Before i open this under a new issue , I updated and scrubed logs to make sure i got the latest for the server
[latest log 2020-07-01.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/4861271/latest.log.2020-07-01.zip)

FAWE version : FastAsyncWorldEdit-1.16-274
server version : Paper 1.16.1 build 34
Craftbook build 4619

Matt (me4502) was kind enough to trace the error to FAWE breaking the WE api specific to how FAWE calls player ID's . https://github.com/EngineHub/CraftBook/issues/1211

ignoring it , it will never go away  if you need help just ask me4502 why FAWE breaks Craftbook

**Comment by Tsoccerguy3** [comment]
Quote from Matt (me4502)

" me4502 commented 1 hour ago
If FAWE breaks CraftBook, it’s a FAWE issue and there’s nothing that can be done about it from my end.
CraftBook uses the WorldEdit API. If they break the WorldEdit API and tell other plugins that they are WorldEdit, their plugin is broken."

**Comment by MattBDev** [comment]
@Tsoccerguy3 I can ignore it because you refuse to cooperate with us and provide us the details we need to fix the issue. I am not sure why you keep bringing up "player ID's" because it has nothing to do with FAWE and this issue you are encountering.
