### ISSUE TITLE
Error when using clipboard on disk

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#525]
This happened to me while testing. Usually only after the server was running for a while, and only when clipboard on disk is enabled.
https://waste.cutiepie.at/0roddf58e67pq2q

**Comment by CCCoderDE** [comment]
Same problem for me.

- FAWE version: Bukkit-Official(1.16-291;704e76e)
- Spigot version: 1.16.1-R0.1-SNAPSHOT

**Comment by MattBDev** [comment]
@aurorasmiles can you share the English translation for that error please?

**Comment by aurorasmiles** [comment]
@MattBDev "The requested operation cannot be performed on a file with a user-mapped section opened"
Sorry, didn't notice it was localized.

**Comment by Darwin1546** [comment]
Can confirm that. So annoying, happens when you leave and reconnect to the server

**Comment by MattBDev** [comment]
Known bug. There is a fix for it but I am not ready to make it public yet.

**Comment by dordsor21** [comment]
I think this is fixed by clipboards actually being closed on player logout (many time ago)
