### ISSUE TITLE
FAWE crashing with latest WorldEdit

### ISSUE THREAD

**Issue by Karl-Heinz-Ott** [IntellectualSites/FastAsyncWorldEdit#526]
My son Jan-Lucas told from Minecraft told me FAWE is crashing because of WorldEdit (@wizjany <- this plugin)
Help please.

**Comment by MattBDev** [comment]
I can't help if you don't provide any details whatsoever. Also, you are not supposed to use FAWE and WorldEdit together.

**Comment by aikar** [comment]
@MattBDev this is a troll account / post
