### ISSUE TITLE
Message.yml for all language

### ISSUE THREAD

**Issue by Lennord** [IntellectualSites/FastAsyncWorldEdit#527]
Hello, I use your plugin in Spigot version 1.15.2 but in the "config.yml" there is no longer the "Language:" configuration and when I go to the "Lang" folder, I have no all languages, I have that "Strings". Because I would like to put myself in French language because I would like to use this plugin on my Minecraft server...

Link: https://pastebin.com/4Em9HpD3

**Comment by MattBDev** [comment]
Please use our crowdin for translations. We now use strings.json

**Comment by N0tMyFaultOG** [comment]
Crowdin: https://intellectualsites.crowdin.com/fastasyncworldedit
