### ISSUE TITLE
~[block] Mask Not Working. 1.14.4

### ISSUE THREAD

**Issue by Iothes** [IntellectualSites/FastAsyncWorldEdit#528]
# Bug report for FastAsyncWorldEdit 1.14.4

FAWE Version: Ask which version Aequotis has for his Cubed C. server (I witness those issues there).
For Paper version and such also do the above :')

 Ok so, the problem is that I want to mask the surroundings of a certain block with ~[block]
This existed in FAWE 1.12.2, they said it was FAWE's feature and not any other plugins'.
But FAWE does not seem to recognize this mask. Whenever I apply it to //replace or //gmask it will just put out usage help thing.

 To reproduce: Simply use that version... or come in the server I suppose (no advertising), then select a region and type for example: //gmask ~1 or select an area with some stone and air, then do //gmask 0 and lastly: //replace ~1 7 : if blocks of air that touch stone are replaced, but not the stone itself, then it works, otherwise not which is most likely.

 For plugins... not really sure please ask mr. Aequotis again.
This is my first github post. If it is messy or too big please say.

**Comment by MattBDev** [comment]
If you are not the owner of the server please do not report bugs.

**Comment by Iothes** [comment]
Sorry about that! I shall tell Aequotis then... *and I hope he hears me xD* Should the post be closed?

**Comment by MattBDev** [comment]
If you can get them to provide the sever details on here I will reopen this issue. I will be closing it for now.
