### ISSUE TITLE
TogglePermission (I.e. /wea & /tips) Non-Functional

### ISSUE THREAD

**Issue by CS-Birb** [IntellectualSites/FastAsyncWorldEdit#529]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/a8644755030b423eb10c9dea7d919f6a
(Small Test Server w/ Minimal Plugins)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
 Bukkit-Official(1.16-293;6d6de61)

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-353 (MC: 1.15.2)

**[REQUIRED] Description of the problem:**
`togglePermission` (as in /wea and /tips) seems to be broken, currently (Currently tested on `Bukkit-Official(1.16-293;6d6de61)`). 
Instead of toggling and returning the new state (as in the `Subject` interface), it's just returning the current state of the perm.
```java
@Override public boolean togglePermission(String permission) {
    return permActor.hasPermission(permission);
}
```
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlayerProxy.java#L178-L180

**How to replicate**:

Running `/wea` with `fawe.admin` will constantly report that your changes are now restricted.
With `fawe.bypass` It'll report that you're now bypassing. No perm changes are performed.

**Plugins being used on the server:**
- FAWE
- LuckPerms
- Vault

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Xaver106** [comment]
I have the same issue. Get the same result on plotsquared as well as Worldguard. `fawe.bypass` and turning restrictions in the config off works, but not `/wea`.

**Comment by IronApollo** [comment]
@aurorasmiles What is the additional complexity you mentioned regarding this ticket?

**Comment by aurorasmiles** [comment]
I explained it a few days ago on discord. Basically, with #561 the core issue is fixed, because Vault is setup correctly, but there is another issue which requires you to toggle everything twice for it to work
