### ISSUE TITLE
1.16  /br height not work

### ISSUE THREAD

**Issue by meerpaluten** [IntellectualSites/FastAsyncWorldEdit#532]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/90f707ea15914cbe8e1f6a450059bd58

**[REQUIRED] FastAsyncWorldEdit Version Number:** [22:28:11 INFO]: FastAsyncWorldEdit-297 created by Empire92
[22:28:11 INFO]: FAWE version:
 - Date Jul 11, 2020, 12:00:00 AM
 - Commit f14612f7
 - Build 297
 - Platform Bukkit
[22:28:11 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[22:28:11 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-297;eb9ed09)

[22:28:11 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 

[22:28:31 INFO]: This server is running Paper version git-Paper-89 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[22:28:31 INFO]: Checking version, please wait...
[22:28:31 INFO]: Previous version: git-Paper-88 (MC: 1.16.1)
[22:28:31 INFO]: You are running the latest version

**[REQUIRED] Description of the problem:**

The desired tarrer is not created but a sphere. The command works in the 1.12.2 

**How to replicate**:

run  /br height 300 https://i.imgur.com/HK9TIyn.png 0 0.3 -r and use that brush, then come a sphere but not the terrer 

**Plugins being used on the server:**

Plugins (26): ArmorStandTools, BackupSystem-Piraty, BankSystem, BannerMaker, BuildSystem, Citizens, CustomHeads*, Denizen, EconomyPlus, FastAsyncWorldEdit, FurnitureLib, JobSystem, LuckPerms, Marketplace, Matrix, PiratySystem-Core, PlotSquared, PlugMan, PremiumVanish, ProtocolLib, ReportSystem, spark, TimoCloud, ViaVersion, VoxelSniper, WorldEdit

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
I cannot reproduce your problem with paper 89 and FAWE 297
