### ISSUE TITLE
Lighting is incorrect in 1.16.1 until rejoining (packet issue)

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#535]
# Bug report for FastAsyncWorldEdit 1.16.1

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
config.yml: https://pastebin.com/qbx642wn
config-legacy.yml: https://pastebin.com/E4qmuBMb

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.16-300

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-90 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Doing a set operation shows the incorrect lighting but rejoining will fix the issue, I suspect the issue is related to packets and 1.16.1.

**How to replicate**:
Do a set operation in the air:
![image](https://user-images.githubusercontent.com/10485646/87494169-3eb0b580-c646-11ea-9f95-b22c6dc30ee2.png)

Skylight is incorrect:
![image](https://user-images.githubusercontent.com/10485646/87494190-4ec89500-c646-11ea-9869-390136712114.png)

Rejoining fixes the issue:
![image](https://user-images.githubusercontent.com/10485646/87494225-6011a180-c646-11ea-805c-bb44abe25666.png)

**Plugins being used on the server:**
FastAsyncWorldEdit, LuckPerms, PlotSquared, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Looks like we need to manually send a lighting update to the user.

**Comment by SecretlyJealous** [comment]
Still seems to be an issue using Build #306

![image](https://user-images.githubusercontent.com/10485646/88431791-f25a3800-cdf2-11ea-9cf0-8b39f476df39.png)
