### ISSUE TITLE
//regen unable to function whatsoever

### ISSUE THREAD

**Issue by ultraic-space** [IntellectualSites/FastAsyncWorldEdit#541]
# Bug report for FastAsyncWorldEdit 1.16.1

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/1c26af2722b3482fb706cee04b59ca82

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
[Sun, 19. Jul 2020 16:39:38 UTC INFO] FastAsyncWorldEdit-302 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[Sun, 19. Jul 2020 16:39:38 UTC INFO] FAWE version:
 - Date Jul 15, 2020 12:00:00 AM
 - Commit f668ba48
 - Build 302
 - Platform Bukkit
Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
------------------ Platforms ------------------
* Bukkit-Official(1.16-302;99745b8)

---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-91 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
//regen doesn't work, simply states: "Unable to regenerate chunks. Check console for details." console does not print details.

**How to replicate**:
Select any region and do //regen

**Plugins being used on the server:**
AdvancedBan, AltFinder, BKCommonLib, BetterSleeping3, BuycraftX, ChatInjector, ChatSentinel, Chunkmaster, CleanMotD, ClearLag, CmdSigns, ColoredSigns, CommandSigns, ConditionalCommands, CoreProtect, DiscordSRV, DiscordSRV-Staff-Chat, EasyClearChat, EntityTrackerFixer, EpicGuard, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, F3NPerm, FarmLimiter, FastAsyncWorldEdit, GriefPrevention, HeadDatabase, ImageOnMap, InventoryRollback, JukeLooper, KeepDeathDrop, LeashTeleport, LightCleaner, LoginSecurity, LuckPerms, MineableSpawners, Multiverse-Core, OpenInv, PlaceholderAPI, ProtocolLib, SAML, ServerUtils, Shopkeepers, SkinsRestorer, TrollBoss, UltimateChairs, Vault, ViaBackwards, ViaRewind, ViaVersion, VillagerOptimiser, Votifier, VotingPlugin, Wild, WitherSound, WolfyUtilities, WorldEdit, WorldGuard and dynmap

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

I'll check if it works on a fresh copy of paper. EDIT: Still doesn't both latest paper and FAWE.

**Comment by SuperPyroManiac** [comment]
I'd like to mention I have the same exact issue. No log in the console.

**Comment by RedstoneFuture** [comment]
I can replicate this on version `1.16-306 for PaperSpigot 1.15.2-308`.

https://pastebin.com/NAn7Ev0N

**Comment by Doc94** [comment]
Still the issue in `FastAsyncWorldEdit version 1.16.2 build 324` in `git-Paper-141 (MC: 1.16.2)`

**Comment by dalandis** [comment]
Relevant for the latest versions

[14:05:38 INFO]: This server is running Paper version git-Paper-185 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

[14:06:00 INFO]: FastAsyncWorldEdit-343 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[14:06:00 INFO]: FAWE version:
 - Date Sep 6, 2020 12:00:00 AM
 - Commit f11b69d9
 - Build 343

**Comment by N0tMyFaultOG** [comment]
This will be fixed with https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/598

**Comment by Tnology** [comment]
same issue, but he said in build 598 it will be fixed so that's cool
