### ISSUE TITLE
/fixlighting - Doesn't effect snow very well.

### ISSUE THREAD

**Issue by Ash10744** [IntellectualSites/FastAsyncWorldEdit#547]
# Bug report for FastAsyncWorldEdit 1.16.1

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/a41bf293a0fb4224b73f8fcc2a03e748

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
26.07 14:23:15 [Server] Startup [12:23:15 INFO]: FastAsyncWorldEdit-306 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
26.07 14:23:15 [Server] Startup [12:23:15 INFO]: FAWE version:
26.07 14:23:15 [Server] INFO - Date Jul 24, 2020 12:00:00 AM
26.07 14:23:15 [Server] INFO - Commit f8dd9620
26.07 14:23:15 [Server] INFO - Build 306
26.07 14:23:15 [Server] INFO - Platform Bukkit
26.07 14:23:15 [Server] Startup [12:23:15 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
26.07 14:23:15 [Server] Startup [12:23:15 INFO]: ------------------ Platforms ------------------
26.07 14:23:15 [Server] INFO * Bukkit-Official(1.16-306;72269e0)
26.07 14:23:15 [Server] Startup [12:23:15 INFO]: ---------------- Capabilities ----------------
26.07 14:23:15 [Server] INFO GAME_HOOKS: Bukkit-Official
26.07 14:23:15 [Server] INFO CONFIGURATION: Bukkit-Official
26.07 14:23:15 [Server] INFO USER_COMMANDS: Bukkit-Official
26.07 14:23:15 [Server] INFO PERMISSIONS: Bukkit-Official
26.07 14:23:15 [Server] INFO WORLDEDIT_CUI: Bukkit-Official
26.07 14:23:15 [Server] INFO WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
[Click Here](https://i.imgur.com/NtEsDLz.png)

**[REQUIRED] Description of the problem:**
Upon doing /fixlighting it has a different effect on snow.

The lighting doesn't fix correctly with the snow.

[Click Here for Image.](https://i.imgur.com/D4qHDBj.png)

**How to replicate**:
//Fixlighting in an area with snow.

**Plugins being used on the server:**
https://i.imgur.com/zKdWO8r.png

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update Fawe and possibly provide some screenshots

**Comment by Ash10744** [comment]
Sorry provided some screenshots after I made the thread.

**Comment by Ash10744** [comment]
And the latest version still does the same.

**Comment by N0tMyFaultOG** [comment]
> And the latest version still does the same.

Why would you downgrade to an older version then while reporting an issue?

**Comment by Ash10744** [comment]
No I updated to the latest and the same error occurred. I was testing it whilst making the thread want me to update it?

**Comment by N0tMyFaultOG** [comment]
> No I updated to the latest and the same error occurred. I was testing it whilst making the thread want me to update it?

Obviously 🤦

**Comment by Ash10744** [comment]
Updated.

**Comment by dordsor21** [comment]
This is fixed in recent builds
