### ISSUE TITLE
CreratFromImage doesn't work with 1.15.2

### ISSUE THREAD

**Issue by Xem46** [IntellectualSites/FastAsyncWorldEdit#549]
Hello, just having a problem with 1.15.2, dunno if the problem comes from plotsquared or FAWE, but the //cfi just doesn't work. It as if it doesn't exist at all (like when you don't have plotsquared at all, I get the same message).

GOt the last plotsquared version, tested on 1.15 and the plug-in work properly. GOt only a cfi issue, other commande work fine on both plug-in.

Thanks.

**Comment by aurorasmiles** [comment]
Don't delete the template.

**Comment by Xem46** [comment]
I didn't delete anything, bug whatever

 

 

 

 

> Message du 26/07/20 19:05
> De : "aurorasmiles" 
> A : "IntellectualSites/FastAsyncWorldEdit" 
> Copie à : "Xem46" , "Author" 
> Objet : Re: [IntellectualSites/FastAsyncWorldEdit] CreratFromImage doesn't work with 1.15.2 (#549)
> 
>
>

> Don't delete the template.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/549#issuecomment-664014358", "url": "https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/549#issuecomment-664014358", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
