### ISSUE TITLE
flag "-f" don't work at "//ceil" and "//up"

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/FastAsyncWorldEdit#550]
# Bug report for FastAsyncWorldEdit 1.16.1

The [//up](https://wiki.intellectualsites.com/en/FastAsyncWorldEdit/Commands-new/Navigation#up) and [//ceil](https://wiki.intellectualsites.com/en/FastAsyncWorldEdit/Commands-new/Navigation#ceil) command will teleport you up. But currently, the valid flags are broken or unuseful:

[-f] -> "Force using flight to keep you still."
At my test he always created a glass block. According to the flag description I  should receive fly-mode.

Furthermore, the "-g" flag is irrelevant, because the glass_block will be placed by default.

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/c7eabd5d8d064eed981775fef7998065

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
> fawe 1.16 - 306

**[REQUIRED] Spigot/Paper Version Number:** 
> PaperMC 1.15.2

**How to replicate**:
`//up 10 -f`

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by lusu007** [comment]
I've the same problem on our building server using FAWE 366.
I've searched for config value ``navigation.use-glass`` and cant find it in both config files.
