### ISSUE TITLE
Createfromimage not working.

### ISSUE THREAD

**Issue by Xem46** [IntellectualSites/FastAsyncWorldEdit#551]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/13993e9db5e54089abba39c668c31741

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
Bukkit-Official(1.16-304;28837c7)

**[REQUIRED] Spigot/Paper Version Number:** 

Paper version git-Paper-376 (MC: 1.15.2)
API Version1.15.2-R01-SNAPSHOT

**[REQUIRED] Description of the problem:**
When using the /cfi in the server it say "Unknown command. Type"/help" for help. Just like when plotsquared isn't installed, There is no error exept for this one.
Plotsquared is up to date. FAWE Too.
Didn't touch any config on plotsquared.

**How to replicate**:

Just write down the commande with the same config for FAWE and vanilla one for plotsquared.

**Plugins being used on the server:**
FAWE, Essentials, Plotsquared, Multiverse-core, Vault, EssentialsGeoIP, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, EssentialsProtect, AmorStandEditor, HeadDataBase, goBrush, goPaint.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Right. `/cfi` or `///cfi` aren't a valid command.

**Comment by MattBDev** [comment]
It needs to be rewritten. I'm going to close this issue and I will create a new one to track.

**Comment by MattBDev** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/552
