### ISSUE TITLE
Upload sources to maven

### ISSUE THREAD

**Issue by Earthcomputer** [IntellectualSites/FastAsyncWorldEdit#555]
Hi, I checked [your maven](https://mvn.intellectualsites.com/content/repositories/releases/com/intellectualsites/fawe/FAWE-Bukkit/) but it doesn't include the source code. It would be helpful if the source was pushed to the maven when using FAWE as a library, so that the IDE can download and attach the sources.

**Comment by N0tMyFaultOG** [comment]
If you add Fawe to your build file, the IDE downloads the provided information from our nexus automatically and provides it in your m2 folder.

**Comment by Earthcomputer** [comment]
@N0tMyFaultOG no it doesn't
![Screenshot from 2020-07-29 12-46-05](https://user-images.githubusercontent.com/13084089/88796426-83396680-d199-11ea-8faa-d6a40ec6866c.png)

**Comment by N0tMyFaultOG** [comment]
That is correct. The files are read because they do not exist and the JavaDocs are hosted on our CI regardless, the nexus provides the api solely.

**Comment by Earthcomputer** [comment]
Where can I get a sources jar from then? It's very useful for navigating the code in intellij.

**Comment by N0tMyFaultOG** [comment]
Build it yourself by building fawe.

**Comment by Earthcomputer** [comment]
Of course I know that, but the issue was why not push the sources to your maven so everyone can benefit? That's the usual practice.

**Comment by N0tMyFaultOG** [comment]
I can't access the nexus so I can't manage the artifacts, for now you need to deal with what is provided.

**Comment by Earthcomputer** [comment]
Ok fair enough, but can you reopen the issue so that whoever does have access can sort it out?

**Comment by Earthcomputer** [comment]
For anyone reading this in the future: I rehosted maven artifacts with sources: https://bintray.com/earthcomputer/mods/fawe

**Comment by N0tMyFaultOG** [comment]
After nagging the person for the 500th time, I just updated the artifacts to the latest builds.
Makes sure to checkout https://wiki.intellectualsites.com/en/FastAsyncWorldEdit/API for the latest changes.
Cheers

**Comment by Earthcomputer** [comment]
Oh, tysm!

**Comment by Earthcomputer** [comment]
`FAWE-Bukkit` is a fat jar, but the corresponding sources are only from the `worldedit-bukkit` project in the repo. This is easy to work around by including `FAWE-Core` in the `pom.xml` as well, like so:
```xml
		<dependency>
			<groupId>com.intellectualsites.fawe</groupId>
			<artifactId>FAWE-Core</artifactId>
			<version>1.16-306</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.intellectualsites.fawe</groupId>
			<artifactId>FAWE-Bukkit</artifactId>
			<version>1.16-306</version>
			<scope>provided</scope>
		</dependency>
```
