### ISSUE TITLE
schematic issuse

### ISSUE THREAD

**Issue by Skygamer777McMegaCity** [IntellectualSites/FastAsyncWorldEdit#556]
1.16.1

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/2ce43b7169b8442dab230324b9712a62

**[REQUIRED] FastAsyncWorldEdit Version lo, dordsor21 and NotMyFault
[11:44:23 INFO]: FAWE version:
 - Date 24.07.2020 00:00:00
 - Commit f8dd9620
 - Build 306
 - Platform Bukkit
[11:44:23 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[11:44:23 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-306;72269e0)

[11:44:23 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version 

[11:46:37 INFO]: This server is running Paper version git-Paper-127 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[11:46:37 INFO]: Previous version: git-Paper-116 (MC: 1.16.1)
[11:46:37 INFO]: You are running the latest version

**[REQUIRED] Description of the problem:**
Cant paste a schematic

**How to replicate**:
load the schematic and paste it

**Plugins being used on the server:**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by chickenputty** [comment]
![image](https://user-images.githubusercontent.com/1813460/89094612-5351b500-d38b-11ea-8bdd-d020405bd0bf.png)
I can't schematic paste either. Tried with file and url.
