### ISSUE TITLE
adding a group to a global region doesn't work

### ISSUE THREAD

**Issue by Mixter213** [IntellectualSites/FastAsyncWorldEdit#558]
# Bug report for FastAsyncWorldEdit 1.16.1

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/606084474ba1434ca25b71429c05f595

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

[14:24:14 INFO]: FastAsyncWorldEdit-309 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[14:24:14 INFO]: FAWE version:
 - Date Aug 1, 2020, 12:00:00 AM
 - Commit fc4808dd
 - Build 309
 - Platform Bukkit
[14:24:14 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[14:24:14 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-309;3b7f723)

[14:24:14 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 

[14:25:07 INFO]: This server is running Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[14:25:07 INFO]: Previous version: git-Paper-130 (MC: 1.16.1)
[14:25:07 INFO]: You are running the latest version

**[REQUIRED] Description of the problem:**

When adding a group to a global region no one is able to build, even those in that group.

**How to replicate**:

make a world, see the global region.
add the desired group to the global region.
try to place block. and fail.

**Plugins being used on the server:**

FAWE
FAVS
gopaint
gobrush
worldguardextraflags
luckperms
vault
there are more, but these are what could possibly affect this issue.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by InfinityAspire** [comment]
Can confirm this is the case.
Adding a group to the global region sets the passthrough flag to deny, as it should, but the flag also affects member groups of the region, which it shouldn't.

**Comment by aurorasmiles** [comment]
This should be fixed now, can you test it again?

**Comment by aurorasmiles** [comment]
No answer, assuming this is fixed
