### ISSUE TITLE
Fawe Region Protection is extremely broken

### ISSUE THREAD

**Issue by Kevduu** [IntellectualSites/FastAsyncWorldEdit#560]
# Bug report for FastAsyncWorldEdit 1.16.1

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/b20fbc9e61534ddc9c036699e724ffda

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
Bukkit-Official(1.16-309;3b7f723)

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-131

**[REQUIRED] Description of the problem:**
I have been using fawe and apparently the permissions are really broken, I have set permissions for regions such as fawe.worldguard fawe.lands etc. and I even have the set worldedit permissions in order to do these tasks, the permissions seem to work but when I try to //copy and //paste, no action is being done and the players are still members and owners of a world they are doing this in. This issue is really major since it heavily relies on worldguard for building and not plots. The only way to fix this from what I have saw was doing fawe.* and worldedit.*, but I do not want to give them every permission to worldedit since it will allow them to worldedit in regions you cant do it. Even unloading most of the plugins that include region protection such as PlayerWorldsPro, and Lands, the issue still occurs.

**How to replicate**:
Start a new server using similar format with worldguard, give your player permissions such as fawe.worldguard and worldedit.seleciton.paste etc. it says it has done the task on the chat but I does not actually do the task, which means the permissions to the command had worked but the execution did not work

**Plugins being used on the server:**
AdvancedAchievements, AdvancedPortals, ArmorStandAdjustor, Atamos, BKCommonLib, Brewery, ChatInjector*, Citizens, CitizensCMD, CleanMotD*, CMI, CMIPaperLib, CoreProtect, CraftBook, DeluxeChat, DeluxeMenus, DeluxeTags*, DiscordSRV, FastAsyncWorldEdit, FogusCore, goBrush, GoldenCrates, goPaint, HeadDatabase*, HolographicDisplays, HubParkour, ImageMaps*, InfiniteScoreboard, InventoryRollback, Iridescent, ItemsAdder, Jobs, JoinEventsPro, Lands, LightAPI, LightCleaner, LoneLibs, LuckPerms, MAmbience, MiningTrophies, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, PlaceholderAPI, PlayerPoints*, PlayerWorldsPro, PluginConstructorAPI, PlugMan, ProtocolLib, QualityArmory, Skript, TAB, UltimateTimber, Vault, Vehicles, VeryDangerousCaves, ViaBackwards, ViaVersion, Votifier, VotingPlugin, VoxelSniper, WorldBeautifier2, WorldBorder, WorldCommands, WorldEdit, WorldGuard, XWeather, Zenchantments

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
This is likely fixed with https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/617
Please open a new issue if that issue persists
