### ISSUE TITLE
/brush copypaste does not work correctly

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#562]
# Bug report for FastAsyncWorldEdit 1.16.1

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
config.yml: https://pastebin.com/qbx642wn
config-legacy.yml: https://pastebin.com/E4qmuBMb

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.16-315

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Doing a left click with the base of an object (in this test a cuboid) only 1 block is copied. Pasting the copied block will place the wrong block.

![image](https://user-images.githubusercontent.com/10485646/89775709-4e65d180-db00-11ea-8b06-d006011e0f19.png)

The other issue is that right clicking with the brush to paste the copied object will place the incorrect item. It copied the stone block but when pasting it sets Andesite Wall: 

![image](https://user-images.githubusercontent.com/10485646/89775675-3d1cc500-db00-11ea-86ff-742690ddceab.png)
**How to replicate**:
Create a stone cube with //set, use /brush copypaste and left click the base of the object. Right click with the brush to paste what you just copied.

**Plugins being used on the server:**
FastAsyncWorldEdit, LuckPerms, PlotSquared, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
This still seems to be an issue. For me it did copy more blocks, but not every block, and they are the wrong type. Due to the shape it copied I assume somehow it always removes 1 from the y when pasting or smth like that?
![2020-09-19_14 52 21](https://user-images.githubusercontent.com/21148213/93667635-c2907f00-fa87-11ea-93bf-2228338d2f8a.png)

**Comment by SecretlyJealous** [comment]
I tested with build 376 and it does indeed seem to copy more than 1 block now however it sets them to the wrong block id and doesn't paste all the blocks:

Original build I copied using the brush:
![2020-09-28_22 32 23](https://user-images.githubusercontent.com/10485646/94488452-89b87e80-01da-11eb-844f-4493c6467225.png)

Pasting the build with the copypaste brush:
![2020-09-28_22 33 18](https://user-images.githubusercontent.com/10485646/94488497-9dfc7b80-01da-11eb-8506-37f7383272f4.png)

**Comment by aurorasmiles** [comment]
The reason why for both of us not all blocks where copied is because the brush size was too small. with /brush copypaste 20 for example it worked :'D
