### ISSUE TITLE
java.lang.IllegalStateException: Chunk not there when requested: Unloaded [-24, -28] Unloaded [-16, -20] Unloaded [-16, -20]

### ISSUE THREAD

**Issue by christophe6** [IntellectualSites/FastAsyncWorldEdit#564]
**[REQUIRED] FastAsyncWorldEdit Configuration Files:**
I can't really share IP's and other confident information on a public website without explicit permission of my players due to the EU GDPR laws. I have the standard configuration and I haven't changed a thing.

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FAWE 1.16 - 315

**[REQUIRED] Spigot/Paper Version Number:**
git-Paper-321 (MC: 1.15.2)

**[REQUIRED] Description of the problem:**
https://haste.athion.net/dofomodefe.md
I created a custom plugin to paste schematics like skyblock islands in a void world. All is fine for the first island but when the second island wants to spawn, the server throws this error. I think it may be because the world has not yet been generated in that place and therefore the chunks do not exist. The player that initiates this island creation is still in the starting world when the error occurs. Is there a possibility to generate the chunk within fawe before trying to paste a schematic? I am handling the world generation myself and there is not a problem with that if I travel the world ingame.

**Plugins being used on the server:**
[16:01:18 INFO]: Plugins (39): chocokikker, Citizens, Classrooms*, CommandNPC*, DreamWorldCorev3, Duel*, EpicWorldGenerator, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FeatherBoard*, Gringotts, Harry_Potter_Economy, HolographicDisplays, LibsDisguises, LiteBans*, LuckPerms, Magic, Missions, MobArena, Multiverse-Core, MVdWPlaceholderAPI*, NametagEdit*, PlaceholderAPI, PlugMan, ProtocolLib, Shops, TitleAPI, TitleManager, Vault, VoidGenerator, Votifier, VoxelSniper, WizardingIdentities, WorldBorderAPI*, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardEvents
Checklist:

√  I included all information required in the sections above
√  I made sure there are no duplicates of this report (Use Search)
√  I made sure I am using an up-to-date version of FastAsyncWorldEdit for 1.16.1
√  I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Is this still an issue using the latest FAWE/paper?

**Comment by christophe6** [comment]
This is a resolved paper bug.
