### ISSUE TITLE
WorldEdit CLI

### ISSUE THREAD

**Issue by Lennord** [IntellectualSites/FastAsyncWorldEdit#566]
Hello, I would like to suggest an idea for adding this plugin.

I would like that we could use all the commands of this plugin but in the console, because I realized that it does not work in the console.

Example console commands:

- //pos1 [player]...
- //cut [player]...
- //replace [player]...
...

**Comment by MattBDev** [comment]
Great idea but we do have a few roadblocks to making this work. I'll list them here later this week.

**Comment by Lennord** [comment]
> Great idea but we do have a few roadblocks to making this work. I'll list them here later this week.

I hope these obstacles are not too great, I hope you will succeed in making this idea...

**Comment by N0tMyFaultOG** [comment]
No, bad stalebot.

**Comment by Lennord** [comment]
Hello, I would like to know any news of my idea? How does his advance?

**Comment by NotMyFault** [comment]
> Hello, I would like to know any news of my idea? How does his advance?

As you can see, nothing has been done in regards of that.

**Comment by MattBDev** [comment]
I'd be happy to revisit this during the Summer but at this time we don't have plans.
