### ISSUE TITLE
Crash /reload

### ISSUE THREAD

**Issue by Lennord** [IntellectualSites/FastAsyncWorldEdit#567]
Hello, I found a problem with this plugin, when I do the / reload command and reconnect it gives me an error in the console and therefore I can no longer recce myself on the server. If you can see if you can fix it...

Erreur: https://pastebin.com/Wwk9Ed2D
Version Spigot: 1.16 R1
Version of plugin: FastAsyncWorldEdit-1.16-311

**Comment by dordsor21** [comment]
never /reload
