### ISSUE TITLE
Entities don't get a correct rotation value on rotate

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#577]
When coping entities and using //rotate, the position of the entity is correctly changed, but the rotation of the entity itself is not, causing funny things with Itemframes
![2020-08-23_12 20 22](https://user-images.githubusercontent.com/21148213/90976362-a5c26380-e53c-11ea-9214-0d0050015009.png)
![2020-08-23_12 27 56](https://user-images.githubusercontent.com/21148213/90976364-a78c2700-e53c-11ea-9810-eec928d58643.png)

**Comment by TheoRetisch1** [comment]
That's awesome! Thank you :)
