### ISSUE TITLE
Error after updating from build #325 to #326 - v1.16.2

### ISSUE THREAD

**Issue by SuperRonanCraft** [IntellectualSites/FastAsyncWorldEdit#588]
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
Debugger: https://athion.net/ISPaster/paste/view/5f0f2740e46744a3bcfef360655123c0
Config: https://hastebin.com/oqezisayiq.coffeescript

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FAWE Version: https://hastebin.com/xogijepatu.makefile

**[REQUIRED] Spigot/Paper Version Number:** 
Spigot Version: This server is running CraftBukkit version git-Spigot-b5a13e6-0491200 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Console Error: https://hastebin.com/ufimidoseb.sql
Description: 
I just upgraded from build #325 to #326 to have translation support, and the expected behvior was to have the small region i had selected to turn into air, but instead had this error, while previously I did not get this error.
 This is a clean install too, so the config is default.

**How to replicate**:
Simply typing '//set air' with a region selected

**Plugins being used on the server:**
Plugins should be listed in the debug command, but some relevant plugins are PlotSquared and worldguard. The Worldedit included was injected from FAWE, Worldedit it not in the plugins file of the server.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
> [14:05:26] [Craft Scheduler Thread - 1/WARN]: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.shorts.ShortArraySet


@aurorasmiles 👀

**Comment by aurorasmiles** [comment]
This is an issue with Spigot. We generally recommend using Paper, since FAWE works better there anyway. I'll look into fixing this, but It is working fine on Paper.

**Comment by N0tMyFaultOG** [comment]
You can use [Paper](https://papermc.io/) in the meantime to get a rid of the error.

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/aa93f192c616f74854725ec77ccb88be8dc69877
