### ISSUE TITLE
Add ability to change wand item.

### ISSUE THREAD

**Issue by satyrnhub** [IntellectualSites/FastAsyncWorldEdit#589]
**Is your feature request related to a problem? Please describe.**
I have a private server with my friends that has Creative and Survival. Because it is on one server, I would like to change the wand item to something other than a wooden axe. That way, my friends can play Survival without interfering with FAWE.

**Describe the solution you'd like**
I would like to be able to change the item that is used for the wand to something else.

**Describe alternatives you've considered**
- FAWE would check WorldEdit's `wand-item` setting. I have already tried this, and it did not work.
- FAWE could be disabled in specific worlds.

**Comment by N0tMyFaultOG** [comment]
You can do that in the config-legacy.yml.
If it doesn't work currently, wait until https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/591 is merged into 1.16.
