### ISSUE TITLE
//move -a does not work properly when the move is within the selection

### ISSUE THREAD

**Issue by EverbloomTober** [IntellectualSites/FastAsyncWorldEdit#592]
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/170ca035576c4de684b055a803f21af3

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldedit-328

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-172 MC:1.16.2 (Implementing API version 1.16.2-R0.1-SNAPSHOT

**[REQUIRED] Description of the problem:**
When trying to use //move -a on a selection, and the move happens within the selection then only some, or none of the blocks get moved. There seems to be no logic to which blocks get moved.

This is before the move: https://i.imgur.com/BSQWzse.png 
After doing //move 1 -a I get this: https://i.imgur.com/07GsQmh.png 

However, if I do //move 5 -a I get this: https://i.imgur.com/ZJAMazS.png

Moving the selection by 5 blocks puts the whole thing outside of the original selection, and then the command seems to be running perfectly fine, however when the selection is moved to a place that still includes part of the selection it seems to start messing up. This only happens when the -a argument is added to the //move command, without this argument the command functions as expected.

**How to replicate**:
Make a selection that's larger than 1 in both length and width
Run //move -a

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by lusu007** [comment]
Using FAWE build 366 and Paper 192 it works fine for me.
