### ISSUE TITLE
#darken and #lighten are not recognized as patterns. 

### ISSUE THREAD

**Issue by EverbloomTober** [IntellectualSites/FastAsyncWorldEdit#595]
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/e600cc926acb4179b6845a07416b1964

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-328

**[REQUIRED] Spigot/Paper Version Number:** 
git-paper-173 (MC 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Trying to equip a brush with the command /brush sphere #darken 10 or /brush sphere #lighten 10
I get the following output: 
https://i.imgur.com/jI56fkP.png 
https://i.imgur.com/Zq6aYSy.png

**How to replicate**:
Use the #darken or #lighten pattern on any command that uses a pattern as an argument, for example /brush sphere #darken 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Could you explain what those patterns do?

**Comment by PhilippUlti** [comment]
#darken and #lighten are patterns to make better color transitions when using multiple types of blocks in the same building. For example it would make a certain selection of blocks darker when using #darken (e.g. fire_coral_block to nether_wart_block)
