### ISSUE TITLE
Craftbook ToggleArea mechanic broken with FAWE 1.16.2

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit#603]
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

 https://athion.net/ISPaster/paste/view/db376863e1a2404c9ade29853bb536b4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

[00:52:32 INFO]: FastAsyncWorldEdit-349 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[00:52:32 INFO]: FAWE version:
 - Date Sep 8, 2020, 12:00:00 AM
 - Commit f153f58c
 - Build 349
 - Platform Bukkit
[00:52:32 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[00:52:32 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-349;eac0a74)

[00:52:32 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 

[00:54:46 INFO]: This server is running Paper version git-Paper-185 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[00:54:46 INFO]: Checking version, please wait...
[00:54:46 INFO]: Previous version: git-Paper-130 (MC: 1.16.1)
[00:54:46 INFO]: You are 1 version(s) behind

**[REQUIRED] Description of the problem:**

CRaftbook loads fine with Worldedit, FAWE breaks the ToggleArea Mechanic and causes the console error
along with not  loading / switching schematics.

I am trying to make a parkour course that uses appearing / disappearing platforms. i have a redstone clock setup to toggle signs assigned to each area.

**How to replicate**:

1: Install worldedit and Craftbook 3.10.2 on 1.16.1.
2: set up 2 areas  and a sign to toggle them. 
3: hook up redstone to the signs to use them.
4: stop server / update to 1.16.2 / Listed plugin versions. (FAWE 349)
5: Start server. When areas are supposed to be toggled, the error in console occurs

        I suspect either schematics from worldedit are either not loading or FAWE / Craftbook are being messy
**Plugins being used on the server:**

Included in FAWE debugpaste

**Checklist**:

- [x] I included all information required in the sections above
- x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin   (pretty sure, the error happens with FAWE but not with worldedit)

**Comment by aurorasmiles** [comment]
The mechanic itself works now.
The only issue that I was able to notice is that when you leave the last line empty, it doesn't clear the area. But you can just use a second empty area instead, and it works fine
