### ISSUE TITLE
Rotation on x- and z-axis does not work

### ISSUE THREAD

**Issue by PhilippUlti** [IntellectualSites/FastAsyncWorldEdit#606]
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/b6c3ca8360804e3f991eb12ae8a5f186

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

http://prntscr.com/uevewn

**[REQUIRED] Spigot/Paper Version Number:** 

http://prntscr.com/uevfay

**[REQUIRED] Description of the problem:**

It is not possible, to rotate Clipboards on x- and z-axis by using //rotate x y z
The y-Axis rotation is working fine tho.

**How to replicate**:

**Plugins being used on the server:**

http://prntscr.com/uevhup

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by lusu007** [comment]
Using build 362 it works fine.

**Comment by aurorasmiles** [comment]
This was likely fixed with 63b2b83c10f0cab9ee39c64c1f958b2974203d5c
