### ISSUE TITLE
WE problem on merged plots 

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/FastAsyncWorldEdit#609]
# Bug report for FastAsyncWorldEdit 1.16.2

Report Copy from https://issues.intellectualsites.com/issue/PS-89

In merged plots WE commands don't work in specify chunks. These chunks was a part of the road before the merging.

![grafik](https://user-images.githubusercontent.com/4140635/92941826-26e08c80-f451-11ea-9f99-561eb9d8bf35.png)
![grafik](https://user-images.githubusercontent.com/4140635/92941899-39f35c80-f451-11ea-82be-13d87e5722bd.png)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

Last test with `FAWE version "1.16-306"`!

**[REQUIRED] Spigot/Paper Version Number:** 

Last test with 1.15.2 ... my admin will re-test it as soon as possible.

**How to replicate**:

1.    Claim 3 plot in a L form.
2.    Merge it.
3.    Use "//set lava" or other set command

**Plugins being used on the server:**
https://athion.net/ISPaster/paste/view/a6d7ac9ee9a044da99386f744709e0ee

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Xaver106** [comment]
Tested with the newest version of FAWE(1.16-353) and Plotsquared(5.13.4)
Get the same results

[Debugpaste](https://athion.net/ISPaster/paste/view/d3111f1d69bf44dfa63febdf258befe1)

**Comment by xion87** [comment]
Bug still here, using Paper 1.16.3, plotsquared 5.13.4 and build Fawe 352 is a lot anoying for these people that merged the plots
