### ISSUE TITLE
//replace not working if selection contains more than one chunk

### ISSUE THREAD

**Issue by lusu007** [IntellectualSites/FastAsyncWorldEdit#612]
# Bug report for FastAsyncWorldEdit 1.16.3

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/1c68532d3fa446f78b7483200ed4be54

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

FAWE Build 354

**[REQUIRED] Spigot/Paper Version Number:** 

git-Paper-192

**[REQUIRED] Description of the problem:**

``//replace`` doesnt work when replacing blocks in multiple chunks. If you just replace blocks in one chunk it works as intented.

**How to replicate**:

Make a selection containing multiple chunks and try to execute ``//replace`` with any block.

**Plugins being used on the server:**

Arceon, BuildersUtilities, BungeeTabListPlus, Essentials, FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, LegendBlockAnimatorBuild*, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoxelSniper, WorldEdit, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by TheoRetisch1** [comment]
I'm facing the same problem using the same version. Since //replace is one of the most frequently used commands, a timely fix would be very welcome :)

**Comment by SirYwell** [comment]
I suggest using build[ 352](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/352/) for now

**Comment by TheoRetisch1** [comment]
Ok, thank you 👍
