### ISSUE TITLE
Block rotations for nether portal blocks

### ISSUE THREAD

**Issue by Cypphi** [IntellectualSites/FastAsyncWorldEdit#618]
**Is your feature request related to a problem? Please describe.**

Well, kind of, since worldedit has the same issue I don't think this is a bug but I would love to see block rotations for nether portal blocks when using //paste, I'm currently working on a big build and I have to relight all nether portals since the portals are rotated the wrong way whenever I paste it in.

Portal blocks don't keep it's rotation when being pasted in specific directions, if I'm right they always get pasted in facing north.

**Describe the solution you'd like**

Make it so when you //copy a build it saves the rotations of blocks like nether portal blocks which still don't keep it's rotation.

**Describe alternatives you've considered**

/

**Additional context**

/

**Comment by dordsor21** [comment]
This does not seem to be an issue anymore
