### ISSUE TITLE
Wrong Data and Orientation with chains and lanterns

### ISSUE THREAD

**Issue by Tombstone1973** [IntellectualSites/FastAsyncWorldEdit#631]
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/cc9d6b7d9cef4f59b062f45633b0caf4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

Build 369
**[REQUIRED] Spigot/Paper Version Number:** 

Paper-198
**[REQUIRED] Description of the problem:**

Chains are pasted in the wrong direction and lanterns don't have the right data
**How to replicate**:

Paste anything with chains or lanterns
**Plugins being used on the server:**

**Checklist**:

- [] I included all information required in the sections above x
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/) x
- [] I made sure the bug/error is not caused by any other plugin x

**Comment by TheoRetisch1** [comment]
Confirmed for Paper 1.16.3 build 198 and FAWE 369.

**Comment by dordsor21** [comment]
I can't replicate anything wrong with either of these. Can you show screenshots of what you mean?

**Comment by TheoRetisch1** [comment]
Chains and lanterns have the wrong block data: 
![Blockstatus](https://user-images.githubusercontent.com/24480321/93671412-1e1c3600-faa3-11ea-9cb2-01940f69c718.png)

But I have just tested it again: It only happens with chains and lanterns that were created as schematic in version 1.16.1. With version 1.16.2 it became possible to set horizontal stairs and to place lanterns under water. So it is once again a schematic conversion problem.

**Comment by dordsor21** [comment]
I'm going to call this fixed then if it's working now.
