### ISSUE TITLE
Any blocks will be penetrated by rain after pasting

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#633]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/ce28bf4de0464632a0f479a59e5fae4f

**FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit version 1.16-369;aed6807

**Spigot/Paper Version Number:** 
git-Paper-198 (MC: 1.16.3)

**Description of the problem:**
After copying a building, the blocks will be penetrated during the rain, unlike normal conditions to prevent the rain, (can be understood as: the player can see this block, but the server may mistakenly think that there is no such block -> Resulting in passing through the blocks when it rains, without blocking the rain's fall).

**How to replicate**:
Copy a building with a roof, paste it and enable the rain. The rain will penetrate through the roof. Example: 
https://imgur.com/a/ZmqKdiN

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report -> you marked all rains issues as fixed so I opened a new one
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
//fixlighting should also fix heightmaps and therefore maps and rain

**Comment by TheoRetisch1** [comment]
I just tried it with fixlighting on the same setup (https://athion.net/ISPaster/paste/view/3bce39451bd64a219ab2610124dccccf) and it doesn't work. I have used fixlighting and //removelighting several times. Turn the rain on and off and restart the server. Without success it still rains through the roof.

**Comment by aurorasmiles** [comment]
This is interesting, because others report that fixlighting does change the heightmaps, but blocks rain completly (#632 )

**Comment by aurorasmiles** [comment]
Please keep in mind that fixlighting only updates the heightmap in your selected area

**Comment by TheoRetisch1** [comment]
I have just tested it again: If you make only a selection the rain is not affected by _//fixlightning_. If you enter _//expand vert_ it won't rain in the area anymore.  Of course this is not a cool solution either xD

**Comment by TheoRetisch1** [comment]
It works like a charm, thank you very much 💯
