### ISSUE TITLE
Restore doesn't work for entities

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#634]
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/fa65d98675eb49b6a54f4f15d431729d

**FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit version 1.16-369;aed6807

**Spigot/Paper Version Number:** 
git-Paper-198 (MC: 1.16.3)

**Description of the problem:**
The restore command doesn't restore entities like item frames, armorstands or paintings. I tested it with multiple rotations of different entities. The world and the restore backup is fully upgraded to version 1.16.3 (force upgrade).

**How to replicate**:
Try to restore item frames, paintings or armor stands from a world in the backup folder using *//restore* . The restore command will only work for blocks.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report -> you marked all restore entity issues as fixed so I opened a new one
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Xaver106** [comment]
Same Problem here. The //restore command doesn't restore entitys. It doesn't adds them back in and doesn't remove newly placed ones. Works the same with other entitys like pigs.

Tested on:
- Paper 385 for 1.15.2
- Fawe Build 446

**Comment by TheoRetisch1** [comment]
The problem still exists:
FastAsyncWorldEdit version 1.16-587
Paper 1.16.5 - 457

**Comment by NotMyFault** [comment]
See https://github.com/EngineHub/WorldEdit/issues/1749
