### ISSUE TITLE
Unsafe memory access using cross server clipboards

### ISSUE THREAD

**Issue by lusu007** [IntellectualSites/FastAsyncWorldEdit#638]
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/4688e1f451a5435da8a2ee16a417e391

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
[20:44:09 INFO]: FastAsyncWorldEdit-371 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[20:44:09 INFO]: FAWE version:
- Date Sep 19, 2020 12:00:00 AM
- Commit f41f1cc9
- Build 371
- Platform Bukkit
[20:44:09 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[20:44:09 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-371;be0e337)
[20:44:09 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 

git-Paper-202

**[REQUIRED] Description of the problem:**

If you paste something with ``//paste -a`` from one server to another an error gets thrown and FAWE pastes nothing. The servers uses a shared clipboard folder.

**How to replicate**:

Setup a server network and shared clipboard. Then execute ``//paste -a``.

**Plugins being used on the server:**

Arceon, Builders-Utilities, BungeeTabListPlus, Essentials, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, Hyperverse, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoidGenerator, VoxelSniper, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
I've talked about this issue before, afaik that is not really a bug since it isn't what clipboard-on-disk is meant to do - but that was a few months ago, maybe this is different now.

**Comment by lusu007** [comment]
When clipboard-on-disk is´nt meant for this use, how should I implement cross-server clipboards?

**Comment by aurorasmiles** [comment]
As far as I know you don't - you use schematics

**Comment by lusu007** [comment]
It would be really cool if a cross server clipboard was possible. 😄

**Comment by Orlaando-dev** [comment]
I’m pretty sure cross server clipboards are possible by setting up symbolic links.

**Comment by lusu007** [comment]
At the moment we mounted a folder into all our Docker Containers running a MC server.
All servers are accessing the same folder.

**Comment by aurorasmiles** [comment]
Hey, if possible could you test if my pull request fixes your issue?

**Comment by lusu007** [comment]
Yes of course. Where do I get the build? Or should I compile FAWE myself?

**Comment by aurorasmiles** [comment]
If you know how to do that you can compile my branch yourself - if not I can send you a build later

**Comment by lusu007** [comment]
I can compile it myself. I will come back to you after a quick test. 😄

**Comment by lusu007** [comment]
It works partially. It looks like the server I'm using ``//paste`` on tries to load the clipboard from RAM. When I execute ``//cc`` before using ``//copy`` it works. Otherwise we get the same error as always.

https://athion.net/ISPaster/paste/view/a9f6855ae5a94a72a5f61f7668485b97
