### ISSUE TITLE
Manual cancellation error when leaving server

### ISSUE THREAD

**Issue by lusu007** [IntellectualSites/FastAsyncWorldEdit#641]
# Bug report for FastAsyncWorldEdit 1.16.3

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/b02cd6d870f843a38392a94f3930efef

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
>.... [12:10:11 INFO]: FastAsyncWorldEdit-372 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
>.... [12:10:11 INFO]: FAWE version:
- Date Sep 19, 2020 12:00:00 AM
- Commit f7ba3cd5
- Build 372
- Platform Bukkit
>.... [12:10:11 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
>.... [12:10:11 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-372;845c32b)
>.... [12:10:11 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 

git-Paper-202

**[REQUIRED] Description of the problem:**

If you run a large task and then leave the server you get an Manual cancellation error in console.
The action cancels successfully but an error gets thrown.

**How to replicate**:

Execute a big replace command and leave the server.

**Plugins being used on the server:**

Arceon, Builders-Utilities, BungeeTabListPlus, Essentials, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, Hyperverse, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoidGenerator, VoxelSniper, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by lusu007** [comment]
This is still a thing in Build 449 and paper-318. This Issue isn't stale.

https://athion.net/ISPaster/paste/view/3154d7f5693e447dba78445f929494ac

**Comment by dordsor21** [comment]
It will only print a (the) warning message now. However, this is not a bug regardless.

**Comment by SchattenWolf2008** [comment]
How can you prevent it from cancellating the action??
I cant run my PC for 18 hours
