### ISSUE TITLE
Reimplement missing masks

### ISSUE THREAD

**Issue by lusu007** [IntellectualSites/FastAsyncWorldEdit#643]
**Is your feature request related to a problem? Please describe.**
#liquid, #l2d[], #l3d[], #buffer[] are missing at the moment. Its nessecarry for setting biomes  and terraforming.
 
**Describe the solution you'd like**
Reimplement missing masks.

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by TheoRetisch1** [comment]
What exactly do the l2d and l3d masks/patterns do? I suppose you used something like 
//br stencil #buffer[#l3d[$measa,$jungle,$desert]]
but I never understood what exactly l3d does and what the concrete difference to l2d is? Can you explain it?

**Comment by lusu007** [comment]
The #l2d mask is basically arranging the blocks like a chess board which than is extended the full height. The #l3d is offsetting the pattern arrangement on every y-level, so that above a "white" tile is a black tile. Obviously you can provide more than just two patterns so this is basically just getting again mixed in.

**Comment by dordsor21** [comment]
Does the liquid mask not work?

**Comment by lusu007** [comment]
Seems to work in the latest version (build 393). With an older version we had some problems.
