### ISSUE TITLE
Significant decrease in //replace performance in build 360+, introduced somewhere after build 354. 

### ISSUE THREAD

**Issue by Combustible** [IntellectualSites/FastAsyncWorldEdit#648]
# Bug report for FastAsyncWorldEdit 1.16.3 / 1.15.2 (reproducible on both)

**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/9f53e1f9f5c946c788a4587928f70ef9

**FastAsyncWorldEdit Version Number:** 
Very slow in version FastAsyncWorldEdit-360, 371
Works fast/correctly in FastAsyncWorldEdit-349, 350, 354

**Spigot/Paper Version Number:** 
Paper version git-Paper-"d802a50a9" (MC: 1.16.3)
Paper version git-Paper-"cebec202f" (MC: 1.15.2)

**Description of the problem:**
Doing a //replace operation over a very large area (for example 5 million blocks) is now extremely slow. In build 354 (latest one I tested which was good), this takes 1-3 seconds. In build 360 (oldest one I tested with the problem), this takes almost 3 minutes before it completes. 

**How to replicate**:
Large //replace operation (~ 5 million blocks for example). Seems to be consistent in my limited testing... Was replacing an underground area so no view of the sky - I know there are some light related changes between 354 and 360 but not sure if that is the reason. 

**Plugins being used on the server:**

Plugins (18): Arceon, BKCommonLib, BungeeTabListPlus, CommandAPI,  (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, LightCleaner, LuckPerms, MonumentaWarps*, PlaceholderAPI, PrometheusExporter*, ProtocolLib, ScriptedQuests, SpeedChanger*, Vault, VentureChat, VoxelSniper

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You have parallel threads set to 1 in this debugpaste. Is that intentional, and did you also have it set to 1 when in pervious versions? I cannot replicate any issues with replace.

**Comment by Combustible** [comment]
Yes, I used the same config for both tests. The only thing I changed was the FAWE plugin jar.

**Comment by dordsor21** [comment]
Is performance still poor for replace?

**Comment by dordsor21** [comment]
I assume this is no longer an issue

**Comment by Combustible** [comment]
Was fixed, thanks!
