### ISSUE TITLE
WARNS at //fixlighting and job seems to not be completed

### ISSUE THREAD

**Issue by P4ND4-1100010** [IntellectualSites/FastAsyncWorldEdit#652]
# Bug report for FastAsyncWorldEdit 1.16.3
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/04db27deb88e417ea98e51b9ef3dbe91

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
```
[lun., 21. sept. 2020 20:01:50 CEST INFO] FastAsyncWorldEditunknown created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[lun., 21. sept. 2020 20:01:50 CEST INFO] Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[lun., 21. sept. 2020 20:01:50 CEST INFO] ------------------ Platforms ------------------
* Bukkit-Official(1.16-376;3b66075)

[lun., 21. sept. 2020 20:01:50 CEST INFO] ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 
```
[lun., 21. sept. 2020 20:03:01 CEST INFO] This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[lun., 21. sept. 2020 20:03:01 CEST INFO] Checking version, please wait...
[lun., 21. sept. 2020 20:03:02 CEST INFO] Previous version: git-Paper-191 (MC: 1.16.3)
[lun., 21. sept. 2020 20:03:02 CEST INFO] You are running the latest version

```
**[REQUIRED] Description of the problem:**
I get warns when I execute //fixlighting and the job seems to not be completed.
Warns: https://pastebin.com/nUnZbpzY

**How to replicate**:
1) Select an area (bigger = most frequent reproducible)
2) //expand vert
3) //fixlighting
You can test to create a map and see that blocks not appear on it and you can also see that there are still dark areas around.

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you could try the latest build with a fixlighting in the same area and look for any debug messages in console, that would be very helpful.

**Comment by P4ND4-1100010** [comment]
Working fine with * Bukkit-Official(1.16-377;5e67c1b)
