### ISSUE TITLE
//redo loses block inventories.

### ISSUE THREAD

**Issue by eth-p** [IntellectualSites/FastAsyncWorldEdit#655]
# Bug report for FastAsyncWorldEdit 1.16.3

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/50c0a7cf9bc14c568236ad5ec9d39119

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
FastAsyncWorldEdit-377 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
FAWE version:
 - Date Sep 22, 2020 12:00:00 AM
 - Commit fa1983e5
 - Build 377
 - Platform Bukkit
 Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
------------------ Platforms ------------------
* Bukkit-Official(1.16-377;5e67c1b)
---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 

`git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`
This also affects 1.15.2.

**[REQUIRED] Description of the problem:**

When copying chests and other containers and performing an `//undo` followed by `//redo`, the re-pasted blocks will lose their inventory contents.

**How to replicate**:

1. Place a chest down and fill it with items.
2. Copy the chest/hopper/furnace/etc in a way that you can `//undo` it (e.g. `//stack` or `//copy` and `//paste`).
3. Check the copy, and it should have the correct inventory.
4. `//undo`
5. `//redo`
6. Check the redo'ed copy, and the inventory is empty.

**Plugins being used on the server:**

A few chat and administration plugins and a custom plugin or two, but nothing that interferes with FAWE. It's also reproducible with a bare minimum setup.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Xaver106** [comment]
Can confirm the error. Same steps with the same result.
Tested with:
- Paper 385 for 1.15.2
- Fawe Build 446

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/708
