### ISSUE TITLE
FAWE can't paste schematics at all.

### ISSUE THREAD

**Issue by IIPedro** [IntellectualSites/FastAsyncWorldEdit#657]
# Bug report for FastAsyncWorldEdit 1.16.3

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/5348763065834249957693645b963627

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
[14:12:29 INFO]: FastAsyncWorldEditunknown created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[14:12:29 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[14:12:29 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-377;5e67c1b)

[14:12:29 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

Here's my latest.log:
[latest.log](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/5269831/latest.log)

**[REQUIRED] Spigot/Paper Version Number:** 
[14:12:52 INFO]: This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[14:12:52 INFO]: Checking version, please wait...
[14:12:53 INFO]: You are 2 version(s) behind

**[REQUIRED] Description of the problem:**
I created a new world via Multiverse and tried to paste a schematic. After that, I received this error: https://pastebin.com/EUya9dT2.
I tried to paste a different schematic to no avail.

**How to replicate**:
Simply try to paste a schematic. This is the one I used:
[https://www.minecraft-schematics.com/schematic/9741/download/action/?type=schematic](https://www.minecraft-schematics.com/schematic/9741/download/action/?type=schematic).
I'm sorry, I can't insert schematic files here.

**Plugins being used on the server:**
AdvancedBan*, AntiCheatReloaded, AuthMe, BedWars, BuildBattle, ChatControl, Citizens, ClearLag, CommandPanels, CoreProtect, CrazyCrates, DeluxeHub, DiscordSRV, EntityTrackerFixer, Essentials, EssentialsChat,  (WorldEdit)FastAsyncWorldEdit, Geyser-Spigot, GriefPrevention, HolographicDisplays, HungerGames, IridiumSkyblock, KP-PVP, LibsDisguises, LitePlaytimeRewards, LuckPerms, Morphy, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MurderMystery, ParticleHats, PetBlocks*, PlaceholderAPI, PlugMan, ProtocolLib, SAML, Scoreboard-revision*, SkinsRestorer, Skywars, StaffPlus, SuperLog, SuperVanish, TAB, TNTRun_reloaded, TrollBoss, Vault, ViaVersion, VoidGenerator, WorldGuard

**Checklist**:

- [X] I included all information required in the sections above (I couldn't provide steps to replicate well, it wasn't possible)
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/) (I'm using 1.16.3)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Rename the schematic from <name>.schematic to <name>.schem

This website is bad and does not abide by the sponge schematic specification as detailed at: https://github.com/SpongePowered/Schematic-Specification
