### ISSUE TITLE
Cinematic Block Placement not working.

### ISSUE THREAD

**Issue by Coder-Kid** [IntellectualSites/FastAsyncWorldEdit#662]
I was looking through the config files of this and found `speed-reduction: 0`. I have spent forever trying to get it to work. I have tried Forge and Spigot. I have tried setting `fast-placement:false`. I have tried big numbers and small numbers. I also can't find anything about it online. I remember using some form of it in the past but cannot get it to work now. Can someone please help me with this?

**Comment by aurorasmiles** [comment]
Please don't delete the issue template.
