### ISSUE TITLE
#id pattern comeback

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#663]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I want to change blocks with different orientations like stairs or trapdoors on one building to another material, but with this action all blocks take the same orientation. This means a lot of manual work.

**Describe the solution you'd like**
It would be great if the pattern #id would return! It made sure that only the block ID is changed, but not the data value.

**Describe alternatives you've considered**
Since the system was already implemented once none.

**Additional context**
_Example_: //replace minecraft:oak_trapdoor #id[iron_trapdoor] -> Replaced all oak trapdoors to iron trapdoors while keeping the original trapdoor alignments.

**Comment by SirYwell** [comment]
That should be already possible with the [type or state applying pattern](https://worldedit.enginehub.org/en/latest/usage/general/patterns/#type-or-state-applying-pattern) provided by WorldEdit

**Comment by TheoRetisch1** [comment]
Thank you, that's awesome :)
