### ISSUE TITLE
FAWE command error

### ISSUE THREAD

**Issue by Spaceelliott** [IntellectualSites/FastAsyncWorldEdit#664]
Bug report for FastAsyncWorldEdit 1.16.3

FastAsyncWorldEdit Configuration Files:
https://athion.net/ISPaster/paste/view/c107a18ebf034a4e901da5642fe50259

FastAsyncWorldEdit Version Number:
26.09 13:22:57 [Server] INFO WORLD_EDITING: Bukkit-Official
26.09 13:22:57 [Server] INFO WORLDEDIT_CUI: Bukkit-Official
26.09 13:22:57 [Server] INFO PERMISSIONS: Bukkit-Official
26.09 13:22:57 [Server] INFO USER_COMMANDS: Bukkit-Official
26.09 13:22:57 [Server] INFO CONFIGURATION: Bukkit-Official
26.09 13:22:57 [Server] INFO GAME_HOOKS: Bukkit-Official
26.09 13:22:57 [Server] INFO ---------------- Capabilities ----------------
26.09 13:22:57 [Server] INFO * Bukkit-Official(1.16-345;f74bc8a)
26.09 13:22:57 [Server] INFO ------------------ Platforms ------------------
26.09 13:22:57 [Server] INFO Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
26.09 13:22:57 [Server] INFO - Platform Bukkit
26.09 13:22:57 [Server] INFO - Build 345
26.09 13:22:57 [Server] INFO - Commit f08b4376
26.09 13:22:57 [Server] INFO - Date Sep 7, 2020 12:00:00 AM
26.09 13:22:57 [Server] INFO FAWE version:
26.09 13:22:57 [Server] INFO FastAsyncWorldEdit-345 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault

Spigot/Paper Version Number:
26.09 13:24:14 [Server] INFO You are 2 version(s) behind
26.09 13:24:14 [Server] INFO Previous version: git-Paper-89 (MC: 1.16.1)
26.09 13:24:14 [Server] INFO This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

Description of the problem:
when i see it in game it says;
(FAWE) Please report this error: [see console]
(FAWE) java.lang.NullPointerException: null
in the console, it shows: https://pastebin.com/gSM7tckm

How to replicate:
basically any command

**Comment by N0tMyFaultOG** [comment]
Update Fawe.

**Comment by Spaceelliott** [comment]
i only just updated FAWE

**Comment by Spaceelliott** [comment]
apologies, i hadent got the right version
