### ISSUE TITLE
SuggestInputParseException is thrown

### ISSUE THREAD

**Issue by lusu007** [IntellectualSites/FastAsyncWorldEdit#674]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

https://athion.net/ISPaster/paste/view/048cfe1409084b2d8a415db2c275bf45

**Required Information**
- FAWE Version Number: 391
- Spigot/Paper Version Number: git-Paper-206
- Minecraft Version: 1.16.3

**Describe the bug**
An SuggestInputParseException exception is thrown when using ``//paste``.

**To Reproduce**
I can't specify, because a user of the server has executed it

**Plugins being used on the server**

Arceon, (WorldEdit)FastAsyncWorldEdit, HeadDatabase*, HolographicDisplays, LegendBauevent, LuckPerms, Panilla, PlotSquared, PremiumVanish, ProtocolLib, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
Seems to be caused by your disallowed-blocks configuration

**Comment by lusu007** [comment]
Hmh can be. But in my opinion the exception should not be thrown because it isnt an error.

**Comment by lusu007** [comment]
or is it due to a non-existent block?

**Comment by SirYwell** [comment]
422 (command_block_minecart), 323 (sign), and 401 (fireworks) aren't valid blocks. They only exist as item. It might be worth to look how WE handles invalid entries and adapt that, so I'll let this one open.

**Comment by lusu007** [comment]
All right I will adjust my configuration and look forward to a change regarding that execption. 😄

**Comment by lusu007** [comment]
This isn't an issue anymore. We resolved by adapting our config file.
