### ISSUE TITLE
//undo-ing a paste does not remove copied entities

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#676]
See title
Using undo after a //paste -e does not remove the entities

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/708

**Comment by jewome62** [comment]
I can confirm the problem exist into latest version.
https://athion.net/ISPaster/paste/view/1193e88715474e949f6534e9ef544ad5
Version: 1.17-277;8cc93a2
Version: git-Paper-266 (MC: 1.17.1)

**Comment by RedstoneFuture** [comment]
Still a problem. Also, with standing entities like an armor_stand.

FAWE 1.17-324
