### ISSUE TITLE
Chunk Bug | Visual after pasting/undoing

### ISSUE THREAD

**Issue by ismhdez** [IntellectualSites/FastAsyncWorldEdit#677]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**Required Information**
- FAWE Version Number: Build 397 (1.16)
- Spigot/Paper Version Number:  git-Paper-207 (MC: 1.16.3) (1.16.3-R0.1-SNAPSHOT)
- Minecraft Version:.1.16.3

**Describe the bug**
When I paste a schematic, people see the cages of my minigame with invisible blocks, and when I undo the pasting people sometimes still seeing it, and the player is bugged inside. They cannot see the player that was inside the cage.

Also, the chunks where the schematic was pasted is now bugged, entities appearing on these chunks are not visible.

**To Reproduce**

My code: https://haste.athion.net/usiqizuqik.cs

**Plugins being used on the server**

-- Custom plugins, the schematic paste is done in the previous link -- 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Some screenshots would be pretty useful here as well

**Comment by ismhdez** [comment]
Oh, sorry. I forgot it! xD

Image 1#: https://gyazo.com/85e5d42726adb1ffc52eb547888fe0dd -- Some blocks are invisible before you do F3+A
Image 2#: https://gyazo.com/2429361a58f4aac343447921df71ca0d -- Some blocks are invisible before you do F3+A

Image 3#: https://gyazo.com/4a3aa695e7e156b75513f346ea0e2891 -- Player from inside the cage is now invisible after undoing the paste (before F3+A)

Image 4#: https://gyazo.com/d1eeaa7c982c995bf885d18834a0dbd8 -- Player from inside the cage after you do F3+A

**Comment by dordsor21** [comment]
Do the blocks always appear to "fix" themselves after using f3+a?

I've replicated a similar issue, however, I have to leave the area and return in order for the blocks to update.

**Comment by ismhdez** [comment]
> Do the blocks always appear to "fix" themselves after using f3+a?
> 
> 
> 
> I've replicated a similar issue, however, I have to leave the area and return in order for the blocks to update.

Yes, if I do F3+A all the problems disappear

**Comment by TheoRetisch1** [comment]
I have the same problem. It happens with a very high probability with large edits 100+*100+. F3+a never helped in my tests. The blocks are there, but you have to reload the chunks on the server-side in order to see the invisible chunks.

Paper 1.16.3 - 220
FAWE 1.16-406

**Comment by TheoRetisch1** [comment]
I think I have a different problem than ismhdez. For me it was the plugin View Distance Tweaks, everything within the no-tick-view distance is not updated for the client, if the plugin is active (https://github.com/froobynooby/ViewDistanceTweaks/issues/5).

**Comment by TheoRetisch1** [comment]
I have tested it again with minimal plugin usage. Chunks in the no-tick-view distance of Paper are not updated, while the chunks in the normal view-distance show the changes correctly. The chunks in the no-tick-view distance can only be updated for the client by reloading the chunks on the serverside.
