### ISSUE TITLE
ArrayIndexOutOfBoundsException when using fixlighting on a big selection

### ISSUE THREAD

**Issue by lusu007** [IntellectualSites/FastAsyncWorldEdit#682]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

https://athion.net/ISPaster/paste/view/9299c4b5117245b9bd7ce2d8d48887f2

**Required Information**
- FAWE Version Number: 403
- Spigot/Paper Version Number: git-Paper-202 
- Minecraft Version: 1.16.3

**Describe the bug**
Fixlightning throws an ArrayIndexOutOfBoundsException when using ``//fixlightning`` on a big selection. 

**To Reproduce**
1. Make a big selection
2. Execute ``//fixlightning``

**Plugins being used on the server**

 Arceon, Builders-Utilities, BungeeTabListPlus, Essentials, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, Hyperverse, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoidGenerator, VoxelSniper, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by StealWonders** [comment]
Can confirm with Bukkit-Official(1.16-420;b86e452)
