### ISSUE TITLE
Worldedit not working

### ISSUE THREAD

**Issue by DoogiePC** [IntellectualSites/FastAsyncWorldEdit#685]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
https://athion.net/ISPaster/paste/view/253d8a72d98e453eba182aed472d664e

**Required Information**
- FAWE Version Number: 401
- Spigot/Paper Version Number:   Paper version git-Paper-214 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
- Minecraft Version: [e.g. 1.16.3] 1.16.3

**Describe the bug**
The plugin seems to be selectively responding to input. When I try //pos1 it sometimes doesn't work at all. Wands don't seem to be responding whatsoever. //asc works fine and responds in chat. //set doesn't even work. I have no idea what is going on. I have all applicable permission nodes.

**To Reproduce**
It is very hard to reproduce as worldedit seems to work initially for everyone but at some random point it just breaks.

**Plugins being used on the server**
https://timings.aikar.co/?id=a2af352089594ddfaa8cfab84fb0393e

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by TheoRetisch1** [comment]
I experienced the same problem. Suddenly no player could perform any worldedit action except pos1 + pos2. When one entered commands there was simply no reaction (no chat feedback and no WE action). Interestingly, from the console you could still successfully execute commands like FAWE reload, whose ingame entry had no effect. In the end only a server restart solved the problem. It happend once in 24 hours.

**Comment by SirYwell** [comment]
Might be worth to try `fawe threads` in console once the problem reappears and paste the resulting thread dump on http://haste.athion.net/

**Comment by dordsor21** [comment]
Also can you remember which build you updated to 401 from?

**Comment by TheoRetisch1** [comment]
I will try ` fawe thread` as soon, as it happens again. I updated from build 398 and never had this issue before.

**Comment by MattBDev** [comment]
I have the thread dump from @DoogiePC's server if you want it @SirYwell and @dordsor21 
http://haste.athion.net/qifusoxeju.log

**Comment by MattBDev** [comment]
Fixed
