### ISSUE TITLE
Implement lighting into FAWE queue. 

### ISSUE THREAD

**Issue by Projecki** [IntellectualSites/FastAsyncWorldEdit#686]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

 https://athion.net/ISPaster/paste/view/1fea5cd152b3424a916dda2c294a72d2

**Required Information**
- FAWE Version Number: 1.16-403;f71ca32
- Spigot/Paper Version Number: Tuinity 88a2c88 (MC: 1.16.3) AND Paper #216
- Minecraft Version: 1.16.3

**Describe the bug**
Lightning is not implemented into the queue. This results in areas where lightning is obviously incorrect after being edited by FAWE.

**To Reproduce**
1. Select an area and use //set air
2. Note the incorrect lightning.

**Plugins being used on the server**

Refer to debug paste. I am using Tokens by GC which utilizes FAWE for new pickaxe enchants that destroy many blocks.

Screenshot of what this issue looks like: https://cdn.discordapp.com/attachments/756175891456852019/763063163482013706/unknown.png

**Comment by Projecki** [comment]
This is very important to me and I would love to see this fixed. Appreciate it!

**Comment by TheoRetisch1** [comment]
Just use `//fixlighting` or `/paper fixlight`? What's the issue about that? I guess there are way more important issues xD.

**Comment by Projecki** [comment]
These enchants are used at regular intervals for mass edits to prison mines. I shouldn't have my server running paper fixlight 24/7

Or should I?

**Comment by Combustible** [comment]
Light Cleaner has built-in FAWE integration to clean lighting after lighting operations complete. I haven't tested the integration much, but recently became aware of it. You can turn off FAWE's automatic relighting and use LightCleaner's instead

Light Cleaner in general works amazingly well, pretty easy on the server and also has few/no visual glitches. 

https://www.spigotmc.org/resources/light-cleaner.42469/
