### ISSUE TITLE
PlotSquared FAWE error

### ISSUE THREAD

**Issue by xph11** [IntellectualSites/FastAsyncWorldEdit#695]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

https://athion.net/ISPaster/paste/view/17b96d61dc3048ee80f6877257a40f97

  
https://pastebin.com/kEr12Tse

**Required Information**
- FAWE Version Number: Build 410
- Spigot/Paper Version Number:  1.16.3
- Minecraft Version: [e.g. 1.16.3] 1.16.3

**Describe the bug**
I get this error upon server start: https://pastebin.com/kEr12Tse

**To Reproduce**
1. Start server
2. Wait a bit for PlotSquared to load the worlds
3. See error

**Plugins being used on the server**
You can see them in the debugpaste.

**Checklist**:
 V
- [] I included all information required in the sections above V
- [] I made sure there are no duplicates of this report [(Use Search)] (https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue) V
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/) V
- [] I made sure the bug/error is not caused by any other plugin V

**Comment by N0tMyFaultOG** [comment]
No response, assume fixed. Can't replicate on latest versions.
