### ISSUE TITLE
//undo doesn't work for //line

### ISSUE THREAD

**Issue by StealWonders** [IntellectualSites/FastAsyncWorldEdit#696]
**FastAsyncWorldEdit Configuration Files** 
https://athion.net/ISPaster/paste/view/83b82c25cdc0425d94164567977c1dbe

**Required Information**
- FAWE Version Number: 1.16-414;3c6280b
- Spigot/Paper Version Number:  git-Paper-220 (MC: 1.16.3)
- Minecraft Version: [e.g. 1.16.3]

**Describe the bug**
After making a line with //line and then trying to //undo it nothing happens apart from it sending a chat message.
This used to be broken then fixed... it's broken again now.

**To Reproduce**
Read "Describe the bug"

**Plugins being used on the server**
Just read the debugpaste

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
@StealWonders What was the last version of the plugin that this was working for you? This is very important so we can comment our code and prevent it breaking again in the future.

**Comment by StealWonders** [comment]
I updated from 377 to 410 and it stopped working. I can try and test some versions later to pin down a more exact version.

**Comment by StealWonders** [comment]
Alright, I tested basically everything from 410 back down to 377. The way I tested changed over the course of time and I found out that version 377 is not in fact unguilty. **All** versions do **not undo correctly**. 

If you use //line in conjunction with //set then weird things start to happen, let me try to explain.

The first time using //line and undoing it everything works fine. Once I use it for a second time though and then try to undo it will undo my first //line edit. If I then try to clear the area using //set 0, use //line and then undo again it will put back everything that //set 0 had taken away. This shouldn't happen it should revert back to air and not to the state pre //set 0.

Hopefully you understand. It's best you play around a bit yourself with any of the versions I guess because it's broken on all of them.
Cheers!

**Comment by zeronerve** [comment]
This bug, or similar behavior at least, also applied to //sel convex > //curve.

**Comment by PhilippUlti** [comment]
This bug also occurs on the current build

**Comment by PhilippUlti** [comment]
We have recently updated to the newest Paper Version and also updated to the newest FaWe build (#449). In this version //undo does work with //line
