### ISSUE TITLE
Brush Image command Bug?

### ISSUE THREAD

**Issue by nicokempe** [IntellectualSites/FastAsyncWorldEdit#698]
**Required Information**
- FAWE Version Number: "/fastasyncworldedit version" shows "Bukkit-Official(1.16-414;3c6280b"
- Spigot/Paper Version Number:  Paper-220 (currently latest build)
- Minecraft Version: 1.16.3

**Describe the bug**
I am creating terrain for all my maps using the brush height command from fawe. The command (//br height 50 https://i.imgur.com/JoSyq0z.png 0.1 0.7 -r) is still working on my 1.12.2 build server. But when I set up a new build server for the latest Minecraft version, the command no longer worked. At first I thought that now I just have to put "-r" in the front and that the syntax has only changed a little. Unfortunately that was not the case (visible during reproduction)

**To Reproduce**
1. Set up a Minecraft server on 1.16.3 and install FAWE.
2. Start the server
3. Join on the server
4. Pick up any tool (in my case a diamond pickaxe)
5. Execute a height command. (In my case, I use a heightmap from Aerios: https://drive.google.com/file/d/1pct3GQ4m2MRK0gB-uvvkZDLqqPd0KCcK/view).
I used the following command: "//br height -r 50 https://i.imgur.com/JoSyq0z.png 0.1 0.7"
6. See the error message.

**Plugins being used on the server**
Plugins (9): ArmorStandTools, BuildersUtilities, BuildSystem, craftFlowers, CustomHeads*, DecoHeads*, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint

**Closing words & proof**
In this [video](https://youtu.be/Fj4DBoWp1ZQ?t=119) by a YouTuber you can see some kind of "proof" that this command works on older versions. I have already asked on the Discord if this is really a bug and if I am just stupid. I have been referred here, I hope I am correct here.
Video: https://youtu.be/Fj4DBoWp1ZQ?t=119
![2020-10-10_16 49 11](https://user-images.githubusercontent.com/50241630/95658160-a9c03a00-0b18-11eb-9d82-b621f885db6b.png)

**Comment by SirYwell** [comment]
The error message is confusing, but rotation only allows **integer** values >= 0 and <= 360.

**Comment by nicokempe** [comment]
In this video you can see, that the command ("//br height 50 https://i.imgur.com/JoSyq0z.png 0.1 0.7 -r") worked on older FAWE versions: https://youtu.be/Fj4DBoWp1ZQ?t=119

**Comment by SirYwell** [comment]
I've seen the video. Do you know, what `0.1` stand for? What is the expected result? I didn't find anything other than the current implementation anymore.

**Comment by nicokempe** [comment]
I do not know. All I know is that the command doesn't work like it used to. I said that on the Discord and it was confirmed as a bug. Then I was referred here. To what extent do I know what the parameters of the command should be irrelevant or not?

**Comment by nicokempe** [comment]
Are there any updates on this problem? Can you already say how long it will take to fix it?

**Comment by nicokempe** [comment]
Is there anything new about the bug?

**Comment by Likqez** [comment]
Hey guys, I have encountered the same error on my paper spigot server(Build 325). Is this currently WIP?
