### ISSUE TITLE
Pasting over top of spawners and some other tile entities corrupts/resets them

### ISSUE THREAD

**Issue by Combustible** [IntellectualSites/FastAsyncWorldEdit#700]
# Bug report for FastAsyncWorldEdit 1.16.3 / 1.15.2 (reproducible on both)

**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/de62a1c082364332bf2d1ce33986fa21

**Required Information**
- FAWE Version Number: FastAsyncWorldEdit-1.16-414.jar
- Paper version git-Paper-"d151cf67a" (MC: 1.16.3) - Latest as of today
- Minecraft Version: 1.16.3

**Description of the problem:**
Pasting a spawner on top of itself will wipe the data from the spawner. This is easy to reproduce and happens every time. 

This happens in 1.15 and 1.16.3, with latest paper and latest FAWE. It also happens with brewstands and furnaces, but it's less obvious since they need to have something in them. Interestingly, this is *not* a problem with chests - it might be related to tile entities that tick themselves?

**How to replicate**:

- Put a spawner in the world. For example: 
```
/setblock ~ ~ ~ minecraft:spawner{MaxNearbyEntities:6s,RequiredPlayerRange:16s,SpawnCount:4s,SpawnData:{id:"minecraft:zombie"},MaxSpawnDelay:200s,Delay:-1s,SpawnRange:4s,MinSpawnDelay:200s,SpawnPotentials:[{Entity:{id:"minecraft:zombie"},Weight:1}]}
```
- Observe there's a zombie in it. Put it somewhere dark, it'll spawn every 10s.
- Select the spawner with FAWE
- //copy
- //paste the spawner on top of itself
- Note that now the spawner is either empty or a pig. It doesn't spawn anything anymore. If you f3+i the block, you get default data (a pig)
```
minecraft:spawner{MaxNearbyEntities:6s,RequiredPlayerRange:16s,SpawnCount:4s,SpawnData:{id:"minecraft:pig"},MaxSpawnDelay:800s,Delay:20s,SpawnRange:4s,MinSpawnDelay:200s,SpawnPotentials:[{Entity:{id:"minecraft:pig"},Weight:1}]}
```
- //paste again - and it's back to a zombie!
- //paste again - and it's wiped/a pig again
- etc. 

This is an important workflow on my game server where we "respawn" areas of the map using FAWE. We have been working around by basically doing `//replace spawner dirt` first but this is far from ideal and causes us other problems. 

**Plugins being used on the server:**

Plugins (24): Arceon, BKCommonLib, BungeeTabListPlus, CommandAPI, EpicStructureManagement, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, LibraryOfSouls, LightCleaner, LuckPerms, Monumenta, MonumentaRedisSync, MonumentaWarps*, NBTAPI, NBTEditor, PlaceholderAPI, PrometheusExporter*, ProtocolLib, ScriptedQuests, SpeedChanger*, Vault, VentureChat, VoxelSniper

This is reproducible with just FAWE alone but this is the full list to match the server I gathered the debug paste link from.

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Combustible** [comment]
Anything I can do to help with this? I'm actually really struggling right now as somehow the latest FAWE has made my hack replace-spawners-with-dirt-first fix not work as reliably - so getting this solved is of even more value to me. 

I'm really handy with plugin code, and have built and contributed to FAWE in the past - but I haven't figured out where to look on this one. I'd be happy to do some digging to get more info / try stuff if I had some idea how FAWE was updating tile entities like spawners to begin with...

**Comment by Combustible** [comment]
Figured out how to build a better hack to work around this (still setting spawners / brewstands / furnaces to dirt before pasting). So at least my server can continue with newest FAWE :) 

Still interested in seeing this fixed and willing to help if I can.

**Comment by Xaver106** [comment]
### Tested with:

- FastAsyncWorldEdit version 1.16-614;6bd866b
- git-Paper-457 (MC: 1.16.5)

The issue with the tile entitys looks like it is fixed. I tested commen inventory blocks (chest, furnace, brewing stand, etc.), the inventory stayed the same. With the spawners it looks like it is working (I used the spawner from above). The spawner is properly overwritten. The Spawners seem to be fixed as well. It can sometimes happen, theat the spawners, that get pasted over reset themselves. The resetted spawners stay in on chunk, the ones outside are usually not affected. The Spawners can just get pasted over to fix the problem.
