### ISSUE TITLE
ID and SubIds for newer Blocks in FaWe

### ISSUE THREAD

**Issue by SilverPhoenixx** [IntellectualSites/FastAsyncWorldEdit#704]
Hello,

my suggestion is not really a programming issue but a personally issue.
in exists IDs and SubIDs so we can use them for commands like //replace 1 3,5,5:2
Many people and i remember some ids to work efficence but in 1.13 and higher we dont have ids and subids.

WorldEdit have a command to see id from a block like: //info
"(FAWE) ......... (1:0) ...."
But you can only see ids from 1.12 Blocks.
1.13 higher blocks dont have that info in their message.

my suggestion is now:
Adding unique ids for blocks.
WorldEdit or some people make a "official fawe" or "global fawe" id list for new minecraft blocks.
so we can use //info to get their ids for better work.

That global list or fawe list dont must be accessible per website.
ingame per command is okay to get once their id to work with it.

Thank you for reading, sorry for my english :c

**Comment by N0tMyFaultOG** [comment]
Every block has an unique ID, their registered material name. Legacy IDs are still supported, but there is no need to add something for new materials or encourage the usage of them. They are legacy and could be removed in the future.

**Comment by MattBDev** [comment]
EngineHub has stated that sometime in the future they would like to remove the ability to use numerical block id's from WorldEdit and I completely support that decision. Once WorldEdit removes that stuff, we will be doing the same. Like NotMyFault said, "we don't need to add something for new materials".
