### ISSUE TITLE
Chests are empty after //undo

### ISSUE THREAD

**Issue by kikelkik** [IntellectualSites/FastAsyncWorldEdit#708]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:  https://athion.net/ISPaster/paste/view/fb186347b42242769be283fbf5bc20b3

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-421;5508b41
- Spigot/Paper Version Number (`/version`):      git-Paper-231
- Minecraft Version: [e.g. 1.16.3]     1.16.3

**Describe the bug**
Chests are empty after undoing an action.

**To Reproduce**
[A]
1. Place a chest
2. Fill in any item
3. //stack 10 that chest
4. //undo
5. The chest is now empty
6. //redo
7. The other 10 chests are invisible (just showing hitboxes) and empty.

[B]
1. Create a large field (120x120) with filled chests
2. //set 0 while standing on a corner of that area so you can't see some parts
3. All chests are invisible (just showing hitboxes) and empty.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
`5. The chest is now empty` Not in my test, but maybe it's dependent on other details.

`7. The other 10 chests are invisible (just showing hitboxes) and empty.` Right, it's invalid and so a hided block. If I opened a chest, the block get an update and I see it again, but the inventory is still empty.


![2020-11-22_23 06 27](https://user-images.githubusercontent.com/4140635/99918504-a1fad480-2d17-11eb-9112-b7c412c82813.png)

_tested with 1.16-444;fbc972f on MCPaper 288, 1.16.4_
