### ISSUE TITLE
Heightmap not working

### ISSUE THREAD

**Issue by ImperatusMaximus** [IntellectualSites/FastAsyncWorldEdit#709]
[
![Heightmapinterface](https://user-images.githubusercontent.com/71344054/96335528-944b9280-1079-11eb-977e-1dc7dd132ad8.PNG)
](url)

when i type //heightmapinterface ingame it won't work.
What am i doing wrong?

**Comment by IronApollo** [comment]
Please do not delete the issue template. Feel free to recreate your issue with the template.
