### ISSUE TITLE
Players can copy other plots with PlotSquared

### ISSUE THREAD

**Issue by zPirroZ3007** [IntellectualSites/FastAsyncWorldEdit#710]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/11056cbdfc104295a81771879eaf368f

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-422
1.- Spigot/Paper Version Number (`/version`):     git-Paper-387
- Minecraft Version: 1.15.2/1.16.3

**Describe the bug**
Just try to set the pos1 in your plot and then set the pos2 with //pos2 outside your plot, then //copy and then //paste, everything will be copied even the plot road, with every players' plot in the selection. (Doesn't work at first try you will have to try it a couple of times).

**To Reproduce**
See above.

**Plugins being used on the server**
Plugins (31): **Arceon**, **BuildersUtilitiesReloaded**, **EpicRename**, **Essentials**, **EssentialsChat**, **EssentialsProtect**, **EssentialsSpawn**,  **(WorldEdit)FastAsyncWorldEdit**, **FeatherBoard***, **goBrush**, **goPaint**, **HeadDatabase***, **ID-Library**, **IllegalStack**, **LuckPerms**, **Marriage**, **Multiverse-Core**, **MVdWPlaceholderAPI***, **PlaceholderAPI**, **PlotSquared**, **PlugMan**, **ProtocolSupport**, **spark**, **TAB**, **TecnoCreative**, **TecnoUtils**, **Vault**, **ViaVersion**, **VoxelSniper**, **WorldEditSUI**, **WorldGuard**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by xion87** [comment]
i confirm the issue, happen to my creative server too with latest version of fawe and plotsquared premium (1.16.3)

**Comment by zPirroZ3007** [comment]
I'm sure that this issue's priority is URGENT, is it possible that **AFTER A MONTH** no one did verify this issue?

**Comment by aurorasmiles** [comment]
You're free to check the code for yourself, if the team currently has no time don't expect stuff. We don't get paid for this.

**Comment by Malachiel87** [comment]
make it premium if you don't care

**Comment by SirYwell** [comment]
While we do care, even making the plugin paid wouldn't magically give us more time. It is clearly stated that current builds aren't meant for production servers for a reason.

**Comment by Malachiel87** [comment]
its alpha from years and you keep alpha everyitime you change server version :) it will be NEVER stable

**Comment by aurorasmiles** [comment]
This is not the place to discuss this. FAWE is open source, everyone who has time can help develop it.
