### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by variationtime** [IntellectualSites/FastAsyncWorldEdit#711]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
 https://athion.net/ISPaster/paste/view/65103ae0f6a3410187fb1b0718cf9caa

**Required Information**
- FAWE Version Number - build 420
- Spigot/Paper Version git-Paper-"53122f37" 
- Minecraft Version: paper 1.16.3

**Describe the bug**
After many same messages server get crashed, i post entiry crash log bellow
https://pastebin.com/sKru0tsr

**To Reproduce**
idk

**Plugins being used on the server**
http://prntscr.com/v2vimr

**Checklist**:

- X I included all information required in the sections above
- X I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- X I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- X I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update Fawe and Paper.
Note: If you fill out the checklist, put the "X" between the [].
