### ISSUE TITLE
can't save schematics to symbolic links

### ISSUE THREAD

**Issue by Ivan8or** [IntellectualSites/FastAsyncWorldEdit#716]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/cfee312cf8694baa9192086654231732

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):    422
- Spigot/Paper Version Number (`/version`):  232
- Minecraft Version: [e.g. 1.16.3]     1.16.3

**Describe the bug**

**
Preface:
I'm running minecraft within a docker container, which could feasibly affect this (maybe?)

When I create a symbolic link named 'schematics' to replace the schematics folder, FAWE will either say "could not create folder for schematics" or "Path is outside allowable root"
The link points to an existing directory on the same mount as the server directory
when I view the filesystem, I can see that the directory the link points at is accessible - I even created it from within the container to no avail.
**

**To Reproduce**

get a papermc server going on a linux machine (I'm using CentOS 8)
create a soft link named "schematics" to replace FAWE's schematics folder, and point it elsewhere in the file system
log on, //copy something and try to /schematic save  

**Plugins being used on the server**

BungeeTabListPlus, ContainerMenu (self-made; a server selector gui), FAWE, LuckPerms, MemCheck, MultiChat, Vault

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
![image](https://user-images.githubusercontent.com/10080017/96742480-e4e52780-13ba-11eb-99ea-11d958724f58.png)
