### ISSUE TITLE
FAWE Snapshot 1.15.2 doesn't work with Worldguard

### ISSUE THREAD

**Issue by JohniUYS** [IntellectualSites/FastAsyncWorldEdit#720]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: Cannot run, i get the following error: https://paste.sentinalcoding.eu/EBPrc5N4Mr

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     FastAsyncWorldEdit version 1.16-427;478ab16
- Spigot/Paper Version Number (`/version`):     This server is running CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
- Minecraft Version: [e.g. 1.16.3]     1.15.2

**Describe the bug**
When downloading the latest snapshot for 1.15.2 and adding the Worldguard for 1.15.2 I get an error saying that WorldEdit wasnt found by Worldguard therefore worldguard doesnt start.

**To Reproduce**
1. Download Fawe for 1.15.2
2. Download Worldguard for 1.15.2
3. Install the Plugins
4. Start the Server.

**Plugins being used on the server**

FastAsyncWorldEdit, Multiverse-Core, (MISSING/NOT WORKING) Worldguard

**Checklist**:

- [X] I included all information required in the sections above 
- [X] I made sure there are no duplicates of this report [(Use Search)] (https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue) 
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/) 
* I Need 1.15.2 its a custom plugin a friend wants.
- [X] I made sure the bug/error is not caused by any other plugin 
* Yes, I removed all plugins except FAWE and Worldguard

**Comment by aurorasmiles** [comment]
Please provide a full log

**Comment by JohniUYS** [comment]
Will do, But will take a bit, as i am not at home rn please dont close this.

**Comment by JohniUYS** [comment]
Okay, I got it this is the Log: https://paste.sentinalcoding.eu/y0098kx0Wf

**Comment by N0tMyFaultOG** [comment]
Build Spigot/Switch to Paper. Your version used is outdated and does not support methods Fawe relies on.
