### ISSUE TITLE
Selection above ~15.000 blocks creates error with stack

### ISSUE THREAD

**Issue by simonbison01** [IntellectualSites/FastAsyncWorldEdit#722]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/ad421e81364a4165986ea746d48d5a8d

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):    1.16-403;f71ca32
- Spigot/Paper Version Number (`/version`):    git-Paper-215  
- Minecraft Version:    1.16.3

**Describe the bug**
As soon as my selection is larger than ~15.000 blocks and I try to stack it downwards with //stack 30 -a, on every letter I type I get the message "Your selection is large...". After executing stack and //confirm, the error you see in the debugpaste file.

**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

ArmorStandTools, BuildersUtilities, craftFlowers, eBackup, Essetials, Fawe

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Thanks for the report. I'll try to fix this soon.

**Comment by dordsor21** [comment]
Seems to be fixed
