### ISSUE TITLE
Players can use VoxelSniper anywhere in a plot world

### ISSUE THREAD

**Issue by so-ssh** [IntellectualSites/FastAsyncWorldEdit#725]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
**config.yml**: https://pastebin.com/DSVWyNKx
**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/e7670432bbd2467b958ab737f480528e
**LuckPerms permissions setup:** https://user-images.githubusercontent.com/66318502/97780732-0dc1a580-1b8f-11eb-910e-c947f00828f9.png

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     FAWE version 1.16-427
- Spigot/Paper Version Number (`/version`):     Paper build 244
- Minecraft Version: 1.16.3

**Describe the bug**
When given the `fawe.voxelbrush` permission node players become able to use the functionality of VoxelSniper's tools outside of their own claimed plots on a plot world, however other WorldEdit functionality is restricted to their claimed plots.

**To Reproduce**
1. Install FAWE and VoxelSniper-flattened
2. Create a plot world with PlotSquared
3. Give a player the permissions `fawe.permpack.basic` and `fawe.voxelbrush`

**Plugins being used on the server**
Shown in the debug paste.

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You're not using FAVS.
