### ISSUE TITLE
Mask Restrict to specific terrain angle

### ISSUE THREAD

**Issue by Darkvodou** [IntellectualSites/FastAsyncWorldEdit#727]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/b3d7501be18242b285bf998d22b1599b

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-427;478ab16
- Spigot/Paper Version Number (`/version`): git-Paper-238 1.16.3
- Minecraft Version: [e.g. 1.16.3] : 1.16.3

**Describe the bug**
Mask like /[0d][50d] doesn't work, it will replace all the selection you take and replace it

**To Reproduce**
1. Select a region
2. Send the command : "//replace /[0d][50d] 1:3"
4. See the result on a mountain

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
Seems to be an issue with the //replace command. Works when using //gmask (or //mask for brushes).
