### ISSUE TITLE
It doesn't work properly on paper-251

### ISSUE THREAD

**Issue by BecodReyes** [IntellectualSites/FastAsyncWorldEdit#731]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
No configuration Files
- FAWE Version Number: `1.16-431;781c1e9` 
- Spigot/Paper Version Number: `git-Paper-251`   
- Minecraft Version: `1.16.3`

**Describe the bug**
It doesn't work properly on paper-251

**Console return**
https://pastebin.ubuntu.com/p/dFdZt4qWYX/

**Resolvent**
After my tests, the latest version of worldedit works
Synchronize upstream worldedit repository
I've tried, but I've never done anything like that before, so I can't make it

**Checklist**:
- [X] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
> No configuration Files
We literally said it's required. Follow the template and file a new issue.
