### ISSUE TITLE
Doesn't work with paper-251

### ISSUE THREAD

**Issue by BecodReyes** [IntellectualSites/FastAsyncWorldEdit#732]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste** Cannot run, I get the following error: https://pastebin.ubuntu.com/p/CZPwJMnG26/

**Required Information**
- FAWE Version Number: `1.16-431;781c1e9` 
- Spigot/Paper Version Number: `git-Paper-251`   
- Minecraft Version: `1.16.3`  

**Describe the bug**
It doesn't work properly on paper-251

**To Reproduce**
1. Download the latest version of FAWE
2. Download paper-251
3. Install the Plugins
4. Start the Server.
5. Use commands, like //set
6. See error: https://pastebin.ubuntu.com/p/jWnZh7sSjN/

**Plugins being used on the server**

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Please provide your complete startup log

**Comment by BecodReyes** [comment]
Plugin conflict, close this issue temporarily
