### ISSUE TITLE
Error messages whenever using FAWE wand or schematic commands.

### ISSUE THREAD

**Issue by HenrikoMagnifico** [IntellectualSites/FastAsyncWorldEdit#735]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
https://athion.net/ISPaster/paste/view/8e05961e112d48a7a1a8661319691df2

**Console error message:** https://hastebin.com/arusofikag.rb

**Required Information**
- FAWE Version Number: 1.16-433;0a233e8
- Spigot/Paper Version Number: git-Paper-259
- Minecraft Version: 1.16.4 

**Describe the bug**
Error messages in chat whenever I try to use the wand or schematic commands in FAWE.

**To Reproduce**
Use the plugin on PaperMC 1.16.4 and using FAWE.

**Plugins being used on the server**
None others.

**Comment by aurorasmiles** [comment]
FAWE is not updated to 1.16.4 yet, see #734
