### ISSUE TITLE
Patern Fullcopy doesn't work

### ISSUE THREAD

**Issue by Darkvodou** [IntellectualSites/FastAsyncWorldEdit#736]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:https://athion.net/ISPaster/paste/view/aeb966bf04b444d8bfac3822f7ceff80

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-434:49052d7
- Spigot/Paper Version Number (`/version`): git-Spigot-57bbdd8-dea4138 (MC:1.16.3)
- Minecraft Version: 1.16.3   

**Describe the bug**
The patern is not recognize as a patern 

**To Reproduce**
1. Create schematics and put it on a folder ( mine are in ./plugins\FastAsyncWorldEdit\schematics\veg\tree\dead_tree )
2. Try use the patern fullcopy on a command like : /br scatter #fullcopy[veg/tree/dead_tree/][true] 1 1 1
3. See error

**Plugins being used on the server**

FastAsyncWorldedit ( WorldEdit )

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
Adding some additional information
![](https://i.imgur.com/dz5vT7B.png)
Looks like Fawe doesn't even give you the chance to input a schematic before complaining it doesn't exist.
