### ISSUE TITLE
EntityTypes WE dont same with EntityType bukkit

### ISSUE THREAD

**Issue by OriginalPhizzle** [IntellectualSites/FastAsyncWorldEdit#737]
Im coding a plugin and when write EntityType.valueOf(#entity from region with EntityTypes), EntityTypes.ITEM dont same with bukkit EntityType.DROPPED_ITEM, and same with EntityTypes.LEASH and other items

**Comment by aurorasmiles** [comment]
Please follow the template. We can't help you without any information
