### ISSUE TITLE
With a command //move, I can break roads between plots

### ISSUE THREAD

**Issue by Birsenberg** [IntellectualSites/FastAsyncWorldEdit#738]
1.16.3 core

fawe debugpaste: https://athion.net/ISPaster/paste/view/5652785ee90443198586741e40605e9d

Required Information
- FAWE Version Number: 435 build
- PlotSquared Version Number: 5.13.8
- Spigot/Paper Version Number: 1.16.3   
- Minecraft Version: 1.16.3

With a command //move, I can break roads between plots. Video: https://youtu.be/suO_2JUdBD0
This bug work only with a lot of blocks and Fawe. With WorldEdit it not work.
Video with fawe - https://youtu.be/YD1elhRao3g
Video with worldedit - https://youtu.be/pybV__l061E
The bug works with any permissions plugin.
I tested fawe build 406 and 435. Bug works on both.

**Comment by aurorasmiles** [comment]
com.boydti.fawe.object.exception.FaweException: Low memory
Maybe that is a cause of the issue

**Comment by Birsenberg** [comment]
I have allocated more memory to the server. It did not help. It was 4, and I installed 6.

**Comment by hhenrichsen** [comment]
I've confirmed this issue on two other servers. We've taken away `//move` for the time being, but it'd be cool to see this fixed.

**Comment by craftyfoxe** [comment]
I have the same issue

**Comment by braceyourself07** [comment]
This appears to still be an issue with the latest PlotSquared (v5 premium) and the latest build of FAWE as of 8 Dec 2020.  To further give analysis on this bug, it appears that blocks can be moved outside of the plot as long as a portion of the selection remains within the plot.

**Comment by Owen1212055** [comment]
I can confirm that this is an issue while using a custom CuboidRegion FaweMask.
