### ISSUE TITLE
Server crash for stackoverflow

### ISSUE THREAD

**Issue by Noiknez** [IntellectualSites/FastAsyncWorldEdit#739]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/9b88325d437d4ecb95e69ef5640350b0

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 427 (debugpaste show the updated version)
- Spigot/Paper Version Number (`/version`): git-Paper-152 (MC: 1.16.2)     
- Minecraft Version: 1.16.2     

**Describe the bug**

The log is over 1 Gb so I attached screenshot and windows can't let me copy the log into an haste website

The bug is FAWE that had fill out all the memory dedicated to fawe
![image](https://user-images.githubusercontent.com/20723083/98445847-4119ac80-211a-11eb-8c91-b25e0f4e9c6d.png)

After the first message, the error continue
![image](https://user-images.githubusercontent.com/20723083/98446022-57743800-211b-11eb-8380-ad789c4296b9.png)

**To Reproduce**
1. Let run the server for multiple hour with FAWE commands 
2. See error

**Plugins being used on the server**

ArmorStandEditor, Autorank, BKCommonLib, Builders-Utilities, BungeeTabListPlus, Citizens, CraftingStore, Denizen, Depenizen, DiscordSRV, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, HolographicDisplays, IPWhitelist*, LightCleaner, LuckPerms, Multiverse-Core, PlaceholderAPI, Plan, PlotSquared, ProtocolLib, spark, Vault, ViaBackwards, ViaVersion, VoxelSniper, WorldBorder, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Reopen the issue if you reproduced that with up to date software. For further notice, use paste services to share logs.

**Comment by Noiknez** [comment]
I will do this. I have pasted this message to express my difficulty with a log of more that 1GB and limitation
``The log is over 1 Gb so I attached screenshot and windows can't let me copy the log into an haste website``
