### ISSUE TITLE
"This schematic version is currently not supported"

### ISSUE THREAD

**Issue by TofPlays** [IntellectualSites/FastAsyncWorldEdit#740]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/192f9073f75b4cf4b2a29190829c6c9e
The error that shows up on trying to load the .schem: https://haste.athion.net/cataqujesi.md

**Required Information**
- FAWE Version Number: FAWE-1.16-435 
- Spigot/Paper Version Number: CraftBukkit version git-Spigot-37d799b-bc6a175 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)    
- Minecraft Version: 1.16.4    
- Schematic file: 
[towncaleb.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/5505220/towncaleb.zip)

**Describe the bug**
A .schem format schematic isn't able to load on clipboard.

**To Reproduce**
1. Save a schematicName.schem file with 1.14.4 (not sure if 1.14.4 is required to reproduce it)
2. In 1.16.4 use command: "//schematic load schematicName.schem"
3. See this error in-game:
![image](https://user-images.githubusercontent.com/33004077/98447900-f14edb80-2141-11eb-85eb-d994059e9b2d.png)
4. See this console error: https://haste.athion.net/cataqujesi.md

Side note:
I saved several schematics from 1.14.4 server to try and paste into the 1.16.4, However some loaded and pasted without issues, while the others, like the "towncaleb.schem", couldn't load. This "townarcane.schem" is an example of one of the schematics that did manage to load without a problem: 
[townarcane.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/5505226/townarcane.zip)

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Please provide us with one of the schematics that would not load.

**Comment by aurorasmiles** [comment]
See the first schematic in that issue

**Comment by MattBDev** [comment]
@aurorasmiles I missed that while reading. thanks.
