### ISSUE TITLE
crash server, for the command gmask ? (with log)

### ISSUE THREAD

**Issue by Noiknez** [IntellectualSites/FastAsyncWorldEdit#741]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:

https://athion.net/ISPaster/paste/view/fa07363e8b954e1ebf06165aea5c1b39

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-435;49052d7
- Spigot/Paper Version Number (`/version`): Paper version git-Paper-262 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) 
- Minecraft Version: 1.16.4

**Describe the bug**

The bug is a server crash maybe from the command gmask from the log ?

Paste from the error : https://pastebin.com/UVCpEuUi

**Plugins being used on the server**

ArmorStandEditor, Autorank, BKCommonLib, Builders-Utilities, BungeeTabListPlus, Citizens, CraftingStore, Denizen, Depenizen, DiscordSRV, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, HolographicDisplays, IPWhitelist*, LightCleaner, LuckPerms, Multiverse-Core, PlaceholderAPI, Plan, PlotSquared, ProtocolLib, spark, Vault, ViaBackwards, ViaVersion, VoxelSniper, WorldBorder, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
This is gopaint using FAWE from the main thread. Not gmask or FAWE.
