### ISSUE TITLE
Plot Schematics not placing correctly in PlotSquared with FAWE and set block timer issue.

### ISSUE THREAD

**Issue by SirCraftypants** [IntellectualSites/FastAsyncWorldEdit#743]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

https://athion.net/ISPaster/paste/view/f67beb86a53f492e900fa4cd9c5edab5

https://paste.helpch.at/inibelevov.bash
https://paste.helpch.at/ikikeqisot.bash

**/fawe debugpaste**:

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16 #432
- Spigot/Paper Version Number (`/version`):     Paper 1.15.2
- Minecraft Version: [e.g. 1.16.4]     1.15.2

**Describe the bug**
When i ran /plot delete in a Plot with PlotSquared, FAWE pasted the Plot Schematic 1 block sideways and 1 block lower than it should have. Then when i tried to run /plot delete again it informed me that the plot or myself had to wait because of a set block timer. I restarted the server and tried to /plot delete again and it again said i had to wait for a set block timer.

**To Reproduce**
1. Run  FAWE and PlotSquared v5
2. create a Plot Schematic and install it in PlotSquared
3. Claim a plot
4. Stand in the claimed Plot and run /Plot Delete
5. Claim the Plot a second time and run /Plot Delete a second tim
6. the Schematic should be wrongly pasted offset by 1 block and 1 block too low.
7. try to /plot Delete again and you should get the same set block timer issue.

**Plugins being used on the server**
PlotSquared V5
FAWE 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

I can not update to 1.16 until all my plugins are 1.16 compatible, i did everything else.

**Comment by dordsor21** [comment]
Is this still an issue?
