### ISSUE TITLE
Server thread dump

### ISSUE THREAD

**Issue by Heliosard** [IntellectualSites/FastAsyncWorldEdit#744]
**/fawe debugpaste**
https://athion.net/ISPaster/paste/view/6635dea6066c4f52956e5785a1fedfce

**Required Information**
- FAWE Version Number: 1.16-437
- Spigot/Paper Version Number: git-paper-267
- Minecraft Version: 1.16.4
- goBrush Version: 3.6.1
- gopaint Version: 2.3.1

**Describe the bug**
I found for the second time a crash caused by goBrush/FAWE.
https://gist.github.com/Heliosard/7ed335359a7a37cc879b150b8f7edd14

Thank you for your time on this issue.
I remain at your disposal.

PS: I apologize if this error is caused by goBrush and not FAWE.

**Comment by Heliosard** [comment]
New crash: https://gist.github.com/Heliosard/055b900b53653b88a677120848204916

**Comment by Heliosard** [comment]
Hi,
Can you help us with this constraining problem?

Thanks.

**Comment by dordsor21** [comment]
gobrush is using FAWE on the main thread
