### ISSUE TITLE
FaweAPI.fixLighting() server crash

### ISSUE THREAD

**Issue by Pugabyte** [IntellectualSites/FastAsyncWorldEdit#745]
**FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/74b53451f72f461383ff6cc851bfbf7f

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 
![image](https://user-images.githubusercontent.com/12417961/99025847-cac0e400-2537-11eb-9d53-a6f7fc6c6eba.png)
- Spigot/Paper Version Number (`/version`):     
![image](https://user-images.githubusercontent.com/12417961/99025983-12477000-2538-11eb-9b89-ff89757e9e9b.png)
- Minecraft Version: 1.16.4     

**Describe the bug**
Server crash when using FaweAPI.fixLighting(): https://paste.bnn.gg/amifi

```Tasks.wait(10, () -> FaweAPI.fixLighting(worldEditWorld, region, null, RelightMode.ALL));```

**Comment by dordsor21** [comment]
Do not use any FAWE anything from main thread. You run the risk of deadlocking yourself (case in point ^^).
