### ISSUE TITLE
Natural warped roots not appearing in //count or //distr

### ISSUE THREAD

**Issue by Pugabyte** [IntellectualSites/FastAsyncWorldEdit#747]
**FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/74b53451f72f461383ff6cc851bfbf7f

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 
![image](https://user-images.githubusercontent.com/12417961/99025847-cac0e400-2537-11eb-9d53-a6f7fc6c6eba.png)
- Spigot/Paper Version Number (`/version`):     
![image](https://user-images.githubusercontent.com/12417961/99025983-12477000-2538-11eb-9b89-ff89757e9e9b.png)
- Minecraft Version: 1.16.4

**Describe the bug**
Natural or bonemealed warped roots not shown when using //count or //distr; WorldEdited warped roots will show on //distr, but not on //count

**Comment by RedstoneFuture** [comment]
![2020-11-22_22 57 49](https://user-images.githubusercontent.com/4140635/99918321-60b5f500-2d16-11eb-8039-391b5683ce34.png)

Right. At my test it was analyzed as AIR.

_tested with 1.16-444;fbc972f on MCPaper 288, 1.16.4_

**Comment by aurorasmiles** [comment]
confirmed with 1.16-460 on Paper 323
