### ISSUE TITLE
Can bind brushes to blocks but cannot unbind them

### ISSUE THREAD

**Issue by Pugabyte** [IntellectualSites/FastAsyncWorldEdit#748]
**FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/74b53451f72f461383ff6cc851bfbf7f

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 
![image](https://user-images.githubusercontent.com/12417961/99025847-cac0e400-2537-11eb-9d53-a6f7fc6c6eba.png)
- Spigot/Paper Version Number (`/version`):     
![image](https://user-images.githubusercontent.com/12417961/99025983-12477000-2538-11eb-9b89-ff89757e9e9b.png)
- Minecraft Version: 1.16.4

**Describe the bug**
Can bind brushes to blocks but cannot unbind them

```
Hold block
/br sphere purple_stained_glass 3
/br none
```

**Comment by aurorasmiles** [comment]
Have you tried /tool none ?

**Comment by Pugabyte** [comment]
Same result
