### ISSUE TITLE
Cannot use /tree when not in direct sunlight

### ISSUE THREAD

**Issue by terakasel** [IntellectualSites/FastAsyncWorldEdit#750]
This used to not be a problem but now I cannot place trees underground/under overhangs, or anywhere where its not within direct sunlight.  It tells me "I tree cannot go there" and is a serious issue for me considering many of my builds rely on having trees underneath terrain or structures.

Thanks in advance
-Kasel

**Comment by terakasel** [comment]
Development.  It appears it DOES place the tree when I go to place it in a "cave" but instead of putting in where I chose, it puts it up on TOP of the cave. (Above me on the surface).

**Comment by aurorasmiles** [comment]
In the future please do not remove the template.
Confirmed with 1.16-460 on paper 323

**Comment by dordsor21** [comment]
This is not something that we can fix. It ultimately uses Bukkit itself to generate the trees.
