### ISSUE TITLE
a simple //maze maybe

### ISSUE THREAD

**Issue by Speeder323** [IntellectualSites/FastAsyncWorldEdit#752]
**Describe the solution you'd like**
you select an area, you type //maze oak_leaves, and it creates a maze in your selection. simple enough, i hope?

**Describe alternatives you've considered**
Plugins such as TangledMaze: takes a long time just to set up a simple maze, has a small size limit and is just generally annoying to get what you want
Making it by hand: thats why i want a command in the first place, since it takes hours to make one
Using MCEdit Filters: mcedit isn't even available for 1.16

**Additional context**
not really.. maybe if you feel fancy you could add path width and wall thickness settings?

**Comment by ThatOneJose95** [comment]
please dont make it only using equations

**Comment by N0tMyFaultOG** [comment]
Use the maze.js craftscript. It does exactly what you described. Or modify it to your needs.
