### ISSUE TITLE
hcyl thickness

### ISSUE THREAD

**Issue by omuhu** [IntellectualSites/FastAsyncWorldEdit#753]
**Is your feature request related to a problem? Please describe.**
I often need to create hcyls with a thickness, I do so like this:
//hcyl <some_material> <some_radius>
//hcyl <some_material> <some_radius + x>
//fill (between the two hcyls)
![hcyl](https://user-images.githubusercontent.com/48032844/99699209-ebfd6500-2a4e-11eb-8fb1-04370c324bba.png)

This is especially cumbersome when the thickness is too small to use just one fill.
![hcyl_2](https://user-images.githubusercontent.com/48032844/99699416-27982f00-2a4f-11eb-9878-dcc70c548663.png)

**Describe the solution you'd like**
//hcyl <material> <radii: N/S,E/W,thickness> [height]
and
//hcyl <material> <radii: N/S,E/W,N/S thickness, E/W thickness> [height]

In this example and the alternatives, thickness could either be: 
how many blocks thick the hcyl is OR the outer radius
I prefer outer_radius because that would give the option of having thickness go inwards with something like this:
//hcyl 57 12,12,10 (shown below)

The example below is using outer radius, not thickness:
Ex: //hcyl 57 10,10,12 OR //hcyl 57 12,12,10
![hcyl](https://user-images.githubusercontent.com/48032844/99699209-ebfd6500-2a4e-11eb-8fb1-04370c324bba.png)

**Describe alternatives you've considered**
This is good too, but it requires you to put the height in.
//hcyl < material> < radii> [height] [thickness]

This is worse, it changes the order of the arguments from how it is now and would be confusing. It would also be quite cumbersome to have to provide the thickness to use height.
//hcyl < material> < radii> [thickness] [height] 

**Additional context**
N/A

**Comment by dordsor21** [comment]
`//hcyl <N/S,E/W> [height] [thickness]` to avoid disparity with standard WorldEdit
