### ISSUE TITLE
Waterlog blocks through masks?

### ISSUE THREAD

**Issue by simonbison01** [IntellectualSites/FastAsyncWorldEdit#754]
**Is your feature request related to a problem? Please describe.**
So far, I do not see any possibility to waterlog every waterloggable block by commands, which would be especially helpful to create detailed under-water builds.

**Describe the solution you'd like**
I think, Worldedit theoretically already features the right masks.
But whenever I try
`//replace #existing ^=[waterlogged=true]`
it doesn't seem to work.
My goal is to influence the waterlogged state for a specific selection of blocks.

**Describe alternatives you've considered**
I did not find any related solutions to this and I do not know if that's just a worldedit given bug or a feature you could actually add.

**Comment by SirYwell** [comment]
`//replace #existing ^[waterlogged=true]` is the command, as described [here](https://worldedit.enginehub.org/en/latest/usage/general/patterns/).
