### ISSUE TITLE
Weird block names on WG blacklist deny messages

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/FastAsyncWorldEdit#756]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/cb812cccaddc4c689709d5920b5e1823

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-444;fbc972f
- Spigot/Paper Version Number (`/version`): This server is running Paper version git-Paper-288 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Minecraft Version: 1.16.4

**Describe the bug**
Weird block names when I use WorldGuard blacklist.txt to deny place specific blocks.

**To Reproduce**
1. Setup a block deny place and tell on blacklist.txt.
Example:
```
[TNT]
on-place=deny,tell
```
2. Try place down the blocked block.
3.
FAWE + WG write this:
`You're not allowed to place TranslatableComponentImpl{key=block.minecraft.tnt, args=[], children=[], style=Style{color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}}.`

Normal WE + WG write this:
`You're not allowed to place TNT.`

**Plugins being used on the server**

Plugins (15): ChestShop, CS-CoreLib, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, LuckPerms, Multiverse-Core, NoCheatPlus, PlugMan, ProtocolLib, Slimefun, Vault, WorldEdit, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Xaver106** [comment]
Can recreate the issue on version 558

**Comment by MattBDev** [comment]
@Xaver106 @andris155 Is this still an issue?

**Comment by andris155** [comment]
Yes, is still.
<img width="484" alt="Screenshot 2021-07-31 105414" src="https://user-images.githubusercontent.com/8324198/127734703-3dce47e3-c565-4c1b-a8c5-072a7b081709.png">

**Comment by andris155** [comment]
Tested with FastAsyncWorldEdit version 1.17-97;e1d18dc and Paper 1.17.1 build 138

**Comment by SirYwell** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockType.java#L132 this should be the same as in WE https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockType.java#L117
