### ISSUE TITLE
somestimes not all AIR blocks are counted with //distr

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/FastAsyncWorldEdit#759]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/55e0ec44b9934625a3b77ad9c97461f9

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-444;fbc972f
- Spigot/Paper Version Number (`/version`): PaperMC 288
- Minecraft Version: 1.16.4]    

**Describe the bug**
Sometimes the total count of all distributes blocks are wrong:

![2020-11-22_22 36 50](https://user-images.githubusercontent.com/4140635/99917922-dff5f980-2d13-11eb-9c90-4825a3dbf4eb.png)

The 3960 blocks are right, based on the selection size. I have 3677 AIR blocks (described as "LUFT" because my client language is german ^^ ), but `//distr` counted only 3443, so the total count number are wrong too.

If I use `//set stone` and `//undo`, after `//distr` the AIR count are right. Idk why.

![2020-11-22_22 50 16](https://user-images.githubusercontent.com/4140635/99918162-6a8b2880-2d15-11eb-8343-771ff7b08b26.png)

**To Reproduce**

1. select a cuboid region
2. with //pos2 your get an total block amount in the chat line
3. use //distr
4. compare the block count and maybe it's different
5. use //set stone
6. //undo
7. with //distr - the AIR count are right in my test

![2020-11-22_22 39 07](https://user-images.githubusercontent.com/4140635/99917916-d79dbe80-2d13-11eb-9cab-309c9e3d848a.png)

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
Seems like empty chunk sections are ignored
