### ISSUE TITLE
Nullpointer on tracemask command

### ISSUE THREAD

**Issue by FluxedScript** [IntellectualSites/FastAsyncWorldEdit#760]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:

https://athion.net/ISPaster/paste/view/e06d46bb0c344cbfbed5cd55c14b3e45

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-446;11f50f8
- Spigot/Paper Version Number (`/version`):   paper 1.16.4 R0.1
- Minecraft Version: [e.g. 1.16.4]     

**Describe the bug**
Cannot execute trackmask water to avoid the water when using brushes 

**To Reproduce**
1. Select hand that isn't a fawe tool
2. Execute '/tracemask water'
3. Go to console as instructed

**To Not Reproduce Error**
1. Select shovel
2. Execute '/br s sand'
3. '/tracemask water'
4. Now it should work

**Plugins being used on the server**

AdvancedBan, AnimatedScoreboard, ChestShop, CleanroomGenerator, CoreProtect, DiscordSRV, Essentials, EssentialsChat, FAWE, HolographicDisplays, LagAssist, leaderHeadsRevamped, LuckPerms, Multiverse-Core, PlaceholderAPI, PlugMan, ProtcolLib, Spartan, Vault, VoxelSniper

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

One fix is to detect if the player is holding an item that is a tool as anything other than a tool generates the error. This can be linked to #748 with a check being written for both.

**Comment by dordsor21** [comment]
This seems to be fixed now?
