### ISSUE TITLE
NPE caused by BukkitAdapter

### ISSUE THREAD

**Issue by occydaboss** [IntellectualSites/FastAsyncWorldEdit#761]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/6839846d0632499b8690cef1cc6266f3

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-446;11f50f8
- Spigot/Paper Version Number (`/version`):     git-Paper-291
- Minecraft Version: [e.g. 1.16.4]     1.16.4

**Describe the bug**
Whenever I try to use a BukkitAdapter to cast a Bukkit world to a WorldEdit world it throws an NPE (https://paste.md-5.net/uvipewogog.bash). Here is my code: https://paste.md-5.net/derafetozo.java

**To Reproduce**
1. Download and compile https://github.com/occydaboss/SkyBlock
2. Run /is
3. Check the console for the stack trace.

**Plugins being used on the server**

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Your plugin has no pom or gradle build skript, how are we supposed to compile it?

**Comment by occydaboss** [comment]
> Your plugin has no pom or gradle build skript, how are we supposed to compile it?

Ah, with intellij. If you add FAWE 1.16 446 and worldedit 720 as modules then build it it will work.
I should really switch to maven shouldn't I...

**Comment by occydaboss** [comment]
Resolved. I used maven and it works now.
