### ISSUE TITLE
crash server PlotSquared 

### ISSUE THREAD

**Issue by YunoOkamii** [IntellectualSites/FastAsyncWorldEdit#765]
**/fawe debugpaste**:

https://athion.net/ISPaster/paste/view/7c95b08ded1340e191874581b551a348

**Required Information**
- FAWE Version Number (`FastAsyncVoxelSniper-flattened-1.0.3-backward.jar`):     
- Spigot/Paper Version Number (`Paper(251) 1.16.3-R0,1-SNAPSHOT`):     
- Minecraft Version: [1.16.3]     

**Describe the bug**

The server gives me a Time out error when I execute commands to delete a plot here a player tried to crash our server with multiple entities so I executed the command /plot clear is this happens every time we want to delete a plot

**To Reproduce**
1. Run  to '/plot clear or /plot delete'
2. the server no longer responds is restarted

**Plugins being used on the server**

BuildersUtilitiesReloaded, Citizens, CloudNet-Bridge, CMI, CMIPaperLib, CoreProtect, DeluxeMenus, FastAsyncWorldEdit, FeatherBoard, goBrush, goPaint, HeadDatabase, LeaderHeadsRevamped, LuckPerms, MiniaturePets, Multiverse-Core, MVdWPlaceholderAPI, MyCommand, PlaceholderAPI, PlotSquared, PlugMan, ProtocolLib, SkinsRestorer, SpecializedCrates, TAB, TigerReports, Triton, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, VoxelSniper, WorldGuard, WorldGuardExtraFlags

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
You don't even have FAWE installed

**Comment by YunoOkamii** [comment]
@aurorasmiles 

if I just made a mistake in the writing of the message I've updated ^^
