### ISSUE TITLE
Incompatibility with Citizens2 (And thus Quests)

### ISSUE THREAD

**Issue by SoraShiunin** [IntellectualSites/FastAsyncWorldEdit#767]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/1646c76c3e574d0c92174c2acbe73996
**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     
FastAsyncWorldEdit 1.16 449

- Spigot/Paper Version Number (`/version`):     
1.16.4 R0.1

Startup log: https://paste.shockbyte.com/wiqiloyogeyovuxosere
(Has other errors but tested in a test server and it happened with fawe and citizens only)
**Describe the bug**
Theres an incompatibility with the plugin Citizens.
Most of my citizens work fine on their own but when on startup there is errors that only pops up when FAWE is installed.
And with quests, citizens cannot be used in quests.

**To Reproduce**
Install Citizens2. Start server.
Additionnaly try using Quests with Citizens while FAWE is installed.
(Does not occur if FAWE is not installed)

**Plugins being used on the server**

Plugins (64): PlaceholderAPI, HiberniaDiscord, PlayerHeads, ItemEditor, Runecraft, LuckPerms, Votifier, ProtocolLib, LibsDisguises, AdvancedPortals, InventoryRollback, MovingDevApi, Vault, HolographicDisplays, RewardPRO, Essentials, Multiverse-Core, VotingPlugin, FastAsyncWorldEdit (WorldEdit), RPGHealthPlus, TAB, XPBoost, WorldGuard, Multiverse-Inventories, ChatFeelings, NexEngine, EssentialsSpawn, WorldGuardExtraFlags, CommandSigns, Slabbo, EnjinMinecraftPlugin, ProCosmetics, RollbackCore, BattleTracker, Boss, MobArena, BattleArena, LWC, Quests, PhatLoots, QuestsGUI, Multiverse-NetherPortals, CoreProtect, AdvancedEnchantments, Towny, TownyNameUpdater, TownyChat, Jobs, CustomCrafting, ActionHealth, SimplePets, Citizens, Shopkeepers, mcMMO, NPC_Destinations, CitizensText, Sentinel, WolfyUtilities, ProjectKorra, ProjectAddons, JedCore, Hyperion, Multiverse-Portals, PlayerParticles
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Provide the full startup log with Fawe and Citizens installed.

**Comment by SoraShiunin** [comment]
Its in the issue.
Startup log: https://paste.shockbyte.com/wiqiloyogeyovuxosere

**Comment by N0tMyFaultOG** [comment]
Oic, Multicrap cut off important parts again. And where is the named exception?

**Comment by SoraShiunin** [comment]
This only occurs with FAWE.
"Loaded class net.citizensnpcs.api.event.NPCRightClickEvent from Citizens v2.0.27-SNAPSHOT (build 2191) which is not a depend, softdepend or loadbefore of this plugin."
Ingame, I can spawn citizens, but plugins that use citizens don't always work. EG:Quests.

**Comment by N0tMyFaultOG** [comment]
This is not an error but utterly irrelevant to Fawe.
