### ISSUE TITLE
Air blocks are not always rotated correctly

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#768]
**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/e8b6101796b44eff8acb0b83b5985a32

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-449;cc5b3ec 
- Spigot/Paper Version Number (`/version`): Paper build 318
- Minecraft Version: 1.16.4

**Describe the bug**
If one copy, rotate and paste the object shown in the picture, the air blocks are missing on one side.
![2020-12-07_15 08 41](https://user-images.githubusercontent.com/24480321/101362567-90313980-38a0-11eb-9cbf-4ca53c6f441c.png)
![2020-12-07_15 08 57](https://user-images.githubusercontent.com/24480321/101362629-a4753680-38a0-11eb-9a4a-fc4ef6210e8b.png)

**To Reproduce**
1. Download the apple.schematic: https://cloud.minecraft-corp.de/index.php/s/AgmWkme5N69377p and drop it into your schematic directory
2. /schem load apple
3. //paste
4. Copy the object
5. //rotate 90
6. //paste -> the air blocks on one side are missing

**Plugins being used on the server**
ChatControl, CMI, CMIEInjector, CMIPaperLib, FastAsyncWorldEdit, LuckPerms, Multiverse-Core, Nucleus, rAPI, rAPInms, StaffStuff, Vault, WirsingFix, WorldGuard, WorldGuardEvents, WorldGuardExtraFlags

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Cannot replicate this at all. Doubtful there's a real issue here
