### ISSUE TITLE
The replacement of/with biomes doesn't work properly

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#769]
**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/1347f4e520f2482f8864affad18aa90b

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-449;cc5b3ec 
- Spigot/Paper Version Number (`/version`): Paper build 318
- Minecraft Version: 1.16.4

**Describe the bug**
If one tries to replace one biom into another (`//replace $savanna $jungle_hills`) the area will be replaced only in stripes, between the stripes the default biom comes through.
![2020-12-07_15 36 38](https://user-images.githubusercontent.com/24480321/101364467-e56e4a80-38a2-11eb-8c69-3b88b013755c.png)
![2020-12-07_15 37 01](https://user-images.githubusercontent.com/24480321/101364501-ee5f1c00-38a2-11eb-84d9-6265069bc947.png)

If one tries to replace blocks with biomes the same problem occurs (`//replace grass_block $savanna`).
![2020-12-07_15 37 38](https://user-images.githubusercontent.com/24480321/101364560-00d95580-38a3-11eb-8651-6157e3394dff.png)

**To Reproduce**
1. Select an area
2. `//setbiome savanna`
3. `//replace $savanna $jungle_hills`

---------------------------------------
1. Select an grass_block area
2. `//replace 2 $savanna`

**Plugins being used on the server**
ChatControl, CMI, CMIEInjector, CMIPaperLib, FastAsyncWorldEdit, LuckPerms, Multiverse-Core, Nucleus, rAPI, rAPInms, StaffStuff, Vault, WirsingFix, WorldGuard, WorldGuardEvents, WorldGuardExtraFlags

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by TheoRetisch1** [comment]
Hej, thank you for the quick response! But could you please reopen the ticket? Unfortunalty the last update made it worse. I still can't replace biomes correctly and the last update broke //setbiome too.
`//setbiome $savanna` and `//replace $plains $savanna` now looks like this:
![2020-12-13_17 33 56](https://user-images.githubusercontent.com/24480321/102017915-01259500-3d6a-11eb-914b-555ce75ccc83.png)

debugpaste: https://athion.net/ISPaster/paste/view/21c5a6e974394d80b635916a8f761197
FAWE 1.16-462;04ba545
Paper 1.16.4 build 324

**Comment by dordsor21** [comment]
You need to expand the select vertically, else minecraft's crappy new biome system will use its crappy "noise" system to make biomes change vertically.

**Comment by jewome62** [comment]
Hello,

The issue can be reopened.
/fawe debugpaste:
https://athion.net/ISPaster/paste/view/7ec5d56fb53443e6aa8de20f67234145
Required Information

    FAWE Version Number: FastAsyncWorldEdit version 1.16-496;82f640d
    Spigot/Paper Version Number: Paper build 355
    Minecraft Version: 1.16.4

Some screenshot (see logs for commands executed)
I have created a surface of grass, default biome : forest
![image](https://user-images.githubusercontent.com/472429/103427453-7219d900-4bc1-11eb-943d-f429dad88bec.png)

into this surface, i make a selection with `//pos1` `//pos2`
and a `//expand 255 up` and `//expand 255 down`
Follow by `//setbiome savana`
Result:
![image](https://user-images.githubusercontent.com/472429/103427500-b4431a80-4bc1-11eb-8257-4becd6ad65e5.png)

**Comment by dordsor21** [comment]
There is still no error. That is how Minecraft does biomes now. You'll just have to deal with it. See https://minecraft.gamepedia.com/Biome#Other_information para 4
