### ISSUE TITLE
Tuinity-Starlight - //removelighting + //fixlighting doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#770]
**/fawe debugpaste**:
 https://athion.net/ISPaster/paste/view/4e0d81f218f946c1a98523648b6fe7d4

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-449;cc5b3ec 
- Spigot/Paper Version Number (`/version`): Tuinity-Starlight build 7 (https://ci.tivy.ca/job/Tuinity-Starlight/)
- Minecraft Version: 1.16.4

**Describe the bug**
Tuinity-Starlight (https://github.com/Spottedleaf/Starlight) offers a completely renewed light calculation that is far superior to vanilla or paper calculations. Therefore it would be fantastic if you could support this light engine. Currently` //removelighting` + `//fixlighting` doesn't work under Tuinity-Starlight.

**To Reproduce**
1. Run Tuinity-Starlight
2. Select an area
3. `//removelighting` + `//fixlighting` -> nothing happens

**Plugins being used on the server**
ChatControl, CMI, CMIEInjector, CMIPaperLib, FastAsyncWorldEdit, LuckPerms, Multiverse-Core, Nucleus, rAPI, rAPInms, StaffStuff, Vault, WirsingFix, WorldGuard, WorldGuardEvents, WorldGuardExtraFlags

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
removelighting is not implemented anyway. And fixlighting depends on the bukkit lighting engine, so I'm not really suprised that it doesn't work with Starlight

**Comment by dordsor21** [comment]
> removelighting is not implemented anyway. And fixlighting depends on the bukkit lighting engine, so I'm not really suprised that it doesn't work with Starlight

removelighting is reimplemented. Starlight may well be faster than FAWE lighting calculations as well...

**Comment by aurorasmiles** [comment]
Oh it definetely is

**Comment by Aurelien30000** [comment]
_There is also an issue propagating light in all cases with Startlight._

**Comment by krolik-exe** [comment]
From my experience, starlight also doesn't support auto relight and no matter what mode it is, so i need to manually fix lightning with

>  /paper fixlight

 command , I'm using latest FAWE 1.16.5 build

**Comment by krolik-exe** [comment]
Maybe You guys could implement a check , if the plugin is installed on paper or other forks of paper , and then use something similiar to [paper fixlight command](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0471-Fix-Light-Command.patch) ?

**Comment by TheoRetisch1** [comment]
I don't think it's really necessary to build a completely new light command or to fall back on the one from Paper. One should not forget that `//fixlighting` not only fixes the light, but also the rain penetration. Tuinity has an API and other plugins, such as LightCleaner, have also managed to [support Tuinity](https://github.com/bergerhealer/BKCommonLib/commit/794d0e4d5aa69e848688703cfbae94abedfe05c0) quite quickly.
The reason why it is not yet supported is, in my opinion, rather that this problem has been marked as low priority and the team is focusing on other problems.

**Comment by LaurenceBarnes** [comment]
I would somewhat like a command that updates heightmaps (such as rain penetration and maps) seperately though.

**Comment by scottyboii** [comment]
Papers /paper fixlight works 10x better than //fixlighting for me. Seeing //fixlighting working as good as papers would be ideal. 
Especially considering papers lack of permissions, making it unable to give players access to only the fixlight command.

**Comment by LaurenceBarnes** [comment]
I assume you use Tuinity? Cause Paper's fixlight is not necessarily accurate (because it uses the normal light engine).

However it doesn't solve the heightmap issue, which is a really big issue atm anyway if you look at the issue tracker
