### ISSUE TITLE
//regen does not work on 1.16.4

### ISSUE THREAD

**Issue by MrMaurice211** [IntellectualSites/FastAsyncWorldEdit#774]
**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/8f1fb456132147818c8f1ad5e12c7d5e

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-449;cc5b3ec
- Spigot/Paper Version Number (`/version`): Tuinity version git-Tuinity-"8056d13" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Minecraft Version: 1.16.4

**Describe the bug**
When running //regen on a selected area an error is thrown and the are is not regenerated

**To Reproduce**
1. Run Tuinity 1.16.4 version
2. Select an area
3. Do //regen

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Works perfectly fine with normal paper.
