### ISSUE TITLE
Polygonal2DRegion Copying Not Work

### ISSUE THREAD

**Issue by meerpaluten** [IntellectualSites/FastAsyncWorldEdit#778]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/fec074a2dc5547e7b8cde246e9f66856

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16 - 460;26e3e56
- Spigot/Paper Version Number (`/version`):     git-Paper-323
- Minecraft Version:1.16.4
**Describe the bug**
I have a Corner List witch i will copy
List<BlockVector2> corner;
This list is sorted with BlockVector2.COMPARING_GRID_ARRANGEMENT
Here are the Area in Black and the Corners in Blue
![image](https://user-images.githubusercontent.com/45709417/101988204-74f76d00-3c98-11eb-94e6-fe0c12362905.png)
Now i copy the Region and save it to the schematic
  Polygonal2DRegion regiontoCopy =
                        new Polygonal2DRegion(BukkitAdapter.adapt(world), region, 0, 255);
                    BlockArrayClipboard clipboard = new BlockArrayClipboard(regiontoCopy);
                    BlockVector3 vector3 = BlockVector3.at(0, 0, 0);
                    try (EditSession editSession =
                        WorldEdit.getInstance()
                            .getEditSessionFactory()
                            .getEditSession(BukkitAdapter.adapt(world), -1)) {
                      ForwardExtentCopy forwardExtentCopy =
                          new ForwardExtentCopy(editSession, regiontoCopy, clipboard, vector3);
                      // configure here
                      Operations.complete(forwardExtentCopy);
                    }
                    File file =
                        new File("plotregion.schem") /* figure out where to save the clipboard */;

                    try (ClipboardWriter writer =
                        BuiltInClipboardFormat.SPONGE_SCHEMATIC.getWriter(
                            new FileOutputStream(file))) {
                      writer.write(clipboard);
                    } catch (IOException e) {
                      e.printStackTrace();
                    }

If i paste the schematic it come a hole. A big Hole, with no content. 

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
It works fine in-game. There will be some incorrect API usage/offsetting/something somewhere.
