### ISSUE TITLE
Tuinity-Starlight - WorldEdit operations cause all entities to fall through the floor.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit#783]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
Config.yml
https://paste.gg/p/anonymous/c541454d83e04d6f99bfc5a225fd07be/files/3901ba614c654c53ad367e97a7fc7604/raw
Config-legacy.yml
https://paste.gg/p/anonymous/4ee2417324fc4797bbb7438feb87f15a/files/41a818ebd104445f941d6ee2d29ae828/raw

**Required Information**
- FAWE Version Number: FastAsyncWorldEdit version 1.16-474;e08fda0
- Spigot/Paper Version Number: Tuinity Starlight (dev 8 - https://ci.tivy.ca/job/Tuinity-Starlight-11/)
- Minecraft Version: 1.16.4

**Describe the bug**
FAWE seems to be incompatible with Tuinity's lighting branch (starlight implementation). Any worldedit operation made causes all entities in nearby chunks to fall through the floor. Affecting things such as armorstands and fake player npc entities (citizens) despite having gravity turned off.

I assume there is a collision check bug or incompatibility with FAWE and Starlight? Downgrading to main branch Tuinity (dev 35 - https://ci.tivy.ca/job/Tuinity/), FAWE operations no longer cause entities to fall.

**To Reproduce**
1. Place fake NPCs and/or armorstands.
2. Make a worldedit operation such as ``/cut``
3. See entities fall through the floor.

**Plugins being used on the server**
Citizens2, FastAsyncWorldEdit, ProtocolLib, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Giving this priority so some people can stop crying

**Comment by TheoRetisch1** [comment]
The bug was fixed in build 11 from yesterday. Furthermore, Spottedleaf has already stated before the issue was even opened here that he will probably have to undo a performance improvement on his side and sees no possibility to fix the problem on FAWE side. So I guess there is no reason to bother with it. Still, I think it's great that you guys want to support Tuinity, maybe instead of this issue, you could rather fix `//fixlighting` #770 <3
