### ISSUE TITLE
Multi-server clipboard doesn't copy entities

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#784]
**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/4871a0639f84455bb4b8b003e3b24ba1

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-463;6676d77
- Spigot/Paper Version Number (`/version`): git-Paper-325, Waterfall 388
- Minecraft Version: 1.16.4

**Describe the bug**
No entities can be copied using the multi-server clipboard.

**How to Reproduce**
1. `//copy -e` (include armorstands and written signs)
2. Teleport to another server
3. `//paste -e` (The signs and entities are not pasted)

**Plugins being used on the server**
ChatControlRed, FastAsyncWorldEdit, LuckPerms, PlaceholderAPI, Vault, WirsingFix, WorldGuard

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
See the discussion in #651. The clipboard on disk feature isn't really meant to be used cross-server, as it's not properly implemented to support that.

**Comment by dordsor21** [comment]
Also worth mentioning clipboard-on-disk has never saved NBT (entities and tile entities) to disk as a suitable method of serialising them hasn't been found

**Comment by TheoRetisch1** [comment]
Even if the requirements are not really available at the moment and the issue has a low priority, it would be a very very useful feature. So I see no need to close the ticket.

**Comment by MattBDev** [comment]
> Even if the requirements are not really available at the moment and the issue has a low priority, it would be a very very useful feature. So I see no need to close the ticket.

This issue will not be closed.

**Comment by TheoRetisch1** [comment]
The feture request is still an interesting vision for the future. Please reopen the ticket.

**Comment by TheoRetisch1** [comment]
The feature request is still an interesting vision for the future. Please reopen the ticket.

**Comment by dordsor21** [comment]
Implemented in #1745
