### ISSUE TITLE
//snow creating snow layers on where it should not be

### ISSUE THREAD

**Issue by Uboaaaaa** [IntellectualSites/FastAsyncWorldEdit#806]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

https://paste.gg/p/anonymous/cddbe72b51054fce8d0d9d08373e89a5

**/fawe debugpaste**: Failed to perform, logs: https://paste.gg/p/anonymous/51f095a838ec42d78e1e6af5a68499cd

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     
- Spigot/Paper Version Number (`/version`):     Yatopia-87c3b4e
- Minecraft Version:     1.16.4

**Describe the bug**
when running //snow, snow layers are placed on "illegal" places where they are not supposed to form. For example, stairs, half slabs, iron bar, glass, trapdoor and pressure plates.
![Screenshot 2020-12-21 141540](https://user-images.githubusercontent.com/70588463/102786712-dce43c80-4397-11eb-975b-dbec5c4c5b29.png)

**To Reproduce**
1. Place the described blocks around you
2. Run //snow

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Yatopia is not supported. Use a proper environment (Paper/Spigot) and we will happily look into the issue if it still occurs.

**Comment by Uboaaaaa** [comment]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 




https://paste.gg/p/anonymous/cddbe72b51054fce8d0d9d08373e89a5

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/37e2024b64fa488cadccf0e0231441c6

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):    1.16-485;be05ae9 
- Spigot/Paper Version Number (`/version`):     paper-231
- Minecraft Version:     1.16.4

**Describe the bug**
when running //snow, snow layers are placed on "illegal" places where they are not supposed to form. For example, stairs, half slabs, iron bar, glass, trapdoor and pressure plates.
![image](https://user-images.githubusercontent.com/70588463/102791240-9b0ac480-439e-11eb-89d2-43f79e1789ec.png)




**To Reproduce**
Steps to reproduce the behavior:
1. Place the described blocks around you
2. Run //snow

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin
