### ISSUE TITLE
/u throws internal error

### ISSUE THREAD

**Issue by Markiealso** [IntellectualSites/FastAsyncWorldEdit#809]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/5044897ec70141eaa5a46e86f1306924

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-487;9f2baf7
- Spigot/Paper Version Number (`/version`):     Paper version git-Paper-337 (MC:1.16.4)
- Minecraft Version: [e.g. 1.16.4]     1.16.3

**Describe the bug**
/u throws internal error

**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
a) This is not a Fawe issue.
b) Don't delete the template.
