### ISSUE TITLE
ClassCastException when saving schematic

### ISSUE THREAD

**Issue by Crypnotic** [IntellectualSites/FastAsyncWorldEdit#810]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/ccf0d6437e2e479e816c82c4ad8cc9db

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-488;7236f1d
- Spigot/Paper Version Number (`/version`): git-Paper-342
- Minecraft Version: 1.16.4

**Describe the bug**
Ran the //schematic save and the aforementioned error was thrown in the logs

**To Reproduce**
1. Make a region selection
2. Copy the region with //copy
3. Attempt to save the region to a schematic file with //schematic

**Plugins being used on the server**

FastAsyncWorldEdit (WorldEdit), Multiverse-Core, ProtocolLib, skyblock, VoidGenerator, WorldBorderAPI

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If this is still an issue on the latest version, could you attempt to find what block is causing the issue?
