### ISSUE TITLE
//undo <big number> throws an error in console

### ISSUE THREAD

**Issue by Bullob** [IntellectualSites/FastAsyncWorldEdit#812]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/6fda3ecd7b044c9c9e6da9a28ed97a51

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-488    
- Spigot/Paper Version Number (`/version`): git-paper-345    
- Minecraft Version: 1.16.4

**Describe the bug**
Execute //undo <number> command with a high number throws an error in console, but the undo is still executed.
Also spams the chat with the "please use //confirm" message even before I sent the command while typing the large number.

**To Reproduce**
1 Type and execute //undo 100
2 The undo will be executed but a large stacktrace will be throw in the console a few seconds later

**Plugins being used on the server**
NoteBlockAPI, FastAsyncWorldEdit, ProtocolSupport, OlympaCore (homemade) and OlympaCreatif (homemade)

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Fixed
