### ISSUE TITLE
FastSchematicReader doesn't load minimum&maximum point as SpongeSchematicReader does

### ISSUE THREAD

**Issue by i998979** [IntellectualSites/FastAsyncWorldEdit#814]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
Just using the build 489 default generated one, nothing changed

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/665b6d02e8d740b3bed3566e53c20c23

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-489;b60d9ef
- Spigot/Paper Version Number (`/version`):     git-Spigot-628435a-768d7fc (MC: 1.16.4)
- Minecraft Version: [e.g. 1.16.4]     1.16.4

**Describe the bug**
```
File file = new File(MythicDungeons.inst().getDataFolder(), "schematics" + File.separator + name + ".schem");
ClipboardFormat format = BuiltInClipboardFormat.SPONGE_SCHEMATIC;
try (ClipboardReader reader = format.getReader(new FileInputStream(file))) {
    Clipboard clipboard = reader.read();
}
```
With the code above, when I'm running original WorldEdit, the clipboard.getMinimumPoint() (as well as max) returns the location of the minimum point relative to the origin. However, when running with FAWE, clipboard.getMinimumPoint() returns the location based on the zero vector.
I've spent 10+ hours in digging into the source code and testing because I get **ZERO** response from the support Discord server and I found that using FAWE deprecated SpongeSchematicReader works, but using the default FastSchematicReader for SPONGE_SCHEMATIC, it doesn't work.
So I guess the problem is in FastSchematicReader.

**To Reproduce**
1. Run the code above with original WorldEdit
2. See the result from clipboard.getMinimumPoint()
3. Run the code above with FAWE
4. See the result from clipboard.getMinimumPoint()

**Plugins being used on the server**

PlugMan, Vault, Multiverse-Core, ProtocolLib, FastAsyncWorldEdit (WorldEdit), MythicMobs, MythicDungeons

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
The difference is that the fast reader returns a different clipboard format to the sponge reader. If you wrap the clipboard in a BlockArrayClipboard the behaviour will be the same
