### ISSUE TITLE
ERROR |  An unexpected error.

### ISSUE THREAD

**Issue by ZerXGIT** [IntellectualSites/FastAsyncWorldEdit#818]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
https://athion.net/ISPaster/paste/view/fa89481b88184c52951dbf6ad46b177d

**/fawe debugpaste**: 

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):      FastAsyncWorldEdit version 19.11.13-5505943-1282-22.3.5
- Spigot/Paper Version Number (`/version`):     git-PaperSpigot-"4c7641d" (MC: 1.8.8)
- Minecraft Version: 1.8.8

**Describe the bug**
The bug arises when you enter "// gtexture".

**To Reproduce**
1. Run  to '//gtexture ...'
2. 
**Plugins being used on the server**

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Unsupported version
