### ISSUE TITLE
BlocksHub Logging Broken

### ISSUE THREAD

**Issue by hhenrichsen** [IntellectualSites/FastAsyncWorldEdit#820]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/edb36764f1d34a2a9515ca9d4a833e64

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-502;efcca5b
- Spigot/Paper Version Number (`/version`): Tuinity-"f06591a" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Minecraft Version: 1.16.4

**Describe the bug**
BlocksHub logging is not working on the latest builds of CoreProtect, FAWE, and BlocksHub.

**To Reproduce**
1. Select a small region
2. Run `//set stone`
3. Run `/co i`
4. Left click the stone that was just placed
5. Output: `CoreProtect - No block data found at stone`

**Plugins being used on the server**

Plugins (4): BlocksHub, CoreProtect, Essentials, FastAsyncWorldEdit (WorldEdit)

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by jewome62** [comment]
BlockHub support was delete without announcing and documentation is not update.
https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/0723620722dfafe1cb663cf0437eb2578efb6ed3
https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/ceec0ec0b9ab3a84c5f7bbf7977ed7bbd81e5199

**Comment by N0tMyFaultOG** [comment]
Blocks Hub has been removed in favor of the build in logging and history service.

**Comment by jewome62** [comment]
Maybe remove from documentation. There are a repo for documentation ?

**Comment by N0tMyFaultOG** [comment]
> Maybe remove from documentation. There are a repo for documentation ?

Where does it say so? There is no other repository but this and I made sure I removed all references to it. If you find anything left over, please let me know.
