### ISSUE TITLE
Immediate error that crashes 1.16.4 paper spigot server.

### ISSUE THREAD

**Issue by techboy04** [IntellectualSites/FastAsyncWorldEdit#821]
Paper Spigot version - #366
Server Version - 1.16.4
FastAsyncWorldEdit Version - 1.16-502

Tried to delete the old folder but for some reason the server keeps crashing.

latest log - https://hastebin.com/jeqegoduqo.yaml

**Comment by dordsor21** [comment]
"zombiesurvival" is using AsyncWorld that is not fixed for latest versions yet.
