### ISSUE TITLE
//undo not working at all

### ISSUE THREAD

**Issue by wearenoobsuk** [IntellectualSites/FastAsyncWorldEdit#822]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     
- Spigot/Paper Version Number (`/version`):     
- Minecraft Version: [e.g. 1.16.4]     

**Describe the bug**

**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

Fawe Log Paste
https://athion.net/ISPaster/paste/view/73a27cffd38f477ea093288457fe325a

Server Version, Latest paper 1.16.4

Latest Fawe version on spigot.

I cannot get //undo to work, It says Undid 1 available edit, But nothing happens, There is no errors in the console either. I did hit one error when doing //undo once. And this was it. https://pastebin.com/zGzXSfRB but I cannot seem to make that error happen again.

I'm also using plotsquared on it's most recent release. But this happens on the same server in a world not controller by plot squared.

thankyou!

**Comment by braceyourself07** [comment]
can confirm.  does not appear to //undo on build 505.   i was using build 502 earlier and //undo will work on that, but schems made with //download will appear corrupt

**Comment by dordsor21** [comment]
Fixed as of yesterday

**Comment by Elric02** [comment]
Using build 511, having the same problem :/

**Comment by dordsor21** [comment]
> Using build 511, having the same problem :/

I cannot replicate on the latest build at all.
