### ISSUE TITLE
WorldEdit axe not working when getting permission

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#826]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:https://athion.net/ISPaster/paste/view/731ff16e7656452a95ac21abe16764b7

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-508
- Spigot/Paper Version Number (`/version`):     312
- Minecraft Version: [e.g. 1.16.4]     1.16.4

**Describe the bug**
WorldEdit axe doesn't work after getting permission to use it.
Looks to me like FAWE only checks if it should listen to a user using the WE axe at the first join and when using `//wand`. So if the user joins without the permission, Fawe only recognises the user gets the axe with `//wand`.

**To Reproduce**
1. Set WorldEdit permissions of yourself (or testaccout) to false.
2. Restart the Server
3. join back in
4. Set WorldEdit permissions to true
5. The axe doesn't work until `//wand` is used.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
I cannot replicate this. Make sure you are properly assigning the correct permission (worldedit.select.pos is for selecting with a wand, worldedit.wand is just for getting the wand).

**Comment by Xaver106** [comment]
Tested this in version 558. Still happening to me.
A reload doesn't work, you need to restart the server. If you don't have the permission `worldedit.selection.pos` when you join the server you can't use the axe. It only starts working **after** you use `//wand` or restart the server!
The steps here in detail:
1. Unset the permission `worldedit.selection.pos` on the testaccount (Setting it to fals works as well)
2. **Restart the server** and not just FAWE
3. Join back in
4. Set the permission `worldedit.selection.pos` true for your testaccount
4. Take the axe from your creative inventory and try to use it.
5. It won't work until the account executes `//wand` or the server is restarted!

**Comment by Xaver106** [comment]
@dordsor21 Please reopen the issue, as it is still a problem!

**Comment by Xaver106** [comment]
@dordsor21 Please reopen, as it is still an issue in FastAsyncWorldEdit-614

**Comment by RedstoneFuture** [comment]
I have the same problem on my production server. Xaver is in my server team and tested it on his own local server with a different setup.

**Comment by Xaver106** [comment]
Tested with only PermissionsEX and FAWE 1.16.5-614. Still the same result as mentioned above.
"normal" WorldEdit 7.2.3 does not have this issue.

**Comment by RedstoneFuture** [comment]
case 1 - I promote a user to a group with WE permission ... and after `//wand` he has WE permission (rejoin doesn't help him - he must use the `//wand` command)
case 2 - I promote a user to a group with WE permission ... and after a server restart he has WE permission

Why this difference is happened?

**Comment by Xaver106** [comment]
Still an issue on FastAsyncWorldEdit version 1.16-666;ceacd7b
Paper: git-Paper-629 (MC: 1.16.5)

**Comment by Xaver106** [comment]
Still an issue with Fawe-99.

Same procedure and result as in this comment: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/826#issuecomment-761614194

**Comment by dordsor21** [comment]
This is no longer fixed, however, that is on purpose. Either this very niche and unimportant issue is fixed, or players cannot toggle the edit wand in any way without removing permissions.
