### ISSUE TITLE
Missing permission

### ISSUE THREAD

**Issue by mare-on** [IntellectualSites/FastAsyncWorldEdit#828]
- FAWE Version: 1.16.4 (#502)
- Paper Version: Paper 1.16.4 (#352)
- Minecraft Version: 1.16.4

**Describe the bug**
Permission for command "//deselect" is missing Command is used only with OP.

**Comment by N0tMyFaultOG** [comment]
Don't delete the template.
The permission is `worldedit.analysis.sel` as `//deselect` is an alias for `//sel`.
