### ISSUE TITLE
Error message when running heightmapinterface

### ISSUE THREAD

**Issue by Zielach** [IntellectualSites/FastAsyncWorldEdit#833]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/5e414a5d01334dd9baf24a5617e051d4

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-502;efcca5b
- Spigot/Paper Version Number (`/version`):     Paper version git-Paper-362 (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Minecraft Version: 1.16.4  

**Describe the bug**
Upon using //heightmapinterface, in the writing process I get the following error: 
![image](https://user-images.githubusercontent.com/32837728/103899697-0ec70400-50f7-11eb-95d8-216906b7b086.png)
Error in console: An unexpected error while handling a WorldEdit command

**To Reproduce**
1. Download an install heightmap-main
2. Copy it to plugins/FastAsyncWorldEdit/heightmap
3. Use //heightmapinterface
4. See error after writing some images

**Plugins being used on the server**
Plugins (8): Builders-Utilities, DiscordSRV, Essentials, FastAsyncWorldEdit (WorldEdit), HeadDatabase, Multiverse-Core*, NoJoinMessages*, VoidGenerator

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You're laying out the folders wrong. The heightmap folder you download goes into plugins/FastAsyncWorldEdit/**web**/heightmap.

The plugins/FastAsyncWorldEdit/heightmap folder is ONLY for images, or folders of images, NOT the web stuff (config.js etc)
