### ISSUE TITLE
Clipboard loading - ClosedByInterruptException

### ISSUE THREAD

**Issue by Voyaris** [IntellectualSites/FastAsyncWorldEdit#834]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     
- Spigot/Paper Version Number (`/version`):     
- Minecraft Version: [e.g. 1.16.4]     

**Describe the bug**

**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

Config files: https://athion.net/ISPaster/paste/view/8f2b076d76c84f7780e6a158bc19c3b6

FAWE-Version: 1.16-522;3accbb8
Paper-Version: git-Paper-390 (MC: 1.16.4)

Description:
I am new to the WorldEdit API and would like to make a plugin that resets certain regions.
I want to do this with Schematics.
Tried everything and always get this error message: https://prnt.sc/wj2lvn
I followed tutorials and read through this website: https://worldedit.enginehub.org/en/latest/api/examples/clipboard/#schematic-examples.
The file exists and there are no complications with file permissions as soon as I know (all tested on Windows).
Therefore I assume that it is a bug from the plugin

My code: https://codeshare.io/5NnYym (Error on line 14)

**Comment by dordsor21** [comment]
Please attempt loading the schematic when the server has actually loaded, rather than (presumably) in your plugin's onEnable
