### ISSUE TITLE
fawe bugs. (example /up;/sel ellipsoid

### ISSUE THREAD

**Issue by supermem99** [IntellectualSites/FastAsyncWorldEdit#836]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

[here](https://athion.net/ISPaster/paste/view/caafd435cf1947abb811862c7ad8bc7c)
**/fawe debugpaste**:

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     
- Spigot/Paper Version Number (`/version`):     
- Minecraft Version: [e.g. 1.16.4]     

**version: 1.16-523;713c22c**

**Describe the bug**

after /up 10 in example nothing appears. No error
with //sel ellipsoid you cant do right ellipsoids
**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
please create separate issues with more details provided. I also cannot replicate anything wrong with //up.
