### ISSUE TITLE
Crash when installing FAWE

### ISSUE THREAD

**Issue by JessyDrew** [IntellectualSites/FastAsyncWorldEdit#841]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
(I cant start my server) https://haste.athion.net/raw/evecevupev
Config: https://haste.athion.net/raw/iluboqufox
Config-legacy : https://haste.athion.net/raw/hetacacefi

**Required Information**
- FAWE Version Number FastAsyncWorldEdit-1.16-525 (i cant execute the cmd)
- Spigot/Paper Version Number:    git-Paper-367 (MC: 1.16.4)
- Minecraft Version: 1.16.4

**Describe the bug**

When I installed FAWE, my server won't start and crash.

**To Reproduce**
download FAWE and restart my server

**Plugins being used on the server**
AdvancedEnchantment / Bentobox / bstats / CrazyCrates / DeluxeMenus/ Epichoppers / Epicpsawners/ Essentials / HolographicDisplays / Jobs / Luckperms / Multiverse / Mycmd / NextEngine / PAPI/ PluginMetrics/ Protocol/ Shopgui+ /StackMob / Sunlight/ UltimateFishing - stacker - timber / updater / Vault/  Voidchest / WorldGuard / xpboost

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Remove all plugins, update paper, boot your server and provide your latest.log

**Comment by JessyDrew** [comment]
Ok
I remove all plugins
I update paper, and i send my lastest.log
https://haste.athion.net/raw/wixorojixa

**Comment by N0tMyFaultOG** [comment]
> Ok
> I remove all plugins
> I update paper, and i send my lastest.log
> https://haste.athion.net/raw/wixorojixa

You also want to install Fawe, this one is useless.

**Comment by JessyDrew** [comment]
Why i'm so stupid like that today..
https://haste.athion.net/raw/cibowafodu

**Comment by JessyDrew** [comment]
Why i'm so stupid like that today..
https://haste.athion.net/gocesodala.md

**Comment by JessyDrew** [comment]
> Why i'm so stupid like that today..
> https://haste.athion.net/gocesodala.md
> 
> > **[hastebin](https://haste.athion.net/gocesodala.md)**

I Know what it the problem. Essentials and FAWE not good friend on my server

**Comment by dordsor21** [comment]
Likely an outdated essentials, invalid/bad configuration of essentials, or bug in essentials then
