### ISSUE TITLE
FAWE stops working when using fixwater/fill

### ISSUE THREAD

**Issue by LaurenceBarnes** [IntellectualSites/FastAsyncWorldEdit#842]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://pastebin.com/xNybejSD (I was asked by aurora to provide this on discord)

**Required Information**
- FAWE Version Number #492, #502, #518, #529, #534 
- Spigot/Paper Version Number #325   
- Minecraft Version: 1.16.4   

**Describe the bug**
hey, I sometimes have the issue that FAWE doesn't work for a single person when using brushes and commands such as //fill water and //fixwater, problems seem to be large operations (perhaps many smaller operations too). There is no error message, it just doesn't work. Relogging doesn't fix it, only restarting the server does. For example, //fill water 500 50, FAWE does a part of it, aborts it and then stops working (at that try it stopped working for everyone)

**To Reproduce**
1. do //fill water with a large radius/depth, or //fixwater with a larger radius (even happened with 50 and reliably with a higher radius) 
2. FAWE will either stop working for the one person who did that command and usually for the other players too, there is no pattern we could find about that
3. There is no error message, however the //fawe threads command spits out some stuff

EDIT: #492 seems to be more tolerant and needs more effort to "break" with //fill or //fixwater (higher radius/multiple people using the command simultaneously)

**Plugins being used on the server**
BKCommonLib, Core, CoreProtect, CustomCommands, DeadChest, dynmap*, Enchantments_plus, Essentials, FastAsyncWorldEdit (WorldEdit), GCoreLegacy, GSit, HolographicDisplays, ImageMaps, ItemJoin, ItemSlotMachine, LibsDisguises, LightCleaner, LuckPerms, Maplands, My_Worlds, MythicMobs, OpenInv, PlaceholderAPI, PlugMan, ProtocolLib, PsudoCommand, QuickShop, TAB, TCPShield*, TimeIsMoney*, Train_Carts, UniqueRewards, Vault, ViaBackwards, ViaVersion, Vivecraft-Spigot-Extensions, WorldEditSelectionVisualizer, WorldGuard

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

this is my first GitHub issue, I hope I did well xD

**Comment by dordsor21** [comment]
Was the `/fawe threads` command run when it had stopped working?

**Comment by LaurenceBarnes** [comment]
yes, aurora asked me on discord to run that command. The pastebin here is the output from /fawe threads after fawe stopped working/reacting

**Comment by Tsoccerguy3** [comment]
This bug has surfaced again FAWE 1.17.1 build 210 and more than likely some builds back . The use of //fixwater 50 causes FAWE to become unresponsive . All FAWE commands entered after this do nothing . Reboot is only way to get FAWE to work again . I can also trigger the same behavior by //stacking something over the same path 3 or more times. /fawe threads does not get a response and no error generated .
