### ISSUE TITLE
Problem with commands /br, /image, /br image

### ISSUE THREAD

**Issue by F1STjd** [IntellectualSites/FastAsyncWorldEdit#845]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/bcc7b7d8f13a4e8faff3dedbbfc21a9e

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):    1.16-523;716c22c
- Spigot/Paper Version Number (`/version`):    git-Spigot-37d799b-3eb7236
- Minecraft Version: [e.g. 1.16.4]    1.16.4

**Describe the bug**
/image, /br, /br image - commands are not working

After clicking many times nothing is changing:
![2021-01-12_16 02 45](https://user-images.githubusercontent.com/77339993/104331881-e45ab980-54ef-11eb-8902-23a0b59cfc96.png)

After typing: "/image https://i.imgur.com/VhFawi1h.jpg":
![2021-01-12_16 05 58](https://user-images.githubusercontent.com/77339993/104332145-284dbe80-54f0-11eb-95d0-b423418ec6a2.png)

**To Reproduce**
1. Run server
2. Type in /br or /br image or /image
3. Press enter (and RMB)
4. See error (nothing has changed)

**Plugins being used on the server**

Plugins (2): LuckPerms, FastAsyncWorldEdit (WorldEdit)

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Please update WorldEdit and try again. I cannot reproduce this.
