### ISSUE TITLE
Plot clearing causing server crash on build 540

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#848]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**Fawe config**:
config.yml: https://haste.athion.net/qeyibecixi.coffeescript

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit-1.16-540    
- PlotSquared version number: PlotSquared-Bukkit-5.13.10-Premium
- Spigot/Paper Version Number (`/version`): Paper version git-Paper-409 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)    
- Minecraft Version: 1.16.4    

**Describe the bug**
Doing a /plot clear on build 540 will cause the server cpu to spike and lead to a crash: https://haste.athion.net/xapafabuke.md this is not an issue when using an older build of fawe. For now I've reverted to build 461 which does not cause this crash. The plot size in the world is 512x512.

**To Reproduce**
1. Create a new world
2. Claim a plot and then run /plot clear

**Plugins being used on the server**
PlotSquared, FastAsyncWorldEdit, LibsDisguises, ProtocolLib, LuckPerms

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
[16:33:23 WARN]: java.lang.OutOfMemoryError: Java heap space
your JVM is running out of memory. Also, please include a debugpaste.

**Comment by SecretlyJealous** [comment]
Fixed in build 541, thanks
