### ISSUE TITLE
Some kind of deadlock

### ISSUE THREAD

**Issue by DoogiePC** [IntellectualSites/FastAsyncWorldEdit#849]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):  540 (this has happened every single version)
- Spigot/Paper Version Number (`/version`):    paperspigot-409
- Minecraft Version: [e.g. 1.16.4]      1.16.4

**Describe the bug**
It's really hard to explain but it seems randomly on my main server with the most players, FAWE seems to just break at some point in the day. No command can be run, /fawe debugpaste doesn't work either. Not a single worldedit or fawe related command. I setup a cheap script to run the command /fawe every 5 seconds and the  server.log I sent shows you the point at which /fawe stopped running (because of the deadlock)

**To Reproduce**
No known way to reproduce

**Plugins being used on the server**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
You didn't include a server log or the other plugins. Please see if /fawe threads works and also attach that output

**Comment by dordsor21** [comment]
Please update to the latest FAWE and see if it continues to happen

**Comment by DoogiePC** [comment]
> Please update to the latest FAWE and see if it continues to happen

ok ill try it and let you know, it may take a few days or longer.

**Comment by dordsor21** [comment]
Assuming this is fixed

**Comment by DoogiePC** [comment]
> Assuming this is fixed

Funny this has been said, as today it seems it has broken. Just 8 hours after the server started up

**Comment by DoogiePC** [comment]
@dordsor21 this might help, I used //cancel today and it spammed console and then w/e was broken: https://pastebin.com/RTCPhhd6
