### ISSUE TITLE
Armor stand problem

### ISSUE THREAD

**Issue by Heron4gf** [IntellectualSites/FastAsyncWorldEdit#850]
**Is your feature request related to a problem? Please describe.**
I have used FastAsyncWorldEdit on several servers, and I have noticed some major differences between 1.12.2 server and 1.16.4 server. ArmorStand don't get copied with //copy

**Describe the solution you'd like**
I think it would be great to get armorstand copied like it used to work in past versions

**Additional context**
Would it be possible? Or else will it work with newest minecraft versions?

**Comment by SirYwell** [comment]
Armor Stands are entities and not copied by default. Use the `-e` flag to copy entities (and same for pasting).
