### ISSUE TITLE
copy, paste, cut painfully slow (with small operations)

### ISSUE THREAD

**Issue by LaurenceBarnes** [IntellectualSites/FastAsyncWorldEdit#855]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/1a137013263046108adf41d4bdb95713

**/fawe threads** (might be relevant): https://controlc.com/5eb3a419

**Required Information**
- FAWE Version Number: 559 
- Spigot/Paper Version Number: 325
- Minecraft Version: 1.16.4   

**Describe the bug**
I have noticed before that since a couple versions (recent fixes for other things), copying and pasting of small operations are slow. This includes brushes that are even slower than before (instead of 1 second, they need 3 seconds to place a sphere with a mask). First I thought that was because of the brushes, because for a few days, I didn't use any //copy etc, but it seems to affect everything. 
I activated options such as "Set experimental.send-before-history to true (this is pretty safe now) and set lighting.delay-packet-sending to false"

![FAWEslow](https://user-images.githubusercontent.com/77249464/104807580-537e2980-57e0-11eb-9d86-4e9365145df2.PNG)

**To Reproduce**
1. Make a small selection (~100 blocks)
2. Copy or cut it
3. notice how it takes 5 seconds or more with speeds like 20 blocks/sec which was much faster before

OR
1. equip any tool
2. use a brush such as
   /brush sphere 40%kelp_plant,60%water 7
   /mask ">gravel,sand,kelp_plant !#solid !seagrass,tall_seagrass[half=upper],tall_seagrass[half=lower],kelp_plant =y<62"
   (take care of the parameters as you need sand or gravel to sea results and need to place it below y=62)
3. Notice how it takes 2-3 seconds to place (1 second before), seemingly slowing down over time

If I can help any further, don't hesitate to ask :D

**Plugins being used on the server**
BKCommonLib, Core, CoreProtect, CustomCommands, DeadChest, dynmap*, Enchantments_plus, Essentials, FastAsyncWorldEdit (WorldEdit), GCoreLegacy, GSit, HolographicDisplays, ImageMaps, ItemJoin, ItemSlotMachine, LibsDisguises, LightCleaner, LuckPerms, Maplands, My_Worlds, MythicMobs, OpenInv, PlaceholderAPI, PlugMan, ProtocolLib, PsudoCommand, QuickShop, TAB, TCCoasters, TCPShield*, TimeIsMoney*, Train_Carts, UniqueRewards, Vault, ViaBackwards, ViaVersion, Vivecraft-Spigot-Extensions, WorldEditSelectionVisualizer, WorldGuard

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
I'd be interested to know if there's by any difference reducing parallel-threads to 8 or so in your config

**Comment by LaurenceBarnes** [comment]
well we are using a 3900x, which means 12cores/24threads. Would be great to utilize that (if that option even does that).

I am trying that now though anyway :D

**Comment by LaurenceBarnes** [comment]
![FAWEslow2](https://user-images.githubusercontent.com/77249464/104808110-51b66500-57e4-11eb-942a-fe8c04f44988.PNG)

sadly same story, same slow speed. What should I do next? (revert the thread setting?)

**Comment by LaurenceBarnes** [comment]
I just tested if LightCleaner was the issue (since it hooks into FAWE), but it is the same story when I remove it. It didn't cause issues before anyway, just ensuring again that it isn't doing that.

**Comment by dordsor21** [comment]
Would you be able to grab a /fawe thread when waiting for the command to complete?

**Comment by LaurenceBarnes** [comment]
will do

**Comment by LaurenceBarnes** [comment]
removing the visualizer doesn't change anything :/

However I was able to retrieve a /fawe threads during the process that lasted 5.2 seconds (as you can see it is from the second (probably 1,5 seconds) from after I executed //cut)

https://controlc.com/ebaf9031

Interestingly after the first //cut, speed doubles and seems to consistently stay at that speed (until I relog OR restart the server), but 2.6 seconds is still more than I had before for such a small amount of blocks (i recall it being less than a second lol).

**Comment by dordsor21** [comment]
The first edit after restarting a server will always take a bit longer because FAWE initialises its caches and loads the block data etc for the rest of the edit. The fact that this takes 2.6 seconds makes me think there's something very wrong with your system and/or java version.

I'd recommend updating to java 11 and making sure there's nothing else on the system slowing anything down (check for disk usage, RAM and CPU).

**Comment by LaurenceBarnes** [comment]
the thing is, that is new. I can try out previous FAWE versions and check from which one this starts happening. 
We were gonna update java anyway. However the system is rather underwhelmed by the server hosting. The 3900x, 32GB of RAM (12GB dedicated to this server) and a 1TB NVMe SSD should prevent any bottleneck.

**Comment by LaurenceBarnes** [comment]
Okay so we updated to java 11. 
However I found out something that I didn't expect at all. As you know, we use a multi-dimension plugin (myworlds) and work in parellel dimensions. Those work fine, also with FAWE, but one dimension has been edited with a tool called WorldPainter. Only in this dimension the delay of at least 2.5 seconds occurs (we didn't test in the other dimensions because it is so unlikely and we work in that dimension only since it is a part of a larger project). Perhaps a solution is to generate a natural map and paste in the terrain.

An additional info: For editing, the world had to be downloaded, saved in singleplayer once, edited with worldpainter (it needs it to be in singleplayer vanilla format), uploaded again, loaded via paper. You are perhaps out of responsibility IF it is really not FAWE at all, but this issue is so weird and I wonder why only FAWE is affected (other plugins seem to perform just fine) and if there need to be made changes from your side, from the tools' side or if converting world to singleplayer and then paper again (or in even one direction only) is a problem for FAWE in general, which would then require a solution for those cases.

I'd be really happy for any kind of hint in any case :D

**Comment by dordsor21** [comment]
What version of minecraft was the map made for in worldpainter?

**Comment by LaurenceBarnes** [comment]
that map that we used was generated in 1.16.3 (or in .2, but pretty certainly the first) based on a custom seed. This is why some villages and structures look different than on the originally generated world (which is irrelevant to this problem, but FAWE works perfectly on it).
We then built on it and did a lot of stuff.
In order to edit it with worldpainter, it was downloaded by the guy who is good at world painting via a FTP. We quickly figured that worldpainter can't then open the world unless it is opened and then saved in vanilla singleplayer (1.16.4).
After he exported the terraformed world (note, he used the merging function) in the 1.14+ world format that worldpainter supports, he uploaded it again (tested it in singleplayer first) and we loaded it in, where it was converted to paper's format again.
We repeated those steps once again for some final adjustments of the terrain, and we are currently finetuning the terrain with the FAWE tools.

I hope that was understandable. I believe it is better to provide too many details than not enough.

Thanks!

**Comment by dordsor21** [comment]
It's usually advised to upgrade the world once major version at a time, so 1.14 -> 1.15 and then 1.15 -> 1.16 using the "--forceUpgrade" flag when starting the server. I'd recommend you skip the 1.15.2 as that might corrupt the world, and run a force upgrade on the entire world.

**Comment by LaurenceBarnes** [comment]
so you think that it could be because of WorldPainter saving it in 1.14.4+ format, whatever that means?

I just checked whether loading a singleplayer world into paper reproduces that issue - it doesn't seem to.

**Comment by dordsor21** [comment]
Yes, so you'll need to forcefully upgrade the world. Otherwise, the server attempts to do this to the chunks on-the-fly.

**Comment by LaurenceBarnes** [comment]
is it possible to do this only for one of the dimensions as the others are already on 1.16.4? Or can it affect them in any way? I have never used that argument before (if you mean those after the RAM definitions)

**Comment by dordsor21** [comment]
you need to put it after you specify your server jar, as it's not a jvm argument. Also, it won't do anything to chunks/worlds that are already on 1.16.4. It *will* take a while to upgrade worlds that aren't upgraded, and I recommend you remove the flag again afterwards as it still takes some time to work out if chunks/worlds don't need upgrading.

**Comment by LaurenceBarnes** [comment]
Since this is related to another issue and I didn't yet have the opportunity to try that tip out, I'll close it xD
If I find out something, I will comment here anyway
