### ISSUE TITLE
Can't manipulate snow layers

### ISSUE THREAD

**Issue by tomtries** [IntellectualSites/FastAsyncWorldEdit#858]
**/fawe debugpaste**: **https://athion.net/ISPaster/paste/view/3163c8699e7245bb9dd3bdcbf0da48e2**

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     559
- Spigot/Paper Version Number (`/version`):     "git-Spigot-37d799b-3eb7236"
- Minecraft Version: [e.g. 1.16.4]     1.16.4

**Describe the bug**
I cannot use the tag -s when smoothing 7 layered sow [78:7] nor can I manipulate (78:7) with //br height -L.
**To Reproduce**
1. Make a square base with //set 78:7
2. get a stick and do //br height 10 -l
3.  the snow will not be affected
4. Also replacing terrain with 78:7 and trying //smooth -s will also result in the snow not changing

**Plugins being used on the server**
 Sethomes, FAWE, FAVS, Multiverse-Core

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by NetroAki** [comment]
Can confirm this issue persists across all supported versions. Tried with a clean install and no luck either. To clarify the blocks do smooth but the snow layers aren't smoothed they stay as the full size 78:7 blocks.

**Comment by indyteo** [comment]
I can also confirm the issue, in 1.16.4 I can't even manage to do anything with a `/br height -l` brush... :(
