### ISSUE TITLE
[MMOItems] Hooked onto WorldEdit ERRO

### ISSUE THREAD

**Issue by BearLeonLight** [IntellectualSites/FastAsyncWorldEdit#862]
Error message: https://pastebin.com/k6eTPkZv
I used the original WorldEdit and did not have this problem. There was a problem with FAWE.
ServerLog: https://pastebin.com/S7HM1bYd

**Comment by N0tMyFaultOG** [comment]
- Don't delete the template.
- Due MMO* plugins being closed source premium you will need to ask them for support.

**Comment by BearLeonLight** [comment]
The official responded, you can add this to the precautions, and change the plugin.yml file in the MMOItems.jar when installing MMOCORE and MMOITEM at the same time.
The content of the change can be solved by changing the MMOCORE in softdepend: to depend:
He said it was a Bukkit problem. ,

**Comment by MattBDev** [comment]
> The official responded, you can add this to the precautions, and change the plugin.yml file in the MMOItems.jar when installing MMOCORE and MMOITEM at the same time.
> The content of the change can be solved by changing the MMOCORE in softdepend: to depend:
> He said it was a Bukkit problem. ,

That didn't make much sense...
