### ISSUE TITLE
In console shows error

### ISSUE THREAD

**Issue by Fiks75** [IntellectualSites/FastAsyncWorldEdit#866]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/4ce9946829a14ecc8e416e113a0e71a0

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-569;acc8a79     
- Spigot/Paper Version Number (`/version`): Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)     
- Minecraft Version: 1.16.4     

**Describe the bug**
When the player joins the server the console shows an error.
https://pastebin.com/DJef1Usp

**To Reproduce**
1. Run  to 'player join server'

**Plugins being used on the server**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
1.16.4 is no longer supported. Please update your server to 1.16.5
