### ISSUE TITLE
1.16.5 //wand leads to java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by NyCodeGHG** [IntellectualSites/FastAsyncWorldEdit#867]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/4ddcb475f0344e6896c27c787f0a51a3

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):
1.16-569;acc8a79
- Spigot/Paper Version Number (`/version`):
git-Paper-436
- Minecraft Version:
1.16.5

**Describe the bug**

When I try to execute '//wand' (probably other commands too), I get an java.lang.StringIndexOutOfBoundsException in chat.

**To Reproduce**
1. Execute `//wand` in chat

**Plugins being used on the server**
- FAWE
- LuckPerms
- Netherboard
- Vault
- Selfwritten Lobby Plugin

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
Could you try disabling persistent brushes?

**Comment by NyCodeGHG** [comment]
Throws the same error

**Comment by N0tMyFaultOG** [comment]
Use Java 11

**Comment by NyCodeGHG** [comment]
Also the same error with Java 11.

**Comment by N0tMyFaultOG** [comment]
Cannot replicate it is then.
