### ISSUE TITLE
#Biome and $ pattern are not working

### ISSUE THREAD

**Issue by PhilippUlti** [IntellectualSites/FastAsyncWorldEdit#869]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/eeaf26724fa34703b46dcd3cc50c2084

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     Bukkit-Official(1.16-560;6895fe3)
- Spigot/Paper Version Number (`/version`):     git-Paper-434
- Minecraft Version: [e.g. 1.16.5]     1.16.5

**Describe the bug**
The #biome and thereby the $ pattern is not working correctly

**To Reproduce**
1. select a brush (surface, sphere) with the $ or #biome pattern
2. try to use the brush
3. see the error in the console

**Plugins being used on the server**

Arceon, Builders-Utilities, BungeeTabListPlus, Essentials, FastAsyncWorldEdit (WorldEdit), goBrush, goPaint, HeadDatabase, Hyperverse, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoidGenerator, VoxelSniper, WorldGuard

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
You need to update FAWE

**Comment by N0tMyFaultOG** [comment]
Don't tick "I made sure I am using an up-to-date version of FastAsyncWorldEdit for 1.16.5" if you didn't really bother to check.
