### ISSUE TITLE
Chunkreloading is needed when using a biome brush

### ISSUE THREAD

**Issue by PhilippUlti** [IntellectualSites/FastAsyncWorldEdit#870]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/eeaf26724fa34703b46dcd3cc50c2084

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     Bukkit-Official(1.16-569;acc8a79)
- Spigot/Paper Version Number (`/version`):     git-Paper-434
- Minecraft Version: [e.g. 1.16.5]     1.16.5

**Describe the bug**
If you are using a brush that contains the pattern #biome, you need to refresh your chunks by either rejoining or flying out of your chunk scope and back into it

**To Reproduce**
1. Run a brush using the #biome pattern
2. See that nothing changes at all
3. Use one of the two ways to see the changes you made by using the brush

**Plugins being used on the server**

Arceon, Builders-Utilities, BungeeTabListPlus, Essentials, FastAsyncWorldEdit (WorldEdit), goBrush, goPaint, HeadDatabase, Hyperverse, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoidGenerator, VoxelSniper, WorldGuard

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by libraryaddict** [comment]
This is still an issue in the latest builds.

**Comment by dordsor21** [comment]
This seems to have been fixed.
