### ISSUE TITLE
Unable to use //history distr and //rollback

### ISSUE THREAD

**Issue by KatanaMajesty** [IntellectualSites/FastAsyncWorldEdit#871]
**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/dcfde0d203e048c197399056f1853c65

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-569;acc8a79
- Spigot/Paper Version Number (`/version`): git-Paper-436 (MC: 1.16.5) 
- Minecraft Version: [e.g. 1.16.5] 1.16.5

**Describe the bug**
cannot rollback because the //rollback command seems not to work. When trying to enter //history distr and rollback via information in /inspect that don't fix the problem as the console throws the error that is attached above.

**To Reproduce**
1. Run '/inspect' on a tool
2. Click on a block to get info about changes
3. Click on a change that needs to be rolled back
4. Click on "history distr" text in chat to execute a //history disrt command
4. See error in console

**Plugins being used on the server**
Plugins (15): AntiExplosion*, AutoMessager, BetterWhitelist*, CleanMotD*, CoreProtect, EntityTrackerFixer, FastAsyncWorldEdit (WorldEdit), goBrush, LuckPerms, Maintenance, NoPortals, SAML, Spartan, SpectatorMode, TAB

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Fixed in 861fb45e5c8d3c82a0d9fdb270f8ebe3ebbafac4
