### ISSUE TITLE
Lag the server out not sure why

### ISSUE THREAD

**Issue by DoogiePC** [IntellectualSites/FastAsyncWorldEdit#872]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
https://athion.net/ISPaster/paste/view/abea4f1a6dd245a590d882117074c3e2

**/fawe debugpaste**:

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):  FAWE-567   
- Spigot/Paper Version Number (`/version`):     1.16.5 paper-418
- Minecraft Version: [e.g. 1.16.5]     1.16.5

**Describe the bug**
Randomly the server seems to start lagging where no commands can be run and nothing works and I end up having to kill the server because its been frozen for so long

**To Reproduce**
no clue

**Plugins being used on the server**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
It's because your DoogiePC. That's why. 🤣😜

**Comment by dordsor21** [comment]
a /fawe threads and a /timings paste would be useful. You've not given any information about the lag itself (not even a TPS...)

**Comment by DoogiePC** [comment]
> a /fawe threads and a /timings paste would be useful. You've not given any information about the lag itself (not even a TPS...)

Kinda impossible to do that when the entire server is frozen completely

**Comment by dordsor21** [comment]
What is there to suggest it's a FAWE issue?

**Comment by DoogiePC** [comment]
> What is there to suggest it's a FAWE issue? The server "freezing" should be followed by a force-stop by the paper watchdog, which would show the current threads and their statuses.

My watchdog never seems to stop it. I've left it overnight sometimes and its still been stuck online

**Comment by MattBDev** [comment]
@DoogiePC I see you didn't like my joke. ☹

**Comment by NotMyFault** [comment]
If you can provide the information requested, feel free to reopen the issue.
