### ISSUE TITLE
Crash for unknown reasons [told to submit it here]

### ISSUE THREAD

**Issue by WalrusSlayer** [IntellectualSites/FastAsyncWorldEdit#873]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:
http://athion.net/ISPaster/paste/view/0ed128b61e3d487cb194aeb4adafd39c
**Required Information**
- FAWE Version Number (
![image](https://user-images.githubusercontent.com/40503028/105285501-84fd4900-5b82-11eb-9722-67ca4a3cddc6.png)
):     
- Spigot/Paper Version Number (`/437`):     
- Minecraft Version: [1.16.5] 

**Describe the bug**
Crashes the server. Here is the log:
https://paste.gg/p/Walrus2020/22d45a17169b40b6b17262b39af25874

**To Reproduce**
No idea. Jury is still out on if it even happens again, and if it does, I will reply here.

**Plugins being used on the server**

![image](https://user-images.githubusercontent.com/40503028/105285594-b37b2400-5b82-11eb-83ad-6f4f21600bf5.png)
Also, AnimatedSidebar, and antiRedstoneClock
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
Update Fawe and disable the optimized clipboard in config.yml

**Comment by WalrusSlayer** [comment]
> Update Fawe and disable the optimized clipboard in config.yml

Where is optimized clipboard? I can't find it anywhere. Thanks!
