### ISSUE TITLE
FAWE Bug

### ISSUE THREAD

**Issue by soyelraul** [IntellectualSites/FastAsyncWorldEdit#883]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

[Server thread/INFO]: uSkyBlock depends on FastAsyncWorldEdit >= v1.16.1 but only v1.16-579;16f72d1 was found!

**/fawe debugpaste**:

**Required Information**
[Server thread/INFO]: This server is running Paper version git-Paper-443 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)   
USkyBlock version 2.8.10

**Describe the bug**
It is not creating the skyworld worlds because it does not detect the correct version of FAWE.

**To Reproduce**
1. Run Server

**Plugins being used on the server**

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
Report that to `uSkyBlock`. They are checking for an invalid version that does not exist.
