### ISSUE TITLE
schematic past poly

### ISSUE THREAD

**Issue by Hij310** [IntellectualSites/FastAsyncWorldEdit#892]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:  https://athion.net/ISPaster/paste/view/d8e384f3008541a49ec747c44ad9fbd0

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):  1.16-587:a13e43f
- Spigot/Paper Version Number (`/version`):  git-Paper-457
- Minecraft Version: 1.16.5

**Describe the bug**
Once you get a poly schematic and you try to past it effect it also the other blocks that are not in the poly.
https://i.imgur.com/mpQGOMM.jpg

**To Reproduce**
1. Run //sel poly
2. Left mouse button on the ground.
3. Walk a bit to the right and right mouse button on the ground
4. Walk back a little and put the right mouse button on the floor again
5. Run //expand vert
6. Run //copy
7. Run //schematic save Test
8. Run //schematic load Test
9. Fly somewhere
10. Run //past

**Plugins being used on the server**

Plugins (1): FastAsyncWorldEdit (WorldEdit)

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
That's how schematics are designed. The format designates a schematic must be cuboidal. You can paste without pasting air with the -a switch.
