### ISSUE TITLE
//regen fails due async catching been on chunk entity add/remove

### ISSUE THREAD

**Issue by LaurenceBarnes** [IntellectualSites/FastAsyncWorldEdit#896]
**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/451bb19d003843d29c9d41b55492fd32

**another attempt with FAWE-591**: https://pastebin.com/4Gjvpzan

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 587-591   
- Spigot/Paper Version Number (`/version`): Tuinity-183 
- Minecraft Version: 1.16.5    

**Describe the bug**
//regen doesn't work and spits out an error in console

**To Reproduce**
1. Mark pos1 and pos2
2. do //regen
3. See error in console

**Plugins being used on the server**
1L1D, BetterGiants, BKCommonLib, BlockLocker, Core, CoreProtect, CustomCommands, DeadChest, dynmap*, Enchantments_plus, Essentials, EssentialsGeoIP, FastAsyncWorldEdit (WorldEdit), GSit, HolographicDisplays, ItemJoin, ItemSlotMachine, LevelledMobs, LibsDisguises, LightCleaner, LuckPerms, Maplands, My_Worlds, MythicMobs, Negativity, OpenInv, PlaceholderAPI, PlugMan, ProtocolLib, PsudoCommand, QuickShop, SilkSpawners, TAB, TCCoasters, TCPShield*, TimeIsMoney*, Train_Carts, UniqueRewards, Vault, ViaBackwards, ViaVersion, Vivecraft-Spigot-Extensions, WorldEditSelectionVisualizer, WorldGuard

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
Can replicate.

**Comment by TheNety** [comment]
Happens also on regular Paper 1.16.5
