### ISSUE TITLE
Edit commands cause ghost blocks and a 16x16x16 lava cube to appear

### ISSUE THREAD

**Issue by lehtoroni** [IntellectualSites/FastAsyncWorldEdit#897]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/ff34bfe693e543709a558e7491ce3e2f

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     `1.16-591;c1f6e43`
- Spigot/Paper Version Number (`/version`):     `git-Paper-457` (1.16.5)
- Minecraft Version: [e.g. 1.16.5]     1.16.5

We tried running the server with both Java 8 and Java 11.

**Describe the bug**
Using FAWE on a specific chunk causes a bunch of ghost blocks and a 16x16x16 cube of lava to appear. This happens when using any commands that modify blocks (paste, set, replace...). Even running `//chunk`, `//copy` and `//paste` causes this to happen.

Leaving and re-joining does not affect the visible bugged blocks, but restarting the server causes them to disappear. The actual edit does not appear and is not saved. Using `//undo` doesn't do anything, and there are no signs of the chunk or world being corrupted.

The problem does not occur when using plain WorldEdit. Disabling other plugins and removing existing FAWE configuration and history folder does not help either. No errors are thrown, and FAWE reports the amounts of blocks affected (a non-zero number) as if the edit was successfully completed.

The specific chunk this happens on our server is (65, 94) and this happens with every player (four players tested this on the same server).

Below are some screenshots.

![image](https://user-images.githubusercontent.com/27345947/106791150-39a46980-665d-11eb-98c1-2e72e74de684.png)

![image](https://user-images.githubusercontent.com/27345947/106791257-5b9dec00-665d-11eb-9362-3562aae3266f.png)

![image](https://user-images.githubusercontent.com/27345947/106791330-74a69d00-665d-11eb-93b2-39f761f6c09a.png)

**To Reproduce**
Since it would be very unpractical to go through all chunks in a world and see if this affects some of them, I don't have a reliable way to tell which chunk(s) the problem appears on. The bug occurs when affecting/modifying a specific chunk with FAWE.

**Plugins being used on the server**
Other plugins didn't affect this issue, but a list of remaining plugins is included in the debug paste: https://athion.net/ISPaster/paste/view/ff34bfe693e543709a558e7491ce3e2f

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Out of curiosity, where you able to replicate that in a different world for example?

**Comment by lehtoroni** [comment]
> Out of curiosity, where you able to replicate that in a different world for example?

I tested this in a different world (on the same server) on a corresponding chunk and was unable to replicate the issue.

However, I tried copying the problematic chunk with different flag combinations, and when using the `-b` flag to copy biomes, the copied selection couldn't be pasted (I don't know if this has anything to do with the actual problem, but I was able to copy and paste other chunks and selections with the biome flag on the same server without any issues).

The thrown error can be found here (as a raw text paste for the sake of readability): [https://lehtodigital.fi/f/RIWWk](https://lehtodigital.fi/f/RIWWk)

This also happens when saving the copied chunk as a [schematic](https://projektit.lehtodigital.fi/foo/_bug2.schem) and then loading and pasting it (again, with the `-b` flag).

I also tried changing the biome of the original chunk, but this just lead back to the original described issue.

**Comment by Tsoccerguy3** [comment]
I tested the //setbiome snowy_taiga for example and its not working .Maybe something is wrong with the biome module 
![2021-02-22_20 07 12](https://user-images.githubusercontent.com/22108822/108791450-1c243a80-754d-11eb-8f46-36212e13ca2c.png)
![2021-02-22_20 20 10](https://user-images.githubusercontent.com/22108822/108791455-1dedfe00-754d-11eb-8b4b-5f6bcc52dc6b.png)
