### ISSUE TITLE
Can't have 2 masks (use /mask and /gmask at the same time)

### ISSUE THREAD

**Issue by MaybeJulien** [IntellectualSites/FastAsyncWorldEdit#898]
**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/1e09d9c8f6b2438f8053a1bd182608cd

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):  FastAsyncWorldEdit-1.16-592

- Spigot/Paper Version Number (`/version`): Paper-457 (1.16.5)
- Minecraft Version: 1.16.5

**Describe the bug**
Users can't use /mask and /gmask to mask two different things for "complex" brush selections (<- for example)

**To Reproduce**
1. Take out a brush (/br sphere stone 4)
2. Place one dirt block and one grass block ontop, the place a dirt block next to the grass block.
3. Run (/mask grass_block) then (/gmask <air)
4.  Click on the block formation you made
5. Voila, now you can see that both the grass and dirt block where made into stone which shouldn't happen since you masked grass blocks

**Comment by Evoloxi** [comment]
can confirm

**Comment by NotMyFault** [comment]
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/509
