### ISSUE TITLE
[Kinda Meta] Incompatibility with areashop, shopchest and others.

### ISSUE THREAD

**Issue by kubo6472** [IntellectualSites/FastAsyncWorldEdit#901]
This is not a bug report about something exactly and explicitly wrong, but there lies an issue, which prevents me from using your plugins with plugins such as areashop and shopchest.
More here: https://github.com/ChestShop-authors/ChestShop-3/issues/180

**Comment by aurorasmiles** [comment]
FAWE does not use a custom Worldguard version, so please provide more information on why something doesn't work. The issue you linked is very old

**Comment by md5sha256** [comment]
Additionally, I should note the original AreaShop plugin as of 2/8/2021 depends on an extremely outdated version of FAWE.
