### ISSUE TITLE
FAWE asked me to provide you with the report version of paper1.16.4

### ISSUE THREAD

**Issue by suningy** [IntellectualSites/FastAsyncWorldEdit#904]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
https://athion.net/ISPaster/paste/view/773cc282d8c94bf39cbdecd63442a2d5

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/773cc282d8c94bf39cbdecd63442a2d5

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     FastAsyncWorldEdit-1.16-596
- Spigot/Paper Version Number (`/version`):     paper-1.16.4-416
- Minecraft Version: [e.g. 1.16.5]     1.16.4

**Describe the bug**
Unable to use prompt  Please report this error: [See console]
java.lang.NullPointerException: null
I can use commands, but I can't do anything

**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

https://imgchr.com/i/ywQg9e   《—— This is an Upload Picture generated from the drawing bed

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by aurorasmiles** [comment]
Update paper

**Comment by suningy** [comment]
1.16.4-416 in 1.16.4

It's the latest version

**Comment by aurorasmiles** [comment]
The latest build is 466, you are 50 versions behind
