### ISSUE TITLE
FAWE for Nukkit

### ISSUE THREAD

**Issue by HealingArcYT** [IntellectualSites/FastAsyncWorldEdit#909]
**Is your feature request related to a problem? Please describe.**
Why is boy0001`s Version of FAWE for Nukkit nowhere to be found?

**Describe the solution you'd like**
Getting the Source code and I try to fix it if there is anything.

**Describe alternatives you've considered**
Is there any other at least as good nukkit worldeditplugin out there?

**Comment by SirYwell** [comment]
<https://github.com/IntellectualSites/FastAsyncWorldedit-Legacy>
