### ISSUE TITLE
Reduced view and console spam

### ISSUE THREAD

**Issue by THklasen** [IntellectualSites/FastAsyncWorldEdit#920]
I replaced worldedit with FAWE and suddenly I can't see far away thing in any color except gray. 
Plus, my console is being spammed with this

[05:30:37 WARN]: [FastAsyncWorldEdit] Task #13 for FastAsyncWorldEdit v1.16-602;e3ab903 generated an exception
org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement (There are per world view distances though!)

And this 

[05:32:36 ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v1.16-602;e3ab903
org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement (There are per world view distances though!)

Here is my startup log
https://haste.athion.net/ivibitofij.md

**Comment by NotMyFault** [comment]
Not a FAWE issue. Paper does not support per-player view distances yet.
