### ISSUE TITLE
Can't //set

### ISSUE THREAD

**Issue by Spyroclub1** [IntellectualSites/FastAsyncWorldEdit#925]
**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):  19.07.12-5cc5ce5-1277-22.3.0  
- Spigot/Paper Version Number (`/version`): 1.8.8    
- Minecraft Version: [e.g. 1.8.8]     

When I try to do //set after selecting regions it goes "Your WorldEdit action was canceled: No allowed region (bypass with /wea or disable 'region-restrictions' in config.yml)"

**Comment by NotMyFault** [comment]
That version is no longer supported.
