### ISSUE TITLE
Command Brushes not work

### ISSUE THREAD

**Issue by blakedj012** [IntellectualSites/FastAsyncWorldEdit#926]
No matter what I type, for example: 

/br command /flora or /br command //flora (this is how it works with the 1.12.2 version of Fawe) nothing works.

It is also not possible to enter anything after a command, for example:

/br command //flora 5 an integer value, then the command does not work at all.

**Comment by LaurenceBarnes** [comment]
You simply skipped the whole format template lmao

**Comment by NotMyFault** [comment]
Don't delete the template. It exists for a reason, which may not to be deleted.

**Comment by LaurenceBarnes** [comment]
Yeah if the dude followed it, you'd have enough info to help. This way it is just so random

**Comment by blakedj012** [comment]
Exactly and that's why it's not a mistake? 
That's why you can't try it out on your test server? 
That's why it's closed here? 
Total lostyboys!

**Comment by blakedj012** [comment]
Be glad that bugs are reported for your Lostplugin!
