### ISSUE TITLE
Replacing redstone blocks near a lamp will cause client crash

### ISSUE THREAD

**Issue by Malachiel87** [IntellectualSites/FastAsyncWorldEdit#928]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

https://athion.net/ISPaster/paste/view/c70177379be94ba2949c9de745d7dc0a

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-606:e550189
- Spigot/Paper Version Number (`/version`):     - 
![image](https://user-images.githubusercontent.com/3611852/108640709-88defc80-749b-11eb-8d37-a00ba5d4e7ee.png)

- Minecraft Version: [e.g. 1.16.5]     1.16.5

**Describe the bug**
Client crashe on certain block changes like lamps+redstone, there are more combination to crash in same way

**To Reproduce**
1 Place a lamp
2 place a  redstone block next to it
3 use //pos1 and //pos2 on redstoneblock and //Set air or another material
4 all clients close to it will crash with these motivations:
Malachiel lost connection: Internal Exception: java.lang.ArrayIndexOutOfBoundsException: Index 20466 out of bounds for length 17112
DoNotConsiderMe lost connection: Internal Exception: java.lang.ArrayIndexOutOfBoundsException
**Plugins being used on the server**
 Plugins (37): ArmorStandTools, BanItem, Builders-Utilities, ChatControl, CMI, CMILib, CMIPaperLib, CoralStay, DiceFurniture, Elevator, FastAsyncWorldEdit (WorldEdit), frConomy, FurnitureLib, HeadDatabase, LegacyChest, LibsDisguises, LPX*, LuckPerms, MarriageMaster, MiniaturePets, Nicky*, Panilla, PlaceholderAPI, Plan, PlotSquared, ProtectionLib*, ProtocolLib, ProtocolSupport, SafeTrade, SimpleLay, Skellett, Skript, SmartSignEditor, spark, Swapper*, Vault, VoxelSniper

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by LaurenceBarnes** [comment]
I cannot reproduce that error, neither with vanilla client, nor my fabric client.
There are some plugins though on that list that I'd overthink using if I were you, especially CMI.
Try using Tuinity.

**Comment by Malachiel87** [comment]
i attached here the plot where is happening this

[crashplot.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6018791/crashplot.zip)

**Comment by NotMyFault** [comment]
I'm not able to replicate that, retry without plugins to find the culprit in your setup.

**Comment by Malachiel87** [comment]
you tried to replicate using that schematica? it happen just in that plot
