### ISSUE TITLE
TerraformGenerator is not supported when using //regen

### ISSUE THREAD

**Issue by sanderdatema** [IntellectualSites/FastAsyncWorldEdit#934]
**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/2031168358dd4b56b8395272b7416541

**Required Information**
- FAWE Version Number: 1.16-609;7696bb9
- Spigot/Paper Version Number: git-Paper-492 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Minecraft Version: 1.16.5

**Describe the bug**
[TerraformGenerator](https://github.com/Hex27/terraformgenerator) is not supported when using `//regen`.

**To Reproduce**
1. `//chunk`
2. `//regen`
3. See error `Unsupported generator type org.terraform.v1_16_R3.NMSChunkGenerator`

**Plugins being used on the server**
FastAsyncWorldEdit (WorldEdit), TerraformGenerator

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report: There is #853, but it was not accepted because the platform was not supported. However, I have the exact same error on a supported platform.
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
`//regen` only supports vanilla worlds, any third party support is up to third party implementations.
