### ISSUE TITLE
Block Rollback Broken

### ISSUE THREAD

**Issue by Semisol** [IntellectualSites/FastAsyncWorldEdit#935]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/008e841f796d45c79001de214ac45e5c

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16-610;bc686a6 
- Spigot/Paper Version Number (`/version`): [02:37:02 INFO]: This server is running Tuinity version git-Tuinity-"1d169e7" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Minecraft Version: [e.g. 1.16.5] 1.16.5

**Describe the bug**
Block data does not restore

**To Reproduce**
1. Do a //sphere on an area
2. //undo it
3. Blocks lose their block entity data, even if they are in the history NBT files.
**Plugins being used on the server**

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Semisol** [comment]
Also this is affecting my server, so if could be fixed soon it would be great.

**Comment by NotMyFault** [comment]
I'm unable to replicate the issue described being reproduced with the steps listed.

**Comment by Semisol** [comment]
I do not know how this happened.
