### ISSUE TITLE
Undo is broken

### ISSUE THREAD

**Issue by GargatheOro** [IntellectualSites/FastAsyncWorldEdit#942]
**Server Implementation**

Paper

**Server Version**

1.16.5

**Describe the bug**

If I make an edit, and undo it, undo will either say there is nothing to undo, or it will say it undid it without actually undoing it. The same goes for redoing.

**To Reproduce**

1. Make an edit
2. Undo it

**Expected behaviour**

I expected it to actually undo my edit.

**Screenshots / Videos**

https://imgur.com/a/33fQm8l

^ That is a gallery

**Error log (if applicable)**

1: https://haste.athion.net/wayucipagi.shell  2: https://haste.athion.net/ecodeponel.rb

**Fawe Debugpaste**

https://athion.net/ISPaster/paste/view/87e19782e60d4ec38d170b1d68e6bf8c

**Fawe Version**

614

**Comment by RedstoneFuture** [comment]
I used "//undo" today with the last FAWE version (1.16-614) on a 1.16.5 server (PaperMC), and it works. So maybe it has problems in a specific situation,

**Comment by GargatheOro** [comment]
> I used "//undo" today with the last FAWE version (1.16-614) on a 1.16.5 server (PaperMC), and it works. So maybe it has problems in a specific situation?

It does it every time. It persists through updates, several block types, brush operations, doesn't matter.

**Comment by LaurenceBarnes** [comment]
which paper build are you two using? Maybe @GargatheOro try the same build as @RedstoneFuture to make sure that it is not it 
On the most recent Tuinity-build I have no problem at all, but it did not yet upstream the recent paper changes.

**Comment by GargatheOro** [comment]
> which paper build are you two using? Maybe @GargatheOro try the same build as @RedstoneFuture to make sure that it is not it
> On the most recent Tuinity-build I have no problem at all, but it did not yet upstream the recent paper changes.

I deleted my config file and now it works all of a sudden.

**Comment by LaurenceBarnes** [comment]
Lmao
