### ISSUE TITLE
Mobs will not burn after undoing a block placement

### ISSUE THREAD

**Issue by Arrowheads844** [IntellectualSites/FastAsyncWorldEdit#944]
**Server Implementation**

Paper

**Server Version**

1.15.2

**Describe the bug**

If you place blocks 3 or more blocks above the ground using FAWE, then undo the operation, mobs will no longer burn in the daylight where the blocks were placed. Even after restarting the server, rolling back chucks (CoreProtect), and attempting to manually place and break blocks in the area, there are still "phantom blocks" that are preventing mobs from burning in daylight, even though there are no blocks there and the operation was "undone."

**To Reproduce**

1. Place blocks ~ ~3 ~ or higher
2. Undo Operation
3. mobs no longer burn under where blocks were placed then undone

**Expected behaviour**

Mobs burn in daylight after undoing the operation.

**Screenshots / Videos**

_No response_

**Error log (if applicable)**

_No response_

**Fawe Debugpaste**

https://athion.net/ISPaster/paste/view/a9cf7e09cf7f4dfa80942d3d2cf118fa

**Fawe Version**

FAWE 19.11.13-5505943-1282 by Empire92

**NOTE: The server says it is running 1.12, however, it is running paper 1.15.2**

**Comment by aurorasmiles** [comment]
You are using an unsupported version of FAWE and Paper, please update.
