### ISSUE TITLE
Option to disable global tool commands

### ISSUE THREAD

**Issue by 0x5c** [IntellectualSites/FastAsyncWorldEdit#945]
**What feature do you want to see added?**

The ability to disable global tool commands (`/info` etc), in part to remove conflicts with other plugins. Those should only be accessible as subcommands of `/tool`.

**Are there any alternatives?**

- Not using FAWE/WE: Not possible
- Overriding commands with `commands.yml`: Doesn't really fix the problem and causes side-effects

**Comment by NotMyFault** [comment]
If commands are conflicting with other plugins, simply switch to namespaced commands.

**Comment by 0x5c** [comment]
That does not allow me to guarantee that the player-facing command that FAWE conflicts with actually get's awarded the command registration. It's a mostly random coinflip on server startup.

As the FAWE user, I couldn't care less about the ability to run `/info` instead of `/[fawe namespace]:info` or `//info`; I'm the admin and complicated commands shouldn't be a problem for me.
The problem is that I can't reasonably expect normal players to run `/[namespace of other plugin]:info` to get basic info about the server. Using the namespaced version in a commands.yml alias "works", until you realise that your players are being told to run the full namespaced command to get the second page.

This is especially painful since upstream WorldEdit [deprecated global tool names](https://worldedit.enginehub.org/en/latest/commands/?highlight=deprecated#command-/info) and FAWE [did it too](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/6476345e449a958f9a3d86db9e774f5a5d68982d/worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolCommands.java#L107) two years ago.

This is about giving server admins the option to disable very longstanding command conflicts caused by FAWE.
