### ISSUE TITLE
Super Pickaxe can destroy LWC

### ISSUE THREAD

**Issue by mare-on** [IntellectualSites/FastAsyncWorldEdit#948]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

By using super pickage you can destroy locked chests and other things by LWC.

### To Reproduce

Download FAWE and LWC.
Put a chest on ground and lock it.
Activate super pickage and dig.

### Expected behaviour

Add support for LWC to prevent destroying of locked things.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6c2f883cca724e88a4a73bed8cca6b37

### Fawe Version

1.16-604;14c0d4a

**Comment by MattBDev** [comment]
@mare-on Considering LWC stopped development years ago, we need the specific link the version of LWC being used. Considering this issue is a few months old, I'll wait a while for a reply. If I don't hear back I'll have to close this issue.
