### ISSUE TITLE
//undo and //redo still work on deleted PS plots

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#949]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

`//redo` still works on recently deleted plots, even if `//Set` doesn't work

### To Reproduce

1. Claim a plot
2. Use `//set` on the plot (I set a block of stone and then set it back to air)
3. Delete the plot
4. After the deletion completed, use `//undo` (`//redo` can also be used). The blocks should reapear, even if You can't use `//set` anymore.

### Expected behaviour

The blocks should obviuosly don't get placed. The Plotsquared restrictions get ignored with `//undo`.

### Screenshots / Videos

https://user-images.githubusercontent.com/46501008/110026631-29051300-7d31-11eb-9a67-8c4a84b3c9c7.mov

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7a0707b1fd254656bf75faca00671e44

### Fawe Version

FastAsyncWorldEdit version 1.16-614;6bd866b

**Comment by RedstoneFuture** [comment]
I think it's still a problem.

**Comment by Xaver106** [comment]
I can confirm this is still an issue on FastAsyncWorldEdit-673
paper: git-Paper-651 (MC: 1.16.5)
PS: PlotSquared-5.13.11-Premium

I used the same setup as in the video with the exact same results.

**Comment by RedstoneFuture** [comment]
#activity

**Comment by Xaver106** [comment]
Still happening on Version: PlotSquared-6.0.7-Premium
Same procedure as stated above with the same result.

**Comment by MattBDev** [comment]
> Still happening on Version: PlotSquared-6.0.7-Premium
> Same procedure as stated above with the same result.

I reopened the issue.
