### ISSUE TITLE
An unexpected error while handling a WorldEdit command

### ISSUE THREAD

**Issue by cyanid2489563** [IntellectualSites/FastAsyncWorldEdit#952]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

can't use command //copy

### To Reproduce

1. //copy

### Expected behaviour

copy blocks

### Error log (if applicable)

https://haste.athion.net/yategidage.bash

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4ce279e281c84092b281884063e3799e

### Fawe Version

FastAsyncWorldEdit-1.16-615

![image](https://user-images.githubusercontent.com/19309564/110210307-04916e00-7ecc-11eb-87b5-92823fbede18.png)

**Comment by aurorasmiles** [comment]
Update Spigot/Paper, you are running an outdatet version. Don't lie about your version in the issue template.
