### ISSUE TITLE
Replace bug

### ISSUE THREAD

**Issue by B1gLev** [IntellectualSites/FastAsyncWorldEdit#954]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When I type //replace /[0d] [10d] gold_block it will be all gold

### To Reproduce

//replace /[0d] [10d] gold_block

### Expected behaviour

It turns it all into gold

### Screenshots / Videos

https://i.imgur.com/owQx5la.mp4

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8f801d0d9ba34d6b8ee9eff573551e70

### Fawe Version

Fawe version 1.16-616;99ea64f

**Comment by SergiSvK** [comment]
The same problem happens to me

https://athion.net/ISPaster/paste/view/0d2bb4bbcc2945f496e508eabb50a70c

**Comment by dordsor21** [comment]
Duplicate of #727
