### ISSUE TITLE
Ghostblocks in Schem after Explosion

### ISSUE THREAD

**Issue by Waifjyux** [IntellectualSites/FastAsyncWorldEdit#956]
### Server Implementation

Paper

### Server Version

1.15.2

### Describe the bug

I constantly get GhostBlocks when a block gets destroyed by an explosion if the blocks were pasted via Fawe

### To Reproduce

1. Paste a big pile of blocks
2. Prime a TNT
3. Some of the destroyed Blocks apear as GhostBlocks

### Expected behaviour

I expected that the TNT would destroy the blocks without causing GhostBlocks

### Screenshots / Videos

https://prnt.sc/10feqtj

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8ae5f43dde824b5cae5e988891c277dd

### Fawe Version

FastAsyncWorldEdit-1.16-615.jar

**Comment by MattBDev** [comment]
Do the "ghost blocks" still appear if you log out and log back in to the server?

**Comment by FlyLik3Moeve** [comment]
Yeah they do.
