### ISSUE TITLE
//history rollback

### ISSUE THREAD

**Issue by RedTurtle52** [IntellectualSites/FastAsyncWorldEdit#958]
### What feature do you want to see added?

Hello, today I used //history rollback - u ... -r ... -t ... and what I will describe below has happened.

### Are there any alternatives?

//history import
//history rollback -u *** -r 100 -t 10h
//history rollback -u *** -r 1000 -t 10h
//history rollback -u *** -r 10000 -t 10h

Hello, both acoron and today it happened to me : https://imgur.com/a/JHC3uEz how, how.. But also to make a sdu tinge, because it happened that he would make a decision. Rollback was from the fact that one eventer that he was fired from AT decided that all that was on him to give //set 0 .. On discord, and also on what he wrote them - unfortunately, what happened was how to get right to keep everything in order. That's all, thank you

- https://imgur.com/a/JHC3uEz

**Comment by NotMyFault** [comment]
This is an issue so please select the bug report template.
