### ISSUE TITLE
//history not working as expected

### ISSUE THREAD

**Issue by RedTurtle52** [IntellectualSites/FastAsyncWorldEdit#959]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I gave the orders they gave me on the discord (someone from staffteam) of course it's not their fault. But I'd like to ask how to handle this, but I guess it's too late. Now I'm going to explain it pretty quickly - Yesterday the eventer was kicked out of AT and he couldn't think of anything better than to destroy all the events using //Set 0 , so I went to ask DC how to deal with this. I did what they said, and here's what happened.

### To Reproduce

1, ''//history import''
2, ''//history rollback -u *** -r 100 (after 1000, 100000) -t 8h''
3, ''//confirm''

### Expected behaviour

I expected everything to return to its original state, not to this one, which will be below.

### Screenshots / Videos

https://imgur.com/a/JHC3uEz

### Error log (if applicable)

nothing

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/63f009c6ea994b4c983728a2c0d2fb1a

### Fawe Version

https://imgur.com/a/jnMign4

I've described everything that's happened more. I don't think there's any need to write more.

**Comment by NotMyFault** [comment]
It appears the rollback logging is currently not properly implemented comparing to other versions.
