### ISSUE TITLE
cannot use /restore

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/FastAsyncWorldEdit#96]
https://gyazo.com/b42eac3c6fa660ce09c143377471d075

**Comment by boy0001** [comment]
Do you know if this occurs with normal WorldEdit as well?

**Comment by bloggy** [comment]
It works fine with WorldEdit

**Comment by PhanaticD** [comment]
bump

**Comment by bloggy** [comment]
I think FAWE needs more devs. Bugs are slowly being solved.

**Comment by MattBDev** [comment]
It's an open source project. Feel free to step in and submit a pull request at any time.

**Comment by PhanaticD** [comment]
Was this fixed or just the issue closed

**Comment by aurorasmiles** [comment]
This issue is invalid and over 2 years old. If you still have the issue please open a new issue following the template, otherwise we can't help.
