### ISSUE TITLE
Worlguard permission message on PS world

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#960]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Worldguard no permission message on a PlotSquared world, even if using FAWE on own Plot.

### To Reproduce

1. Use any command that is edditing the world (Tested with `//set` and `//replace`)
2. With the complete message you also get a missing permission message for worldguard (See image below)

### Expected behaviour

Only the operation complete message should appear.

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/46501008/110667054-293a5e00-81ca-11eb-8606-58eed2a35a20.png)
Using `//set` after setting the positions

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1026685f0dbb4335b030a9ad75059024

### Fawe Version

FastAsyncWorldEdit version 1.16-614;6bd866b

**Comment by RedstoneFuture** [comment]
I try to "fix" it with giving of `fawe.worldguard` (and `fawe.worldguardextraflags`) permission for all player in the plotworld. But maybe a better prioritization between PlotSquared and WorldGuard restriction would be useful.

**Comment by RedstoneFuture** [comment]
It's still a behavior to validate.

**Comment by RedstoneFuture** [comment]
Not fixable with "priority: -2147483648" in the world-config of WorldGuard.
