### ISSUE TITLE
Changing the wand item causes errors

### ISSUE THREAD

**Issue by AMDBartek** [IntellectualSites/FastAsyncWorldEdit#961]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When changing your wand to a different item (in my case a blaze rod) some errors will occur as shown in the error log.

### To Reproduce

1. Go to the config-legacy.yml file and change your wand item
2. Start the server
3. Execute //wand
4. There will be an error in the console if you have changed your wand item

### Expected behaviour

For the user to be able to change the wand item without an error occurring.

### Error log (if applicable)

https://haste.athion.net/ozofocokic.sql

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f750aa140566498fa423208ce8d87d8c

### Fawe Version

FastAsyncWorldEdit version 1.16-620;cde52f9

**Comment by AMDBartek** [comment]
As it turns out, this is a problem with the navigation wand item, when you set this to an existing item in the game it works but if you try to disable it then this error will occur.

What could I set this item to so that the navigation wand will be disabled?

**Comment by NotMyFault** [comment]
-1 or any other item; minecraft:null is invalid and will therefore not work.

**Comment by AMDBartek** [comment]
@NotMyFault `-1` is the first thing that I tried, this produced the error shown in my issue (https://haste.athion.net/ozofocokic.sql)

**Comment by NotMyFault** [comment]
> @NotMyFault `-1` is the first thing that I tried, this produced the error shown in my issue (https://haste.athion.net/ozofocokic.sql)

Then use any other material, or even more simple; remove the permission to the command.

**Comment by AMDBartek** [comment]
@NotMyFault Will removing the permission disable this all together (including messages in chat)?

**Comment by NotMyFault** [comment]
> @NotMyFault Will removing the permission disable this all together (including messages in chat)?

Yes, that is how permissions work.

**Comment by AMDBartek** [comment]
I should've clarified, will it show a message like "you are lacking permission node: permission.node"?

**Comment by NotMyFault** [comment]
Yes it will.

**Comment by AMDBartek** [comment]
Is there any way I could have the message not show?

**Comment by NotMyFault** [comment]
Void it from the `strings.json`
