### ISSUE TITLE
Chunk issues

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#962]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

*Can only reproduce on server.redstoneworld.de at the moment!*
We also don't know yet, when the bug occures/starts.
When it occures, all FAWE actions (`//set`, `//undo`, `//place`, `//replace` and every actions taken by other plugins, like Plotsquared) that edit the world can cause subchunk bugs (16x16x16) blocks setting the air around to a random block, mostly the block that is supposed to be set, sometimes another, we als don't know which one yet.
We had it happen several times in the last week.
Chunk bugs ignore WorldEdit restrictions, so other Plots can be effected.

### To Reproduce

We currently don't know how to really reproduce it. Will update when we have more infos.

### Expected behaviour

No Chunk bugs occuring when using FAWE.

### Screenshots / Videos

![2021-03-08_15 52 41](https://user-images.githubusercontent.com/46501008/110771319-a6151880-825a-11eb-9d60-4a3efa96f9b4.png)
![2021-03-08_15 58 04](https://user-images.githubusercontent.com/46501008/110771336-ab726300-825a-11eb-8118-e94148097032.png)
both screens are from `/p clear` on a PS world

### Fawe Debugpaste

Not able to, due to data protection reasons (All relevant errors will be posted)

### Fawe Version

FastAsyncWorldEdit version 1.16-617;5acd1d7

(Sorry for the little info, but we are still investing the issue. we will update when we have new info)

**Comment by QuickWrite** [comment]
This bug has happened several times on the server, without us being able to find a connection in the times.
This bug happened in all commands where blocks were placed, modified, etc.

I think that the subchunks filled with blocks always take the block that is most northwest, which is not air.

**Comment by Xaver106** [comment]
The Bugs are not visual. The blocks stay, even after a restart. They only replace air, but this can still destroy plots and hurt server performance, if the bug places blogs, that immediately break and drop items.

**Comment by RedstoneFuture** [comment]
If I'm right, it's sometimes on servers without PlotSquared and WorldGuard too. In PlotSquared worlds the restriction works basically. So if the player have WE permission inside the same chunk, the bug can happen.

**Comment by RedstoneFuture** [comment]
Maybe it was a part of a memory problem. I've re-define the `max-memory-percent: 95` option. Since 2 weeks this bug wasn't happened.
