### ISSUE TITLE
FAWE messes with McMMO

### ISSUE THREAD

**Issue by Pabsb** [IntellectualSites/FastAsyncWorldEdit#967]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Can't use /inspect on mcmmo because fawe keeps overriding when it shouldn't

### To Reproduce

1. Install FAWE
2. Install McMMO
3. Try to /inspect a players stats 
4. Fails

### Expected behaviour

McMMO should take priority and show inspected players stats

### Screenshots / Videos

N/A

### Fawe Debugpaste

N/A

### Fawe Version

FastAsyncWorldEdit-1.16-621

Add option to allow priority for McMMO or to just disable inspect command for FAWE.

**Comment by NotMyFault** [comment]
Use namespaced commands, eg `/mcmmo:<command>`.

**Comment by MattBDev** [comment]
Inspect is a WorldEdit command. Complaining to us is stupid.

**Comment by Pabsb** [comment]
> Inspect is a WorldEdit command. Complaining to us is stupid.

You guys override mcmmo inspect with your own inspect command

**Comment by NotMyFault** [comment]
> > Inspect is a WorldEdit command. Complaining to us is stupid.
> 
> You guys override mcmmo inspect with your own inspect command



> Use namespaced commands, eg `/mcmmo:<command>`.
