### ISSUE TITLE
//stack creating randon blocks

### ISSUE THREAD

**Issue by Lothiredon** [IntellectualSites/FastAsyncWorldEdit#972]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Stacking a selection introduces random blocks. The images below show a slab of light gray concrete where suddenly acacia buttons, planks and air blocks crept into the stack. This was after creating a large region and having to use //confirm.

### To Reproduce

1. Create a selection large selection
2. //confirm
3. Use //stack (unsure whether direction is relevant)

(I have not been able to reproduce the behaviour since but the steps described above were the only commands used prior to the bug occuring)

### Expected behaviour

No random blocks being introduced in the stack.

### Screenshots / Videos

https://media.discordapp.net/attachments/344128526435221505/820365220399546418/unknown.png?width=1248&height=676
https://media.discordapp.net/attachments/344128526435221505/820380283718860820/unknown.png?width=1248&height=676

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5bbecfe8d76e4300b60acb55466aaa65

### Fawe Version

1.16-622;bc64eaf

**Comment by NotMyFault** [comment]
I've not been able to replicate that yet, could you try it in a clean environment with an up to date version of Paper, Fawe without any other plugins?
