### ISSUE TITLE
Add disable commands option

### ISSUE THREAD

**Issue by Pabsb** [IntellectualSites/FastAsyncWorldEdit#973]
### What feature do you want to see added?

Add config option to disable certain commands altogether to prevent conflicts with any plugins using a command with same name/alias 

### Are there any alternatives?

There is no alternative to fix this. Namespace command is not a viable alternative as it opens up a whole slew of issues with players able to bypass command restrictions etc.

Option in config to be able to list what FAWE/WorldEdit commands you want to be disabled.

**Comment by NotMyFault** [comment]
Won't be added.

**Comment by Pabsb** [comment]
Why close this?

**Comment by NotMyFault** [comment]
Outlined on discord.
