### ISSUE TITLE
Weak server cannot handle schematic

### ISSUE THREAD

**Issue by Porkason** [IntellectualSites/FastAsyncWorldEdit#975]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

server crashes when trying to load schem. 

https://pastebin.com/ELe3RAct

### To Reproduce

1. Upload latest FAWE. start server.
2. Upload schem to schematic folder. 
3. Try to load it. 

### Expected behaviour

I expected it to load. 

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f19bfd1e33b14bafb1c3bd7dbdde4c1a

### Fawe Version

	FastAsyncWorldEdit-1.16-622.jar

**Comment by Porkason** [comment]
[Uploading castratingmap4.zip…]()
(schematic)

**Comment by Porkason** [comment]
> > Uploading castratingmap4.zip…
> > (schematic)
> 
> The URL is invalid, yet it appears your server is just overloaded.

Well that is not the case. I tried it with 10gb ram and 12 cores and it still couldn't load nor paste it properly. I believe that it's optimisation for enormous schemes from your part that makes it not possible to load nor paste them. same thing with we.

**Comment by aurorasmiles** [comment]
Just to add: just throwing more RAM at the server doesn't help with stuff like that
