### ISSUE TITLE
Snow/Ice cannot reform naturally after large WorldEdit pasts

### ISSUE THREAD

**Issue by Kakalavala** [IntellectualSites/FastAsyncWorldEdit#977]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Snow and Ice will not reform after a large operation has taken place, I have a screenshot of the ice; I did not take a screenshot of the snow, but it forms in the same way as the ice. It forms to the chunk borders, regardless of changes made in the chunk after the operation took place. I've yet to find any solution besides not having water there at all (or having only ice).

### To Reproduce

In every chunk that I do a large W.E. operation in (i.e. a large selection then //set to something or //replace).

Other than that I'm not entirely sure if you can reproduce it in other means. It's happened a ton of my world but, haven't been able to document the exact steps.

### Expected behaviour

Ice should form around the edge of the lake, and only to about 3-4 blocks out, and snow should fall evenly across all chunks that have a snow biome.

Neither of these are happening.

### Screenshots / Videos

https://i.imgur.com/J9IpN8T.png

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/eb9cb4f7e16d4488839fd7cd2d8a4848

### Fawe Version

FastAsyncWorldEdit version 1.16-595;5f83643

**Comment by LaurenceBarnes** [comment]
I will be so bold and assume it is somewhat related to #881 and #891 and heightmap related? I might be wrong though, but that wouldn't surprise me

**Comment by LaurenceBarnes** [comment]
Also try updating FAWE, just to ensure it hasn't been fixed somehow

**Comment by Kakalavala** [comment]
> I will be so bold and assume it is somewhat related to #881 and #891 and heightmap related? I might be wrong though, but that wouldn't surprise me

That would make sense cause both of those problems are also occurring, whether or not they're related - I'm unsure.

**Comment by LaurenceBarnes** [comment]
So just to ensure, try my workaround for those other issues:
1. Stop your server
2. Replace FAWE with Worldedit
3. Make a platform of stone or other materials above affected areas
4. Do //set 0, removing the platform
5. Rain/Maps/Mob spawning are fixed
6. Check whether it fixes your issue as well

If yes, those are related.

**Comment by Kakalavala** [comment]
> So just to ensure, try my workaround for those other issues:
> 
> 1. Stop your server
> 2. Replace FAWE with Worldedit
> 3. Start the Server again
> 4. Make a platform of stone or other materials above affected areas
> 5. Do //set 0, removing the platform
> 6. Rain/Maps/Mob spawning are fixed
> 7. Check whether it fixes your issue as well
> 
> If yes, those are related.
> 
> EDIT: After that you can switch back to FAWE of course, I also continue to use it despite that issue, since there is a workaround.

Well I'll be, that fixed it.

**Comment by LaurenceBarnes** [comment]
@Kakalavala so my workaround fixed it?
Then @MattBDev this is another one related to #881 , #891 and mobs not spawning due to corrupted heightmaps
