### ISSUE TITLE
Persistent Brushes do not persist

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/FastAsyncWorldEdit#978]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Persistent brushes used to be renamed to the brush type/specification
For example `//br sphere` would rename the brush item "Sphere" in 1.12.2 
However in 1.16.5, `//br sphere` does not rename the item, it stays the same. e.g. a stick simply shows up as a stick.
`persistent-brushes` is set to `true` in config.yml

After logging off, the item is just a regular item when you log back in.

### To Reproduce

Make a brush e.g. `//br sphere`

### Expected behaviour

Item should be renamed to the brush type and have tooltips that show the brush configuration.
Item should also persist after logging off.

### Fawe Debugpaste

https://brew.brdv.coffee/xomihoxebi.hs

### Fawe Version

1.16-625;20424b0

**Comment by TheMeinerLP** [comment]
https://brew.brdv.coffee/xomihoxebi.hs is empty :(

**Comment by OneLiteFeather** [comment]
If you can provide us a not empty debugpaste we would be able to try replicate this issue. If you don't have one to provide us, I would close this issue instead.

**Comment by braceyourself07** [comment]
lol.  considering the original issue was posted in 2021, it's no longer relevant.
