### ISSUE TITLE
//flip up does not place slabs in the proper place

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/FastAsyncWorldEdit#987]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Using //flip works on slabs in every direction except for up/down.  The slabs usually end up in the wrong vertical half.

### To Reproduce

1) Make a build with slabs
2) //copy, //flip up
3) //paste

### Expected behaviour

See screenshots

### Screenshots / Videos

Glitch demonstrated:  https://brdv.coffee/storage/uploads/4/ZaEMbBE8SJmu.png
Normal with regular blocks:  https://brdv.coffee/storage/uploads/4/rkTZGvkBFJQ0.png

### Fawe Debugpaste

No error

### Fawe Version

1.16-625

**Comment by SirYwell** [comment]
Do you know if that worked before? In my recent PR, I needed to touch that code, so I probably broke it.

**Comment by braceyourself07** [comment]
I don't recall. I'm actually not a builder but I own a build server.  So one of the builders on my server reported it.  It was first reported to me in 23 Dec 2020 but I could not duplicate it until one of the builders finally gave me specific instructions on how to reproduce it.

**Comment by SirYwell** [comment]
Okay, sounds like I didn't break it then.
