### ISSUE TITLE
Add thickness modifier to //hcyl

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/FastAsyncWorldEdit#988]
### What feature do you want to see added?

Back in 1.12.2 version of FAWE, you could add a 4th modifier to //hcyl command that would set thickness.
e.g. `//hcyl <block> <radius> <height> <thickness>`
Can this be added back?

### Are there any alternatives?

None that I'm aware

**Comment by LaurenceBarnes** [comment]
Oh that's not possible anymore?

**Comment by braceyourself07** [comment]
A far as I know that is correct.  One of the builders that uses my server says that it hasn't been a thing since the 1.15 version of FAWE came out.

**Comment by dordsor21** [comment]
Duplicate of #753
