### ISSUE TITLE
//br catenary being spammed causes server crash

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/FastAsyncWorldEdit#989]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

When using `//br catenary` and spamming it will cause the server to crash. No error in logs, the server just performs a shutdown.

### To Reproduce

`//br catenary 41 1.2`
Then spam click 10's of times.

### Expected behaviour

Back in 1.12.2 version, you could spam click and it would produce vines without lagging or crashing the server.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a31d757bf7e2428f934b0d8847943498

### Fawe Version

626

**Comment by NotMyFault** [comment]
I can replicate that, it appears something is being locked not supposed to be locked that long.

**Comment by MattBDev** [comment]
We'll need to profile a test server to figure out what is going on to cause a shutdown.

**Comment by dordsor21** [comment]
This seems to have been fixed.
