### ISSUE TITLE
´//paste -o´ issues

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/FastAsyncWorldEdit#990]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Pasting your clipboard at original position (`//paste -o`) after a rejoin will paste at the bottom corner of the 0 0 Chunk. It will paste it, so that the area will sit exactly in the corner (look at photo).

### To Reproduce

1. Use `//copy` or `//cut` to fill your clipboard
2. Rejoin the server
3. Place the clipboard at it's original position with `//paste -o`
4. Th clipboard is placed at the bottom corner of the 

### Expected behaviour

Th clipboard is pasted at the original position, not at a random location.

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/46501008/112374190-1784aa80-8ce2-11eb-83f0-8ba9c30dff32.png)
Copy position on emerald block. Pasted at this location after rejoin

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c72d417e43af41dcb58a804bf7bb9e2b

### Fawe Version

FastAsyncWorldEdit version 1.16-614;6bd866b

**Comment by SirYwell** [comment]
Note for anyone looking into it: DiskOptimizedClipboard doesn't save the absolute minimum point.
