### ISSUE TITLE
Problem when //copy a terrain

### ISSUE THREAD

**Issue by dabou0** [IntellectualSites/FastAsyncWorldEdit#994]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I select the pos 1 and 2, and i try to //copy, it says its too big so i need to //confirm it will give error map failed.

then i tried smaller area and it will say 

### To Reproduce

1. Select //pos1 and //pos2
And try //copy 
It will ask to //confirm
Execute //confirm

Result: It will give error and say to look console

### Expected behaviour

I would be able to copy the selected area

### Error log (if applicable)

https://haste.athion.net/voxasaliva.md

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7059d467ed7b4689b347548e73dba5ed

### Fawe Version

* Bukkit-Official(1.16-635;65067ea)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

Nothing to add.

**Comment by aurorasmiles** [comment]
`Caused by: java.lang.OutOfMemoryError`
Your server ran out of memory. Allocate more RAM or select a smaller area
