### ISSUE TITLE
I used more ram i copied the area, but problem on schem save

### ISSUE THREAD

**Issue by dabou0** [IntellectualSites/FastAsyncWorldEdit#995]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I changed to 5gb Ram, but when after copied it wont save to .schem

### To Reproduce

Select the area
Copy the area (Confirm the copy)
Try saving as schematic

### Expected behaviour

Save the clipboard as .schem

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/0581fec070e64bf9b04ac82937ada93d

### Fawe Version

* Bukkit-Official(1.16-635;65067ea)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by aurorasmiles** [comment]
You need to copy something before saving a schematic. Please join our discord for support, github is not the place for that
